### ISSUE TITLE
Gracefully work around invalid URLs

### ISSUE THREAD

**Issue by hrj** [square/okhttp#1044]
With the default HttpURLStreamHandler, URLs are automatically encoded correctly.
For example, this URL: `http://host/abc|xyz` works fine with the default handler.

But OkHttp throws an exception:

```

java.io.IOException: Illegal character in path at index 15: http://host/abc|xyz
at com.squareup.okhttp.Request.uri(Request.java:65)
at com.squareup.okhttp.internal.http.HttpEngine.networkRequest(HttpEngine.java:579)
at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:212)
at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:420)
at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:371)
at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:466)
```

**Comment by swankjesse** [comment]
I'm punting this to 2.4. The focus of that release will be our own URL API. I think can probably do something that's better-enough from `java.net.URL` and `java.net.URI` that it justifies its own existence.

Handling this kind of thing is just one example.

**Comment by swankjesse** [comment]
HttpUrl has this now. We still need to offer HttpUrl as a mechanism that you can use with the rest of OkHttp.

**Comment by swankjesse** [comment]
I'm going to actually wire this into HttpEngine in 2.5.
