### ISSUE TITLE
cancel a async call will cause FATAL EXCEPTION

### ISSUE THREAD

**Issue by qqonline** [square/okhttp#1049]
the code below will case a FATAL EXCEPTION:

```
    Call theCall = null;
    byte[] okHttpBuf = new byte[4096];
    OkHttpClient client = new OkHttpClient();

    Callback callback = new Callback() {

        @Override
        public void onFailure(Request request, IOException e) {
            // TODO Auto-generated method stub
            Log.d(TAG, "onFailure");
        }

        @Override
        public void onResponse(Response response) throws IOException {
            // TODO Auto-generated method stub
            Log.d(TAG, "onResponse");

            Log.d(TAG, "response.isSuccessful()=" + response.isSuccessful());
            ResponseBody respBody = response.body();
            BufferedInputStream bis = new BufferedInputStream(respBody.byteStream());

            int len = 0;
            while ((len = bis.read(okHttpBuf)) > 0) {
                Log.d(TAG, "read len: " + len);
            }
        }

    };

    private void __testOkHttp() {
        if (theCall != null) {
            theCall.cancel();
            theCall = null;
            return;
        } else {
            String strUrl = "http://cdn1.evernote.com/win5/public/Evernote_5.6.4.4632.exe";
            theCall = client.newCall(new Request.Builder().tag(System.nanoTime()).url(strUrl).build());
            theCall.enqueue(callback);
            return;
        }
    }
```

exception info:

```
FATAL EXCEPTION: OkHttp Dispatcher
Process: com.ishareok.isharekitdemo, PID: 14453
java.lang.RuntimeException: java.net.SocketException: Socket closed
    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:153)
    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:811)
Caused by: java.net.SocketException: Socket closed
    at libcore.io.Posix.recvfromBytes(Native Method)
    at libcore.io.Posix.recvfrom(Posix.java:141)
    at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
    at libcore.io.IoBridge.recvfrom(IoBridge.java:506)
    at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
    at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
    at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
    at okio.Okio$2.read(Okio.java:136)
    at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
    at okio.RealBufferedSource.read(RealBufferedSource.java:50)
    at com.squareup.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:456)
    at okio.RealBufferedSource$1.read(RealBufferedSource.java:265)
    at java.io.InputStream.read(InputStream.java:162)
    at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)
    at java.io.BufferedInputStream.read(BufferedInputStream.java:288)
    at java.io.InputStream.read(InputStream.java:162)
    at com.ishareok.isharekitdemo.MiscActivity$1.onResponse(MiscActivity.java:361)
    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:150)
    ... 4 more
```

**Comment by jaypatel512** [comment]
We are seeing this issue too when we call cancel operation. I was hoping if we could either catch that exception properly, or find a way to neglect that issue ?
