### ISSUE TITLE
MockWebserver 2.0 play() does not seem to work.

### ISSUE THREAD

**Issue by ksarmalkar** [square/okhttp#1069]
I have code that uses `MockWebServer`, however it seems like the server does not accept incoming connections. This seems to have started happening since we moved to 2.0.0, on 1.6.0 things were working fine. 

The dependencies are 
`compile 'com.squareup.okhttp:okhttp:2.0.0'`
`compile 'com.squareup.okhttp:okhttp-urlconnection:2.0.0'`
`androidTestCompile ('com.squareup.okhttp:mockwebserver:2.0.0'){
        exclude group: 'com.squareup.okhttp'
    }`

Tried a sample test as below, once play is called, I try to hit the server URL:port using curl/browser, but it does not seem to accept any connection, Just says connection refused. Isn't it supposed to return the enqueued responses ?

``` java
public void testMockWebServer() throws Exception {
        // Create a MockWebServer. These are lean enough that you can create a new
        // instance for every unit test.
        MockWebServer server = new MockWebServer();

        // Schedule some responses.
        server.enqueue(new MockResponse().setBody("hello, world!"));
        server.enqueue(new MockResponse().setBody("sup, bra?"));
        server.enqueue(new MockResponse().setBody("yo dog"));

        // Start the server.
        server.play();
        server.getPort();
        Thread.sleep(5000000000L);
        // Shut down the server. Instances cannot be reused.
        server.shutdown();
    }
```

**Comment by josketres** [comment]
I'm having the same issue using version 2.2.0 running in a real device and in an emulator.
When I change to **version 2.1.0 the test runs without problems** in the device and in the emulator.

    compile 'com.squareup.okhttp:okhttp:2.2.0'
    androidTestCompile('com.squareup.okhttp:mockwebserver:2.2.0') {
        exclude group: 'com.squareup.okhttp'
    }

my test looks like this

```java
import android.test.AndroidTestCase;

import com.squareup.okhttp.OkHttpClient;
import com.squareup.okhttp.Request;
import com.squareup.okhttp.mockwebserver.MockResponse;
import com.squareup.okhttp.mockwebserver.MockWebServer;

public class UseOfMockWebServerTest extends AndroidTestCase {

    public void test() throws Exception {

        MockWebServer server = new MockWebServer();
        server.enqueue(new MockResponse().setBody("hello, world!"));
        server.play();
        String url = server.getUrl("/").toString();
        String result = new OkHttpClient().newCall(new Request.Builder().url(url).build()).execute().body().string();
        assertEquals("hello, world!", result);
    }
}
```

And I'm getting the following error

```
java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 54748): connect failed: ECONNREFUSED (Connection refused)
at libcore.io.IoBridge.connect(IoBridge.java:114)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:460)
at java.net.Socket.connect(Socket.java:833)
at com.squareup.okhttp.internal.Platform$Android.connectSocket(Platform.java:179)
at com.squareup.okhttp.Connection.connect(Connection.java:155)
at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:174)
at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120)
at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:131)
at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:312)
at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:235)
at com.squareup.okhttp.Call.getResponse(Call.java:262)
at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219)
at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192)
at com.squareup.okhttp.Call.execute(Call.java:79)
at uk.co.tipp24os.infoservice.service.UseOfMockWebServerTest.test(UseOfMockWebServerTest.java:18)
at java.lang.reflect.Method.invokeNative(Native Method)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:191)
at android.test.AndroidTestRunner.runTest(AndroidTestRunner.java:176)
at android.test.InstrumentationTestRunner.onStart(InstrumentationTestRunner.java:554)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1741)
Caused by: libcore.io.ErrnoException: connect failed: ECONNREFUSED (Connection refused)
at libcore.io.Posix.connect(Native Method)
at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:85)
at libcore.io.IoBridge.connectErrno(IoBridge.java:127)
at libcore.io.IoBridge.connect(IoBridge.java:112)
... 27 more
```


Emulator details
```
Name: Nexus_S_API_21
CPU/ABI: Google APIs Intel Atom (x86)
Path: /home/developers/jzarz/.android/avd/Nexus_S_API_21.avd
Target: Google APIs (API level 21)
Skin: nexus_s
SD Card: /home/developers/jzarz/.android/avd/Nexus_S_API_21.avd/sdcard.img
Snapshot: no
hw.lcd.density: 240
hw.dPad: no
avd.ini.encoding: UTF-8
hw.camera.back: none
disk.dataPartition.size: 200M
hw.gpu.enabled: yes
runtime.network.latency: none
skin.dynamic: no
hw.keyboard: yes
runtime.network.speed: full
hw.device.hash2: MD5:e4aa1843c1036cf7c41ef163fc4d1028
hw.ramSize: 343
tag.id: google_apis
tag.display: Google APIs
hw.sdCard: yes
hw.device.manufacturer: Google
hw.mainKeys: yes
hw.accelerometer: yes
hw.trackBall: no
hw.device.name: Nexus S
hw.sensors.proximity: yes
hw.battery: no
AvdId: Nexus_S_API_21
hw.sensors.orientation: yes
hw.audioInput: yes
hw.camera.front: none
hw.gps: yes
avd.ini.displayname: Nexus S API 21
snapshot.present: no
vm.heapSize: 32
runtime.scalefactor: auto
```

**Comment by curioustechizen** [comment]
To add to what @josketres mentioned, MockWebServer works fine when run from a Robolectric test. The ECONNREFUSED error is seen only when running instrumentation tests on an emulator/device.

**Comment by nfuller** [comment]
Just a corroborating report:

I'm running tests in a fairly unorthodox way against AOSP (with the Android CTS runner which runs tests as an IntrumentedTestCase). I'm seeing many failures that are variants of this:

java.net.ConnectException: failed to connect to localhost/127.0.0.1 (port 54415): connect failed: ECONNREFUSED (Connection refused)>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:128)
at org.junit.Assert.assertEquals(Assert.java:147)
at com.squareup.okhttp.internal.ws.WebSocketRecorder.assertTextMessage(WebSocketRecorder.java:89)
at com.squareup.okhttp.internal.ws.WebSocketCallTest.serverStreamingMessage(WebSocketCallTest.java:107)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:46)
at org.junit.rules.RunRules.evaluate(RunRules.java:18)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:24)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
at org.junit.runner.JUnitCore.run(JUnitCore.java:136)

It does not appear to be every test, just some.

**Comment by nfuller** [comment]
I'm wondering if this is because Android does not (AFAIK) support Junit 4.11 (it looks like it has 4.10 in external/junit). OkHttp has started using @Rule more and @Parameterized.Parameters. I know the @Parameterized.Parameters usage does not compile, but because @Rule was present in 4.10 it may be just not be working as intended.

Connection refusal may just be symptom of the MockWebServer not being started as expected.

**Comment by alfishe** [comment]
The reason is in a way MockWebServer determines address to bind incoming socket
That is the line: inetAddress = InetAddress.getByName(null);

it returns IPv6 address so following binding serverSocket.bind(new InetSocketAddress(inetAddress, port), 50);
making it possible to access mockwebserver only by IPv6 localhost address.

But public URL getUrl(String path) and called from there public String getHostName()  returned 'localhost' string which Android on all of my devices is resolving to IPv4.

Thus connecting to http(s)://localhost:<port> is always refused cause no IPv4 port binding made.

For myself I had to get okhttp sources and modify the only line:
inetAddress = InetAddress.getByName(null);
to
inetAddress = InetAddress.getLocalHost();

Voila, it works perfectly!

p.s. okhttp and mockwebserver contains huge amount of questionable staff but no routing rules to fully simulate rest apis activities? come on! it's just one day of work to implement

**Comment by JakeWharton** [comment]
Then take a day and send a PR.

**Comment by alfishe** [comment]
Will do. Found that okhttp exists today, started to integrate and immediately found a showstopper issue. Had to resolve first. Anyway thanks development team for the idea and existing implementation. Probably will add my version of routing and present for review and approval

**Comment by JakeWharton** [comment]
Needing routes is usually a sign that you should probably just be using a
normal web server.

**Comment by josketres** [comment]
It looks like this error was caused by https://github.com/square/okhttp/commit/b78030a630dc0b757d77e8565241f984e11feaf8 
That explains why it is only ocurring on 2.2.0.

**Comment by nfuller** [comment]
Thanks all for looking into this.

IMO, there is a bug here on Android. I have created this: https://code.google.com/p/android/issues/detail?id=96801

The problem lies in the fact that getAllByName() has a blind spot when it comes to "localhost" and only returns the IPv4 address.

This is in the wild so fixing in Android everywhere would require a time machine, so we'll need to look at a workaround. With the latest Android MockWebServer could use getLocalHost() or getByName("localhost") when binding to be sure of getting the IPv4 address.

It seems reasonable to me that MockWebServer *doesn't* bind to non-loopback interfaces, but if that is not a concern binding the server socket to null would presumably work too.

Alternatively, the URL generation side could specify the IP of the server not the name (thereby side-stepping the "localhost" lookup bug and fixing the problem closest to where it exists).

**Comment by castrojr913** [comment]
The same thing @josketres, I have tested with `com.squareup.okhttp:mockwebserver:2.1.0` and it works. This link has several test codes: http://www.programcreek.com/java-api-examples/index.php?api=tests.http.MockWebServer

**Comment by curioustechizen** [comment]
@castrojr913 This is actually an issue in Android. It will be fixed in a future release of Android. Please take a look at the [comment before yours](https://github.com/square/okhttp/issues/1069#issuecomment-69728761)  and follow the bug opened against Android.

**Comment by nfuller** [comment]
@castrojr913 What @curioustechizen said: It led to a bug being filed on Android. It was also worked around in MockWebServer with pull #1320.

There have been other changes to MockWebServer recently. I think previously it may have been binding to all network interfaces, allowing people to connect via non-loopback IPs and from other hosts. This behavior changed. Because it broke some people, I also think there was a change recently to overload start() and allow developers to select an IP address to bind to.
