### ISSUE TITLE
BufferedSource error with WebSockets

### ISSUE THREAD

**Issue by arriolac** [square/okhttp#1071]
In `WebSocketListener#onMessage(BufferedSource bufferedSource, WebSocket.PayloadType payloadType)`, calling `bufferedSource.readUtf8()` after verifying that `payloadType == WebSocket.PayloadType.TEXT` throws the following exception:

```
System.err  W  java.lang.IllegalArgumentException: byteCount < 0: -26991
    W      at okio.RealBufferedSource.read(RealBufferedSource.java:46)
    W      at com.squareup.okhttp.internal.ws.WebSocketReader$FramedMessageSource.read(WebSocketReader.java:250)
    W      at okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)
    W      at com.operator.expert.service.ChatSocketConnection.onMessage(ChatSocketConnection.java:76)
    W      at com.squareup.okhttp.internal.ws.WebSocketReader.readMessage(WebSocketReader.java:112)
    W      at com.squareup.okhttp.WebSocket$ReaderRunnable.execute(WebSocket.java:283)
    W      at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
    W      at java.lang.Thread.run(Thread.java:841)
```

Any ideas how to prevent/fix this? It doesn't appear to happen to all socket messages.

**Comment by JakeWharton** [comment]
I have identified a potential source of this error. Working on how to apply the fix since it's not a simple misread or mathematical error.
