### ISSUE TITLE
(okhttp-2.1.0 w/ urlconnection & retrofit) NoSuchMethodError "HttpMethod.hasRequestBody"

### ISSUE THREAD

**Issue by mannodermaus** [square/okhttp#1152]
Hello,

after updating my project's okhttp dependencies, every call fails with a NoSuchMethodError.
The same calls go through just fine when using _com.squareup.okhttp:okhttp:2.1.0-RC1_.

My dependencies:

```
compile 'com.squareup.retrofit:retrofit:1.7.1'
compile 'com.squareup.okhttp:okhttp-urlconnection:2.1.0-RC1'
compile 'com.squareup.okhttp:okhttp:2.1.0'
```

The trace:

```
java.lang.NoSuchMethodError: com.squareup.okhttp.internal.http.HttpMethod.hasRequestBody
            at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.newHttpEngine(HttpURLConnectionImpl.java:321)
            at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.initHttpEngine(HttpURLConnectionImpl.java:303)
            at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:364)
            at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:466)
            at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
            at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
            at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.java:73)
            at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:38)
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:321)
            at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
            at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
            at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at retrofit.Platform$Android$2$1.run(Platform.java:142)
            at java.lang.Thread.run(Thread.java:841)
```

**Comment by martinbonnin** [comment]
Hi, I just had the same kind of problem switching from 2.4 to 2.5 and HttpEngine.sameConnection() now taking a HttpUrl and not a java.net.URL: `java.lang.NoSuchMethodError: No virtual method sameConnection(Ljava/net/URL;)Z in class Lcom/squareup/okhttp/internal/http/HttpEngine; `

I was not declaring the urlconnection dependency directly in my gradle file but some other module did. 
Any chance you could force the dependency to okhttp-urlconnection in the main okhttp pom file ? Or trigger an error so that we know something is wrong ?
