### ISSUE TITLE
OkHostnameVerifier verify return false sometimes

### ISSUE THREAD

**Issue by niqo01** [square/okhttp#1163]
We are using OkHttp 2.1.0 on Android and seeing a few "Hostname 'XXX' was not verified"  where XXX is the correct host. We are having maybe an hundreds of thousand connections a day and seeing this one ~250 times a day.

I was wondering what are the circumstances where the hostname verification would failed if the host part of the URL is actually correct?

StackTrace:

```
com.couchsurfing.mobile.data.api.CsRetrofitError: retrofit.RetrofitError: Hostname 'XXX' was not verified
       at com.couchsurfing.mobile.data.api.CouchsurfingErrorHandler.handleError(CouchsurfingErrorHandler.java:38)
       at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
       at $Proxy0.a()
       at com.couchsurfing.mobile.manager.SyncManager.syncConversations(SyncManager.java:474)
       at com.couchsurfing.mobile.manager.SyncManager.performSyncInternal(SyncManager.java:370)
       at com.couchsurfing.mobile.manager.SyncManager.access$100(SyncManager.java:61)
       at com.couchsurfing.mobile.manager.SyncManager$1$1.call(SyncManager.java:273)
       at com.couchsurfing.mobile.manager.SyncManager$1$1.call(SyncManager.java:260)
       at rx.Observable.unsafeSubscribe(Observable.java:7441)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.handleNewSource(OperatorMerge.java:188)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:158)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:93)
       at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
       at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:189)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.access$000(OperatorObserveOn.java:65)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:153)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:45)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:444)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
       at java.util.concurrent.FutureTask.run(FutureTask.java:138)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
       at java.lang.Thread.run(Thread.java:1019)
Caused by: retrofit.RetrofitError: Hostname 'XXX' was not verified
       at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:390)
       at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
       at $Proxy0.a()
       at com.couchsurfing.mobile.manager.SyncManager.syncConversations(SyncManager.java:474)
       at com.couchsurfing.mobile.manager.SyncManager.performSyncInternal(SyncManager.java:370)
       at com.couchsurfing.mobile.manager.SyncManager.access$100(SyncManager.java:61)
       at com.couchsurfing.mobile.manager.SyncManager$1$1.call(SyncManager.java:273)
       at com.couchsurfing.mobile.manager.SyncManager$1$1.call(SyncManager.java:260)
       at rx.Observable.unsafeSubscribe(Observable.java:7441)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.handleNewSource(OperatorMerge.java:188)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:158)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:93)
       at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
       at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:189)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.access$000(OperatorObserveOn.java:65)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:153)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:45)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:444)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
       at java.util.concurrent.FutureTask.run(FutureTask.java:138)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
       at java.lang.Thread.run(Thread.java:1019)
Caused by: java.io.IOException: Hostname 'XXX' was not verified
       at com.squareup.okhttp.Connection.upgradeToTls(Connection.java:239)
       at com.squareup.okhttp.Connection.connect(Connection.java:153)
       at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:169)
       at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:119)
       at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:134)
       at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:314)
       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:237)
       at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:423)
       at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:105)
       at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:239)
       at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
       at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
       at retrofit.client.UrlConnectionClient.prepareRequest(UrlConnectionClient.java:68)
       at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:37)
       at com.couchsurfing.mobile.data.client.RetrofitHttpClient.execute(RetrofitHttpClient.java:40)
       at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:321)
       at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
       at $Proxy0.a()
       at com.couchsurfing.mobile.manager.SyncManager.syncConversations(SyncManager.java:474)
       at com.couchsurfing.mobile.manager.SyncManager.performSyncInternal(SyncManager.java:370)
       at com.couchsurfing.mobile.manager.SyncManager.access$100(SyncManager.java:61)
       at com.couchsurfing.mobile.manager.SyncManager$1$1.call(SyncManager.java:273)
       at com.couchsurfing.mobile.manager.SyncManager$1$1.call(SyncManager.java:260)
       at rx.Observable.unsafeSubscribe(Observable.java:7441)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.handleNewSource(OperatorMerge.java:188)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:158)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:93)
       at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
       at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:189)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.access$000(OperatorObserveOn.java:65)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:153)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:45)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:444)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
       at java.util.concurrent.FutureTask.run(FutureTask.java:138)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
       at java.lang.Thread.run(Thread.java:1019)
```

**Comment by niqo01** [comment]
@swankjesse. We deployed yesterday to a few users and we got the new messages coming in. Here are the new stacktraces:
```
Caused by: java.io.IOException: Hostname hapi.couchsurfing.com not verified:
    certificate: sha1/r4XdjuTmlen7QsCnkgBepuW/7tI=
    DN: CN=*.boingohotspot.net,O=Boingo Wireless,L=Los Angeles,ST=California,C=US
    subjectAltNames: [*.boingohotspot.net]
       at com.squareup.okhttp.Connection.upgradeToTls(Connection.java:260)
```

```
retrofit.RetrofitError: Hostname hapi.couchsurfing.com not verified:
    certificate: sha1/dt+P+XTl0hy1Odbc9iQl/Yuoh20=
    DN: CN=controller.mobile.lan,O=UCOPIA Communications,OU=UCOPIA Communications,L=Montrouge,ST=IDF,C=FR
    subjectAltNames: [controller.mobile.lan, mobileapp.ucopia.com]
       at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
       at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
       at $Proxy0.a()
```
```
java.io.IOException: Hostname hapi.couchsurfing.com not verified:
    certificate: sha1/cJcRXkq5f+V0iFm1eXeOgui6KmU=
    DN: CN=wifisignon.shaw.ca,OU=Engineering,O=Shaw Cablesystems G.P.,L=Calgary,ST=Alberta,C=CA
    subjectAltNames: [wifisignon.shaw.ca]
       at com.squareup.okhttp.Connection.upgradeToTls(Connection.java:260)
       at com.squareup.okhttp.Connection.connect(Connection.java:158)
```
I don't know much, but is MITM the only possible explanation?

**Comment by iNoles** [comment]
last one is WiFi HotSpot sign in. I guess OkHttp wasn't aware of it.

**Comment by swankjesse** [comment]
Looks like all of these are legitimate man-in-the-middle attacks by rogue internet service providers. I assume that couchsurfing.com isn't owned by Shaw Cablesystems or Boingo Wireless.

**Comment by niqo01** [comment]
@swankjesse yeap. Also why are you saying "rogue" internet service providers, aren't they just Network Sign-On redirect?

**Comment by swankjesse** [comment]
No. I'm saying bad companies like Boingo that forge TLS certificates in order to man-in-the-middle attack your network session.

**Comment by niqo01** [comment]
Thanks for the investigation @swankjesse . I am still unsure how sarcastic I want be in the error message but I ll figure that one on my own.
