### ISSUE TITLE
 SSL handshake aborted on 2.3.X & 3.X devices

### ISSUE THREAD

**Issue by niqo01** [square/okhttp#1209]
OkHttp 2.1.0
Only on Android 2.3.X and 3.x

A very low number of our users are having this issue:
http://crashes.to/s/026a4a77865

Reporting as reference. I don't mind if this will ever be fixed.

```
com.couchsurfing.mobile.data.api.CsRetrofitError: retrofit.RetrofitError: SSL handshake aborted: ssl=0x1fcc30: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:658 0xad1276bf:0x00000000)
       at com.couchsurfing.mobile.data.api.CouchsurfingErrorHandler.handleError(CouchsurfingErrorHandler.java:38)
       at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:242)
       at $Proxy0.a()
       at com.couchsurfing.mobile.manager.SyncManager.syncConversations(SyncManager.java:471)
       at com.couchsurfing.mobile.manager.SyncManager.performSyncInternal(SyncManager.java:369)
       at com.couchsurfing.mobile.manager.SyncManager.access$100(SyncManager.java:60)
       at com.couchsurfing.mobile.manager.SyncManager$1$1.call(SyncManager.java:272)
       at com.couchsurfing.mobile.manager.SyncManager$1$1.call(SyncManager.java:259)
       at rx.Observable.unsafeSubscribe(Observable.java:7239)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.handleNewSource(OperatorMerge.java:188)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:158)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:93)
       at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
       at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:189)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.access$000(OperatorObserveOn.java:65)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:153)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:444)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
       at java.util.concurrent.FutureTask.run(FutureTask.java:138)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
       at java.lang.Thread.run(Thread.java:1019)
Caused by: retrofit.RetrofitError: SSL handshake aborted: ssl=0x1fcc30: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:658 0xad1276bf:0x00000000)
       at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:390)
       at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
       at $Proxy0.a()
       at com.couchsurfing.mobile.manager.SyncManager.syncConversations(SyncManager.java:471)
       at com.couchsurfing.mobile.manager.SyncManager.performSyncInternal(SyncManager.java:369)
       at com.couchsurfing.mobile.manager.SyncManager.access$100(SyncManager.java:60)
       at com.couchsurfing.mobile.manager.SyncManager$1$1.call(SyncManager.java:272)
       at com.couchsurfing.mobile.manager.SyncManager$1$1.call(SyncManager.java:259)
       at rx.Observable.unsafeSubscribe(Observable.java:7239)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.handleNewSource(OperatorMerge.java:188)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:158)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:93)
       at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
       at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:189)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.access$000(OperatorObserveOn.java:65)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:153)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:444)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
       at java.util.concurrent.FutureTask.run(FutureTask.java:138)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
       at java.lang.Thread.run(Thread.java:1019)
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x1fcc30: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:658 0xad1276bf:0x00000000)
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(NativeCrypto.java)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:474)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:328)
       at com.squareup.okhttp.Connection.upgradeToTls(Connection.java:235)
       at com.squareup.okhttp.Connection.connect(Connection.java:153)
       at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:169)
       at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:119)
       at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:134)
       at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:314)
       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:237)
       at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:423)
       at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:105)
       at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:239)
       at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
       at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
       at retrofit.client.UrlConnectionClient.prepareRequest(UrlConnectionClient.java:68)
       at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:37)
       at com.couchsurfing.mobile.data.client.RetrofitHttpClient.execute(RetrofitHttpClient.java:40)
       at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:321)
       at retrofit.RestAdapter$RestHandler.invoke(RestAdapter.java:240)
       at $Proxy0.a()
       at com.couchsurfing.mobile.manager.SyncManager.syncConversations(SyncManager.java:471)
       at com.couchsurfing.mobile.manager.SyncManager.performSyncInternal(SyncManager.java:369)
       at com.couchsurfing.mobile.manager.SyncManager.access$100(SyncManager.java:60)
       at com.couchsurfing.mobile.manager.SyncManager$1$1.call(SyncManager.java:272)
       at com.couchsurfing.mobile.manager.SyncManager$1$1.call(SyncManager.java:259)
       at rx.Observable.unsafeSubscribe(Observable.java:7239)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.handleNewSource(OperatorMerge.java:188)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:158)
       at rx.internal.operators.OperatorMerge$MergeSubscriber.onNext(OperatorMerge.java:93)
       at rx.internal.operators.OperatorMap$1.onNext(OperatorMap.java:54)
       at rx.internal.operators.NotificationLite.accept(NotificationLite.java:150)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.pollQueue(OperatorObserveOn.java:189)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber.access$000(OperatorObserveOn.java:65)
       at rx.internal.operators.OperatorObserveOn$ObserveOnSubscriber$2.call(OperatorObserveOn.java:153)
       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:47)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:444)
       at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:306)
       at java.util.concurrent.FutureTask.run(FutureTask.java:138)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:153)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:267)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
       at java.lang.Thread.run(Thread.java:1019)
```

**Comment by niqo01** [comment]
@swankjesse Yes it is always the same target site. I cannot reproduce on my emulator so I am not sure about "reproducing reliably against the same HTTPS server". Do you think that one of our HTTPS server behind our API URL might be misconfigured?

**Comment by swankjesse** [comment]
One thing I wonder about is whether we're just reporting a normal failure using scary language. Is it just a timeout?

**Comment by milcarzg** [comment]
Hi, any news how to fix that problem? I`m getting the same behaviour on 4.4.2 device. 


javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x77abccc0: Failure in SSL library, usually a protocol error
error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:741 0x725577d0:0x00000000)
  at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:448)
 	at com.squareup.okhttp.Connection.upgradeToTls(Connection.java:146)
 	at com.squareup.okhttp.Connection.connect(Connection.java:107)
 	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
 	at com.squareup.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
 	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
 	at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:351)
 	at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:90)
 	at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:198)
 	at com.squareup.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:256)
 	at com.cellpointmobile.sdk.client.AsyncHttpRequest.doInBackground(AsyncHttpRequest.java:291)
 	at com.cellpointmobile.sdk.client.AsyncHttpRequest.doInBackground(AsyncHttpRequest.java:1)
 	at android.os.AsyncTask$2.call(AsyncTask.java:288)
 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 	at java.lang.Thread.run(Thread.java:841)

**Comment by duladissa** [comment]
Hope this post will solve the problem on SSLV3 issue. I have added the HttpsURLConnection.setSSLSocketFactory()

http://stackoverflow.com/questions/26633349/disable-ssl-as-a-protocol-in-httpsurlconnection

**Comment by swankjesse** [comment]
@duladissa do you have a URL that fails reliably? I'd love to reproduce this.

**Comment by duladissa** [comment]
@swankjesse The linkedin user connections url is having the problem. https://api.linkedin.com/v1/people/~/connections

**Comment by swankjesse** [comment]
@duladissa I'm able to successfully connect to that URL. I get a 401, but that means that the TLS handshake was successful. Does that URL redirect to another host?
https://api.linkedin.com/v1/people/~/connections

**Comment by duladissa** [comment]
@swankjesse As I know it will not redirects to another host, but for me It is not possible to reproduce the issue now. I'll try more and if i found any url let you know. Thanks

**Comment by swankjesse** [comment]
Got it. It's possible they just updated their SSL server to offer a more modern set of cipher suites. I'm going to close this issue for now; there's no action for us to take.
