### ISSUE TITLE
WebSocketCallTest.serverMessage is flaky

### ISSUE THREAD

**Issue by JakeWharton** [square/okhttp#1296]
```
<<< FAILURE! - in com.squareup.okhttp.internal.ws.WebSocketCallTest
serverMessage(com.squareup.okhttp.internal.ws.WebSocketCallTest)  Time elapsed: 10.014 sec  <<< FAILURE!
java.lang.AssertionError: expected:<Message[TEXT Buffer[size=18 md5=be471905fcbe7f881ceb7fa60775ab5e]]> but was:<null>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.squareup.okhttp.internal.ws.WebSocketRecorder.assertTextMessage(WebSocketRecorder.java:89)
	at com.squareup.okhttp.internal.ws.WebSocketCallTest.serverMessage(WebSocketCallTest.java:78)
```

**Comment by JakeWharton** [comment]
When using MockWebServer as a rule it's really hard to run a single test 100s of times to try and trigger these. Even using a class rule doesn't seem to re-initialize the server.

Will try to look more at it soon.
