### ISSUE TITLE
Incompatibility with default ProxySelector?

### ISSUE THREAD

**Issue by agatti** [square/okhttp#1311]
Hi there, I'm trying to use OkHttp in a desktop application that sets a JVM-wide proxy via java.net.ProxySelector#setDefault, but looks like OkHttp doesn't like that.  Unfortunately I can't get rid of ProxySelector and I was wondering if there were ways to still use OkHttp.

So, using Java 7 (1.7.0_72) on Mac OS X and OkHttp 2.2.0, the sample code at https://gist.github.com/agatti/7620010f1a356965e4d7 fails with this:

    Exception in thread "main" java.net.SocketException: Unknown proxy type : HTTP
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:396)
    at java.net.Socket.connect(Socket.java:579)
    at com.squareup.okhttp.internal.Platform.connectSocket(Platform.java:100)
    at com.squareup.okhttp.Connection.connect(Connection.java:155)
    at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:174)
    at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120)
    at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:131)
    at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:312)
    at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:235)
    at com.squareup.okhttp.Call.getResponse(Call.java:262)
    at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219)
    at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192)
    at com.squareup.okhttp.Call.execute(Call.java:79)
    at ProxyTest.main(ProxyTest.java:36)

although the normal URL#connect() method of getting data works with a default ProxySelector being set.

Is this a (known) bug or is there a way to work around this?  Maybe it's just me doing things wrong here :)

Thank you!

**Comment by swankjesse** [comment]
This is quite a surprise. We're assuming the system proxy selector won't be picked-up at this level. Do other Java HTTP clients work here? I would expect your proxy selector to completely break your network here.

**Comment by agatti** [comment]
I haven't tried any other clients besides HttpURLConnection, but I did find a way to get it working with OkHttp.  Apparently the code for the ProxySelector instance always returns HTTP proxies even for SOCKS connections (as far as the JVM is concerned), and since OkHttp sends such requests, well, you know what happens.

I haven't checked the okhttp-urlconnection module yet, but on paper it looks like it should work around this situation by sticking with sending HTTP requests to be proxied rather than SOCKS ones, right?

**Comment by swankjesse** [comment]
Yuck. From OkHttp's perspective we're using raw sockets. But unfortunately, the sockets we're getting are consulting proxy selector against our wishes!

You really can't clear the proxy selector?

**Comment by swankjesse** [comment]
No action for us to take here.

**Comment by agatti** [comment]
Unfortunately not, otherwise other pieces break.  Still, thanks for the help!

However, how about adding a warning or a note somewhere in the documentation to prevent others from getting stuck as I was?  I'm not a native English speaker otherwise I might have submitted that PR myself.
