### ISSUE TITLE
NullPointerException in WebSockets PongWriter

### ISSUE THREAD

**Issue by mmarc** [square/okhttp#1319]
Sometimes when closing websocket connection I get a ```NullPointerException```.
Seems like the writer gets closed prior writing pong.

```
java.lang.NullPointerException
 	at com.squareup.okhttp.internal.ws.WebSocket$1$1.execute(WebSocket.java:205)
 	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
 	at java.lang.Thread.run(Thread.java:841)
```

**Comment by JakeWharton** [comment]
This was a pong trying to write after the writer had been closed locally.

It was fixed by 9631227619ffe9497c67d92d20428682e5df8862 where we no longer `null` out the `writer` and we further swallow problems the occur when writing the pong.
