### ISSUE TITLE
com.squareup.okhttp.internal.spdy.Spdy3ConnectionTest#getResponseHeadersTimesOut is flaky on Android

### ISSUE THREAD

**Issue by nfuller** [square/okhttp#1328]
I haven't looked closely at why. This shows up when running the OkHttp tests under Android's CTS runner (an InstrumentationTestCase arrangement).

Sometimes it passes, sometimes it fails with:

01-15 11:43:09 I/0201ad2c860e49b1: com.squareup.okhttp.internal.spdy.Spdy3ConnectionTest#getResponseHeadersTimesOut FAIL 
java.lang.AssertionError: expected:<0> but was:<1>
at org.junit.Assert.fail(Assert.java:93)
at org.junit.Assert.failNotEquals(Assert.java:647)
at org.junit.Assert.assertEquals(Assert.java:128)
at org.junit.Assert.assertEquals(Assert.java:472)
at org.junit.Assert.assertEquals(Assert.java:456)
at com.squareup.okhttp.internal.spdy.Spdy3ConnectionTest.getResponseHeadersTimesOut(Spdy3ConnectionTest.java:888)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:45)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:15)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:42)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:20)
at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:30)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:263)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:68)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:47)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:24)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:231)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:60)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:229)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:50)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:222)
at org.junit.runners.ParentRunner.run(ParentRunner.java:300)
at org.junit.runner.JUnitCore.run(JUnitCore.java:157)
at org.junit.runner.JUnitCore.run(JUnitCore.java:136)
at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:245)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1837)

Using a Nexus 4. I'm not particularly looking into it because SPDY is turned off by default on Android but it may indicate a race (probably in the test) on other platforms.

**Comment by swankjesse** [comment]
Yup, here's an interleaving that will cause the test to flake:

  1. MAIN: schedules a timeout on WATCHDOG
  2. MAIN: begins read
  3. WATCHDOG: timeout reached! calls closeLater(). 
  4. WATCHDOG: closeLater() calls notifyAll(). Context switch _before_ `connection.removeStream(id);`
  5. MAIN: Object.wait() interrupted by watchdog. Throws timeout exception.
  6. MAIN: asserts connection count, expected to be 0, but it's still 1.
  7. WATCHDOG: removes the connection. Too late!
