### ISSUE TITLE
java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by yaming116** [square/okhttp#1340]
i use this test has a error and i test three times it always blocked, can't execute 1000 times.
```java
OkHttpClient client = new OkHttpClient();

	String run(String url) throws IOException {
		Request request = new Request.Builder().url(url).build();

		Response response = client.newCall(request).execute();
		return response.body().string();
	}
	public static void main(String[] args) throws ParseException, IOException {
		final Main example = new Main();
		for (int i = 0, count = 1000; i < count; i++) {
			new Thread(new Runnable() {

				@Override
				public void run() {
					try {
						ok(example);
					} catch (ParseException | IOException e) {
						e.printStackTrace();
					}
				}
			}).start();
		}
	}
```

```java
java.net.SocketException: Connection reset
	at java.net.SocketInputStream.read(Unknown Source)
	at java.net.SocketInputStream.read(Unknown Source)
	at okio.Okio$2.read(Okio.java:136)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:255)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:249)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:187)
	at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:791)
	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:90)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:784)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:645)
	at com.squareup.okhttp.Call.getResponse(Call.java:263)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at com.ucmed.http.Main.run(Main.java:25)
	at com.ucmed.http.Main.ok(Main.java:64)
	at com.ucmed.http.Main$1.run(Main.java:45)
	at java.lang.Thread.run(Unknown Source)
```

**Comment by swankjesse** [comment]
@yaming116 
Expected behavior? You mentioned _1000_ threads. What's the right number that OkHttp should support? I suspect the peer server may stop accepting requests at some number of DoS attack.

**Comment by yaming116** [comment]
Yes,expected behavior.I had test apache httpclient and okhttp ,okhttp always block,it not excute 1000 times.

**Comment by swankjesse** [comment]
I don't think it's appropriate to make 1,000 simultaneous connections to a target server; that may be interpreted as a DoS attack. If you want this behavior, you should probably use OkHttp's async API, which will limit how many concurrent sockets are opened.

**Comment by wozaifeiyang0** [comment]
I have the same problem，“com.squareup.okhttp” no problem,replace "com.squareup.okhttp3" have the same problem
