### ISSUE TITLE
Reusing connections when they are not "isReadable" 

### ISSUE THREAD

**Issue by yogurtearl** [square/okhttp#1442]
```com/squareup/okhttp/internal/http/RouteSelector#nextUnconnected ``` has some odd behaviour.

```java
  Connection nextUnconnected() throws IOException {
    // Always prefer pooled connections over new connections.
    for (Connection pooled; (pooled = pool.get(address)) != null; ) {
      if (request.method().equals("GET") || Internal.instance.isReadable(pooled)) return pooled;
      pooled.getSocket().close();
    }
```

The OR in ```request.method().equals("GET") || Internal.instance.isReadable(pooled)``` seems odd. This can return pooled connections that are GET but NOT "readable".

This is particularly problematic when combined with ```setRetryOnConnectionFailure(false)``` because a non readable connection will always fail with: 

```
java.io.EOFException: \n not found: size=0 content=...
  at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
  at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:187)
  at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
  at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:791)
  at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:678)
  at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:431)
  at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:376)
  at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:471)
  at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
  at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
  at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.java:73)
  at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:38)
```

*Also*, the name of the method is "nextUnconnected" , but it doesn't ensure that isConnected is false. ( maybe I am mis-understanding 'unconnected' ).

**Comment by yogurtearl** [comment]
Using Retrofit 1.9.0 this is the stacktrace:
```
    retrofit.RetrofitError: \n not found: size=0 content=...
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
            at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
            at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
            at retrofit.RxSupport$2.run(RxSupport.java:55)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at █████████████████████████████████████████████████)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)
     Caused by: java.io.EOFException: \n not found: size=0 content=...
            at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
            at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:187)
            at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
            at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:791)
            at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:90)
            at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:784)
            at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:645)
            at com.squareup.okhttp.Call.getResponse(Call.java:263)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192)
            at com.squareup.okhttp.Call.execute(Call.java:79)
            at retrofit.client.OkClient.execute(OkClient.java:53)
            at ██████████████████████████████████████)
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
            at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
            at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
            at retrofit.RxSupport$2.run(RxSupport.java:55)
            at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:442)
            at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:305)
            at java.util.concurrent.FutureTask.run(FutureTask.java:137)
            at ███████████████████████████████████████████)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
            at java.lang.Thread.run(Thread.java:856)
```

**Comment by yogurtearl** [comment]
2 tests fail if I change || to &&:

```if (request.method().equals("GET") && Internal.instance.isReadable(pooled)) return pooled;```

Which makes sense, since that would only use a pooled connection for GETs ( not posts, etc ).


*But*, All tests pass if I just remove the ```request.method().equals("GET") ||```

Which makes more sense, why would we want to dis-regard the state of a pooled connection and try it anyway just because it is a GET request.

**Comment by yogurtearl** [comment]
@JakeWharton suggested that I look at master. 

Looks like this logic got moved on master to HttpEngine:
https://github.com/square/okhttp/blob/52454c61993e4d4376d429652104ae404503c3ad/okhttp/src/main/java/com/squareup/okhttp/internal/http/HttpEngine.java

**Comment by yogurtearl** [comment]
The tests still pass on master after removing ```request.method().equals("GET") ||``` from HttpEngine#createNextConnection on master

**Comment by swankjesse** [comment]
I think the fix might be as simple as making sure `EOFExceptions` on recycled connections aren't surfaced to the application layer. That isn't supposed to happen, but I think it is.

**Comment by swankjesse** [comment]
Does this fix?
```
    client.setRetryOnConnectionFailure(true);
```

**Comment by swankjesse** [comment]
Note that `Internal.instance.isReadable` costs 1ms + an exception allocation in the happy path. We avoid it for `GET` requests because we can assume that connection failures are being handled. (Either by OkHttp itself, with `setRetryOnConnectionFailure(true)`, or by the caller who has heeded the warning on that method's Javadoc, which I quote here:

```
   * Set this to false to avoid retrying requests when doing so is destructive. In this case the
   * calling application should do its own recovery of connectivity failures.
```

**Comment by yogurtearl** [comment]
```client.setRetryOnConnectionFailure(true);``` does fix it from the application's point of view. Although, from the debugger, I can see that the ```EOFException``` is still happening and then the connection is being retried. 

Maybe HttpEngine could have a field alwaysReuseConnectionForGetRequests. 

In the HttpEngine constructor:

```
this.alwaysReuseConnectionForGetRequests = client.getRetryOnConnectionFailure();

````

Then it could be 

```
  if ( (alwaysReuseConnectionForGetRequests  && request.method().equals("GET")) || Internal.instance.isReadable(pooled)) 
```

I have seen pathological HTTP connections that often/always return "Connection: Keep-Alive" and keep the TCP socket open, but won't respond to any further requests on that socket ( i.e. they are not "isReadable" ).

**Comment by swankjesse** [comment]
The cost of the `EOFException` will be far less than the 1ms wait that would be required to avoid it!

On `setRetryOnConnectionFailure(false)`, my expectation is that if you're disabling automatic retries inside of OkHttp, then you're prepared to do your own manual retries in the application layer. I don't think it's worth the complexity to add fine-grained controls on which retries are done inside OkHttp and which are done in the application layer.

Closing; I don't think there's further action required here.
