### ISSUE TITLE
NullPointerException in HttpEngine.readResponse

### ISSUE THREAD

**Issue by isaacl** [square/okhttp#1460]
This is from v2.1.0.  It might be fixed in 2.2.0 since readResponse() now calls emit() instead of flush(). NPE is on buffer.head

java.lang.NullPointerException
    at okio.Okio$1.write(Okio.java:77)
    at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
    at okio.RealBufferedSink.flush(RealBufferedSink.java:171)
    at com.squareup.okhttp.internal.http.HttpConnection$FixedLengthSink.flush(HttpConnection.java:306)
    at okio.RealBufferedSink.flush(RealBufferedSink.java:173)
    at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:636)
    at com.squareup.okhttp.Call.getResponse(Call.java:240)
    at com.squareup.okhttp.Call.execute(Call.java:84)

**Comment by swankjesse** [comment]
I suspect this is now fixed. If you can reproduce in 2.2, please re-open.
