### ISSUE TITLE
Interceptor - java.lang.NoClassDefFoundError: okio.Okio

### ISSUE THREAD

**Issue by vyscond** [square/okhttp#1477]
I writing a interceptor to check access token on a service

```java
import android.util.Log;

import com.squareup.okhttp.Interceptor;
import com.squareup.okhttp.Request;
import com.squareup.okhttp.Response;

import java.io.IOException;

public class MyAppInterceptor implements Interceptor {


    @Override public Response intercept(Chain chain) throws IOException {

        Request request = chain.request();

        Response response = chain.proceed(request);

        echo("received code -> " + response.code());

        if (response.code() == 401) {

            echo("401 received - trying to refresh token");

            (... getting token)

            return chain.proceed(request.newBuilder().header("access_token",token_value).build());

        }

        return response;
    }


    public void echo(String msg) {

        Log.d("interceptor", msg);
    }
}

```

But this ```Response response = chain.proceed(request);``` line is getting this error

```
11922-12161/vyscond.myapp D/Retrofit﹕ ---- ERROR http://192.168.1.5:80/api/access_token/new
03-08 20:50:17.679  11922-12161/vyscond.myapp D/Retrofit﹕ ---- END ERROR
03-08 20:50:17.679  11922-11922/vyscond.myapp D/laconica﹕ SigninActivity - error :/
03-08 20:50:18.101    499-12163/? E/android.os.Debug﹕ !@Dumpstate > sdumpstate -k -t -z -d -o /data/log/dumpstate_app_error
03-08 20:55:17.875      499-584/? W/InputDispatcher﹕ channel ~ Consumer closed input channel or an error occurred.  events=0x9
03-08 21:06:08.460  12723-12723/? W/System.err﹕ java.lang.UnsatisfiedLinkError: Couldn't load minizip from loader dalvik.system.PathClassLoader[dexPath=/system/framework/twframework.jar:/system/app/SamsungApps_Tablet.apk,libraryPath=/data/app-lib/SamsungApps_Tablet]: findLibrary returned null
03-08 21:06:12.820  12618-12791/vyscond.myapp D/Retrofit﹕ ---- ERROR http://192.168.1.5:80/api/access_token/new
03-08 21:06:12.859  12618-12791/vyscond.myapp D/Retrofit﹕ java.lang.NoClassDefFoundError: okio.Okio
            at com.squareup.okhttp.internal.http.HttpConnection.<init>(HttpConnection.java:87)
            at com.squareup.okhttp.Connection.connect(Connection.java:160)
            at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:174)
            at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:120)
            at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:131)
            at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:312)
            at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:235)
            at com.squareup.okhttp.Call.getResponse(Call.java:262)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219)
            at vyscond.myapp.rest.MyService.intercept(MyServiceInterceptor.java:23)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:216)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192)
            at com.squareup.okhttp.Call.execute(Call.java:79)
            at retrofit.client.OkClient.execute(OkClient.java:53)
            at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
            at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
            at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
            at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at retrofit.Platform$Android$2$1.run(Platform.java:142)
            at java.lang.Thread.run(Thread.java:856)
03-08 21:06:12.859  12618-12791/vyscond.myapp D/Retrofit﹕ ---- END ERROR
```

so i search about this ```java.lang.NoClassDefFoundError: okio.Okio``` and include the okio library by gradle

```gradle
compile 'com.squareup.okio:okio:1.1.0'
compile 'com.squareup.okhttp:okhttp:2.2.0'
```

But i'm still getting the same error on the same line

**Comment by swankjesse** [comment]
This is a troubleshooting problem, not an OkHttp bug or feature request. Please try stackoverflow!

**Comment by reisfernanda** [comment]
Hi @ramonmoraes8080 were you able to solve this?
I'm facing the same issue. Thank you!

**Comment by ramonmoraes8080** [comment]
@reisfernanda I think so. Below is a modified version of what I was able to come up at that time. Just keep in mind that it's been a long time since the last time I've tested this logic.

```
import retrofit.RestAdapter;
import com.squareup.okhttp.OkHttpClient;

public class MyRestAPI {
    public static String address = "0.0.0.0";
    public static APICallbacks api = new RestAdapter.Builder().setClient(new OkClient(MyRestAPI.getOkClient())).setLogLevel(RestAdapter.LogLevel.FULL).setEndpoint("http://" + MyRestAPI.address + ":8080/api/v1").build().create(APICallbacks.class);
    public static final OkHttpClient getOkClient() {
        OkHttpClient c = new OkHttpClient();
        c.setReadTimeout(10, TimeUnit.SECONDS);
        c.interceptors().add(new Interceptor() {
            @Override public Response intercept(Chain chain) throws IOException {
                Request request = chain.request();
                echo("1 - request -> " + request.toString());
                Response response = chain.proceed(request);
                echo("2 - response [" + response.code() + "] -> " + response.toString());
                if (response.header("unicorn") != null) {
                    if (response.header("unicorn").equals("expired")) {
                        echo("3 - unicorn access token is invalid! getting new token");
                        User user = MyRestAPI.api.getAccessToken(GlobalPreferences.newUserForTokenRequest(GlobalPreferences.context));
                        GlobalPreferences.updateToken(GlobalPreferences.context, user.token);
                        Request newRequest = request.newBuilder().header(APICallbacks.ACCESS_TOKEN_HEADER_NAME, user.token).build();
                        echo("4 - new token obtained! re-requesting the last request");
                        return chain.proceed(newRequest);
                    }
                }
                //echo(response.header("Content-Type"));
                //echo(response.body().string());
                return response;
            }

            public void echo(String msg) {
                Log.d("FooBar", "[OkHttp] " + msg);
            }
        });
        return c;
    }
    public interface APICallbacks {
        public final String ACCESS_TOKEN_HEADER_NAME = "unicorn";
        @POST("/access_token/new") void getAccessToken(@Body User user, Callback<User> cb);
        // ...
    }
}
```
