### ISSUE TITLE
IOException in DiskLruCache.renameTo while rebuilding the journal.

### ISSUE THREAD

**Issue by crossle** [square/okhttp#1511]
```
W/System.err( 2848): java.lang.RuntimeException: java.io.IOException
W/System.err( 2848): 	at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:175)
W/System.err( 2848): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
W/System.err( 2848): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
W/System.err( 2848): 	at java.lang.Thread.run(Thread.java:818)
W/System.err( 2848): Caused by: java.io.IOException
W/System.err( 2848): 	at com.squareup.okhttp.internal.DiskLruCache.renameTo(DiskLruCache.java:403)
W/System.err( 2848): 	at com.squareup.okhttp.internal.DiskLruCache.rebuildJournal(DiskLruCache.java:385)
W/System.err( 2848): 	at com.squareup.okhttp.internal.DiskLruCache.access$300(DiskLruCache.java:88)
W/System.err( 2848): 	at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:171)
W/System.err( 2848): 	... 3 more

```

**Comment by swankjesse** [comment]
I suspect the underlying issue might be a full disk on the host device. Any ideas?

**Comment by metcorne** [comment]
Some users in this thread with the same issue:
https://github.com/square/okhttp/issues/646

**Comment by swankjesse** [comment]
Fixed by this:
https://github.com/square/okhttp/pull/2388
