### ISSUE TITLE
WebSocket Read timed out when connect to a self-signed HTTPS url

### ISSUE THREAD

**Issue by mingfai** [square/okhttp#1515]
there is a problem in using okhttp-ws to connect to a WSS server that use self-signed cert. (self-signed may or may not be relevant)
 - On Mac, with Oracle's JDK, the https websocket connection works fine
 - On Android, OkHttpClient instance construct in the same way, it can connect to that https server with normal http get call. The instance is set with sslSocketFactory of course
   ```
    OkHttpClient ok = new OkHttpClient();
            ok.setSslSocketFactory(sslSocketFactory);
   ``` 
 - On Android, i tested time out settings from 5s to 60s and there is no difference. 
 
The exception is as follows:

Android 4.3
```
java.net.SocketTimeoutException: Read timed out
            at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_read(Native Method) ~[na:0.0]
            at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:673) ~[na:0.0]
            at okio.Okio$2.read(Okio.java:137) ~[na:0.0]
            at okio.AsyncTimeout$2.read(AsyncTimeout.java:211) ~[na:0.0]
            at okio.RealBufferedSource.request(RealBufferedSource.java:71) ~[na:0.0]
            at okio.RealBufferedSource.require(RealBufferedSource.java:64) ~[na:0.0]
            at okio.RealBufferedSource.readByte(RealBufferedSource.java:77) ~[na:0.0]
            at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:108) ~[na:0.0]
            at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97) ~[na:0.0]
            at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:87) ~[na:0.0]
            at com.squareup.okhttp.ws.WebSocketCall$2.execute(WebSocketCall.java:187) ~[na:0.0]
            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33) ~[na:0.0]
```

Android 4.4
```
java.net.SocketTimeoutException: Read timed out
            at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method) ~[na:0.0]
            at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:689) ~[na:0.0]
            at okio.Okio$2.read(Okio.java:137) ~[na:0.0]
            at okio.AsyncTimeout$2.read(AsyncTimeout.java:211) ~[na:0.0]
            at okio.RealBufferedSource.request(RealBufferedSource.java:71) ~[na:0.0]
            at okio.RealBufferedSource.require(RealBufferedSource.java:64) ~[na:0.0]
            at okio.RealBufferedSource.readByte(RealBufferedSource.java:77) ~[na:0.0]
            at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:108) ~[na:0.0]
            at com.squareup.okhttp.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97) ~[na:0.0]
            at com.squareup.okhttp.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:87) ~[na:0.0]
            at com.squareup.okhttp.ws.WebSocketCall$2.execute(WebSocketCall.java:187) ~[na:0.0]
            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33) ~[na:0.0]
            at java.lang.Thread.run(Thread.java:841) ~[na:0.0]
```

**Comment by mingfai** [comment]
i think this is a false report. it should be a problem with my server system. sorry about it
