### ISSUE TITLE
  java.lang.Throwable: Explicit termination method 'end' not called

### ISSUE THREAD

**Issue by jonneymendoza** [square/okhttp#1535]
Hi i am getting the error below 

    java.lang.Throwable: Explicit termination method 'end' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:184)
            at java.util.zip.Inflater.<init>(Inflater.java:82)
            at okio.GzipSource.<init>(GzipSource.java:62)
            at com.squareup.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:574)
            at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:756)
            at com.squareup.okhttp.Call.getResponse(Call.java:272)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
            at com.squareup.okhttp.Call.execute(Call.java:79)
            at com.jon.net.networklib.NetworkHelper.getResponseBody(NetworkHelper.java:32)
            at com.jon.net.networklib.helpers.PromoCodeHelper.getPromoCode(PromoCodeHelper.java:24)
            at com.jon.net.networklib.NetworkDeligatorImpl.getPromoCode(NetworkDeligatorImpl.java:22)
            at com.jon.net.networklib.NetworkService.onHandleIntent(NetworkService.java:29)
            at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.os.HandlerThread.run(HandlerThread.java:61)

code below:

protected ResponseBody getResponseBody(String url) throws IOException {

        OkHttpClient client = new OkHttpClient();

        Request request = new Request.Builder().url(url).build();

        Response response = client.newCall(request).execute();

        return response.body();
    }

it crashes on  Response response = client.newCall(request).execute();

Am using latest version of okHttp:

    compile 'com.squareup.okhttp:okhttp:2.3.0'

**Comment by swankjesse** [comment]
The exception is just a warning; that just means you didn't close the response body.

**Comment by jonneymendoza** [comment]
Its not a warning, it throws an exception and crashes the app

**Comment by swankjesse** [comment]
The exception that's crashing your app is not the one pasted. Step through with a debugger if you'd like to confirm that!

**Comment by jonneymendoza** [comment]
i have and it crashes right when i make that call to execute request.

How do u close the response body?

**Comment by Miha-x64** [comment]
@swankjesse It is a warning, but it warns about a resource that should be closed expliciltly.
I'm getting this StrictMode violation warning along with SocketTimeoutException; perhaps, `Inflater` not gets closed because of this exception.

SocketTimeoutException stack trace:
```
java.net.SocketTimeoutException: timeout
at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:587)
at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:595)
at okhttp3.internal.http2.Http2Stream$FramedDataSource.waitUntilReadable(Http2Stream.java:366)
at okhttp3.internal.http2.Http2Stream$FramedDataSource.read(Http2Stream.java:329)
at okio.ForwardingSource.read(ForwardingSource.java:35)
at okio.RealBufferedSource.read(RealBufferedSource.java:45)
at okio.RealBufferedSource.exhausted(RealBufferedSource.java:55)
at okio.InflaterSource.refill(InflaterSource.java:101)
at okio.InflaterSource.read(InflaterSource.java:62)
at okio.GzipSource.read(GzipSource.java:80)
at okio.RealBufferedSource.request(RealBufferedSource.java:66)
at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:238)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
at com.example.mypackage.SomeClass$1.intercept(SomeFile:someLine) <— the only line with my code
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)
```

My interceptor code is just this (in Kotlin):
```
.addInterceptor {
    val req = it.request()
    it.proceed(req.newBuilder().url(req.url().newBuilder().addQueryParameter("someParameter", "someValue").build()).build())
}
```
