### ISSUE TITLE
SPDY Request stuck

### ISSUE THREAD

**Issue by raggi** [square/okhttp#1560]
I have an Android bugreport in which a user has all communications with a server halted due to what appears to be a hanging SSL handshake. Full report isn't provided due to confidentiality, but I can provide some more information as needed.

Relevant stacks appear to be:

```
"OkHttp <REMOVED>" prio=5 tid=22 Native
  | group="main" sCount=1 dsCount=0 obj=0x12c07940 self=0xaec4b000
  | sysTid=23547 nice=0 cgrp=bg_non_interactive sched=0/0 handle=0xaef1c800
  | state=S schedstat=( 5023230 434323 20 ) utm=0 stm=0 core=1 HZ=100
  | stack=0xa232a000-0xa232c000 stackSize=1036KB
  | held mutexes=
  kernel: (couldn't read /proc/self/task/23547/stack)
  native: #00 pc 0003b070  /system/lib/libc.so (__pselect6+20)
  native: #01 pc 00016347  /system/lib/libc.so (select+60)
  native: #02 pc 000152fb  /data/app/com.google.android.gms-1/lib/arm/libgmscore.so (???)
  native: #03 pc 000196ff  /data/app/com.google.android.gms-1/lib/arm/libgmscore.so (???)
  native: #04 pc 0207e411  /data/dalvik-cache/arm/data@app@com.google.android.gms-1@base.apk@classes.dex (Java_com_google_android_gms_org_conscrypt_NativeCrypto_SSL_1read__JLjava_io_FileDescriptor_2Lcom_google_android_gms_org_conscrypt_NativeCrypto_00024SSLHandshakeCallbacks_2_3BIII+196)
  at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_read(Native method)
  at com.google.android.gms.org.conscrypt.r.read(SourceFile:698)
  - locked <@addr=0x12c001d0> (a java.lang.Object)
  at okio.Okio$2.read(Okio.java:137)
  at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
  at okio.RealBufferedSource.request(RealBufferedSource.java:71)
  at okio.RealBufferedSource.require(RealBufferedSource.java:64)
  at okio.RealBufferedSource.readInt(RealBufferedSource.java:217)
  at com.squareup.okhttp.internal.spdy.Spdy3$Reader.nextFrame(Spdy3.java:129)
  at com.squareup.okhttp.internal.spdy.SpdyConnection$Reader.execute(SpdyConnection.java:574)
  at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
  at java.lang.Thread.run(Thread.java:818)
```

```
"OkHttp ConnectionPool" daemon prio=5 tid=25 TimedWaiting
  | group="main" sCount=1 dsCount=0 obj=0x12c078e0 self=0xaec4ac00
  | sysTid=19849 nice=0 cgrp=bg_non_interactive sched=0/0 handle=0xaec5e980
  | state=S schedstat=( 985625 835312 7 ) utm=0 stm=0 core=0 HZ=100
  | stack=0xa242e000-0xa2430000 stackSize=1036KB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x3311b349> (a com.squareup.okhttp.ConnectionPool)
  at com.squareup.okhttp.ConnectionPool.performCleanup(ConnectionPool.java:304)
  - locked <0x3311b349> (a com.squareup.okhttp.ConnectionPool)
  at com.squareup.okhttp.ConnectionPool.runCleanupUntilPoolIsEmpty(ConnectionPool.java:241)
  at com.squareup.okhttp.ConnectionPool.access$000(ConnectionPool.java:54)
  at com.squareup.okhttp.ConnectionPool$1.run(ConnectionPool.java:97)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
  at java.lang.Thread.run(Thread.java:818)
```

```
"Okio Watchdog" daemon prio=5 tid=27 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x12c076a0 self=0x9cd39c00
  | sysTid=12193 nice=0 cgrp=bg_non_interactive sched=0/0 handle=0x9b02f280
  | state=S schedstat=( 183982797 342420840 5954 ) utm=4 stm=14 core=1 HZ=100
  | stack=0x99859000-0x9985b000 stackSize=1036KB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x03943ee4> (a java.lang.Class<okio.AsyncTimeout>)
  at okio.AsyncTimeout.awaitTimeout(AsyncTimeout.java:297)
  - locked <0x03943ee4> (a java.lang.Class<okio.AsyncTimeout>)
  at okio.AsyncTimeout.access$000(AsyncTimeout.java:40)
  at okio.AsyncTimeout$Watchdog.run(AsyncTimeout.java:272)
```

```
"Thread-27808" prio=5 tid=23 Waiting
  | group="main" sCount=1 dsCount=0 obj=0x12c09120 self=0x9cd38800
  | sysTid=8876 nice=0 cgrp=bg_non_interactive sched=0/0 handle=0xb491f100
  | state=S schedstat=( 3802479844 5281316024 11998 ) utm=249 stm=131 core=0 HZ=100
  | stack=0x9b55d000-0x9b55f000 stackSize=1036KB
  | held mutexes=
  at java.lang.Object.wait!(Native method)
  - waiting on <0x2673c277> (a com.squareup.okhttp.internal.spdy.SpdyConnection)
  at com.squareup.okhttp.internal.spdy.SpdyConnection.writeData(SpdyConnection.java:314)
  - locked <0x2673c277> (a com.squareup.okhttp.internal.spdy.SpdyConnection)
  at com.squareup.okhttp.internal.spdy.SpdyStream$SpdyDataSink.write(SpdyStream.java:499)
  at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:156)
  at okio.RealBufferedSink.write(RealBufferedSink.java:70)
  at com.squareup.okhttp.RequestBody$1.writeTo(RequestBody.java:72)
  at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:787)
  at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:652)
  at com.squareup.okhttp.Call.getResponse(Call.java:263)
  at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:219)
  at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:192)
  at com.squareup.okhttp.Call.execute(Call.java:79)
  at <APPCODE>
  at <APPCODE>
  at <APPCODE>
  at <APPCODE>
  at <APPCODE>
  at <APPCODE>
  at <APPCODE>
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:135)
  at <APPCODE>
```

I should have observed timeouts/errors as I have:

```
client.setConnectTimeout(2, TimeUnit.SECONDS);
client.setReadTimeout(4, TimeUnit.SECONDS);
client.setWriteTimeout(2, TimeUnit.SECONDS);
```

Looking at the rest of my logs here, the request was initiated before the logs started at around 11am, with the last log at around 1pm. The service making this request was created and initiated it therefore over 2 hours before. I also have in the logs many wifi and data connection losses and connects, so we would have expected an error or timeout by now.

**Comment by swankjesse** [comment]
Thanks for the complete bug report. Made it easy to build a testcase & write a fix.

**Comment by raggi** [comment]
Awesome, I completely missed that. Thanks :)

**Comment by toluju** [comment]
Ran into a similar and perplexing issue on a build that should have the above fix in it. Truncated thread dump:

    "downloader-pool-thread-1" prio=5 tid=62 NATIVE
    | group="main" sCount=1 dsCount=0 obj=0x44578580 self=0x622cc470
    | sysTid=13979 nice=10 sched=0/0 cgrp=apps/bg_non_interactive handle=1646803144
    | schedstat=( 2842312441 7088782150 32938 ) utm=180 stm=104 core=0
    #00  pc 0000ccb8  /system/lib/libc.so (select+20)
    #01  pc 0001f383  /system/lib/libjavacore.so
    #02  pc 0002077f  /system/lib/libjavacore.so
    #03  pc 0001de70  /system/lib/libdvm.so (dvmPlatformInvoke+112)
    #04  pc 0004d0c3  /system/lib/libdvm.so (dvmCallJNIMethod(unsigned int const*, JValue*, Method   const*, Thread*)+394)
    #05  pc 00000214  /dev/ashmem/dalvik-jit-code-cache (deleted)
    at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_read(Native Method)
    at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl  .java:651)
    at okio.Okio$2.read(Okio.java:137)
    at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
    at okio.RealBufferedSource.read(RealBufferedSource.java:50)
    at com.squareup.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.  java:418)
    at okio.RealBufferedSource.read(RealBufferedSource.java:50)
    at okio.RealBufferedSink.writeAll(RealBufferedSink.java:102)

The symptoms of this behavior are downloads that simply hang indefinitely. We aren't explicitly configuring OkHttp to have timeouts, but from reading the code it seems like it has default values, so I would expect a timeout to trigger eventually.

So far we've seen this behavior on a Samsung Note 2 and a Samsung Galaxy S3. It doesn't reproduce very consistently, and we're not sure yet if it's possibly an issue in our app code or something deeper in the stack.
