### ISSUE TITLE
ResponseBody#string ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by cocoahero** [square/okhttp#1585]
We're seeing lots of crashes out in the wild when attempting to read response body's as strings (for JSON parsing). This is occurring in the v2.3.0 release of OkHttp. Not sure if this is related to #1540 or not.

```
java.lang.ArrayIndexOutOfBoundsException: size=0 offset=0 byteCount=1
	at okio.Util.checkOffsetAndCount(SourceFile:29)
	at okio.Buffer.getByte(SourceFile:294)
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(SourceFile:269)
	at com.squareup.okhttp.internal.http.HttpConnection$ChunkedSource.readChunkSize(SourceFile:451)
	at com.squareup.okhttp.internal.http.HttpConnection$ChunkedSource.read(SourceFile:432)
	at okio.Buffer.writeAll(SourceFile:819)
	at okio.RealBufferedSource.readByteArray(SourceFile:92)
	at com.squareup.okhttp.ResponseBody.bytes(SourceFile:57)
	at com.squareup.okhttp.ResponseBody.string(SourceFile:83)
	at com.redacted.JSONRequestCallback.onResponse(SourceFile:21)
	at com.squareup.okhttp.Call$AsyncCall.execute(SourceFile:168)
	at com.squareup.okhttp.internal.NamedRunnable.run(SourceFile:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
```

Here's the `JSONRequestCallback` code in case it's helpful.

```
public abstract class JSONRequestCallback implements Callback {
    @Override
    public final void onResponse(Response response) throws IOException {
        ResponseBody body = response.body();
        try {
            if (response.isSuccessful()) {
                String bodyString = body.string().trim();
                if (!TextUtils.isEmpty(bodyString)) {
                    onSuccess(response, new JSONObject(bodyString));
                }
                else {
                    onSuccess(response, null);
                }
            }
            else {
                onFailure(response.request(), new InvalidResponseException(response.code()));
            }
        }
        catch (IOException e) {
            onFailure(response.request(), e);
        }
        catch (JSONException | ArrayIndexOutOfBoundsException e) {
            onFailure(response.request(), new InvalidResponseException(e));
        }
        finally {
            body.close();
        }
    }

    public void onSuccess(Response response, JSONObject json) {

    }

    @Override
    public void onFailure(Request request, IOException exception) {

    }
}
```

**Comment by JakeWharton** [comment]
This was fixed by https://github.com/square/okio/pull/142 and will be in the next OkHttp release.

**Comment by ArneKoeckeritz** [comment]
I see the same issue on my app in the wild.
@JakeWharton can you please give an estimate when the release is planned.
Thx for the great library !

**Comment by swankjesse** [comment]
We're planning a release 2 weeks from today.

**Comment by swankjesse** [comment]
If you want to use a snapshot in the interim, please do!
