### ISSUE TITLE
Intercepting RequestBody sink with ForwardingSink fails with "unexpected end of stream"

### ISSUE THREAD

**Issue by mttkay** [square/okhttp#1587]
We're attempting to implement upload progress and largely looked at the reference implementation for downloads here: https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/com/squareup/okhttp/recipes/Progress.java

Here is what we did:

```
class ProgressRequestBody extends RequestBody {

    private final RequestBody requestBody;
    private final ProgressListener progressListener;

    public ProgressRequestBody(RequestBody requestBody, ProgressListener progressListener) {
        this.requestBody = requestBody;
        this.progressListener = progressListener;
    }

    @Override
    public MediaType contentType() {
        return requestBody.contentType();
    }

    @Override
    public long contentLength() throws IOException {
        return requestBody.contentLength();
    }

    @Override
    public void writeTo(BufferedSink sink) throws IOException {
        final long totalBytes = contentLength();
        requestBody.writeTo(Okio.buffer(new ForwardingSink(sink) {
            private long bytesWritten = 0L;

            @Override
            public void write(Buffer source, long byteCount) throws IOException {
                bytesWritten += byteCount;
                progressListener.update(bytesWritten, totalBytes);
                super.write(source, byteCount);
            }
        }));
    }
}
```

so essentially we're simply decorating the sink we're writing the request body to with something that counts bytes. However, this suddenly started to fail all these requests with the following error:

```
 04-28 15:11:01.234  E SoundCloudApplication  at com.soundcloud.android.api.ApiClient.fetchResponse(ApiClient.java:103)
 04-28 15:11:01.234  E SoundCloudApplication  at com.soundcloud.android.api.ApiClient.fetchMappedResponse(ApiClient.java:177)
 04-28 15:11:01.234  E SoundCloudApplication  at com.soundcloud.android.api.ApiClient.fetchMappedResponse(ApiClient.java:182)
 04-28 15:11:01.234  E SoundCloudApplication  at com.soundcloud.android.creators.upload.Uploader.upload(Uploader.java:123)
 04-28 15:11:01.234  E SoundCloudApplication  at com.soundcloud.android.creators.upload.Uploader.run(Uploader.java:97)
 04-28 15:11:01.234  E SoundCloudApplication  at android.os.Handler.handleCallback(Handler.java:730)
 04-28 15:11:01.234  E SoundCloudApplication  at android.os.Handler.dispatchMessage(Handler.java:92)
 04-28 15:11:01.234  E SoundCloudApplication  at android.os.Looper.loop(Looper.java:137)
 04-28 15:11:01.234  E SoundCloudApplication  at android.os.HandlerThread.run(HandlerThread.java:61)
 04-28 15:11:01.234  E SoundCloudApplication  Caused by: java.net.ProtocolException: unexpected end of stream
 04-28 15:11:01.234  E SoundCloudApplication  at com.squareup.okhttp.internal.http.HttpConnection$FixedLengthSink.close(HttpConnection.java:292)
 04-28 15:11:01.234  E SoundCloudApplication  at okio.RealBufferedSink.close(RealBufferedSink.java:221)
 04-28 15:11:01.234  E SoundCloudApplication  at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:820)
 04-28 15:11:01.234  E SoundCloudApplication  at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:684)
 04-28 15:11:01.234  E SoundCloudApplication  at com.squareup.okhttp.Call.getResponse(Call.java:272)
 04-28 15:11:01.234  E SoundCloudApplication  at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
 04-28 15:11:01.234  E SoundCloudApplication  at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
 04-28 15:11:01.234  E SoundCloudApplication  at com.squareup.okhttp.Call.execute(Call.java:79)
 04-28 15:11:01.234  E SoundCloudApplication  at com.soundcloud.android.api.ApiClient.fetchResponse(ApiClient.java:96)
 04-28 15:11:01.234  E SoundCloudApplication  ... 8 more
```

We looked into this a bit, and what apparently happens is that in `HttpEngine#proceed`, the call to `bufferedRequestBody.close()` fails, because there are remaining bytes that haven't been written to the sink yet.

This is odd, since our decorator purely listens in and doesn't actually touch any of the data. One thing that could add to this is that the request body we're writing is a `MultipartRequestBody` which actually walks over all its parts to count the bytes it needs to write.

Is there something we're missing or could this be a bug in OkHttp (or Okio?)

**Comment by JakeWharton** [comment]
You probably want:
```java
        final long totalBytes = contentLength();
        BufferedSink progressSink = Okio.buffer(new ForwardingSink(sink) {
            private long bytesWritten = 0L;

            @Override
            public void write(Buffer source, long byteCount) throws IOException {
                bytesWritten += byteCount;
                progressListener.update(bytesWritten, totalBytes);
                super.write(source, byteCount);
            }
        });
        requestBody.writeTo(progressSink);
        progressSink.flush();
```
The key change is flushing after telling the body to write on your wrapped, buffered sink.

If the request body does not call `.flush()` (or `.close()`) on its given `BufferedSink`, bytes will be stuck in the `Okio.buffer`-wrapped `ForwardingSink` and won't make it to the underlying `sink`.

**Comment by mttkay** [comment]
Wow that was quick. Thanks @JakeWharton , that was indeed the issue. I wish I had asked 2 hours ago.

**Comment by lingrixin** [comment]
@mttkay @JakeWharton RequestBody writeTo() method  maybe called twice or More...
