### ISSUE TITLE
Connection canceling breaks onResponse

### ISSUE THREAD

**Issue by Wavesonics** [square/okhttp#1608]
So I've got a case where a Call is running, and invokes onResponse, and the onResponse impl begins reading from the body, and then, on a separate thread, cancel() is called. And this blows up onResponse() with a SocketException:

java.net.SocketException: Socket closed
            at libcore.io.Posix.recvfromBytes(Native Method)
            at libcore.io.Posix.recvfrom(Posix.java:141)
            at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)
            at libcore.io.IoBridge.recvfrom(IoBridge.java:506)
            at java.net.PlainSocketImpl.read(PlainSocketImpl.java:489)
            at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
            at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
            at okio.Okio$2.read(Okio.java:137)
            at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
            at okio.RealBufferedSource.read(RealBufferedSource.java:50)
            at com.squareup.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:390)
            at okio.RealBufferedSource.read(RealBufferedSource.java:50)
            at com.squareup.okhttp.internal.http.HttpEngine$2.read(HttpEngine.java:868)
            at okio.Buffer.writeAll(Buffer.java:819)
            at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:92)
            at com.squareup.okhttp.ResponseBody.bytes(ResponseBody.java:57)
            at com.xxx.xxx.XxxRequestCallback.onResponse(XxxRequestCallback.java:32)
            at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:168)
            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:841)

Is there a best-practice way of doing this? Just catch it in onResponse I suppose and dispatch a failure?

**Comment by swankjesse** [comment]
Yup! You probably want to handle that exception anyway, such as when your network drops while reading a response.
