### ISSUE TITLE
Okio is 'DDOS' my server

### ISSUE THREAD

**Issue by ppamorim** [square/okhttp#1611]
Hi.
I'm using the last version of the OkHttp. My team have warned me that was being made ​​more than 1,500 requests per seconds from Okio. I've revised the code but I can't find anything wrong. I've one request when the app starts. I handle the all exceptions.
I think it's a problem of the Okio. I've added the Crashlytics to warn errors, well, I've found this:

    java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:299)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
       at java.util.concurrent.FutureTask.run(FutureTask.java:239)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)
    Caused by: java.lang.ArrayIndexOutOfBoundsException: size=0 offset=0 byteCount=1
       at okio.Util.checkOffsetAndCount(Util.java:29)
       at okio.Buffer.getByte(Buffer.java:294)
       at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:269)
       at com.squareup.okhttp.internal.http.HttpConnection$ChunkedSource.readChunkSize(HttpConnection.java:451)
       at com.squareup.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:432)
       at okio.RealBufferedSource.read(RealBufferedSource.java:50)
       at okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)
       at okio.InflaterSource.refill(InflaterSource.java:101)
       at okio.InflaterSource.read(InflaterSource.java:62)
       at okio.GzipSource.read(GzipSource.java:80)
       at okio.Buffer.writeAll(Buffer.java:819)
       at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:92)
       at com.squareup.okhttp.ResponseBody.bytes(ResponseBody.java:57)
       at com.squareup.okhttp.ResponseBody.string(ResponseBody.java:83)
       at ...
       at android.os.AsyncTask$2.call(AsyncTask.java:287)
       at java.util.concurrent.FutureTask.run(FutureTask.java:234)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:841)

**Comment by swankjesse** [comment]
Does your code automatically retry HTTP requests that fail with a RuntimeException? That's likely to be what's causing the amplification attack.

The ArrayIndexOutOfBoundsException bug is fixed. I'll cut an Okio release very soon. In the interim, you could use a snapshot build.

**Comment by ppamorim** [comment]
My code doesn't retry when the request fail.

**Comment by DanielNovak** [comment]
Could it be related with request retrying on connection failure? You can test if setting [OkHtttpClient.setRetryOnConnectionFailure(false)](http://square.github.io/okhttp/javadoc/com/squareup/okhttp/OkHttpClient.html#setRetryOnConnectionFailure-boolean-).

**Comment by swankjesse** [comment]
Unlikely that this is being classified as a connection failure.

**Comment by swankjesse** [comment]
If you can provide a test case, that would be helpful. We already have a fix for the underlying exception, so I don't think there's further action to take here.

**Comment by ppamorim** [comment]
Well, the server notify that return 200 (OK) on every request. I removed the OKHttp for this request because this is applied on a production app. I'll return with OkHttp when this issue is gone.

**Comment by ppamorim** [comment]
@Daniel setRetryOnConnectionFailure not working :/
