### ISSUE TITLE
IPv6 addresses are resolved too eagerly

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#1616]
We don't want to do DNS resolution as a part of URL parsing.
```
"main" prio=5 tid=0x00007f90d3803000 nid=0x1903 runnable [0x0000000110171000]
   java.lang.Thread.State: RUNNABLE
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$1.lookupAllHostAddr(InetAddress.java:901)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1293)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1246)
	at java.net.InetAddress.getAllByName(InetAddress.java:1162)
	at java.net.InetAddress.getAllByName(InetAddress.java:1098)
	at java.net.InetAddress.getByName(InetAddress.java:1048)
	at com.squareup.okhttp.HttpUrl$Builder.decodeIpv6(HttpUrl.java:741)
```

**Comment by swankjesse** [comment]
Fixed with https://github.com/square/okhttp/pull/1618.
