### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException No deadline

### ISSUE THREAD

**Issue by ArneKoeckeritz** [square/okhttp#1620]
Hi,

i found a failure in the okhttp 2.3.0
see: http://crashes.to/s/0feb94a574c

Stacktrace

java.lang.IllegalStateException: No deadline
       at okio.Timeout.deadlineNanoTime(SourceFile:104)
       at okio.AsyncTimeout.scheduleTimeout(SourceFile:84)
       at okio.AsyncTimeout.enter(SourceFile:69)
       at okio.AsyncTimeout$2.read(SourceFile:209)
       at okio.RealBufferedSource.indexOf(SourceFile:295)
       at okio.RealBufferedSource.indexOf(SourceFile:289)
       at okio.RealBufferedSource.readUtf8LineStrict(SourceFile:196)
       at com.squareup.okhttp.internal.http.HttpConnection.readResponse(SourceFile:190)
       at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(SourceFile:80)
       at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(SourceFile:830)
       at com.squareup.okhttp.internal.http.HttpEngine.access$200(SourceFile:95)
       at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(SourceFile:823)
       at com.squareup.okhttp.internal.http.HttpEngine.readResponse(SourceFile:684)
       at com.squareup.okhttp.Call.getResponse(SourceFile:272)
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(SourceFile:228)
       at com.squareup.okhttp.Call.getResponseWithInterceptorChain(SourceFile:199)
       at com.squareup.okhttp.Call.execute(SourceFile:79)
       at de.komoot.android.net.task.HttpTask.execute(SourceFile:449)
       at de.komoot.android.net.task.HttpTask.executeOnThread(SourceFile:263)
       at de.komoot.android.net.task.HttpTask.executeOnThread(SourceFile:219)
       at de.komoot.android.net.task.BaseHttpTask.asyncNetworkExecution(SourceFile:208)
       at de.komoot.android.net.task.BaseHttpTask.run(SourceFile:179)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:848)

I can not reproduce it with any of my test devices. In the wild it doesn't happen not very often.
1 failure in 10000 sessions.

**Comment by swankjesse** [comment]
Yikes. Thanks for reporting this.

**Comment by swankjesse** [comment]
Fixed by https://github.com/square/okhttp/pull/1654.
