### ISSUE TITLE
Flake on test run with latest code today

### ISSUE THREAD

**Issue by nfuller** [square/okhttp#1640]
Uncaught exception in OkHttp thread "MockSpdyPeer"
java.lang.NullPointerException
	at com.squareup.okhttp.internal.spdy.MockSpdyPeer.readAndWriteFrames(MockSpdyPeer.java:133)
	at com.squareup.okhttp.internal.spdy.MockSpdyPeer.access$300(MockSpdyPeer.java:39)
	at com.squareup.okhttp.internal.spdy.MockSpdyPeer$1.run(MockSpdyPeer.java:122)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:745)

Last test to start was: writeTimesOutAwaitingConnectionWindow(com.squareup.okhttp.internal.spdy.Spdy3ConnectionTest)

Failed once. Passed on re-run.

**Comment by swankjesse** [comment]
Fixed with https://github.com/square/okhttp/pull/1658
