### ISSUE TITLE
com.squareup.okhttp.internal.Network$1.resolveInetAddresses

### ISSUE THREAD

**Issue by andaas4** [square/okhttp#1646]
Hey

I'm using okhttp:2.3.0
I can not reproduce it, but it does happen a couple of times a day on my device.
If i try to run the same request seconds later it works.

java.net.UnknownHostException: Unable to resolve host "appname.appspot.com": No address associated with hostname
       at java.net.InetAddress.lookupHostByName(InetAddress.java:457)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
       at java.net.InetAddress.getAllByName(InetAddress.java:215)
       at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
       at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
       at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
       at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
       at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
       at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
       at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
       at com.squareup.okhttp.Call.getResponse(Call.java:271)
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
       at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
       at com.squareup.okhttp.Call.execute(Call.java:79)
       at lib.JSONParser.getJSONFromUrlNew(JSONParser.java:93)
       at com.test.test.MainView$CheckForNewMessages.doInBackground(MainView.java:539)
       at com.test.test.MainView$CheckForNewMessages.doInBackground(MainView.java:474)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
       at libcore.io.Posix.android_getaddrinfo(Posix.java)
       at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
       at java.net.InetAddress.lookupHostByName(InetAddress.java:438)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
       at java.net.InetAddress.getAllByName(InetAddress.java:215)
       at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
       at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
       at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
       at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
       at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
       at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
       at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
       at com.squareup.okhttp.Call.getResponse(Call.java:271)
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
       at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
       at com.squareup.okhttp.Call.execute(Call.java:79)
       at lib.JSONParser.getJSONFromUrlNew(JSONParser.java:93)
       at com.test.test.MainView$CheckForNewMessages.doInBackground(MainView.java:539)
       at com.test.test.MainView$CheckForNewMessages.doInBackground(MainView.java:474)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by swankjesse** [comment]
That's a problem with your network connectivity. We can't fix that here!

**Comment by andaas4** [comment]
Ok, thanks! Any idea what could cause this problem?

**Comment by swankjesse** [comment]
That's a question for StackOverflow.

**Comment by tehfonsi** [comment]
I've got the same issue (also appspot) and the problem occurs for 10% of all calls, which seems to be a bit often to be only a connectivity issue?

Here is my stacktrace:

Non-fatal Exception: retrofit.RetrofitError: Unable to resolve host "appname.appspot.com": No address associated with hostname
       at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:390)
       at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
       at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
       at retrofit.RxSupport$2.run(RxSupport.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at retrofit.Platform$Android$2$1.run(Platform.java:142)
       at java.lang.Thread.run(Thread.java:841)
Caused by java.net.UnknownHostException: Unable to resolve host "appname.appspot.com": No address associated with hostname
       at java.net.InetAddress.lookupHostByName(InetAddress.java:424)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
       at java.net.InetAddress.getAllByName(InetAddress.java:214)
       at com.squareup.okhttp.internal.Dns$1.getAllByName(Dns.java:29)
       at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:231)
       at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
       at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:317)
       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
       at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:420)
       at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:371)
       at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:466)
       at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
       at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
       at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.java:73)
       at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:38)
       at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:321)
       at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
       at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
       at retrofit.RxSupport$2.run(RxSupport.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at retrofit.Platform$Android$2$1.run(Platform.java:142)
       at java.lang.Thread.run(Thread.java:841)
Caused by libcore.io.GaiException: getaddrinfo failed: EAI_NODATA (No address associated with hostname)
       at libcore.io.Posix.getaddrinfo(Posix.java)
       at libcore.io.ForwardingOs.getaddrinfo(ForwardingOs.java:61)
       at java.net.InetAddress.lookupHostByName(InetAddress.java:405)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
       at java.net.InetAddress.getAllByName(InetAddress.java:214)
       at com.squareup.okhttp.internal.Dns$1.getAllByName(Dns.java:29)
       at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:231)
       at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
       at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:317)
       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
       at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:420)
       at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:371)
       at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:466)
       at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
       at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
       at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.java:73)
       at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:38)
       at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:321)
       at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
       at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
       at retrofit.RxSupport$2.run(RxSupport.java:55)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at retrofit.Platform$Android$2$1.run(Platform.java:142)
       at java.lang.Thread.run(Thread.java:841)
