### ISSUE TITLE
Crash in newCall().execute()

### ISSUE THREAD

**Issue by T7777** [square/okhttp#1656]
Hi,

I am getting a crash in my mobile app in your utility.  To narrow it down and exclude other factors, I created an empty test project and used the sample code you provided.  My code is below.  I put in some logging to see where it crashes.  The line it crashes on is:

Response response = client.newCall(request).execute();

It gets to the "finally" block in the "try" statement.  I am using Android Studio v1.2.  I am using OKHttp v2.3 and OKIO v1.3.  

Any help is appreciated.

Thanks!

--------------------------------------------

class GetExample {
    OkHttpClient client = new OkHttpClient();

    String run(String url) throws IOException {
        Request request = new Request.Builder()
                .url(url)
                .build();

        Response response = client.newCall(request).execute();
        return response.body().string();
    }
}

@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        Logs logs = new Logs();

        try {
            GetExample example = new GetExample();
            String response = example.run("https://raw.github.com/square/okhttp/master/README.md");
        } catch (IllegalArgumentException e) {
            logs.LogMessage("ERROR_MALFORMED_URL");
        } catch (SocketTimeoutException e) {
            logs.LogMessage("ERROR_CONNECTION_ERROR");
        } catch (UnknownHostException e) {
            logs.LogMessage("ERROR_UNKNOWN_HOST");
        } catch (IOException e) {
            logs.LogMessage("ERROR_IO_ERROR");
        } catch (NullPointerException e) {
            logs.LogMessage("ERROR_CONNECTION_ERROR");
        } finally {
            logs.LogMessage("catch->finally");
        }
    }

**Comment by swankjesse** [comment]
Do you get a stacktrace?

**Comment by T7777** [comment]
Thanks for the quick reply!

Full thread dump

"FinalizerDaemon@3782" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks FinalizerDaemon@3782
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Object.wait(Object.java:422)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:101)
	  - locked <0xecc> (a java.lang.ref.ReferenceQueue)
	  at java.lang.ref.ReferenceQueue.remove(ReferenceQueue.java:72)
	  at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:173)
	  at java.lang.Thread.run(Thread.java:820)

"main@3563" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	  at android.os.BinderProxy.transactNative(Binder.java:-1)
	  at android.os.BinderProxy.transact(Binder.java:496)
	  at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:4100)
	  at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:89)
	  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
	  at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)

"FinalizerWatchdogDaemon@3781" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks FinalizerWatchdogDaemon@3781
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Daemons$FinalizerWatchdogDaemon.waitForObject(Daemons.java:239)
	  - locked <0xecb> (a java.lang.Daemons$FinalizerWatchdogDaemon)
	  at java.lang.Daemons$FinalizerWatchdogDaemon.run(Daemons.java:211)
	  at java.lang.Thread.run(Thread.java:820)

"GCDaemon@3779" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks GCDaemon@3779
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Daemons$GCDaemon.run(Daemons.java:341)
	  - locked <0xeca> (a java.lang.Daemons$GCDaemon)
	  at java.lang.Thread.run(Thread.java:820)

"HeapTrimmerDaemon@3780" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks HeapTrimmerDaemon@3780
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Daemons$HeapTrimmerDaemon.run(Daemons.java:310)
	  - locked <0xecd> (a java.lang.Daemons$HeapTrimmerDaemon)
	  at java.lang.Thread.run(Thread.java:820)

"ReferenceQueueDaemon@3783" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 blocks ReferenceQueueDaemon@3783
	  at java.lang.Object.wait(Object.java:-1)
	  at java.lang.Daemons$ReferenceQueueDaemon.run(Daemons.java:133)
	  - locked <0x5c6> (a java.lang.Class)
	  at java.lang.Thread.run(Thread.java:820)

"Signal Catcher@3778" daemon prio=5 waiting
  java.lang.Thread.State: WAITING
	 Incompatible thread state: thread not suspended

"Binder_1@3784" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

"Binder_2@3785" prio=5 runnable
  java.lang.Thread.State: RUNNABLE
	 Incompatible thread state: thread not suspended

**Comment by swankjesse** [comment]
I don't see what the crash is.

**Comment by T7777** [comment]
What is that uncaughtException?

**Comment by iNoles** [comment]
On Android Studio, he would like you to copy a stack trace where full exception occurs in the logcat window, then paste it to here.

**Comment by T7777** [comment]
I'm mainly a Windows developer.  How do I do that?

**Comment by T7777** [comment]
I think I got it.

05-16 21:27:13.342  30213-30213/com.powerlobbies.test I/art﹕ Not late-enabling -Xcheck:jni (already on)
05-16 21:27:13.365  30213-30213/com.powerlobbies.test W/ActivityThread﹕ Application com.powerlobbies.test is waiting for the debugger on port 8100...
05-16 21:27:13.378  30213-30213/com.powerlobbies.test I/System.out﹕ Sending WAIT chunk
05-16 21:27:13.521  30213-30220/com.powerlobbies.test W/art﹕ Suspending all threads took: 16.321ms
05-16 21:27:13.522  30213-30220/com.powerlobbies.test I/art﹕ Debugger is active
05-16 21:27:13.738  30213-30213/com.powerlobbies.test I/System.out﹕ Debugger has connected
05-16 21:27:13.739  30213-30213/com.powerlobbies.test I/System.out﹕ waiting for debugger to settle...
05-16 21:27:13.950  30213-30213/com.powerlobbies.test I/System.out﹕ waiting for debugger to settle...
05-16 21:27:14.159  30213-30213/com.powerlobbies.test I/System.out﹕ waiting for debugger to settle...
05-16 21:27:14.377  30213-30213/com.powerlobbies.test I/System.out﹕ waiting for debugger to settle...
05-16 21:27:14.589  30213-30213/com.powerlobbies.test I/System.out﹕ waiting for debugger to settle...
05-16 21:27:14.799  30213-30213/com.powerlobbies.test I/System.out﹕ waiting for debugger to settle...
05-16 21:27:15.010  30213-30213/com.powerlobbies.test I/System.out﹕ waiting for debugger to settle...
05-16 21:27:15.220  30213-30213/com.powerlobbies.test I/System.out﹕ waiting for debugger to settle...
05-16 21:27:15.430  30213-30213/com.powerlobbies.test I/System.out﹕ debugger has settled (1365)
05-16 21:27:15.614  30213-30213/com.powerlobbies.test D/AndroidRuntime﹕ Shutting down VM
05-16 21:27:15.614  30213-30213/com.powerlobbies.test E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.powerlobbies.test, PID: 30213
    java.lang.RuntimeException: Unable to start activity ComponentInfo{com.powerlobbies.test/com.powerlobbies.test.MainActivity}: android.os.NetworkOnMainThreadException
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
     Caused by: android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
            at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
            at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
            at java.net.InetAddress.getAllByName(InetAddress.java:215)
            at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
            at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:224)
            at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:193)
            at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:113)
            at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:344)
            at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:329)
            at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:319)
            at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
            at com.squareup.okhttp.Call.getResponse(Call.java:271)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
            at com.squareup.okhttp.Call.execute(Call.java:79)
            at com.powerlobbies.test.GetExample.run(MainActivity.java:27)
            at com.powerlobbies.test.MainActivity.onCreate(MainActivity.java:42)
            at android.app.Activity.performCreate(Activity.java:5937)
            at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
            at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
            at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
            at android.app.ActivityThread.access$800(ActivityThread.java:144)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:135)
            at android.app.ActivityThread.main(ActivityThread.java:5221)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
05-16 21:27:55.685  30213-30220/com.powerlobbies.test W/art﹕ Suspending all threads took: 5.824ms

**Comment by JakeWharton** [comment]
You cannot do synchronous HTTP on the main thread. Use enqueue not execute
to run the request asynchronously.

**Comment by T7777** [comment]
Thanks Jake.  I tried enqueue(), but it fails at the same location and there is a ton of entries on the stack, so I am still looking into it.

**Comment by swankjesse** [comment]
I think at this point your best bet is to go to stackoverflow. This tracker is for bug reports & feature requests only; I think you're just suffering the pain of Android's main thread.

**Comment by T7777** [comment]
Yes, now that I know it's a thread issue I am going down that path.  Thanks for the help!
