### ISSUE TITLE
Flaky Spdy3ConnectionTest.receiveGoAway on Android

### ISSUE THREAD

**Issue by nfuller** [square/okhttp#1660]
Likely just a flaky test:

java.io.IOException: shutdown
at com.squareup.okhttp.internal.spdy.SpdyConnection.ping(SpdyConnection.java:377)
at com.squareup.okhttp.internal.spdy.Spdy3ConnectionTest.receiveGoAway(Spdy3ConnectionTest.java:729)

Occurs occasionally (1:10 - 1:20 runs) when running under automated CTS tests on Android with OkHttp sync'd to 3c61fdb2ba9d1ebe0419b93cfbd4e94ffc857fe3. (

**Comment by nfuller** [comment]
Thanks for the fix!
