### ISSUE TITLE
java.lang.IllegalAccessError on 2.4.0 but not on 2.2.0?

### ISSUE THREAD

**Issue by eddnav** [square/okhttp#1680]
Hi Guys, I've run into the following issue while trying to update my gradle build file so I could use the latest mockWebServer:

it went from this:

```groovy
   ...
    compile 'com.squareup.okhttp:okhttp:2.2.0'
    compile 'com.squareup.okio:okio:1.2.0'
```
to this:

```groovy
   ...
    compile 'com.squareup.okhttp:okhttp:2.4.0'
    compile 'com.squareup.okio:okio:1.4.0'
   ...
    testCompile 'com.squareup.okhttp:mockwebserver:2.4.0'
```

I'm also using `'com.android.support:support-v4:21.0.2'` instead of the latest (heads up, just in case it)

Stack trace:
```
4101-4144/no.familieplan.grus E/Event﹕ Could not dispatch event: class no.familieplan.grus.app.event.VerifyUserEvent to subscribing class class no.familieplan.grus.app.service.GrusService
    java.lang.IllegalAccessError: Method 'void com.squareup.okhttp.Call.<init>(com.squareup.okhttp.OkHttpClient, com.squareup.okhttp.Request)' is inaccessible to class 'com.newrelic.agent.android.instrumentation.okhttp2.CallExtension' (declaration of 'com.newrelic.agent.android.instrumentation.okhttp2.CallExtension' appears in /data/app/no.familieplan.grus-2/base.apk)
            at com.newrelic.agent.android.instrumentation.okhttp2.CallExtension.<init>(CallExtension.java:32)
            at com.newrelic.agent.android.instrumentation.okhttp2.OkHttp2Instrumentation.newCall(OkHttp2Instrumentation.java:28)
            at no.familieplan.grus.app.api.GrusApiService.verifyUser(GrusApiService.java:138)
            at no.familieplan.grus.app.service.GrusService.onEventAsync(GrusService.java:539)
            at java.lang.reflect.Method.invoke(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:372)
            at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:477)
            at de.greenrobot.event.EventBus.invokeSubscriber(EventBus.java:472)
            at de.greenrobot.event.AsyncPoster.run(AsyncPoster.java:47)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

Misc: tested on an emulator on API level 21.

As in the issue title explains, this does not happen with a previous version of OkHttp/Okio. Other weirdness include the fact that when debugging the call for `okHttpClient.newCall(request).execute()` I noticed the debugger stops twice in this method (also does not happen on 2.2.0)? Is this issue on my end or OkHttp's?

**Comment by JakeWharton** [comment]
OkHttp's `Call` constructor is package scoped and it looks like NewRelic is trying to do clever things with it. Perhaps the method signature changed between these two releases. This is a NewRelic bug that you should report upstream to them.

> I noticed the debugger stops twice in this method

I'm not quite sure what you mean by this. Got any more info?

**Comment by swankjesse** [comment]
NewRelic probably wants to use OkHttp's Interceptors instead of whatever they're doing currently.

**Comment by eddnav** [comment]
@JakeWharton oh it's just something that I noticed when this happens, as in you put a breakpoint in this call and resume the program it stops again there (doesn't happen with 2.2.0).

Thanks for your input guys, I'll report this to NewRelic.

**Comment by danielgomezrico** [comment]
@eddnav did you report it? where? same happens to me

**Comment by fightingmonk** [comment]
New Relic for Android needs package access to the Call constructor. In 2.4.0 the constructor changed from protected to private, which breaks our instrumentation. This also effects things like mocking frameworks, unfortunately.

A PR reversing the scope change has been merged into OkHttp and this should be fixed with the 2.5 release. https://github.com/square/okhttp/pull/1687

**Comment by danielgomezrico** [comment]
ok thanks

**Comment by pawankumarGowda** [comment]
I am facing similar issue, please support me to solve this. 
i am using 
`implementation "com.squareup.okhttp3:logging-interceptor:4.9.3"
    implementation "com.squareup.okhttp3:okhttp:4.9.3"`

`FATAL EXCEPTION: main
                                                                                                    Process: cargill.com.digitalsaathi, PID: 15400
                                                                                                    java.lang.IllegalAccessError: Field 'okhttp3.OkHttpClient$Builder.eventListenerFactory' is inaccessible to class 'okhttp3.OkHttpClient' (declaration of 'okhttp3.OkHttpClient' appears in /data/app/~~oNgvZAXxf9GUbKeqElAk7w==/cargill.com.digitalsaathi-01pcnYlRj6YXSK_2i4Qxcg==/base.apk!classes21.dex)
                                                                                                    	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:131)
                                                                                                    	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:1079)
                                                                                                    	at com.datadog.android.core.internal.CoreFeature.<clinit>(CoreFeature.kt:72)
                                                                                                    	at com.datadog.android.DatadogInterceptor.<init>(DatadogInterceptor.kt:121)
                                                                                                    	at com.datadog.android.DatadogInterceptor.<init>(DatadogInterceptor.kt:117)`

**Comment by lyubomir-ganev-iu** [comment]
@pawankumarGowda , I have exactly the same issue after I have started a new project that is not targeting java 17 instead of java 8 (due to the new Android Gradle plugin requirements). I'm not sure the issue is caused by that, but it's highly likely since the same version of OkHttp worked just fine for me in the older project where I targeted java 8.

**Comment by yschimke** [comment]
This looks like an R8 bug.  Consider raising an issue for AOSP.

Similar but probably not the same issues
https://issuetracker.google.com/issues/243955191
https://issuetracker.google.com/issues/235576668
https://issuetracker.google.com/issues/157583077

**Comment by lyubomir-ganev-iu** [comment]
@pawankumarGowda , @yschimke ,

We solved the issue for us. I'm happy to report in the end it wasn't an issue in OkHttp client itself.

We use in the project 2 libraries which use internally OkHttp, one of which is also applied through a gradle plugin:

- https://github.com/auth0/Auth0.Android
- https://github.com/getsentry/sentry-android-gradle-plugin

Apparently the gradle plugin one had some issue (https://github.com/getsentry/sentry-android-gradle-plugin/pull/514) and was breaking something with OkHttp. It was only unfortunate that in our case it was manifesting itself also whenever we simply instantiate an OkHttp client through its builder. After updating to the latest fixed sentry gradle plugin version, the issue is now gone.
