### ISSUE TITLE
Intermittent Network is unreachable exception 

### ISSUE THREAD

**Issue by maxim432** [square/okhttp#1700]
We run jobs on AWS EC2 that periodically query multiple external APIs via Retrofit v1.9.0 and OkHttp v2.4.0. For some time this works fine, but after hours or even days of running, network requests to `https://www.googleapis.com` start to fail with "Network is unreachable exception" exception (full stack trace below). We have isolated the problem to OkHttp code by replacing OkHttpClient with UrlConnectionClient which fixes the issue. Interestingly we do not experience this problem with other APIs running in the same process, and the failures affect all or fraction of requests at different times.

Few things we've observed while debugging (may or may not be related):
- www.googleapis.com uses some kind of DNS load balancing and does rotation of several IPs.
- `InetAddress.getByName("www.googleapis.com")` returns IPv4 address.

retrofit.RetrofitError: Network is unreachable
	at retrofit.RetrofitError.networkError(RetrofitError.java:27)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
	at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
	at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
	at retrofit.RxSupport$2.run(RxSupport.java:55)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.run(FutureTask.java:262)
	at com.bento.util.BentoExecutorUtils$1.run(BentoExecutorUtils.java:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Network is unreachable
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:579)
	at com.squareup.okhttp.internal.Platform.connectSocket(Platform.java:100)
	at com.squareup.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
	at com.squareup.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:79)
	at com.squareup.okhttp.Connection.connect(Connection.java:143)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:185)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
	at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
	at com.squareup.okhttp.Call.getResponse(Call.java:273)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
	at com.squareup.okhttp.Call.execute(Call.java:81)
	at retrofit.client.OkClient.execute(OkClient.java:53)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
	... 9 more

**Comment by swankjesse** [comment]
One thing we could definitely do here is provide more information to help debug. We are attempting multiple IP addresses behind-the-scenes (unless you have switched that off) and we can likely report which ones we tried and what the outcomes were.

**Comment by swankjesse** [comment]
... if you want to fork our code, add some instrumentation, and figure out what's going on, that would be very awesome.

**Comment by maxim432** [comment]
Might be tricky to get side jar into our build, Is there is some diagnostics output that can be enabled programmatically?

Also disabling multiple IPs may be worth trying, how would we do that?

**Comment by swankjesse** [comment]
You'll want to manually implement the internal `Network` interface to plug in your own DNS resolution.

**Comment by swankjesse** [comment]
No action for us to take here.
