### ISSUE TITLE
IllegalArgumentException in DiskLruCache (v2.2.0 ~ v2.4.0)

### ISSUE THREAD

**Issue by gfx** [square/okhttp#1709]
We caught the following crash:

```
java.lang.IllegalArgumentException: keys must match regex [a-z0-9_-]{1,64}: "68fac896d061fc06ee23d3e2cREAD"
       at com.android.okhttp.internal.DiskLruCache.validateKey(DiskLruCache.java:655)
       at com.android.okhttp.internal.DiskLruCache.remove(DiskLruCache.java:576)
       at com.android.okhttp.internal.DiskLruCache.trimToSize(DiskLruCache.java:638)
       at com.android.okhttp.internal.DiskLruCache.access$100(DiskLruCache.java:86)
       at com.android.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:169)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

I don't know when the crash occur because it comes from Crashlytics. No member including me has seen it so I have no idea about how to reproduce this issue :(

**Comment by swankjesse** [comment]
Yep, that's a bug in OkHttp somewhere. What version are you using?

**Comment by gfx** [comment]
It occurs on 2.2.0 and 2.4.0. I  never use 2.3.0 so I have no idea about 2.3.0.

**Comment by JakeWharton** [comment]
Your stack trace is from Android's OkHttp, not one that you would be
bundling yourself.

**Comment by gfx** [comment]
OMG! We can do nothing about it right? It's a bad news :(

Thanks anyway.

**Comment by swankjesse** [comment]
@gfx just make sure you're using the cache that's bundled with OkHttp, not the one that comes with Android.

**Comment by gfx** [comment]
@swankjesse Yep, I use OkHttp's DiskLruCache.

**Comment by iNoles** [comment]
If that is true, you may not to do it correctly because anybody can see com.android.okhttp.internal.DiskLruCache in that stack trace.

**Comment by gfx** [comment]
This is reported in android issue tracker: https://code.google.com/p/android/issues/detail?id=82889
