### ISSUE TITLE
No retry/failover on Android with setConnectTimeout() set

### ISSUE THREAD

**Issue by matejsnoha** [square/okhttp#1736]
When using OkHttpClient with setConnectTimeout() set to 10 seconds on Android, I get a SocketTimeoutException after 10 seconds if it picks an unreachable IP (another IP is reachable). 

When I do not call setConnectTimeout(), the request runs for a few minutes (seems to be different on different Android versions) while waiting for the unreachable IP and then correctly fails over to the reachable IP and returns response.

On desktop the behaviour is correct, the request always returns response from the one available IP and in a very short time.

My setup:
DNS name with 2 IPv4 A addresses, 1 is unreachable.
OkHttp 2.4.0
Android 4.1.1 and 5.0

    java.net.SocketTimeoutException: failed to connect to host/unreachable-ip (port 443) after 10000ms
    at libcore.io.IoBridge.connectErrno(IoBridge.java:159)
    at libcore.io.IoBridge.connect(IoBridge.java:112)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:192)
    at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:459)
    at java.net.Socket.connect(Socket.java:842)
    at com.squareup.okhttp.internal.Platform$Android.connectSocket(Platform.java:190)
    at com.squareup.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
    at com.squareup.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:79)
    at com.squareup.okhttp.Connection.connect(Connection.java:143)
    at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:185)
    at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
    at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
    at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
    at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
    at com.squareup.okhttp.Call.getResponse(Call.java:273)
    at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
    at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
    at com.squareup.okhttp.Call.execute(Call.java:81)

**Comment by warpspin** [comment]
I think I had the same problem with some of our users who used our app on an improperly configured IPv6 connection - the IPv6 connection times out while IPv4 would work. Unfortunately I have no stacktraces at the moment, as our stacktrace reporting also relies on okhttp. Is there a fix already in git which I could apply to my okhttp copy - or when is the 2.5 milestone scheduled for? I have to decide whether to wait for okhttp 2.5 with my next release or not.

**Comment by swankjesse** [comment]
Not fixed yet, and 2.5 likely won't be done till late August or September.

**Comment by warpspin** [comment]
Ok, thanks for your answer. I managed to re-create a full stacktrace now, by the way. And the behaviour seems to be identical for me, no matter whether I use setConnectTimeout or not, but that could maybe be because I use the URLConnection API.

```stacktrace
java.net.SocketTimeoutException: failed to connect to www.spin.de/2001:780:138:480::d55f:4f2a (port 443) after 30000ms
            at libcore.io.IoBridge.connectErrno(IoBridge.java:169)
            at libcore.io.IoBridge.connect(IoBridge.java:122)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
            at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
            at java.net.Socket.connect(Socket.java:882)
            at com.squareup.okhttp.internal.Platform$Android.connectSocket(Platform.java:190)
            at com.squareup.okhttp.internal.http.SocketConnector.connectRawSocket(SocketConnector.java:160)
            at com.squareup.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:79)
            at com.squareup.okhttp.Connection.connect(Connection.java:143)
            at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:185)
            at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
            at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
            at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
            at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
            at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:433)
            at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:114)
            at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:245)
            at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
            at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:25)
            at de.spin.http.SerializableAsParams.writePostBody(SerializableAsParams.java:18)
            at de.spin.http.HttpParams.writePostBody(HttpParams.java:195)
            at de.spin.http.HttpRequest.attemptConnection(HttpRequest.java:82)
            at de.spin.http.HttpRequest.call(HttpRequest.java:39)
            at de.spin.http.HttpRequest.call(HttpRequest.java:11)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

**Comment by warpspin** [comment]
Sorry to spam this here but in case someone has the same problem as me: I could fix the issue based on the okhttp 2.4 snapshot by inserting

```java
    if (ioe instanceof SocketTimeoutException ) {
        return true;
    }
```

in HttpEngine.isRecoverable(RouteException e) IN FRONT OF the if (ioe instanceof InterruptedIOException) check. (line 457), as a SocketTimeoutException is also an InterruptedIOException but InterruptedIOExceptions count as non-recoverable.

For a future okhttp version, I'd wish it would, at least for the IPv4/IPv6 dual stack case, always connect to both sockets non-blocking and use whichever socket connects first, but from what I've seen in the source code now this is probably a very non-trivial change.

**Comment by matejsnoha** [comment]
Thanks, your fix works for me too.
Also there is already an issue for the dual-stack parallel connecting - #506 .

**Comment by jleidgens** [comment]
This is assigned to the 2.5 Milestone but not closed. Did it make it into the release?

**Comment by thest1** [comment]
Hi Guys! Let me contribute a little.

I have complains from my users about the same problem. My app doesn't want to connect in some misconfigured IPv6 networks. But all browsers work fine due to Happy Eyeballs.

Fix from warpspin is great, I can see it's already in master. But unfortunately it doesn't solve my problem. It still makes me wait until connection timeouts before trying the next IP. My users never agree to wait for so long.

Happy Eyeballs is a perfect solution. But running two connections in parallel seems to be an architecture change, reasonable effort to get implementation stable enough.

Please review my approach. It's very easy and straightforward. And seems to work fine for my users. So I want to know what you thing about it.

When we get a list of IPs from DNS why don't we just reorder them. IPv4 should go first, IPv6 after them. This way application will try to use IPv4 first. And IPv4 should work in most cases. We'll fallback to IPv6 only if IPv4 fails. In real world right now IPv4 is used much more often than IPv6 so prioritisation probably makes sense.

But I'm still concerned about that. Is it safe enough to change the order? Maybe an optional thing. I'll create a pull request just for a review.
