### ISSUE TITLE
Unexpected end of stream on Connection

### ISSUE THREAD

**Issue by ppamorim** [square/okhttp#1741]
I have disabled the setRetryOnConnectionFailure() and sometimes the request returns  "unexpected end of stream on Connection". If I try again, randomly it get success. Anyone can help me?

    java.io.IOException: unexpected end of stream on Connection{myapp.com.br, proxy=DIRECT@ hostAddress=54.94.155.109 cipherSuite=none protocol=http/1.1} (recycle count=1)
    at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:211)
    at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
    at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:917)
    at com.squareup.okhttp.internal.http.HttpEngine.access$300(HttpEngine.java:95)
    at     com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:902)
    at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:760)
    at com.squareup.okhttp.Call.getResponse(Call.java:274)
    at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
    at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
    at com.squareup.okhttp.Call.execute(Call.java:81)

**Comment by ppamorim** [comment]
@JakeWharton any solution?

**Comment by swankjesse** [comment]
Not much we can do here. From OkHttp's perspective the response was truncated, and we return that error to the user. It's likely that either your webserver or your network is to blame.

**Comment by Balajipss** [comment]
We had the similar issue. Adding below lines solved the issue

headers:{
Accept: 'application/json',
'Content-Type': 'application/json',
'Cache-Control':'no-cache'
},
