### ISSUE TITLE
OkHttp can not get data on Coolpad8297 in China!!

### ISSUE THREAD

**Issue by Saxxhw** [square/okhttp#1762]
```javascript
07-24 04:38:37.639      151-519/? I/SurfaceTexture﹕ [com.wxw.http/com.wxw.http.MainActivity](this:0x44014320,api:1) [void* android::SurfaceTexture::createImage(EGLDisplay, const android::sp<android::GraphicBuffer>&)]
07-24 04:38:37.644  31102-31987/com.wxw.http W/System.err﹕ java.io.IOException: unexpected end of stream on Connection{wap2.yojianzhi.com:80, proxy=DIRECT@ hostAddress=123.57.46.40 cipherSuite=none protocol=http/1.1} (recycle count=0)
07-24 04:38:37.644  31102-31987/com.wxw.http W/System.err﹕ at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:211)
07-24 04:38:37.645  31102-31987/com.wxw.http W/System.err﹕ at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
07-24 04:38:37.645  31102-31987/com.wxw.http W/System.err﹕ at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:917)
07-24 04:38:37.645  31102-31987/com.wxw.http W/System.err﹕ at com.squareup.okhttp.internal.http.HttpEngine.access$300(HttpEngine.java:95)
07-24 04:38:37.645  31102-31987/com.wxw.http W/System.err﹕ at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:902)
07-24 04:38:37.645  31102-31987/com.wxw.http W/System.err﹕ at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:760)
07-24 04:38:37.645  31102-31987/com.wxw.http W/System.err﹕ at com.squareup.okhttp.Call.getResponse(Call.java:274)
07-24 04:38:37.645  31102-31987/com.wxw.http W/System.err﹕ at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
07-24 04:38:37.645  31102-31987/com.wxw.http W/System.err﹕ at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
07-24 04:38:37.645  31102-31987/com.wxw.http W/System.err﹕ at com.squareup.okhttp.Call.execute(Call.java:81)
07-24 04:38:37.645  31102-31987/com.wxw.http W/System.err﹕ at com.wxw.http.utils.OkHttpUtil.get(OkHttpUtil.java:40)
07-24 04:38:37.646  31102-31987/com.wxw.http W/System.err﹕ at com.wxw.http.utils.WebServiceUtil.getArray(WebServiceUtil.java:27)
07-24 04:38:37.646  31102-31987/com.wxw.http W/System.err﹕ at com.wxw.http.web.TestService.myTest(TestService.java:18)
07-24 04:38:37.647  31102-31987/com.wxw.http W/System.err﹕ at com.wxw.http.impl.TestImp.getLbtData(TestImp.java:18)
07-24 04:38:37.647  31102-31987/com.wxw.http W/System.err﹕ at com.wxw.http.MainActivity.getTaskData(MainActivity.java:49)
07-24 04:38:37.647  31102-31987/com.wxw.http W/System.err﹕ at com.wxw.http.base.BaseAty$1.run(BaseAty.java:31)
07-24 04:38:37.647  31102-31987/com.wxw.http W/System.err﹕ at java.lang.Thread.run(Thread.java:838)
07-24 04:38:37.647  31102-31987/com.wxw.http W/System.err﹕ Caused by: java.io.EOFException: \n not found: size=535 content=485454502f312e3120323030204f4b0d0a446174653a204672692c203234204a...
07-24 04:38:37.648  31102-31987/com.wxw.http W/System.err﹕ at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:200)
07-24 04:38:37.648  31102-31987/com.wxw.http W/System.err﹕ at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:191)
07-24 04:38:37.648  31102-31987/com.wxw.http W/System.err﹕ ... 16 more
07-24 04:38:37.648  31102-31987/com.wxw.http D/dalvikvm﹕ threadid=11: exiting
07-24 04:38:37.648  31102-31987/com.wxw.http D/dalvikvm﹕ threadid=11: bye!

```

**Comment by Saxxhw** [comment]
My English is not good，thank you。。。

**Comment by swankjesse** [comment]
Fixed in the next release.
