### ISSUE TITLE
ArrayIndexOutOfBoundsException when socket.connect(address, connectTimeout)

### ISSUE THREAD

**Issue by JackCho** [square/okhttp#1776]
java.lang.ArrayIndexOutOfBoundsException: length=4; index=1153466837
       at java.util.HashMap.put(HashMap.java:407)
       at android.content.Context$1.isNetworkDenied(Context.java:3233)
       at java.net.Socket.connect(Socket.java:867)
       at com.squareup.okhttp.internal.Platform$Android.connectSocket(SourceFile:190)
       at com.squareup.okhttp.internal.http.SocketConnector.connectRawSocket(SourceFile:160)
       at com.squareup.okhttp.internal.http.SocketConnector.connectCleartext(SourceFile:67)
       at com.squareup.okhttp.Connection.connect(SourceFile:152)
       at com.squareup.okhttp.Connection.connectAndSetOwner(SourceFile:185)
       at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(SourceFile:128)
       at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(SourceFile:341)
       at com.squareup.okhttp.internal.http.HttpEngine.connect(SourceFile:330)
       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(SourceFile:248)
       at com.squareup.okhttp.Call.getResponse(SourceFile:273)
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(SourceFile:230)
       at com.squareup.okhttp.Call.getResponseWithInterceptorChain(SourceFile:201)
       at com.squareup.okhttp.Call.access$100(SourceFile:36)
       at com.squareup.okhttp.Call$AsyncCall.execute(SourceFile:164)
       at com.squareup.okhttp.internal.NamedRunnable.run(SourceFile:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:848)

**Comment by JackCho** [comment]
okhttp version : 2.4.0

**Comment by swankjesse** [comment]
FYI @nfuller, this looks like a bug in AOSP. Nothing to do in OkHttp.

**Comment by nfuller** [comment]
@JackCho That stack trace suggests an OEM-specific modification. I can't find any branch where these lines match up with source:

at android.content.Context$1.isNetworkDenied(Context.java:3233)
at java.net.Socket.connect(Socket.java:867)

Can you tell me what device and android release this is? 

It would help me be sure I haven't missed somethign and I may be able to get in contact with the OEM to let them know / warn them if I can get the details.

**Comment by JackCho** [comment]
@nfuller this bug happens on  Xiaomi,Meizu devices and on android releases of 4.4.4, 4.1.1, 4.2.1.
After we switch our http client to okhttp, the bug just shows up.
This link is from fabric : http://crashes.to/s/1b42e16d2ea

**Comment by nfuller** [comment]
@JackCho Thanks for the link and details. I will try to pass this on to the OEM. In the meantime I'm guessing that the code is not properly synchronized around a data structure that was added to Context. The only thing I can think of for these existing devices would be to add some synchronization further up the stack. e.g. com.squareup.okhttp.internal.Platform$Android.connectSocket to try to limit the number of OkHttp threads passing through that code.

Here's why I'm pointing fingers. Looking for that Context line number in 4.4.4:

https://android.googlesource.com/platform/frameworks/base/+/android-4.4.4_r1.0.1/core/java/android/content/Context.java
https://android.googlesource.com/platform/frameworks/base/+/android-4.4.4_r2.0.1/core/java/android/content/Context.java

I'm just back from 2-weeks vacation and looking through a mountain of email. I've seen from the summary that SocketConnector has been deleted (https://github.com/square/okhttp/pull/1782), but I don't know the details. I'm currently assuming that wouldn't affect this but I could be wrong.
