### ISSUE TITLE
Received NetworkOnMainThreadException after cancel AsyncCall

### ISSUE THREAD

**Issue by minakov** [square/okhttp#1777]
```
uiHandler = new Handler(Looper.getMainLooper());
uiHandler.post(new Runnable() {
  @Override
  public void run() {
    call.enqueue(...)
    call.cancel();
  }
});
```

```
    android.os.NetworkOnMainThreadException
            at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1166)
            at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1010)
            at com.squareup.okhttp.Connection.closeIfOwnedBy(Connection.java:132)
            at com.squareup.okhttp.OkHttpClient$1.closeIfOwnedBy(OkHttpClient.java:75)
            at com.squareup.okhttp.internal.http.HttpConnection.closeIfOwnedBy(HttpConnection.java:137)
            at com.squareup.okhttp.internal.http.HttpTransport.disconnect(HttpTransport.java:135)
            at com.squareup.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:583)
            at com.squareup.okhttp.Call.cancel(Call.java:124)
```

**Comment by JakeWharton** [comment]
Dupe #869 . See also #1592.
