### ISSUE TITLE
Attempt to invoke virtual method 'void java.net.Socket.close()' on a null object reference

### ISSUE THREAD

**Issue by kdpdev** [square/okhttp#1787]
I try to check fix for Cannot cancel async post/get requests. #1779 and got null pointer exception.
Trace:
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.net.Socket.close()' on a null object reference
            at com.squareup.okhttp.Connection.closeIfOwnedBy(Connection.java:147)
            at com.squareup.okhttp.OkHttpClient$1.closeIfOwnedBy(OkHttpClient.java:75)
            at com.squareup.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:577)
            at com.squareup.okhttp.Call.cancel(Call.java:122)

Steps to reproduce are described in #1779. But there is one detail:
When i am trying to connect to not started server, i got onFailure as expected. But a little bit later i invoke call.cancel() for that failed call.

The code in Connection.java (lines 174-175) closes the socket and makes it nullable:
        Util.closeQuietly(socket);
        socket = null;

**Comment by felipecsl** [comment]
+1 also seeing this quite a few times

**Comment by SeanA208** [comment]
+1
