### ISSUE TITLE
AsyncCall NPE's if an interceptor throws before the call is attempted.

### ISSUE THREAD

**Issue by GrahamFirst** [square/okhttp#1801]
AsyncCall throws an uncaught NullPointerException [here](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/com/squareup/okhttp/Call.java#L175) because engine is null, having never been initialized, if the call was never attempted.  For example, this can happen if an ("application-level") interceptor aborted the call by throwing an IOException before the call was ever attempted.

I suggest that it could simply pass a null request to the callback in this case instead.

**Comment by ansman** [comment]
I'm getting the same problem, here's the stacktrace:
```
java.lang.NullPointerException: Attempt to invoke virtual method 'com.squareup.okhttp.Request com.squareup.okhttp.internal.http.HttpEngine.getRequest()' on a null object reference
    at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:175)
    at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)
```
