### ISSUE TITLE
Handshake failed

### ISSUE THREAD

**Issue by ghazel** [square/okhttp#1806]
I am having the same issue as #1543 and #1582. If I add TLSv1.2 to my nginx server, OkHttp spits "Handshake failed":

this nginx.conf works:
```nginx
ssl_protocols TLSv1 TLSv1.1;# TLSv1.2;
```

this nginx.conf does not:
```nginx
ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
```

exception:
```java
08-17 02:28:49.850 E/MyApp(28623): javax.net.ssl.SSLHandshakeException: Handshake failed
08-17 02:28:49.850 E/MyApp(28623): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:392)
08-17 02:28:49.850 E/MyApp(28623): 	at com.android.okhttp.Connection.upgradeToTls(Connection.java:1243)
08-17 02:28:49.850 E/MyApp(28623): 	at com.android.okhttp.Connection.connect(Connection.java:1174)
08-17 02:28:49.850 E/MyApp(28623): 	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:380)
08-17 02:28:49.850 E/MyApp(28623): 	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:289)
08-17 02:28:49.850 E/MyApp(28623): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
08-17 02:28:49.850 E/MyApp(28623): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
08-17 02:28:49.850 E/MyApp(28623): 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getHeaderFields(HttpURLConnectionImpl.java:169)
08-17 02:28:49.850 E/MyApp(28623): 	at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getHeaderFields(DelegatingHttpsURLConnection.java:178)
08-17 02:28:49.850 E/MyApp(28623): 	at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getHeaderFields(HttpsURLConnectionImpl.java:25)
08-17 02:28:49.850 E/MyApp(28623): 	at com.MyApp.processConnection(MyApp.java:266)
08-17 02:28:49.850 E/MyApp(28623): 	at com.MyApp.access$100(MyApp.java:49)
08-17 02:28:49.850 E/MyApp(28623): 	at com.MyApp$3$1.run(MyApp.java:341)
08-17 02:28:49.850 E/MyApp(28623): Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0xa9a71000: Failure in SSL library, usually a protocol error
08-17 02:28:49.850 E/MyApp(28623): error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:770 0xaecb7679:0x00000000)
08-17 02:28:49.850 E/MyApp(28623): 	at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
08-17 02:28:49.850 E/MyApp(28623): 	at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:320)
08-17 02:28:49.850 E/MyApp(28623): 	... 12 more
```

My connection initialization goes something like:
```java
    KeyStore keystore = KeyStore.getInstance(KeyStore.getDefaultType());
    keystore.load(null);
    keystore.setCertificateEntry("cert-alias", base64ToCert(MY_KEY));

    TrustManagerFactory tmf = TrustManagerFactory.getInstance("X509");
    tmf.init(keystore);

    SSLContext context = SSLContext.getInstance("TLS");
    context.init(null, tmf.getTrustManagers(), null);

    URL url = new URL(urlString);
    HttpsURLConnection connection = (HttpsURLConnection) url.openConnection();
    connection.setSSLSocketFactory(context.getSocketFactory());

    return connection;
```

This is Android 5.0, on a Samsung Galaxy S5. (Yes, I tried calling `SSLContext.getInstance("TLSv1.2")` instead.)

**Comment by swankjesse** [comment]
Not much action we can take unfortunately. If there's something we can change in OkHttp to make this work better, I'm happy to accept a pull request. But right now it seems like this is a problem with your device's TLS stack.

**Comment by ghazel** [comment]
Hm. It is true that this does not occur on a Nexus 6.

Have you seen this issue before? What sorts of devices?

**Comment by IgorGanapolsky** [comment]
It occurs on all of my Lollipop devices now.
