### ISSUE TITLE
NetworkOnMainThread exception on response.body() 

### ISSUE THREAD

**Issue by tuhin10** [square/okhttp#1815]
I am getting NetworkOnMainThread exception while retrieving the response body. I am using the Async mode with callbacks, and getting the exception on 

@Override public void onResponse(Response response) throws IOException { 
          String responseBody = response.body().string();   //Exception
      }
    });

this code is working fine on Android 5.0.2 but in Android 4.4.4 I am getting the exception.

**Comment by swankjesse** [comment]
Can you provide the full stack trace?

**Comment by tuhin10** [comment]
android.os.NetworkOnMainThreadException
at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1154)
at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:163)
at libcore.io.IoBridge.recvfrom(IoBridge.java:506)
at java.net.PlainSocketImpl.read(PlainSocketImpl.java:489)
at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:241)
at okio.Okio$2.read(Okio.java:139)
at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
at okio.RealBufferedSource.read(RealBufferedSource.java:50)
at com.squareup.okhttp.internal.http.HttpConnection$ChunkedSource.read(HttpConnection.java:464)
at com.squareup.okhttp.internal.Util.skipAll(Util.java:176)
at com.squareup.okhttp.internal.Util.discard(Util.java:158)
at com.squareup.okhttp.internal.http.HttpConnection$ChunkedSource.close(HttpConnection.java:499)
at okio.RealBufferedSource.close(RealBufferedSource.java:374)
at com.squareup.okhttp.internal.Util.closeQuietly(Util.java:90)
at com.squareup.okhttp.ResponseBody.bytes(ResponseBody.java:59)
at com.squareup.okhttp.ResponseBody.string(ResponseBody.java:83)
at com.test.app.HomeActivity$50$1$1.run(HomeActivity.java:183)
at android.os.Handler.handleCallback(Handler.java:733)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5095)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
at dalvik.system.NativeStart.main(Native Method)

**Comment by swankjesse** [comment]
It appears the `onResponse` method isn't in your stacktrace. If you're explicitly passing the `ResponseBody` to your main thread to do I/O there, I can't stop you.

**Comment by tuhin10** [comment]
private Call uploadImage(Callback callback){    
    	  OkHttpClient client = new OkHttpClient();
    	
          RequestBody formBody = new FormEncodingBuilder()
          .add("param_1", "1234")
          .add("param_2", "acv")
          .build();
    	
        Request request = new Request.Builder()
        .url(URL)
        .post(formBody)
        .build();
	  
	    Call call = client.newCall(request);
	    call.enqueue(callback);
	    return call;        
    }
	
		uploadImage(new Callback() {
		  @Override public void onResponse(final com.squareup.okhttp.Response response)  {				     					
					final String responseStr;					     					    
					try {
						responseStr = response.body().string();
						HomeActivity.this.runOnUiThread(new Runnable() {
								   public void run() {
								     			//Update UI here									     						
									     }
									});								     						
						} catch (IOException e) {
							e.printStackTrace();
						}  						     					 
				     }
		@Override
		public void onFailure(Request req, IOException exp) {
			}
		});

I have updated the code as above .. no more exception. But is correct way to call it Asynchronously?

**Comment by swankjesse** [comment]
Yep, that's reasonable.
