### ISSUE TITLE
OkHttp throwing exception on 401.

### ISSUE THREAD

**Issue by jojojames** [square/okhttp#1822]
--- End of managed exception stack trace ---
java.net.SocketException: sendto failed: EPIPE (Broken pipe)
	at libcore.io.IoBridge.maybeThrowAfterSendto(IoBridge.java:547)
	at libcore.io.IoBridge.sendto(IoBridge.java:516)
	at java.net.PlainSocketImpl.write(PlainSocketImpl.java:508)
	at java.net.PlainSocketImpl.access$100(PlainSocketImpl.java:46)
	at java.net.PlainSocketImpl$PlainSocketOutputStream.write(PlainSocketImpl.java:270)
	at okio.Okio$1.write(Okio.java:80)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:155)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
	at okio.RealBufferedSink.write(RealBufferedSink.java:46)
	at com.squareup.okhttp.internal.http.HttpConnection$FixedLengthSink.write(HttpConnection.java:302)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
	at okio.RealBufferedSink.write(RealBufferedSink.java:46)
	at okio.ForwardingSink.write(ForwardingSink.java:35)
	at md52084f192e2c86223300d53b5b6d1e5a4.CountingSink.n_write(Native Method)
	at md52084f192e2c86223300d53b5b6d1e5a4.CountingSink.write(CountingSink.java:28)
	at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:176)
	at okio.RealBufferedSink.writeAll(RealBufferedSink.java:104)
	at com.squareup.okhttp.RequestBody$3.writeTo(RequestBody.java:118)
	at md52084f192e2c86223300d53b5b6d1e5a4.CountRequestBody.n_writeTo(Native Method)
	at md52084f192e2c86223300d53b5b6d1e5a4.CountRequestBody.writeTo(CountRequestBody.java:46)
	at com.squareup.okhttp.MultipartBuilder$MultipartRequestBody.writeOrCountBytes(MultipartBuilder.java:277)
	at com.squareup.okhttp.MultipartBuilder$MultipartRequestBody.writeTo(MultipartBuilder.java:297)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:887)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:749)
	at com.squareup.okhttp.Call.getResponse(Call.java:268)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
	at md52084f192e2c86223300d53b5b6d1e5a4.OkHttpLoggingInterceptor.n_intercept(Native Method)
	at md52084f192e2c86223300d53b5b6d1e5a4.OkHttpLoggingInterceptor.intercept(OkHttpLoggingInterceptor.java:29)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:221)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at mono.java.lang.Runnable.n_run(Native Method)
	at mono.java.lang.Runnable.run(Runnable.java:29)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at mono.java.lang.RunnableImplementor.n_run(Native Method)
	at mono.java.lang.RunnableImplementor.run(RunnableImplementor.java:29)
	at java.lang.Thread.run(Thread.java:841)

I am doing a multipart upload where I am triggering a 401 on the server. 

On an LG-D851 (Android 4.4.2), an exception is being thrown before I get back the response code. On other devices, the same code doesn't throw the exception and the response code is returned normally.

CountRequestBody is just a simple subclassed RequestBody that allows me to track progress.

**Comment by JakeWharton** [comment]
What makes you think this has to do with a 401 response? The stack trace indicates that this is just a broken connection to the server which is the result of the general flakiness of mobile connections.

**Comment by jojojames** [comment]
I point my client to my development server and have the server return a 401. It happens everytime on some devices and not on others.

**Comment by swankjesse** [comment]
@jojojames could you provide us with a test case to isolate the problem? There's some examples in `CallTest.java` to get you started.

**Comment by jojojames** [comment]
I will try when time frees up.
