### ISSUE TITLE
OkHttp.Builder#setQueryParameter uses too optimistic encoding

### ISSUE THREAD

**Issue by paour** [square/okhttp#1825]
The following code throws an exception when HttpUrl tries to build a java.net.URI, which is overly strict…
```java
      String jsonObject = "{}";
      OkHttpClient client = new OkHttpClient();
      Request request = new Request.Builder()
          .url(HttpUrl.parse("http://www.example.com")
              .newBuilder()
              // HttpUrl.Builder doesn't properly encode curly braces (at least from java.net.URI's point of view)
              .setQueryParameter("config", jsonObject)
              // this works, but URLEncoder!
              //.setEncodedQueryParameter("config", URLEncoder.encode(jsonObject))
              .build())
          .get()
          .build();
      Response response = client.newCall(request).execute();
```

Regrettably, OkHttp should use a more extended set of characters to encode, similar to the 2.5.0 change with URL encoding.

**Comment by swankjesse** [comment]
Does it work with OkHttp 2.5.0 ?

**Comment by swankjesse** [comment]
(We avoid `java.net.URI` internally for this reason)

**Comment by paour** [comment]
2.5.0 didn't change this as far as I can tell. The exception happens in OkHttp code, where `java.net.URI` is indeed used:

```
java.lang.IllegalStateException: not valid as a java.net.URI: https://www.example.com?config={}
at com.squareup.okhttp.HttpUrl.uri(HttpUrl.java:336)
at com.squareup.okhttp.internal.http.RouteSelector.resetNextProxy(RouteSelector.java:135)
at com.squareup.okhttp.internal.http.RouteSelector.<init>(RouteSelector.java:71)
at com.squareup.okhttp.internal.http.RouteSelector.get(RouteSelector.java:76)
at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:321)
at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
at com.squareup.okhttp.Call.getResponse(Call.java:267)
at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
at com.squareup.okhttp.Call.execute(Call.java:79)
```

**Comment by swankjesse** [comment]
Yup. Ugh! If we escape it just for the benefit or URI, maybe that makes everything better.

**Comment by paour** [comment]
Hard to escape legacy code, isn't it? ;-)

**Comment by swankjesse** [comment]
Fixed with https://github.com/square/okhttp/pull/1959
