### ISSUE TITLE
Websocket enqueue with cache produces a crash when server refuses connection

### ISSUE THREAD

**Issue by andresesfm** [square/okhttp#1826]
Setup
```
File cacheDirectory = new File(app.getCacheDir(), "network_cache");
        if (!cacheDirectory.exists()) {
            cacheDirectory.mkdir();
        }
        Cache cache = new Cache(cacheDirectory, CACHE_MAX_SIZE);
        OkHttpClient okHttpClient = new OkHttpClient();
        okHttpClient.networkInterceptors().add(new StethoInterceptor());
        okHttpClient.setCache(cache);
```
Causes this exception with no possibility to be caught:
```
Process: xx.xx.xx.debug, PID: 8227
    java.lang.NullPointerException: Attempt to invoke virtual method 'okio.BufferedSource com.squareup.okhttp.ResponseBody.source()' on a null object reference
            at com.squareup.okhttp.internal.http.HttpEngine.cacheWritingResponse(HttpEngine.java:935)
            at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:821)
            at com.squareup.okhttp.Call.getResponse(Call.java:268)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
            at com.squareup.okhttp.Call.access$100(Call.java:34)
            at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
```

Removing the cache fixes the issue
```
        OkHttpClient okHttpClient = new OkHttpClient();
        okHttpClient.networkInterceptors().add(new StethoInterceptor());
```

I know this is an edge case but it would be nice to be able to catch this exception somewhere.

This happens with okhttp 2.5 and okhttp-ws 2.5. With  okhttp 2.4 and okhttp-ws 2.4 we got a crash with no stacktrace

**Comment by JakeWharton** [comment]
This was fixed as a side-effect of https://github.com/square/okhttp/pull/2831.
