### ISSUE TITLE
Crash with Facebook sdk

### ISSUE THREAD

**Issue by huyduongtu** [square/okhttp#1837]
In my code, I initialize a singleton of OkHttpClient
```
private static OkHttpClient defaultOkHttpClient() {
        if(clientokHttp == null){
            int connectTimeout = AQUtility.getNetworkTimeOut(Constants.TYPE_HTTP_LOAD_IMAGE);
            clientokHttp = new OkHttpClient();
            clientokHttp.setConnectTimeout(connectTimeout, TimeUnit.MILLISECONDS);
            clientokHttp.setReadTimeout(DEFAULT_READ_TIMEOUT_MILLIS, TimeUnit.MILLISECONDS);
            clientokHttp.setWriteTimeout(DEFAULT_WRITE_TIMEOUT_MILLIS, TimeUnit.MILLISECONDS);
        }

        return clientokHttp;
    }
```

And here is the stacktrace:
```
java.lang.NullPointerException
at com.android.org.conscrypt.OpenSSLSocketFactoryImpl.createSocket(OpenSSLSocketFactoryImpl.java:94)
at com.android.okhttp.Connection.upgradeToTls(Connection.java:131)
at com.android.okhttp.Connection.connect(Connection.java:107)
at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:296)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:503)
at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:136)
at com.facebook.GraphResponse.java.util.List fromHttpConnection(java.net.HttpURLConnection,com.facebook.GraphRequestBatch)(SourceFile:253)
at com.facebook.GraphRequest.java.util.List executeConnectionAndWait(java.net.HttpURLConnection,com.facebook.GraphRequestBatch)(SourceFile:1130)
at com.facebook.GraphRequest.java.util.List executeBatchAndWait(com.facebook.GraphRequestBatch)(SourceFile:1032)
at com.facebook.GraphRequest.java.util.List executeBatchAndWait(java.util.Collection)(SourceFile:999)
at com.facebook.GraphRequest.java.util.List executeBatchAndWait(com.facebook.GraphRequest[])(SourceFile:983)
at com.facebook.GraphRequest.com.facebook.GraphResponse executeAndWait(com.facebook.GraphRequest)(SourceFile:958)
at com.facebook.GraphRequest.com.facebook.GraphResponse executeAndWait()(SourceFile:854)
at com.facebook.internal.Utility.org.json.JSONObject getAppSettingsQueryResponse(java.lang.String)(SourceFile:893)
at com.facebook.internal.Utility.org.json.JSONObject access$000(java.lang.String)(SourceFile:75)
at com.facebook.internal.Utility$1.void run()(SourceFile:802)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
```

**Comment by swankjesse** [comment]
FYI @nfuller 

Can you isolate this?

**Comment by huyduongtu** [comment]
Thanks for your quick reply.
It happened a lot on device ASUS ZenFone 4 ASUS_T00Q, OS version 4.4.2.
I don't know how to reproduce this bug. It's the stacktrace reported to my google play account.
In my application, I don't enable SPDY for the shared SSL context.

**Comment by nfuller** [comment]
This all looks like the Android built-in copy of OkHttp and socket factory.

I couldn't isolate the exact version of the code, but I can tell from the stack trace that the platform-embedded version of okhttp / SSLSocketFactory is being used. The crash is highly likely to be because the SSLParametersImpl object is null (assuming the OEM hasn't modified the code themselves).

If so, something has caused the socket factory to end up with a null SSLParametersImpl object. Since the socket factory being picked up by OkHttp/HttpURLConnection will be the one provided by SSLSocketFactory.getDefault(), it's possible some code elsewhere in the app has configured a new instance, or modified the existing instance.

The SSLParametersImpl object is picked up with SSLParametersImpl.getDefault() or it is passed in, depending on which constructor is used. From a sampling of versions of the code, SSLParametersImpl.getDefault() doesn't look like it can return null. The one standard codepath I could find that passes SSLParametersImpl to the factory also guards against null (OpenSSLContextImpl).

The only similar stack trace I can find is here: https://groups.google.com/forum/#!topic/robovm/HU-SNvMSGnY - but that's in robovm and suggests misconfiguration.

Are you, or any of the libraries you're using, manipulating the socket factory, security provider or SSL context?

**Comment by huyduongtu** [comment]
I'm using Facebook sdk and ACRA library in my application.
I'm afraid of them related to socket factory or SSL context.

**Comment by swankjesse** [comment]
No action for us to take here.
