### ISSUE TITLE
EBADF Exception

### ISSUE THREAD

**Issue by iooly** [square/okhttp#1850]
hello, with approach #1817 , i also has a Errno Exception, it happens on HttpConnection.readResponse not close, this is the stack trace:
java.lang.AssertionError: libcore.io.ErrnoException: getsockname failed: EBADF (Bad file number)
at libcore.io.IoBridge.getSocketLocalAddress(IoBridge.java:670)
at libcore.io.IoBridge.recvfrom(IoBridge.java:569)
at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
at okio.Okio$2.read(Okio :148)
at okio.AsyncTimeout$2.read(AsyncTimeout:227)
at okio.RealBufferedSource.indexOf(RealBufferedSource:339)

at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource:217)
at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection:199)
at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport:86)
at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine:923)
at com.squareup.okhttp.internal.http.HttpEngine.access$300(HttpEngine:91)
at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine:908)
at com.squareup.okhttp.Call.com.iooly.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine:763)
at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call:228)
at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call:196)

**Comment by swankjesse** [comment]
Fixed in the next release.

**Comment by swankjesse** [comment]
Actually, it isn't! But here's the fix:
https://github.com/square/okio/pull/170

**Comment by iooly** [comment]
ok, thanks for fixing it
