### ISSUE TITLE
NetworkOnMainThreadException on Cancel

### ISSUE THREAD

**Issue by snadjafi** [square/okhttp#1862]
Call.cancel() throws a android.os.NetworkOnMainThreadException

I am getting a `android.os.NetworkOnMainThreadException` from `Call.cancel()`. Also I am not using `StrickMode.`

```
E/AndroidRuntime: FATAL EXCEPTION: main
E/AndroidRuntime: Process: com.etiennelawlor.loop, PID: 6069
E/AndroidRuntime: android.os.NetworkOnMainThreadException
E/AndroidRuntime:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
E/AndroidRuntime:     at com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative(OpenSSLSocketImpl.java:1126)
E/AndroidRuntime:     at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1121)
E/AndroidRuntime:     at com.squareup.okhttp.Connection.closeIfOwnedBy(Connection.java:148)
E/AndroidRuntime:     at com.squareup.okhttp.OkHttpClient$1.closeIfOwnedBy(OkHttpClient.java:75)
E/AndroidRuntime:     at com.squareup.okhttp.internal.http.HttpConnection.closeIfOwnedBy(HttpConnection.java:137)
E/AndroidRuntime:     at com.squareup.okhttp.internal.http.HttpTransport.disconnect(HttpTransport.java:135)
E/AndroidRuntime:     at com.squareup.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:573)
E/AndroidRuntime:     at com.squareup.okhttp.Call.cancel(Call.java:122)
E/AndroidRuntime:     at retrofit.OkHttpCall.cancel(OkHttpCall.java:158)
E/AndroidRuntime:     at retrofit.ExecutorCallAdapterFactory$ExecutorCallbackCall.cancel(ExecutorCallAdapterFactory.java:63)
```
I thought this could be called from the main UI thread?  Is there a fix for this issue?

**Comment by JakeWharton** [comment]
This is a dupe, but I don't have the other issue # handy.

**Comment by JakeWharton** [comment]
#1592
