### ISSUE TITLE
ArrayIndexOutOfBoundsException getting ContentType

### ISSUE THREAD

**Issue by mntgoat** [square/okhttp#1869]
I've started receiving this error report over in crashlytics. I have no idea how to reproduce it as it has never happened to me. Here is the stacktrace. This is on a HttpURLConnection on Android 4.4 and 5.0, no idea what version of okhttp that is. 

java.lang.ArrayIndexOutOfBoundsException
       at com.android.okio.Util.checkOffsetAndCount(Util.java:29)
       at com.android.okio.OkBuffer.getByte(OkBuffer.java:161)
       at com.android.okio.OkBuffer.readUtf8Line(OkBuffer.java:322)
       at com.android.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:96)
       at com.android.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:175)
       at com.android.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:101)
       at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:616)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:379)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getHeaderField(HttpURLConnectionImpl.java:152)
       at java.net.URLConnection.getContentType(URLConnection.java:325)
       at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getContentType(DelegatingHttpsURLConnection.java:150)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getContentType(HttpsURLConnectionImpl.java:25)

**Comment by swankjesse** [comment]
Thanks for reporting this. If you get more insight into how to report it, I'm curious. As is there's not much I can do, and I can't see how we'd reproduce it.
