### ISSUE TITLE
Cannot reuse connection if retryOnConnectionFailure is false

### ISSUE THREAD

**Issue by srwilson** [square/okhttp#1873]
If retryOnConnectionFailure is to set false then sequential requests to the same host will fail.  Here's a simple repro case:

```java
public class Test {
    public static void main(String[] args) throws IOException {
        OkHttpClient client = new OkHttpClient();
        client.setRetryOnConnectionFailure(false);

        for(int i=0; i<2; i++) {
            Request request = new Request.Builder() .url("http://yahoo.com")
                    .build();

            Response response = client.newCall(request).execute();
            response.body().close();
            System.out.println("good");
        }
    }
}
```

Generates this output
```
good
Exception in thread "main" java.io.IOException: unexpected end of stream on Connection{yahoo.com:80, proxy=DIRECT hostAddress=98.138.253.109 cipherSuite=none protocol=http/1.1} (recycle count=1)
	at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:211)
	at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:906)
	at com.squareup.okhttp.internal.http.HttpEngine.access$300(HttpEngine.java:92)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:891)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:749)
	at com.squareup.okhttp.Call.getResponse(Call.java:268)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
	at com.squareup.okhttp.Call.execute(Call.java:79)
...
```

It seems to work if connection keep alive is set to zero.

**Comment by swankjesse** [comment]
Do not use setRetryOnConnectionFailure lightly. From that method's documentation:
http://square.github.io/okhttp/javadoc/com/squareup/okhttp/OkHttpClient.html#setRetryOnConnectionFailure-boolean-

> _“Set this to false to avoid retrying requests when doing so is destructive. In this case the calling application should do its own recovery of connectivity failures.”_

**Comment by baywet** [comment]
for sanity, here is the updated docs link https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/-builder/retry-on-connection-failure/
