### ISSUE TITLE
GzipSource resource leak

### ISSUE THREAD

**Issue by dlazerka** [square/okhttp#1887]
Upon just launching an emulator I see in logcat
```
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode: java.lang.Throwable: Explicit termination method 'end' not called
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at dalvik.system.CloseGuard.open(CloseGuard.java:180)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at java.util.zip.Inflater.<init>(Inflater.java:82)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.android.okhttp.okio.GzipSource.<init>(GzipSource.java:62)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.android.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:645)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:827)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:439)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:384)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:497)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.google.android.gms.http.GoogleHttpClient.a(SourceFile:811)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.google.android.gms.http.GoogleHttpClient.a(SourceFile:776)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.google.android.gms.http.GoogleHttpClient.execute(SourceFile:676)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.google.android.gms.http.GoogleHttpClient.execute(SourceFile:660)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.google.android.gms.auth.be.j.a(SourceFile:220)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.google.android.gms.auth.be.appcert.a.a(SourceFile:263)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.google.android.gms.auth.be.appcert.a.a(SourceFile:132)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.google.android.gms.auth.be.appcert.b.a(SourceFile:43)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.google.android.gms.auth.b.b.a(SourceFile:62)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.google.android.gms.auth.b.a.a(SourceFile:120)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.google.android.gms.auth.b.a.a(SourceFile:61)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.google.android.gms.auth.be.cron.AuthCronService.a(SourceFile:44)
09-29 12:31:45.410 1810-1815/com.google.process.gapps E/StrictMode:     at com.google.android.gms.gcm.al.run(SourceFile:135)
```
just in case, this is preceded by
```
09-29 12:31:42.160 2362-2486/com.google.android.gms.unstable W/DG.WV: Widevine DRM not supported on this device
09-29 12:31:42.160 2362-2486/com.google.android.gms.unstable W/DG.WV: android.media.UnsupportedSchemeException: Failed to instantiate drm object.
09-29 12:31:42.160 2362-2486/com.google.android.gms.unstable W/DG.WV:     at android.media.MediaDrm.native_setup(Native Method)
09-29 12:31:42.160 2362-2486/com.google.android.gms.unstable W/DG.WV:     at android.media.MediaDrm.<init>(MediaDrm.java:215)
09-29 12:31:42.160 2362-2486/com.google.android.gms.unstable W/DG.WV:     at com.google.android.gms.droidguard.p.run(SourceFile:99)
09-29 12:31:42.160 2362-2486/com.google.android.gms.unstable W/DG.WV:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
09-29 12:31:42.160 2362-2486/com.google.android.gms.unstable W/DG.WV:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
09-29 12:31:42.160 2362-2486/com.google.android.gms.unstable W/DG.WV:     at java.lang.Thread.run(Thread.java:818)
09-29 12:31:43.090 1810-2489/com.google.process.gapps I/PhenotypeFlagCommitter: Experiment Configs successfully retrieved for com.google.android.gms.playlog.uploader
09-29 12:31:43.090 1810-2489/com.google.process.gapps I/GoogleURLConnFactory: Using platform SSLCertificateSocketFactory
09-29 12:31:43.090 1341-1666/system_process I/AccountManagerService: getTypesVisibleToCaller: isPermitted? true
09-29 12:31:43.090 1810-2489/com.google.process.gapps W/Uploader:  no longer exists, so no auth token.
09-29 12:31:43.090 1810-2489/com.google.process.gapps E/Uploader: GoogleApiClient failed to connect: 14
09-29 12:31:44.460 2362-2375/com.google.android.gms.unstable I/art: Rejecting re-init on previously-failed class java.lang.Class<com.google.ccc.abuse.droidguard.DroidGuard>
09-29 12:31:44.590 1016-1590/? E/Drm: Failed to find drm plugin
09-29 12:31:44.650 1810-2489/com.google.process.gapps E/Uploader: GoogleApiClient failed to connect: 14
09-29 12:31:44.710 1810-2489/com.google.process.gapps E/Uploader: GoogleApiClient failed to connect: 14
09-29 12:31:44.870 1810-2489/com.google.process.gapps E/Uploader: GoogleApiClient failed to connect: 14
09-29 12:31:44.930 1810-2489/com.google.process.gapps E/Uploader: GoogleApiClient failed to connect: 14
09-29 12:31:45.080 1810-2489/com.google.process.gapps E/Uploader: GoogleApiClient failed to connect: 14
09-29 12:31:45.290 1810-2489/com.google.process.gapps E/Uploader: GoogleApiClient failed to connect: 14
09-29 12:31:45.400 1810-2485/com.google.process.gapps W/GLSUser: [AppCertManager] IOException while requesting key: 
09-29 12:31:45.400 1810-2485/com.google.process.gapps W/GLSUser: java.io.IOException: Invalid device key response.
09-29 12:31:45.400 1810-2485/com.google.process.gapps W/GLSUser:     at com.google.android.gms.auth.be.appcert.a.a(SourceFile:268)
09-29 12:31:45.400 1810-2485/com.google.process.gapps W/GLSUser:     at com.google.android.gms.auth.be.appcert.a.a(SourceFile:132)
09-29 12:31:45.400 1810-2485/com.google.process.gapps W/GLSUser:     at com.google.android.gms.auth.be.appcert.b.a(SourceFile:43)
09-29 12:31:45.400 1810-2485/com.google.process.gapps W/GLSUser:     at com.google.android.gms.auth.b.b.a(SourceFile:62)
09-29 12:31:45.400 1810-2485/com.google.process.gapps W/GLSUser:     at com.google.android.gms.auth.b.a.a(SourceFile:120)
09-29 12:31:45.400 1810-2485/com.google.process.gapps W/GLSUser:     at com.google.android.gms.auth.b.a.a(SourceFile:61)
09-29 12:31:45.400 1810-2485/com.google.process.gapps W/GLSUser:     at com.google.android.gms.auth.be.cron.AuthCronService.a(SourceFile:44)
09-29 12:31:45.400 1810-2485/com.google.process.gapps W/GLSUser:     at com.google.android.gms.gcm.al.run(SourceFile:135)
```
emulator config to reproduce
```
avd.ini.encoding=UTF-8
AvdId=Nexus_6_API_23
abi.type=x86_64
avd.ini.displayname=Nexus 6 API 23
disk.dataPartition.size=200M
hw.accelerometer=yes
hw.audioInput=yes
hw.battery=yes
hw.camera.back=emulated
hw.camera.front=none
hw.cpu.arch=x86_64
hw.dPad=no
hw.device.hash2=MD5:9b564b60b1aebee32c73ded9daa1e620
hw.device.manufacturer=Google
hw.device.name=Nexus 6
hw.gps=yes
hw.gpu.enabled=yes
hw.keyboard=yes
hw.lcd.density=560
hw.mainKeys=no
hw.ramSize=1536
hw.sdCard=yes
hw.sensors.orientation=yes
hw.sensors.proximity=yes
hw.trackBall=no
image.sysdir.1=system-images/android-23/google_apis/x86_64/
runtime.network.latency=gprs
runtime.network.speed=gprs
runtime.scalefactor=auto
sdcard.path=/home/dl/.android/avd/Nexus_6_API_22.avd/sdcard.img
skin.dynamic=yes
skin.name=1440x2560
skin.path=1440x2560
skin.path.backup=/your-path/android-studio/plugins/android/lib/device-art-resources/nexus_6
snapshot.present=no
tag.display=Google APIs
tag.id=google_apis
vm.heapSize=64
```
This isn't a problem for us, just to let you know.

**Comment by swankjesse** [comment]
I suspect you aren't closing the `HttpURLConnection` that is creating this connection. If you close that, this should go away.
