### ISSUE TITLE
null byte in User-Agent header after updating to okhttp 2.5.0

### ISSUE THREAD

**Issue by brennantaylor** [square/okhttp#1906]
This is a very intermittent issue that I've only been able to see on the Moto G.

In my client I set a header with `User-Agent: fake` but `MockWebServer` reads it strangely.

````text
java.lang.IllegalArgumentException: Unexpected char 0x00 at 5 in header value: fake�fake
	at com.squareup.okhttp.Headers$Builder.checkNameAndValue(Headers.java:295)
	at com.squareup.okhttp.Headers$Builder.add(Headers.java:245)
	at com.squareup.okhttp.mockwebserver.MockWebServer$FramedSocketHandler.readRequest(MockWebServer.java:890)
	at com.squareup.okhttp.mockwebserver.MockWebServer$FramedSocketHandler.receive(MockWebServer.java:859)
	at com.squareup.okhttp.internal.framed.FramedConnection$Reader$1.execute(FramedConnection.java:648)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

````

**Comment by swankjesse** [comment]
Very interesting, this suggests a bug in the HPACK encoder. I assume you're using OkHttp as the client also?

**Comment by brennantaylor** [comment]
Yes and it is selecting h2. I'm still narrowing it down.

**Comment by brennantaylor** [comment]
It looks like I may be reusing a request builder to initiate another request after the first succeeded.

**Comment by swankjesse** [comment]
Oh, very interesting.

**Comment by brennantaylor** [comment]
Also not that intermittent it's just a race condition for tripping the recursive `doRequest`. I can reproduce easily now.

**Comment by swankjesse** [comment]
Awesome. Wanna send a test case? Something that loops 1000 times is okay!

**Comment by brennantaylor** [comment]
Will do.

**Comment by swankjesse** [comment]
@brennantaylor ping!

**Comment by brennantaylor** [comment]
Yeah sorry I forgot. I will get to this soon.
