### ISSUE TITLE
OkHttp (used by UrlConnection) might start a new Thread when reading response

### ISSUE THREAD

**Issue by william-ferguson-au** [square/okhttp#1907]
I'm the maintainer for ACRA (Android Crash Reporter) and as part of the migration to using UrlConnection instead of the Apache Http library we are running foul of OkHttp potentially starting a new Thread during runtime shutdown when we attempt to read a HTTP response..

See https://github.com/ACRA/acra/issues/313

Is there any way of ensuring that OkHttp doesn't start a new Thread?

```
D/ACRA﹕ Connect to https://testapps.cloudant.com/acra-testapp/_design/acra-storage/_update/report
 09-28 22:35:09.235 16507-16536/? E/ACRA﹕ ACRA caught a InternalError for com.blogspot.test.testapp
 java.lang.InternalError: Thread starting during runtime shutdown
 at java.lang.Thread.nativeCreate(Native Method)
 at java.lang.Thread.start(Thread.java:1063)
 at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
 at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1337)
 at com.android.okhttp.ConnectionPool.addConnection(ConnectionPool.java:208)
 at com.android.okhttp.ConnectionPool.recycle(ConnectionPool.java:198)
 at com.android.okhttp.OkHttpClient$1.recycle(OkHttpClient.java:111)
 at com.android.okhttp.internal.http.HttpConnection$AbstractSource.endOfInput(HttpConnection.java:377)
 at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:426)
 at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:349)
 at java.io.InputStream.read(InputStream.java:162)
 at com.a.a.a.a.a(SourceFile:238)
 at com.a.a.a.a.a(SourceFile:123)
 at com.a.a.k.run(SourceFile:112)

```

**Comment by swankjesse** [comment]
No, there's no such mechanism. When does Android shutdown the runtime?!

**Comment by william-ferguson-au** [comment]
I suspect Android is marking it as shutdown as soon as an unchecked Exception or Error is not handled by the app. 

ACRA installs an UncaughtExceptionHandler in Application#onCreate. We send the HttpRequest from the UncaughtExceptionHandler. I can only presume that the Android framework is intercepting in some fashion to mark the VM as shutdown.

**Comment by william-ferguson-au** [comment]
So it's sounding like ACRA won't be able to UrlConnection to send Http requests since UrlConnection is using OkHttp under the covers. Does that sound correct?

**Comment by swankjesse** [comment]
You're probably better off writing the crash information to disk somewhere, and picking it up when the app relaunches. The crash might be an OutOfMemoryError, for example, and you're also going to need to allocate a bunch of memory to make an HTTP request.

**Comment by swankjesse** [comment]
(No action for us here.)

**Comment by william-ferguson-au** [comment]
We do write the crash info to disk as a fall back. 
But sending requires the app to relaunch which doesn't automatically occur for all Android versions.
One action for OkHttp could be to allow a minimum nr of threads in the pool instead of always collapsing to zero.

**Comment by JakeWharton** [comment]
This is a dupe of a really, really old issue. I'd have to search to find it.

**Comment by JakeWharton** [comment]
https://github.com/square/okhttp/issues/1153

**Comment by william-ferguson-au** [comment]
Thanks for the reference Jake.
