### ISSUE TITLE
HttpLoggingInterceptor with Level.Body doesn't close source

### ISSUE THREAD

**Issue by plastiv** [square/okhttp#1914]
I have StrictMode enabled which reports next issue:

```
10-09 16:46:30.907  28437-28443/? E/StrictMode﹕ A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'end' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:180)
            at java.util.zip.Inflater.<init>(Inflater.java:82)
            at okio.GzipSource.<init>(GzipSource.java:62)
            at com.squareup.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:645)
            at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:821)
            at com.squareup.okhttp.Call.getResponse(Call.java:268)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
            at com.squareup.okhttp.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:184)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:221)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
            at com.squareup.okhttp.Call.execute(Call.java:79)
```

I *think* the issue is because with `Level.BODY` interceptor copies body to `buffer`, but don't close response `source` here: https://github.com/square/okhttp/blob/master/okhttp-logging-interceptor/src/main/java/com/squareup/okhttp/logging/HttpLoggingInterceptor.java#L197. 

At least StrictMode is quiet after adding next line:

```
  responseBody.source().readAll(buffer);
  Util.closeQuietly(responseBody.source());
```

**Comment by JakeWharton** [comment]
Nice find. Just sent a PR to fix it.
