### ISSUE TITLE
NPE When Reading Header

### ISSUE THREAD

**Issue by jophde** [square/okhttp#1921]
We use OkHTTP as a dependency for our Android SDK at Optimizely.  We have been seeing this crash in the wild.  It only happens for one customer.  Any ideas?

```
Package: com.snowball.app 
Version Code: 66 
Version Name: 2.1.1 
Android: 5.0.1 
Manufacturer: LGE 
Model: Nexus 5 
CrashReporter Key: 718B9F67-EEC4-AAC0-AA77-E2BC2E9868E18BD68E1B 
Date: Mon Oct 05 13:23:03 PDT 2015

java.lang.RuntimeException: An error occured while executing doInBackground() 
at android.os.AsyncTask$3.done(AsyncTask.java:300) 
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355) 
at java.util.concurrent.FutureTask.setException(FutureTask.java:222) 
at java.util.concurrent.FutureTask.run(FutureTask.java:242) 
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
at java.lang.Thread.run(Thread.java:818) 
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'com.squareup.okhttp.Headers com.squareup.okhttp.Response.headers()' on a null object reference 
at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:796) 
at com.squareup.okhttp.Call.getResponse(Call.java:274) 
at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230) 
at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201) 
at com.squareup.okhttp.Call.execute(Call.java:81) 
at com.optimizely.LogAndEvent.OptimizelyTimeSeriesEventsManager$TimeSeriesEventTask.doInBackground(OptimizelyTimeSeriesEventsManager.java:280) 
at com.optimizely.LogAndEvent.OptimizelyTimeSeriesEventsManager$TimeSeriesEventTask.doInBackground(OptimizelyTimeSeriesEventsManager.java:242) 
at android.os.AsyncTask$2.call(AsyncTask.java:288) 
at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
```

Please let me know how I can help debug and fix.

**Comment by wwchen** [comment]
This happens when the call times out. When there is no response, the Response object is null, and in `readResponse`, it calls the object without checking whether it's null or nto

**Comment by swankjesse** [comment]
@jophde my theory is that you have a network interceptor that is returning null. Is that possible?
