### ISSUE TITLE
NoSuchElementException should not be thrown by DiskLruCache.trimToSize()

### ISSUE THREAD

**Issue by denversc** [square/okhttp#1932]
In an Android app that I'm writing I got a ```NoSuchElementException``` thrown from ```DiskLruCache.trimToSize()``` when invoked from ```cleanupRunnable```; however, I would expect that trimToSize() would never cause such an exception to occur.

    FATAL EXCEPTION: OkHttp DiskLruCache
    java.util.NoSuchElementException
        at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:350)
        at java.util.LinkedHashMap$ValueIterator.next(LinkedHashMap.java:371)
        at com.squareup.okhttp.internal.DiskLruCache.trimToSize(DiskLruCache.java:664)
        at com.squareup.okhttp.internal.DiskLruCache.access$200(DiskLruCache.java:88)
        at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:175)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)

I think this exception is a symptom of a race condition.  This exception happened when I cancelled an upload in my Android app, which calls ```OkHttpClient.cancel(Object tag)```, which I believe schedules an asynchronous run of ```DiskLruCache.cleanupRunnable```.

All calls to ```trimToSize()``` are synchronized on the enclosing DiskLruCache instance... except when called from ```cleanupRunnable```.  This is suspicious, as perhaps the calls to trimToSize() from cleanupRunnable should also be synchronized on the DiskLruCache instance?

okhttp version on which this issue was discovered: com.squareup.okhttp:okhttp:2.4.0

Thanks!

**Comment by denversc** [comment]
Duplicate of #1804
