### ISSUE TITLE
Okhttp fails strictmode for release resource on OpenSSLSocketImpl.startHandshake

### ISSUE THREAD

**Issue by jayshah123** [square/okhttp#1938]
```
E/StrictMode﹕ A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
    java.lang.Throwable: Explicit termination method 'close' not called
            at dalvik.system.CloseGuard.open(CloseGuard.java:180)
            at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:288)
            at com.squareup.okhttp.internal.http.SocketConnector.connectTls(SocketConnector.java:103)
            at com.squareup.okhttp.Connection.connect(Connection.java:143)
            at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:185)
            at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
            at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:341)
            at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
            at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
            at com.squareup.okhttp.Call.getResponse(Call.java:273)
            at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
            at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
            at com.squareup.okhttp.Call.access$100(Call.java:36)
            at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:164)
            at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
```

**Comment by jayshah123** [comment]
Android nexus 6.0
with okhttp version 2.4.0
and stetho interceptor applied from     
compile 'com.facebook.stetho:stetho-okhttp:1.1.1'

**Comment by jayshah123** [comment]
The use case is also pretty simple 

```
final OkHttpClient okHttpClient = new OkHttpClient();

     if (MainApplication.STETHO_DEBUG) {
          okHttpClient.networkInterceptors().add(MainApplication.getInstance().stethoInterceptor);
      }
      RequestBody formBody = new FormEncodingBuilder()
              .add("var1", var1)
              .build();
      com.squareup.okhttp.Request request = new com.squareup.okhttp.Request.Builder()
              .url(Config.CustomEndPoint)
              .post(formBody)
              .build();

      com.squareup.okhttp.Response response = null;
      try {
          response = okHttpClient.newCall(request).execute();
          if (!response.isSuccessful())
              throw new IOException(" Unexpected code " + response);

          String responseBodyString = response.body().string();
          Log.d(LOG_TAG, " response : " + responseBodyString);

          handleResponseBodyProcessing(responseBodyString);

      } catch (IOException e) {
          e.printStackTrace();
      }
```

**Comment by JakeWharton** [comment]
You are not closing the body in the unsuccessful case.

**Comment by jayshah123** [comment]
Ok Cool,
Checking the recipes, 
never found if we had to response.body().close()
Thanks a lot!
