### ISSUE TITLE
java.net.ConnectException: failed to connect to /serverHostName (port 8080) after 10000ms: connect failed: EMFILE (Too many open files)

### ISSUE THREAD

**Issue by shroffrushabh** [square/okhttp#1943]
Hello,

I have an Android app where I am basically running an Async task to ping my server for an Access Token every 3 minutes. But after about an hour the app freezes and I see this exception in logcat. The app eventually crashes.

```
10-25 16:38:47.527  19845-19845/com.test.app E/SharedPreferencesImpl﹕ Couldn't create directory for SharedPreferences file /data/data/com.test.app/shared_prefs/MY_SHARED_PREF.xml
10-25 16:38:47.536  19845-19845/com.test.app E/SharedPreferencesImpl﹕ Couldn't create directory for SharedPreferences file /data/data/com.test.app/shared_prefs/MY_SHARED_PREF.xml
10-25 16:38:47.545  19845-23000/com.test.app W/SpotifySDK﹕ Player::deliverAudio called with 0 frames
10-25 16:38:47.545  19845-23000/com.test.app I/SpotifySDK﹕ Got notification: Pause
10-25 16:38:47.547  19845-23000/com.test.app I/SpotifySDK﹕ Got notification: Track ended
10-25 16:38:47.552  19845-23000/com.test.app I/SpotifySDK﹕ Got notification: Track changed
10-25 16:38:47.553  19845-19845/com.test.app E/SharedPreferencesImpl﹕ Couldn't create directory for SharedPreferences file /data/data/com.test.app/shared_prefs/MY_SHARED_PREF.xml
10-25 16:38:47.560  19845-19913/com.test.app W/System.err﹕ java.net.ConnectException: failed to connect to /51.21.21.111 (port 8080) after 10000ms: connect failed: EMFILE (Too many open files)
10-25 16:38:47.572  19845-19913/com.test.app W/System.err﹕ at libcore.io.IoBridge.connect(IoBridge.java:124)
10-25 16:38:47.572  19845-19913/com.test.app W/System.err﹕ at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
10-25 16:38:47.572  19845-19913/com.test.app W/System.err﹕ at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:456)
10-25 16:38:47.572  19845-19913/com.test.app W/System.err﹕ at java.net.Socket.connect(Socket.java:882)
10-25 16:38:47.573  19845-19913/com.test.app W/System.err﹕ at com.squareup.okhttp.internal.Platform$Android.connectSocket(Platform.java:190)
10-25 16:38:47.573  19845-19913/com.test.app W/System.err﹕ at com.squareup.okhttp.Connection.connectSocket(Connection.java:196)
10-25 16:38:47.573  19845-19913/com.test.app W/System.err﹕ at com.squareup.okhttp.Connection.connect(Connection.java:172)
10-25 16:38:47.573  19845-19913/com.test.app W/System.err﹕ at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:367)
10-25 16:38:47.573  19845-19913/com.test.app W/System.err﹕ at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:128)
10-25 16:38:47.573  19845-19913/com.test.app W/System.err﹕ at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:328)
10-25 16:38:47.573  19845-19913/com.test.app W/System.err﹕ at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:245)
10-25 16:38:47.574  19845-19913/com.test.app W/System.err﹕ at com.squareup.okhttp.Call.getResponse(Call.java:267)
10-25 16:38:47.574  19845-19913/com.test.app W/System.err﹕ at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
10-25 16:38:47.574  19845-19913/com.test.app W/System.err﹕ at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
10-25 16:38:47.574  19845-19913/com.test.app W/System.err﹕ at com.squareup.okhttp.Call.execute(Call.java:79)
10-25 16:38:47.575  19845-19913/com.test.app W/System.err﹕ at com.test.app.async.AccessTokenUpdateTask.doInBackground(AccessTokenUpdateTask.java:57)
10-25 16:38:47.575  19845-19913/com.test.app W/System.err﹕ at com.test.app.async.AccessTokenUpdateTask.doInBackground(AccessTokenUpdateTask.java:21)
10-25 16:38:47.575  19845-19913/com.test.app W/System.err﹕ at android.os.AsyncTask$2.call(AsyncTask.java:292)
10-25 16:38:47.575  19845-19913/com.test.app W/System.err﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:237)
10-25 16:38:47.575  19845-19913/com.test.app W/System.err﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
10-25 16:38:47.575  19845-19913/com.test.app W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
10-25 16:38:47.576  19845-19913/com.test.app W/System.err﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
10-25 16:38:47.576  19845-19913/com.test.app W/System.err﹕ at java.lang.Thread.run(Thread.java:818)
10-25 16:38:47.576  19845-19913/com.test.app W/System.err﹕ Caused by: android.system.ErrnoException: connect failed: EMFILE (Too many open files)
10-25 16:38:47.576  19845-19913/com.test.app W/System.err﹕ at libcore.io.Posix.connect(Native Method)
10-25 16:38:47.577  19845-19913/com.test.app W/System.err﹕ at libcore.io.BlockGuardOs.connect(BlockGuardOs.java:111)
10-25 16:38:47.577  19845-19913/com.test.app W/System.err﹕ at libcore.io.IoBridge.connectErrno(IoBridge.java:154)
10-25 16:38:47.577  19845-19913/com.test.app W/System.err﹕ at libcore.io.IoBridge.connect(IoBridge.java:122)
10-25 16:38:47.577  19845-19913/com.test.app W/System.err﹕ ... 22 more
10-25 16:38:47.578  19845-19845/com.test.app W/art﹕ Large object allocation failed: ashmem_create_region failed for 'large object space allocation': Too many open files
10-25 16:38:47.603  19845-19845/com.test.app I/art﹕ Alloc sticky concurrent mark sweep GC freed 75611(1974KB) AllocSpace objects, 15(384KB) LOS objects, 13% free, 48MB/55MB, paused 1.317ms total 23.837ms
10-25 16:38:47.605  19845-19845/com.test.app W/art﹕ Large object allocation failed: ashmem_create_region failed for 'large object space allocation': Too many open files
10-25 16:38:47.626  19845-19845/com.test.app I/art﹕ Alloc partial concurrent mark sweep GC freed 9352(329KB) AllocSpace objects, 6(1169KB) LOS objects, 25% free, 46MB/62MB, paused 965us total 20.962ms
10-25 16:38:47.628  19845-19845/com.test.app W/art﹕ Large object allocation failed: ashmem_create_region failed for 'large object space allocation': Too many open files
10-25 16:38:47.650  19845-19845/com.test.app I/art﹕ Alloc concurrent mark sweep GC freed 399(28KB) AllocSpace objects, 0(0B) LOS objects, 25% free, 46MB/62MB, paused 922us total 21.750ms
10-25 16:45:19.014  19845-19845/com.test.app E/Surface﹕ dequeueBuffer failed (Unknown error 2147483646)
10-25 16:45:19.022  19845-19845/com.test.app E/ViewRootImpl﹕ Could not lock surface
    java.lang.IllegalArgumentException
            at android.view.Surface.nativeLockCanvas(Native Method)
```

Here is my analysis of this log: I understand why the app UI froze, it was due to the "dequeueBuffer failed" and the "lock surface" exception. But the line before it tells me that the app is keeping too many files open from each 3 min ping I make to my server. Here is the code in my Async task

I am defining my client object in the activity like below and am passing in that client object to that Async task through the constructor.
```
    OkHttpClient client = new OkHttpClient();
```
```
    Async task doBackground code
 
    RequestBody body = RequestBody.create("application/json; charset=utf-8", jsonString);
    Request request = new Request.Builder()
            .url(url)
            .post(body)
            .build();
    Response response = null;
    try {
        response = client.newCall(request).execute();
        if(response.isSuccessful()) {
            String responseBody = response.body().string();
            return responseBody;
        }
    } catch (Exception e) {
        e.printStackTrace();
    }
```

Any idea what I am doing wrong here?

**Comment by JakeWharton** [comment]
Don't create a new OkHttpClient for each request. Create it once and reuse.

**Comment by shroffrushabh** [comment]
I did that and I am getting the same exception. I removed that comment from this issue as I think it was misleading.

**Comment by JakeWharton** [comment]
Well the error is simple: something is opening too many files or sockets.
Tracking it down is just a matter of seeing what's using these resources
without freeing them.

**Comment by shroffrushabh** [comment]
@JakeWharton I am sorry but it was an issue with another SDK I was using and not with okhttp. I am sorry. Closing this issue now.
