### ISSUE TITLE
MockWebServerTest.throttleRequest() is flaky

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#1981]
```
Tests run: 22, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 14.04 sec <<< FAILURE! - in com.squareup.okhttp.mockwebserver.MockWebServerTest
throttleRequest(com.squareup.okhttp.mockwebserver.MockWebServerTest)  Time elapsed: 8.291 sec  <<< FAILURE!
java.lang.AssertionError: Request + Response: 8283ms
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at com.squareup.okhttp.mockwebserver.MockWebServerTest.throttleRequest(MockWebServerTest.java:212)
```

**Comment by swankjesse** [comment]
Seems like in the run above the host VM paused for ~7.5 seconds. To make this work without flakiness we need to either extend our margin of error from 500ms to 10 seconds, or go to a test infrastructure with fake clocks everywhere.

**Comment by swankjesse** [comment]
No action to take here unless we build this: https://github.com/square/okhttp/issues/2134
