### ISSUE TITLE
A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

### ISSUE THREAD

**Issue by l123456789jy** [square/okhttp#2002]
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                               java.lang.Throwable: Explicit termination method 'end' not called
                                                   at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                   at java.util.zip.Inflater.<init>(Inflater.java:82)
                                                   at okio.GzipSource.<init>(GzipSource.java:62)
                                                   at com.squareup.okhttp.internal.http.HttpEngine.unzip(HttpEngine.java:645)
                                                   at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:821)
                                                   at com.squareup.okhttp.Call.getResponse(Call.java:268)
                                                   at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:224)
                                                   at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:195)
                                                   at com.squareup.okhttp.Call.access$100(Call.java:34)
                                                   at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:162)
                                                   at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                   at java.lang.Thread.run(Thread.java:841)

**Comment by l123456789jy** [comment]
StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder().detectAll().penaltyLog()
                .penaltyDeath().build());

**Comment by JakeWharton** [comment]
Show your `Callback.onReponse` code. Are you correctly closing the resource in all paths?

**Comment by l123456789jy** [comment]
//封装get请求
    public static void get(String uri, final MyHttpCallBcak mMyHttpCallBcak) {
        OkHttpClientManager instance = OkHttpClientManager.getInstance();
        //创建okHttpClient对象
        //创建一个Request
        final Request request = new Request.Builder()
                .url(uri)
                .build();
        //new call
        final Call call = mOkHttpClient.newCall(request);
        //请求加入调度
        call.enqueue(new Callback() {
            @Override
            public void onFailure(final Request request, final IOException e) {
                mMyHttpCallBcak.onFailure(request, e);
            }

            @Override
            public void onResponse(final Response response) throws IOException {
                mMyHttpCallBcak.onResponse(response);
            }
        });
    }



OkHttpClientManager.get(uri, new MyHttpCallBcak() {
            @Override
            public void onFailure(Request request, IOException e) {
                runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        Toast.makeText(getApplicationContext(), "获取数据失败！", Toast.LENGTH_SHORT).show();
                    }
                });
            }
            @Override
            public void onResponse(final Response response) {
                try {
                    mcountViewPagerBean = mGson.fromJson(response.body().string(), CountViewPagerBean.class);
                } catch (IOException e) {
                    e.printStackTrace();
                }
                mHandler.sendEmptyMessage(0);

            }
        });




I use mHandler  solved the problem

    public Handler mHandler = new Handler(Looper.getMainLooper()) {
        @Override
        public void handleMessage(Message msg) {
            super.handleMessage(msg);
            MyCountPagerAdapter = new MyCountPagerAdapter(mcountViewPagerBean.body.slides, mLayoutUtil, options_base);
            mConvenientBanner.setAdapter(MyCountPagerAdapter);
            mIndexTv.setText(1 + "");
            mTotalCount.setText("/" + mcountViewPagerBean.body.slides.size());
            mTv.setText(mcountViewPagerBean.body.slides.get(0).description);
        }
    };
