### ISSUE TITLE
HttpLoggingInterceptor crashes when 204 not content

### ISSUE THREAD

**Issue by WonderCsabo** [square/okhttp#2029]
If the server returns a no content response, `HttpLoggingInterceptor` is crashing for me with this stack trace:

```java
java.io.EOFException
   at okio.RealBufferedSource.require(RealBufferedSource.java:64)
   at okio.GzipSource.consumeHeader(GzipSource.java:114)
   at okio.GzipSource.read(GzipSource.java:73)
   at okio.RealBufferedSource.request(RealBufferedSource.java:71)
   at com.squareup.okhttp.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:197)
   at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:223)
   at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:196)
   at com.squareup.okhttp.Call.execute(Call.java:79)
```

**Comment by WonderCsabo** [comment]
This is the what i see from the response:

```
<-- HTTP/1.1 204 No Content (64ms)
Date: Mon, 23 Nov 2015 23:49:07 GMT
Server: Apache/2.2.22 (Debian)
vary: Origin,Accept-Encoding
x-powered-by: Express, Phusion Passenger 5.0.6
access-control-allow-credentials: true
Connection: close
Status: 204 No Content
Content-Type: application/json
OkHttp-Selected-Protocol: http/1.1
OkHttp-Sent-Millis: 1448322543237
OkHttp-Received-Millis: 1448322543275
```

**Comment by JakeWharton** [comment]
Good find. Should be an easy fix.

**Comment by JakeWharton** [comment]
I cannot reproduce. Here's my test case from `HttpLoggingInterceptorTest.java`:
```java
  @Test public void bodyGet204() throws IOException {
    interceptor.setLevel(Level.BODY);

    server.enqueue(new MockResponse()
        .setStatus("HTTP/1.1 204 No Content")
        .addHeader("Date", "Mon, 23 Nov 2015 23:49:07 GMT")
        .addHeader("Server", "Apache/2.2.22 (Debian)")
        .addHeader("vary", "Origin,Accept-Encoding")
        .addHeader("x-powered-by", "Express, Phusion Passenger 5.0.6")
        .addHeader("access-control-allow-credentials", "true")
        .addHeader("Connection", "close")
        .addHeader("Status", "204 No Content")
        .addHeader("Content-Type", "application/json"));
    client.newCall(request().build()).execute();

    assertEquals(20, logs.size());
    assertEquals("--> GET / HTTP/1.1", logs.get(0));
    assertEquals("Host: " + server.getHostName() + ":" + server.getPort(), logs.get(1));
    assertEquals("Connection: Keep-Alive", logs.get(2));
    assertEquals("Accept-Encoding: gzip", logs.get(3));
    assertTrue(Pattern.matches("User-Agent: okhttp/.+", logs.get(4)));
    assertEquals("--> END GET", logs.get(5));
    assertTrue(Pattern.matches("<-- HTTP/1\\.1 204 No Content \\(\\d+ms\\)", logs.get(6)));
    assertEquals("Content-Length: 0", logs.get(7));
    assertEquals("Date: Mon, 23 Nov 2015 23:49:07 GMT", logs.get(8));
    assertEquals("Server: Apache/2.2.22 (Debian)", logs.get(9));
    assertEquals("vary: Origin,Accept-Encoding", logs.get(10));
    assertEquals("x-powered-by: Express, Phusion Passenger 5.0.6", logs.get(11));
    assertEquals("access-control-allow-credentials: true", logs.get(12));
    assertEquals("Connection: close", logs.get(13));
    assertEquals("Status: 204 No Content", logs.get(14));
    assertEquals("Content-Type: application/json", logs.get(15));
    assertEquals("OkHttp-Selected-Protocol: http/1.1", logs.get(16));
    assertTrue(Pattern.matches("OkHttp-Sent-Millis: \\d+", logs.get(17)));
    assertTrue(Pattern.matches("OkHttp-Received-Millis: \\d+", logs.get(18)));
    assertEquals("<-- END HTTP (0-byte body)", logs.get(19));
  }
```
Are you using version 2.6.0 of both the 'okhttp' and 'logging-interceptor' artifacts?

**Comment by WonderCsabo** [comment]
Thanks for your time checking this out!

Yes, i am using the correct dependencies. I also could not reproduce it with mock servers or mocking the reponse. But i can clearly reproduce it with our server. That is not public, so i sent the code snippet to your GMail. Can you check it out? Thanks in advance.

**Comment by WonderCsabo** [comment]
Thanks for the super-fast fix, i can verify it works in my case. :)

**Comment by modislaszlox2** [comment]
@JakeWharton issue is reproducible in 3.6.0

java.io.EOFException
     at okio.RealBufferedSource.require(RealBufferedSource.java:59)
     at okio.GzipSource.consumeHeader(GzipSource.java:114)
     at okio.GzipSource.read(GzipSource.java:73)
     at okio.RealBufferedSource.request(RealBufferedSource.java:66)
     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:238)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)

**Comment by JakeWharton** [comment]
Can you provide a test case?

**Comment by modislaszlox2** [comment]
@JakeWharton cannot provide the exact url I'm using but this is what I'm doing:
1. GET request with retrofit
2. Url redirects to different url and returns status code 200(no response body)

**Comment by JakeWharton** [comment]
There's test cases in `HttpLoggingInterceptorTest.java`, can you add one that fails in a PR?
