### ISSUE TITLE
StrictMode CloseGuard tripped when no network.

### ISSUE THREAD

**Issue by JakeWharton** [square/okhttp#2054]
I believe the cause of this is when no network is available (insta-`UnknownHostException`) and an expired cached response exists.
```
             StrictMode  E  A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                         E  java.lang.Throwable: Explicit termination method 'close' not called
                         E      at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                         E      at java.io.FileInputStream.<init>(FileInputStream.java:78)
                         E      at okio.Okio.source(Okio.java:163)
                         E      at com.squareup.okhttp.internal.io.FileSystem$1.source(FileSystem.java:44)
                         E      at com.squareup.okhttp.internal.DiskLruCache$Entry.snapshot(DiskLruCache.java:1001)
                         E      at com.squareup.okhttp.internal.DiskLruCache.get(DiskLruCache.java:429)
                         E      at com.squareup.okhttp.Cache.get(Cache.java:184)
                         E      at com.squareup.okhttp.Cache$1.get(Cache.java:139)
                         E      at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:227)
                         E      at com.squareup.okhttp.Call.getResponse(Call.java:276)
                         E      at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:234)
                         E      at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:196)
                         E      at com.squareup.okhttp.Call.execute(Call.java:79)
```

**Comment by JakeWharton** [comment]
cc @mattprecious

**Comment by dave-r12** [comment]
Is anyone currently looking into this? If not, do you think an outside contribution is feasible? I'm willing to give it a shot, but will likely need guidance along the way

**Comment by swankjesse** [comment]
We’ll fix it soon. Probably OkHttp 3.1.

**Comment by swankjesse** [comment]
@dave-r12 yes, please give this a shot!

**Comment by dave-r12** [comment]
Ok. Per Jake's description, I think I have a failing test case. The test throws an IllegalStateException from the InMemoryFileSystem rule

```java
  @Test public void networkDropsOnConditionalGet() throws IOException {
    FakeDns dns = new FakeDns();
    dns.addresses(Dns.SYSTEM.lookup(server.url("/").host()));
    client = client.newBuilder()
        .dns(dns)
        .cache(cache)
        .build();

    server.enqueue(new MockResponse()
        .addHeader("ETag: v1")
        .setBody("A"));

    Request cacheStoreRequest = new Request.Builder()
        .url(server.url("/"))
        .build();
    executeSynchronously(cacheStoreRequest)
        .assertCode(200)
        .assertBody("A");

    // simulate no network available
    dns.unknownHost();
    // force a new connection to be established
    client.connectionPool().evictAll();

    Request conditionalGetRequest = new Request.Builder()
        .url(server.url("/"))
        .build();
    try {
      executeSynchronously(conditionalGetRequest);
      fail();
    } catch (UnknownHostException expected) {
    }
  }
```

**Comment by swankjesse** [comment]
Awesome.
