### ISSUE TITLE
HttpURLConnection.disconnect() takes too long

### ISSUE THREAD

**Issue by FengMonkey** [square/okhttp#2057]
In android 4.4, when download a large file, canceling request by calling disconnect() takes too long.  Stacktrace looks like this:

> at libcore.io.Posix.recvfromBytes(Native Method)	
  at libcore.io.Posix.recvfrom(Posix.java:141)	
  at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:164)	
  at libcore.io.IoBridge.recvfrom(IoBridge.java:506)	
  at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)	
  at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)	
  at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)	
  at java.io.InputStream.read(InputStream.java:162)	
  at java.io.BufferedInputStream.fillbuf(BufferedInputStream.java:142)	
  at java.io.BufferedInputStream.read(BufferedInputStream.java:288)	
  at com.android.okhttp.internal.http.HttpTransport$FixedLengthInputStream.read(HttpTransport.java:386)	
  at com.android.okhttp.internal.Util.readSingleByte(Util.java:182)	
  at com.android.okhttp.internal.http.AbstractHttpInputStream.read(AbstractHttpInputStream.java:63)	
  at com.android.okhttp.internal.Util.skipAll(Util.java:250)	
  at com.android.okhttp.internal.http.HttpTransport.discardStream(HttpTransport.java:190)	
  at com.android.okhttp.internal.http.HttpTransport.access$200(HttpTransport.java:32)	
  at com.android.okhttp.internal.http.HttpTransport$FixedLengthInputStream.close(HttpTransport.java:408)	
  at com.android.okhttp.internal.Util.closeQuietly(Util.java:110)	
  at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:102)	
  at tv.fun.appstore.download.DownloadThread.executeDownload(DownloadThread.java:384)	
  at tv.fun.appstore.download.DownloadThread.runInternal(DownloadThread.java:231)	
  at tv.fun.appstore.download.DownloadThread.run(DownloadThread.java:173)	
  at tv.fun.appstore.download.DownloadServiceLocal$DownloadItem.run(DownloadServiceLocal.java:77)	
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)	
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)	
  at java.lang.Thread.run(Thread.java:841)	

It seems okhttp wants to read all remaining data. Is there a way to disable this behavior?

Thanks.

**Comment by swankjesse** [comment]
Try the latest OkHttp from this project.
