### ISSUE TITLE
error when calling via https

### ISSUE THREAD

**Issue by JacobZ** [square/okhttp#2076]
Hi,

I recently upgraded to 2.6.0 and having problems when sending a request with https.
By calling (for example) `https://foo.com/bar` I get the following error:
```java
MockWebServer[63548] connection from /127.0.0.1 crashed
java.lang.IllegalArgumentException: Unexpected header: �	��39/5
	at com.squareup.okhttp.Headers$Builder.add(Headers.java:238)
	at com.squareup.okhttp.mockwebserver.MockWebServer.readRequest(MockWebServer.java:607)
	at com.squareup.okhttp.mockwebserver.MockWebServer.access$1500(MockWebServer.java:94)
	at com.squareup.okhttp.mockwebserver.MockWebServer$4.processOneRequest(MockWebServer.java:520)
	at com.squareup.okhttp.mockwebserver.MockWebServer$4.processConnection(MockWebServer.java:482)
	at com.squareup.okhttp.mockwebserver.MockWebServer$4.execute(MockWebServer.java:424)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:744)
```
However `http://foo.com/bar` works. Am I missing a configuration step or something when using https?

**Comment by swankjesse** [comment]
Are you enabling HTTPS on your MockWebServer?

**Comment by JacobZ** [comment]
Not yet I think. How do I enable HTTPS on my MockWebServer?

**Comment by swankjesse** [comment]
That's a better question for StackOverflow than this bug tracker. This bug tracker is for feature requests & bug reports only.
