### ISSUE TITLE
Block thread

### ISSUE THREAD

**Issue by emacsist** [square/okhttp#2098]
> at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:927)
	- locked <0x0000000784e3e858> (a java.lang.Object)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:884)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:102)
	- locked <0x0000000784e3d9f0> (a sun.security.ssl.AppInputStream)
	at okio.Okio$2.read(Okio.java:136)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at okio.RealBufferedSource.read(RealBufferedSource.java:50)
	at com.squareup.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:457)
	at okio.RealBufferedSource.exhausted(RealBufferedSource.java:60)
	at okio.InflaterSource.refill(InflaterSource.java:96)
	at okio.InflaterSource.read(InflaterSource.java:62)
	at okio.GzipSource.read(GzipSource.java:80)
	at okio.Buffer.writeAll(Buffer.java:574)
	at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:87)
	at com.squareup.okhttp.ResponseBody.bytes(ResponseBody.java:56)
	at com.squareup.okhttp.ResponseBody.string(ResponseBody.java:82)

Hello, everybody. When my applicatioin is calling the `Response.body.string()`, the thread is blocked there. And I don't know why. Everybody can help me ? Thanks.

**Comment by swankjesse** [comment]
Seems like a better question for stackoverflow. This issues tracker is for bug reports & feature requests only.
