### ISSUE TITLE
Still getsockname failed: EBADF.

### ISSUE THREAD

**Issue by HomHomLin** [square/okhttp#2108]
Our project use:okhttp:2.6.0
Received error from user-sever:

libcore.io.ErrnoException
getsockname failed: EBADF (Bad file number)
com.squareup.okhttp.internal.Platform$Android.a(Platform.java:190)

**Comment by swankjesse** [comment]
No action for us to take on this. If you could provide us with an executable test case, that’d help!

**Comment by linxhome** [comment]
ava.lang.AssertionError: libcore.io.ErrnoException: getsockname failed: EBADF (Bad file number)
	at libcore.io.IoBridge.getSocketLocalAddress(IoBridge.java:670)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:569)
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
	at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:723)
	at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:81)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)


I meet this in android 4.0.3

**Comment by swankjesse** [comment]
@linxhome upgrading to Okio 1.8.0 or newer should fix this.
