### ISSUE TITLE
crashes on 4.1 samsung s3 mini

### ISSUE THREAD

**Issue by aimiliano** [square/okhttp#2114]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListIterator.next(ArrayList.java:569)
	at org.apache.harmony.security.fortress.Services.updateServiceInfo(Services.java:186)
	at org.apache.harmony.security.fortress.Services.refresh(Services.java:234)
	at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:137)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:98)
	at com.squareup.okhttp.OkHttpClient.getDefaultSSLSocketFactory(OkHttpClient.java:663)
	at com.squareup.okhttp.OkHttpClient.copyWithDefaults(OkHttpClient.java:623)
	at com.squareup.okhttp.Call.<init>(Call.java:48)
	at com.squareup.okhttp.OkHttpClient.newCall(OkHttpClient.java:595)

**Comment by aimiliano** [comment]
Is it only Device related?

**Comment by swankjesse** [comment]
This is a device bug. No action we can take unfortunately. Consider reporting it to Samsung.
