### ISSUE TITLE
Fail to retrieve cached data when offline

### ISSUE THREAD

**Issue by AlmogBaku** [square/okhttp#2144]
## Steps to reproduce
1. Do get request when online
2. Validate data cached using `adb shell`
3. Kill the app
4. Disable `Cellular data` and `Wifi`
5. Running the app

## Server response while online
```
2-22 22:53:56.735 15941-16350/com.mycompany.android D/Retrofit: <--- HTTP 200 http://mycompany.com/api/test (638ms)
12-22 22:53:56.735 15941-16350/com.mycompany.android D/Retrofit: Server: nginx/1.4.6 (Ubuntu)
12-22 22:53:56.735 15941-16350/com.mycompany.android D/Retrofit: Content-Type: application/json
12-22 22:53:56.735 15941-16350/com.mycompany.android D/Retrofit: Transfer-Encoding: chunked
12-22 22:53:56.735 15941-16350/com.mycompany.android D/Retrofit: Connection: keep-alive
12-22 22:53:56.735 15941-16350/com.mycompany.android D/Retrofit: Cache-Control: max-age=900, max-stale=4838400, public
12-22 22:53:56.735 15941-16350/com.mycompany.android D/Retrofit: Allow: POST, GET, DELETE
12-22 22:53:56.735 15941-16350/com.mycompany.android D/Retrofit: Date: Tue, 22 Dec 2015 20:54:03 GMT
12-22 22:53:56.735 15941-16350/com.mycompany.android D/Retrofit: OkHttp-Selected-Protocol: http/1.1
12-22 22:53:56.735 15941-16350/com.mycompany.android D/Retrofit: OkHttp-Sent-Millis: 1450817636439
12-22 22:53:56.735 15941-16350/com.mycompany.android D/Retrofit: OkHttp-Received-Millis: 1450817636733
12-22 22:53:56.742 15941-16350/com.mycompany.android D/Retrofit: [‘my data’]
12-22 22:53:56.742 15941-16350/com.mycompany.android D/Retrofit: <--- END HTTP (3180-byte body)
```

## Logs when offline
```
12-22 22:58:15.980 20271-20271/com.mycompany.android W/System.err: com.mycompany.api.MyException: Unable to resolve host "mycompany.com": No address associated with hostname
12-22 22:58:15.980 20271-20271/com.mycompany.android W/System.err:     at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
12-22 22:58:15.981 20271-20271/com.mycompany.android W/System.err:     at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
12-22 22:58:15.981 20271-20271/com.mycompany.android W/System.err:     at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
12-22 22:58:15.981 20271-20271/com.mycompany.android W/System.err:     at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
12-22 22:58:15.981 20271-20271/com.mycompany.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-22 22:58:15.981 20271-20271/com.mycompany.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-22 22:58:15.981 20271-20271/com.mycompany.android W/System.err:     at retrofit.Platform$Android$2$1.run(Platform.java:142)
12-22 22:58:15.981 20271-20271/com.mycompany.android W/System.err:     at java.lang.Thread.run(Thread.java:818)
12-22 22:58:16.343 20271-20358/com.mycompany.android D/Retrofit: ---> HTTP GET http://mycompany.com/api/test
12-22 22:58:16.343 20271-20358/com.mycompany.android D/Retrofit: ---> END HTTP (no body)
12-22 22:58:16.346 20271-20358/com.mycompany.android D/Retrofit: ---- ERROR http://mycompany.com/api/test
12-22 22:58:16.347 20271-20358/com.mycompany.android D/Retrofit: java.net.UnknownHostException: Unable to resolve host "mycompany.com": No address associated with hostname
                                                                  at java.net.InetAddress.lookupHostByName(InetAddress.java:427)
                                                                  at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
                                                                  at java.net.InetAddress.getAllByName(InetAddress.java:215)
                                                                  at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
                                                                  at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:188)
                                                                  at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:157)
                                                                  at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:100)
                                                                  at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:357)
                                                                  at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:340)
                                                                  at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
                                                                  at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
                                                                  at com.squareup.okhttp.Call.getResponse(Call.java:273)
                                                                  at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
                                                                  at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
                                                                  at com.squareup.okhttp.Call.execute(Call.java:81)
                                                                  at retrofit.client.OkClient.execute(OkClient.java:53)
                                                                  at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
                                                                  at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
                                                                  at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
                                                                  at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                  at retrofit.Platform$Android$2$1.run(Platform.java:142)
                                                                  at java.lang.Thread.run(Thread.java:818)
12-22 22:58:16.347 20271-20358/com.mycompany.android D/Retrofit: ---- END ERROR
12-22 22:58:16.372 20271-20363/com.mycompany.android I/OpenGLRenderer: Initialized EGL, version 1.4
12-22 22:58:16.378 20271-20363/com.mycompany.android D/OpenGLRenderer: Enabling debug mode 0
12-22 22:58:16.407 20271-20271/com.mycompany.android D/com.instabug.library: ActivityLifecycleListener: SplashActivity_ paused
12-22 22:58:16.407 20271-20271/com.mycompany.android D/com.instabug.library: Stopping shake detection
12-22 22:58:16.429 20271-20271/com.mycompany.android W/System.err: retrofit.RetrofitError: Unable to resolve host "mycompany.com": No address associated with hostname
12-22 22:58:16.429 20271-20271/com.mycompany.android W/System.err:     at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
12-22 22:58:16.429 20271-20271/com.mycompany.android W/System.err:     at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
12-22 22:58:16.429 20271-20271/com.mycompany.android W/System.err:     at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
12-22 22:58:16.429 20271-20271/com.mycompany.android W/System.err:     at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
12-22 22:58:16.429 20271-20271/com.mycompany.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
12-22 22:58:16.429 20271-20271/com.mycompany.android W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
12-22 22:58:16.429 20271-20271/com.mycompany.android W/System.err:     at retrofit.Platform$Android$2$1.run(Platform.java:142)
12-22 22:58:16.429 20271-20271/com.mycompany.android W/System.err:     at java.lang.Thread.run(Thread.java:818)
12-22 22:58:16.429 20271-20271/com.mycompany.android W/System.err: Caused by: java.net.UnknownHostException: Unable to resolve host "mycompany.com": No address associated with hostname
12-22 22:58:16.429 20271-20271/com.mycompany.android W/System.err:     at java.net.InetAddress.lookupHostByName(InetAddress.java:427)
12-22 22:58:16.429 20271-20271/com.mycompany.android W/System.err:     at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
12-22 22:58:16.429 20271-20271/com.mycompany.android W/System.err:     at java.net.InetAddress.getAllByName(InetAddress.java:215)
12-22 22:58:16.429 20271-20271/com.mycompany.android W/System.err:     at com.squareup.okhttp.internal.Network$1.resolveInetAddresses(Network.java:29)
12-22 22:58:16.429 20271-20271/com.mycompany.android W/System.err:     at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:188)
12-22 22:58:16.429 20271-20271/com.mycompany.android W/System.err:     at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:157)
12-22 22:58:16.430 20271-20271/com.mycompany.android W/System.err:     at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:100)
12-22 22:58:16.430 20271-20271/com.mycompany.android W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.createNextConnection(HttpEngine.java:357)
12-22 22:58:16.430 20271-20271/com.mycompany.android W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(HttpEngine.java:340)
12-22 22:58:16.430 20271-20271/com.mycompany.android W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:330)
12-22 22:58:16.430 20271-20271/com.mycompany.android W/System.err:     at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:248)
12-22 22:58:16.430 20271-20271/com.mycompany.android W/System.err:     at com.squareup.okhttp.Call.getResponse(Call.java:273)
12-22 22:58:16.430 20271-20271/com.mycompany.android W/System.err:     at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:230)
12-22 22:58:16.430 20271-20271/com.mycompany.android W/System.err:     at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:201)
12-22 22:58:16.430 20271-20271/com.mycompany.android W/System.err:     at com.squareup.okhttp.Call.execute(Call.java:81)
12-22 22:58:16.430 20271-20271/com.mycompany.android W/System.err:     at retrofit.client.OkClient.execute(OkClient.java:53)
12-22 22:58:16.430 20271-20271/com.mycompany.android W/System.err:     at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
12-22 22:58:16.430 20271-20271/com.mycompany.android W/System.err: 	... 7 more
```

**Comment by swankjesse** [comment]
OkHttp’s cache will do conditional gets if the locally stored content needs to be revalidated.

**Comment by AlmogBaku** [comment]
Not sure I understood... but neither the `max-age` and `max-stale` are expired, if that's what you meant.

**Comment by swankjesse** [comment]
Yeah, you might want to try `CacheControl.FORCE_CACHE` on the request if you want to avoid the network.

**Comment by AlmogBaku** [comment]
I'm receiving "retrofit.RetrofitError: 504 Unsatisfiable Request
(only-if-cached)" although it's cached as you can see from the headers

--------------------------------------------
Q: Why is this email five sentences or less?
A: http://five.sentenc.es

**Comment by AlmogBaku** [comment]
It's throws `retrofit.RetrofitError: 504 Unsatisfiable Request (only-if-cached)`, although it's cached as you can see from the headers.

**Comment by AlmogBaku** [comment]
```
    public static Interceptor sOkHttpInterceptor = (chain) -> {
        Request request = chain.request();

            if(!isConnected()) {
                request = request.newBuilder().cacheControl(CacheControl.FORCE_CACHE).build();
            }

        return chain.proceed(request);
    };
```
```
        okHttpClient.interceptors().add(sOkHttpInterceptor);
```

**Comment by AlmogBaku** [comment]
I found something:
```shell
shell@titan_umts:/data/data/com.mycomapny.android/cache/httpCache $ cat 5f23392c232ce5f240e9f2dcd496397c.0                                         <
http://mycomnpany.com/api/test
GET
0
HTTP/1.1 301 Moved Permanently
11
Server: nginx/1.4.6 (Ubuntu)
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: no-cache
Location: http://mycomnpany.com/api/test/?access_token=MGRkOWY1NjQ***jRmYzllNDVkNjc5OTZiMzdhMGUzMw
Allow: POST, GET, DELETE
Date: Fri, 25 Dec 2015 12:52:59 GMT
OkHttp-Selected-Protocol: http/1.1
OkHttp-Sent-Millis: 1451047972438
OkHttp-Received-Millis: 1451047972622

shell@titan_umts:/data/data/com.mycomapny.android/cache/httpCache $ cat at c6dbb1936fffe0b45c46a910c3161f18.0                                         <
http://mycomnpany.com/api/test/?access_token=MGRkOWY1NjQ***jRmYzllNDVkNjc5OTZiMzdhMGUzMw
GET
0
HTTP/1.1 200 OK
9
Server: nginx/1.4.6 (Ubuntu)
Content-Type: application/json
Transfer-Encoding: chunked
Connection: keep-alive
Cache-Control: max-age=900, max-stale=4838400, public
Allow: POST, GET, DELETE
Date: Fri, 25 Dec 2015 13:23:48 GMT
OkHttp-Sent-Millis: 1451049821364
OkHttp-Received-Millis: 1451049821665
shell@titan_umts:/data/data/net.rimoto.android/cache/httpCache $               
```

Maybe because my interceptor adds an `access_token` it's not caching it?

**Comment by AlmogBaku** [comment]
OKAY! I found it!
I'm requesting to:
`http://mycomnpany.com/api/test?access_token=MGRkOWY1NjQ***jRmYzllNDVkNjc5OTZiMzdhMGUzMw`
instead of `http://mycomnpany.com/api/test/?access_token=MGRkOWY1NjQ***jRmYzllNDVkNjc5OTZiMzdhMGUzMw`

Did you see that? `test?...` instead of `test/?...`.
This causing the server to return `301`, and the cache is failing.

Is it a bug?

**Comment by swankjesse** [comment]
`test` and `test/` are different URLs. No bug!

**Comment by AlmogBaku** [comment]
but, should it cache the redirect?

**Comment by swankjesse** [comment]
Redirect has this header:
```
Cache-Control: no-cache
```

**Comment by FisnikIbishi** [comment]
I use the interceptor like below and works fine for me. Hope it will help you
 
private val offlineResponseCacheInterceptor = Interceptor { chain ->
            val originalResponse = chain.proceed(chain.request())
            originalResponse.newBuilder()
                    .removeHeader("Pragma")
                    .header("Cache-Control", String.format("max-age=%d", 60))
                    .build()
        }
