### ISSUE TITLE
java.io.IOException: unexpected end of stream on com.squareup.okhttp.Address@a7b169ed

### ISSUE THREAD

**Issue by raviteja83** [square/okhttp#2147]
I am getting this exception on some devices and some requests are working and others are not working.How to fix this

**Comment by swankjesse** [comment]
If this is a bug, please isolate it into a test case so we can investigate & fix. If it’s a support request, please use stackoverflow instead.

**Comment by robfletcher** [comment]
I think I'm seeing the same thing when connecting to an HTTPS address if `retryConnectionFailure` is set to `false` on `OkHttpClient`.

**Comment by cfieber** [comment]
We were running into this issue using OkHttp via Retrofit for inter-microservice RPC.

The fix (which seemed surprising given the description of ConnectionPool's behaviour) was to explicitly give each OkHttpClient a new ConnectionPool (previously it was unspecified and falling through to the `ConnectionPool.systemDefault`, now we give each OkHttpClient a new ConnectionPool(5, 300000)) and our problem has gone away.

Also worth noting is this was really only manifesting on clients doing HTTPS with clientAuth.

At this point I haven't dug deeper to explain why this actually fixes things because we've applied it against Retrofit 1 / OkHttp 2 and we need to address that dead end first.

**Comment by moisesvs** [comment]
I have the same error. Could you share the fix?. Please. 

Thank a lot.

**Comment by rajesh-khadka** [comment]
I have same problem in okhttp3. How to resolve this issue ?

**Comment by allenzhangp** [comment]
I have same problem in okhttp3. How to resolve this issue ?

**Comment by cooperkong** [comment]
having same issue here too, it just randomly appears.

**Comment by gengjiawen** [comment]
@swankjesse, I can reproduce this problem.
All you need is to create a websocket server using [socketio](https://github.com/socketio/socket.io)
```node
var server = require('http').createServer();
var io = require('socket.io')(server);
io.on('connection', function(client){
  client.on('event', function(data){});
  client.on('disconnect', function(){});
});
server.listen(3000);
```
When I use this url "ws://echo.websocket.org" my code run correctly, but when I switch to "ws://localhost:3000", then WebSocketListener's onFailure print stacktrace like this:
```
java.io.IOException: unexpected end of stream on okhttp3.Address@b9c05ad8
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:201)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:53)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.access$100(RealCall.java:33)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: \n not found: size=0 content=…
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:215)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	... 21 more
```

So maybe it's a bug on socketio or some compatibility issue.

**Comment by gengjiawen** [comment]
I use Python [websockets](https://pypi.python.org/pypi/websockets) to create another websocket server, works fine.So maybe something wrong with the nodejs code (I am still learning node :) , for now i still have not a clue why socketio failed).

**Comment by cristin** [comment]
I also have this issue, but only on mobile data connection. Is there any fix? Thank you!

**Comment by isicout** [comment]
so many same issue here .
no any solution ?

**Comment by AndroDevMili** [comment]
Facing the same issue for HttpURLConnection any solution?

**Comment by AndroDevMili** [comment]
@JakeWharton Ok I shall add OkHttp.

**Comment by thefoureyedraven** [comment]
Fixed the issue by explicitly specifying the "Host:MyHostName" in the requests** for the following set up:

Android-Retrofit-OkHttp > Nginx (TLS enabled) > Gunicorn > Flask application.

Details:

1. As a test, OkHttp could connect to the Gunicorn server directly on the same host, but when Nginx was used for connection, the app error-ed out with "unexpected end of stream".

2. To ensure the issue wasn't with TLS configuration, a) made the same requests through Firefox, Openssl s_client, and curl: all of which returned a correct response to the request; and b) made non-TLS (http) request to a Non-TLS configured Nginx server: got the same unexpected end of stream error.

3.  The Nginx access logs showed a 444 response to the received request in the access logs: the configured response for requests with incorrect server name.

4. Updated the request to add the "Host:MyHostName" header: this resolved the issue.

5. Removed the  "Host:MyHostName" header from the request, and reproduced the issue. Added the  "Host:MyHostName" header back, and the issue was fixed.

Note: in the dev environment where this issue occurred, the prior-to-this-fix  "Host" header in the generated requests was "10.0.2.2:4433" -- as picked from the request base url -- instead of "10.0.2.2" (which is basically "127.0.0.1" for the emulator). Whereas the Nginx Server was configured for "127.0.0.1" as server_name in the Server context. 

Either I've misused the concept or probably an issue with how Retrofit/OkHttp parses host-name out of the base URL? With a port specified, one would expect it to pick just the IP part as host-name.

**Comment by youssefmaly** [comment]
> 



> Fixed the issue by explicitly specifying the "Host:MyHostName" in the requests** for the following set up:

@thefoureyedraven  Could you please share how did you explicitly specify host:myhostname in the request  ?

**Comment by yschimke** [comment]
This is in an interceptor, but generally OkHttp will honour an explicit "Host" header over the URL.

https://github.com/square/okhttp/blob/6d040e06c132048599cd8c22e9d2fc71e22d3245/okhttp/src/jvmTest/java/okhttp3/internal/http2/HttpOverHttp2Test.kt#L2162

```
        val request = Request.Builder()
          .url("...")
          .header("Host", "privateobject.com")
          .build()
```

**Comment by war44245-commits** [comment]
java.io.IOException: unexpected end of stream on com.android.okhttp.Address@61bae618
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:203)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFileMonitored(DownloadUtils.java:70)
	at net.kdt.pojavlaunch.mirrors.DownloadMirror.downloadFileMirrored(DownloadMirror.java:41)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.lambda$downloadFile$0$net-kdt-pojavlaunch-tasks-MinecraftDownloader$DownloaderTask(MinecraftDownloader.java:511)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask$$ExternalSyntheticLambda0.call(D8$$SyntheticClass:0)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:125)
	at net.kdt.pojavlaunch.utils.DownloadUtils.ensureSha1(DownloadUtils.java:151)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.downloadFile(MinecraftDownloader.java:510)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.verifyFileSha1(MinecraftDownloader.java:504)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.runCatching(MinecraftDownloader.java:489)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.run(MinecraftDownloader.java:477)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.io.EOFException: \n not found: size=0 content=...
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:202)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
	... 21 more

**Comment by yschimke** [comment]
@war44245-commits com.android.okhttp.internal.http is not this project.

**Comment by aa3skm-netizen** [comment]
wow Terrible bite

**Comment by samyaljbarh-debug** [comment]
java.io.IOException: unexpected end of stream on com.android.okhttp.Address@ee509410
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:203)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:542)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:30)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.acquireMinecraftToken(MicrosoftBackgroundLogin.java:247)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin.lambda$performLogin$2$net-kdt-pojavlaunch-authenticator-microsoft-MicrosoftBackgroundLogin(MicrosoftBackgroundLogin.java:83)
	at net.kdt.pojavlaunch.authenticator.microsoft.MicrosoftBackgroundLogin$$ExternalSyntheticLambda3.run(D8$$SyntheticClass:0)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.io.EOFException: \n not found: size=0 content=...
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:202)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
	... 14 more

**Comment by yschimke** [comment]
Wrong project

**Comment by short17a-sudo** [comment]
java.io.IOException: unexpected end of stream on com.android.okhttp.Address@f8309feb
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:203)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFileMonitored(DownloadUtils.java:80)
	at net.kdt.pojavlaunch.mirrors.DownloadMirror.downloadFileMirrored(DownloadMirror.java:49)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.lambda$downloadFile$0$net-kdt-pojavlaunch-tasks-MinecraftDownloader$DownloaderTask(MinecraftDownloader.java:500)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask$$ExternalSyntheticLambda0.call(Unknown Source:2)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:136)
	at net.kdt.pojavlaunch.utils.DownloadUtils.ensureSha1(DownloadUtils.java:161)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.downloadFile(MinecraftDownloader.java:499)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.verifyFileSha1(MinecraftDownloader.java:493)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.runCatching(MinecraftDownloader.java:478)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.run(MinecraftDownloader.java:466)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.io.EOFException: \n not found: size=0 content=...
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:202)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
	... 21 more

**Comment by yschimke** [comment]
Still the wrong project. Please stop posting unrelated stacktraces here

**Comment by haengma43-cloud** [comment]
java.io.IOException: unexpected end of stream on com.android.okhttp.Address@e0bab81b
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:203)
	at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:129)
	at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:750)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:622)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:475)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:411)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:248)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getInputStream(DelegatingHttpsURLConnection.java:211)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:30)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFileMonitored(DownloadUtils.java:70)
	at net.kdt.pojavlaunch.mirrors.DownloadMirror.downloadFileMirrored(DownloadMirror.java:41)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.lambda$downloadFile$0$net-kdt-pojavlaunch-tasks-MinecraftDownloader$DownloaderTask(MinecraftDownloader.java:469)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask$$ExternalSyntheticLambda0.call(D8$$SyntheticClass:0)
	at net.kdt.pojavlaunch.utils.DownloadUtils.downloadFile(DownloadUtils.java:125)
	at net.kdt.pojavlaunch.utils.DownloadUtils.ensureSha1(DownloadUtils.java:151)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.downloadFile(MinecraftDownloader.java:468)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.verifyFileSha1(MinecraftDownloader.java:462)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.runCatching(MinecraftDownloader.java:447)
	at net.kdt.pojavlaunch.tasks.MinecraftDownloader$DownloaderTask.run(MinecraftDownloader.java:435)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1302)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:677)
	at java.lang.Thread.run(Thread.java:1119)
Caused by: java.io.EOFException: \n not found: size=0 content=...
	at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:202)
	at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:188)
	... 21 more

**Comment by hten0600-lgtm** [comment]
val request = Request.Builder()
          .url("...")
          .header("Host", "privateobject.com")
          .build()

**Comment by hten0600-lgtm** [comment]
var server = require('http').createServer();
var io = require('socket.io')(server);
io.on('connection', function(client){
  client.on('event', function(data){});
  client.on('disconnect', function(){});
});
server.listen(3000);

**Comment by hten0600-lgtm** [comment]
java.io.IOException: unexpected end of stream on okhttp3.Address@b9c05ad8
    at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:201)
    at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
    at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:53)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
    at okhttp3.RealCall.access$100(RealCall.java:33)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.EOFException: \n not found: size=0 content=…
    at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:215)
    at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
    ... 21 more

**Comment by rigksiblaibepiwvopso-beep** [comment]
Please not https://github.com/square/okhttp/issues/2147  in zalithLauncher

**Comment by rigksiblaibepiwvopso-beep** [comment]
__
