### ISSUE TITLE
java.util.NoSuchElementException

### ISSUE THREAD

**Issue by sfsheng0322** [square/okhttp#2151]
java.util.NoSuchElementException
	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:79)
	at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:164)
	at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
	at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:283)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
	at com.squareup.okhttp.Call.getResponse(Call.java:286)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.access$100(Call.java:35)
	at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
	at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

Can you help me to find why it is happened?
Thanks!

**Comment by swankjesse** [comment]
Two possibilities:

 * OkHttp has a bug where we’re attempting to recover when we shouldn't be because we’ve exhausted all of the available routes.
 * OkHttp has a bug where you’ve got a custom DNS implementation that returned zero IP addresses for a host and we didn't reject that.

**Comment by swankjesse** [comment]
Please try OkHttp 2.7.1 which has a targeted fix for this problem.

**Comment by swankjesse** [comment]
I believe we have this fixed with 2.7.1. Will reopen if that fix wasn't sufficient.

**Comment by sfsheng0322** [comment]
2.6 is Ok, I will try 2.7.1 later, thanks very much! Merry Christmas！
