### ISSUE TITLE
ConnectionPoolTest.inUseConnectionsNotEvicted() is flaky

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#2165]
Also `leakedAllocation()`.

```
Tests run: 5, Failures: 0, Errors: 2, Skipped: 0, Time elapsed: 0.093 sec <<< FAILURE! - in okhttp3.ConnectionPoolTest
inUseConnectionsNotEvicted(okhttp3.ConnectionPoolTest)  Time elapsed: 0.009 sec  <<< ERROR!
java.lang.NullPointerException: null
	at okhttp3.internal.http.StreamAllocation.routeDatabase(StreamAllocation.java:204)
	at okhttp3.internal.http.StreamAllocation.<init>(StreamAllocation.java:90)
	at okhttp3.ConnectionPoolTest.inUseConnectionsNotEvicted(ConnectionPoolTest.java:84)

leakedAllocation(okhttp3.ConnectionPoolTest)  Time elapsed: 0 sec  <<< ERROR!
java.lang.NullPointerException: null
	at okhttp3.internal.http.StreamAllocation.routeDatabase(StreamAllocation.java:204)
	at okhttp3.internal.http.StreamAllocation.<init>(StreamAllocation.java:90)
	at okhttp3.ConnectionPoolTest.allocateAndLeakAllocation(ConnectionPoolTest.java:175)
	at okhttp3.ConnectionPoolTest.leakedAllocation(ConnectionPoolTest.java:164)
```

https://github.com/square/okhttp/pull/2162

**Comment by swankjesse** [comment]
Fixed with this:
```
  static {
    Internal.initializeInstanceForTests();
  }
```
