### ISSUE TITLE
okhttp3:logging-interceptor:3.0.0-RC1 wile adding to retrofit2 okhttp3 client

### ISSUE THREAD

**Issue by silva96** [square/okhttp#2206]
Hi, im using this gradle plugins
```
    compile 'com.squareup.retrofit2:retrofit:2.0.0-beta3'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0-beta3'
    compile 'com.squareup.okhttp3:logging-interceptor:3.0.0-RC1'
```

This is how I create my service:

```
        OkHttpClient client = new OkHttpClient();
        HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
        logging.setLevel(HttpLoggingInterceptor.Level.BODY);
        client.interceptors().add(logging);
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(BASE_URL)
                .addConverterFactory(GsonConverterFactory.create())
                .client(client)
                .build();
        APIService service = retrofit.create(APIService.class);

```

It fails when `client.interceptors().add(logging);`

With this strack trace:

```
01-06 09:30:27.944 27005-27005/com.silva.benjamin.ninetyninecoins E/AndroidRuntime: FATAL EXCEPTION: main
                                                                                    Process: com.silva.benjamin.ninetyninecoins, PID: 27005
                                                                                    java.lang.UnsupportedOperationException
                                                                                        at java.util.Collections$UnmodifiableCollection.add(Collections.java:928)
                                                                                        at com.silva.benjamin.ninetyninecoins.util.Helper.service(Helper.java:22)
                                                                                        at com.silva.benjamin.ninetyninecoins.fragments.ConsoleFragment.renderData(ConsoleFragment.java:60)
                                                                                        at com.silva.benjamin.ninetyninecoins.fragments.ConsoleFragment.onCreateView(ConsoleFragment.java:45)
                                                                                        at android.support.v4.app.Fragment.performCreateView(Fragment.java:1962)
                                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1067)
                                                                                        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1248)
                                                                                        at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:738)
                                                                                        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1613)
                                                                                        at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(FragmentManager.java:570)
                                                                                        at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:163)
                                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:1106)
                                                                                        at android.support.v4.view.ViewPager.populate(ViewPager.java:952)
                                                                                        at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1474)
                                                                                        at android.view.View.measure(View.java:17547)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                                        at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:610)
                                                                                        at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:677)
                                                                                        at android.view.View.measure(View.java:17547)
                                                                                        at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:940)
                                                                                        at android.view.View.measure(View.java:17547)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                                        at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
                                                                                        at android.view.View.measure(View.java:17547)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                                        at android.view.View.measure(View.java:17547)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                                        at android.view.View.measure(View.java:17547)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                                        at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1436)
                                                                                        at android.widget.LinearLayout.measureVertical(LinearLayout.java:722)
                                                                                        at android.widget.LinearLayout.onMeasure(LinearLayout.java:613)
                                                                                        at android.view.View.measure(View.java:17547)
                                                                                        at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5535)
                                                                                        at android.widget.FrameLayout.onMeasure(FrameLayout.java:436)
                                                                                        at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:2615)
                                                                                        at android.view.View.measure(View.java:17547)
                                                                                        at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2015)
                                                                                        at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1173)
                                                                                        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1379)
                                                                                        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1061)
                                                                                        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:5885)
                                                                                        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:767)
                                                                                        at android.view.Choreographer.doCallbacks(Choreographer.java:580)
                                                                                        at android.view.Choreographer.doFrame(Choreographer.java:550)
                                                                                        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:753)
                                                                                        at android.os.Handler.handleCallback(Handler.java:739)
                                                                                        at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                                        at android.os.Looper.loop(Looper.java:135)
                                                                                        at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                                    	at java.lang.reflect.Method.invoke(
01-06 09:30:30.760 27005-27005/com.silva.benjamin.ninetyninecoins I/Process: Sending signal. PID: 27005 SIG: 9
```

any lights on what's going on?

**Comment by serj-lotutovici** [comment]
Starting with OkHttp v3 `OkHttpClient` is immutable and so are the interceptors. To add the logging interceptor (or any other for that mater), use `OkHttpClient.Builder`.

**Comment by silva96** [comment]
Thanks @serj-lotutovici  for your quick reply. That solves the problem. But LoggingInterceptor has no builder.

 here is the adjusted piece of code

```
        HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
        logging.setLevel(HttpLoggingInterceptor.Level.BODY);
        OkHttpClient client = new OkHttpClient.Builder().addInterceptor(logging).build();
        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(BASE_URL)
                .addConverterFactory(GsonConverterFactory.create())
                .client(client)
                .build();
        APIService service = retrofit.create(APIService.class);
        return service;
```

**Comment by agonist** [comment]
@silva96 hey I just faced the same problem few minutes ago here how I solved it : 

```
  HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
  OkHttpClient httpClient = new OkHttpClient.Builder().addInterceptor(interceptor).build();

retrofit = new Retrofit.Builder()
                .client(httpClient)
                .baseUrl(appContext.getString(R.string.base_url))
                .build();
```

**Comment by smoothdvd** [comment]
@agonist thanks!

**Comment by dp-singh** [comment]
What if we want to add two interceptors?

**Comment by JakeWharton** [comment]
call the `addInterceptor` method multiple times.

**Comment by usmaanz** [comment]
How do I add an interceptor but at a later stage? I do have the okHttpClient object. I don't wish to overwrite any interceptors. Only add an extra one.

**Comment by JakeWharton** [comment]
OkHttpClient newClient = oldClient.newBuilder().addInterceptor(..).build();

**Comment by NightlyNexus** [comment]
@usmaanz Alternatively, I sometimes add easily mutable Interceptors and just inject them where I want them.

**Comment by lawloretienne** [comment]
@JakeWharton I tried calling `oldClient.newBuilder().addInterceptor(..).build();` but it doesn't look like any interceptors are being added.  How can I track down what i am messing up?

**Comment by NightlyNexus** [comment]
@lawloretienne In the code you posted, you are making a new OkHttpClient instance. Building a new one does not modify the old one.
```
okHttpClient = okHttpClient.newBuilder()
    // ...
    .build();
```

**Comment by lawloretienne** [comment]
@NightlyNexus then how do you modify an old okHttpClient instance?

**Comment by NightlyNexus** [comment]
@lawloretienne You can't add Interceptors to an existing OkHttpClient. As stated above, rebind a new client later on, or make mutable Interceptors. StackOverflow will be able to help for these usage questions. Use the okhttp tag.

**Comment by lawloretienne** [comment]
So then what can be set up after the call to newBuilder() ?

**Comment by lawloretienne** [comment]
Okay i figured it out.  I wasn't assigning the new configuration to another variable.  After making that change it all works now.

Similar to the answer here :
http://stackoverflow.com/questions/40793201/interceptor-no-getting-called-retrofit2/40825440#40825440
