### ISSUE TITLE
Cache is closed exception with OkHttp 2.7.1

### ISSUE THREAD

**Issue by hidroh** [square/okhttp#2228]
Got these (very rare) crashes recently, started after I upgraded to Retrofit 2.0.0-beta2. All of my network calls use asynchronous callbacks, either through `OkHttpClient.newCall(Request).enqueue(OkHttp.Callback)` or `Retrofit.Call.enqueue(Retrofit.Callback)`

I'm using OkHttp 2.7.1 and Retrofit 2.0.0-beta2.

```
Fatal Exception: java.lang.IllegalStateException: cache is closed
       at com.squareup.okhttp.internal.DiskLruCache.checkNotClosed(DiskLruCache.java:630)
       at com.squareup.okhttp.internal.DiskLruCache.get(DiskLruCache.java:424)
       at com.squareup.okhttp.Cache.get(Cache.java:184)
       at com.squareup.okhttp.Cache$1.get(Cache.java:139)
       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
       at com.squareup.okhttp.Call.getResponse(Call.java:286)
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
       at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
       at com.squareup.okhttp.Call.access$100(Call.java:35)
       at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
       at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by swankjesse** [comment]
Do you have code that closes the cache?

**Comment by hidroh** [comment]
Nope I don't have any logic that handles cache, except for during construction of `OkHttpClient` instance as follows:

```java
OkHttpClient okHttpClient = new OkHttpClient();
okHttpClient.setCache(new Cache(context.getApplicationContext().getCacheDir(),
        CACHE_SIZE));
```

My network logic mostly relies on standard Retrofit interfaces with callback, with `@Headers("Cache-Control: max-age=600")`, except for a few POST request chain thru OkHttp with cookie handling.

**Comment by UweTrottmann** [comment]
I am seeing the `cache is closed` at this same location as well with okhttp 3.0.1.

```
Fatal Exception: java.lang.IllegalStateException: cache is closed
       at okhttp3.internal.DiskLruCache.checkNotClosed(DiskLruCache.java:622)
       at okhttp3.internal.DiskLruCache.get(DiskLruCache.java:420)
       at okhttp3.Cache.get(Cache.java:194)
       at okhttp3.Cache$1.get(Cache.java:144)
       at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:198)
       at okhttp3.RealCall.getResponse(RealCall.java:240)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
       at okhttp3.RealCall.execute(RealCall.java:57)
```

Most of them (95%) occur on **Nexus 9/Android 6.0.1**.

Possibly related to #2365.

**Comment by samehgerges** [comment]
We started to see same crash after upgrading from 2.5 to 2.7.5. Using retrofit 1.9.0
It has not clear scenario and happens on different devices with different operating systems (4.4.2, 4.4.4, 5.0.2, 5.1.1)
Here is stack trace

Stack Trace
_________________________________
0	java.lang.IllegalStateException: cache is closed
1		at com.squareup.okhttp.internal.DiskLruCache.checkNotClosed(DiskLruCache.java:630)
2		at com.squareup.okhttp.internal.DiskLruCache.edit(DiskLruCache.java:452)
3		at com.squareup.okhttp.internal.DiskLruCache.edit(DiskLruCache.java:446)
4		at com.squareup.okhttp.Cache.put(Cache.java:235)
5		at com.squareup.okhttp.Cache.access$000(Cache.java:131)
6		at com.squareup.okhttp.Cache$1.put(Cache.java:142)
7		at com.squareup.okhttp.internal.http.HttpEngine.maybeCache(HttpEngine.java:404)
8		at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:647)
9		at com.squareup.okhttp.Call.getResponse(Call.java:287)
10		at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
11		at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
12		at com.squareup.okhttp.Call.access$100(Call.java:35)
13		at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:171)
14		at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
15		at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
16		at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
17		at java.lang.Thread.run(Thread.java:831)

**Comment by 2fours** [comment]
Also seeing this in 3.0.1.

**Comment by 2fours** [comment]
For me looks like it's happening when I hit the same POST url twice in a row, happens every time:

```
04-02 12:18:09.149 26715-26889/com.twofours.surespot D/okhttp: okhttp: --> POST http://192.168.10.24:8080/invite/old HTTP/1.1 (0-byte body)
04-02 12:18:09.229 26715-26889/com.twofours.surespot D/okhttp: okhttp: <-- 204 No Content http://192.168.10.24:8080/invite/old (74ms, unknown-length body)
04-02 12:18:16.196 26715-26889/com.twofours.surespot D/okhttp: okhttp: --> DELETE http://192.168.10.24:8080/friends/old HTTP/1.1 (0-byte body)
04-02 12:18:16.236 26715-26889/com.twofours.surespot D/okhttp: okhttp: <-- 204 No Content http://192.168.10.24:8080/friends/old (46ms, unknown-length body)
04-02 12:18:19.479 26715-26889/com.twofours.surespot D/okhttp: okhttp: --> POST http://192.168.10.24:8080/invite/old HTTP/1.1 (0-byte body)
04-02 12:18:19.479 26715-26889/com.twofours.surespot E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                       Process: com.twofours.surespot, PID: 26715
                                                                       java.lang.IllegalStateException: cache is closed
                                                                           at okhttp3.internal.DiskLruCache.checkNotClosed(DiskLruCache.java:622)
                                                                           at okhttp3.internal.DiskLruCache.get(DiskLruCache.java:420)
                                                                           at okhttp3.Cache.get(Cache.java:194)
                                                                           at okhttp3.Cache$1.get(Cache.java:144)
                                                                           at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:198)
                                                                           at okhttp3.RealCall.getResponse(RealCall.java:240)
                                                                           at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
                                                                           at com.twofours.surespot.network.UserAgentInterceptor.intercept(UserAgentInterceptor.java:26)
                                                                           at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
                                                                           at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:203)
                                                                           at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
                                                                           at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
                                                                           at okhttp3.RealCall.access$100(RealCall.java:30)
                                                                           at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
                                                                           at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                           at java.lang.Thread.run(Thread.java:818)
```

**Comment by samehgerges** [comment]
In my case this was happening because I had two okhttp instances share the same cache directory, which isn't recommended by okhttp according to documentation. Once having two different cache directories problem not happening anymore

**Comment by 2fours** [comment]
@samehgerges definitely only have 1 instance.

**Comment by 2fours** [comment]
Figured it out. I was calling cache.delete() before the second POST which apparently closes the cache.
