### ISSUE TITLE
IncompatibleClassChangeError on Android 5.x after upgrading from OkHttp 2.6 to 2.7.2

### ISSUE THREAD

**Issue by felipecsl** [square/okhttp#2234]
```
E/AndroidRuntime( 5516): Caused by: java.lang.IncompatibleClassChangeError: The method 'com.squareup.okhttp.Protocol com.squareup.okhttp.Connection.getProtocol()' was expected to be of type virtual but instead was found to be of type interface (declaration of 'java.lang.reflect.ArtMethod' appears in /system/framework/core-libart.jar)
E/AndroidRuntime( 5516): 	at com.squareup.okhttp.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:146)
E/AndroidRuntime( 5516): 	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
E/AndroidRuntime( 5516): 	at com.airbnb.airrequest.CacheControlInterceptor.intercept(CacheControlInterceptor.java:28)
E/AndroidRuntime( 5516): 	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:695)
E/AndroidRuntime( 5516): 	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
E/AndroidRuntime( 5516): 	at com.squareup.okhttp.Call.getResponse(Call.java:287)
E/AndroidRuntime( 5516): 	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
E/AndroidRuntime( 5516): 	at com.airbnb.airrequest.CacheRevalidationInterceptor.intercept(CacheRevalidationInterceptor.java:30)
E/AndroidRuntime( 5516): 	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
E/AndroidRuntime( 5516): 	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
E/AndroidRuntime( 5516): 	at com.squareup.okhttp.Call.execute(Call.java:80)
E/AndroidRuntime( 5516): 	at retrofit.OkHttpCall.execute(OkHttpCall.java:116)
E/AndroidRuntime( 5516): 	at retrofit.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:107)
E/AndroidRuntime( 5516): 	at retrofit.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:88)
E/AndroidRuntime( 5516): 	at rx.Observable$2.call(Observable.java:162)
E/AndroidRuntime( 5516): 	at rx.Observable$2.call(Observable.java:154)
E/AndroidRuntime( 5516): 	at rx.Observable$2.call(Observable.java:162)
E/AndroidRuntime( 5516): 	at rx.Observable$2.call(Observable.java:154)
E/AndroidRuntime( 5516): 	at rx.Observable$2.call(Observable.java:162)
E/AndroidRuntime( 5516): 	at rx.Observable$2.call(Observable.java:154)
E/AndroidRuntime( 5516): 	at rx.Observable$2.call(Observable.java:162)
E/AndroidRuntime( 5516): 	at rx.Observable$2.call(Observable.java:154)
E/AndroidRuntime( 5516): 	at rx.Observable$2.call(Observable.java:162)
E/AndroidRuntime( 5516): 	at rx.Observable$2.call(Observable.java:154)
E/AndroidRuntime( 5516): 	at rx.Observable$2.call(Observable.java:162)
E/AndroidRuntime( 5516): 	at rx.Observable$2.call(Observable.java:154)
E/AndroidRuntime( 5516): 	at rx.Observable$2.call(Observable.java:162)
E/AndroidRuntime( 5516): 	at rx.Observable$2.call(Observable.java:154)
E/AndroidRuntime( 5516): 	at rx.Observable$2.call(Observable.java:162)
E/AndroidRuntime( 5516): 	at rx.Observable$2.call(Observable.java:154)
E/AndroidRuntime( 5516): 	at rx.Observable$2.call(Observable.java:162)
E/AndroidRuntime( 5516): 	at rx.Observable$2.call(Observable.java:154)
E/AndroidRuntime( 5516): 	at rx.Observable.unsafeSubscribe(Observable.java:8098)
E/AndroidRuntime( 5516): 	at rx.internal.operators.OperatorSubscribeOn$1$1.call(OperatorSubscribeOn.java:62)
E/AndroidRuntime( 5516): 	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
E/AndroidRuntime( 5516): 	... 7 more
```

**Comment by felipecsl** [comment]
Sorry, my bad. Forgot to also bump the logging-interceptor version.
