### ISSUE TITLE
NPE when logging-interceptor:3.0.1with okhttp-ws:3.0.1 

### ISSUE THREAD

**Issue by whylee259** [square/okhttp#2264]
I'm using okhttp-ws and logging-interceptor is added to okhttp client.

I think NPE is caused because `response.body()` returns alway null.

```
01-20 14:28:45.033 12757-12904/? E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
  java.lang.NullPointerException
    at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:207)
    at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
    at okhttp3.RealCall.access$100(RealCall.java:30)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:841)
```

**Comment by JakeWharton** [comment]
I think we define that response.body() should never return null, so this is
more likely a bug in the okhttp-ws module than the logger.

**Comment by JakeWharton** [comment]
Fixed by https://github.com/square/okhttp/pull/2831
