### ISSUE TITLE
ArrayIndexOutOfBoundsException happend in okhttp:2.7.2

### ISSUE THREAD

**Issue by Ooorange** [square/okhttp#2295]
i looked everywhere,and i do not know how is that happen?it's the  reason i used in worry way or it's a bug i should to void to use,give me some solution。thanks
java.lang.ArrayIndexOutOfBoundsException: src.length=2048 srcPos=2560 dst.length=2048 dstPos=0 length=512
	at java.lang.System.arraycopy(System.java:261)
	at com.android.okio.Segment.split(Segment.java:98)
	at com.android.okio.OkBuffer.write(OkBuffer.java:579)
	at com.android.okio.OkBuffer.read(OkBuffer.java:610)
	at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:53)
	at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:442)
	at com.android.okio.RealBufferedSource$1.read(RealBufferedSource.java:168)
	at java.io.InputStream.read(InputStream.java:162)
	at com.autonavi.amap.mapcore.BaseMapLoader.doRequest(Unknown Source)
	at com.autonavi.amap.mapcore.a.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:831)

**Comment by swankjesse** [comment]
Typically this kind of crash occurs when you're accessing a stash from multiple threads concurrently.

**Comment by swankjesse** [comment]
I think we fix this upstream in Okio. https://github.com/square/okio/issues/163
