### ISSUE TITLE
Okio dependency problem

### ISSUE THREAD

**Issue by Anonomousxxx** [square/okhttp#2297]
Okay, so I am using Retrofit, OkHttp and Picasso in my project. Here are my relevant dependencies in the project:

`compile ('com.squareup.retrofit:retrofit:2.0.0-beta2')
compile ('com.squareup.retrofit:converter-gson:2.0.0-beta2')
compile ('com.squareup.okhttp:okhttp-urlconnection:2.5.0')
compile ('com.squareup.picasso:picasso:2.5.2')
compile 'com.squareup:otto:1.3.6'
compile ('com.squareup.okhttp:okhttp:2.5.0')`

The project builds but when it starts it crashes **on Android versions <5.0** This is what I get in the log:

`01-28 18:03:54.103 20816-20816/by.set.pibox E/dalvikvm: Could not find class 'android.app.AppOpsManager', referenced from method com.google.android.gms.common.GooglePlayServicesUtil.zzb
**01-28 18:03:54.543 20816-20816/by.set.pibox E/dalvikvm: Could not find class 'retrofit.Retrofit$Builder', referenced from method by.set.pibox.helpers.ApiHelper.getInstance
01-28 18:03:54.568 20816-20816/by.set.pibox E/dalvikvm: Could not find class 'okio.Buffer', referenced from method com.squareup.okhttp.internal.Util.toHumanReadableAscii
01-28 18:03:54.648 20816-20816/by.set.pibox E/dalvikvm: Could not find class 'okio.Buffer', referenced from method by.set.pibox.helpers.ApiHelper$1.intercept
01-28 18:03:54.658 20816-20816/by.set.pibox E/dalvikvm: Could not find class 'com.squareup.okhttp.internal.DiskLruCache$4', referenced from method com.squareup.okhttp.internal.DiskLruCache.<clinit>
01-28 18:03:54.678 20816-20816/by.set.pibox E/dalvikvm: Could not find class 'com.squareup.okhttp.internal.DiskLruCache$2', referenced from method com.squareup.okhttp.internal.DiskLruCache.newJournalWriter**
01-28 18:03:58.888 20816-20816/by.set.pibox E/CrashlyticsCore: Failed to execute task.
                                                              java.util.concurrent.TimeoutException
                                                               at java.util.concurrent.FutureTask.get(FutureTask.java:173)
                                                               at com.crashlytics.android.core.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException(CrashlyticsExecutorServiceWrapper.java:44)
                                                               at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:235)
                                                               at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
                                                               at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
                                                               at dalvik.system.NativeStart.main(Native Method)
01-28 18:03:59.293 20816-20816/by.set.pibox E/AndroidRuntime: FATAL EXCEPTION: main
                                                          java.lang.ExceptionInInitializerError
                                                              at by.set.pibox.helpers.HelperFactory.setHelper(HelperFactory.java:112)
                                                              at by.set.pibox.PiboxApplication.onCreate(PiboxApplication.java:30)
                                                              at by.set.pibox.PiboxApplication_.onCreate(PiboxApplication_.java:32)
                                                              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5056)
                                                              at android.app.ActivityThread.access$1300(ActivityThread.java:162)
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1432)
                                                              at android.os.Handler.dispatchMessage(Handler.java:99)
                                                              at android.os.Looper.loop(Looper.java:158)
                                                              at android.app.ActivityThread.main(ActivityThread.java:5751)
                                                              at java.lang.reflect.Method.invokeNative(Native Method)
                                                              at java.lang.reflect.Method.invoke(Method.java:511)
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083)
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850)
                                                              at dalvik.system.NativeStart.main(Native Method)
                                                           Caused by: java.lang.ExceptionInInitializerError
                                                              at com.squareup.okhttp.Cache.<init>(Cache.java:172)
                                                              at com.squareup.okhttp.Cache.<init>(Cache.java:168)
                                                              at by.set.pibox.helpers.ApiHelper.<clinit>(ApiHelper.java:111)
                                                              at by.set.pibox.helpers.HelperFactory.setHelper(HelperFactory.java:112) 
                                                              at by.set.pibox.PiboxApplication.onCreate(PiboxApplication.java:30) 
                                                              at by.set.pibox.PiboxApplication_.onCreate(PiboxApplication_.java:32) 
                                                              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012) 
                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5056) 
                                                              at android.app.ActivityThread.access$1300(ActivityThread.java:162) 
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1432) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                              at android.os.Looper.loop(Looper.java:158) 
                                                              at android.app.ActivityThread.main(ActivityThread.java:5751) 
                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                              at java.lang.reflect.Method.invoke(Method.java:511) 
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083) 
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850) 
                                                              at dalvik.system.NativeStart.main(Native Method) 
                                                          ** Caused by: java.lang.NoClassDefFoundError: com.squareup.okhttp.internal.DiskLruCache$4**
                                                              at com.squareup.okhttp.internal.DiskLruCache.<clinit>(DiskLruCache.java:809)
                                                              at com.squareup.okhttp.Cache.<init>(Cache.java:172) 
                                                              at com.squareup.okhttp.Cache.<init>(Cache.java:168) 
                                                              at by.set.pibox.helpers.ApiHelper.<clinit>(ApiHelper.java:111) 
                                                              at by.set.pibox.helpers.HelperFactory.setHelper(HelperFactory.java:112) 
                                                              at by.set.pibox.PiboxApplication.onCreate(PiboxApplication.java:30) 
                                                              at by.set.pibox.PiboxApplication_.onCreate(PiboxApplication_.java:32) 
                                                              at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012) 
                                                              at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5056) 
                                                              at android.app.ActivityThread.access$1300(ActivityThread.java:162) 
                                                              at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1432) 
                                                              at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                              at android.os.Looper.loop(Looper.java:158) 
                                                              at android.app.ActivityThread.main(ActivityThread.java:5751) 
                                                              at java.lang.reflect.Method.invokeNative(Native Method) 
                                                              at java.lang.reflect.Method.invoke(Method.java:511) 
                                                              at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1083) 
                                                              at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:850) 
                                                              at dalvik.system.NativeStart.main(Native Method) `

I've searched this error, and has found out that okhttp uses okio
But when I add the okio jar, I get this while building the app:
`Error:Execution failed for task            ':pibox:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException:    java.util.zip.ZipException: duplicate entry: okio/AsyncTimeout$1.class`

I also tried adding the jar and excluding modules from libs, but no success anyway, until I exclude from all libs I get duplicate error, than I get the first error

Please help

**Comment by JakeWharton** [comment]
Are you using multidex?

**Comment by Anonomousxxx** [comment]
Yes, I do

**Comment by JakeWharton** [comment]
The exception indicates that required classes are not available and are not being loaded properly. For example, `com.squareup.okhttp.Cache` is causing `com.squareup.okhttp.internal.DiskLruCache` to be loaded which then cannot find `com.squareup.okhttp.internal.DiskLruCache$4`. This is either a problem with your build system performing multidex or a bug in the multidex library.

You should either try StackOverflow to help with the multidex configuration problem or report the bug to http://b.android.com/ if it turns out to be a bug in the multidex library.

These errors:
```
Could not find class 'retrofit.Retrofit$Builder', referenced from method by.set.pibox.helpers.ApiHelper.getInstance
Could not find class 'okio.Buffer', referenced from method com.squareup.okhttp.internal.Util.toHumanReadableAscii
Could not find class 'okio.Buffer', referenced from method by.set.pibox.helpers.ApiHelper$1.intercept
```
also indicate that it's a packaging problem by your build system, and not a bug in OkHttp itself.

> found out that okhttp uses okio but when I add the okio jar

Because you are using 
```groovy
compile ('com.squareup.okhttp:okhttp:2.5.0')
```
Gradle will automatically pull down the Okio dependency. This is why adding the jar manually causes duplicate classes to be present.

Also totally unrelated, but you can remove this explicit dependency:
```groovy
compile ('com.squareup.okhttp:okhttp-urlconnection:2.5.0')
```
It's not needed by the versions of Retrofit or Picasso anymore.

**Comment by JakeWharton** [comment]
Also if you are using ProGuard that might be part of the cause, but it's hard to know without a ton more information.

**Comment by Anonomousxxx** [comment]
Okay, thank you for the answer, I hope it will help

**Comment by thamizh2k7** [comment]
> Could not download okio.jar (com.squareup.okio:okio:1.13.0)
   > Could not get resource 'https://jcenter.bintray.com/com/squareup/okio/okio/1.13.0/okio-1.13.0.jar'.
      > Could not GET 'https://jcenter.bintray.com/com/squareup/okio/okio/1.13.0/okio-1.13.0.jar'. Received status code 504 from server: Gateway Time-out
i got this error

**Comment by swankjesse** [comment]
We don't publish to bintray. Use Maven Central.

**Comment by artem-zinnatullin** [comment]
Just in case Bintray (Jcenter) is experiencing problems 

<img width="982" alt="screen shot 2018-03-27 at 5 43 57 am" src="https://user-images.githubusercontent.com/967132/37968024-e4b24626-3181-11e8-931c-35dcb95275a1.png">

(they also managed to put wrong date on screenshot)

See http://status.bintray.com
