### ISSUE TITLE
Listener failed to call close on message payload. okhttp-ws:3.0.1

### ISSUE THREAD

**Issue by whylee259** [square/okhttp#2303]
This may be occurred when receive an message.
Two WebSocket is connected to server and they received same message.

Stacktrace is below.

------------------------------------------------------------------------------------------------------------------------------------------
java.lang.IllegalStateException: Listener failed to call close on message payload.
        at okhttp3.internal.ws.WebSocketReader.readMessageFrame(WebSocketReader.java:244)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:108)
        at okhttp3.internal.ws.RealWebSocket.readMessage(RealWebSocket.java:97)
        at okhttp3.ws.WebSocketCall.createWebSocket(WebSocketCall.java:152)
        at okhttp3.ws.WebSocketCall.access$000(WebSocketCall.java:41)
        at okhttp3.ws.WebSocketCall$1.onResponse(WebSocketCall.java:97)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:818)

**Comment by mpost** [comment]
I see the same error on okhttp 2.7.4.

**Comment by swankjesse** [comment]
Change your code to call close in onMessage() ?

**Comment by whylee259** [comment]
I've added 
`responseBody.close();`
on `onMessage(ResponseBody responseBody)` 
to the old websocket.

and the failure is not occurred anymore.

**Comment by Sh3rawi** [comment]
@whylee259 could you please elaborate more on what you did ? Im using react-native which uses okhttp for networking in android, and this exception happens quite alot when a socket is being closed and another one is being opened (if the server closes the connection for example) and a msg arrives at that time. Any hint on what to do on the java side might be of great help.
