### ISSUE TITLE
Spdy3ConnectionTest.serverSendsSettingsToClient is flaky

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#2305]
From [Travis](https://api.travis-ci.org/jobs/106069151/log.txt?deansi=true):

```
Tests run: 43, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 2.366 sec <<< FAILURE! - in okhttp3.internal.framed.Spdy3ConnectionTest
serverSendsSettingsToClient(okhttp3.internal.framed.Spdy3ConnectionTest)  Time elapsed: 0.006 sec  <<< FAILURE!
java.lang.AssertionError: expected:<10> but was:<0>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:743)
	at org.junit.Assert.assertEquals(Assert.java:118)
	at org.junit.Assert.assertEquals(Assert.java:555)
	at org.junit.Assert.assertEquals(Assert.java:542)
	at okhttp3.internal.framed.Spdy3ConnectionTest.serverSendsSettingsToClient(Spdy3ConnectionTest.java:290)
```

**Comment by swankjesse** [comment]
Obsolete.
