### ISSUE TITLE
Cache crashed, failed to delete file

### ISSUE THREAD

**Issue by KennyGoers** [square/okhttp#2318]
I'm starting to see a lot of this exception in my app released with OkHttp 3.01 via Picasso 2.5.2 (using Jake's adapter from 3.01 to 2.5.2)

Fatal Exception: java.lang.RuntimeException: java.io.IOException: failed to delete /storage/emulated/0/Android/data/com.trixiesoft.clapp/cache/images/51d313bf28724ba47541b0ca45ac084f.0
       at okhttp3.internal.DiskLruCache$1.run(DiskLruCache.java:178)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

Caused by java.io.IOException: failed to delete /storage/emulated/0/Android/data/com.trixiesoft.clapp/cache/images/51d313bf28724ba47541b0ca45ac084f.0
       at okhttp3.internal.io.FileSystem$1.delete(FileSystem.java:70)
       at okhttp3.internal.DiskLruCache.removeEntry(DiskLruCache.java:599)
       at okhttp3.internal.DiskLruCache.trimToSize(DiskLruCache.java:656)
       at okhttp3.internal.DiskLruCache.access$200(DiskLruCache.java:85)
       at okhttp3.internal.DiskLruCache$1.run(DiskLruCache.java:172)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

**Comment by dave-r12** [comment]
@KennyGoers do you happen to have any other information? Can you reproduce with a simple example or test case?

**Comment by KennyGoers** [comment]
It's the best I can do for this one, it comes up in my crashlytics crashes.
I'll see if I can find some device correlation, but if I remember it was
scattered across 4 and 5 and different manufacturers.

**Comment by dave-r12** [comment]
@KennyGoers the disk cache implementation should now recover from this scenario, see #2366. Hopefully you won't see this exception again :)

**Comment by KennyGoers** [comment]
Awesome, time line on release!

Thanks!

**Comment by JakeWharton** [comment]
We do not provide release ETAs because OkHttp is not a product.

**Comment by KennyGoers** [comment]
NP, just wondering if anything might be pushing one like the 3.1.2
situation. I can build my own.

Thanks for taking the time.
Your work is much appreciated.

**Comment by swankjesse** [comment]
No ETAs. But Actual time of arrival of 3.2.0 is right now.

**Comment by dave-r12** [comment]
Closed with #2366.

**Comment by spacemase** [comment]
@swankjesse so is this in 3.2 or 3.3?  You say 3.2, Milestone says 3.3.  So confoosed.

**Comment by swankjesse** [comment]
3.2.
