### ISSUE TITLE
Unable to get trust certificate

### ISSUE THREAD

**Issue by Peddro** [square/okhttp#2334]
Hi. I had an issue related with getting the certificate on an android Nexus 6P. I'm using retrofit:1.9.0 and okhttp:3.1.1 . Retrofit returned an UNEXPECTED error. 
Adding the stack trace below:

`Fatal Exception: java.lang.RuntimeException: retrofit.RetrofitError: Attempt to invoke virtual method 'java.security.cert.X509Certificate java.security.cert.TrustAnchor.getTrustedCert()' on a null object reference
       at goodnews.maily.maily.data.api.exceptions.ApiErrorHandler.handleError(ApiErrorHandler.java:64)
       at retrofit.CallbackRunnable.run(CallbackRunnable.java:49)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at retrofit.Platform$Android$2$1.run(Platform.java:142)
       at java.lang.Thread.run(Thread.java:818)
Caused by retrofit.RetrofitError: Attempt to invoke virtual method 'java.security.cert.X509Certificate java.security.cert.TrustAnchor.getTrustedCert()' on a null object reference
       at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:400)
       at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
       at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
       at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at retrofit.Platform$Android$2$1.run(Platform.java:142)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.cert.X509Certificate java.security.cert.TrustAnchor.getTrustedCert()' on a null object reference
       at okhttp3.internal.tls.AndroidTrustRootIndex.findByIssuerAndSignature(AndroidTrustRootIndex.java:43)
       at okhttp3.internal.tls.CertificateChainCleaner.clean(CertificateChainCleaner.java:68)
       at okhttp3.CertificatePinner.check(CertificatePinner.java:151)
       at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:208)
       at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:148)
       at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
       at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
       at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
       at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
       at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
       at okhttp3.RealCall.getResponse(RealCall.java:240)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
       at goodnews.maily.maily.data.api.UserAgentInterceptor.intercept(UserAgentInterceptor.java:27)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
       at okhttp3.RealCall.execute(RealCall.java:57)
       at com.jakewharton.retrofit.Ok3Client.execute(Ok3Client.java:40)
       at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
       at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
       at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
       at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at retrofit.Platform$Android$2$1.run(Platform.java:142)
       at java.lang.Thread.run(Thread.java:818)`

**Comment by swankjesse** [comment]
Try upgrading to 3.1.2.
