### ISSUE TITLE
Certificate pinning crash with prelease GMS

### ISSUE THREAD

**Issue by tadfisher** [square/okhttp#2341]
Since we shipped 2.7.4 in a hotfix release, we're receiving many reports of this crash, confined completely to the Nexus 5X, Nexus 6, and Nexus 6P on Android 6.0.1.

Any pointers would be appreciated.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.cert.X509Certificate java.security.cert.TrustAnchor.getTrustedCert()' on a null object reference
       at com.squareup.okhttp.internal.tls.AndroidTrustRootIndex.findByIssuerAndSignature(AndroidTrustRootIndex.java:43)
       at com.squareup.okhttp.internal.tls.CertificateChainCleaner.clean(CertificateChainCleaner.java:68)
       at com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:207)
       at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
       at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
       at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
       at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
       at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
       at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
       at com.squareup.okhttp.Call.getResponse(Call.java:286)
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
       at com.banksimple.http.ApiInterceptor.intercept(ApiInterceptor.java:50)
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
       at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
       at com.squareup.okhttp.Call.execute(Call.java:80)
       at com.banksimple.http.BaseApiClient.execute(BaseApiClient.java:94)
       at com.banksimple.http.BaseApiClient.execute(BaseApiClient.java:106)
       at com.banksimple.http.ClientSettingsApiClient.getAndroidSettings(ClientSettingsApiClient.java:28)
       at com.banksimple.service.ClientSettingsManagerIntentService.getClientSettings(ClientSettingsManagerIntentService.java:83)
       at com.banksimple.service.ClientSettingsManagerIntentService.onHandleIntent(ClientSettingsManagerIntentService.java:69)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:148)
       at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by tadfisher** [comment]
Info about our configuration:

- We install the GMS security provider.
- We pin a public key and not an entire cert like so:

```java
    /**
     * Returns the {@code CertificatePinner} to be used with this client or null.
     */
    public CertificatePinner getCertificatePinner() {
        String path = getPinnedCertsPath();
        if (TextUtils.isEmpty(path)) {
            return null;
        }

        PublicKey publicKey;
        try {
            publicKey = getPubKey(mContext, path);
        } catch (Exception e) {
            SFLog.e("Failed to initialize certificate pinning!", e);
            return null;
        }

        CertificatePinner.Builder builder = new CertificatePinner.Builder();
        builder.add(getHostname(), sha1(publicKey));
        return builder.build();
    }

    /**
     * Generate a SHA-1 hash of a public key in the format expected by {@code CertificatePinner}
     */
    private static String sha1(PublicKey key) {
        return "sha1/" + Util.sha1(ByteString.of(key.getEncoded())).base64();
    }

    /**
     * Returns a public key loaded from the given path relative to the assets directory.
     * <p/>
     * The key must be stored in the {@code DER} format.
     */
    private static PublicKey getPubKey(Context context, String path) throws IOException,
            NoSuchAlgorithmException, InvalidKeySpecException {
        InputStream in = context.getAssets().open(path);

        // Read the key file
        byte[] bytes = new byte[in.available()];
        in.read(bytes);
        in.close();

        // Load the public key
        X509EncodedKeySpec spec = new X509EncodedKeySpec(bytes);
        KeyFactory keyFactory = KeyFactory.getInstance("RSA");
        return keyFactory.generatePublic(spec);
    }
```

**Comment by swankjesse** [comment]
Any chance you can reproduce this? It’s weird and bad that it can’t find the trusted cert that just succeeded the handshake.

**Comment by tadfisher** [comment]
@swankjesse: Not able to reproduce, but we have found that the affected users are running an Android security patch level of "March 1, 2016", and we have confirmed at least in two cases that the users are Googlers. Assuming the rest are not time travelers, I believe this is an issue with an upcoming change to the system JSSE provider.

**Comment by tadfisher** [comment]
We've had a Googler install a test build with a synchronous GMS SecurityProvider install, and that does not appear to solve the issue.

**Comment by tadfisher** [comment]
It appears the OS version reported may not be correct; we've only been able to confirm this crash occurs on "unreleased" OS builds, and the engineers we've been in contact with have declined to state their OS builds or versions :)

**Comment by danh32** [comment]
We've been seeing this issue as well. It increased very sharply on Friday Feb 12th, even though we hadn't released any new code for 2 weeks at that point. That build of our app was running okhttp v3.0.1. We've also seen this crash since in a couple of patch updates that we've pushed containing okhttp v3.1.1 and v3.1.2.

It seems likely that this crash is being caused by an incompatibility in a new version of Google Play Services's Security Provider that was pushed around Feb 12th. We were able to confirm with an affected user that his GPS version is 8.7.01, our devices running 8.4.89 are unaffected.

We are also doing sha1 cert pinning, but are not manually installing the GMS Provider. Please let me know if I can provide any additional info!

**Comment by danh32** [comment]
I've got a bit more info:

- I shipped an affected user a build without cert pinning, there is no crash.
- He also had a device running the new Android version, but without the latest GPS. this runs our current prod app without the crash.
- Interestingly, he also ran the app on a Pixel C tablet with the latest GPS and our prod app, and still no crash. I'm really curious what's different about the Pixel C in this scenario.

Sorry if this is beating a dead horse at this point -- all signs point to the new GPS and using cert pinning.

**Comment by chadbrubaker** [comment]
Here from Android,

AndroidTrustRootIndex is using reflection to call conscrypt's TrustManagerImpl.findTrustAnchorBySubjectAndPublicKey, which will return null if the cert is not in the trusted set, which can be pretty common and totally normal, you should be checking that the return value isn't null before calling getTrustedCert().

**Comment by swankjesse** [comment]
Hey Chad, what's the best way to discover the trusted CA in this case?

**Comment by chadbrubaker** [comment]
The logic in CertificateChainCleaner.clean already looks like it correctly handles the case where the current cert is not the CA, but the current code will never have trustRootIndex.findByIssuerAndSignature actually return null since findTrustAnchorBySubjectAndPublicKey will return null, leading to a NPE when you call getTrustedCert. 

Your current code should work so long as you return null if findTrustAnchorBySubjectAndPublicKey returns null.

**Comment by swankjesse** [comment]
How does it work without a trust root?

**Comment by swankjesse** [comment]
(We expect clients to be able to pin the root certificate)
