### ISSUE TITLE
java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by LyndonDing** [square/okhttp#2350]
java.lang.OutOfMemoryError
	at java.lang.String.<init>(String.java:265)
	at java.lang.String.<init>(String.java:238)
	at okhttp3.ResponseBody.string(ResponseBody.java:109)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:33)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1076)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:569)
	at java.lang.Thread.run(Thread.java:856)

**Comment by swankjesse** [comment]
You'll need to stream your response rather than buffering it all in memory.
