### ISSUE TITLE
DiskCache can't be load when use Picasso with No network.

### ISSUE THREAD

**Issue by cctanfujun** [square/okhttp#2362]
I use picasso and okhttps to load image.If I off the network,kill the process,reopen the activity,the images can't be load success.

I use Picasso with okhhtp3 picasso and picasso:picasso2-okhttp3-downloader:1.0.2' like this:

```Java
compile 'com.squareup.okhttp3:okhttp:3.1.2'   
compile 'com.squareup.okio:okio:1.6.0'
compile 'com.jakewharton.picasso:picasso2-okhttp3-downloader:1.0.2' 
```

In my application oncreate()

```Java
OkHttpClient client = new OkHttpClient();
        Picasso picasso = new Picasso.Builder(this)
                .downloader(new OkHttp3Downloader(client))
                .build();
        Picasso.setSingletonInstance(picasso);
```

I debug the code ,I find in OkHttp3Downloader.java

```Java
{
    CacheControl cacheControl = null;
    if (networkPolicy != 0) {
      if (NetworkPolicy.isOfflineOnly(networkPolicy)) {
        cacheControl = CacheControl.FORCE_CACHE;
      } else {
        CacheControl.Builder builder = new CacheControl.Builder();
        if (!NetworkPolicy.shouldReadFromDiskCache(networkPolicy)) {
          builder.noCache();
        }
        if (!NetworkPolicy.shouldWriteToDiskCache(networkPolicy)) {
          builder.noStore();
        }
        cacheControl = builder.build();
      }
    }

    Request.Builder builder = new Request.Builder().url(uri.toString());
    if (cacheControl != null) {
      builder.cacheControl(cacheControl);
    }

    okhttp3.Response response = client.newCall(builder.build()).execute();
    int responseCode = response.code();
    if (responseCode >= 300) {
      response.body().close();
      throw new ResponseException(responseCode + " " + response.message(), networkPolicy,
          responseCode);
    }

    boolean fromCache = response.cacheResponse() != null;

    ResponseBody responseBody = response.body();
    return new Response(responseBody.byteStream(), fromCache, responseBody.contentLength());
  }
```
will get an IOException.  java.net.UnknownHostException: Unable to resolve host "xxx": No address associated with hostname.

I konw the picasso has cache http respone and image in picasso cache dir with name  XXX.0 XXX.1.
why url not change image can't be reload?

**Comment by cctanfujun** [comment]
I solve this Problem by using Follow code in My Application Class onCreate() method

```Java
public void onCreate() {
        super.onCreate();

        File httpCacheDirectory = new File(getCacheDir(), "picasso-cache");
        //设置缓存 10M
        Cache cache = new Cache(httpCacheDirectory, 10 * 1024 * 1024);
        OkHttpClient okHttpClient = new OkHttpClient.Builder()
                .addInterceptor(new Interceptor() {
                    @Override
                    public Response intercept(Chain chain) throws IOException {
                        Request request = chain.request();
                        Response response = chain.proceed(request);

                        String cacheControl = request.cacheControl().toString();
                        if (TextUtils.isEmpty(cacheControl)) {
                            cacheControl = "public, max-age=3600";
                        }
                        return response.newBuilder()
                                .header("Cache-Control", cacheControl)
                                .removeHeader("Pragma")
                                .build();
                    }
                })
                .cache(cache).build();
        Picasso picasso = new Picasso.Builder(this)
                .downloader(new OkHttp3Downloader(okHttpClient))
                .build();
        Picasso.setSingletonInstance(picasso);
     }

```

But it will cause a strick mode error sometimes.

```Java

02-25 10:41:59.850 4116-4131/? E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
                                             java.lang.Throwable: Explicit termination method 'close' not called
                                                 at dalvik.system.CloseGuard.open(CloseGuard.java:184)
                                                 at java.io.FileInputStream.<init>(FileInputStream.java:78)
                                                 at okio.Okio.source(Okio.java:163)
                                                 at okhttp3.internal.io.FileSystem$1.source(FileSystem.java:44)
                                                 at okhttp3.internal.DiskLruCache$Entry.snapshot(DiskLruCache.java:988)
                                                 at okhttp3.internal.DiskLruCache.get(DiskLruCache.java:424)
                                                 at okhttp3.Cache.get(Cache.java:193)
                                                 at okhttp3.Cache$1.get(Cache.java:143)
                                                 at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:198)
                                                 at okhttp3.RealCall.getResponse(RealCall.java:240)
                                                 at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
                                                 at com.meizu.flyme.appcenter.AppCenterApplication$1.intercept(AppCenterApplication.java:38)
                                                 at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
                                                 at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
                                                 at okhttp3.RealCall.execute(RealCall.java:57)
                                                 at com.jakewharton.picasso.OkHttp3Downloader.load(OkHttp3Downloader.java:126)
                                                 at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
                                                 at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
                                                 at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
                                                 at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                 at java.lang.Thread.run(Thread.java:818)
                                                 at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)

```

Is this An OKhttp bug？

**Comment by swankjesse** [comment]
Looks like the warning is due to something not closing the HTTP response stream. Possibly Picasso.

**Comment by swankjesse** [comment]
No obvious action to take here.
