### ISSUE TITLE
Cache not working on Nexus 9

### ISSUE THREAD

**Issue by renato-almeida** [square/okhttp#2365]
Hello there,

I've come across with an error regarding the cache on a Nexus 9 tablet running Android 5.1.1
I'm using Retrofit 1.9.0 and okhttp 2.7.4.

I've added a Cache to the OkHttpClient, but the problem is, when I make a request that has the header **Cache-Control:public, max-age=60, s-maxage=60** it does not cache in a Nexus 9, but in a Nexus 6, Samsung S6 and Samsung S5 mini it does.

the RestAdapter logic:

        String API = "https://api.github.com";
        RestAdapter.Builder builder = new RestAdapter.Builder();

        // Setup Http client
        OkHttpClient client = new OkHttpClient();

        // Http client cache
        File httpCacheDir = new File(getCacheDir(), CACHE_DIRECTORY);
        Cache cache = new Cache(httpCacheDir, CACHE_SIZE);
        client.setCache(cache);

        builder.setClient(new OkClient(client));

        RestAdapter restAdapter = builder.
                setLogLevel(RestAdapter.LogLevel.FULL).setEndpoint(API).build();

        GitApi git = restAdapter.create(GitApi.class);

        git.getFeed("square", new Callback<GitModel>() {

            @Override
            public void success(GitModel gitModel, Response response) {
                Log.d("TAG", gitModel.toString());
                Snackbar.make(view, gitModel.toString(), Snackbar.LENGTH_LONG).show();
            }

            @Override
            public void failure(RetrofitError error) {
                Snackbar.make(view, error.toString(), Snackbar.LENGTH_LONG).show();
            }
        });

Logs:

```
-24 14:25:03.360 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: ---> HTTP GET https://api.github.com/users/square
02-24 14:25:03.360 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: ---> END HTTP (no body)
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: <--- HTTP 200 https://api.github.com/users/square (936ms)
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: Server: GitHub.com
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: Date: Tue, 23 Feb 2016 14:24:20 GMT
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: Content-Type: application/json; charset=utf-8
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: Transfer-Encoding: chunked
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: Status: 200 OK
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: X-RateLimit-Limit: 60
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: X-RateLimit-Remaining: 59
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: X-RateLimit-Reset: 1456241060
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: Cache-Control: public, max-age=60, s-maxage=60
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: ETag: W/"60845db1ec4931a35849cad61285fb5f"
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: Vary: Accept
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: Last-Modified: Wed, 10 Feb 2016 09:55:08 GMT
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: X-GitHub-Media-Type: github.v3; format=json
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: Access-Control-Allow-Credentials: true
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: Access-Control-Expose-Headers: ETag, Link, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: Access-Control-Allow-Origin: *
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: Content-Security-Policy: default-src 'none'
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: Strict-Transport-Security: max-age=31536000; includeSubdomains; preload
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: X-Content-Type-Options: nosniff
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: X-Frame-Options: deny
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: X-XSS-Protection: 1; mode=block
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: Vary: Accept-Encoding
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: X-Served-By: e724c57ebb9961c772a91e2dd7421c8d
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: X-GitHub-Request-Id: C3F597D2:A4E6:8CD9A89:56CC6B93
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: OkHttp-Sent-Millis: 1456323904095
02-24 14:25:04.297 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: OkHttp-Received-Millis: 1456323904273
02-24 14:25:04.307 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: {"login":"square","id":82592,"avatar_url":"https://avatars.githubusercontent.com/u/82592?v=3","gravatar_id":"","url":"https://api.github.com/users/square","html_url":"https://github.com/square","followers_url":"https://api.github.com/users/square/followers","following_url":"https://api.github.com/users/square/following{/other_user}","gists_url":"https://api.github.com/users/square/gists{/gist_id}","starred_url":"https://api.github.com/users/square/starred{/owner}{/repo}","subscriptions_url":"https://api.github.com/users/square/subscriptions","organizations_url":"https://api.github.com/users/square/orgs","repos_url":"https://api.github.com/users/square/repos","events_url":"https://api.github.com/users/square/events{/privacy}","received_events_url":"https://api.github.com/users/square/received_events","type":"Organization","site_admin":false,"name":"Square","company":null,"blog":"http://square.github.io","location":null,"email":null,"hireable":null,"bio":null,"public_repos":160,"public_gists":5,"followers":0,"following":0,"created_at":"2009-05-08T23:28:44Z","updated_at":"2016-02-10T09:55:08Z"}
02-24 14:25:04.307 12701-14957/com.renatoalmeida.retrofitcenas D/Retrofit: <--- END HTTP (1108-byte body)
02-24 14:25:04.352 12701-12701/com.renatoalmeida.retrofitcenas D/TAG: GitModel{login='square', id=82592, avatarUrl='https://avatars.githubusercontent.com/u/82592?v=3', gravatarId='', url='https://api.github.com/users/square', htmlUrl='https://github.com/square', followersUrl='https://api.github.com/users/square/followers', followingUrl='https://api.github.com/users/square/following{/other_user}', gistsUrl='https://api.github.com/users/square/gists{/gist_id}', starredUrl='https://api.github.com/users/square/starred{/owner}{/repo}', subscriptionsUrl='https://api.github.com/users/square/subscriptions', organizationsUrl='https://api.github.com/users/square/orgs', reposUrl='https://api.github.com/users/square/repos', eventsUrl='https://api.github.com/users/square/events{/privacy}', receivedEventsUrl='https://api.github.com/users/square/received_events', type='Organization', siteAdmin=false, name='Square', company='null', blog='http://square.github.io', location='null', email='null', hireable=null, bio=null, publicRepos=160, publicGists=5, followers=0, following=0, createdAt='2009-05-08T23:28:44Z', updatedAt='2016-02-10T09:55:08Z'}
02-24 14:25:04.352 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x1/d=0x7f0900f9 a=2 r=0x7f0900f9}
02-24 14:25:04.352 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xc01 a=2 r=0x7f08005b}
02-24 14:25:04.352 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xc01 a=2 r=0x7f08005b}
02-24 14:25:04.352 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0x14001 a=2 r=0x7f080014}
02-24 14:25:04.353 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f0c006b}
02-24 14:25:04.353 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xc01 a=2 r=0x7f08005b}
02-24 14:25:04.353 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xe01 a=2 r=0x7f08005c}
02-24 14:25:04.353 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xc01 a=2 r=0x7f08005b}
02-24 14:25:04.353 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xe01 a=2 r=0x7f08005c}
02-24 14:25:04.353 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f0c006c}
02-24 14:25:04.353 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xc01 a=2 r=0x7f08005b}
02-24 14:25:04.353 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xe01 a=2 r=0x7f08005c}
02-24 14:25:04.353 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xc01 a=2 r=0x7f08005b}
02-24 14:25:04.353 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xe01 a=2 r=0x7f08005c}


02-24 14:25:16.990 12701-15435/com.renatoalmeida.retrofitcenas D/Retrofit: ---> HTTP GET https://api.github.com/users/square
02-24 14:25:16.990 12701-15435/com.renatoalmeida.retrofitcenas D/Retrofit: ---> END HTTP (no body)
02-24 14:25:17.010 12701-15435/com.renatoalmeida.retrofitcenas D/Retrofit: ---- ERROR https://api.github.com/users/square
02-24 14:25:17.014 12701-15435/com.renatoalmeida.retrofitcenas D/Retrofit: java.net.UnknownHostException: Unable to resolve host "api.github.com": No address associated with hostname
                                                                               at java.net.InetAddress.lookupHostByName(InetAddress.java:457)
                                                                               at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
                                                                               at java.net.InetAddress.getAllByName(InetAddress.java:215)
                                                                               at com.squareup.okhttp.Dns$1.lookup(Dns.java:39)
                                                                               at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175)
                                                                               at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141)
                                                                               at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83)
                                                                               at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
                                                                               at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
                                                                               at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
                                                                               at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
                                                                               at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
                                                                               at com.squareup.okhttp.Call.getResponse(Call.java:286)
                                                                               at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
                                                                               at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
                                                                               at com.squareup.okhttp.Call.execute(Call.java:80)
                                                                               at retrofit.client.OkClient.execute(OkClient.java:53)
                                                                               at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
                                                                               at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
                                                                               at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278)
                                                                               at retrofit.CallbackRunnable.run(CallbackRunnable.java:42)
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                               at retrofit.Platform$Android$2$1.run(Platform.java:142)
                                                                               at java.lang.Thread.run(Thread.java:818)
                                                                            Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
                                                                               at libcore.io.Posix.android_getaddrinfo(Native Method)
                                                                               at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
                                                                               at java.net.InetAddress.lookupHostByName(InetAddress.java:438)
                                                                               at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252) 
                                                                               at java.net.InetAddress.getAllByName(InetAddress.java:215) 
                                                                               at com.squareup.okhttp.Dns$1.lookup(Dns.java:39) 
                                                                               at com.squareup.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:175) 
                                                                               at com.squareup.okhttp.internal.http.RouteSelector.nextProxy(RouteSelector.java:141) 
                                                                               at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:83) 
                                                                               at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174) 
                                                                               at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126) 
                                                                               at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95) 
                                                                               at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281) 
                                                                               at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224) 
                                                                               at com.squareup.okhttp.Call.getResponse(Call.java:286) 
                                                                               at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243) 
                                                                               at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205) 
                                                                               at com.squareup.okhttp.Call.execute(Call.java:80) 
                                                                               at retrofit.client.OkClient.execute(OkClient.java:53) 
                                                                               at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326) 
                                                                               at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220) 
                                                                               at retrofit.RestAdapter$RestHandler$2.obtainResponse(RestAdapter.java:278) 
                                                                               at retrofit.CallbackRunnable.run(CallbackRunnable.java:42) 
                                                                               at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                               at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                               at retrofit.Platform$Android$2$1.run(Platform.java:142) 
                                                                               at java.lang.Thread.run(Thread.java:818) 
02-24 14:25:17.014 12701-15435/com.renatoalmeida.retrofitcenas D/Retrofit: ---- END ERROR
02-24 14:25:17.014 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x1/d=0x7f0900f9 a=2 r=0x7f0900f9}
02-24 14:25:17.014 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xc01 a=2 r=0x7f08005b}
02-24 14:25:17.014 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xc01 a=2 r=0x7f08005b}
02-24 14:25:17.014 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0x14001 a=2 r=0x7f080014}
02-24 14:25:17.015 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f0c006b}
02-24 14:25:17.015 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xc01 a=2 r=0x7f08005b}
02-24 14:25:17.015 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xe01 a=2 r=0x7f08005c}
02-24 14:25:17.015 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xc01 a=2 r=0x7f08005b}
02-24 14:25:17.015 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xe01 a=2 r=0x7f08005c}
02-24 14:25:17.016 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x12/d=0x0 a=2 r=0x7f0c006c}
02-24 14:25:17.016 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xc01 a=2 r=0x7f08005b}
02-24 14:25:17.016 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xe01 a=2 r=0x7f08005c}
02-24 14:25:17.016 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xc01 a=2 r=0x7f08005b}
02-24 14:25:17.016 12701-12701/com.renatoalmeida.retrofitcenas W/Resources: Converting to string: TypedValue{t=0x5/d=0xe01 a=2 r=0x7f08005c}
```
The steps were, the first request was with internet on, the second request was with internet off.
And it should have returned the same message as the first request.

              
If you'd like, I can provide a full example.

**Comment by dave-r12** [comment]
@renato-almeida did you have any luck? I don't have a Nexus 9, but can you confirm files are being created in the cache directory?

**Comment by swankjesse** [comment]
No clear action for us to take here.
