### ISSUE TITLE
NetworkOnMainThreadException when using proxy

### ISSUE THREAD

**Issue by drindt** [square/okhttp#2369]
Using com.squareup.okhttp3:okhttp:3.0.1 together with a proxy. This code i invoked inside my application:
```java
Builder builder = new Builder()
        .proxy(new Proxy(Type.HTTP,
                new InetSocketAddress(PROXY_HOST, PROXY_PORT)));
```
This stacktrace is the result:
```
Caused by: android.os.NetworkOnMainThreadException
 at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1147)
 at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
 at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
 at java.net.InetAddress.getByName(InetAddress.java:305)
 at java.net.InetSocketAddress.<init>(InetSocketAddress.java:105)
 at java.net.InetSocketAddress.<init>(InetSocketAddress.java:90)
```
I guess this is a false positive warning? Thank you very much.

**Comment by JakeWharton** [comment]
Use `InetSocketAddress.createUnresolved` instead of the constructor to defer DNS lookup to first use (which will be on a background thread).

**Comment by drindt** [comment]
Thank you for the information and the quick response.

**Comment by code4a** [comment]
Thanks
