### ISSUE TITLE
NullPointerException in AndroidTrustRootIndex (Okhttp 2.7.5)

### ISSUE THREAD

**Issue by mahdihijazi** [square/okhttp#2378]
I have the following crash on Nexus 9/Android 5.0
using Okhttp 2.7.5

```
Error: com.android.volley.VolleyError: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                              at com.android.volley.NetworkDispatcher.run(NetworkDispatcher.java:135)
                                                           Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.Object.getClass()' on a null object reference
                                                              at com.squareup.okhttp.internal.tls.AndroidTrustRootIndex.get(AndroidTrustRootIndex.java:57)
                                                              at com.squareup.okhttp.internal.Platform$Android.trustRootIndex(Platform.java:266)
                                                              at com.squareup.okhttp.internal.io.RealConnection.trustRootIndex(RealConnection.java:248)
                                                              at com.squareup.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:206)
                                                              at com.squareup.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:149)
                                                              at com.squareup.okhttp.internal.io.RealConnection.connect(RealConnection.java:112)
                                                              at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:184)
                                                              at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:126)
                                                              at com.squareup.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:95)
                                                              at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:281)
                                                              at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:224)
                                                              at com.squareup.okhttp.Call.getResponse(Call.java:286)
                                                              at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
```

**Comment by swankjesse** [comment]
What do you get when you run this?
```
System.out.println(okHttpClient.getSslSocketFactory().getClass());
```

**Comment by mahdihijazi** [comment]
class android.net.SSLCertificateSocketFactory

**Comment by jebstuart** [comment]
Same problem here, and I'll add a little more detail about my use case in case it helps.

My dev environment uses a self-signed certificate, so I create my own SSLSocketFactory subclass which will return that cert as valid.  I only do this against the dev environment, prod uses the system's default/strong SSLSocketFactory instead.

I also use a CertificatePinner for all environments.

So I get this exception against my dev environment, due to the custom SSLSocketFactory subclass, which doesn't have the members that OkHttp is trying to access by reflection, but prod works fine.

Happens on both Android 5.1 and 6.0.

**Comment by cjkrieseSF** [comment]
We just encountered the ame here with 2.7.5 on two Nexus 5X phones that were updated to March security patch to Android 6.0.1

**Comment by swankjesse** [comment]
@cjkrieseSF yikes. Can you tell me what this returns?
```
System.out.println(okHttpClient.getSslSocketFactory().getClass());
```

**Comment by cjkrieseSF** [comment]
@swankjesse My mistake re: version in my earlier (now deleted) post.  The problem was seen in 2.7.4 but now with 2.7.5, all seems good. Thanks for response.

**Comment by swankjesse** [comment]
Closing because I believe this is fixed. If you see a problem on the latest 2.x or 3.x release, please reopen.

**Comment by mahdihijazi** [comment]
double checked it on 2.7.5 and it sill crashes, I reopen a ticket here
https://github.com/square/okhttp/issues/2425

I wonder if we can help tracing the issue or you need any further details.
