### ISSUE TITLE
OKHttp Null Pointer Exception in v2.3.0

### ISSUE THREAD

**Issue by pamoptly** [square/okhttp#2381]
Optimizely is seeing a crash for clients using our SDK with OKHttp.  We are getting the following crash log specifically for Sony devices on Android 6.  Is this something that you can help with?

Please let me know!

`Fatal Exception: java.lang.RuntimeException: An error occurred while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:309)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.cert.X509Certificate java.security.cert.TrustAnchor.getTrustedCert()' on a null object reference
       at com.squareup.okhttp.internal.tls.AndroidTrustRootIndex.findByIssuerAndSignature(SourceFile:43)
       at com.squareup.okhttp.internal.tls.CertificateChainCleaner.clean(SourceFile:68)
       at com.squareup.okhttp.internal.io.RealConnection.connectTls(SourceFile:207)
       at com.squareup.okhttp.internal.io.RealConnection.connectSocket(SourceFile:149)
       at com.squareup.okhttp.internal.io.RealConnection.connect(SourceFile:112)
       at com.squareup.okhttp.internal.http.StreamAllocation.findConnection(SourceFile:184)
       at com.squareup.okhttp.internal.http.StreamAllocation.findHealthyConnection(SourceFile:126)
       at com.squareup.okhttp.internal.http.StreamAllocation.newStream(SourceFile:95)
       at com.squareup.okhttp.internal.http.HttpEngine.connect(SourceFile:281)
       at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(SourceFile:224)
       at com.squareup.okhttp.Call.getResponse(SourceFile:286)
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(SourceFile:243)
       at de.idealo.android.util.OkHttpClientFactory$UserAgentInterceptor.intercept(SourceFile:204)
       at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(SourceFile:232)
       at com.squareup.okhttp.Call.getResponseWithInterceptorChain(SourceFile:205)
       at com.squareup.okhttp.Call.execute(SourceFile:80)
       at com.optimizely.LogAndEvent.OptimizelyTimeSeriesEventsManager$TimeSeriesEventTask.doInBackground$10299ca(SourceFile:281)
       at com.optimizely.LogAndEvent.OptimizelyTimeSeriesEventsManager$TimeSeriesEventTask.doInBackground(SourceFile:243)
       at android.os.AsyncTask$2.call(AsyncTask.java:295)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)`

**Comment by swankjesse** [comment]
Hey! To cope with some awkward SSL stuff, OkHttp is doing dangerous & weird things extract the default trust store out of the system’s SSLSocketFactory. It looks like we’re unable to interop with Optimizely’s SSLSocketFactory. Any idea why Optimizely is changing the system default SSLSocketFactory?

**Comment by redochka** [comment]
same thing here with Galaxy S6 and Nexus 5X

**Comment by swankjesse** [comment]
No clear action for us to take here.
