### ISSUE TITLE
NullPointerException in AndroidTrustRootIndex (Okhttp 3.2.0)

### ISSUE THREAD

**Issue by trramsiq** [square/okhttp#2386]
NullPointer on Android 5.0.2 running on a Samsung SM A300H.Fatal Exception: 

Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.security.cert.X509Certificate java.security.cert.TrustAnchor.getTrustedCert()' on a null object reference
       at okhttp3.internal.tls.AndroidTrustRootIndex.findByIssuerAndSignature(AndroidTrustRootIndex.java:43)
       at okhttp3.internal.tls.CertificateChainCleaner.clean(CertificateChainCleaner.java:68)
       at okhttp3.CertificatePinner.check(CertificatePinner.java:151)
       at okhttp3.internal.io.RealConnection.connectTls(RealConnection.java:208)
       at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:148)
       at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
       at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
       at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
       at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
       at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
       at okhttp3.RealCall.getResponse(RealCall.java:240)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
       at com.soudfa.APIs.HeaderInterceptor.intercept(HeaderInterceptor.java:24)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:142)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
       at okhttp3.RealCall.access$100(RealCall.java:30)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by swankjesse** [comment]
Are you completely sure you aren't using a different version of OkHttp? The line numbers of your stack trace don't align with OkHttp 3.2.0.

**Comment by trramsiq** [comment]
You are completely right! 
The issues is coming from a build that runs OkHttp 3.1.1. 
The issue does not seem to be in OkHttp 3.2.0.

**Comment by swankjesse** [comment]
No problem.
