### ISSUE TITLE
HEAD calls with OkHttp fail with 504 Gateway Time-out

### ISSUE THREAD

**Issue by inder123** [square/okhttp#2387]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [X ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

            Request request = new Request.Builder()
                    .head()
                    .url("http://www.vudu.com/rss/contents.xml")
                    .build();
            Response response = client.newCall(request).execute();
            int statusCode = response.code();
            // Status code comes back as 504

Equivalent code with HttpUrlConnection:
            HttpURLConnection con = (HttpURLConnection) new URL("http://www.vudu.com/rss/contents.xml").openConnection();
            con.setRequestMethod("HEAD");
            int statusCode = con.getResponseCode();
// Returns 200

**Comment by swankjesse** [comment]
You wouldn't happen to be forcing the cache, would you?

**Comment by inder123** [comment]
No. I also tried setting Cache-Control to explicitly max-age=0 but didn't make a difference.

**Comment by swankjesse** [comment]
Install the logging interceptor & paste the headers?

**Comment by swankjesse** [comment]
And try with a default instance of OkHttpClient (

**Comment by dave-r12** [comment]
Maybe something with there web server? I see this:

```sh
$ curl -v -X HEAD http://www.vudu.com/rss/contents.xml

> HEAD /rss/contents.xml HTTP/1.1
> Host: www.vudu.com
> User-Agent: curl/7.43.0
> Accept: */*
> 
< HTTP/1.1 200 OK
< Date: Sat, 05 Mar 2016 13:32:16 GMT
< Server: Apache
```

When I add gzip, it seems to fail:

```bash
$ curl -v -H "Accept-Encoding: gzip" -X HEAD http://www.vudu.com/rss/contents.xml

 HEAD /rss/contents.xml HTTP/1.1
> Host: www.vudu.com
> User-Agent: curl/7.43.0
> Accept: */*
> Accept-Encoding: gzip
> 
< HTTP/1.1 504 Gateway Time-out
< Server: EdgePrism/4.3.2.0
```

**Comment by inder123** [comment]
HEAD http://www.vudu.com/rss/contents.xml
Accept: */*
User-Agent: Mozilla/5.0
Cache-Control: max-age=0

Received 504  Gateway Time-out in 13633.1ms
Server: EdgePrism/4.3.2.0
Mime-Version: 1.0
Date: Sat, 05 Mar 2016 19:34:14 GMT
Content-Type: text/html
Expires: Sat, 05 Mar 2016 19:34:14 GMT
Content-Length: 2
Connection: keep-alive
OkHttp-Sent-Millis: 1457206443851
OkHttp-Received-Millis: 1457206457402


I have tried removing all client headers, or adding different ones. They made no difference.

**Comment by inder123** [comment]
With default OkHttpClient (and logging enabled), here are the logs:

HEAD http://www.vudu.com/rss/contents.xml

java.net.SocketTimeoutException: timeout
	at okio.Okio$3.newTimeoutException(Okio.java:207)
	at okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
	at com.squareup.okhttp.Call.getResponse(Call.java:287)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.peel.server.vudu.VuduProvider$2.intercept(VuduProvider.java:122)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at com.peel.server.vudu.VuduProvider.getLastModifiedWithOkHttp(VuduProvider.java:163)
	at com.peel.server.vudu.VuduProvider.downloadXml(VuduProvider.java:83)
	at com.peel.server.vudu.VuduProviderTest.testDownloadVudu(VuduProviderTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:86)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:38)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:459)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:675)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:382)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:192)
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	... 41 more

**Comment by inder123** [comment]
Here is a Unit test to reproduce this bug:


import static org.junit.Assert.assertEquals;

import java.io.IOException;

import org.junit.Test;

import com.squareup.okhttp.Interceptor;
import com.squareup.okhttp.OkHttpClient;
import com.squareup.okhttp.Request;
import com.squareup.okhttp.Response;

public class HeadTest {
    @Test
    public void testOkHttpHead() throws Exception {
        OkHttpClient client = createOkHttpClient();
       Request request = new Request.Builder()
              .head()
              .url("http://www.vudu.com/rss/contents.xml")
//              .header("Accept", "*/*")
//              .header("User-Agent", "Mozilla/5.0")
//              .header("Cache-Control", "max-age=0")
              //.header("Accept-Language", "en-US,en;q=0.8")
              .build();
      Response response = client.newCall(request).execute();
      int statusCode = response.code();
      assertEquals(200, statusCode);
    }

    private OkHttpClient createOkHttpClient() {
        OkHttpClient client = new OkHttpClient();
//      client.setFollowRedirects(true);
//      client.setFollowSslRedirects(true);
//      client.setReadTimeout(30 * 1000, TimeUnit.MILLISECONDS);
//      client.setConnectTimeout(30 * 1000, TimeUnit.MILLISECONDS);
      client.interceptors().add(new Interceptor() {
          @Override public Response intercept(Chain chain) throws IOException {
            Request request = chain.request();
            long t1 = System.nanoTime();
            System.out.println(request.method() + " " + request.url() + "\n" + request.headers());
            Response response = chain.proceed(request);
            long t2 = System.nanoTime();
            System.out.println(String.format("Received %s  %s in %.1fms%n%s",
                response.code(), response.message(), (t2 - t1) / 1e6d, response.headers()));
            return response;
          }
        });
        return client;
    }
}

**Comment by inder123** [comment]
Smaller test:
```
import static org.junit.Assert.assertEquals;
import java.net.HttpURLConnection;
import java.net.URL;
import org.junit.Test;

import com.squareup.okhttp.OkHttpClient;
import com.squareup.okhttp.Request;
import com.squareup.okhttp.Response;
public class HeadTest {
    /**
     * Test to reproduce <a href="https://github.com/square/okhttp/issues/2387">a bug</a>
     * in OkHttp.
     */
    @Test
    public void testOkHttpHead() throws Exception {
        String url = "http://www.vudu.com/rss/contents.xml";

        HttpURLConnection con = (HttpURLConnection) new URL(url).openConnection();
        con.setRequestMethod("HEAD");
        int statusCode = con.getResponseCode();
        assertEquals(200, statusCode);

        OkHttpClient client = new OkHttpClient();
        Request request = new Request.Builder().head().url(url).build();
        Response response = client.newCall(request).execute();
        statusCode = response.code();
        assertEquals(200, statusCode);
    }
}
```

**Comment by swankjesse** [comment]
Try adding an `Accept-Encoding` request header:

```
    Request request = new Request.Builder().head()
        .url(url)
        .header("Accept-Encoding", "identity")
        .build();
```

Looks like the vudu.com webserver isn’t prepared to mix `HEAD` requests with `Accept-Encoding: gzip` which is what OkHttp is sending. This is a bug in their webserver, but you can work around it by disabling compression.

**Comment by inder123** [comment]
I wonder if this may be a more serious problem with okhttp. For caching with Last-Modified header, OkHttp uses HEAD calls to check if the resource has changed. All such calls will fail.

Why do you use gzip with HEAD? Why not use identity since the response is not going to have body anyway?

**Comment by swankjesse** [comment]
OkHttp doesn't use HEAD calls for caching.

We enable gzip with HEAD because we enable it with GET, and part of the motivation of HEAD is to preview what GET will return.
