### ISSUE TITLE
Android 2.3 occur a Exception :`OkHttp ConnectionPool`

### ISSUE THREAD

**Issue by MrFuFuFu** [square/okhttp#2400]
Hi，I got a runtime `NullPointerException`, It's like blow code: it's occur my Android 2.3 device, It's chance to happen it.

```java
AndroidRuntime﹕ FATAL EXCEPTION: OkHttp ConnectionPool
    java.lang.NullPointerException
            at com.squareup.okhttp.ConnectionPool.performCleanup(Unknown Source)
            at com.squareup.okhttp.ConnectionPool.runCleanupUntilPoolIsEmpty(Unknown Source)
            at com.squareup.okhttp.ConnectionPool.access$000(Unknown Source)
            at com.squareup.okhttp.ConnectionPool$1.run(Unknown Source)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1088)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:581)
            at java.lang.Thread.run(Thread.java:1019)
```

this is my dependencies

```xml
    //Network
    compile 'com.squareup.okhttp:okhttp:2.6.0'
    compile 'com.squareup.retrofit:retrofit:1.9.0'
    //RxJava
    compile 'io.reactivex:rxandroid:1.1.0'
    compile 'io.reactivex:rxjava:1.1.0'
```

**Comment by swankjesse** [comment]
Thanks for the report. Fixed in OkHttp 3.

**Comment by MrFuFuFu** [comment]
Hi, @swankjesse if I want continue to use okhttp 2.6.0, how can I avoid this bug. today will release. I haven't time to upgrade to OkHttp 3

**Comment by swankjesse** [comment]
You could delay your release.
