### ISSUE TITLE
i have a question 

### ISSUE THREAD

**Issue by a99194978** [square/okhttp#2408]
String url = http://www.391k.com/api/xapi.ashx/info.json?key=bd_hyrzjjfb4modhj&size=10&page=1

        Log.i("url", url);
        OkHttpClient okHttpClient = new OkHttpClient();
        Request request = new Request.Builder().url(url).build();
        Call call = okHttpClient.newCall(request);
        call.enqueue(new Callback() {
                         @Override
                         public void onFailure(Request request, IOException e) {
                             e.printStackTrace();
                         }

                         @Override
                         public void onResponse(Response response) throws IOException {
                             Log.i("onResponse", response.body().string());
                            
                         }
                     }
        );

03-15 12:57:05.513 20587-20990/com.yiwan.cartoon I/OkHttpClient: Callback failure for call to http://www.391k.com/...
                                                                 java.io.EOFException
                                                                     at okio.RealBufferedSource.require(RealBufferedSource.java:64)
                                                                     at okio.RealBufferedSource.readIntLe(RealBufferedSource.java:237)
                                                                     at okio.GzipSource.consumeTrailer(GzipSource.java:173)
                                                                     at okio.GzipSource.read(GzipSource.java:92)
                                                                     at okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
                                                                     at java.io.InputStreamReader.read(InputStreamReader.java:233)
                                                                     at java.io.BufferedReader.fillBuf(BufferedReader.java:145)
                                                                     at java.io.BufferedReader.readLine(BufferedReader.java:397)
                                                                     at com.yiwan.util.DataHelper$1.onResponse(DataHelper.java:68)
                                                                     at com.squareup.okhttp.Call$AsyncCall.execute(Call.java:177)
                                                                     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     at java.lang.Thread.run(Thread.java:841)

**Comment by a99194978** [comment]
OkHttpClient okHttpClient = new OkHttpClient();
        Request request = new Request.Builder().url(url).build();
        Call call = okHttpClient.newCall(request);
        call.enqueue(new Callback() {
                         @Override
                         public void onFailure(Request request, IOException e) {
                             e.printStackTrace();
                         }

                         @Override
                         public void onResponse(Response response) throws IOException {
                             Log.i("onResponse","onResponse");
                             InputStream is = response.body().byteStream();
                             BufferedReader reader = new BufferedReader(new InputStreamReader(is, "utf-8"), 8);
                             StringBuilder sb = new StringBuilder();
                             String line = null;
                             while ((line = reader.readLine()) != null) {
                                 sb.append(line + "\n");
                             }
                             is.close();
                             reader.close();
                             String json = sb.toString();
                             Log.i("json",json);
                         }
                     }
        );

**Comment by swankjesse** [comment]
That webserver is returning a malformed file. Gunzip on my Mac can’t handle it either.
```
gunzip: foo.gz: unexpected end of file
gunzip: foo.gz: uncompress failed
```

You can workaround with this:
```
    Request request = new Request.Builder()
        .header("Accept-Encoding", "identity")
        .url("http://www.391k.com/api/xapi.ashx/info.json?key=bd_hyrzjjfb4modhj&size=10&page=1")
        .build();
```

But you should really ask the server’s administrators to fix their broken file.

**Comment by rahulrj** [comment]
@swankjesse But how does a broken file throws an Exception? I looked at the code and found out that this line returns `false` and thats why it throws an Exception. But is it because the server returns an empty file or something else? What is a "broken file" here?

**Comment by swankjesse** [comment]
It's a file that claims to be gzipped but isn't.
