### ISSUE TITLE
IllegalArgumentException: in == null

### ISSUE THREAD

**Issue by jonbe242** [square/okhttp#2411]
OkHttp 3.1.2, Okio 1.6.0.

I get this error (see stacktrace below) now and then, causing the Android app to crash (Samsung SM-T810, Android 5.0.2).

Server end is a combination of MS Forefront (HTTPS-termination) and IIS 7.5 if it matters.

It seems like the InputStream from the socket is null for some reason. Maybe bug in device or bug in socket health monitoring (wild guesses)? Can one do a null check in Okio.source or catch IllegalArgumentException in RealConnection.connectSocket?

java.lang.IllegalArgumentException: in == null
	at okio.Okio.source(Okio.java:129)
	at okio.Okio.source(Okio.java:200)
	at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:144)
	at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
	at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
	at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
	at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
	at okhttp3.RealCall.getResponse(RealCall.java:240)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
	at foo.MyInterceptor.intercept(MyInterceptor.java:28)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
	at okhttp3.RealCall.access$100(RealCall.java:30)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

**Comment by swankjesse** [comment]
Are you using a custom SocketFactory or SSLSocketFactory ? This should never happen. Maybe you’re using a third-party API that might be installing its own custom SSLSocketFactory?

**Comment by jonbe242** [comment]
Thanks! 

I did have a factory looking like this:
`public SSLSocketFactory createSslSocketFactory(){
        final TrustManager[] trustManagers = new TrustManager[]{new X509TrustManager() {

            @Override
            public X509Certificate[] getAcceptedIssuers() {
                return new X509Certificate[0];
            }

            @Override
            public void checkServerTrusted(final X509Certificate[] chain,
                                           final String authType) throws CertificateException {
            }

            @Override
            public void checkClientTrusted(final X509Certificate[] chain,
                                           final String authType) throws CertificateException {
            }
        }};

        SSLContext ctx;
        try {
            ctx = SSLContext.getInstance("TLS");
            ctx.init(null, trustManagers, new SecureRandom());
            return ctx.getSocketFactory();
        } catch (final java.security.GeneralSecurityException ex) {
            throw new RuntimeException("Failed to create SSLSocketFactory", ex);
        }
    }
`

It's not needed any more so I have removed it.
I'll close the issue if this resolved the problem.

**Comment by swankjesse** [comment]
Closing. If you can reproduce, please reopen.
