### ISSUE TITLE
OnErrorNotImplementedException when Interceptor throws.

### ISSUE THREAD

**Issue by localhostEU** [square/okhttp#2415]
I get this exception any time there's SocketTimeoutException.
Using Retrofit2, RxJava 1.1.0, OkHttp3.

```
FATAL EXCEPTION: RxCachedThreadScheduler-1
                                                                   Process: com.***, PID: 13298
                                                                   java.lang.IllegalStateException: Exception thrown on Scheduler.Worker thread. Add `onError` handling.
                                                                       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:60)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                       at java.lang.Thread.run(Thread.java:818)
                                                                    Caused by: rx.exceptions.OnErrorNotImplementedException
                                                                       at rx.Observable$27.onError(Observable.java:8139)
                                                                       at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:157)
                                                                       at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:120)
                                                                       at rx.internal.operators.OperatorSubscribeOn$1$1.onError(OperatorSubscribeOn.java:59)
                                                                       at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:151)
                                                                       at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:125)
                                                                       at rx.Observable.unsafeSubscribe(Observable.java:8314)
                                                                       at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
                                                                       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                       at java.lang.Thread.run(Thread.java:818) 
                                                                    Caused by: java.net.SocketTimeoutException
                                                                       at java.net.PlainSocketImpl.read(PlainSocketImpl.java:484)
                                                                       at java.net.PlainSocketImpl.-wrap0(PlainSocketImpl.java)
                                                                       at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:237)
                                                                       at okio.Okio$2.read(Okio.java:139)
                                                                       at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
                                                                       at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
                                                                       at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
                                                                       at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
                                                                       at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
                                                                       at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
                                                                       at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:723)
                                                                       at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:81)
                                                                       at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)
                                                                       at com.***.network.interceptor.HeaderInterceptor.intercept(HeaderInterceptor.java:24)
                                                                       at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:681)
                                                                       at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
                                                                       at okhttp3.RealCall.getResponse(RealCall.java:241)
                                                                       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
                                                                       at com.***.network.interceptor.TokenExpiredInterceptor.intercept(TokenExpiredInterceptor.java:40)
                                                                       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
                                                                       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:203)
                                                                       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
                                                                       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
                                                                       at okhttp3.RealCall.execute(RealCall.java:57)
                                                                       at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
                                                                       at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:144)
                                                                       at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:125) 
                                                                       at rx.Observable.unsafeSubscribe(Observable.java:8314) 
                                                                       at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94) 
                                                                       at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55) 
                                                                       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423) 
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                       at java.lang.Thread.run(Thread.java:818) 
```

**Comment by JakeWharton** [comment]
Add use `Observer` or `Subscriber` or one of the subscribe overloads that takes an `Action1` for `Throwable` to add error handling to your call chain. This isn't an OkHttp issue.

**Comment by localhostEU** [comment]
Inside interceptor? There's no Rx stuff there. Why?
Outside of iterceptors every retrofit call is supplied with onError(throwable).

**Comment by JakeWharton** [comment]
The stack trace indicates otherwise and RxJava corroborates:

<img width="474" alt="screen shot 2016-03-18 at 12 12 17 pm" src="https://cloud.githubusercontent.com/assets/66577/13884086/b7616384-ed02-11e5-8e54-a589fc51b9ca.png">

**Comment by Xuzhiwei** [comment]
how to solve it?

**Comment by localhostEU** [comment]
[RxLint](https://bitbucket.org/littlerobots/rxlint) for the rescue!

**Comment by Xuzhiwei** [comment]
Thank you,I'll try it

**Comment by Xuzhiwei** [comment]
I catched the exception,and resolved the problem:
try {
      response = chain.proceed(request);
    } catch (IOException e) {
      LogUtil.error(TAG,"ERROR",e);
      return null;
    }

**Comment by VsMaX** [comment]
I've had the same problem. Unfortunately catching and returning null as Xuzhiwei proposed did not help me.

**Comment by mshaileshr** [comment]
Always get  carsh android app throwing the exception java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/MediaType

**Comment by MrLuo0312** [comment]
Still get OnErrorNotImplementedException and  SocketTimeoutException and app crashed .  My code:

Disposable httpSubscribe = observable.compose(TransformerHelper.<Response<T>>io_main()).doOnSubscribe(new Consumer<Disposable>() {
            @Override
            public void accept(@io.reactivex.annotations.NonNull Disposable disposable) throws Exception {
                requestCallback.onBefore();
            }
        }).doOnError(new Consumer<Throwable>() {
            @Override
            public void accept(@io.reactivex.annotations.NonNull Throwable throwable) throws Exception {
                requestCallback.onAfter();
                requestCallback.onError(throwable);
            }
        }).doOnComplete(new Action() {
            @Override
            public void run() throws Exception {
                requestCallback.onAfter();
            }
        }).onErrorReturn(new Function<Throwable, Response<T>>() {
            @Override
            public Response<T> apply(@io.reactivex.annotations.NonNull Throwable throwable) throws Exception {
                return null;
            }
        }).subscribe(new Consumer<Response<T>>() {
            @Override
            public void accept(@io.reactivex.annotations.NonNull Response<T> response) throws Exception {
                try {
                    requestCallback.onAfter();
                    if (response.isSuccess()) {
                        requestCallback.onSuccess(response.data, response.msg);
                    } else {
                        requestCallback.onBizErr(response.code, response.msg);
                    }
                } catch (Exception e) {
                    requestCallback.onAfter();
                    requestCallback.onError(e.getCause());
                }
            }
        }, new Consumer<Throwable>() {
            @Override
            public void accept(@io.reactivex.annotations.NonNull Throwable throwable) throws Exception {
                requestCallback.onAfter();
                requestCallback.onError(throwable);
            }
        }

**Comment by MrLuo0312** [comment]
## **Still get OnErrorNotImplementedException and SocketTimeoutException and app crashed . My code:**
```
Disposable httpSubscribe = observable.compose(TransformerHelper.<Response>io_main()).doOnSubscribe(new Consumer() {
@override
public void accept(@io.reactivex.annotations.NonNull Disposable disposable) throws Exception {
requestCallback.onBefore();
}
}).doOnError(new Consumer() {
@override
public void accept(@io.reactivex.annotations.NonNull Throwable throwable) throws Exception {
requestCallback.onAfter();
requestCallback.onError(throwable);
}
}).doOnComplete(new Action() {
@override
public void run() throws Exception {
requestCallback.onAfter();
}
}).onErrorReturn(new Function<Throwable, Response>() {
@override
public Response apply(@io.reactivex.annotations.NonNull Throwable throwable) throws Exception {
return null;
}
}).subscribe(new Consumer<Response>() {
@override
public void accept(@io.reactivex.annotations.NonNull Response response) throws Exception {
try {
requestCallback.onAfter();
if (response.isSuccess()) {
requestCallback.onSuccess(response.data, response.msg);
} else {
requestCallback.onBizErr(response.code, response.msg);
}
} catch (Exception e) {
requestCallback.onAfter();
requestCallback.onError(e.getCause());
}
}
}, new Consumer() {
@override
public void accept(@io.reactivex.annotations.NonNull Throwable throwable) throws Exception {
requestCallback.onAfter();
requestCallback.onError(throwable);
}
}
```
