### ISSUE TITLE
 java.lang.IllegalArgumentException: Pin is not a valid length

### ISSUE THREAD

**Issue by DimaKoz** [square/okhttp#2419]
I got the crash log.
Android 4.4.2(no rooted)
device ACER A3-A20FHD
the version of okhttp is 3.2.0
see stack trace below:

Caused by java.lang.IllegalArgumentException: Pin is not a valid length
       at com.android.org.conscrypt.PinListEntry.validatePin(PinListEntry.java:129)
       at com.android.org.conscrypt.PinListEntry.addPins(PinListEntry.java:121)
       at com.android.org.conscrypt.PinListEntry.<init>(PinListEntry.java:77)
       at com.android.org.conscrypt.CertPinManager.rebuild(CertPinManager.java:91)
       at com.android.org.conscrypt.CertPinManager.<init>(CertPinManager.java:49)
       at com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:137)
       at com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:97)
       at com.android.org.conscrypt.TrustManagerFactoryImpl.engineGetTrustManagers(TrustManagerFactoryImpl.java:80)
       at javax.net.ssl.TrustManagerFactory.getTrustManagers(TrustManagerFactory.java:219)
       at com.android.org.conscrypt.SSLParametersImpl.createDefaultTrustManager(SSLParametersImpl.java:401)
       at com.android.org.conscrypt.SSLParametersImpl.getDefaultTrustManager(SSLParametersImpl.java:392)
       at com.android.org.conscrypt.SSLParametersImpl.<init>(SSLParametersImpl.java:118)
       at com.android.org.conscrypt.SSLContextImpl.engineInit(SSLContextImpl.java:92)
       at javax.net.ssl.SSLContext.init(SSLContext.java:219)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:177)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:151)

**Comment by swankjesse** [comment]
Looks like a bug in the device. No clear action for us to take here unfortunately. Report it to AOSP or Acer?
