### ISSUE TITLE
NoSuchElementException in DiskLruCache

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#2420]
Was able to trigger this under heavy load. The LinkedHashMap was empty, but the maxSize was not zero. Something is unhappy.

```
Exception in thread "OkHttp DiskLruCache" java.util.NoSuchElementException
	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:713)
	at java.util.LinkedHashMap$LinkedValueIterator.next(LinkedHashMap.java:739)
	at okhttp3.internal.DiskLruCache.trimToSize(DiskLruCache.java:676)
	at okhttp3.internal.DiskLruCache.access$200(DiskLruCache.java:84)
	at okhttp3.internal.DiskLruCache$1.run(DiskLruCache.java:174)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by swankjesse** [comment]
Closed by https://github.com/square/okhttp/pull/2421
