### ISSUE TITLE
OkHttp3 not running on Java 9

### ISSUE THREAD

**Issue by cbeust** [square/okhttp#2459]
```
Caused by: java.lang.reflect.InaccessibleObjectException: Unable to make member of class sun.security.ssl.SSLSocketFactoryImpl accessible:  module java.base does not export sun.security.ssl to unnamed module @5c5a1b69
	at sun.reflect.Reflection.throwInaccessibleObjectException(java.base@9-ea/Reflection.java:420)
	at java.lang.reflect.AccessibleObject.checkCanSetAccessible(java.base@9-ea/AccessibleObject.java:174)
	at java.lang.reflect.Field.checkCanSetAccessible(java.base@9-ea/Field.java:170)
	at java.lang.reflect.Field.setAccessible(java.base@9-ea/Field.java:164)
	at okhttp3.internal.Platform.readFieldOrNull(Platform.java:417)
	at okhttp3.internal.Platform.trustManager(Platform.java:91)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:184)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:151)
```

/cc @talios

What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by swankjesse** [comment]
Already fixed on master. Oh neat, that's the new locked down unsafe stuff!

**Comment by cbeust** [comment]
That's great to hear, thanks Jesse!

Do you mean that this specific issue is fixed on master or that `okhttp3` is now running fine on JDK 9?

**Comment by swankjesse** [comment]
The code path that triigers this is avoided in master. You'll only hit it off you customize the SSLSocketFactory, and if you do there's an API to provide your own TrustManager.

Will probably release as 3.3 in 2-4 weeks.

**Comment by cbeust** [comment]
Sounds good. Kobalt is not using okhttp3 directly, only through Retrofit,
so I'm sure Jake will have it updated by then.

Thanks Jesse!


-- 
Cédric
