### ISSUE TITLE
[Bug report]useJack error

### ISSUE THREAD

**Issue by EngrZhou** [square/okhttp#2476]
When i  use Jack using Gradle.
```
 buildToolsRevision '24.0.0-rc2'
    defaultConfig {
      // Enable the experimental Jack build tools.
      useJack = true
    }
```
Okhttp report the error.

```
04-12 14:57:38.242 11092-11152/? E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                   Process: com.packageName, PID: 11092
                                                   java.lang.VerifyError: okhttp3/ResponseBody
                                                       at okhttp3.internal.http.HttpEngine.<clinit>(Unknown)
                                                       at okhttp3.RealCall.getResponse(Unknown)
                                                       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(Unknown)
                                                       at okhttp3.RealCall.getResponseWithInterceptorChain(Unknown)
                                                       at okhttp3.RealCall.access$100(Unknown)
                                                       at okhttp3.RealCall$AsyncCall.execute(Unknown)
                                                       at okhttp3.internal.NamedRunnable.run(Unknown)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:841)
```

**Comment by JakeWharton** [comment]
This is a problem with Jack, not OkHttp. Please report to the Android team at http://b.android.com/.

**Comment by iNoles** [comment]
I had this problem before and found https://code.google.com/p/android/issues/detail?id=82691
