### ISSUE TITLE
NetworkOnMainThread Exception when calling okhttpclient.cancel(tag)

### ISSUE THREAD

**Issue by mohan-mishra** [square/okhttp#2511]
ndroid.os.NetworkOnMainThreadException
                                                             at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1273)
                                                             at com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative(OpenSSLSocketImpl.java:1131)
                                                             at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1126)
                                                             at com.squareup.okhttp.Connection.closeIfOwnedBy(Connection.java:142)
                                                             at com.squareup.okhttp.OkHttpClient$1.closeIfOwnedBy(OkHttpClient.java:71)
                                                             at com.squareup.okhttp.internal.http.HttpConnection.closeIfOwnedBy(HttpConnection.java:136)
                                                             at com.squareup.okhttp.internal.http.HttpTransport.disconnect(HttpTransport.java:135)
                                                             at com.squareup.okhttp.internal.http.HttpEngine.disconnect(HttpEngine.java:507)
                                                             at com.squareup.okhttp.Dispatcher.cancel(Dispatcher.java:128)
                                                             at com.squareup.okhttp.OkHttpClient.cancel(OkHttpClient.java:579)

**Comment by mohan-mishra** [comment]
Using okhttp 3.2.0

**Comment by JakeWharton** [comment]
This is OkHttp 2.x, not 3.2.0.

**Comment by JakeWharton** [comment]
This was fixed in OkHttp 3

**Comment by Larnoo** [comment]
How to cancel a request?
