### ISSUE TITLE
MockWebServer#shutdown fails if client makes more requests than we have enqueued

### ISSUE THREAD

**Issue by caplan** [square/okhttp#2521]
using 2.7.5:

```java
MockWebServer server = new MockWebServer();
server.enqueue(new MockResponse());
server.enqueue(new MockResponse());
// client makes at least 3 requests... 3rd one probably times out
server.shutdown(); // <- this throws an exception
```

Even though this is an error on the part of the calling code (sending more requests than we have responses), it doesn't seem appropriate for `shutdown()` to throw an exception.

Here's the stack trace:

```
java.io.IOException: Gave up waiting for executor to shut down
	at com.squareup.okhttp.mockwebserver.MockWebServer.shutdown(MockWebServer.java:411)
	at com.squareup.okhttp.mockwebserver.MockWebServer$2.evaluate(MockWebServer.java:152)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by JakeWharton** [comment]
So the fix for this is fairly easy it turns out, but it begs the question as to whether we actually want the queue dispatcher to accept new connections without an existing response. It would be much easier to eagerly fail on an empty queue.

@swankjesse ?

**Comment by swankjesse** [comment]
I’m curious to see what the thread dumps are. I think our current behavior is to terminate all service threads on shutdown, which means we don’t need special behavior for QueueDispatcher vs. other ones.

**Comment by swankjesse** [comment]
Oh hang on, we terminate those service threads by breaking their sockets. If the queue dispatcher is empty, then the service thread might be blocked waiting on that. Hmm.

**Comment by swankjesse** [comment]
I suppose we could also put a dead letter into the queue on shutdown.

**Comment by JakeWharton** [comment]
It is blocked on the dispatcher being empty, yes. You'd have to put as many
responses in as are threads waiting.

Calling shutdownNow in shutdown works with the current model, assuming you
make InterruptedException propagate correctly.

**Comment by swankjesse** [comment]
We don’t know how many threads are waiting. But we could put just one dead letter in the queue, then when the recipient of a dead letter receives it that recipient could re-enqueue the dead letter. They’d return in serial, but that’s okay ’cause typically there’s only one.

**Comment by JakeWharton** [comment]
What about custom Dispatcher implementations? Isn't thread interrupting a
more appropriate mechanism for them?

**Comment by swankjesse** [comment]
I don’t like thread interrupting, and it isn’t even likely to work reasonably for other dispatchers. It’s a historical accident that QueueDispatcher can block. I don’t expect other dispatchers to have similar behavior.

**Comment by caplan** [comment]
Thanks!

**Comment by BorislavKamenov** [comment]
So what's the workaround ? It's doesn't work event with QueueDispatcher .
