### ISSUE TITLE
Getting a crash with Facebook sdk 4.5.0

### ISSUE THREAD

**Issue by olx-gaurav-mishra** [square/okhttp#2526]
Not sure about reproduction steps as haven't been able to reproduce. Below are crashlytics log

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=0; index=0
       at com.android.okhttp.internal.Util.rjil_playstore_download_case(Util.java:309)
       at com.android.okhttp.HostResolver$1.getAllByName(HostResolver.java:31)
       at com.android.okhttp.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:232)
       at com.android.okhttp.internal.http.RouteSelector.next(RouteSelector.java:124)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:310)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:249)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:397)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:347)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:515)
       at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
       at com.facebook.GraphResponse.fromHttpConnection(GraphResponse.java:253)
       at com.facebook.GraphRequest.executeConnectionAndWait(GraphRequest.java:1251)
       at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:1153)
       at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:1120)
       at com.facebook.GraphRequest.executeBatchAndWait(GraphRequest.java:1104)
       at com.facebook.GraphRequest.executeAndWait(GraphRequest.java:1079)
       at com.facebook.GraphRequest.executeAndWait(GraphRequest.java:973)
       at com.facebook.internal.Utility.getAppSettingsQueryResponse(Utility.java:871)
       at com.facebook.internal.Utility.access$000(Utility.java:75)
       at com.facebook.internal.Utility$1.run(Utility.java:780)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by swankjesse** [comment]
This is a surprising line in your stack trace.
```
com.android.okhttp.internal.Util.rjil_playstore_download_case(Util.java:309)
```
What device is this on? Which version of Android? The manufacturer has hacked OkHttp to do something weird after a DNS query and that code is crashing.

Nothing we can do unfortunately. Report this to the device maker.

**Comment by ankur-j9** [comment]
Though this issue is occurring mostely on LGE devices(97%) but it is happening on other manufacturer's devices as well. Kindly see the crash logs here: http://crashes.to/s/845f72a220f

**Comment by swankjesse** [comment]
FYI @15characterlimi

**Comment by 15characterlimi** [comment]
@swankjesse thanks for the heads up. As you say, someone has clearly messed with HostResolver. This is the first time I've heard of this; this class name hasn't existed after Android Lollipop so old devices are probably stuck with this bug, but I've flagged this through appropriate channels.

@ankur-j9 I suspect that the 3% attributed to other manufacturers are simply misattributed. Note that the crash you're seeing appears specific to (this manufacturer's version of) Android, not to the Facebook SDK.

**Comment by 15characterlimi** [comment]
PS. I just saw that the crashlytics page also says that this particular stacktrace only affects Android version 5 (Lollipop), which matches my investigation.

**Comment by nickylin** [comment]
how is the result now? is there any sulostion about that? i think maybe we did grant some perssion but we use the api to excute, so the reponse is null, that to occur this problem.
