### ISSUE TITLE
java.lang.VerifyError: Rejecting class com.squareup.okhttp.internal.spdy.SpdyConnection 

### ISSUE THREAD

**Issue by LucyAna** [square/okhttp#2531]
This errors  on a 5.x device.reappear many times.

`java.lang.VerifyError: Rejecting class com.squareup.okhttp.internal.spdy.SpdyConnection because it failed compile-time verification (declaration of 'com.squareup.okhttp.internal.spdy.SpdyConnection' appears in /data/app/cn.kidyn.qdmedical160-1/base.apk)
	at com.squareup.okhttp.internal.spdy.SpdyConnection$Builder.build(Unknown Source)
	at com.squareup.okhttp.Connection.connect(Unknown Source)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Unknown Source)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(Unknown Source)
	at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(Unknown Source)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(Unknown Source)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(Unknown Source)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(Unknown Source)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.connect(Unknown Source)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(Unknown Source)
	at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(Unknown Source)
	at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
	at cn.kidyn.qdmedical160.network.HttpLoader$OkHttpStack.a(Unknown Source)
	at com.android.volley.toolbox.BasicNetwork.a(Unknown Source)
	at com.android.volley.NetworkDispatcher.run(Unknown Source)`

----------------------------

`java.lang.VerifyError: com.squareup.okhttp.internal.spdy.SpdyConnection
	at com.squareup.okhttp.internal.spdy.SpdyConnection$Builder.build(Unknown Source)
	at com.squareup.okhttp.Connection.connect(Unknown Source)
	at com.squareup.okhttp.Connection.connectAndSetOwner(Unknown Source)
	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(Unknown Source)
	at com.squareup.okhttp.internal.http.HttpEngine.nextConnection(Unknown Source)
	at com.squareup.okhttp.internal.http.HttpEngine.connect(Unknown Source)
	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(Unknown Source)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.execute(Unknown Source)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.connect(Unknown Source)
	at com.squareup.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(Unknown Source)
	at com.squareup.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(Unknown Source)
	at com.squareup.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(Unknown Source)
	at cn.kidyn.qdmedical160.network.HttpLoader$OkHttpStack.a(Unknown Source)
	at com.android.volley.toolbox.BasicNetwork.a(Unknown Source)
	at com.android.volley.NetworkDispatcher.run(Unknown Source)`

**Comment by swankjesse** [comment]
I'm guessing this is a problem with the device, not with OkHttp. Could you report this to the device's manufacturer?

**Comment by LucyAna** [comment]
From more to less in order to have these device's.
M57AC
H23
Doov L5pro
Galaxy S5
...

**Comment by LucyAna** [comment]
Do not know what factors will be the emergence of these problems.
who can help me ?

**Comment by swankjesse** [comment]
You should report the issue to YunOS, that's where the bug is.
