### ISSUE TITLE
Strange test flake in URLConnectionTest.testRequestBodySurvivesRetries

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#2541]
Somehow the response parser is seeing a request status line. What’s up with that?

```
closed
Tests run: 229, Failures: 0, Errors: 1, Skipped: 8, Time elapsed: 18.912 sec <<< FAILURE! - in okhttp3.URLConnectionTest
requestBodySurvivesRetriesWithBufferedBody(okhttp3.URLConnectionTest)  Time elapsed: 0.011 sec  <<< ERROR!
java.net.ProtocolException: Unexpected status line: POST http://localhost:48879/def HTTP/1.1
	at okhttp3.internal.http.StatusLine.parse(StatusLine.java:69)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
	at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:726)
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:596)
	at okhttp3.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:481)
	at okhttp3.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:417)
	at okhttp3.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:247)
	at okhttp3.URLConnectionTest.assertContent(URLConnectionTest.java:3476)
	at okhttp3.URLConnectionTest.assertContent(URLConnectionTest.java:3480)
	at okhttp3.URLConnectionTest.testRequestBodySurvivesRetries(URLConnectionTest.java:319)
	at okhttp3.URLConnectionTest.requestBodySurvivesRetriesWithBufferedBody(URLConnectionTest.java:302)
```

This happened on Travis on Java 7.
https://s3.amazonaws.com/archive.travis-ci.org/jobs/128577751/log.txt

**Comment by swankjesse** [comment]
I couldn’t reproduce this.

**Comment by swankjesse** [comment]
I couldn’t reproduce this.

**Comment by devinhu** [comment]
**I have the same problem**

Caused by: java.lang.NullPointerException:Attempt to invoke interface method 'okio.BufferedSink okio.BufferedSink.writeUtf8(java.lang.String)' on a null object reference
1	at okhttp3.internal.http.Http1xStream.writeRequest(Http1xStream.java:167)
2	at okhttp3.internal.http.Http1xStream.writeRequestHeaders(Http1xStream.java:123)
3	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:42)
4	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
5	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
6	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
7	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
8	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
9	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
10	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
11	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
12	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
13	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
14	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
15	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
16	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
17	at okhttp3.RealCall.access$100(RealCall.java:33)
18	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
19	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
20	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
21	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
22	at java.lang.Thread.run(Thread.java:818)
