### ISSUE TITLE
Okhttp version : 2.0.0   ---->  java.lang.RuntimeException: java.io.IOException at com.squareup.okhttp.internal.DiskLruCache

### ISSUE THREAD

**Issue by Revenge94** [square/okhttp#2578]
```
java.lang.RuntimeException: java.io.IOException
	at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:174)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.IOException
	at com.squareup.okhttp.internal.DiskLruCache.renameTo(DiskLruCache.java:390)
	at com.squareup.okhttp.internal.DiskLruCache.rebuildJournal(DiskLruCache.java:372)
	at com.squareup.okhttp.internal.DiskLruCache.access$300(DiskLruCache.java:86)
	at com.squareup.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:170)
	... 3 more
```

**Comment by swankjesse** [comment]
Please only report issues against the current version.

**Comment by guoliuya** [comment]
whether this bug had already deal with in the newest version?
