### ISSUE TITLE
java.lang.ExceptionInInitializerError bug

### ISSUE THREAD

**Issue by tomatozheng** [square/okhttp#2580]
Bug report:
java.lang.ExceptionInInitializerError
	at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:64)
Caused by: java.lang.NullPointerException
	at okhttp3.ConnectionSpec$Builder.cipherSuites(ConnectionSpec.java:278)
	at okhttp3.ConnectionSpec.<clinit>(ConnectionSpec.java:66)
java.lang.NullPointerException
	at okhttp3.ConnectionSpec$Builder.cipherSuites(ConnectionSpec.java:278)
	at okhttp3.ConnectionSpec.<clinit>(ConnectionSpec.java:66)
	at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:64)

**Comment by tomatozheng** [comment]
sometimes when i init OkHttpClient instance,throw those message

**Comment by hysbtr** [comment]
Oh~,My kiddo,Let me see one see!

**Comment by swankjesse** [comment]
Looks like a device or VM initialization problem. Can you tell me more about the impacted devices?

**Comment by suraj9781** [comment]
OS Version: 5.0
 Device: Aqua Power+
RAM Free: 39%
Disk Free: 72.4%
Fatal Exception: java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.ExceptionInInitializerError
       at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:359)
