### ISSUE TITLE
RealCall Exception in WebSocket

### ISSUE THREAD

**Issue by hamberluo** [square/okhttp#2581]
```
Fatal Exception: java.lang.IllegalStateException: Closing the body of Response{protocol=http/1.0, code=408, message=Request Time-out, url=http://xxx.com/socket.io/?EIO=3&sid=fl-BcqOjm6RZSa78BjRF&transport=websocket} didn't close its backing stream. Bad interceptor?
       at okhttp3.RealCall.getResponse(RealCall.java:299)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
       at okhttp3.RealCall.access$100(RealCall.java:30)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by dave-r12** [comment]
Ahh, I believe I found it. I think this would be fixed with #2374.

```java
class WebSocketCallTest {
  @Test public void clientTimeout() {
    server.enqueue(new MockResponse().setResponseCode(408));
    awaitWebSocket();
  }
}
```

**Comment by hamberluo** [comment]
@dave-r12 this happened in 3.3.0-snapshot

**Comment by swankjesse** [comment]
@hamberluo can you try it with 3.3.1 ?

**Comment by hamberluo** [comment]
@swankjesse i have tried 3.3.1 and it looks like fixed.
