### ISSUE TITLE
AssertionError when running Unit Tests on Android with Robolectric

### ISSUE THREAD

**Issue by vanniktech** [square/okhttp#2591]
Started happening with OkHttp 3.3.1 (didn't try 3.3.0 out)

Relevant Stacktrace

> java.lang.AssertionError
	at okhttp3.internal.AndroidPlatform.isCleartextTrafficPermitted(AndroidPlatform.java:143)
	at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:73)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:381)

**Comment by JakeWharton** [comment]
Dupe #2533

**Comment by vanniktech** [comment]
Ups sorry for that

**Comment by JakeWharton** [comment]
You can workaround by setting `@Config(sdk = 23)` on each test

**Comment by vanniktech** [comment]
Yeah I'm reading the issue. Thanks for the quick reply and the workaround
