### ISSUE TITLE
[Bug Report] Interceptor may throw a IllegalStateException: cache is closed

### ISSUE THREAD

**Issue by vedant1811** [square/okhttp#2605]
I am using the following code to add a custom header:

```
    OkHttpClient.Builder builder = getBuilder()
            .addInterceptor(new Interceptor() {
                @Override
                public Response intercept(Chain chain) throws IOException {
                    Request request = chain.request()
                            .newBuilder()
                            .addHeader("Session-Token", accessToken)
                            .build();
                    return chain.proceed(request);
                }
            });
```

But sometimes I get an error:

```
Fatal Exception: java.lang.IllegalStateException: cache is closed
   at okhttp3.internal.DiskLruCache.checkNotClosed(DiskLruCache.java:635)
   at okhttp3.internal.DiskLruCache.edit(DiskLruCache.java:453)
   at okhttp3.internal.DiskLruCache.edit(DiskLruCache.java:447)
   at okhttp3.Cache.put(Cache.java:244)
   at okhttp3.Cache.access$000(Cache.java:135)
   at okhttp3.Cache$1.put(Cache.java:147)
   at okhttp3.internal.http.HttpEngine.maybeCache(HttpEngine.java:389)
   at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:633)
   at okhttp3.RealCall.getResponse(RealCall.java:241)
   at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
   at co.voggle.core.ApiProvider$3.intercept(ApiProvider.java:149)
   at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
   at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
   at okhttp3.RealCall.access$100(RealCall.java:30)
   at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
   at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
   at java.lang.Thread.run(Thread.java:818)
```

The error makes sense but I don't understand how to work around it, as I do not have the required objects in the `intercept(Chain chain)` method to check if the cache is closed or not.

It would be okay to drop the call if the cache is closed.

_I am using OkHttp via Retorofit for my android application_

**Comment by swankjesse** [comment]
Don't close the response cache?

**Comment by vedant1811** [comment]
@swankjesse I am not explicitly closing the cache, its probably getting closed by Retrofit.

I could catch the exception in `chain.proceed(request)` but then I don't know what to return in the `intercept` method. Would returning `null` be fine?

**Comment by JakeWharton** [comment]
Retrofit knows nothing about the cache.

**Comment by swankjesse** [comment]
Maybe put a breakpoint in the Cache.close() code and see who calls that?

**Comment by vedant1811** [comment]
This is the code I use to setup OkHttp and Retrofit:

        OkHttpClient.Builder builder = new OkHttpClient.Builder();
        builder.cache(new Cache(new File(context.getCacheDir(), "ok-http-cache"),
                1024 * 1024 * 5)) // 5 MB cache
                .addInterceptor(new Interceptor() {
                    @Override
                    public Response intercept(Chain chain) throws IOException {
                        Request request = chain.request()
                                .newBuilder()
                                .addHeader("Session-Token", accessToken)
                                .build();
                        return chain.proceed(request);
                    }
                });

        Retrofit retrofit = new Retrofit.Builder()
                .baseUrl(BASE_URL)
                .addConverterFactory(getGsonFactory())
                .client(builder.build())
                .build();

Now, how can I put a breakpoint or handle the exception?

**Comment by PiotrWpl** [comment]
+1, we have the same problem sometimes in our app.

**Comment by vedant1811** [comment]
With great pain, I am using the following **hack**:

                        Request request = chain.request()
                                .newBuilder()
                                .addHeader("Client-Key", CLIENT_KEY)
                                .build();
                        try {
                            return chain.proceed(request);
                        } catch (IllegalStateException ignored) {
                            LogWrapper.e(TAG, "error in client key interceptor", ignored);
                            // return a dummy response (that again has to be appropriately handled in the client)
                            return new Response.Builder()
                                    .protocol(Protocol.HTTP_1_1)
                                    .body(ResponseBody.create(MediaType.parse("text/plain"), "cache is closed"))
                                    .request(request)
                                    .code(CLIENT_INTERNAL_ERROR_CODE) // 599
                                    .build();
                        }
                    }

**Comment by dave-r12** [comment]
@vedant1811 are you certain you aren't closing the cache? Can you reproduce with a simple example or test case?

**Comment by vedant1811** [comment]
Yes I am sure :) This is the only place I use the OkHttp.Cache class (I searched and there was only 1 such import). It could be an issue in retrofit if not here.

I will try to make a simple example or test case to reproduce this.

**Comment by swankjesse** [comment]
Thanks. Looking forward to something that’ll help us figure this out

**Comment by Steven-Yao** [comment]
I have the same issue,how to resolve it

**Comment by Jungle68** [comment]
I have the same issue ,too,so anyone  can resolve that?

**Comment by MariannaVR** [comment]
We are using the following code to add a header:

OkHttpClient httpClient = new OkHttpClient.Builder()
        .addInterceptor(
                new Interceptor() {
                    @Override
                    public Response intercept(Interceptor.Chain chain) throws IOException {
                        Request original = chain.request();
                        Request.Builder builder = original.newBuilder();
                        builder.header("Session-Token", accessToken);
                        Request request = builder
                                .method(original.method(), original.body())
                                .build();
                        try {
                            return chain.proceed(request);
                        } catch (IllegalStateException e) {
                            Log.e(TAG, "error in client key interceptor", e);
                            throw new IOException(e);
                        }
                    }
                })
        .addInterceptor(interceptor)
        .addNetworkInterceptor(REWRITE_CACHE_CONTROL_INTERCEPTOR)
        .cache(cache)
        .build();

In Android M we have this problem. If storage permission in app is disabled and then enable this permission we get an error:

java.lang.IllegalStateException: cache is closed
  at okhttp3.internal.cache.DiskLruCache.checkNotClosed(DiskLruCache.java:646)
  at okhttp3.internal.cache.DiskLruCache.get(DiskLruCache.java:433)
  at okhttp3.Cache.get(Cache.java:194)
  at okhttp3.Cache$1.get(Cache.java:144)
  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:70)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
  at okhttp3.RealCall.access$100(RealCall.java:33)
  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
  at java.lang.Thread.run(Thread.java:818)

**Comment by swankjesse** [comment]
@MariannaVR could you provide an executable test case to demonstrate the problem?

**Comment by swankjesse** [comment]
No obvious action to take on this.

**Comment by yizuochengchi** [comment]
@MariannaVR how to resolve it,please? thanks!
