### ISSUE TITLE
Cannot mock OkHttpClient with Mockito in Robolectric unit tests

### ISSUE THREAD

**Issue by allenchen1154** [square/okhttp#2607]
Updating from OkHttp 3.2.0 to 3.3.1 breaks Robolectric unit tests that attempt to mock `OkHttpClient` with the following error:
```
java.lang.NoClassDefFoundError: Could not initialize class okhttp3.OkHttpClient$$EnhancerByMockitoWithCGLIB$$f3011856
	at sun.reflect.GeneratedSerializationConstructorAccessor20.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:408)
	at org.objenesis.instantiator.sun.SunReflectionFactoryInstantiator.newInstance(SunReflectionFactoryInstantiator.java:45)
	at org.objenesis.ObjenesisBase.newInstance(ObjenesisBase.java:73)
	at org.mockito.internal.creation.instance.ObjenesisInstantiator.newInstance(ObjenesisInstantiator.java:14)
	at org.mockito.internal.creation.cglib.ClassImposterizer.createProxy(ClassImposterizer.java:143)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:58)
	at org.mockito.internal.creation.cglib.ClassImposterizer.imposterise(ClassImposterizer.java:49)
	at org.mockito.internal.creation.cglib.CglibMockMaker.createMock(CglibMockMaker.java:24)
	at org.mockito.internal.util.MockUtil.createMock(MockUtil.java:33)
	at org.mockito.internal.MockitoCore.mock(MockitoCore.java:59)
	at org.mockito.Mockito.mock(Mockito.java:1285)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:33)
	at org.mockito.internal.configuration.MockAnnotationProcessor.process(MockAnnotationProcessor.java:16)
	at org.mockito.internal.configuration.DefaultAnnotationEngine.createMockFor(DefaultAnnotationEngine.java:43)
	at org.mockito.internal.configuration.DefaultAnnotationEngine.process(DefaultAnnotationEngine.java:66)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.processIndependentAnnotations(InjectingAnnotationEngine.java:71)
	at org.mockito.internal.configuration.InjectingAnnotationEngine.process(InjectingAnnotationEngine.java:55)
	at org.mockito.MockitoAnnotations.initMocks(MockitoAnnotations.java:108)
```

**Comment by JakeWharton** [comment]
Dupe of #2533? Set `@Config(sdk = 23)`

**Comment by allenchen1154** [comment]
Looks like this is a dupe of #2533. Closing since that issue has more details.
