### ISSUE TITLE
3.3.1 java.lang.IllegalStateException: must call close()

### ISSUE THREAD

**Issue by hamberluo** [square/okhttp#2630]
```
Fatal Exception: java.lang.IllegalStateException: must call close()
       at okhttp3.internal.ws.RealWebSocket.sendMessage(RealWebSocket.java:108)
       at io.socket.engineio.client.transports.WebSocket$3.call(WebSocket.java:173)
       at io.socket.engineio.parser.Parser.encodePacket(Parser.java:63)
       at io.socket.engineio.parser.Parser.encodePacket(Parser.java:42)
       at io.socket.engineio.client.transports.WebSocket.write(WebSocket.java:168)
       at io.socket.engineio.client.Transport$3.run(Transport.java:101)
       at io.socket.thread.EventThread.exec(EventThread.java:50)
       at io.socket.engineio.client.Transport.send(Transport.java:96)
       at io.socket.engineio.client.Socket.flush(Socket.java:608)
       at io.socket.engineio.client.Socket.onDrain(Socket.java:599)
       at io.socket.engineio.client.Socket.access$1000(Socket.java:30)
       at io.socket.engineio.client.Socket$6.call(Socket.java:294)
       at io.socket.emitter.Emitter.emit(Emitter.java:117)
       at io.socket.engineio.client.transports.WebSocket$2$1.run(WebSocket.java:160)
       at io.socket.thread.EventThread$2.run(EventThread.java:75)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by JakeWharton** [comment]
What makes you think this is an OkHttp bug and not a socket.io bug? Looks
like they're simply not fulfilling the method contract.

**Comment by hamberluo** [comment]
Maybe a socket.io bug. Just remind you if there is an optimization in case.

**Comment by swankjesse** [comment]
No action for us to take on this.
