### ISSUE TITLE
Handshake's localPrincipal causes NPE.

### ISSUE THREAD

**Issue by brannpark** [square/okhttp#2634]
Hello! I got a strange crash report from Crashlytics today.

```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke interface method 'boolean java.util.List.isEmpty()' on a null object reference
       at okhttp3.Handshake.localPrincipal(Handshake.java:114)
       at android.support.v4.view.ViewPager.populate(ViewPager.java)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1025)
       at android.support.v4.view.ViewPager.onMeasure(ViewPager.java:1545)
       at android.view.View.measure(View.java:18646)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
       at android.view.View.measure(View.java:18646)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5832)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
       at <my-package>.onMeasure(<my-view>.java:937)
       at android.view.View.measure(View.java:18646)
       at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:728)
       at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:464)
       at android.view.View.measure(View.java:18646)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5832)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
       at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:135)
       at android.view.View.measure(View.java:18646)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5832)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
       at android.view.View.measure(View.java:18646)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5832)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
       at android.view.View.measure(View.java:18646)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5832)
       at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1435)
       at android.widget.LinearLayout.measureVertical(LinearLayout.java:721)
       at android.widget.LinearLayout.onMeasure(LinearLayout.java:612)
       at android.view.View.measure(View.java:18646)
       at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:5832)
       at android.widget.FrameLayout.onMeasure(FrameLayout.java:430)
       at com.android.internal.policy.impl.PhoneWindow$DecorView.onMeasure(PhoneWindow.java:3011)
       at android.view.View.measure(View.java:18646)
       at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2310)
       at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1354)
       at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1597)
       at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1239)
       at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6752)
       at android.view.Choreographer$CallbackRecord.run(Choreographer.java:777)
       at android.view.Choreographer.doCallbacks(Choreographer.java:590)
       at android.view.Choreographer.doFrame(Choreographer.java:560)
       at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:763)
       at android.os.Handler.handleCallback(Handler.java:739)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:6145)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
```

```
OkHttp https://***.com/***.apsx
       at com.android.org.conscrypt.NativeCrypto.SSL_read(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:728)
       at okio.Okio$2.read(Okio.java:139)
       at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
       at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
       at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
       at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
       at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
       at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
       at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:723)
       at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:81)
       at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)
       at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
       at okhttp3.RealCall.getResponse(RealCall.java:241)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:142)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
       at okhttp3.RealCall.access$100(RealCall.java:30)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

I'm wondering what causes this problem. 
I'm using Retrofit2(v2.0.2) with okhttp(v3.2.0) and the device is sm_a700l and OS version is 5.0.2.

**Comment by swankjesse** [comment]
We do something special with handshakes when reading from old versions of the response cache. I wonder if this is what's going on here.

**Comment by swankjesse** [comment]
Seems like this stacktrace is impossible. Let me know if this is more common than a single crash.

**Comment by brannpark** [comment]
I haven't received any report like this after that day. This issue doesn't seem to be the problem of the library, but It needs exception handling for NPE. Thanks!

**Comment by swankjesse** [comment]
Lemme know if you ever figure out a way to reproduce this.
