### ISSUE TITLE
Can I make Android source code which contains Okhttp2.7.5 in java6?

### ISSUE THREAD

**Issue by LumiaHuan** [square/okhttp#2674]
After I kicked 'make xxx' command, I got java.io.IOException

**Proguard: out/target/common/obj/APPS/xxx_intermediates/proguard.classes.jar
ProGuard, version 4.4
Reading input...
Reading program jar [xxx/out/target/common/obj/APPS/xxx_intermediates/classes.jar]
java.io.IOException: Can't read [proguard.ClassPathEntry@37e893df] Can't process class [com/squareup/okhttp/ResponseBody.class] Unsupported version number [51.0] for class format
	at proguard.InputReader.readInput(InputReader.java:230)
	at proguard.InputReader.readInput(InputReader.java:200)
	at proguard.InputReader.readInput(InputReader.java:178)
	at proguard.InputReader.execute(InputReader.java:78)
	at proguard.ProGuard.readInput(ProGuard.java:195)
	at proguard.ProGuard.execute(ProGuard.java:78)
	at proguard.ProGuard.main(ProGuard.java:499)**

**Comment by swankjesse** [comment]
We build with Java 7 only. This doesn’t generally harm our ability to run on Android.

**Comment by LumiaHuan** [comment]
Yeah~~ I skip proguard in my Android.mk. And that's run.
