### ISSUE TITLE
 java.lang.NoSuchMethodError: okhttp3.internal.Platform.log

### ISSUE THREAD

**Issue by hacket** [square/okhttp#2678]
The DEFAULT Logger in HttpLoggingInterceptor is using Platform.get().log(String) method. That method doesn't exist in OkHttp 3.2?

my build.gradle
```groovy
compile 'com.squareup.okhttp3:okhttp:3.2.0'
compile 'com.squareup.okhttp3:logging-interceptor:3.2.0'
```

logging-interceptor3.2 `HttpLoggingInterceptor`
```java
  public interface Logger {
    void log(String message);

    /** A {@link Logger} defaults output appropriate for the current platform. */
    Logger DEFAULT = new Logger() {
      @Override public void log(String message) {
        Platform.get().log(message);
      }
    };
  }
```

but in okhttp3.2 , `Platform.get().log(String)` method doesn't exist.

crash:
```
java.lang.NoSuchMethodError: okhttp3.internal.Platform.log
	at okhttp3.logging.HttpLoggingInterceptor$Logger$1.log(HttpLoggingInterceptor.java:109)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:157)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at okhttp3.RealCall.access$100(RealCall.java:30)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
```

**Comment by artem-zinnatullin** [comment]
I guess some of your project dependencies require OkHttp 3.3.+ where
Platform.log() was changed and overrides version 3.2.0 of OkHttp specified
by you.

Can you please print tree of project dependencies and check what version of
OkHttp and what version of logging interceptor compiles to your project?
With Gradle it'll be `:moduleName:dependencies`

TL TR: You need to use same version of OkHttp and logging interceptor.
