### ISSUE TITLE
E/StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.

### ISSUE THREAD

**Issue by anurag-singh-exzeo** [square/okhttp#2680]
**Condition**: Application running in offline mode and trying to load an image from a url

**Setup**: 
- compile 'com.squareup.retrofit2:retrofit:2.0.2'
  compile 'com.squareup.retrofit2:converter-gson:2.0.2'
  compile 'com.squareup.okhttp3:okhttp:3.3.1'
  compile 'com.squareup.okhttp3:logging-interceptor:3.3.1'
  compile 'com.squareup.picasso:picasso:2.5.2'

- SomeClass extends extends Application {
@Override public void onCreate() {
StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder() //
          .detectAll() //
          .penaltyLog() //
          .penaltyDeath() //
          .build());
StrictMode.setVmPolicy(
          new StrictMode.VmPolicy.Builder().detectAll().penaltyLog().penaltyDeath().build());
}
}

**Result**:
- Application shuts down with the following stack trace 
java.lang.Throwable: Explicit termination method 'close' not called
at dalvik.system.CloseGuard.open(CloseGuard.java:184)
at java.io.FileInputStream.<init>(FileInputStream.java:78)
at com.android.okhttp.internal.DiskLruCache.get(DiskLruCache.java:417)
at com.android.okhttp.HttpResponseCache.get(HttpResponseCache.java:164)
at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:190)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:382)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:332)
at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:500)
at com.squareup.picasso.UrlConnectionDownloader.load(UrlConnectionDownloader.java:93)
at com.squareup.picasso.NetworkRequestHandler.load(NetworkRequestHandler.java:47)
at com.squareup.picasso.BitmapHunter.hunt(BitmapHunter.java:206)
at com.squareup.picasso.BitmapHunter.run(BitmapHunter.java:159)
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
at com.squareup.picasso.Utils$PicassoThread.run(Utils.java:411)
W/System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.

**Comment by anurag-singh-exzeo** [comment]
Not the correct user. Sorry.
