### ISSUE TITLE
Flaky test

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#2687]
Fails intermittently when run on its own, either in Intellij or from the command line

```
$ mvn test -DfailIfNoTests=false -Dtest=okhttp3.internal.framed.Http2ConnectionTest#peerHttp2ServerLowersInitialWindowSize

Running okhttp3.internal.framed.Http2ConnectionTest
Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.078 sec <<< FAILURE! - in okhttp3.internal.framed.Http2ConnectionTest
peerHttp2ServerLowersInitialWindowSize(okhttp3.internal.framed.Http2ConnectionTest)  Time elapsed: 0.073 sec  <<< FAILURE!
java.lang.AssertionError: expected:<65535> but was:<1684>
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at okhttp3.internal.framed.Http2ConnectionTest.peerHttp2ServerLowersInitialWindowSize(Http2ConnectionTest.java:123)
```

peer.play() is asynchronous, so the value of connection.peerSettings.getInitialWindowSize(-1) is unpredictable

In JDK9 it fails a lot more frequently, but still not always.  I'll look into fixing in a final JDK9 PR for getting the unit tests running successfully.

**Comment by yschimke** [comment]
fixed in https://github.com/square/okhttp/pull/2688 by removing the check
