### ISSUE TITLE
Verify error

### ISSUE THREAD

**Issue by ty44795016** [square/okhttp#2704]
java.lang.VerifyError
Lokhttp3/HttpUrl$Builder;

find verifyerror on Android devices(e.m. android 4.4.4)

**Comment by artem-zinnatullin** [comment]
Can you please post full stacktrace and version of OkHttp that you use?

It might be [Instant Run problem](https://code.google.com/p/android/issues/detail?id=202347) btw.

**Comment by ty44795016** [comment]
I used okhttp-3.3.1jar okio-1.8.0.jar.
Find this problem on some devices,but I can't occurs.
logcat info below:
07-07 10:07:14.280 29891 29945 W TVM : VFY: storing non-ref v0 into ref field 'scheme' (Ljava/lang/String;)
07-07 10:07:14.280 29891 29945 W TVM : VFY: rejecting opcode 0x5b at 0x0081
07-07 10:07:14.280 29891 29945 W TVM : VFY: rejected Lokhttp3/HttpUrl$Builder;.parse (Lokhttp3/HttpUrl;Ljava/lang/String;)Lokhttp3/HttpUrl$Builder$ParseResult;
07-07 10:07:14.280 29891 29945 W TVM : Verifier rejected class Lokhttp3/HttpUrl$Builder;
07-07 10:07:14.283 29891 29945 W TVM : try to handle uncaught exception in bootstrap frame.
07-07 10:07:14.283 29891 29945 E TVM : 0x44618ad8 0x44cf2540 0x446143f0 0x5d03c694
07-07 10:07:14.283 29891 29945 E TVM : uncaughtException Ljava/lang/ThreadGroup;

**Comment by swankjesse** [comment]
Can you identify which device this occurs on? It looks like that device has a broken verifier.

**Comment by ty44795016** [comment]
Devices info:
H1(HOONRUN) Android 5.1.0,level 19
LD700(LD) Android 4.4.4,level 19
WP-S2(wellphone) Android 4.4.2,level 19
m1(Meizu) Android 4.4.4,level 19

**Comment by swankjesse** [comment]
Yikes. Not sure what to do here.

**Comment by swankjesse** [comment]
My suspicion is that this is an issue with those devices and not with OkHttp. If you can come up with a simple way to prevent the verify error, please send a pull request. But also please report the issue to those manufacturers.

No other action for us to take here.

**Comment by FordLiu** [comment]
java.lang.ArrayIndexOutOfBoundsException: length=0; index=1153466866
	at java.util.HashMap.get(HashMap.java:307)
	at android.content.Context$1.isNetworkDenied(Context.java:3230)
	at java.net.Socket.connect(Socket.java:867)
	at okhttp3.internal.a.a(AndroidPlatform.java:55)
	at okhttp3.internal.a.c.c(RealConnection.java:185)
	at okhttp3.internal.a.c.b(RealConnection.java:170)
	at okhttp3.internal.a.c.a(RealConnection.java:111)
	at okhttp3.internal.http.u.a(StreamAllocation.java:187)
	at okhttp3.internal.http.u.b(StreamAllocation.java:123)
	at okhttp3.internal.http.u.a(StreamAllocation.java:93)
	at okhttp3.internal.http.j.k(HttpEngine.java:296)
	at okhttp3.internal.http.j.a(HttpEngine.java:248)
	at okhttp3.ag.a(RealCall.java:243)
	at okhttp3.ag$a.a(RealCall.java:201)
	at okhttp3.ag.a(RealCall.java:163)
	at okhttp3.ag.a(RealCall.java:30)
	at okhttp3.ag$b.b(RealCall.java:127)
	at okhttp3.internal.i.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:848)
