### ISSUE TITLE
java.net.SocketTimeoutException: timeout raised with 3G network (v3.4.1)

### ISSUE THREAD

**Issue by ElodieMfp** [square/okhttp#2724]
I am using okHttp (v3.4.1) in a native Android app to assess the downloading speed of audio files stored on a remote server with the HTTP/2 protocol.

It is working fine for a few files (5), or a very good network. But when I am using a 3G network, and try to download 10 files at a time, I keep having this "java.net.SocketTimeoutException: timeout" exception after the 6th or 7th file. I succeeded once to get until file number 9, but no way to execute my other requests, while it is working fine on the same network for 5 files.

Here is my code (callback after a button click), URL is an ArrayList of urls (https://...) and the stack trace I keep getting with 10 urls

`

    @Override
    public void onClick(View v) {

        OkHttpClient client = new OkHttpClient();
        endTime = 0;
        startTime = System.currentTimeMillis();
        for (String url:URLS)
        {
            final Request request = new Request.Builder().url(url).build();
            client.newCall(request).enqueue(new Callback() {

                @Override
                public void onFailure(Call call, IOException e) {
                    e.printStackTrace();
                }

                @Override
                public void onResponse(Call call, final Response response) throws IOException {
                    if(!response.isSuccessful()) {
                        throw new IOException("Unexpected code " + response);
                    } else {
                        endTime = System.currentTimeMillis();
                        long duration = endTime - startTime;
                        NumberFormat numberFormat = NumberFormat.getInstance(Locale.US);
                        Log.i("END TIME",numberFormat.format(duration));
                    }
                }
            });
        }
    }`

`java.net.SocketTimeoutException: timeout
    at okhttp3.internal.framed.FramedStream$StreamTimeout.newTimeoutException(FramedStream.java:600)
     at okhttp3.internal.framed.FramedStream$StreamTimeout.exitAndThrowIfTimedOut(FramedStream.java:608)
     at okhttp3.internal.framed.FramedStream.getResponseHeaders(FramedStream.java:142)
     at okhttp3.internal.http.Http2xStream.readResponseHeaders(Http2xStream.java:145)
     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:53)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
    at okhttp3.RealCall.access$100(RealCall.java:33)
     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
     at java.lang.Thread.run(Thread.java:818)`

Thanks for your answers, I saw some previous posts about those kinds of timeout Exceptions, but I didn't find what I need

**Comment by anirudhramanan** [comment]
Try increasing the readTimeout on the okhttpclient object using builder.

**Comment by swankjesse** [comment]
No action to take on this.
