### ISSUE TITLE
Bug with version 3.3.1

### ISSUE THREAD

**Issue by virengujariya** [square/okhttp#2728]
```Fatal Exception: java.lang.NullPointerException: application interceptor me.latergram.latergramme.network.services.c@42661bd0 returned null
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:193)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
       at okhttp3.RealCall.access$100(RealCall.java:30)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)```

**Comment by JakeWharton** [comment]
This is a bug in your interceptor, not OkHttp. You cannot return null from
an interceptor.
