### ISSUE TITLE
okhttp 3.1.2 throws unknownhost exception when using socks proxy with azure sdk (beta1)

### ISSUE THREAD

**Issue by nihalnaik25** [square/okhttp#2748]
okhttp 3.1.2 throws unknownhost exception when using socks proxy with azure sdk (beta1)
Other jars used : retrofit-2.0.0-beta4.jar

Note : 
The machine on which the code gets executed does not have internet. But hosts file has IP Address mapping
This issue is not seen for HTTP proxy

Code snippet:

OkHttpClient.Builder clientBuilder = new OkHttpClient.Builder();
            clientBuilder.connectTimeout(CONNECT_TIMEOUT, TimeUnit.SECONDS);
            clientBuilder.writeTimeout(WRITE_TIMEOUT, TimeUnit.SECONDS);
            clientBuilder.readTimeout(READ_TIMEOUT, TimeUnit.SECONDS);
            logger.debug(methodName, "ProxyType :" + proxy.getproxyType());
            clientBuilder.proxy(new Proxy(proxy.getproxyType(), InetSocketAddress.createUnresolved(proxy.getproxyHost(),
                    proxy.getproxyPort())));

            // Set Proxy Credentials
            Authenticator proxyAuthenticator = new Authenticator() {
                @Override
                public okhttp3.Request authenticate(okhttp3.Route route, okhttp3.Response response) throws IOException {
                    String credential = Credentials.basic(proxy.getuserName(), proxy.getpassword());
                    return response.request().newBuilder().header("Proxy-Authorization", credential).build();
                }
            };
            clientBuilder.proxyAuthenticator(proxyAuthenticator);

            Retrofit.Builder retroBuilder = new Retrofit.Builder();
            retroBuilder.client(clientBuilder.build());

            tmpArmClient = new ResourceManagementClientImpl(account.getbaseURL(), appTokenCreds, clientBuilder, retroBuilder);

exception
java.net.UnknownHostException: management.azure.com:443
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:466)
	at java.net.Socket.connect(Socket.java:589)
	at okhttp3.internal.Platform.connectSocket(Platform.java:126)
	at okhttp3.internal.io.RealConnection.connectSocket(RealConnection.java:140)
	at okhttp3.internal.io.RealConnection.connect(RealConnection.java:111)
	at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:188)
	at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
	at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
	at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
	at okhttp3.RealCall.getResponse(RealCall.java:240)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
	at com.microsoft.rest.UserAgentInterceptor.intercept(UserAgentInterceptor.java:58)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
	at com.microsoft.rest.retry.RetryHandler.intercept(RetryHandler.java:69)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
	at com.microsoft.rest.credentials.TokenCredentialsInterceptor.sendRequestWithAuthorization(TokenCredentialsInterceptor.java:49)
	at com.microsoft.rest.credentials.TokenCredentialsInterceptor.intercept(TokenCredentialsInterceptor.java:37)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
	at com.microsoft.azure.CustomHeaderInterceptor.intercept(CustomHeaderInterceptor.java:133)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:177)
	at com.microsoft.azure.management.resources.ProvidersOperationsImpl.list(ProvidersOperationsImpl.java:240)

**Comment by swankjesse** [comment]
Is it somehow thinking `management.azure.com:443` is the hostname, instead of ` management.azure.com` ?

**Comment by swankjesse** [comment]
Does it work when you configure a regular `java.net.Socket` with a SOCKS proxy?
