### ISSUE TITLE
okhttp 3.4.1, Android 4.2.2 HttpUrl.java canonicalize crash

### ISSUE THREAD

**Issue by gaurav-chandra** [square/okhttp#2749]
On Android 4.2 okhttp 3.4.1, as soon as I hit a button to start with the post request to the server, I get this error:

```
java.lang.IllegalStateException: Could not execute method for android:onClick

```

and it leads to this line:

```
okhttp3.HttpUrl.canonicalize
```

The logcat shows the following dump:

```
07-25 15:21:07.257 17202-17202/mobi.gaurav.telx E/AndroidRuntime: FATAL EXCEPTION: main
                                                                  java.lang.IllegalStateException: Could not execute method for android:onClick
                                                                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:293)
                                                                      at android.view.View.performClick(View.java:4212)
                                                                      at android.view.View$PerformClick.run(View.java:17476)
                                                                      at android.os.Handler.handleCallback(Handler.java:800)
                                                                      at android.os.Handler.dispatchMessage(Handler.java:100)
                                                                      at android.os.Looper.loop(Looper.java:194)
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5371)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:525)
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
                                                                      at dalvik.system.NativeStart.main(Native Method)
                                                                   Caused by: java.lang.reflect.InvocationTargetException
                                                                      at java.lang.reflect.Method.invokeNative(Native Method)
                                                                      at java.lang.reflect.Method.invoke(Method.java:525)
                                                                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288)
                                                                      at android.view.View.performClick(View.java:4212) 
                                                                      at android.view.View$PerformClick.run(View.java:17476) 
                                                                      at android.os.Handler.handleCallback(Handler.java:800) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:100) 
                                                                      at android.os.Looper.loop(Looper.java:194) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5371) 
                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600) 
                                                                      at dalvik.system.NativeStart.main(Native Method) 
                                                                   Caused by: java.lang.NullPointerException
                                                                      at okhttp3.HttpUrl.canonicalize(HttpUrl.java:1612)
                                                                      at okhttp3.FormBody$Builder.add(FormBody.java:110)
                                                                      at mobi.gaurav.telx.HTTP.post(HTTP.java:82)
                                                                      at mobi.gaurav.telx.MainActivity.startConnecting(MainActivity.java:358)
                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                      at android.support.v7.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:288) 
                                                                      at android.view.View.performClick(View.java:4212) 
                                                                      at android.view.View$PerformClick.run(View.java:17476) 
                                                                      at android.os.Handler.handleCallback(Handler.java:800) 
                                                                      at android.os.Handler.dispatchMessage(Handler.java:100) 
                                                                      at android.os.Looper.loop(Looper.java:194) 
                                                                      at android.app.ActivityThread.main(ActivityThread.java:5371) 
                                                                      at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                      at java.lang.reflect.Method.invoke(Method.java:525) 
                                                                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833) 
                                                                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600) 
                                                                      at dalvik.system.NativeStart.main(Native Method) 
```

The strange thing is it works perfectly with Android 4.4+ but fails on Android 4.2. 

I am using the example from the website itself. Nothing fancy.

**Comment by gaurav-chandra** [comment]
So, I found out that if I remove https and use http, it works perfectly. So, this means that the server certificate might not be accepted by Android 4.2. Is there a solution to this?

**Comment by swankjesse** [comment]
Are you passing null to something that isn’t expecting it? Perhaps on line 82 of `HTTP.java` ?

**Comment by gaurav-chandra** [comment]
@swankjesse no, I am not passing null. It is because of server SSL certificate. I have letsencrypt ssl on the server and Android 4.2 does not recognize it.

As soon as I removed https and switched to http, it works smoothly. I think I need to bundle the .cer file with my app for it to work over https.

**Comment by swankjesse** [comment]
Could you provide an executable test case please?
