### ISSUE TITLE
okhttp 3.2.0, android4.0.3  libcore.io.ErrnoException: getsockname failed: EBADF (Bad file number)

### ISSUE THREAD

**Issue by Little-of-Water** [square/okhttp#2754]
libcore.io.ErrnoException: getsockname failed: EBADF (Bad file number)
	at libcore.io.Posix.getsockname(Posix.java)
	at libcore.io.ForwardingOs.getsockname(ForwardingOs.java:65)
	at libcore.io.IoBridge.getSocketLocalAddress(IoBridge.java:629)
	at libcore.io.IoBridge.recvfrom(IoBridge.java:533)
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
	at okio.Okio$2.read(Okio.java:139)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:184)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:125)
	at okhttp3.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:723)
	at okhttp3.internal.http.HttpEngine.access$200(HttpEngine.java:81)
	at okhttp3.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:708)
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:563)
	at okhttp3.RealCall.getResponse(RealCall.java:241)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
	at okhttp3.RealCall.execute(RealCall.java:57)

**Comment by swankjesse** [comment]
This stacktrace is incomplete. Please include the full stacktrace. It suspect it’ll have a `SocketTimeoutException` somewhere.

**Comment by Little-of-Water** [comment]
Thank you for your reply：

I package OKHTTP multiple dowloading requests (less 3), which request this error uncertain
Code segment:
        Request request = new Request.Builder()
                .cacheControl(new CacheControl.Builder().build())
                .url(targetUrl)
                .header("Connection","close") // to resolve the issue "unexpected end of stream on okhttp3.Address"
                .get()
                .build();
        OkHttpClient client = OkHttpUtils.getInstance().getShortOkHttpClient();
        call = client.newCall(request);
The last line of code errors。

**Comment by Little-of-Water** [comment]
@swankjesse 
Now I upgraded to the latest version

**Comment by swankjesse** [comment]
No action to take here.
