### ISSUE TITLE
systemDefaultTrustManager Out of Memory error

### ISSUE THREAD

**Issue by NodensN** [square/okhttp#2768]
What kind of issue is this?

 - [ ] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [X] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

This is a Crashlytics report and it's only on android 4.4.x 

```
OkHttpClient.java line 253
okhttp3.OkHttpClient.systemDefaultTrustManager
```

```java
Fatal Exception: java.lang.OutOfMemoryError: (Heap Size=65536KB, Allocated=61117KB)
       at java.lang.String.<init>(String.java:255)
       at libcore.io.IoUtils$FileReader.toString(IoUtils.java:272)
       at libcore.io.IoUtils.readFileAsString(IoUtils.java:114)
       at com.android.org.conscrypt.CertPinManager.readPinFile(CertPinManager.java:111)
       at com.android.org.conscrypt.CertPinManager.rebuild(CertPinManager.java:85)
       at com.android.org.conscrypt.CertPinManager.<init>(CertPinManager.java:49)
       at com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:137)
       at com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:97)
       at com.android.org.conscrypt.TrustManagerFactoryImpl.engineGetTrustManagers(TrustManagerFactoryImpl.java:80)
       at javax.net.ssl.TrustManagerFactory.getTrustManagers(TrustManagerFactory.java:219)
       at okhttp3.OkHttpClient.systemDefaultTrustManager(OkHttpClient.java:253)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:228)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:117)
       at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:830)
       at com.my.package.common.provider.GoApiProvider.initAdapter(GoApiProvider.java:32)
       at com.my.package.common.provider.GoApiProvider.<init>(GoApiProvider.java:20)
       at com.my.package.common.service.impl.UrlService.<init>(UrlService.java:24)
       at com.my.package.component.publication.fragment.PublicationFragment.loadLinkPreview(PublicationFragment.java:617)
       at com.my.package.component.publication.fragment.PublicationFragment.onResume(PublicationFragment.java:651)
       at android.support.v4.app.Fragment.performResume(Fragment.java:2120)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1147)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1286)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1268)
       at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2153)
       at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
       at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:522)
       at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:511)
       at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:178)
       at android.app.Activity.performResume(Activity.java:5418)
       at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3156)
       at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3211)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2500)
       at android.app.ActivityThread.access$800(ActivityThread.java:153)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:157)
       at android.app.ActivityThread.main(ActivityThread.java:5633)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:896)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)
       at dalvik.system.NativeStart.main(NativeStart.java)
```

Any ideas? 

GoApiProvider: 
```java
public class GoApiProvider<T> {

    private Retrofit retrofit;
    private final Environment mEnvironment = Environment.getInstance();
    private final String END_POINT = mEnvironment.getBaseURL();
    private final HttpLoggingInterceptor.Level LOG_LEVEL = mEnvironment.getLogLevel(); // NONE in production

    public GoApiProvider() {
        initAdapter();
    }

    public T getService(Class<T> service) {
        return retrofit.create(service);
    }

    private void initAdapter() {
        HttpLoggingInterceptor interceptor = new HttpLoggingInterceptor();
        interceptor.setLevel(LOG_LEVEL);
        OkHttpClient client = new OkHttpClient.Builder()
                .addInterceptor(interceptor)
                .build();

        retrofit = new Retrofit.Builder()
                .baseUrl(END_POINT)
                .addConverterFactory(new ToStringConverterFactory())
                .client(client)
                .build();
    }
    
}
```

Gradle:
```
compile 'com.squareup.retrofit2:retrofit:2.1.0'
compile 'com.squareup.okhttp3:logging-interceptor:3.4.1'
```
Thanks a lot

**Comment by swankjesse** [comment]
Seems to be a problem with the device’s TLS stack, and not OkHttp in particular. I found similar stacktraces on other projects.
https://github.com/kontalk/androidclient/issues/703

Next steps – please report this to AOSP. They own the TLS code and should be able to fix.

**Comment by rohantilekar** [comment]
I got the same error. Did you guys get any solution?

Fatal Exception: java.lang.OutOfMemoryError
       at java.lang.String.<init>(String.java:255)
       at libcore.io.IoUtils$FileReader.toString(IoUtils.java:272)
       at libcore.io.IoUtils.readFileAsString(IoUtils.java:114)
       at com.android.org.conscrypt.CertPinManager.readPinFile(CertPinManager.java:111)
       at com.android.org.conscrypt.CertPinManager.rebuild(CertPinManager.java:85)
       at com.android.org.conscrypt.CertPinManager.<init>(CertPinManager.java:49)
       at com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:137)
       at com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:97)
       at com.android.org.conscrypt.TrustManagerFactoryImpl.engineGetTrustManagers(TrustManagerFactoryImpl.java:80)
       at javax.net.ssl.TrustManagerFactory.getTrustManagers(TrustManagerFactory.java:219)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.handleHandshakeStatus(AsyncSSLSocketWrapper.java:290)
       at com.koushikdutta.async.AsyncSSLSocketWrapper.access$000(AsyncSSLSocketWrapper.java:30)
       at com.koushikdutta.async.AsyncSSLSocketWrapper$5.onDataAvailable(AsyncSSLSocketWrapper.java:213)
       at com.koushikdutta.async.Util.emitAllData(Util.java:23)
       at com.koushikdutta.async.AsyncNetworkSocket.onReadable(AsyncNetworkSocket.java:152)
       at com.koushikdutta.async.AsyncServer.runLoop(AsyncServer.java:789)
       at com.koushikdutta.async.AsyncServer.run(AsyncServer.java:627)
       at com.koushikdutta.async.AsyncServer.access$700(AsyncServer.java:41)
       at com.koushikdutta.async.AsyncServer$13.run(AsyncServer.java:569)

**Comment by swankjesse** [comment]
@rohantilekar please report to AOSP. Nothing OkHttp can do about problems in `com.koushikdutta.async` code!

**Comment by rahmatrasyidi** [comment]
I got this error. Could you give me some hint why I got OOM
`Fatal Exception: java.lang.OutOfMemoryError
       at java.lang.String.<init>(String.java:255)
       at libcore.io.IoUtils$FileReader.toString(IoUtils.java:272)
       at libcore.io.IoUtils.readFileAsString(IoUtils.java:114)
       at com.android.org.conscrypt.CertPinManager.readPinFile(CertPinManager.java:111)
       at com.android.org.conscrypt.CertPinManager.rebuild(CertPinManager.java:85)
       at com.android.org.conscrypt.CertPinManager.<init>(CertPinManager.java:49)
       at com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:142)
       at com.android.org.conscrypt.TrustManagerImpl.<init>(TrustManagerImpl.java:102)
       at com.android.org.conscrypt.TrustManagerFactoryImpl.engineGetTrustManagers(TrustManagerFactoryImpl.java:80)
       at javax.net.ssl.TrustManagerFactory.getTrustManagers(TrustManagerFactory.java:219)
       at okhttp3.OkHttpClient.systemDefaultTrustManager(OkHttpClient.java:258)
       at okhttp3.OkHttpClient.<init>(OkHttpClient.java:232)
       at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:868)
       at com.tiket.gits.main.MainBannerFragment.onCreateView(MainBannerFragment.java:64)
       at android.support.v4.app.Fragment.performCreateView(Fragment.java:2189)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1299)
       at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(FragmentManager.java:1528)
       at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1595)
       at android.support.v4.app.BackStackRecord.executeOps(BackStackRecord.java:757)
       at android.support.v4.app.FragmentManagerImpl.executeOps(FragmentManager.java:2355)
       at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2146)
       at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(FragmentManager.java:2098)
       at android.support.v4.app.FragmentManagerImpl.execSingleAction(FragmentManager.java:1979)
       at android.support.v4.app.BackStackRecord.commitNowAllowingStateLoss(BackStackRecord.java:626)
       at android.support.v4.app.FragmentStatePagerAdapter.finishUpdate(FragmentStatePagerAdapter.java:166)
       at android.support.v4.view.ViewPager.populate(ViewPager.java:1268)
       at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:668)
       at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:630)
       at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:611)
       at com.tiket.gits.main.MainActivity$2$1.run(MainActivity.java:214)
       at android.os.Handler.handleCallback(Handler.java:733)
       at android.os.Handler.dispatchMessage(Handler.java:95)
       at android.os.Looper.loop(Looper.java:136)
       at android.app.ActivityThread.main(ActivityThread.java:5590)
       at java.lang.reflect.Method.invokeNative(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:515)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1280)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1096)
       at dalvik.system.NativeStart.main(NativeStart.java)`
