### ISSUE TITLE
Crash caused by a "null" buildIfSupported check

### ISSUE THREAD

**Issue by DavidEdwards** [square/okhttp#2769]
- [x] Bug report. 

[Location of the error is here](https://github.com/square/okhttp/blob/master/okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java#L184).

Only a single crash so far - probably not even fix-worthy, or even at all. However, I thought that you may want to know about it.

Error device:
Sony - D6603
Android 5.1.1

```
Fatal Exception: java.lang.ExceptionInInitializerError
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:309)
       at java.lang.Class.forName(Class.java:273)
       at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(SourceFile:184)
       at okhttp3.internal.platform.Platform.findPlatform(SourceFile:152)
       at okhttp3.internal.platform.Platform.(SourceFile)
       at okhttp3.internal.tls.CertificateChainCleaner.get(SourceFile:41)
       at okhttp3.OkHttpClient.(SourceFile)
       at okhttp3.OkHttpClient.(SourceFile)
       at ...
       at java.lang.Thread.run(Thread.java:818)
Caused by java.lang.NumberFormatException: Invalid int: "null"
       at java.lang.Integer.invalidInt(Integer.java:11)
       at java.lang.Integer.parseInt(Integer.java:358)
       at java.lang.Integer.parseInt(Integer.java)
       at android.net.Network.(Network.java)
       at java.lang.Class.classForName(Class.java)
       at java.lang.Class.forName(Class.java:309)
       at java.lang.Class.forName(Class.java:273)
       at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(SourceFile:184)
       at okhttp3.internal.platform.Platform.findPlatform(SourceFile:152)
       at okhttp3.internal.platform.Platform.(SourceFile)
       at okhttp3.internal.tls.CertificateChainCleaner.get(SourceFile:41)
       at okhttp3.OkHttpClient.(SourceFile)
       at okhttp3.OkHttpClient.(SourceFile)
       at ...
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by swankjesse** [comment]
Thanks for the report. But sigh, no action to take on this. My guess was a bad system property was set somehow.
