### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/OkHttpClient;

### ISSUE THREAD

**Issue by sendtion** [square/okhttp#2771]
stack=java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/OkHttpClient;
                                                          at com.bri.cdstm.ui.MainActivity.getAsynHttp(MainActivity.java:119)
                                                          at com.bri.cdstm.ui.MainActivity.onCreate(MainActivity.java:114)
                                                          at android.app.Activity.performCreate(Activity.java:6323)
                                                          at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2385)
                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2492)
                                                          at android.app.ActivityThread.access$900(ActivityThread.java:153)
                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1358)
                                                          at android.os.Handler.dispatchMessage(Handler.java:102)
                                                          at android.os.Looper.loop(Looper.java:148)
                                                          at android.app.ActivityThread.main(ActivityThread.java:5458)
                                                          at java.lang.reflect.Method.invoke(Native Method)
                                                          at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:738)
                                                          at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:628)

                                                       Caused by: java.lang.ClassNotFoundException: Didn't find class "okhttp3.OkHttpClient" on path: DexPathList[[dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-universal-image-loader-1.9.5_0485f67ee30402ff2cb9a08a51fa3316dec30f7b-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-x86-0.5.1_7f18e9367ecf1edacbe0c88c9a5e6000b7293486-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-java-0.5.1_fa75f211e45f4ad2392bbbbf5caf73b2414f79f7-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-exo-0.5.1_c7938e9961f99a7ab12a3096be7a0e09e609ad28-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-armv7a-0.5.1_4e4968c09f802caefc744c4b5d3ca15fa08483fe-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-tv.danmaku.ijk.media-ijkplayer-armv5-0.5.1_55fd4323183f90cee519ecbc9039984bd144093c-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-support-annotations-23.4.0_6c2a284fdd61d0d8ac24aa3991d9cfbc35ef85c7-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-org.adw.library-discrete-seekbar-1.0.1_57ed5cf60d7a0ec005927c59588981e62865ec13-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-mpchartlib_69ae15a6a9a33382ca00e70497aec3d0946da274-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-library-2.4.0_abd53f9872566ea74536e79ddcb4d5ecac8d2421-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-jp.wasabeef-glide-transformations-2.0.1_ddc0f9cbcea49151ca8747dbfde5c72ba2433a41-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-internal_impl-23.4.0_c4500b1317e13c591717b0f49d1cad55385fc27a-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-glide-3.7.0_9af733ecc099890fa4c4d4a7dae811cc1117aa0c-classes.dex", dex file "/data/data/com.bri.cdstm/files/instant-run/dex/slice-com.theartofdev.edmodo-android-image-cropper-2.2.5_c6214267d8533a1eae34f95c6faa514078a6

**Comment by sendtion** [comment]
compile 'com.squareup.okhttp3:okhttp:3.4.1' 
compile 'com.squareup.okio:okio:1.7.0'

Android 6.0.1 , this is why?

**Comment by swankjesse** [comment]
This is a build tools issue. No action we can take on this.
