### ISSUE TITLE
Permission Denied, it happens again. It is important for me. Need help.

### ISSUE THREAD

**Issue by maoaixianyu** [square/okhttp#2775]
I am warried for this.  Need help. Thanks.
Fatal Exception: java.lang.SecurityException: Permission denied (missing INTERNET permission?)
       at java.net.InetAddress.lookupHostByName(InetAddress.java:418)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
       at java.net.InetAddress.getAllByName(InetAddress.java:214)
       at okhttp3.Dns$1.lookup(Dns.java:39)
       at okhttp3.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:173)
       at okhttp3.internal.http.RouteSelector.nextProxy(RouteSelector.java:139)
       at okhttp3.internal.http.RouteSelector.next(RouteSelector.java:81)
       at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
       at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
       at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
       at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
       at okhttp3.RealCall.getResponse(RealCall.java:240)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:203)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
       at okhttp3.RealCall.access$100(RealCall.java:30)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by libcore.io.GaiException: getaddrinfo failed: EAI_NODATA (No address associated with hostname)
       at libcore.io.Posix.getaddrinfo(Posix.java)
       at libcore.io.ForwardingOs.getaddrinfo(ForwardingOs.java:61)
       at java.net.InetAddress.lookupHostByName(InetAddress.java:405)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
       at java.net.InetAddress.getAllByName(InetAddress.java:214)
       at okhttp3.Dns$1.lookup(Dns.java:39)
       at okhttp3.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:173)
       at okhttp3.internal.http.RouteSelector.nextProxy(RouteSelector.java:139)
       at okhttp3.internal.http.RouteSelector.next(RouteSelector.java:81)
       at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
       at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
       at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
       at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
       at okhttp3.RealCall.getResponse(RealCall.java:240)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:203)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
       at okhttp3.RealCall.access$100(RealCall.java:30)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)
Caused by libcore.io.ErrnoException: getaddrinfo failed: EACCES (Permission denied)
       at libcore.io.Posix.getaddrinfo(Posix.java)
       at libcore.io.ForwardingOs.getaddrinfo(ForwardingOs.java:61)
       at java.net.InetAddress.lookupHostByName(InetAddress.java:405)
       at java.net.InetAddress.getAllByNameImpl(InetAddress.java:236)
       at java.net.InetAddress.getAllByName(InetAddress.java:214)
       at okhttp3.Dns$1.lookup(Dns.java:39)
       at okhttp3.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:173)
       at okhttp3.internal.http.RouteSelector.nextProxy(RouteSelector.java:139)
       at okhttp3.internal.http.RouteSelector.next(RouteSelector.java:81)
       at okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
       at okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
       at okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at okhttp3.internal.http.HttpEngine.connect(HttpEngine.java:289)
       at okhttp3.internal.http.HttpEngine.sendRequest(HttpEngine.java:241)
       at okhttp3.RealCall.getResponse(RealCall.java:240)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:198)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:203)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:187)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:160)
       at okhttp3.RealCall.access$100(RealCall.java:30)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:841)

**Comment by artem-zinnatullin** [comment]
You need to declare internet permission in the AndroidManifest.xml. See
https://developer.android.com/training/basics/network-ops/connecting.html

**Comment by maoaixianyu** [comment]
This problem  is still existing. So do you have another method?
![qq20160820-0](https://cloud.githubusercontent.com/assets/17868022/17828420/938b35d0-66c3-11e6-9228-cc66cfe681e7.png)
So how can  I  do? Help me.

**Comment by Ljy545733599** [comment]
i have the same problem when i want to get localDNS address. Could you please tell me how to slove this problem if you have solved it？
