### ISSUE TITLE
CallTest.legalToExecuteTwiceCloning_Async is flaky

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#2808]
https://s3.amazonaws.com/archive.travis-ci.org/jobs/154435176/log.txt

```
Tests run: 142, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 16.135 sec <<< FAILURE! - in okhttp3.CallTest
legalToExecuteTwiceCloning_Async(okhttp3.CallTest)  Time elapsed: 0.013 sec  <<< FAILURE!
org.junit.ComparisonFailure: expected:<[abc]> but was:<[def]>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at okhttp3.RecordedResponse.assertBody(RecordedResponse.java:90)
	at okhttp3.CallTest.legalToExecuteTwiceCloning_Async(CallTest.java:608)
```

**Comment by yschimke** [comment]
https://github.com/square/okhttp/pull/2809

**Comment by swankjesse** [comment]
Thanks @yschimke !
