### ISSUE TITLE
HttpLoggingInterceptor.java maybe occur a NullPointException on line 220;

### ISSUE THREAD

**Issue by android9527** [square/okhttp#2811]
`Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:220)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.access$100(RealCall.java:33)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)`

`HttpLoggingInterceptor loggingInterceptor = new HttpLoggingInterceptor().setLevel(level);
builder.addInterceptor(loggingInterceptor);    // log
OkHttpClient okHttpClient = builder.build();
WebSocketCall call = new WebSocketCall(okHttpClient, request);`

**Comment by swankjesse** [comment]
This is another case where websocket responses behave strangely.

**Comment by swankjesse** [comment]
(what should interceptors do when they encounter a websocket?)

**Comment by JakeWharton** [comment]
An empty body I would think. The response code is 101 so no body should be expected anyway.

**Comment by android9527** [comment]
yeah, the body is empty.
