### ISSUE TITLE
okhttp3.RealCall$ApplicationInterceptorChain.proceed intermittently throws NPE

### ISSUE THREAD

**Issue by jaredculp** [square/okhttp#2895]
I'm trying to write an `Interceptor` that dynamically appends a UUID header called "Correlation" (used to correlate requests across microservices).

The interceptor seems to throw a NPE randomly when I execute concurrent requests.
```
java.util.concurrent.ExecutionException: java.lang.NullPointerException

	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at TestInterceptor.test(TestInterceptor.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at okhttp3.mockwebserver.MockWebServer$2.evaluate(MockWebServer.java:156)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.NullPointerException
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at TestInterceptor$CorrelatedInterceptor.intercept(TestInterceptor.java:106)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at TestInterceptor.lambda$test$0(TestInterceptor.java:78)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

I've reproduced the issue with the following isolated test case below. The tests may pass a few times, but eventually will fail. Changing the `count` variable to `1` will make the tests pass every time, but anything larger than 1 causes intermittent failures.

```java
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.ObjectMapper;
import okhttp3.HttpUrl;
import okhttp3.Interceptor;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.mockwebserver.MockResponse;
import okhttp3.mockwebserver.MockWebServer;
import org.junit.Rule;
import org.junit.Test;
import retrofit2.Call;
import retrofit2.Response;
import retrofit2.Retrofit;
import retrofit2.converter.jackson.JacksonConverterFactory;
import retrofit2.http.GET;

import java.io.IOException;
import java.util.UUID;
import java.util.concurrent.ExecutionException;
import java.util.concurrent.ExecutorCompletionService;
import java.util.concurrent.Executors;

import static com.google.common.truth.Truth.assertThat;
import static java.util.Objects.requireNonNull;

public class TestInterceptor {

    @Rule
    public final MockWebServer mockWebServer = new MockWebServer();

    interface MyClient {
        @GET("/")
        Call<MyObject> get();
    }

    static final class MyObject {
        private final UUID value;

        @JsonCreator
        public MyObject(@JsonProperty("value") UUID value) {
            this.value = value;
        }

        public UUID getValue() {
            return this.value;
        }
    }

    @Test
    public void test() throws IOException, InterruptedException, ExecutionException {
        final int count = 10;

        final ObjectMapper mapper = new ObjectMapper();
        final UUID correlation = UUID.randomUUID();
        final MyObject myObject = new MyObject(correlation);

        for (int i = 0; i < count; i++) {
            this.mockWebServer.enqueue(new MockResponse()
                    .setBody(mapper.writeValueAsString(myObject)));
        }

        final HttpUrl httpUrl = new HttpUrl.Builder()
                .host(this.mockWebServer.getHostName())
                .port(this.mockWebServer.getPort())
                .scheme("http")
                .build();

        final OkHttpClient.Builder okHttpBuilder = new OkHttpClient.Builder();
        final Retrofit.Builder retrofitBuilder = retrofitBuilder(httpUrl, mapper);
        final MyCorrelated myCorrelated = new MyCorrelated(okHttpBuilder, retrofitBuilder);

        final ExecutorCompletionService<Response<MyObject>> executorService =
                new ExecutorCompletionService<>(Executors.newFixedThreadPool(count));
        for (int i = 0; i < count; i++) {
            executorService.submit(() -> myCorrelated.withId(correlation).get().execute());
        }

        for (int i = 0; i < count; i++) {
            final Response response = executorService.take().get();
            assertThat(response.isSuccessful()).isTrue();

            assertThat(this.mockWebServer.takeRequest().getHeader("Correlated")).isEqualTo(correlation.toString());
        }
    }

    private static final class CorrelatedInterceptor implements Interceptor {

        private static final String HEADER_NAME = "Correlated";

        private final UUID correlationId;

        public CorrelatedInterceptor(UUID correlationId) {
            this.correlationId = requireNonNull(correlationId, "correlationId");
        }

        @Override
        public okhttp3.Response intercept(Chain chain) throws IOException {
            final Request original = chain.request();
            final Request reWritten = original.newBuilder()
                    .addHeader(HEADER_NAME, this.correlationId.toString())
                    .build();

            return chain.proceed(reWritten);
        }

    }

    private static Retrofit.Builder retrofitBuilder(HttpUrl url, ObjectMapper mapper) {
        return new Retrofit.Builder().baseUrl(url).addConverterFactory(JacksonConverterFactory.create(mapper));
    }

    interface Correlated<T> {
        T withId(UUID id);
    }

    private static final class MyCorrelated implements Correlated<MyClient> {

        private final OkHttpClient.Builder okHttpBuilder;
        private final Retrofit.Builder retrofitBuilder;

        private MyCorrelated(OkHttpClient.Builder okHttpBuilder, Retrofit.Builder retrofitBuilder) {
            this.okHttpBuilder = okHttpBuilder;
            this.retrofitBuilder = retrofitBuilder;
        }

        @Override
        public MyClient withId(UUID id) {
            return this.retrofitBuilder
                    .client(this.okHttpBuilder.addInterceptor(new CorrelatedInterceptor(id)).build())
                    .build()
                    .create(MyClient.class);
        }
    }
}
```

Is there something obvious that I'm missing?

**Comment by jaredculp** [comment]
Also should note this is with Retrofit 2.1 and OkHttp 3.3.1

**Comment by swankjesse** [comment]
Paste the stack trace?

**Comment by jaredculp** [comment]
@swankjesse here's the full output from my IDE.

```
Oct 07, 2016 9:22:45 AM okhttp3.mockwebserver.MockWebServer$3 execute
INFO: MockWebServer[56184] starting to accept connections
Oct 07, 2016 9:22:46 AM okhttp3.mockwebserver.MockWebServer$3 acceptConnections
INFO: MockWebServer[56184] done accepting connections: Socket closed

java.util.concurrent.ExecutionException: java.lang.NullPointerException

	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at TestInterceptor.test(TestInterceptor.java:82)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at okhttp3.mockwebserver.MockWebServer$2.evaluate(MockWebServer.java:156)
	at org.junit.rules.RunRules.evaluate(RunRules.java:20)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:117)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:262)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:84)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.NullPointerException
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:190)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at okhttp3.RealCall.execute(RealCall.java:57)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at TestInterceptor.lambda$test$0(TestInterceptor.java:78)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


Process finished with exit code 255
```

**Comment by jaredculp** [comment]
@swankjesse it appears the problem is with reusing the `OkHttpClient.Builder`. Closing this as it's not a valid bug.
