### ISSUE TITLE
SSL-Connection via Proxy with Authentcation fails

### ISSUE THREAD

**Issue by ja-fra** [square/okhttp#2900]
The following simple request via a Proxy that requires Authentication fails:
```#!java
final Proxy proxy = new Proxy(Proxy.Type.HTTP, new InetSocketAddress("localhost", 8001));
final Response response = new OkHttpClient.Builder()
        .proxy(proxy)
        .proxyAuthenticator(new Authenticator() {
            @Override
            public Request authenticate(Route route, Response response) throws IOException {
                String credential = Credentials.basic("proxyuser", "proxypass");
                return response.request().newBuilder()
                        .header("Proxy-Authorization", credential)
                        .build();                        
            }
        })
        .build()
        .newCall(new Request.Builder()
                .get()
                .url("https://www.google.com/")
                .build())
        .execute();
```
with the following error:
```
Caused by: java.net.ProtocolException: Unexpected status line: <html>
	at okhttp3.internal.http.StatusLine.parse(StatusLine.java:69)
	at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.java:296)
	at okhttp3.internal.connection.RealConnection.buildTunneledConnection(RealConnection.java:155)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:111)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:193)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:129)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:98)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
	at okhttp3.RealCall.execute(RealCall.java:60)
```

The same request via a Proxy _without_ Authentication works fine, as does a Non-SSL request via Proxy with Authentication.

The issue came up while debugging googlemaps/google-maps-services-java#190. Both, v2.7.5 and v3.4.1 show the same behaviour.

For testing, I'm using [mitmproxy](https://mitmproxy.org/) with the following parameters: `mitmproxy -p 8001 --singleuser proxyuser:proxypass`

**Comment by swankjesse** [comment]
The preceding HTTP response om the shared connection has a mismatching status code + body length. Can you log that response and its headers and paste here?

**Comment by ja-fra** [comment]
```
> CONNECT www.google.com:443 HTTP/1.1
> Host: www.google.com:443
> Proxy-Connection: Keep-Alive
> User-Agent: okhttp/3.4.1

< HTTP/1.1 407 Proxy Authentication Required
< Proxy-Authenticate: Basic realm="mitmproxy"
< 
< <html>
<             <head>
<                 <title>407 Proxy Authentication Required</title>
<             </head>
<             <body>Proxy Authentication Required</body>
<         </html>

> CONNECT www.google.com:443 HTTP/1.1
> Host: www.goggle.com:443
> Proxy-Connection: Keep-Alive
> User-Agent: okhttp/2.7.5
> Proxy-Authorization: Basic cHJveHl1c2VyOnByb3h5cGFzcw==
```

**Comment by swankjesse** [comment]
On first glance it looks like a malformed response from the proxy. It provides no mechanism to differentiate the HTML from the response that follows. Yuck.

**Comment by ja-fra** [comment]
I'm not very deep into the HTTP-Protocol, but for me the proxy-response looks valid. I see the following problems:
* The Client is re-using the connection despite the the missing `Connection: Keep-Alive`-Header in the response
* Before sending the follow-up request, the Response-Body is not fully consumed on the client side.

**Comment by swankjesse** [comment]
This is a problem with your HTTP server. You should report a bug there. The problem is that it fails to include a mechanism for the client to delimit the end of the first HTTP response’s body and the start of the second HTTP response’s status. It could do this with a `Content-Length` header, or with a `Connection: close` header.

**Comment by ja-fra** [comment]
Tend to disagree here: 
Both [`Content-Length`](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.13) and [`Connection`](https://www.w3.org/Protocols/rfc2616/rfc2616-sec14.html#sec14.10) are optional response-headers, so the client needs to be able to work properly without their presence.

Other HTTP-clients, even plain `java.net.HttpUrlConnection` manage to connect via that proxy, but anyway - we'll try to find a workaround solution...

**Comment by adriano-fonseca** [comment]
ja-fra did you get make this work?
I have the same issue here.

**Comment by ja-fra** [comment]
sorry, no.
In the end we didn't need `Authentication` for the proxy in production so we didn't investigate the issue further.

**Comment by aleksey-ho** [comment]
I recently encountered this problem, and described it on staskoverflov, but got no response
https://stackoverflow.com/questions/50028879/okhttp-request-via-proxy-with-authentcation-fails
I'm 100% sure that the problem is not in the HTTP server. The problem has not been solved. If you have any ideas...

**Comment by derwild** [comment]
I'm having the exact same issue.
As it seems there is no solution for it as of yet, I will try to use a different http client and see if it runs into the same issue.
Kinda sad, as I really liked okHttp... =(

**Comment by swankjesse** [comment]
@derwild did you try [pre-emptive authentication](https://square.github.io/okhttp/4.x/okhttp/okhttp3/-authenticator/#preemptive-authentication)? That may prevent the 407 from occurring in the first place.
