### ISSUE TITLE
java.lang.NullPointerException:BridgeInterceptor.intercept

### ISSUE THREAD

**Issue by heqingbao** [square/okhttp#2948]
It occurs a lot, But I can not locate the row that occurred, Can anyone help me out please.
```
java.lang.NullPointerException
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java)
	                                                     recover(RetryAndFollowUpInterceptor.java)
	                                                     isRecoverable(RetryAndFollowUpInterceptor.java)
	                                                     sameConnection(RetryAndFollowUpInterceptor.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java)
	at okhttp3.RealCall.access$100(RealCall.java)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
	at java.lang.Thread.run(Thread.java:838)
```

**Comment by swankjesse** [comment]
Are you on the latest version? Sadly without line numbers in the stack trace there’s not much I can do. Maybe provide a test case?

**Comment by heqingbao** [comment]
@swankjesse The latest version `3.4.1`

**Comment by heqingbao** [comment]
Is it possible `Content-Length` == 0? In this case `HttpHeaders.hasBody` will return true. But `networkResponse.body()` == null.

**Comment by swankjesse** [comment]
We don’t treat an empty body any differently.

**Comment by swankjesse** [comment]
Can you provide a test case to demonstrate the problem?

**Comment by Jaspreet84** [comment]
I'm on Okhttp 3.5.0  and still see this issue. Important to note that it happens only after I add a cookie to cookiemanager of client:


Exception in thread "main" java.lang.NullPointerException
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:85)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
	at okhttp3.RealCall.execute(RealCall.java:63)
	at com.zscaler.qa.ztaap.business.Authentication.main(Authentication.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)

**Comment by swankjesse** [comment]
@jaspreet84 please fix your cookie jar to not return null when it should return an empty list.
