### ISSUE TITLE
NPE in RetryAndFollowupInterceptor

### ISSUE THREAD

**Issue by nageshtikare** [square/okhttp#2960]
Randomly getting NPE when i am adding headers to request using intercept.

Using Http3 and retrofit2 are latest version.

Adding header code looks something like this:
OkHttpClient.Builder httpClient = new OkHttpClient.Builder();  
httpClient.addInterceptor(new Interceptor() {  
    @Override
    public Response intercept(Interceptor.Chain chain) throws IOException {
        Request original = chain.request();

        // Request customization: add request headers
        Request.Builder requestBuilder = original.newBuilder()
                .header("Authorization", "auth-value"); 

        Request request = requestBuilder.build();
        return chain.proceed(request);
    }
});

OkHttpClient client = httpClient.build();  

Issue:
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'okhttp3.HttpUrl okhttp3.Request.url()' on a null object reference
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:111)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at mypackage.client.RetrofitClient$2.intercept(SourceFile:112)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:170)
       at okhttp3.RealCall.access$100(SourceFile:33)
       at okhttp3.RealCall$AsyncCall.execute(SourceFile:120)
       at okhttp3.internal.NamedRunnable.run(SourceFile:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by swankjesse** [comment]
Could you provide an executable test case?

**Comment by nageshtikare** [comment]
Basically I am trying to add HMAC to the header. It is working fine. But randomly on some devices, it throws NPE. Below is the complete code.

`import java.io.IOException;
import java.io.InputStream;
import java.net.URLEncoder;
import java.security.KeyManagementException;
import java.security.KeyStore;
import java.security.KeyStoreException;
import java.security.NoSuchAlgorithmException;
import java.security.cert.Certificate;
import java.security.cert.CertificateException;
import java.security.cert.CertificateFactory;
import java.util.Map;
import java.util.Set;
import java.util.concurrent.TimeUnit;

import javax.net.ssl.HostnameVerifier;
import javax.net.ssl.SSLContext;
import javax.net.ssl.SSLSession;
import javax.net.ssl.TrustManagerFactory;
import javax.net.ssl.X509TrustManager;

import okhttp3.Interceptor;
import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import retrofit2.Retrofit;
import retrofit2.converter.jackson.JacksonConverterFactory;

public final class RetrofitClient {

    private RetrofitClient() {

    }

    private static OkHttpClient getHttpClient(final Context context, final Map<String, String> additionalHeaders) throws CertificateException, KeyStoreException, IOException, NoSuchAlgorithmException, KeyManagementException {
        CertificateFactory cf = CertificateFactory.getInstance("X.509");
        InputStream caInput = context.getResources().openRawResource(R.raw.certificate);
        Certificate ca;
        ca = cf.generateCertificate(caInput);

        String keyStoreType = KeyStore.getDefaultType();
        KeyStore keyStore = KeyStore.getInstance(keyStoreType);
        keyStore.load(null, null);
        keyStore.setCertificateEntry("ca", ca);

        String tmfAlgorithm = TrustManagerFactory.getDefaultAlgorithm();
        TrustManagerFactory tmf = TrustManagerFactory.getInstance(tmfAlgorithm);
        tmf.init(keyStore);

        SSLContext sslcontext = SSLContext.getInstance("TLS");
        sslcontext.init(null, tmf.getTrustManagers(), null);

        OkHttpClient.Builder okHttp = new OkHttpClient().newBuilder();
        okHttp.connectTimeout(Constants.CONNECTION_TIMEOUT, TimeUnit.MILLISECONDS);
        okHttp.readTimeout(Constants.CONNECTION_TIMEOUT, TimeUnit.MILLISECONDS);
        okHttp.writeTimeout(Constants.CONNECTION_TIMEOUT, TimeUnit.MILLISECONDS);
        okHttp.retryOnConnectionFailure(false);

        okHttp.sslSocketFactory(sslcontext.getSocketFactory(), (X509TrustManager) tmf.getTrustManagers()[0]);
        okHttp.hostnameVerifier(new HostnameVerifier() {
            @Override
            public boolean verify(String s, SSLSession sslSession) {
                return true;
            }
        });

        final Auth auth = new Auth(context);

        //add headers
        okHttp.addInterceptor(new Interceptor() {
            @Override
            public Response intercept(Chain chain) throws IOException {
                Request.Builder requestBuilder;
                Request request = null;

                try {
                    String requestUrl = chain.request().url().toString(); 		//NPE issue : Attempt to invoke virtual method 'okhttp3.HttpUrl okhttp3.Request.url()' on a null object reference

                    requestBuilder = chain.request().newBuilder()
                            .addHeader("hmac", generateHmac(requestUrl))
							.addHeader("somemoreHeaders", "values");
							
                    if(additionalHeaders != null && !additionalHeaders.isEmpty()) {
                        Set<Map.Entry<String, String>> entries = additionalHeaders.entrySet();

                        for (Map.Entry<String, String> header : entries) {
                            requestBuilder.addHeader(header.getKey(), URLEncoder.encode((auth.getEncodedData(header.getValue())), context.getString(R.string.charSet)));
                        }
                    }

                    request = requestBuilder.build();
                } catch (Exception e) {
                    e.printStackTrace();
                }
                return chain.proceed(request);
            }
        });

		return okHttp.build();
    }

    /**
     * Additional headers added apart from default headers.. 
     * @param context
     * @return
     */
    public static Retrofit getRetrofitClient(final Context context, Map<String, String> additionalHeaders) {
        Retrofit retrofit = null;
        try {
            retrofit = new Retrofit.Builder()
                    .addConverterFactory(JacksonConverterFactory.create())
                    .client(getHttpClient(context, additionalHeaders))
                    .baseUrl(UrlConstants.BASE_URL)
                    .build();
        } catch (CertificateException | KeyStoreException | NoSuchAlgorithmException | IOException | KeyManagementException e) {
            e.printStackTrace();
        }

        return retrofit;
    }

    /** Default headers added
     * @param context
     * @return
     */
    public static Retrofit getRetrofitClient(Context context) {
        return getRetrofitClient(context, null);
    }
}
`

**Comment by nageshtikare** [comment]
Can you please tell me when there can be a scenario when chain.request() returns null?

**Comment by swankjesse** [comment]
I think your problem is that when an exception is thrown in your interceptor, you pass a null request to `chain.proceed()`. Don’t do that.
