### ISSUE TITLE
Cancelling streaming responses

### ISSUE THREAD

**Issue by ming13** [square/okhttp#2964]
Long story short, I wrote a sample to indicate the issue (or not an issue, have no idea at this point).

```java
public final class OkHttpCalls
{
    @Test
    public void callIsCancelledWhileReadingStreamingResponse() throws IOException {
        OkHttpClient client = new OkHttpClient();

        Request request = new Request.Builder().get().url("https://httpbin.org/stream/100").build();
        final Call call = client.newCall(request);
        Response response = call.execute();

        Executors.newSingleThreadExecutor().execute(new Runnable() {
            @Override
            public void run() {
                call.cancel();
            }
        });

        try (BufferedSource responseBody = response.body().source()) {
            while (!responseBody.exhausted()) {
                String responseBodyLine = responseBody.readUtf8Line();

                System.out.println(responseBodyLine);
            }
        }
    }
}
```
Actually it might pass depending on your network connection, but you can get the idea. The output is something like that.
```
{"url": "https://httpbin.org/stream/100", "headers": {"Host": "httpbin.org", "Accept-Encoding": "gzip", "User-Agent": "okhttp/3.4.1"}, "args": {}, "id": 0, "origin": "212.98.173.54"}
...
{"url": "https://httpbin.org/stream/100", "headers": {"Host": "httpbin.org", "Accept-Encoding": "gzip", "User-Agent": "okhttp/3.4.1"}, "args": {}, "id": 84, "origin": "212.98.173.54"}

java.net.SocketException: Socket closed

	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
	at java.net.SocketInputStream.read(SocketInputStream.java:170)
	at java.net.SocketInputStream.read(SocketInputStream.java:141)
	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:973)
	at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:930)
	at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
	at okio.Okio$2.read(Okio.java:138)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
	at okio.RealBufferedSource.request(RealBufferedSource.java:66)
	at okio.RealBufferedSource.require(RealBufferedSource.java:59)
	at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:284)
	at okhttp3.internal.http.Http1xStream$ChunkedSource.readChunkSize(Http1xStream.java:437)
	at okhttp3.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:418)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:325)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:314)
	at okio.RealBufferedSource.readUtf8Line(RealBufferedSource.java:200)
	at net.juno.rd.OkHttpCalls.callIsCancelledWhileReadingStreamingResponse(OkHttpCalls.java:33)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:119)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:42)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:234)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:74)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```
At our real environment we see `SocketException` when trying to call `exhausted()` as well.
```
java.net.SocketException: Socket closed
     at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:705)
     at okio.Okio$2.read(Okio.java:138)
     at okio.AsyncTimeout$2.read(AsyncTimeout.java:236)
     at okio.RealBufferedSource.request(RealBufferedSource.java:66)
     at okio.RealBufferedSource.require(RealBufferedSource.java:59)
     at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:284)
     at okhttp3.internal.http.Http1xStream$ChunkedSource.readChunkSize(Http1xStream.java:437)
     at okhttp3.internal.http.Http1xStream$ChunkedSource.read(Http1xStream.java:418)
     at okio.RealBufferedSource.read(RealBufferedSource.java:45)
     at okio.RealBufferedSource.exhausted(RealBufferedSource.java:55)
     at okio.InflaterSource.refill(InflaterSource.java:101)
     at okio.InflaterSource.read(InflaterSource.java:62)
     at okio.GzipSource.read(GzipSource.java:80)
     at okio.RealBufferedSource.read(RealBufferedSource.java:45)
     at okio.ForwardingSource.read(ForwardingSource.java:35)
     at retrofit2.OkHttpCall$ExceptionCatchingRequestBody$1.read(OkHttpCall.java:279)
     at okio.RealBufferedSource.exhausted(RealBufferedSource.java:55)
     at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
     at rx.internal.operators.OnSubscribeRedo$2$1.onNext(OnSubscribeRedo.java:244)
     at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.onNext(OperatorOnErrorResumeNextViaFunction.java:154)
     at rx.internal.operators.OnSubscribeMap$MapSubscriber.onNext(OnSubscribeMap.java:77)
     at rx.internal.operators.OperatorSubscribeOn$1$1.onNext(OperatorSubscribeOn.java:53)
     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:173)
     at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(OperatorSubscribeOn.java:80)
     at rx.internal.producers.ProducerArbiter.setProducer(ProducerArbiter.java:126)
     at rx.internal.operators.OperatorOnErrorResumeNextViaFunction$4.setProducer(OperatorOnErrorResumeNextViaFunction.java:159)
     at rx.internal.operators.OnSubscribeMap$MapSubscriber.setProducer(OnSubscribeMap.java:102)
     at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(OperatorSubscribeOn.java:76)
     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:152)
     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(RxJavaCallAdapterFactory.java:138)
     at rx.Observable.unsafeSubscribe(Observable.java:10200)
     at rx.internal.operators.OperatorSubscribeOn$1.call(OperatorSubscribeOn.java:94)
     at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
     at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
     at java.lang.Thread.run(Thread.java:818)
```

In other words. We are reading a streaming response. Sometimes the connection is closed by cancelling the call — Retrofit does that for us on `Observable#unsubscribe`. As a result, any operation on underlying `Source` throws `SocketException`. Unfortunately, we cannot access the `Source` state and react properly. Something like `Source.closed()` probably can help to detect such situations.

My question is — what is the correct way to dealing with such conditions? Should we always wrap `Source` operations and catch exceptions in situations when underlying `Source` can be cancelled this way or another?

**Comment by swankjesse** [comment]
Yes. You always need to handle IOExceptions which can be triggered by cancellation or connectivity problems.
