### ISSUE TITLE
java.lang.IllegalArgumentException: keys must match regex [a-z0-9_-]{1,64}

### ISSUE THREAD

**Issue by jaredsburrows** [square/okhttp#2970]
## Android: 
5.0.2

## Manufacturer: 
LGE

## Model: 
LG-X150

## Exception:
```
java.lang.IllegalArgumentException: keys must match regex [a-z0-9_-]{1,64}: "bDIRTY"
	at com.android.okhttp.internal.DiskLruCache.validateKey(DiskLruCache.java:655)
	at com.android.okhttp.internal.DiskLruCache.remove(DiskLruCache.java:576)
	at com.android.okhttp.internal.DiskLruCache.trimToSize(DiskLruCache.java:638)
	at com.android.okhttp.internal.DiskLruCache.access$100(DiskLruCache.java:86)
	at com.android.okhttp.internal.DiskLruCache$1.run(DiskLruCache.java:169)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
```

**Comment by jaredsburrows** [comment]
Since this in Android, I am guessing Google has to upgrade their OkHTTP version?

**Comment by swankjesse** [comment]
Yes.

**Comment by liamcottle** [comment]
Same issue here - any workaround for this ?

**Comment by Trollologic** [comment]
Did anyone found a workaround for this issue? It is strange that this is only happening on devices running on Lollipop.
