### ISSUE TITLE
[Bug report]Crash

### ISSUE THREAD

**Issue by joedan0104** [square/okhttp#2976]
java.lang.ArrayIndexOutOfBoundsException
length=8192; regionStart=0; regionLength=-1
java.util.Arrays.checkOffsetAndCount(Arrays.java:1719)
libcore.io.IoBridge.write(IoBridge.java:491)
java.io.FileOutputStream.write(FileOutputStream.java:186)
java.util.MarsUtils.write(MarsUtils.java:33)
com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:704)
okio.o$2.a(Okio.java:140)
okio.a$2.a(AsyncTimeout.java:238)
okio.r.a(RealBufferedSource.java:55)
okhttp3.internal.a.b.a(RealConnection.java:379)
okhttp3.internal.http.p.a(StreamAllocation.java:135)
okhttp3.internal.http.p.a(StreamAllocation.java:93)
okhttp3.internal.http.g.a(HttpEngine.java:296)
okhttp3.internal.http.g.a(HttpEngine.java:248)
okhttp3.x.a(RealCall.java:243)
okhttp3.x$a.a(RealCall.java:201)
okhttp3.x.a(RealCall.java:163)
okhttp3.x.a(RealCall.java:30)
okhttp3.x$b.b(RealCall.java:127)
okhttp3.internal.i.run(NamedRunnable.java:32)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
java.lang.Thread.run(Thread.java:818)

**Comment by JakeWharton** [comment]
This is a bug in Android. Please report to http://b.android.com

**Comment by swankjesse** [comment]
Probably not Google’s Android. Something called MarsUtils in on your device and it's buggy. I couldn't find out what that is.

**Comment by yogurtearl** [comment]
"MarsUtil" might be related to the app being scanned by https://mars.trendmicro.com/ ...

**Comment by Larnoo** [comment]
`java.lang.ArrayIndexOutOfBoundsException: length=8192; regionStart=0; regionLength=-1
	at java.util.Arrays.checkOffsetAndCount(Arrays.java:1719)
	at libcore.io.IoBridge.write(IoBridge.java:491)
	at java.io.FileOutputStream.write(FileOutputStream.java:186)
	at java.util.MarsUtils.write(MarsUtils.java:33)
	at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:704)
	at okio.u.read(SourceFile:138)
	at okio.c.read(SourceFile:236)
	at okio.ab.indexOf(SourceFile:325)
	at okio.ab.indexOf(SourceFile:314)
	at okio.ab.readUtf8LineStrict(SourceFile:210)
	at okhttp3.internal.http.Http1xStream.readResponse(SourceFile:186)
	at okhttp3.internal.http.Http1xStream.readResponseHeaders(SourceFile:127)
	at okhttp3.internal.http.CallServerInterceptor.intercept(SourceFile:53)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:124)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:170)
	at okhttp3.RealCall.access$100(SourceFile:33)
	at okhttp3.RealCall$AsyncCall.execute(SourceFile:120)
	at okhttp3.internal.NamedRunnable.run(SourceFile:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)`

I have the same problem.

**Comment by lorinwu** [comment]
hi  @joedan0104  How can contact with you? Could you kind please leave a method to let me contact you easily, thanks.

**Comment by caltseng** [comment]
FYI I we have a customer that ran into this as well.

**Comment by swankjesse** [comment]
The `GI-I9500_TMMARS` isn’t a real device. It’s a bogus tool that triggers impossible crashes and logs them to your crash reporting tool
