### ISSUE TITLE
 java.lang.IllegalStateException: Already Executed

### ISSUE THREAD

**Issue by klower** [square/okhttp#2984]
String url = Constant.getBaseUrl("", "", 1, 10);
        mCall = OkHttpUtils.getInstance().get(url, null, new CustomResponseListener(null) {
            @Override
            public void onSucess(int code, String response) {
                LogTool.d(response);
            }

            @Override
            public void onError(int code, String msg) {

            }
        });

        mProgressDialog.setOnDismissListener(new DialogInterface.OnDismissListener() {
            @Override
            public void onDismiss(DialogInterface dialog) {
                mCall.cancel();
            }
        });

FATAL EXCEPTION: OkHttp Dispatcher
                                                                   Process: com.klower.common, PID: 10212
                                                                   java.lang.IllegalStateException: Already Executed
                                                                       at okhttp3.RealCall.execute(RealCall.java:55)
                                                                       at com.klower.common.interfaces.CustomResponseListener.onFailure(CustomResponseListener.java:31)
                                                                       at com.klower.common.communication.OkHttpUtils$1.onFailure(OkHttpUtils.java:47)
                                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:133)
                                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:818)

**Comment by swankjesse** [comment]
Looks like you're calling execute twice on the same call, which is forbidden. If you're doing something else please resubmit with an executable test case.
