### ISSUE TITLE
java.io.IOException: unexpected end of stream on okhttp3.Address

### ISSUE THREAD

**Issue by WanYouZhi** [square/okhttp#3006]
it's get method ,the response back is http1.0 
 Caused by: java.io.EOFException: \n not found: size=0 content=…
at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:215)
at okhttp3.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
at ... 24 more

**Comment by JakeWharton** [comment]
Dupe of #1517.

**Comment by xybCoder** [comment]
I have the same problem. the bug is fix?

**Comment by juliovera78** [comment]
the same happen to me.. ;(
