### ISSUE TITLE
IllegalStateException: cache is closed，Please send a simple solution.Thanks

### ISSUE THREAD

**Issue by LucianWang** [square/okhttp#3007]
java.lang.IllegalStateException: cache is closed
	at okhttp3.internal.DiskLruCache.checkNotClosed(DiskLruCache.java:644)
	at okhttp3.internal.DiskLruCache.edit(DiskLruCache.java:458)
	at okhttp3.internal.DiskLruCache.edit(DiskLruCache.java:452)
	at okhttp3.Cache.put(Cache.java:244)
	at okhttp3.Cache.access$000(Cache.java:135)
	at okhttp3.Cache$1.put(Cache.java:147)
	at okhttp3.internal.http.HttpEngine.maybeCache(HttpEngine.java:438)
	at okhttp3.internal.http.HttpEngine.readResponse(HttpEngine.java:683)
	at okhttp3.RealCall.getResponse(RealCall.java:244)
	at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at okhttp3.RealCall.access$100(RealCall.java:30)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

**Comment by swankjesse** [comment]
Please send a simple test case. Thank you.
