### ISSUE TITLE
while releasing apk okhttp 3.5.0 error

### ISSUE THREAD

**Issue by srinathvidapu** [square/okhttp#3040]
Warning:Exception while processing task java.io.IOException: Can't write [/Users/Srinath/Desktop/Android_User/app/build/intermediates/transforms/proguard/release/jars/3/1f/main.jar] (Can't read [/Users/Srinath/.gradle/caches/modules-2/files-2.1/com.squareup.okhttp3/okhttp/3.5.0/4b0bb6bfbecbdd42b97ff400af342bfe7f32bc83/okhttp-3.5.0.jar(;;;;;;**.class)] (Duplicate zip entry [okhttp-3.5.0.jar:okhttp3/internal/ws/RealWebSocket$1.class]))

**Comment by swankjesse** [comment]
This is an issue with your build tools. Please ask on StackOverflow for help.

**Comment by allenchen1154** [comment]
This is caused by the inclusion of the OkHttp websockets API in version 3.5.0: https://medium.com/square-corner-blog/web-sockets-now-shipping-in-okhttp-3-5-463a9eec82d1#.kn0cx1dhg
This causes a conflict if any of your dependencies bring in the now-deprecated `okhttp-ws` library.
To fix this on your end, include the following in your `build.gradle`:
```
configurations.all {
    // OkHttp 3.5.0+ includes the websockets API, so we need this to prevent a conflict
    exclude module: 'okhttp-ws'
}
```

**Comment by cinder92** [comment]
@allenchen1154 thanks for your reply, but now i'm getting following error...

```
FATAL EXCEPTION: AsyncTask #1
                                                                 Process: com.laRancherita2, PID: 32645
                                                                 java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                     at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                     at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                     at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                     at java.lang.Thread.run(Thread.java:818)
                                                                  Caused by: java.lang.NoClassDefFoundError: com.facebook.react.devsupport.JSPackagerWebSocketClient
                                                                     at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:122)
                                                                     at com.facebook.react.devsupport.DevServerHelper$1.doInBackground(DevServerHelper.java:119)
                                                                     at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                     at java.lang.Thread.run(Thread.java:818) 
```

ENV
OS : mac
Platform : Android
RN Version : 0.39
