### ISSUE TITLE
BufferedSink NullPointerException

### ISSUE THREAD

**Issue by torv** [square/okhttp#3046]
java.lang.NullPointerException: Attempt to invoke interface method 'okio.BufferedSink okio.BufferedSink.writeUtf8(java.lang.String)' on a null object reference
                                                             at com.squareup.okhttp.internal.http.Http1xStream.writeRequest(Http1xStream.java:169)
                                                             at com.squareup.okhttp.internal.http.Http1xStream.writeRequestHeaders(Http1xStream.java:125)
                                                             at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:715)
                                                             at org.qiyi.net.httpengine.impl.OkHttpStack$1.intercept(OkHttpStack.java:95)
                                                             at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:700)
                                                             at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:581)
                                                             at com.squareup.okhttp.Call.getResponse(Call.java:288)
                                                             at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:244)
                                                             at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:206)
                                                             at com.squareup.okhttp.Call.execute(Call.java:81)

**Comment by swankjesse** [comment]
Please upgrade to OkHttp 3.
