### ISSUE TITLE
Fatal Exception: java.lang.IllegalArgumentException: byteCount < 0: -1512

### ISSUE THREAD

**Issue by neerajshrivastav** [square/okhttp#3104]
Hi,

We are seeing the number increasing continuously for this crash in fabric. 

The crash is seen in android OS versions 5.0(~72% times), 5.0.1(~4 %) and 5.0.2(~23%) .

Crash log

Fatal Exception: java.lang.IllegalArgumentException: byteCount < 0: -1512
       at com.android.okio.RealBufferedSource.read(RealBufferedSource.java:44)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:442)
       at com.android.okhttp.internal.Util.skipAll(Util.java:227)
       at com.android.okhttp.internal.http.HttpConnection.discard(HttpConnection.java:212)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:464)
       at com.android.okhttp.internal.Util.closeQuietly(Util.java:97)
       at com.android.okhttp.internal.http.HttpEngine.close(HttpEngine.java:439)
       at com.android.okhttp.internal.http.HttpURLConnectionImpl.disconnect(HttpURLConnectionImpl.java:113)
       at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.disconnect(DelegatingHttpsURLConnection.java:93)
       at com.android.okhttp.internal.http.HttpsURLConnectionImpl.disconnect(HttpsURLConnectionImpl.java:25)
       at com.facebook.ads.internal.e.b.h.b(Unknown Source)
       at com.facebook.ads.internal.e.b.k.h(Unknown Source)

Please help with the solution.

**Comment by swankjesse** [comment]
Unfortunately `com.android.okhttp` is the version of OkHttp that ships with the device. We’re unable to ship updates to it. If you want a fix, consider using `okhttp-urlconnection` like so:

```
   OkHttpClient okHttpClient = new OkHttpClient();
   URL.setURLStreamHandlerFactory(new OkUrlFactory(okHttpClient));
 ```
