### ISSUE TITLE
Android init crash after add cache in some devices.

### ISSUE THREAD

**Issue by SethFeng** [square/okhttp#3115]
Crash stack:
```
OkHttp Dispatcher
java.lang.IllegalStateException
cache is closed
okhttp3.internal.DiskLruCache.void checkNotClosed()(SourceFile:644)
okhttp3.internal.DiskLruCache.okhttp3.internal.DiskLruCache$Editor edit(java.lang.String,long)(SourceFile:458)
okhttp3.internal.DiskLruCache.okhttp3.internal.DiskLruCache$Editor edit(java.lang.String)(SourceFile:452)
okhttp3.Cache.okhttp3.internal.http.CacheRequest put(okhttp3.Response)(SourceFile:244)
okhttp3.Cache.access$000(SourceFile:135)
okhttp3.Cache$1.okhttp3.internal.http.CacheRequest put(okhttp3.Response)(SourceFile:147)
okhttp3.internal.http.HttpEngine.void maybeCache()(SourceFile:438)
okhttp3.internal.http.HttpEngine.void readResponse()(SourceFile:683)
okhttp3.RealCall.okhttp3.Response getResponse(okhttp3.Request,boolean)(SourceFile:244)
okhttp3.RealCall$ApplicationInterceptorChain.okhttp3.Response proceed(okhttp3.Request)(SourceFile:201)
okhttp3.logging.HttpLoggingInterceptor.okhttp3.Response intercept(okhttp3.Interceptor$Chain)(SourceFile:212)
okhttp3.RealCall$ApplicationInterceptorChain.okhttp3.Response proceed(okhttp3.Request)(SourceFile:190)
okhttp3.RealCall.okhttp3.Response getResponseWithInterceptorChain(boolean)(SourceFile:163)
okhttp3.RealCall.access$100(SourceFile:30)
okhttp3.RealCall$AsyncCall.void execute()(SourceFile:127)
okhttp3.internal.NamedRunnable.void run()(SourceFile:32)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
java.lang.Thread.run(Thread.java:818)
```

log(may be useful):
```
12-02 09:04:15.277 10212 10257 W OkHttp : DiskLruCache /data/user/0/com.aa.bb/cache is corrupt: failed to delete /data/user/0/com.aa.bb/cache/38ad70faeb69ed8ed8a31df00aefae8b.0, removing
12-02 09:04:15.278 10212 10257 W OkHttp : java.io.IOException: failed to delete /data/user/0/com.aa.bb/cache/38ad70faeb69ed8ed8a31df00aefae8b.0
12-02 09:04:15.278 10212 10257 W OkHttp : at okhttp3.internal.io.FileSystem$1.delete(SourceFile:70)
12-02 09:04:15.278 10212 10257 W OkHttp : at okhttp3.internal.DiskLruCache.processJournal(SourceFile:372)
12-02 09:04:15.278 10212 10257 W OkHttp : at okhttp3.internal.DiskLruCache.initialize(SourceFile:228)
12-02 09:04:15.278 10212 10257 W OkHttp : at okhttp3.internal.DiskLruCache.get(SourceFile:429)
12-02 09:04:15.278 10212 10257 W OkHttp : at okhttp3.Cache.get(SourceFile:193)
12-02 09:04:15.278 10212 10257 W OkHttp : at okhttp3.Cache$1.get(SourceFile:143)
12-02 09:04:15.278 10212 10257 W OkHttp : at okhttp3.internal.http.HttpEngine.sendRequest(SourceFile:203)
12-02 09:04:15.278 10212 10257 W OkHttp : at okhttp3.RealCall.getResponse(SourceFile:243)
12-02 09:04:15.278 10212 10257 W OkHttp : at okhttp3.RealCall$ApplicationInterceptorChain.proceed(SourceFile:201)
12-02 09:04:15.278 10212 10257 W OkHttp : at okhttp3.logging.HttpLoggingInterceptor.intercept(SourceFile:212)
12-02 09:04:15.278 10212 10257 W OkHttp : at okhttp3.RealCall$ApplicationInterceptorChain.proceed(SourceFile:190)
12-02 09:04:15.278 10212 10257 W OkHttp : at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:163)
12-02 09:04:15.278 10212 10257 W OkHttp : at okhttp3.RealCall.access$100(SourceFile:30)
12-02 09:04:15.278 10212 10257 W OkHttp : at okhttp3.RealCall$AsyncCall.execute(SourceFile:127)
12-02 09:04:15.278 10212 10257 W OkHttp : at okhttp3.internal.NamedRunnable.run(SourceFile:32)
12-02 09:04:15.278 10212 10257 W OkHttp : at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
12-02 09:04:15.278 10212 10257 W OkHttp : at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
12-02 09:04:15.278 10212 10257 W OkHttp : at java.lang.Thread.run(Thread.java:818)
```

With OkHttp v3.3.1.

**Comment by swankjesse** [comment]
Can you provide some tips to reproduce? Not much actionable here.

**Comment by SethFeng** [comment]
Crash logs is uploaded by user device. Once I open okhttp cache in my app's new version, these crash comes.

**Comment by dave-r12** [comment]
I think I spotted a possible culprit - if the first initialization fails from a faulty filesystem, the closed field may get set to true.
