### ISSUE TITLE
[bug report] ANR 

### ISSUE THREAD

**Issue by dahutiger** [square/okhttp#3116]
java.lang.InternalError: Thread starting during runtime shutdown
	at java.lang.Thread.nativeCreate(Native Method)
	at java.lang.Thread.start(Thread.java:1063)
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:921)
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1328)
	at okhttp3.internal.ws.RealWebSocket$1.onClose(SourceFile:82)
	at okhttp3.internal.ws.WebSocketReader.readControlFrame(SourceFile:205)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(SourceFile:106)
	at okhttp3.internal.ws.RealWebSocket.readMessage(SourceFile:97)
	at okhttp3.ws.WebSocketCall.createWebSocket(SourceFile:152)
	at okhttp3.ws.WebSocketCall.access$000(SourceFile:41)
	at okhttp3.ws.WebSocketCall$1.onResponse(SourceFile:97)
	at okhttp3.RealCall$AsyncCall.execute(SourceFile:126)
	at okhttp3.internal.NamedRunnable.run(SourceFile:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by swankjesse** [comment]
Not much we can do here unfortunately. We can’t not create threads. Can you tear down OkHttp before shutting down your JVM?

**Comment by dahutiger** [comment]
I saw this exception on my statistics platform.so,I don't know the user's operation.I thought the user maybe kills app when OkHttp initiates a network request?

**Comment by swankjesse** [comment]
No action for us to take on this.
