### ISSUE TITLE
Network on Main Thread

### ISSUE THREAD

**Issue by DavidEdwards** [square/okhttp#3145]
## The issue

My issue is extremely intermittent. It does not appear every time. Infact, only quite rarely. Perhaps a couple of times per week.

In the first step, you see that I am directly starting a new Thread for running my blocking function in. 

In the last step, I even check that the Thread is not running on the Main Thread.

Could okhttp be pushing the request onto the Main Thread?

## My Exception

```
01-31 09:29:58.459 15392-15814/dae.evepi E/UncaughtException: android.os.NetworkOnMainThreadException
	  at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1303)
	  at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:300)
	  at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:808)
	  at okio.Okio$1.write(SourceFile:78)
	  at okio.AsyncTimeout$1.write(SourceFile:179)
	  at okio.RealBufferedSink.flush(SourceFile:216)
	  at okhttp3.internal.http2.Http2Writer.flush(SourceFile:121)
	  at okhttp3.internal.http2.Http2Connection.newStream(SourceFile:239)
	  at okhttp3.internal.http2.Http2Connection.newStream(SourceFile:205)
	  at okhttp3.internal.http2.Http2Codec.writeRequestHeaders(SourceFile:105)
	  at okhttp3.internal.http.CallServerInterceptor.intercept(SourceFile:43)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
	  at dae.evepi.network.LoggingInterceptor.intercept(SourceFile:20) /* duplicate of your LoggingInterceptor recipe */
	  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	  at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:45)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
	  at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:93)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
	  at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:120)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
	  at okhttp3.RealCall.b(SourceFile:179)
	  at okhttp3.RealCall.execute(SourceFile:63)
	  at dae.evepi.network.Api.a(SourceFile:188)
	  at dae.evepi.network.Api.getPlanetLayoutBlocking(SourceFile:713)
	  at dae.evepi.network.Api$7.run(SourceFile:753)
	  at java.lang.Thread.run(Thread.java:761)
```

## My code

```
	// at dae.evepi.network.Api$7.run(SourceFile:753)
    public void getPlanetLayout(@NonNull final Character c, @NonNull final Planet p, @NonNull final PinCallback callback) {
        new Thread(new Runnable() {
            @Override
            public void run() {
                getPlanetLayoutBlocking(c, p, callback);
            }
        }).start();
    }
```

```
	// at dae.evepi.network.Api.getPlanetLayoutBlocking(SourceFile:713)
    @WorkerThread
    @Nullable
    public List<Pin> getPlanetLayoutBlocking(@NonNull final Character c, @NonNull final Planet p, @NonNull final PinCallback callback) {
        final String CACHE_KEY = "Api.getPlanetLayout(Character="+c.getId()+",Planet="+p.getId()+",PinCallback)";
        if(isCached(CACHE_KEY)) {
            LogUtils.log("W::Planet pins are cached. Don't refresh.");
            EventBus.getDefault().post(new EsiCacheEvent(getCacheExpireTime(CACHE_KEY)));
            return null;
        }

        Response response = null;

        try {
            Request request = new Request.Builder()
                    .url(String.format(Locale.US, AN_API_CALL, c.getId(), p.getId()))
                    .header("User-Agent", USER_AGENT)
                    .header("Authorization", "...")
                    .header("Host", "...")
                    .build();
            response = retryWithBackoff(request);

            if(response != null && response.code() == 200) {
                // Some stuff
            } else {
                // Some other stuff
            }
        } catch (MalformedURLException e) {
            LogUtils.log("E::e: "+e);
            e.printStackTrace();
            callback.onError(response, e);
        } catch (IOException e) {
            LogUtils.log("E::e: "+e);
            e.printStackTrace();
            callback.onError(response, e);
        } catch (JSONException e) {
            LogUtils.log("E::e: "+e);
            e.printStackTrace();
            callback.onError(response, e);
        }
        return null;
    }
```
	
```
	// at dae.evepi.network.Api.a(SourceFile:188)
    @WorkerThread
    @Nullable
    private Response retryWithBackoff(@NonNull Request request) throws IOException {
        Response response = null;

        int retryAttempt = 0;
        int backoffTime = 500;

        while(++retryAttempt <= MAX_RETRIES) {
            if(retryAttempt > 1) {
                LogUtils.log("W::There was an error accessing the API. We will try again in "+backoffTime+"ms");
                Utils.sleep(backoffTime); /* just a wrapped Thread.sleep(...); */
                backoffTime *= RETRY_DEPLAY_MULTIPLIER;
            }

            try {
                // This if block is never entered
                if(Looper.myLooper() == Looper.getMainLooper()) {
                    LogUtils.log("CRIT", "WTF::Attempting to call '"+request.url().toString()+"' on the main thread ("+retryAttempt+"/"+MAX_RETRIES+").");
                    LogUtils.logCaller("Trace critical error of network on main thread.");
                }

                response = mClient.newCall(request).execute();

                if (response.code() == 200) {
                    break;
                }
            } catch (SocketTimeoutException e) {
                LogUtils.log("E::Socket request timed out for '"+request.url().toString()+"'");
            }
        }

        return response;
    }
```

**Comment by swankjesse** [comment]
I’ve never seen that before. That's a bug in strict mode. Can you reproduce locally? Which devices does this impact?

**Comment by DavidEdwards** [comment]
I cannot reproduce it. It just "happens" sometimes. Usually when starting the App.

It has happened to me specifically on a Pixel (7.1.1).

So this is a bug I should forward to the AOSP team?

**Comment by swankjesse** [comment]
Yup. It's their bug.

**Comment by DavidEdwards** [comment]
OK, thanks for taking the time to look at it!

**Comment by swankjesse** [comment]
Actually I'm wrong. It's a Conscrypt bug. 
FYI @kruton

**Comment by DavidEdwards** [comment]
OK, I will make an issue report there.

**Comment by swankjesse** [comment]
Ugh, I keep following the stacktrace and implicating the wrong code.

How are you installing strict mode? Basically it looks like the background thread is getting a strict mode that forbids network I/O, which is typically a thing you only restrict on the main thread.

**Comment by swankjesse** [comment]
(the exception message is a bit distracting, to be pedantic it means `NetworkOnForbiddenThread` because the policy doesn’t actually know or care about the main thread’s special status.)

**Comment by DavidEdwards** [comment]
I am setting StrictMode in the onCreate() method of my Application class.

```
    @Override
    public void onCreate() {
        super.onCreate();
        Fabric.with(this, new Crashlytics());

        if (BuildConfig.APP_DEBUG) {
            StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
                    .detectDiskReads()
                    .detectDiskWrites()
                    .detectNetwork()   // or .detectAll() for all detectable problems
                    .penaltyLog()
                    .build());
            StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                    .detectLeakedSqlLiteObjects()
                    .detectLeakedClosableObjects()
                    .penaltyLog()
//                    .penaltyDeath()
                    .build());
        }
    }
```

**Comment by DavidEdwards** [comment]
However, I thought that this StrictMode check is built into Nougat? Not as part of initializing StrictMode myself.

**Comment by swankjesse** [comment]
From the trace of the exception it looks like a network policy is enabled for your background thread.

**Comment by DavidEdwards** [comment]
Searched my code and found another place I use StrictMode:

```
oldThreadPolicy = StrictMode.getThreadPolicy();
oldVmPolicy = StrictMode.getVmPolicy();
StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
		.permitAll()
		.build());
StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
		.build());
		
// Working on preferences.

StrictMode.setThreadPolicy(oldThreadPolicy);
StrictMode.setVmPolicy(oldVmPolicy);
```

Used in a library to avoid causing StrictMode logs from accessing SharedPreferences. That could be called from a background thread.

However, it would only set permissive and reset back to original policies.

**Comment by swankjesse** [comment]
I'm lost. Can you set up a breakpoint and inspect which policy it’s using when it fails? I’m specifically interested in whether it’s a policy you installed and whether it's the same policy instance as you’re using on the main thread.

**Comment by DavidEdwards** [comment]
Unfortunately, I have no way of testing that. I have no way to cause the error. I will do some testing, perhaps I can trigger the error with the above StrictMode code.

In any case, it isn't an okhttp issue, so I'll stop posting here about it! However, if you are curious to the resolution of it, I can post it here once I have it figured out. Let me know.

**Comment by swankjesse** [comment]
Yes, I'm quite curious!

**Comment by DavidEdwards** [comment]
After removing this code, I am not having any more issues.

The issue seems to stem from my fiddling of StrictMode around retrieving SharedPreferences. 

In the below code, I am reading from SharedPreferences. However, I am also running in StrictMode and I didn't want StrictMode to remind me about opening SharedPreferences on the UI Thread. 

Editing the StrictMode settings at runtime seemed to cause this issue.

```
private Semaphore policyLock = new Semaphore(1);
private StrictMode.ThreadPolicy oldThreadPolicy;
private StrictMode.VmPolicy oldVmPolicy;

public boolean getPref(@NonNull Context context, @NonNull String key, boolean defaultValue) {
	pausePolicy();
	try {
		SharedPreferences sharedPreferences = context.getSharedPreferences(GLOBAL_PREFERENCES, Context.MODE_PRIVATE);
		return sharedPreferences.getBoolean(key, defaultValue);
	} finally {
		resumePolicy();
	}
}

private void pausePolicy() {
	try {
		policyLock.acquire();
	} catch (InterruptedException e) {
		Utils.log("E::"+e.toString());
	}

	oldThreadPolicy = StrictMode.getThreadPolicy();
	oldVmPolicy = StrictMode.getVmPolicy();
	StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
			.permitAll()
			.build());
	StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
			.build());
}

private void resumePolicy() {
	policyLock.release();

	StrictMode.setThreadPolicy(oldThreadPolicy);
	StrictMode.setVmPolicy(oldVmPolicy);
}
```

**Comment by kruton** [comment]
I don't think you want to use a `Semaphore` here. In this particular case, I see no reason why two local variables holding the thread and VM policy can't be used. This method doesn't seem to be re-entrant because you'd have a deadlock already.

If this method is called from multiple threads simultaneously (i.e., main thread and other background threads) the `pausePolicy` method will continue on if it receives `InterruptedException` which could create a situation where two threads are writing to the fields for the old policies simultaneously. If multiple threads manage to get past `acquire()`, then `Semaphore` will let whichever thread finishes first call `policyLock.release()` even if it wasn't the thread that successfully called `policyLock.acquire()`.

So image thread A and thread B both simultaneously call into this method. Thread A successfully calls `acquire()`, thread B calls `acquire()` but it gets `InterruptedException` in the middle, thread B completes the write, thread B calls `release()`, thread C successfully calls `acquire()`, thread A finishes and calls `release()`, thread D successfully calls `acquire()`, ad naseum.

**Comment by rusmichal** [comment]
Hey, I have the same problem with my UI test. Please take a look:

http://stackoverflow.com/questions/42393136/test-running-failed-instrumentation-run-failed-due-to-android-os-networkonmain
