### ISSUE TITLE
java.lang.IllegalStateException: closed

### ISSUE THREAD

**Issue by boyfox** [square/okhttp#3190]
`java.lang.IllegalStateException: closed
	at okio.RealBufferedSource.request(RealBufferedSource.java:64)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:238)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
	at okhttp3.RealCall.execute(RealCall.java:63)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
	at retrofit2.ExecutorCallAdapterFactory$ExecutorCallbackCall.execute(ExecutorCallAdapterFactory.java:89)
	at com.takeal.stm.fragments.authregpages.AuthPage$4.run(AuthPage.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)`

**Comment by swankjesse** [comment]
Mind providing a test case to reproduce the problem?

**Comment by boyfox** [comment]
hi @swankjesse, reproducing this error easy, this problem will be appear when working with retrofit library. For example : need create response with model - 

`Response<UserResp> resp = ...`

if server will be return error with 404 status code and response content will not matched with model then will be this error

**Comment by swankjesse** [comment]
Could you provide a standalone test case for the problem? My guess is you have a bad interceptor that’s consuming the response body when it isn’t supposed to.

**Comment by boyfox** [comment]
This is dependency:

    compile 'com.squareup.retrofit2:retrofit:2.2.0'
    compile 'com.squareup.retrofit2:converter-gson:2.2.0'
    compile 'com.squareup.okhttp3:logging-interceptor:3.5.0'

and this is interceptor code:

        HttpLoggingInterceptor hli = new HttpLoggingInterceptor();
        hli.setLevel(HttpLoggingInterceptor.Level.BODY);

        OkHttpClient mHttpClient = new OkHttpClient.Builder()
        .readTimeout(20, TimeUnit.SECONDS)
        .connectTimeout(20, TimeUnit.SECONDS)
        .writeTimeout(20, TimeUnit.SECONDS)
        .addInterceptor(hli)
        .addInterceptor(new LoginInterseptor())
        .build();

**Comment by swankjesse** [comment]
Does it work without LoginIncerseptor ?

**Comment by boyfox** [comment]
Oy, Thank you @swankjesse , yes works!!! yes this is my mistake, my login interseptor is wrong. Thank you for helping and great library!

**Comment by boyfox** [comment]
you can close this issue
