### ISSUE TITLE
NoClassDefFoundError: org.objenesis.ObjenesisStd

### ISSUE THREAD

**Issue by christopherperry** [square/okhttp#3198]
Including:

```groovy
androidTestCompile 'com.squareup.okhttp3:mockwebserver:3.6.0'
```

in my project's `build.gradle` file and running on a device above Android API v19 works fine. However, when I try to run my tests on an API v19 device I get:

```
java.lang.NoClassDefFoundError: org.objenesis.ObjenesisStd
  at org.mockito.internal.creation.jmock.ClassImposterizer.<init>(ClassImposterizer.java:36)
  at org.mockito.internal.creation.jmock.ClassImposterizer.<clinit>(ClassImposterizer.java:29)
  at org.mockito.internal.util.MockCreationValidator.isTypeMockable(MockCreationValidator.java:17)
  at org.mockito.internal.util.MockCreationValidator.validateType(MockCreationValidator.java:21)
  at org.mockito.internal.creation.MockSettingsImpl.validatedSettings(MockSettingsImpl.java:133)
  at org.mockito.internal.creation.MockSettingsImpl.confirm(MockSettingsImpl.java:127)
  at org.mockito.internal.MockitoCore.mock(MockitoCore.java:50)
  at org.mockito.Mockito.mock(Mockito.java:1243)
  at org.mockito.Mockito.mock(Mockito.java:1120)
```

I'm also including the dexmaker-mockito since the app is multi-dex. I suspect it's something to do with that, but I'm at a loss. I'm hoping you guys have seen this before and have a workaround, this way if somebody else runs into this they don't have to spend an entire day trying to resolve it.

**Comment by swankjesse** [comment]
Might be a better question for StackOverflow.

**Comment by christopherperry** [comment]
Thanks @swankjesse I tried that and got crickets.

**Comment by swankjesse** [comment]
I don’t think there’s any action for us to take on this.
