### ISSUE TITLE
java.lang.VerifyError: Lokhttp3/Headers;

### ISSUE THREAD

**Issue by 5830327wy** [square/okhttp#3199]
【issues】
many Android devices reported the following error

【os】
Most of them are Android 4.4.x

【version】
okhttp 3.4.2

java.lang.VerifyError: Lokhttp3/Address;
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.createAddress(RetryAndFollowUpInterceptor.java)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java)
	at okhttp3.RealCall.execute(RealCall.java)
	at com.bill99.kuaiqian.framework.core.network.volley.toolbox.OkHttpClientStack.createRequestBody(OkHttpClientStack.java)
	                                                                               performRequest(OkHttpClientStack.java)
	at com.bill99.kuaiqian.framework.core.network.volley.toolbox.BasicNetwork.attemptRetryOnException(BasicNetwork.java)
	                                                                          convertHeaders(BasicNetwork.java)
	                                                                          performRequest(BasicNetwork.java)
	                                                                          entityToBytes(BasicNetwork.java)
	at com.bill99.kuaiqian.framework.core.network.volley.NetworkDispatcher.run(NetworkDispatcher.java)

-------------------------------------------------------------------------------------------------
java.lang.VerifyError: Lokhttp3/Headers;
	at okhttp3.Headers.get(Headers.java)
	at okhttp3.Request.header(Request.java)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java)
	at okhttp3.RealCall.execute(RealCall.java)
	at com.bill99.kuaiqian.framework.core.network.volley.toolbox.OkHttpClientStack.createRequestBody(OkHttpClientStack.java)
	                                                                               performRequest(OkHttpClientStack.java)
	at com.bill99.kuaiqian.framework.core.network.volley.toolbox.BasicNetwork.attemptRetryOnException(BasicNetwork.java)
	                                                                          convertHeaders(BasicNetwork.java)
	                                                                          performRequest(BasicNetwork.java)
	                                                                          entityToBytes(BasicNetwork.java)
	at com.bill99.kuaiqian.framework.core.network.volley.NetworkDispatcher.run(NetworkDispatcher.java)

-------------------------------------------------------------------------------------------------
java.lang.VerifyError: Lokhttp3/Response;
	at okhttp3.Response$Builder.build(Response.java)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java)
	at okhttp3.RealCall.execute(RealCall.java)
	at com.bill99.kuaiqian.framework.core.statistics.network.StatNetworkUtil.initKeyStore(StatNetworkUtil.java)
	                                                                         post(StatNetworkUtil.java)
	                                                                         loge(StatNetworkUtil.java)
	at com.bill99.kuaiqian.framework.core.statistics.common.UploadHistoryLog.uploadFileAndDelete(UploadHistoryLog.java)
	                                                                                    UploadHistoryLog.java)
	at com.bill99.kuaiqian.framework.core.statistics.common.UploadHistoryLog.uploadFileAndDelete(UploadHistoryLog.java)
	                                                                                    UploadHistoryLog.java)
	at com.bill99.kuaiqian.framework.core.statistics.Stat$2.run(Stat.java)
	at android.os.Handler.handleCallback(Handler.java:808)
	at android.os.Handler.dispatchMessage(Handler.java:103)
	at android.os.Looper.loop(Looper.java:195)
	at android.os.HandlerThread.run(HandlerThread.java:61)

**Comment by swankjesse** [comment]
Which devices & Android versions?

**Comment by 5830327wy** [comment]
Android 4.4.x

**Comment by 5830327wy** [comment]
Android versions: Android 4.4.x
devices: xiaomi M1、best_sonny_lt416、yepen、eton i95、bird l9
I find most of theme are  YunOs, also happened MIUI

**Comment by swankjesse** [comment]
I don’t think there’s any action we can take on this. Please consider reporting the problem to the device makers, I think this is likely a problem in their devices.
