### ISSUE TITLE
FATAL EXCEPTION:  okhttp3.internal.connection.RealConnection.connectSocket

### ISSUE THREAD

**Issue by nextdimension** [square/okhttp#3201]
okhttp3:okhttp:3.6.0

I am making a single call with retrofit, which works fine, until the server is unreachable(offline), then my application crashes.

FATAL EXCEPTION: main java.net.ConnectException: Failed to connect  okhttp3.internal.connection.RealConnection.connectSocket

` FATAL EXCEPTION: main
                                                              Process: ***********
                                                              java.net.ConnectException: Failed to connect /192.168.0.2:8080
                                                                  at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:222)
                                                                  at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:146)
                                                                  at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)
                                                                  at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
                                                                  at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
                                                                  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
                                                                  at okhttp3.RealCall.execute(RealCall.java:63)
                                                                  at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
                                                                  at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
                                                                  at io.reactivex.Observable.subscribe(Observable.java:10514)
                                                                  at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39)
                                                                  at io.reactivex.Scheduler$1.run(Scheduler.java:134)
                                                                  at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59)
                                                                  at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51)
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                  at java.lang.Thread.run(Thread.java:818)
                                                               Caused by: java.net.ConnectException: failed to connect to /127.0.0.1 (port 8080) after 10000ms: isConnected failed: ECONNREFUSED (Connection refused)
                                                                  at libcore.io.IoBridge.isConnected(IoBridge.java:234)
                                                                  at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
                                                                  at libcore.io.IoBridge.connect(IoBridge.java:122)
                                                                  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
                                                                  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
                                                                  at java.net.Socket.connect(Socket.java:884)
                                                                  at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:63)
                                                                  at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:220)
                                                                  at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:146) 
                                                                  at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186) 
                                                                  at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121) 
                                                                  at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100) 
                                                                  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) 
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) 
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179) 
                                                                  at okhttp3.RealCall.execute(RealCall.java:63) 
                                                                  at retrofit2.OkHttpCall.execute(OkHttpCall.java:174) 
                                                                  at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41) 
                                                                  at io.reactivex.Observable.subscribe(Observable.java:10514) 
                                                                  at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39) 
                                                                  at io.reactivex.Scheduler$1.run(Scheduler.java:134) 
                                                                  at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59) 
                                                                  at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51) 
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                  at java.lang.Thread.run(Thread.java:818) 
                                                               Caused by: android.system.ErrnoException: isConnected failed: ECONNREFUSED (Connection refused)
                                                                  at libcore.io.IoBridge.isConnected(IoBridge.java:223)
                                                                  at libcore.io.IoBridge.connectErrno(IoBridge.java:171) 
                                                                  at libcore.io.IoBridge.connect(IoBridge.java:122) 
                                                                  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183) 
                                                                  at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452) 
                                                                  at java.net.Socket.connect(Socket.java:884) 
                                                                  at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:63) 
                                                                  at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:220) 
                                                                  at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:146) 
                                                                  at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186) 
                                                                  at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121) 
                                                                  at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100) 
                                                                  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) 
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) 
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179) 
                                                                  at okhttp3.RealCall.execute(RealCall.java:63) 
                                                                  at retrofit2.OkHttpCall.execute(OkHttpCall.java:174) 
                                                                  at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41) 
                                                                  at io.reactivex.Observable.subscribe(Observable.java:10514) 
                                                                  at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(ObservableSubscribeOn.java:39) 
                                                                  at io.reactivex.Scheduler$1.run(Scheduler.java:134) 
                                                                  at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:59) 
                                                                  at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:51) 
                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                  at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269) 
                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                  at java.lang.Thread.run(Thread.java:818) 
`

**Comment by nextdimension** [comment]
ignore - User error
