### ISSUE TITLE
Attempt to invoke virtual method 'void java.util.Calendar.setLenient(boolean)' on a null object reference

### ISSUE THREAD

**Issue by isanwenyu** [square/okhttp#3221]
It happened in version 3.1.2.
```
java.lang.NullPointerException: Attempt to invoke virtual method 'void java.util.Calendar.setLenient(boolean)' on a null object reference
	at java.text.DateFormat.setLenient(DateFormat.java:659)
	at okhttp3.internal.http.HttpDate$1.initialValue(HttpDate.java:42)
	at okhttp3.internal.http.HttpDate$1.initialValue(HttpDate.java:38)
	at java.lang.ThreadLocal$Values.getAfterMiss(ThreadLocal.java:430)
	at java.lang.ThreadLocal.get(ThreadLocal.java:65)
	at okhttp3.internal.http.HttpDate.format(HttpDate.java:114)
	at okhttp3.Cookie.toString(Cookie.java:542)
```

When i configured `cookieJar` overriding `loadForRequest` method  to print cookie using `item.toString()` , it happended.

My code:

```
        mOkHttpClient = new OkHttpClient.Builder()
                .connectTimeout(CONNECT_TIMIE_OUT, TimeUnit.SECONDS)
                .writeTimeout(WRITE_TIME_OUT, TimeUnit.SECONDS)
                .readTimeout(READ_TIME_OUT, TimeUnit.SECONDS)
                .cookieJar(new CookieJar() {
                    private final PersistentCookieStore cookieStore = new PersistentCookieStore(AppContext.getInstance());

                    @Override
                    public void saveFromResponse(HttpUrl url, List<Cookie> cookies) {
                        if (cookies != null && cookies.size() > 0) {
                            LogUtil.d(TAG, "saveCookie:");
                            for (Cookie item : cookies) {
                                cookieStore.add(url, item);
                                if (item != null) {
                                    LogUtil.d(TAG, "cookie:" + item.toString());
                                }
                            }
                        }
                    }

                    @Override
                    public List<Cookie> loadForRequest(HttpUrl url) {
                        LogUtil.d(TAG, "loadCookie:");
                        List<Cookie> cookies = cookieStore.get(url);
                        for (Cookie item : cookies) {
                            if (item != null) {
                                LogUtil.d(TAG, "cookie:" + item.toString());
                            }
                        }
                        return cookies;
                    }
                })
                .build();
```

**Comment by swankjesse** [comment]
Seems impossible. Which JVM or device did this occur on? Can you reproduce it consistently?

**Comment by isanwenyu** [comment]
I can't reproduce it because it is a third-party platform statistics. 
The device is  HuaiWei P8ALE-TL00 running Android 6.0 ROM.

**Comment by swankjesse** [comment]
If you can help to reproduce, we can fix. Otherwise this is not actionable.
