### ISSUE TITLE
Null pointer exception Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.mkdirs()' on a null object reference

### ISSUE THREAD

**Issue by suhaibroomy** [square/okhttp#3236]
Random crash on first request from retrofit

Non-fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.io.File.mkdirs()' on a null object reference
       at okhttp3.internal.io.FileSystem$1.sink(Unknown Source)
       at okhttp3.internal.cache.DiskLruCache.create$6dc183ad(Unknown Source)
       at okhttp3.internal.cache.DiskLruCache.initialize(Unknown Source)
       at okhttp3.internal.cache.DiskLruCache.create$6dc183ad(Unknown Source)
       at okhttp3.Cache.key(Unknown Source)
       at okhttp3.Cache$1.get(Unknown Source)
       at okhttp3.internal.cache.CacheInterceptor.intercept(Unknown Source)
       at okhttp3.internal.http.RealInterceptorChain.request(Unknown Source)
       at okhttp3.internal.http.RealInterceptorChain.request(Unknown Source)
       at okhttp3.internal.http.BridgeInterceptor.intercept(Unknown Source)
       at okhttp3.internal.http.RealInterceptorChain.request(Unknown Source)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(Unknown Source)
       at okhttp3.internal.http.RealInterceptorChain.request(Unknown Source)
       at okhttp3.internal.http.RealInterceptorChain.request(Unknown Source)
       at okhttp3.RealCall.getResponseWithInterceptorChain(Unknown Source)
       at okhttp3.RealCall$AsyncCall.execute(Unknown Source)
       at okhttp3.internal.NamedRunnable.run(Unknown Source)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

**Comment by swankjesse** [comment]
Could you provide an executable test case?

**Comment by lzyang187** [comment]
在Smartisan SM919（锤子M1L）这款型号的手机上出现，test url为"https:www.baidu.com"，get请求方式。
换个小米手机正常请求！
