### ISSUE TITLE
setBodyDelay() throws java.net.ProtocolException: unexpected end of stream

### ISSUE THREAD

**Issue by prabintim** [square/okhttp#3256]
I am testing how my app reacts to slow network connection using setBodyDelay().

**Input:**
```
mockedServer.enqueue(new MockResponse()
.setBody(getStringFromFile("login/token_granttype_password.json"))
.setBodyDelay(3, TimeUnit.SECONDS));
```

**Output:**

```
java.net.ProtocolException: unexpected end of stream
                                                                   at okhttp3.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:380)
                                                                   at okio.RealBufferedSource.read(RealBufferedSource.java:45)
                                                                   at okio.ForwardingSource.read(ForwardingSource.java:35)
                                                                   at retrofit2.OkHttpCall$ExceptionCatchingRequestBody$1.read(OkHttpCall.java:279)
                                                                   at okio.RealBufferedSource$1.read(RealBufferedSource.java:409)
                                                                   at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:287)
                                                                   at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:350)
                                                                   at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:179)
                                                                   at java.io.InputStreamReader.read(InputStreamReader.java:184)
                                                                   at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1287)
                                                                   at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1325)
                                                                   at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:549)
                                                                   at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
                                                                   at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:205)
                                                                   at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
                                                                   at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
                                                                   at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:117)
                                                                   at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:211)
                                                                   at retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
                                                                   at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(RxJavaCallAdapterFactory.java:171)
                                                                   at rx.internal.operators.OperatorSubscribeOn$1$1$1$1.call(OperatorSubscribeOn.java:85)
                                                                   at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:228)
                                                                   at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
                                                                   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
                                                                   at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
                                                                   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                   at java.lang.Thread.run(Thread.java:761)
```

**Documentation for setBodyDelay() reads:**
Set the delayed time of the response body to {@code delay}. This applies to the response body
only; response headers are not affected.

**Should I be supplying some information in the response headers? If so what would be it?**

**One Response from SOF:**
That exception is thrown by FixedLengthInputStream when the expected number of bytes (usually set in the content-length header of the response) is larger than the actual data in the response. Check that the content-length header is correct. (If you're supplying your own value for the content length, make sure it is correct.)

**Thank you.**

**Comment by swankjesse** [comment]
Are you sure the body delay is what’s interfering here? As-is it seems like the body doesn’t have the number of bytes it promises.

**Comment by prabintim** [comment]
The problem has resolved itself and I still have no idea how and why.
