### ISSUE TITLE
Websocket EOFException message

### ISSUE THREAD

**Issue by Dean79000** [square/okhttp#3258]
WebSocket are successfully connected to server, but if retreive and/or send message, i get this exception in onFailure callback. If not (do nothing) socket is stable.

```
java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.java:59)
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:72)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:261)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:200)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

Gist to reproduce : https://gist.github.com/Dean79000/f4626dffa0e82374632ab2a57553dad1

Tested on Android and pure Java, with differents socket server services. (locally and on internet)
With OkHttp 3.6.0

**Comment by swankjesse** [comment]
It worked for me.

**Comment by swankjesse** [comment]
No action to take on this.

**Comment by zcgl** [comment]
change a url Address, test  like:    ws://echo.websocket.org
