### ISSUE TITLE
[Bug report] ClassNotFoundException: Didn't find class "okio.Buffer" on path in Android Studio

### ISSUE THREAD

**Issue by tianzry** [square/okhttp#3267]
I download the latest JAR okhttp-3.6.0 and Add As Library... in Android Studio, but it couldn't  work and caused a crash in my App.The following info is shown in logcat:

`D/Error: ERR: stack=java.lang.NoClassDefFoundError: Failed resolution of: Lokio/Buffer;
                                                                  at okhttp3.ResponseBody.create(ResponseBody.java:208)
                                                                  at okhttp3.internal.Util.<clinit>(Util.java:48)
                                                                  at okhttp3.internal.Util.immutableList(Util.java:187)
                                                                  at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:122)
                                                                  at cn.tianzry.testokhttp.MainActivity$2.run(MainActivity.java:36)
                                                                  at java.lang.Thread.run(Thread.java:818)
                                                               Caused by: java.lang.ClassNotFoundException: Didn't find class "okio.Buffer" on path: DexPathList[[dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-support-annotations-24.2.1_2d37e4eef202308d9b294755eef7576afdfb7090-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-okhttp-3.6.0_5a9bfb02fc187a16d7d7cf88bfa32576b498003d-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-internal_impl-24.2.1_bca349fe2f8127a89af1c087770b814e44c60584-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-internal_impl-24.2.1_959d9fc519dac27595514d7088e036717ddaedb7-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-internal_impl-24.2.1_7caabe8ff035cca0108b76704632921b715fc3b7-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-internal_impl-24.2.1_6d2aeb2d03578333a58d4fa6b09927b6a8b025d0-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-internal_impl-24.2.1_46e3f9d74ffe797d352033d0af4d38d9851c84fb-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-com.android.support-support-vector-drawable-24.2.1_93214438d9bffb70907acb8c15a741b6b1da10bf-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-com.android.support-support-v4-24.2.1_fbaa1300d900909276a2df52c5776e16e6beacd2-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-com.android.support-support-media-compat-24.2.1_bc8b09be4fb319d06485af0c6c1fa6e66a052cad-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-com.android.support-support-fragment-24.2.1_65af9964338c6472914e6b13330598b15c0f7063-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-com.android.support-support-core-utils-24.2.1_527c3aef224ecb5399e9e152486bcdb7704f0508-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-com.android.support-support-core-ui-24.2.1_86a36f0d6b45c0e1dc7c258ea93be8be8fcd1065-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-com.android.support-support-compat-24.2.1_fb67b54b2bb8d5c11dd1cbef271252dd3fbfab59-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-com.android.support-appcompat-v7-24.2.1_e6062f365e76965fdba2e85f060a074e0d3b3596-classes.dex", dex file "/data/data/cn.tianzry.testokhttp/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-24.2.1_b7203f4850a3041c24d746a2cd36f9559938a413-classes.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib, /vendor/lib, /syst`

**However, when I try another way to add library: 
`compile 'com.squareup.okhttp3:okhttp:3.6.0'`
it works.**

**Comment by swankjesse** [comment]
No action to take on this. Problems with your build system are unrelated to OkHttp.
