### ISSUE TITLE
java.nio.charset.UnsupportedCharsetException: gdk

### ISSUE THREAD

**Issue by KingPeng** [square/okhttp#3270]
java.nio.charset.UnsupportedCharsetException: gdk
	at java.nio.charset.Charset.forName(Charset.java:309)
	at okhttp3.MediaType.parse(MediaType.java)
	                     charset(MediaType.java)
	at okhttp3.ResponseBody.charset(ResponseBody.java)
	at okhttp3.ResponseBody.string(ResponseBody.java)
	at com.linkin.base.nhttp.http.HttpRequest.onFailure(HttpRequest.java)
	                                          onResponse(HttpRequest.java)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)

Now i use okhttp:3.6 and okio:1.11.0. 
Then i meet this exception. 
The request i ' m not setting header. 
But i use okhttp is no thi problem.
So how can I fix this ?

**Comment by swankjesse** [comment]
The response you’re receiving cannot be decoded as a string because `gdk` is not a supported charset. Consider asking the webserver’s administrator to encode using UTF-8 instead.

**Comment by KingPeng** [comment]
The webserver’s administrator tells me that he always use UTF-8 , without gdk.
This Expection is not usually happend,but it still.
How can i location this ?

**Comment by swankjesse** [comment]
Unsure what your next step is. Know which URL does this? Is it HTTPS? Otherwise maybe it's a man-in-the-middle attack?

**Comment by KingPeng** [comment]
I can't know which url does.
And only a little people meet this Expection.
This Expection is Okhttp3 catched, so I don't when it happend

**Comment by swankjesse** [comment]
No action for us to take on this. If you can provide a test case that demonstrates a bug, I'm happy to reopen this.
