### ISSUE TITLE
Problem with ping interval

### ISSUE THREAD

**Issue by snjeza** [square/okhttp#3297]
I have faced this issue while fixing https://issues.jboss.org/browse/CHE-180
Try the following example - https://gist.github.com/snjeza/5a7e5138148d4d90e8e844bafb0913b8. It is based on https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/WebSocketEcho.java)
The example uses a ping interval of 1000 ms and slows down the onMessage method. It will print:
```
java.io.IOException: closed
	at okhttp3.internal.ws.WebSocketWriter.writeControlFrameSynchronized(WebSocketWriter.java:123)
	at okhttp3.internal.ws.WebSocketWriter.writePing(WebSocketWriter.java:79)
	at okhttp3.internal.ws.RealWebSocket.writePingFrame(RealWebSocket.java:525)
	at okhttp3.internal.ws.RealWebSocket$PingRunnable.run(RealWebSocket.java:513)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:308)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:180)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:294)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
MESSAGE: Hello...
```

The Kubernetse client (https://github.com/fabric8io/kubernetes-client) uses a ping interval of 1000 ms by default and often throws the "Pipe broken" exception when JVM is loaded.

**Comment by swankjesse** [comment]
What behavior would you prefer?

**Comment by snjeza** [comment]
I have created a PR.

**Comment by swankjesse** [comment]
No action to take on this.
