### ISSUE TITLE
OutOfMemoryError in `RouteSelector`

### ISSUE THREAD

**Issue by zhiweiofli** [square/okhttp#3306]
catch a lot of OutOfMemoryError in `RouteSelector`
crash log like this:
```
java.lang.OutOfMemoryError
	at java.util.ArrayList.add(ArrayList.java:118)
	at com.square.okhttp3.internal.http.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:187)
	at com.square.okhttp3.internal.http.RouteSelector.a(RouteSelector.java:4150)
	at com.square.okhttp3.internal.http.StreamAllocation.findConnection(StreamAllocation.java:174)
	at com.square.okhttp3.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:127)
	at com.square.okhttp3.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
	at com.square.okhttp3.internal.http.HttpEngine.a(HttpEngine.java:10289)
	at com.square.okhttp3.RealCall.getResponse(RealCall.java:243)
	at com.square.okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
	at com.square.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
	at com.square.okhttp3.RealCall.execute(RealCall.java:57)
```

**Comment by swankjesse** [comment]
I’m curious – have you customized the Dns implementation? Which hostname are you hitting?

**Comment by changety** [comment]
@swankjesse  in my issue, a custom DNS implementation can leak the memory

**Comment by swankjesse** [comment]
No action to take on this.
