### ISSUE TITLE
java.lang.IllegalStateException: closed

### ISSUE THREAD

**Issue by JDEast1029** [square/okhttp#3319]
i get 
 FATAL EXCEPTION: OkHttp Dispatcher
                                                   Process: com.dyb_app, PID: 20703
                                                   java.lang.IllegalStateException: closed
                                                       at okio.RealBufferedSink.write(RealBufferedSink.java:39)
                                                       at okio.ForwardingSink.write(ForwardingSink.java:35)
                                                       at com.facebook.react.modules.network.ProgressRequestBody$1.write(ProgressRequestBody.java:58)
                                                       at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
                                                       at com.facebook.react.modules.network.ProgressRequestBody.writeTo(ProgressRequestBody.java:48)
                                                       at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:47)
                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:109)
                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:124)
                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:170)
                                                       at okhttp3.RealCall.access$100(RealCall.java:33)
                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:120)
                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                       at java.lang.Thread.run(Thread.java:818)

when i fetch the url

**Comment by swankjesse** [comment]
Could you provide an executable test case to reproduce the problem?

**Comment by JDEast1029** [comment]
I could not provide, it happens occasionally

**Comment by jaredsburrows** [comment]
@JDEast1029 Can you provide the code that you are using?

**Comment by alexstoyanov** [comment]
I am having the same issue ... happens occasionally. Any help would be appreciated.

**Comment by swankjesse** [comment]
@alexstoyanov which version? We fixed one of these in 3.9.0. If you're still seeing it on that version please open a new bug with a stack trace.

**Comment by vivelvlv** [comment]
@swankjesse  will you please help me to find out the solution? same problem https://github.com/square/okhttp/issues/3842
