### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'okio.BufferedSource okhttp3.ResponseBody.source()' on a null object reference

### ISSUE THREAD

**Issue by MissBears** [square/okhttp#3323]
java.lang.NullPointerException: Attempt to invoke virtual method 'okio.BufferedSource okhttp3.ResponseBody.source()' on a null object reference
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:103)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:124)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
	at okhttp3.RealCall.e(SourceFile:170)
	at okhttp3.RealCall.a(SourceFile:33)
	at okhttp3.RealCall$AsyncCall.execute(SourceFile:120)
	at okhttp3.internal.NamedRunnable.run(SourceFile:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)

my app accured this problem sometimes

**Comment by bartdkmediahuis** [comment]
Same here, but hard to reproduce, so it seems.
Any tips on how to solve this issue ?

**Comment by swankjesse** [comment]
Not sure. Can you help us to isolate the problem? Executable test case?
