### ISSUE TITLE
java.lang.InternalError: java.util.MissingResourceException

### ISSUE THREAD

**Issue by mengdd** [square/okhttp#3334]
There is such a crash reported from our app:

```
Caused by java.lang.InternalError: java.util.MissingResourceException: Can't find bundle for base name sun.util.logging.resources.logging, locale en_AU
       at java.util.logging.Logger$1.run(Logger.java:1385)
       at java.util.logging.Logger$1.run(Logger.java:1379)
       at java.security.AccessController.doPrivileged(AccessController.java:41)
       at java.util.logging.Logger.findSystemResourceBundle(Logger.java:1378)
       at java.util.logging.Logger.findResourceBundle(Logger.java:1425)
       at java.util.logging.Logger.setupResourceInfo(Logger.java:1523)
       at java.util.logging.Logger.(Logger.java)
       at java.util.logging.Logger.(Logger.java)
       at java.util.logging.LogManager$SystemLoggerContext.demandLogger(LogManager.java:734)
       at java.util.logging.LogManager.demandSystemLogger(LogManager.java:399)
       at java.util.logging.Logger.getPlatformLogger(Logger.java:474)
       at java.util.logging.LoggingProxyImpl.getLogger(LoggingProxyImpl.java:41)
       at sun.util.logging.LoggingSupport.getLogger(LoggingSupport.java:100)
       at sun.util.logging.PlatformLogger$JavaLoggerProxy.(PlatformLogger.java)
       at sun.util.logging.PlatformLogger$JavaLoggerProxy.(PlatformLogger.java)
       at sun.util.logging.PlatformLogger.(PlatformLogger.java)
       at sun.util.logging.PlatformLogger.getLogger(PlatformLogger.java:205)
       at java.net.CookieManager.put(CookieManager.java:262)
       at okhttp3.JavaNetCookieJar.saveFromResponse(SourceFile:47)
       at okhttp3.internal.http.HttpEngine.receiveHeaders(SourceFile:866)
       at okhttp3.internal.http.HttpEngine.readResponse(SourceFile:598)
       at okhttp3.RealCall.getResponse(SourceFile:241)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(SourceFile:198)
       at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:160)
       at okhttp3.RealCall.execute(SourceFile:57)
```
We are using okhttp v3.2.0.
And the configuration is looks like this:
```java
CookieHandler cookieHandler = new CookieManager(cookieStore, CookiePolicy.ACCEPT_ALL);
OkHttpClient.Builder okHttpBuilder = okHttpClient.newBuilder()
        .cache(cache)
        .cookieJar(new JavaNetCookieJar(cookieHandler))
        .connectTimeout(HTTP_TIMEOUT, TimeUnit.SECONDS)
        .readTimeout(HTTP_TIMEOUT, TimeUnit.SECONDS);
this.okHttpClient = okHttpBuilder.build();
```

This crash is not easy to reproduce.
I'm not sure if it's an OS bug, because it only happens on Android 7 according to our collected data.

**Comment by cheyiliu** [comment]
meet the same error

java.lang.RuntimeException: An error occurred while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:330)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:255)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:776)
Caused by: java.lang.InternalError: java.util.MissingResourceException: Can't find bundle for base name sun.util.logging.resources.logging, locale zh_CN
	at java.util.logging.Logger$1.run(Logger.java:1385)
	at java.util.logging.Logger$1.run(Logger.java:1379)
	at java.security.AccessController.doPrivileged(AccessController.java:41)
	at java.util.logging.Logger.findSystemResourceBundle(Logger.java:1378)
	at java.util.logging.Logger.findResourceBundle(Logger.java:1425)
	at java.util.logging.Logger.setupResourceInfo(Logger.java:1523)
	at java.util.logging.Logger.(Logger.java:266)
	at java.util.logging.Logger.(Logger.java:261)
	at java.util.logging.LogManager$SystemLoggerContext.demandLogger(LogManager.java:734)
	at java.util.logging.LogManager.demandSystemLogger(LogManager.java:399)
	at java.util.logging.Logger.getPlatformLogger(Logger.java:474)
	at java.util.logging.LoggingProxyImpl.getLogger(LoggingProxyImpl.java:41)
	at sun.util.logging.LoggingSupport.getLogger(LoggingSupport.java:100)
	at sun.util.logging.PlatformLogger$JavaLoggerProxy.(PlatformLogger.java:636)
	at sun.util.logging.PlatformLogger$JavaLoggerProxy.(PlatformLogger.java:631)
	at sun.util.logging.PlatformLogger.(PlatformLogger.java:246)
	at sun.util.logging.PlatformLogger.getLogger(PlatformLogger.java:205)
	at java.net.CookieManager.put(CookieManager.java:262)
	at com.android.okhttp.internal.http.HttpEngine.receiveHeaders(HttpEngine.java:1043)
	at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:785)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:463)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:405)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:243)
	at com.turbomanage.httpclient.f.b(BasicRequestHandler.java:77)
	at com.turbomanage.httpclient.a.a(AbstractHttpClient.java:328)
	at com.turbomanage.httpclient.a.a(AbstractHttpClient.java:220)
	at com.turbomanage.httpclient.c.a(AsyncHttpClient.java:189)
	at com.turbomanage.httpclient.a.c.a(DoHttpRequestTask.java:40)
	at com.turbomanage.httpclient.a.c.doInBackground(DoHttpRequestTask.java:18)
	at android.os.AsyncTask$2.call(AsyncTask.java:316)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)

**Comment by swankjesse** [comment]
Can you execute the following on the offending device? My guess is that there’s a problem with the way the Java library on the device was packaged and an important localization resource was omitted.

```
import java.util.Enumeration;
import java.util.Locale;
import java.util.ResourceBundle;

public class MissingBundleCheck {
  public static void main(String[] args) {
    ResourceBundle bundle = ResourceBundle.getBundle(
        "sun.util.logging.resources.logging", new Locale("en", "AU"),
        ClassLoader.getSystemClassLoader());
    for (Enumeration<String> k = bundle.getKeys(); k.hasMoreElements(); ) {
      String key = k.nextElement();
      System.out.println(key + ": " + bundle.getString(key));
    }
  }
}
```

When I run it on my Android 7 device everything works properly.

```
ALL: ALL
FINE: FINE
INFO: INFO
OFF: OFF
SEVERE: SEVERE
CONFIG: CONFIG
FINEST: FINEST
FINER: FINER
WARNING: WARNING
```

Also: which device is this? Might be a bogus device.

**Comment by mengdd** [comment]
@swankjesse The crash report is collected from users. So I can not reach the buggy device.

**Comment by swankjesse** [comment]
Got it. Any patterns on which devices are impacted? Manufacturers, OS versions, locales, etc.?

**Comment by mengdd** [comment]
@swankjesse OS 100% Android 7; 48% HTC and 47 HUAWEI.

**Comment by codesForLiving** [comment]
+1

`API 24`
HTC

**Comment by swankjesse** [comment]
Nothing actionable by us here. If you can report this to the device’s manufacturer, they’re the ones who can fix this.
