### ISSUE TITLE
java.lang.ExceptionInInitializerError On Android 7

### ISSUE THREAD

**Issue by yuyanghe** [square/okhttp#3336]
Hi We use OkHttp3.3.1 in our project. than I found some crash on Some Android 7. 
it crash at ConnectionSpec$Builder.tlsVersions.
ths crash log is:
java.lang.ExceptionInInitializerError
	at okhttp3.OkHttpClient.(Unknown Source)
	at okhttp3.OkHttpClient.y(Unknown Source)
	at okhttp3.OkHttpClient$Builder.(Unknown Source)
	at com.gf.mobile.common.h.(Unknown Source)
	at com.gf.mobile.common.h.b(Unknown Source)
	at com.gf.mobile.common.h.a(Unknown Source)
	at com.gf.mobile.control.a.l$1.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:776)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'okhttp3.ConnectionSpec$Builder okhttp3.ConnectionSpec$Builder.tlsVersions(okhttp3.TlsVersion[])' on a null object reference
	at okhttp3.ConnectionSpec.(Unknown Source)
	... 10 more

**Comment by swankjesse** [comment]
Can you provide more of the exception?

**Comment by yzbzz** [comment]
I have also encountered this problem:
`java.lang.ExceptionInInitializerError
	at okhttp3.internal.Util.a(Util.java:187)
	at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:121)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:443)
	at com.etcp.base.network.okhttp.OKHttpManager.d(OKHttpManager.java:102)
	at com.etcp.base.network.okhttp.OKHttpManager.<init>(OKHttpManager.java:40)
	at com.etcp.base.network.okhttp.OKHttpManager.<init>(OKHttpManager.java:35)
	at com.etcp.base.network.okhttp.OKHttpManager$SingletonHolder.<clinit>(OKHttpManager.java:63)
	at com.etcp.base.network.okhttp.OKHttpManager$SingletonHolder.a(OKHttpManager.java:62)
	at com.etcp.base.network.okhttp.OKHttpManager.a(OKHttpManager.java:44)
	at com.etcp.base.network.okhttp.request.OKHttpRequest.<init>(OKHttpRequest.java:44)
	at com.etcp.base.network.okhttp.request.OKHttpGetRequest.<init>(OKHttpGetRequest.java:23)
	at com.etcp.base.network.okhttp.request.OKHttpGetRequest$Builder.a(OKHttpGetRequest.java:30)
	at com.etcp.base.api.OKHttpUtils.a(OKHttpUtils.java:49)
	at com.etcp.base.api.OKHttpUtils.a(OKHttpUtils.java:104)
	at com.etcp.base.api.ETCPHttpUtils.c(ETCPHttpUtils.java:163)
	at com.etcp.base.api.ETCPHttpUtils.b(ETCPHttpUtils.java:104)
	at com.etcp.base.api.ETCPHttpUtils.d(ETCPHttpUtils.java:72)
	at com.ETCPOwner.yc.activity.LogoActivity.d(LogoActivity.java:217)
	at com.ETCPOwner.yc.activity.LogoActivity.c(LogoActivity.java:208)
	at com.ETCPOwner.yc.activity.LogoActivity.onCreate(LogoActivity.java:108)
	at android.app.Activity.performCreate(Activity.java:6912)
	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1126)
	at cn.jiguang.a.a.c.a.a.d.callActivityOnCreate(Unknown Source)
	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2877)
	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2985)
	at android.app.ActivityThread.-wrap14(ActivityThread.java)
	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1635)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loop(Looper.java:154)
	at android.app.ActivityThread.main(ActivityThread.java:6692)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
Caused by: java.lang.NullPointerException: source == null
	at okhttp3.ResponseBody.a(ResponseBody.java:215)
	at okhttp3.ResponseBody.a(ResponseBody.java:209)
	at okhttp3.internal.Util.<clinit>(Util.java:48)
	... 33 more
,ver:4.7.0,sdk24,phone:hero2qltechn`

There should be a problem with this line:
**this.networkInterceptors = Util.immutableList(builder.networkInterceptors);**
`  OkHttpClient(Builder builder) {
    this.dispatcher = builder.dispatcher;
    this.proxy = builder.proxy;
    this.protocols = builder.protocols;
    this.connectionSpecs = builder.connectionSpecs;
    this.interceptors = Util.immutableList(builder.interceptors);
    this.networkInterceptors = Util.immutableList(builder.networkInterceptors);
    this.proxySelector = builder.proxySelector;
    this.cookieJar = builder.cookieJar;
    this.cache = builder.cache;
    this.internalCache = builder.internalCache;
    this.socketFactory = builder.socketFactory;`

**device name**: Samsung Galaxy S7 edge
**android Version**: Android 7.0 
**model**: SM-G9350

**Comment by yuyanghe** [comment]
I have solve this problem. it caused by mutiDex.   If you use Goolge MultiDex. please don't use MultiDex.install().if  android sdk > 21

**Comment by yzbzz** [comment]
my configuration:
defaultConfig {
        versionName "4.7.0"
        versionCode 56
        minSdkVersion 17
        targetSdkVersion 25
        multiDexEnabled = true
    }

**Comment by yzbzz** [comment]
@yuyanghe Thank you for your answer. But my minSdkVersion is 17, What should we do?

**Comment by swankjesse** [comment]
Not sure what action for us to take on this. If there’s a specific bug, please provide an executable test case.

**Comment by PGMacDesign** [comment]
I know this is an older issue, but I just inherited some legacy code that had this verbatim same issue and I resolved it on my end. 

The core of the problem is that a NullPointerException is being thrown here:

```
Caused by: java.lang.NullPointerException: Attempt to get length of null array
        at okhttp3.internal.tls.BasicTrustRootIndex.<init>(BasicTrustRootIndex.java:32)
        at okhttp3.internal.platform.Platform.buildTrustRootIndex(Platform.java:288)
        at okhttp3.internal.platform.AndroidPlatform.buildTrustRootIndex(AndroidPlatform.java:280)
        at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.java:172)
        at okhttp3.internal.platform.AndroidPlatform.buildCertificateChainCleaner(AndroidPlatform.java:230)
        at okhttp3.internal.tls.CertificateChainCleaner.get(CertificateChainCleaner.java:41)
        at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:694)
```

This is being caused by the need (in this particular call) to allow all Certificates, in which I was using this code to generate the X509TrustManager in the builder:

```
                X509TrustManager trustManager = new X509TrustManager() {
                    public void checkClientTrusted(X509Certificate[] xcs, String string)
                            throws CertificateException {}
                    public void checkServerTrusted(X509Certificate[] xcs, String string)
                            throws CertificateException {}
                    public X509Certificate[] getAcceptedIssuers() {
                        return null;
                    }
                };
```
This is what a large number of StackOverflow posts recommend doing for this situation, but returning null in the getAcceptedIssuers() is why this is occurring. To fix this, simply change the code above to:

```
                X509TrustManager trustManager = new X509TrustManager() {
                    public void checkClientTrusted(X509Certificate[] xcs, String string)
                            throws CertificateException {}
                    public void checkServerTrusted(X509Certificate[] xcs, String string)
                            throws CertificateException {}
                    public X509Certificate[] getAcceptedIssuers() {
                        return new X509Certificate[]{};
                    }
                };
```

I wrote up a StackOverflow Q/A here in case anyone needs to read it.

**Comment by yschimke** [comment]
Please link to the Stackoverflow question

**Comment by PGMacDesign** [comment]
Sure, edited and included, thank you for reminding me.
