### ISSUE TITLE
java.lang.NullPointerException: Attempt to invoke virtual method 'okio.Timeout okio.Timeout.a(long, java.util.concurrent.TimeUnit)' on a null object reference

### ISSUE THREAD

**Issue by yzbzz** [square/okhttp#3347]
**When i keep coming in and out of the app，I found an exception：**
`java.lang.NullPointerException: Attempt to invoke virtual method 'okio.Timeout okio.Timeout.a(long, java.util.concurrent.TimeUnit)' on a null object reference
    at okhttp3.internal.connection.StreamAllocation.a(StreamAllocation.java:109)
    at okhttp3.internal.connection.ConnectInterceptor.a(ConnectInterceptor.java:42)
    at okhttp3.internal.http.RealInterceptorChain.a(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.a(RealInterceptorChain.java:67)
    at okhttp3.internal.cache.CacheInterceptor.a(CacheInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.a(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.a(RealInterceptorChain.java:67)
    at okhttp3.internal.http.BridgeInterceptor.a(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.a(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.a(RetryAndFollowUpInterceptor.java:120)
    at okhttp3.internal.http.RealInterceptorChain.a(RealInterceptorChain.java:92)
    at okhttp3.internal.http.RealInterceptorChain.a(RealInterceptorChain.java:67)
    at okhttp3.RealCall.k(RealCall.java:179)
    at okhttp3.RealCall$AsyncCall.d(RealCall.java:129)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
    at java.lang.Thread.run(Thread.java:818)`

**Sometimes the following exception occurs**:
`java.lang.NullPointerException: Attempt to invoke virtual method 'okhttp3.Response$Builder okhttp3.Response$Builder.a(okhttp3.Request)' on a null object reference
	at okhttp3.internal.http.CallServerInterceptor.a(CallServerInterceptor.java:55)
	at okhttp3.internal.http.RealInterceptorChain.a(RealInterceptorChain.java:92)
	at okhttp3.internal.connection.ConnectInterceptor.a(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.a(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.a(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.CacheInterceptor.a(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.a(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.a(RealInterceptorChain.java:67)
	at okhttp3.internal.http.BridgeInterceptor.a(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.a(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.a(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.RealInterceptorChain.a(RealInterceptorChain.java:92)
	at okhttp3.internal.http.RealInterceptorChain.a(RealInterceptorChain.java:67)
	at okhttp3.RealCall.k(RealCall.java:179)
	at okhttp3.RealCall$AsyncCall.d(RealCall.java:129)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:818)
,ver:4.7.0,sdk22,phone:clark_ds`

**Comment by swankjesse** [comment]
There isn’t anything actionable here. A non-obfuscated stacktrace or executable test case would help!
