### ISSUE TITLE
Websocket client crashes when sending data of length larger than 2^16

### ISSUE THREAD

**Issue by emilsjolander** [square/okhttp#3364]
I'm using websockets from okhttp 3.8.0 and am seeing an issue when sending large text payloads. Once sending text exceeds 2^16 chars the connection will close instantly with a broken pipe error.

Works fine:
```
webSocket.send(new String(new char[65536]).replace('\0', 'A'));
```

Crashes:
```
webSocket.send(new String(new char[65537]).replace('\0', 'A'));
```

Looking at the code and reading the discussion in https://github.com/square/okhttp/issues/2270 it seems okhttp intends to split large messages into smaller frames automatically so I would expect any size of message to send just fine.

I'm seeing the following stack trace in my logs. Unsure if it is the cause of the issue or of it is an error when processing the frame after the errored frame.
```
java.io.EOFException
    at okio.RealBufferedSource.require(RealBufferedSource.java:60)
    at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
    at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
    at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
    at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
    at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
```

**Comment by emilsjolander** [comment]
I segment in okio is 2^13 large (https://github.com/square/okio/blob/master/okio/src/main/java/okio/Segment.java#L37) so it seems like segmentation is working fine. At least until it reaches a certain point.

**Comment by emilsjolander** [comment]
Actually nvm I think this is on the server end of our websocket implementation. It just manifested itself with an error looking very much like a client error.
