### ISSUE TITLE
W/System.err: java.lang.IllegalArgumentException: byteCount < 0: -2015,  E/AndroidRuntime: FATAL EXCEPTION: pool-5-thread-1 java.lang.IllegalStateException: Closed, java.net.ProtocolException: Control frames must be final.

### ISSUE THREAD

**Issue by SidCosineLabs** [square/okhttp#3366]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [ ] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

**Comment by SidCosineLabs** [comment]
`W/System.err: java.lang.IllegalArgumentException: byteCount < 0: -2015
W/System.err:     at okio.RealBufferedSource.read(RealBufferedSource.java:42)
W/System.err:   atcom.squareup.okhttp.internal.ws.WebSocketReader$
FramedMessageSource.read(WebSocketReader.java:250)
W/System.err:     at okio.Buffer.writeAll(Buffer.java:1005)
W/System.err:     at okio.RealBufferedSource.readUtf8(RealBufferedSource.java:178)
W/System.err:     at com.wowlabz.aime.network.WebSocketsService.onMessage(WebSocketsService.java:247)
W/System.err:     at com.squareup.okhttp.internal.ws.WebSocketReader.readMessage(WebSocketReader.java:111)
W/System.err:     at com.squareup.okhttp.internal.ws.WebSocket$ReaderRunnable.execute(WebSocket.java:355)
W/System.err:     at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
W/System.err:     at java.lang.Thread.run(Thread.java:841)`

E/WebSockets: Websocket is closed
java.net.ProtocolException: Control frames must be final.
at com.squareup.okhttp.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:139)
at com.squareup.okhttp.internal.ws.WebSocketReader.readUntilNonControlFrame(WebSocketReader.java:120)
at com.squareup.okhttp.internal.ws.WebSocketReader.readMessage(WebSocketReader.java:95)
at com.squareup.okhttp.internal.ws.WebSocket$ReaderRunnable.execute(WebSocket.java:355)
at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
at java.lang.Thread.run(Thread.java:841)

E/AndroidRuntime: FATAL EXCEPTION: pool-5-thread-1
Process: com.wowlabz.aime, PID: 31398
java.lang.IllegalStateException: Closed
at com.squareup.okhttp.internal.ws.WebSocketWriter.writePong(WebSocketWriter.java:87)
at com.squareup.okhttp.internal.ws.WebSocket$1$1.execute(WebSocket.java:205)
at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)

**Comment by SidCosineLabs** [comment]
I am getting these errors continuously and I am not getting why this is happening, please suggest me some fix. That would be a great help

**Comment by swankjesse** [comment]
Which version?

**Comment by SidCosineLabs** [comment]
1.9.0
com.squareup.okhttp.internal.ws.WebSocket;
com.squareup.okhttp.internal.ws.WebSocketListener

**Comment by swankjesse** [comment]
Try upgrading to the latest.
