### ISSUE TITLE
Okhttp 3.8.0 to 3.9.0-SNAPSHOT java.lang.reflect.UndeclaredThrowableException

### ISSUE THREAD

**Issue by bitsydarel** [square/okhttp#3369]
Issue founded when scrolling an recyclerview and downloading image with glide.

E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                       Process: com.dbeginc.dbweather, PID: 20663
                                                                       java.lang.reflect.UndeclaredThrowableException
                                                                           at $Proxy1.intercept(Unknown Source)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                           at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                           at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                           at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                           at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                           at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                           at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                                           at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                           at java.lang.Thread.run(Thread.java:818)
                                                                        Caused by: java.lang.reflect.InvocationTargetException
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at com.android.tools.profiler.support.network.OkHttpInterceptorHandler.invoke(OkHttpInterceptorHandler.java:36)
                                                                           at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                                           at $Proxy1.intercept(Unknown Source) 
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                           at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) 
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                           at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                           at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                           at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120) 
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92) 
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67) 
                                                                           at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185) 
                                                                           at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135) 
                                                                           at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) 
                                                                           at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
                                                                           at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
                                                                           at java.lang.Thread.run(Thread.java:818) 
                                                                        Caused by: java.net.SocketException: Socket closed
                                                                           at libcore.io.Posix.recvfromBytes(Native Method)
                                                                           at libcore.io.Posix.recvfrom(Posix.java:189)
                                                                           at libcore.io.BlockGuardOs.recvfrom(BlockGuardOs.java:250)
                                                                           at libcore.io.IoBridge.recvfrom(IoBridge.java:584)
                                                                           at java.net.PlainSocketImpl.read(PlainSocketImpl.java:488)
                                                                           at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:42)
                                                                           at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:242)
                                                                           at okio.Okio$2.read(Okio.java:139)
                                                                           at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
                                                                           at okio.RealBufferedSource.indexOf(RealBufferedSource.java:345)
                                                                           at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
                                                                           at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
                                                                           at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
                                                                           at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:75)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                           at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)

**Comment by JakeWharton** [comment]
Seems like an Android tools bug. File on b.android.com.

**Comment by bitsydarel** [comment]
I guess you right but maybe is an glide issue because i'm using dagger bindingAdapter to download image 

@BindingAdapter("setImage")
    public static void setImage(@Nonnull final ImageView imageView, final String url) {
        if (!url.isEmpty()) {
            Glide.with(imageView)
                    .load(url)
                    .apply(RequestOptions.errorOf(R.drawable.no_image_icon))
                    .apply(RequestOptions.skipMemoryCacheOf(true))
                    .into(imageView);
        }
    } 

i will post the issue in android .

**Comment by JakeWharton** [comment]
The exception indicates the Android profiler is creating a dynamic proxy
which can't re-throw a checked exception. So I suspect it's their problem.

**Comment by bitsydarel** [comment]
Yes that was it! Disabling android profiler fixed the issue . Thanks!

did not notice this line: 
at com.android.tools.profiler.support.network.OkHttpInterceptorHandler.invoke(OkHttpInterceptorHandler.java:36)

**Comment by JakeWharton** [comment]
Can you link the issue you filed on Android?

**Comment by bitsydarel** [comment]
Sure, 
https://issuetracker.google.com/issues/38481613

**Comment by JakeWharton** [comment]
Thanks!
