### ISSUE TITLE
A SocketTimeoutException occured after restart the network.

### ISSUE THREAD

**Issue by MegatronKing** [square/okhttp#3378]
I created a HTTP/2 connection, this connection remains open in a half-closed state (read time is 1 hour).  After connected, I disable the network and restart. And then, I send a normal request, which was occured a SocketTimeoutException : timeout

`java.net.SocketTimeoutException: timeout
                                                                     at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:593)
                                                                     at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:601)
                                                                     at okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(Http2Stream.java:510)
                                                                     at okhttp3.internal.http2.Http2Stream$FramingSink.write(Http2Stream.java:481)
                                                                     at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
                                                                     at okio.RealBufferedSink.write(RealBufferedSink.java:85)`

**Comment by ekstro** [comment]
Related to?

https://github.com/square/okhttp/issues/1771
https://github.com/square/okhttp/issues/3146
https://github.com/square/okhttp/issues/3278

**Comment by swankjesse** [comment]
I think we gotta fix this with HTTP/2 pings. Otherwise we can’t differentiate between a stalled stream and a stalled connection.

**Comment by Kiran89kumar** [comment]
@swankjesse :Can you please let us know the tentative release date for 3.9

**Comment by swankjesse** [comment]
It might be a few months. If you need something urgently please use a snapshot; everything but the API is stable.

**Comment by MegatronKing** [comment]
Very much looking forward to 3.9

**Comment by swankjesse** [comment]
Will implement with this:
https://github.com/square/okhttp/issues/3268
