### ISSUE TITLE
java.lang.NullPointerException: ssl_session == null

### ISSUE THREAD

**Issue by ronniesun** [square/okhttp#3387]
java.lang.NullPointerException: ssl_session == null
	at com.android.org.conscrypt.NativeCrypto.SSL_SESSION_cipher(Native Method)
	at com.android.org.conscrypt.OpenSSLSessionImpl.getCipherSuite(OpenSSLSessionImpl.java:320)
	at okhttp3.s.a(Handshake.java:49)
	at okhttp3.internal.connection.c.b(RealConnection.java:268)
	at okhttp3.internal.connection.c.a(RealConnection.java:237)
	at okhttp3.internal.connection.c.a(RealConnection.java:148)
	at okhttp3.internal.connection.f.a(StreamAllocation.java:186)
	at okhttp3.internal.connection.f.a(StreamAllocation.java:121)
	at okhttp3.internal.connection.f.a(StreamAllocation.java:100)
	at okhttp3.internal.connection.a.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.c.g.a(RealInterceptorChain.java:92)
	at okhttp3.internal.c.g.a(RealInterceptorChain.java:67)
	at okhttp3.internal.a.a.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.c.g.a(RealInterceptorChain.java:92)
	at okhttp3.internal.c.g.a(RealInterceptorChain.java:67)
	at okhttp3.internal.c.a.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.c.g.a(RealInterceptorChain.java:92)
	at okhttp3.internal.c.j.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.c.g.a(RealInterceptorChain.java:92)
	at okhttp3.internal.c.g.a(RealInterceptorChain.java:67)
	at okhttp3.y.k(RealCall.java:179)
	at okhttp3.y$a.d(RealCall.java:129)
	at okhttp3.internal.b.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

device  M5，M611D  made in china.  please fix it ASAP

**Comment by swankjesse** [comment]
Could you provide an executable test case? As is there’s no action for us to take on this.

**Comment by ronniesun** [comment]
The bug code position is very clear and we can not reproduce it

**Comment by ronniesun** [comment]
okhttp3.s.a(Handshake.java:49)       please check here

**Comment by JakeWharton** [comment]
That's not a class. Deobfuscate your stacktrace

**Comment by swankjesse** [comment]
No action for us to take on this.

**Comment by rgrigoryev** [comment]
For history - see https://github.com/square/okhttp/issues/3301#issuecomment-318955688
