### ISSUE TITLE
may be bug

### ISSUE THREAD

**Issue by duzechao** [square/okhttp#3391]
` java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.Class java.lang.ClassLoader.loadClass(java.lang.String)' on a null object reference
                                                                                at com.android.tools.profiler.support.network.okhttp.reflection.okhttp3.Request$.getTargetClass(Request$.java:29)
                                                                                at com.android.tools.profiler.support.network.okhttp.reflection.okhttp3.Interceptor$$Chain$.proceed(Interceptor$.java:50)
                                                                                at com.android.tools.profiler.support.network.okhttp.OkHttp3Interceptor.invoke(OkHttp3Interceptor.java:57)
                                                                                at java.lang.reflect.Proxy.invoke(Proxy.java:393)
                                                                                at $Proxy0.intercept(Unknown Source)`

today，my app crash，i don't know what happened，this is the log，i try to debug，but  @couldn't find the question

**Comment by duzechao** [comment]
wtf!!!   this is the Android Studio 3.0 Preview bug,i disable the profiler,it work find

**Comment by NightlyNexus** [comment]
Be sure to file a bug on Android Studio, then: https://issuetracker.google.com/issues/new?component=192708&template=840533

**Comment by BenoitDuffez** [comment]
@duzechao: how did you disable the profiler? How did you find out that this was related to this feature? Did you submit a bug report?
Thanks!

**Comment by duzechao** [comment]
@BenoitDuffez submitted report

**Comment by mateusgrb** [comment]
They claim it's fixed, but I still face this issue: https://issuetracker.google.com/issues/62435342

**Comment by sinwoobang** [comment]
Same problem.

Android Studio 3.0
Build #AI-171.4408382, built on October 21, 2017
JRE: 1.8.0_152-release-915-b08 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.12.6

**Comment by wangyeming** [comment]
@mateusgrb Me too! I got this issue on Android Studio 3.1.2 release and I also disable the Android Profiler!
