### ISSUE TITLE
[Bug] Unable to create Request on 4.4.4 and earlier versions

### ISSUE THREAD

**Issue by j-garin** [square/okhttp#3402]
Hello.

OkHttp version: 3.8.0.
Got this error on 4.4 and earlier devices when attempting a get request. Unable to reproduce on 5+.
MultiDex is enabled.
Build tools version 25.0.2

Logs:

```
E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.ExceptionInInitializerError
                                                       at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1318)
                                                       at okhttp3.HttpUrl.parse(HttpUrl.java:900)
                                                       at okhttp3.Request$Builder.url(Request.java:142)
                                                    Caused by: java.lang.NoClassDefFoundError: okio.Buffer
                                                       at okhttp3.ResponseBody.create(ResponseBody.java:209)
                                                       at okhttp3.internal.Util.<clinit>(Util.java:48)
                                                       at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1318) 
                                                       at okhttp3.HttpUrl.parse(HttpUrl.java:900) 
                                                       at okhttp3.Request$Builder.url(Request.java:142) 

```
Please help

**Comment by maduperera** [comment]
May I please know if this is resolved or perhaps may I please know how to check if a Library like this supports ones' desired minimum api level for his app. 
For example I declared my app to support min api level 15. And I'm using this nice API. But I'm not sure how to find out whether this library supports upto api 15 or not.

**Comment by xty19** [comment]
just use the older dependency is ok
`    implementation 'com.squareup.okhttp3:logging-interceptor:3.12.1'`
`    implementation 'com.squareup.okhttp3:okhttp:3.12.2'`
