### ISSUE TITLE
 "Multipart body must have at least one part"

### ISSUE THREAD

**Issue by iegik** [square/okhttp#3411]
In one of StackOverflow asked question (react-native upload pictures on android) described request with param "FormData", but I requested GET request without data and got same message!

react-native app with ProGuard enabled = true

App crashed on first request.

```
06-16 14:00:30.971: E/AndroidRuntime(14321): java.lang.IllegalStateException: Multipart body must have at least one part.
06-16 14:00:30.971: E/AndroidRuntime(14321):    at okhttp3.MultipartBody$Builder.build(SourceFile:327)
06-16 14:00:30.971: E/AndroidRuntime(14321):    at com.facebook.react.modules.network.NetworkingModule.sendRequest(SourceFile:309)
06-16 14:00:30.971: E/AndroidRuntime(14321):    at java.lang.reflect.Method.invoke(Native Method)
06-16 14:00:30.971: E/AndroidRuntime(14321):    at java.lang.reflect.Method.invoke(Method.java:372)
06-16 14:00:30.971: E/AndroidRuntime(14321):    at com.facebook.react.bridge.BaseJavaModule$b.a(SourceFile:345)
06-16 14:00:30.971: E/AndroidRuntime(14321):    at com.facebook.react.cxxbridge.JavaModuleWrapper.invoke(SourceFile:136)
06-16 14:00:30.971: E/AndroidRuntime(14321):    at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method)
06-16 14:00:30.971: E/AndroidRuntime(14321):    at android.os.Handler.handleCallback(Handler.java:739)
06-16 14:00:30.971: E/AndroidRuntime(14321):    at android.os.Handler.dispatchMessage(Handler.java:95)
06-16 14:00:30.971: E/AndroidRuntime(14321):    at com.facebook.react.bridge.queue.a.dispatchMessage(SourceFile:31)
06-16 14:00:30.971: E/AndroidRuntime(14321):    at android.os.Looper.loop(Looper.java:135)
06-16 14:00:30.971: E/AndroidRuntime(14321):    at com.facebook.react.bridge.queue.MessageQueueThreadImpl$3.run(SourceFile:196)
06-16 14:00:30.971: E/AndroidRuntime(14321):    at java.lang.Thread.run(Thread.java:818)
```

https://stackoverflow.com/questions/44591453/multipart-body-must-have-at-least-one-part

**Comment by iegik** [comment]
Maybe related to this: https://github.com/square/okhttp/issues/3394

**Comment by swankjesse** [comment]
Test case? Not much action we can take here.

**Comment by iegik** [comment]
```
06-16 18:01:09.992: E/AndroidRuntime(20405): Caused by: java.lang.ClassNotFoundException: Didn't find class "com.facebook.react.devsupport.DevSupportManagerImpl" on path: DexPathList[[zip file "/data/app/com.citylife.cachier-1/base.apk"],nativeLibraryDirectories=[/data/app/com.citylife.cachier-1/lib/arm, /vendor/lib, /system/lib]]
06-16 18:01:09.992: E/AndroidRuntime(20405): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
06-16 18:01:09.992: E/AndroidRuntime(20405): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
06-16 18:01:09.992: E/AndroidRuntime(20405): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
06-16 18:01:09.992: E/AndroidRuntime(20405): 	... 24 more
06-16 18:01:09.992: E/AndroidRuntime(20405): 	Suppressed: java.lang.ClassNotFoundException: com.facebook.react.devsupport.DevSupportManagerImpl
06-16 18:01:09.992: E/AndroidRuntime(20405): 		at java.lang.Class.classForName(Native Method)
06-16 18:01:09.992: E/AndroidRuntime(20405): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
06-16 18:01:09.992: E/AndroidRuntime(20405): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
06-16 18:01:09.992: E/AndroidRuntime(20405): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
06-16 18:01:09.992: E/AndroidRuntime(20405): 		... 25 more
06-16 18:01:09.992: E/AndroidRuntime(20405): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
```

**Comment by iegik** [comment]
https://github.com/facebook/react-native/issues/13853

**Comment by iegik** [comment]
> I tried to pass body as empty FormData, so message about body without any part of it.

**Comment by lylest** [comment]
I got the same issue

**Comment by virtualLast** [comment]
Still having this issue using Expo 31. 
debugging FormData I can see that I have at least one part

![Screenshot 2019-05-24 at 10 12 13](https://user-images.githubusercontent.com/2872439/58316879-848c3800-7e0c-11e9-8c37-ba1a253570ad.png)

**Comment by canpoyrazoglu** [comment]
Any updates? This is a blocker for me to push my React Native (which uses okhttp in Android) app into production. My POST request fails even though I have form data parameters (actually a blob) set.

**Comment by lylest** [comment]
I faced the same issue I decided to use firebase to upload images or videos it's lots more easier

**Comment by andreykarnovskiy** [comment]
Guys, always check module dependencies and add latest version of the library to the module dependencies, otherwise module will use obsolete version and you dont notice it. Оften this is the cause of problems.
