### ISSUE TITLE
 java.lang.IllegalStateException  StreamAllocation.java:347

### ISSUE THREAD

**Issue by Heart2009** [square/okhttp#3435]
okhttp3: v3.8.0
java.lang.IllegalStateException
	at okhttp3.internal.connection.f.a(StreamAllocation.java:347)
	at okhttp3.f.a(ConnectionPool.java:126)
	at okhttp3.p$1.a(OkHttpClient.java:150)
	at okhttp3.internal.connection.f.a(StreamAllocation.java:161)
	at okhttp3.internal.connection.f.a(StreamAllocation.java:121)
	at okhttp3.internal.connection.f.a(StreamAllocation.java:100)
	at okhttp3.internal.connection.a.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.f.a(RealInterceptorChain.java:92)
	at okhttp3.internal.http.f.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.cache.a.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.f.a(RealInterceptorChain.java:92)
	at okhttp3.internal.http.f.proceed(RealInterceptorChain.java:67)
	at okhttp3.internal.http.a.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.f.a(RealInterceptorChain.java:92)
	at okhttp3.internal.http.i.intercept(RetryAndFollowUpInterceptor.java:120)
	at okhttp3.internal.http.f.a(RealInterceptorChain.java:92)
	at okhttp3.internal.http.f.proceed(RealInterceptorChain.java:67)
	at okhttp3.q.e(RealCall.java:185)
	at okhttp3.q$a.b(RealCall.java:135)
	at okhttp3.internal.b.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	at java.lang.Thread.run(Thread.java:776)

**Comment by JakeWharton** [comment]
Provide a deobfuscated stacktrace.

**Comment by MegatronKing** [comment]
Hi, I got a deobfuscated stacktrace.

okhttp version 3.8.0
mobile Android 7.0,level 24,SM-G930T

```
okhttp3.internal.connection.StreamAllocation.acquire(Unknown Source)
okhttp3.ConnectionPool.get(Unknown Source)
okhttp3.OkHttpClient$1.get(Unknown Source)
okhttp3.internal.connection.StreamAllocation.findConnection(Unknown Source)
okhttp3.internal.connection.StreamAllocation.findHealthyConnection(Unknown Source)
okhttp3.internal.connection.StreamAllocation.newStream(Unknown Source)
okhttp3.internal.connection.ConnectInterceptor.intercept(Unknown Source)
okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
okhttp3.internal.cache.CacheInterceptor.intercept(Unknown Source)
okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
okhttp3.internal.http.BridgeInterceptor.intercept(Unknown Source)
okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(Unknown Source)
okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
com.zhixin.roav.avs.d.g.intercept(Unknown Source)
okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source)
okhttp3.RealCall.getResponseWithInterceptorChain(Unknown Source)
okhttp3.RealCall$AsyncCall.execute(Unknown Source)
okhttp3.internal.NamedRunnable.run(Unknown Source)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
java.lang.Thread.run(Thread.java:762)
```
