### ISSUE TITLE
Okhttp exception: [java.io.IOException: gzip finished without exhausting source]

### ISSUE THREAD

**Issue by vk2211** [square/okhttp#3457]
I know similar exception issue has been submitted, but, this is different.

```
java.io.IOException: gzip finished without exhausting source
    at okio.GzipSource.read(GzipSource.java:100)
    at okio.Buffer.writeAll(Buffer.java:1005)
    at okio.RealBufferedSource.readString(RealBufferedSource.java:190)
    at okhttp3.ResponseBody.string(ResponseBody.java:175)
    at com.test.testokhttp.PostExampleActivity$2.onResponse(PostExampleActivity.java:99)
    at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
    at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
    at java.lang.Thread.run(Thread.java:761)
```

My source code is like this:
```
String url = "http://api.kdniao.cc/Ebusiness/EbusinessOrderHandle.aspx";
String key1 = "RequestData";
String key2 = "EBusinessID";
String key3 = "RequestType";
String key4 = "DataSign";
String key5 = "DataType";

String val1 = "%7B%27OrderCode%27%3A%27%27%2C%27ShipperCode%27%3A%27STO%27%2C%27LogisticCode%27%3A%27402581441844%27%7D";
String val2 = "1293539";
String val3 = "1002";
String val4 = "OWNiNzUxODEyMmEzN2E5NWY0NDAwYTJlY2QxZWVmNWY%3D";
String val5 = "2";

public void simplePostClick(View view) {
	OkHttpClient okHttpClient = new OkHttpClient();
	RequestBody requestBody = new FormBody.Builder()
		.add(key1, val1)
		.add(key2, val2)
		.add(key3, val3)
		.add(key4, val4)
		.add(key5, val5)
		.build();
	Request request = new Request.Builder()
		.url(url)
		.post(requestBody)
		.build();
	okHttpClient.newCall(request).enqueue(callback);
}

private Callback callback = new Callback() {
	@Override
	public void onFailure(Call call, IOException e) {
		setResult(e.getMessage(), false);
	}

	@Override
	public void onResponse(Call call, Response response) throws IOException {
		setResult(response.body().string(), true);
	}
};

private void setResult(final String msg, final boolean success) {
	runOnUiThread(new Runnable() {
		@Override
		public void run() {
			Log.e("okhttp", msg);
			resultTextView.setText(msg);
		}
	});
}
```

Run this code will always get the exception. There is no problem with the server. But **HttpURLConnection** will get the right result

**Comment by wujingchao** [comment]
<img width="715" alt="gzipsourceerror" src="https://user-images.githubusercontent.com/10916295/28491057-cb796f8c-6f1b-11e7-8698-25b9cf6a717a.png">

Response body gzip format is malformed. It more of a newline character.Why the server append 0x10 character in the end? In addition, the HttpClient decode compatible with the situation using GzipInputStream

**Comment by swankjesse** [comment]
Looks like a bug in whichever server is serving this data; possibly `api.kdniao.cc`. You should fix it there.

We could fix OkHttp to ignore unexpected data at the end of the gzip stream, but there’s lots of bad consequences for that. For example, there might be security consequences! Instead it’s best to fix the problem with the offending server.
