### ISSUE TITLE
Crash on wifi connecting but not connected

### ISSUE THREAD

**Issue by hamberluo** [square/okhttp#3466]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.v.toString()' on a null object reference
       at io.socket.engineio.client.transports.PollingXHR$Request.onLoad(PollingXHR.java:271)
       at io.socket.engineio.client.transports.PollingXHR$Request.access$400(PollingXHR.java:148)
       at io.socket.engineio.client.transports.PollingXHR$Request$1.onResponse(PollingXHR.java:232)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```

**Comment by JakeWharton** [comment]
Report to socket.io. This doesn't seem to be related to OkHttp other than its the library being used underneath socket.io.
