### ISSUE TITLE
SocketException -  okhttp3.internal.platform.AndroidPlatform.connectSocket

### ISSUE THREAD

**Issue by mhdtouban** [square/okhttp#3478]
Fatal Exception: java.net.SocketException: Software caused connection abort
       at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java)
       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
       at java.net.Socket.connect(Socket.java:605)
       at okhttp3.internal.platform.AndroidPlatform.connectSocket(SourceFile:63)
       at okhttp3.internal.connection.RealConnection.connectSocket(SourceFile:223)
       at okhttp3.internal.connection.RealConnection.connect(SourceFile:149)
       at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:192)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:121)
       at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:100)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:120)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at com.readystatesoftware.chuck.ChuckInterceptor.intercept(SourceFile:56)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(SourceFile:144)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:185)
       at okhttp3.RealCall.execute(SourceFile:69)
       at retrofit2.OkHttpCall.execute(SourceFile:180)
       at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(SourceFile:41)
       at io.reactivex.Observable.subscribe(SourceFile:10514)
       at io.reactivex.internal.operators.observable.ObservableObserveOn.subscribeActual(SourceFile:44)
       at io.reactivex.Observable.subscribe(SourceFile:10514)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$1.run(SourceFile:39)
       at io.reactivex.Scheduler$1.run(SourceFile:134)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(SourceFile:59)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(SourceFile:51)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

**Comment by JakeWharton** [comment]
This is a normal IOException that your application code needs to handle occurring. Not an issue with OkHttp.

**Comment by zahidgirnar** [comment]
http://crashes.to/s/926f376bac6

**Comment by ashutoshkumardev** [comment]
@JakeWharton can you please suggest how to handle these type of issues.
