### ISSUE TITLE
Flaky CallTest

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#3534]
https://travis-ci.org/square/okhttp/builds/266942779?utm_source=github_status&utm_medium=notification

```
Tests run: 166, Failures: 1, Errors: 2, Skipped: 1, Time elapsed: 18.145 sec <<< FAILURE! - in okhttp3.CallTest
expect100ContinueTimesOutWithoutContinue_HTTP2(okhttp3.CallTest)  Time elapsed: 0.603 sec  <<< ERROR!
okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
	at okhttp3.internal.http2.Http2Stream.checkOutNotClosed(Http2Stream.java:567)
	at okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(Http2Stream.java:501)
	at okhttp3.internal.http2.Http2Stream$FramingSink.close(Http2Stream.java:538)
	at okhttp3.internal.http2.Http2Codec.finishRequest(Http2Codec.java:120)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:98)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:202)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at okhttp3.CallTest.expect100ContinueTimesOutWithoutContinue(CallTest.java:2303)
	at okhttp3.CallTest.expect100ContinueTimesOutWithoutContinue_HTTP2(CallTest.java:2314)

expect100ContinueTimesOutWithoutContinue(okhttp3.CallTest)  Time elapsed: 0.503 sec  <<< ERROR!
java.net.SocketException: Socket closed
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:118)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at okio.Okio$1.write(Okio.java:79)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:216)
	at okhttp3.internal.http1.Http1Codec.finishRequest(Http1Codec.java:167)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:98)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:202)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at okhttp3.CallTest.expect100ContinueTimesOutWithoutContinue(CallTest.java:2303)

failingCallsDoNotInterfereWithConnection(okhttp3.CallTest)  Time elapsed: 0.183 sec  <<< FAILURE!
java.lang.AssertionError: null
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.fail(Assert.java:95)
	at okhttp3.CallTest.makeFailingCall(CallTest.java:3043)
	at okhttp3.CallTest.access$200(CallTest.java:93)

```

**Comment by yschimke** [comment]
ignore
