### ISSUE TITLE
[StrictMode] close  not called @ Connection.setTimeouts

### ISSUE THREAD

**Issue by plentz** [square/okhttp#3560]
```
08-30 13:25:17.535  6437  6446 E StrictMode: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
08-30 13:25:17.535  6437  6446 E StrictMode: java.lang.Throwable: Explicit termination method 'close' not called
08-30 13:25:17.535  6437  6446 E StrictMode:  at dalvik.system.CloseGuard.open(CloseGuard.java:180)
08-30 13:25:17.535  6437  6446 E StrictMode:  at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:103)
08-30 13:25:17.535  6437  6446 E StrictMode:  at java.net.Socket.createImpl(Socket.java:464)
08-30 13:25:17.535  6437  6446 E StrictMode:  at java.net.Socket.getImpl(Socket.java:530)
08-30 13:25:17.535  6437  6446 E StrictMode:  at java.net.Socket.setSoSndTimeout(Socket.java:1194)
08-30 13:25:17.535  6437  6446 E StrictMode:  at com.android.okhttp.Connection.setTimeouts(Connection.java:508)
08-30 13:25:17.535  6437  6446 E StrictMode:  at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:400)
08-30 13:25:17.535  6437  6446 E StrictMode:  at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
08-30 13:25:17.535  6437  6446 E StrictMode:  at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:356)
08-30 13:25:17.535  6437  6446 E StrictMode:  at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:273)
08-30 13:25:17.535  6437  6446 E StrictMode:  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:474)
08-30 13:25:17.535  6437  6446 E StrictMode:  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
08-30 13:25:17.535  6437  6446 E StrictMode:  at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
08-30 13:25:17.535  6437  6446 E StrictMode:  at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
08-30 13:25:17.535  6437  6446 E StrictMode:  at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
08-30 13:25:17.535  6437  6446 E StrictMode:  at io.fabric.sdk.android.services.network.HttpRequest.openOutput(HttpRequest.java:2450)
08-30 13:25:17.535  6437  6446 E StrictMode:  at io.fabric.sdk.android.services.network.HttpRequest.startPart(HttpRequest.java:2463)
08-30 13:25:17.535  6437  6446 E StrictMode:  at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2542)
08-30 13:25:17.535  6437  6446 E StrictMode:  at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2526)
08-30 13:25:17.535  6437  6446 E StrictMode:  at io.fabric.sdk.android.services.network.HttpRequest.part(HttpRequest.java:2512)
08-30 13:25:17.535  6437  6446 E StrictMode:  at io.fabric.sdk.android.services.settings.AbstractAppSpiCall.applyMultipartDataTo(AbstractAppSpiCall.java:108)
08-30 13:25:17.535  6437  6446 E StrictMode:  at io.fabric.sdk.android.services.settings.AbstractAppSpiCall.invoke(AbstractAppSpiCall.java:76)
08-30 13:25:17.535  6437  6446 E StrictMode:  at io.fabric.sdk.android.services.settings.UpdateAppSpiCall.invoke(UpdateAppSpiCall.java:29)
08-30 13:25:17.535  6437  6446 E StrictMode:  at io.fabric.sdk.android.Onboarding.performUpdateApp(Onboarding.java:204)
08-30 13:25:17.535  6437  6446 E StrictMode:  at io.fabric.sdk.android.Onboarding.performUpdateApp(Onboarding.java:194)
08-30 13:25:17.535  6437  6446 E StrictMode:  at io.fabric.sdk.android.Onboarding.performAutoConfigure(Onboarding.java:175)
08-30 13:25:17.535  6437  6446 E StrictMode:  at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:112)
08-30 13:25:17.535  6437  6446 E StrictMode:  at io.fabric.sdk.android.Onboarding.doInBackground(Onboarding.java:45)
08-30 13:25:17.535  6437  6446 E StrictMode:  at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:63)
08-30 13:25:17.535  6437  6446 E StrictMode:  at io.fabric.sdk.android.InitializationTask.doInBackground(InitializationTask.java:28)
08-30 13:25:17.535  6437  6446 E StrictMode:  at io.fabric.sdk.android.services.concurrency.AsyncTask$2.call(AsyncTask.java:311)
08-30 13:25:17.535  6437  6446 E StrictMode:  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-30 13:25:17.535  6437  6446 E StrictMode:  at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
08-30 13:25:17.535  6437  6446 E StrictMode:  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
08-30 13:25:17.535  6437  6446 E StrictMode:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
08-30 13:25:17.535  6437  6446 E StrictMode:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
08-30 13:25:17.535  6437  6446 E StrictMode:  at java.lang.Thread.run(Thread.java:761)
08-30 13:25:17.535  6437  6446 W System.err: StrictMode VmPolicy violation with POLICY_DEATH; shutting down.
```

**Comment by JakeWharton** [comment]
This is not an OkHttp bug. Looks like Fabric is opening an `HttpURLConnection` that they aren't closing the body of. Report to Fabric.

**Comment by plentz** [comment]
@JakeWharton thanks
