### ISSUE TITLE
Flaky recoverWhenRetryOnConnectionFailureIsFalse_HTTP2 test

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#3565]
```
Tests run: 166, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 36.553 sec <<< FAILURE! - in okhttp3.CallTest
recoverWhenRetryOnConnectionFailureIsFalse_HTTP2(okhttp3.CallTest)  Time elapsed: 0.236 sec  <<< FAILURE!
java.lang.AssertionError: closed
	at okhttp3.RecordedResponse.assertFailureMatches(RecordedResponse.java:170)
	at okhttp3.CallTest.noRecoverWhenRetryOnConnectionFailureIsFalse(CallTest.java:1018)
	at okhttp3.CallTest.recoverWhenRetryOnConnectionFailureIsFalse_HTTP2(CallTest.java:1025)

```

**Comment by swankjesse** [comment]
Hasn’t been problematic lately.
