### ISSUE TITLE
OkHttp 3.9.0 IllegalStateException with Cookies and ProGuard

### ISSUE THREAD

**Issue by talklittle** [square/okhttp#3582]
Sample project: https://github.com/talklittle/TestOkHttp3.9.0

Crashes with OkHttp 3.9.0; works with OkHttp 3.8.1

Crashes with `minifyEnabled true`; works with `minifyEnabled false`

I guess ProGuard is stripping away `src/main/resources/`.

```
java.lang.IllegalStateException: Unable to load publicsuffixes.gz resource from the classpath.
       at okhttp3.internal.publicsuffix.PublicSuffixDatabase.findMatchingRule(PublicSuffixDatabase.java:120)
       at okhttp3.internal.publicsuffix.PublicSuffixDatabase.getEffectiveTldPlusOne(PublicSuffixDatabase.java:83)
       at okhttp3.Cookie.parse(Cookie.java:311)
       at okhttp3.Cookie.parse(Cookie.java:219)
       at okhttp3.Cookie.parseAll(Cookie.java:445)
       at okhttp3.internal.http.HttpHeaders.receiveHeaders(HttpHeaders.java:201)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
       at okhttp3.RealCall.execute(RealCall.java:77)
```

**Comment by talklittle** [comment]
**Does not work:** Proguard rule `-keepdirectories src/main/resources/okhttp3/**`

**Does not work:** Copying `publicsuffixes.gz` into app's `src/main/resources/okhttp3/internal/publicsuffix/publicsuffixes.gz`, even combined with above proguard rule.

**Comment by csshuai** [comment]
Worked: Proguard rule `-keep class okhttp3.internal.publicsuffix.PublicSuffixDatabase`

**Comment by schildbach** [comment]
I recently ran into this issue, because I excluded the file from my APK. There were no problems for years, but it started crashing some weeks ago. I assume the server operator changed cookie configuration.

Is there an alternative to including the file again, like switching off support for cookies? I don't need cookies because I'm querying a stateless API.

**Comment by yschimke** [comment]
@schildbach That was the conclusion I came to, avoid cookies if you can't include.  https://github.com/square/okhttp/issues/7095#issuecomment-1046261963
