### ISSUE TITLE
I have a lot of thread locked in my tomcat, and this may be related to okhttp

### ISSUE THREAD

**Issue by peterxiemin** [square/okhttp#3583]
There are a lot of thread lock, the following is jstack information. I do not know why this will happen, which leads to my memory and cpu are rising

"http-nio-8891-exec-152" #571 daemon prio=5 os_prio=0 tid=0x00007f79047a2000 nid=0x5a2c waiting for monitor entry [0x00007f78e4380000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at okio.AsyncTimeout.scheduleTimeout(AsyncTimeout.java:75)
	- waiting to lock <0x0000000087b012a0> (a java.lang.Class for okio.AsyncTimeout)
	at okio.AsyncTimeout.enter(AsyncTimeout.java:69)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:209)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	at com.squareup.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
	at com.squareup.okhttp.Call.getResponse(Call.java:287)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.farmfriend.common.http.OkHttpRetryHandler.chainProceed(OkHttpRetryHandler.java:48)
	at com.farmfriend.common.http.OkHttpRetryHandler.retryHandler(OkHttpRetryHandler.java:31)
	at com.farmfriend.common.http.OkHttpRetryHandler.intercept(OkHttpRetryHandler.java:25)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
	at com.farmfriend.common.http.OkHttpAddHeaderHandler.addHeadersHandler(OkHttpAddHeaderHandler.java:41)
	at com.farmfriend.common.http.OkHttpAddHeaderHandler.intercept(OkHttpAddHeaderHandler.java:27)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
	at com.farmfriend.common.http.OkHttpUtil.post(OkHttpUtil.java:90)
	at com.farmfriend.common.http.OkHttpUtil.ral(OkHttpUtil.java:110)
	at com.farmfriend.weather.util.MojiWeatherUtil.getWeatherInfoFromNet(MojiWeatherUtil.java:43)
	at com.farmfriend.weather.service.impl.GetMojiWeatherInfoServiceImpl.getMapToWeatherEntity(GetMojiWeatherInfoServiceImpl.java:459)
	at com.farmfriend.weather.service.impl.GetMojiWeatherInfoServiceImpl.getOrderInfoWeather(GetMojiWeatherInfoServiceImpl.java:171)
	at com.farmfriend.weather.controller.WeatherServerController.getOrderInfoWeather(WeatherServerController.java:75)
	at com.farmfriend.weather.controller.WeatherServerController$$FastClassBySpringCGLIB$$5b434648.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.framework.adapter.MethodBeforeAdviceInterceptor.invoke(MethodBeforeAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.aspectj.AspectJAfterAdvice.invoke(AspectJAfterAdvice.java:47)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.framework.adapter.AfterReturningAdviceInterceptor.invoke(AfterReturningAdviceInterceptor.java:52)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:168)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
	at com.farmfriend.weather.controller.WeatherServerController$$EnhancerBySpringCGLIB$$1a7115a.getOrderInfoWeather(<generated>)
	at sun.reflect.GeneratedMethodAccessor524.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
	- locked <0x00000000f20a5f90> (a org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

my okhttp version 2.7.5

**Comment by peterxiemin** [comment]
ok!  following is whole dump file : 


[dump.zip](https://github.com/square/okhttp/files/1276495/dump.zip)

**Comment by peterxiemin** [comment]
my issue is same as https://github.com/square/okio/issues/214 ?

**Comment by swankjesse** [comment]
Here’s the thread that currently holds the lock. It’s doing pretty normal-looking work. This is disappointing because I was hoping to find a smoking gun here. Instead it’s just a regular thread that’s doing what should be a very fast operation.

```
"http-nio-8891-exec-8" #62 daemon prio=5 os_prio=0 tid=0x00007f790410b000 nid=0x4f70 runnable [0x00007f78f71ef000]
   java.lang.Thread.State: RUNNABLE
	at okio.AsyncTimeout.scheduleTimeout(AsyncTimeout.java:95)
	- locked <0x0000000087b012a0> (a java.lang.Class for okio.AsyncTimeout)
	at okio.AsyncTimeout.enter(AsyncTimeout.java:69)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:153)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:221)
	at com.squareup.okhttp.internal.http.Http1xStream.finishRequest(Http1xStream.java:161)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:735)
	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
	at com.squareup.okhttp.Call.getResponse(Call.java:287)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
	at com.farmfriend.common.http.OkHttpRetryHandler.chainProceed(OkHttpRetryHandler.java:48)
	at com.farmfriend.common.http.OkHttpRetryHandler.retryHandler(OkHttpRetryHandler.java:31)
	at com.farmfriend.common.http.OkHttpRetryHandler.intercept(OkHttpRetryHandler.java:25)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:232)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
	at com.squareup.okhttp.Call.execute(Call.java:80)
```

Two potential things to try next:

1. Upgrade to the latest Okio and OkHttp. You’re running code that’s a few years old and I can’t be sure we didn’t fix something that could have caused this.

2. Can you attach a debugger and tell me the size of the linked list of `AsyncTimeout` objects starting at `AsyncTimeout.head` ? It isn’t a `java.util.LinkedList` but a hasty manual one, so you’ll need to actually count manually by following references until you get a `null` next.

One other thing that could potentially cause this – if a bug somehow caused that linked list to contain a cycle, we’re doomed. And being doomed like that would fail exactly like this. I don’t think there’s any code that could cause such a cycle, but that’s my best hypothesis for what could cause this.

So next steps: please upgrade OkHttp + Okio. If the problem continues, please tell me the length of the linked list. In the interim I’ll study the code to check for something that could cause that.

**Comment by peterxiemin** [comment]
I change my okhttp version to  version 3.8.1 , the issue of AsyncTimeout lock not reproduce。 but there is a new issue in my tomcat . I suspect that the two questions are the same cause
          **blow thread #59 is always runnable and never exit, this lead to cpu almost 100%** 
"http-nio-8891-exec-4" #59 daemon prio=5 os_prio=0 tid=0x00007fa4f801a800 nid=0xce2 runnable [0x00007fa4f7cb3000]
   java.lang.Thread.State: RUNNABLE
        at okio.Buffer.indexOf(Buffer.java:1317)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:339)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:217)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
        at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:441)
        at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:425)
        at okio.Buffer.writeAll(Buffer.java:1005)
        at okio.RealBufferedSource.readString(RealBufferedSource.java:190)
        at okhttp3.ResponseBody.string(ResponseBody.java:175)
        at com.farmfriend.common.http.OkHttpUtil.get(OkHttpUtil.java:56)
        at com.farmfriend.common.http.OkHttpUtil.ral(OkHttpUtil.java:114)
        at com.farmfriend.common.interceptor.LoginInterceptor.preHandle(LoginInterceptor.java:46)
        at org.springframework.web.servlet.HandlerExecutionChain.applyPreHandle(HandlerExecutionChain.java:134)
        at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:958)
        at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
        at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
        at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:872)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:648)
        at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:846)
        at javax.servlet.http.HttpServlet.service(HttpServlet.java:729)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:230)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:105)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:197)
        at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
        at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:192)
        at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:165)
        at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:198)
        at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)
        at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:474)
        at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)
        at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79)
        at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)
        at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:349)
        at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:783)
        at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)
        at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:798)
        at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1434)
        at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)
        - locked <0x0000000087b11bb8> (a org.apache.tomcat.util.net.NioEndpoint$NioSocketWrapper)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)
        at java.lang.Thread.run(Thread.java:745)

        **following is whole dump file :** 
[dumpfile.zip](https://github.com/square/okhttp/files/1292698/dumpfile.zip)

**Comment by yschimke** [comment]
I suspect the response is corrupt and the status line isn't correctly encoded or is missing.

@swankjesse is it worth revisiting https://github.com/square/okhttp/issues/2152

https://maxchadwick.xyz/blog/http-request-header-size-limits
https://community.fastly.com/t/general-size-limits-cookies-headers-urls/284

This seems like an attack vector against clients.

**Comment by peterxiemin** [comment]
please tell me how to fix this issue?

**Comment by peterxiemin** [comment]
I print log of endless loop。I think this is a bug : 

**2017-09-18 21:14:53.588 [http-nio-8891-exec-8] INFO  okio.Buffer [Buffer.java:1321] kio monitor s : okio.Segment@7375dccf, s.next : okio.Segment@7375dccf, s.limit : 274, s.pos : 304, offset : -270089850, nextOffset : -270089880, fromIndex : 0**

the Buffer.java source code : 
        **for (long nextOffset; (nextOffset = offset + (s.limit - s.pos)) < fromIndex; ) {
          s = s.next;
          offset = nextOffset;**
it will be not stop util exceed long value limit;

**Comment by swankjesse** [comment]
Looks like you’ve got a concurrency problem that is corrupting your memory. Can you try running this at the beginning of your program?

```
    try {
      // Use reflection to disable segment pooling. This prevents concurrency
      // problems from causing corruption across threads.
      Class.forName("okio.Segment").getDeclaredField("SIZE").set(null, 0);
    } catch (Exception e) {
      throw new RuntimeException(e);
    }
```

**Comment by peterxiemin** [comment]
looks like I can't set Segment.size.
Caused by: java.lang.IllegalAccessException: Class com.farmfriend.common.CommonApplication$1 can not access a member of class okio.Segment with modifiers "static final"
	at sun.reflect.Reflection.ensureMemberAccess(Reflection.java:102)
	at java.lang.reflect.AccessibleObject.slowCheckMemberAccess(AccessibleObject.java:296)
	at java.lang.reflect.AccessibleObject.checkAccess(AccessibleObject.java:288)
	at java.lang.reflect.Field.set(Field.java:761)
Btw,  okio or okhttp is not threadsafe?  or  I am using it wrongly?

**Comment by chenpengfei88** [comment]
看不懂啊

**Comment by swankjesse** [comment]
Unclear what action to take here. There’s definitely a problem but we need an executable test case or something to reproduce.
