### ISSUE TITLE
I have a crash report, is it a concurrency problem

### ISSUE THREAD

**Issue by SundyJin** [square/okhttp#3601]
OkHttp Dispatcher(2116)
java.lang.ArrayIndexOutOfBoundsException
size=1 offset=0 byteCount=640

okio.Util.checkOffsetAndCount(Util.java:30)
--
okio.AsyncTimeout$1.write(AsyncTimeout.java:162)
okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
okio.RealBufferedSink.writeByte(RealBufferedSink.java:117)
okhttp3.internal.http2.Http2Writer.writeMedium(Http2Writer.java:291)
okhttp3.internal.http2.Http2Writer.frameHeader(Http2Writer.java:279)
okhttp3.internal.http2.Http2Writer.dataFrame(Http2Writer.java:181)
okhttp3.internal.http2.Http2Writer.data(Http2Writer.java:176)
okhttp3.internal.http2.Http2Connection.writeData(Http2Connection.java:293)
okhttp3.internal.http2.Http2Stream$FramingSink.emitFrame(Http2Stream.java:514)
okhttp3.internal.http2.Http2Stream$FramingSink.write(Http2Stream.java:485)
okio.RealBufferedSink.emit(RealBufferedSink.java:178)

**Comment by JakeWharton** [comment]
ResponseBody is not thread safe. This usually indicates you are writing
from different threads.

**Comment by SundyJin** [comment]
It looks like the send buffer is not thread safe, but I did not open a extra thread to write data.

**Comment by yschimke** [comment]
Is this still happening with recent OkHttp? Is it reproducible? If not, I'll close the issue.

**Comment by lkishor** [comment]
Hi Team, 
Getting a lot of these on Crashlytics:
OkHttp : 3.12.0
OkIo : 2.1.0
Is there a way to find which API am I calling when this comes?

`Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: size=1 offset=0 byteCount=30
       at okio.-Util.checkOffsetAndCount(-Util.kt:23)
       at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:85)
       at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:181)
       at okio.RealBufferedSink.write(RealBufferedSink.kt:127)
       at okhttp3.internal.http2.Http2Writer.writeMedium(Http2Writer.java:283)
       at okhttp3.internal.http2.Http2Writer.frameHeader(Http2Writer.java:271)
       at okhttp3.internal.http2.Http2Writer.goAway(Http2Writer.java:238)
       at okhttp3.internal.http2.Http2Connection.shutdown(Http2Connection.java:432)
       at okhttp3.internal.http2.Http2Connection.close(Http2Connection.java:448)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.execute(Http2Connection.java:618)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.lang.Thread.run(Thread.java:764)`
