### ISSUE TITLE
Why okhttp gets "Proxy-Authorization" value from custom Authenticator instead of header map.

### ISSUE THREAD

**Issue by Leaking** [square/okhttp#3607]
Read the source code of method [okhttp3.internal.connection.RealConnection#createTunnel](https://github.com/square/okhttp/blob/9b0d19f913465483d0942558eb21e37868040050/okhttp/src/main/java/okhttp3/internal/connection/RealConnection.java#L344). I find something which seems strange. 

Okhttp get "Proxy-Authorization" value from custom Authenticator like below lines:

```java
Authenticator authenticator = new Authenticator() {
         @Override
         public Request authenticate(Route route, Response response) throws IOException {
         return response.request().newBuilder()
                        .header("Proxy-Authorization", credential)
                        .build();
         }
 };
OkHttpClient okHttpClient = new OkHttpClient.Builder().proxy(proxy).proxyAuthenticator(authenticator).build();
```

These lines of code will work properly.

But If we just add "Proxy-Authorization"in request header without  a custom Authenticator

```java
//Step 1:  Initial a okhttpclient with a proxy
OkHttpClient client = new OkHttpClient.Builder()
        .proxy(proxy)
        .build();

//Step 2: add proxy credential message to request headers
request.newBuilder()
      .header(proxyAuthorization ? "Proxy-Authorization" : "Authorization", credential)
      .build();
```
 
we will get the following crash. I think lots of developers have come acroos the same crash.

```java
 java.io.IOException: Failed to authenticate with proxy
               at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.java:362)
               at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:199)
               at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:147)
               at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
               at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
               at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
```
      

My question is why okhttp gets "Proxy-Authorization" value from custom Authenticator instead of header map?

**Comment by swankjesse** [comment]
So we don't leak proxy credentials to the origin webserver.
