### ISSUE TITLE
NullPointerException at BasicTrustRootIndex when caCert.getSubjectX500Principal() is null

### ISSUE THREAD

**Issue by bgorkowy** [square/okhttp#3627]
We are seeing NullPointerException crashes, mainly from Samsung devices running 4.1.2 and 4.2.2. We have custom TrustManager, but it delegates to platform default getAcceptedIssuers() method. Version 3.8.1. Stack:

`
Fatal Exception: java.lang.NullPointerException
       at org.apache.harmony.security.provider.cert.X509CertImpl.getEncoded(X509CertImpl.java:346)
       at java.security.cert.Certificate.hashCode(Certificate.java:102)
       at java.util.HashMap.put(HashMap.java:390)
       at java.util.HashSet.add(HashSet.java:95)
       at okhttp3.internal.tls.TrustRootIndex$BasicTrustRootIndex.(SourceFile)
       at okhttp3.internal.tls.TrustRootIndex.get(SourceFile:48)
       at okhttp3.internal.tls.TrustRootIndex.get(SourceFile:43)
       at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(SourceFile:167)
       at okhttp3.internal.platform.AndroidPlatform.buildCertificateChainCleaner(SourceFile:173)
       at okhttp3.internal.tls.CertificateChainCleaner.get(SourceFile:41)
       at okhttp3.OkHttpClient$Builder.sslSocketFactory(SourceFile:696)
`

Could caCert.getSubjectX500Principal() even return null for a CA cert? Is this maybe a sign of misconfigured system CAs on those devices?

**Comment by yschimke** [comment]
Yes, it looks like a bug in an old manufacturer version of Android.  Without a reproduction it will be tough to confirm.

**Comment by yschimke** [comment]
There isn't much for us to do here since it's failing inside another codebase
