### ISSUE TITLE
Samsung Android 4.2.2 NullPointer in okhttp3.internal.connection.RealConnection.connectTls

### ISSUE THREAD

**Issue by tulioht** [square/okhttp#3634]
Samsung Android 4.2.2 only

Fatal Exception: java.lang.NullPointerException
       at org.apache.harmony.xnet.provider.jsse.TrustedCertificateIndex.findBySubjectAndPublicKey(TrustedCertificateIndex.java:126)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.findTrustAnchorBySubjectAndPublicKey(TrustManagerImpl.java:413)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.cleanupCertChainAndFindTrustAnchors(TrustManagerImpl.java:384)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:225)
       at org.apache.harmony.xnet.provider.jsse.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:203)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:598)
       at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(NativeCrypto.java)
       at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:379)
       at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:299)
       at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268)
       at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
       at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
       at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
       at java.lang.Thread.run(Thread.java:856)

**Comment by yschimke** [comment]
I suspect at a glance this is a bug in an old manufacturer version of Android.  If you can provide a reproduction via an emulator we can confirm and potentially look at a workaround, but without that it's tough.

**Comment by tulioht** [comment]
Does not give the bug in the emulator emulator, in my Crashlytics only the Samsung S3 Slim with Android 4.2.2 is included, this is the second most common bug in my App
This cell phone is very common in my country.

**Comment by swankjesse** [comment]
This is an issue with the device. Not a lot we can do from OkHttp.

One option you might be able to try is installing the GMS security provider. That’ll get you on an updated TLS stack.
https://developer.android.com/training/articles/security-gms-provider.html
