### ISSUE TITLE
Unexpected OOME while loading publicsuffixes.gz

### ISSUE THREAD

**Issue by bidetofevil** [square/okhttp#3658]
We’re seeing some strange OutOfMemoryExceptions coming from OkHttp 3.9, namely from PublicSuffixDatabase trying to read in publicsuffixes.gz. Rarely but consistently, we’ve seen OOM crashes where, according to the stacktraces, it appears the resource being read in is impossibly large (500 MB+) or the total bytes reported by the created BufferedSource is crazy large too (1.5 GB+).

I don't have a test or reproduction scenario, as we are only seeing this in production in the crash reports we receive. While there have been instances of crashes from various OS versions and device manufacturers, the vast majority (disproportional from our typical usage distribution) comes from Samsung phones running M.

A couple of sample stacktraces can be found below:

```
Caused by java.lang.OutOfMemoryError: Failed to allocate a 1768847725 byte allocation with 7394266 free bytes and 490MB until OOM
       at okhttp3.internal.publicsuffix.PublicSuffixDatabase.readTheList(Twttr:319)
       at okhttp3.internal.publicsuffix.PublicSuffixDatabase.readTheListUninterruptibly(Twttr:289)
       at okhttp3.internal.publicsuffix.PublicSuffixDatabase.findMatchingRule(Twttr:110)
       at okhttp3.internal.publicsuffix.PublicSuffixDatabase.getEffectiveTldPlusOne(Twttr:83)
       at okhttp3.Cookie.parse(Twttr:311)
       at okhttp3.Cookie.parse(Twttr:219)
       at okhttp3.Cookie.parseAll(Twttr:445)
       at okhttp3.internal.http.HttpHeaders.receiveHeaders(Twttr:201)
       at okhttp3.internal.http.BridgeInterceptor.intercept(Twttr:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(Twttr:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(Twttr:125)
       at okhttp3.internal.http.RealInterceptorChain.proceed(Twttr:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(Twttr:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(Twttr:200)
       at okhttp3.RealCall.execute(Twttr:77)
```
```
Caused by java.lang.OutOfMemoryError: Failed to allocate a 535394406 byte allocation with 8388608 free bytes and 239MB until OOM
       at java.io.ByteArrayOutputStream.expand(ByteArrayOutputStream.java:91)
       at java.io.ByteArrayOutputStream.write(ByteArrayOutputStream.java:201)
       at libcore.io.Streams.readFullyNoClose(Streams.java:109)
       at libcore.io.Streams.readFully(Streams.java:95)
       at java.util.jar.JarFile.readMetaEntries(JarFile.java:337)
       at java.util.jar.JarFile.(JarFile.java)
       at libcore.net.url.JarURLConnectionImpl.openJarFile(JarURLConnectionImpl.java:136)
       at libcore.net.url.JarURLConnectionImpl.findJarFile(JarURLConnectionImpl.java:113)
       at libcore.net.url.JarURLConnectionImpl.connect(JarURLConnectionImpl.java:82)
       at libcore.net.url.JarURLConnectionImpl.getInputStream(JarURLConnectionImpl.java:215)
       at java.net.URL.openStream(URL.java:470)
       at java.lang.ClassLoader.getResourceAsStream(ClassLoader.java:444)
       at java.lang.Class.getResourceAsStream(Class.java:1175)
       at okhttp3.internal.publicsuffix.PublicSuffixDatabase.readTheList(Twttr:309)
       at okhttp3.internal.publicsuffix.PublicSuffixDatabase.readTheListUninterruptibly(Twttr:289)
       at okhttp3.internal.publicsuffix.PublicSuffixDatabase.findMatchingRule(Twttr:110)
       at okhttp3.internal.publicsuffix.PublicSuffixDatabase.getEffectiveTldPlusOne(Twttr:83)
       at okhttp3.Cookie.parse(Twttr:311)
       at okhttp3.Cookie.parse(Twttr:219)
       at okhttp3.Cookie.parseAll(Twttr:445)
       at okhttp3.internal.http.HttpHeaders.receiveHeaders(Twttr:201)
       at okhttp3.internal.http.BridgeInterceptor.intercept(Twttr:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(Twttr:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(Twttr:125)
       at okhttp3.internal.http.RealInterceptorChain.proceed(Twttr:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(Twttr:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(Twttr:200)
       at okhttp3.RealCall.execute(Twttr:77)
```

**Comment by samwencn** [comment]
Multi Thread?

**Comment by bidetofevil** [comment]
Yeah, definitely multi-thread. But isn't access to this code internally synchronized?

**Comment by dave-r12** [comment]
Yikes. I'll see if I can spot anything.

**Comment by dave-r12** [comment]
Haven't been able to come up with anything yet. Loading the public suffixes is guarded by a CAS so shouldn't be loaded multiple times.

The first stack trace seems to indicate it's asking for a very large byte array. The only thing that seems suspect here is the size of the array is read from the resource itself. So if that is somehow corrupted it might ask for a very large array. Unsure how possible that is though.

The second stack trace appears to say it failed reading the resource itself. I don't know if that's one we should bring up to the Android team? Or there is something about the way we are loading the resource that is incorrect.

I'll keep looking.

**Comment by yschimke** [comment]
Maybe something we should consider avoiding anyway

http://blog.nimbledroid.com/2016/04/06/slow-ClassLoader.getResourceAsStream.html
https://github.com/JakeWharton/ThreeTenABP
http://blog.danlew.net/2013/08/20/joda_time_s_memory_issue_in_android/

@JakeWharton 
> Similar to the problems with using Joda-Time on Android, the threetenbp uses a JAR resource for loading timezone information. This is an extremely inefficient mechanism on Android.
> 
> This library places the timezone information as a standard Android asset and provides a custom loader for parsing it efficiently.

**Comment by dave-r12** [comment]
@yschimke good find. That's unfortunate.

**Comment by yschimke** [comment]
@dave-r12 @JakeWharton is it worth abstracting loading resources through the Platform class, and using assets on Android and Class loader resources on the JVM?

https://github.com/JakeWharton/ThreeTenABP/blob/master/threetenabp/src/main/java/com/jakewharton/threetenabp/AndroidThreeTen.java

```
 InputStream is = null;
    try {
      is = context.getAssets().open("org/threeten/bp/TZDB.dat");
```

**Comment by JakeWharton** [comment]
We don't have a way to deliver it as an asset unless we publish an
Android-specific binary aar instead of jar.

**Comment by yschimke** [comment]
Is it better to encode as a field in a class or similar then?  Or just live with it?

**Comment by JakeWharton** [comment]
Yes. We could switch it to generate a classfile or source file.

**Comment by swankjesse** [comment]
Ick. I don’t think we should change how this works; it works correctly for almost everyone. The performance problem of resource loading is unlikely to make a big difference here; loading a class file with all this data will likely need to do even more work.

Closing for now.
