### ISSUE TITLE
NullPointerException in handshake

### ISSUE THREAD

**Issue by GrahamBorland** [square/okhttp#3663]
This is a report from end users, via Crashlytics. We do not have repro steps.

A few users complain that our app repeatedly crashes. From what I can tell, all affected users so far are using the same device (Meizu M5). From what I can tell, it happens every time our app attempts a network request.

OS version: 6.0
OkHttp version: 3.9.0
Device: Meizu M5

Is this a platform bug, or is there anything OkHttp (or we app authors!) can do to work around it?

```
Fatal Exception: java.lang.NullPointerException: ssl_session == null
       at com.android.org.conscrypt.NativeCrypto.SSL_SESSION_cipher(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLSessionImpl.getCipherSuite(OpenSSLSessionImpl.java:320)
       at io.intercom.okhttp3.Handshake.get(Handshake.java:49)
       at io.intercom.okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:268)
       at io.intercom.okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:237)
       at io.intercom.okhttp3.internal.connection.RealConnection.connect(RealConnection.java:148)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:186)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
       at io.intercom.okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
       at io.intercom.okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
       at io.intercom.okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
       at io.intercom.okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
       at io.intercom.okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
       at io.intercom.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by swankjesse** [comment]
Sounds like a device bug. Could you report it to the manufacturer?

I’m not sure what our workaround would look like; seems like this device isn't able to do SSL with whichever URL you're requesting.

**Comment by swankjesse** [comment]
Lets track this here:
https://github.com/square/okhttp/issues/3301
