### ISSUE TITLE
error connect to http2 server

### ISSUE THREAD

**Issue by onesea** [square/okhttp#3666]
server is written in nghttp2, okhttp client can not connect via http/2, seems it still use http 1.1. what is the problem? thanks!

**Comment by JakeWharton** [comment]
You haven't provided any information to diagnose a cause.

**Comment by onesea** [comment]
hello,

url: https://gw.codein.net/echo method: POST body: [{'name':'Jesse},{'name':'Jake}]
java.io.IOException: unexpected end of stream on Connection{gw.codein.net:443, proxy=DIRECT hostAddress=gw.codein.net/39.108.239.170:443 cipherSuite=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 protocol=http/1.1}

**Comment by onesea** [comment]
and it is okay if i use curl to connect the same server

**Comment by onesea** [comment]
this is out when running on windows.

java.io.IOException: unexpected end of stream on Connection{gw.codein.net:443, proxy=DIRECT hostAddress=gw.codein.net/39.108.239.170:443 cipherSuite=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384 protocol=http/1.1}
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:203)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:211)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:187)
	... 19 more

**Comment by yschimke** [comment]
Just confirmed this works fine with OkHttp using a curl like client

```
$ oksocial --debug -d '[{'name':'Jesse},{'name':'Jake}]' https://gw.codein.net/echo
06:54:31.454	url https://gw.codein.net/echo
06:54:31.476	Request Request{method=POST, url=https://gw.codein.net/echo, tag=null}
06:54:31.495	Dns (gw.codein.net): gw.codein.net/39.108.239.170
06:54:32.733	>> CONNECTION 505249202a20485454502f322e300d0a0d0a534d0d0a0d0a
06:54:32.734	>> 0x00000000     6 SETTINGS
06:54:32.735	>> 0x00000000     4 WINDOW_UPDATE
06:54:32.744	--> POST https://gw.codein.net/echo h2
06:54:32.744	Content-Type: application/x-www-form-urlencoded
06:54:32.744	Content-Length: 26
06:54:32.745	User-Agent: oksocial/1.0.54
06:54:32.745	Host: gw.codein.net
06:54:32.745	Connection: Keep-Alive
06:54:32.745	Accept-Encoding: gzip
06:54:32.745	--> END POST
06:54:32.749	>> 0x00000003    68 HEADERS       END_HEADERS
06:54:32.750	>> 0x00000003    26 DATA          END_STREAM
06:54:33.012	<< 0x00000000     6 SETTINGS
06:54:33.013	>> 0x00000000     0 SETTINGS      ACK
06:54:33.291	<< 0x00000000     0 SETTINGS      ACK
06:54:33.292	<< 0x00000003    34 HEADERS       END_HEADERS
06:54:33.292	<< 0x00000003    36 DATA          END_STREAM
06:54:33.294	<-- 200  https://gw.codein.net/echo (548ms)
06:54:33.295	date: Wed, 25 Oct 2017 13:54:33 GMT
06:54:33.295	content-type: text/plain
06:54:33.295	<-- END HTTP
echoing: [{name:Jesse},{name:Jake}]

06:54:33.382	>> 0x00000000     8 GOAWAY
```

I suspect you need the alpn-boot jar.  Alternatively, test with Java 9.

https://github.com/square/okhttp/wiki/Building

If need further help, could I ask you to post in stackoverflow (after searching for similar posts) and link here.
