### ISSUE TITLE
BUG: OkHttp 3.9.0 et. al. Does Not Support HTTPS Proxying With User Installed Certificates

### ISSUE THREAD

**Issue by phlogistic** [square/okhttp#3681]
okhttp is not honoring user-installed certificates for wifi proxy + https on multiple versions of android.

1. Install a certificate onto the android device using settings/lock screen & security/other security settings/install from device storage + setting 
2. go to connections/wi-fi/long touch on AP/manage network settings/show advanced options/proxy/set to manual & enter IP to proxy thru
3. get thrown a stack such as the below

	11-09 09:01:55.528 26293 26371 D OkHttp  : <-- HTTP FAILED: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	11-09 09:01:55.530 26293 26372 D OkHttp  : <-- HTTP FAILED: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	11-09 09:01:55.534 26293 26293 V BaseActivity: handleLoading
	11-09 09:01:55.534 26293 26293 V BaseActivity: handleLoading...
	11-09 09:01:55.534 26293 26293 V BaseActivity: not refreshing...
	11-09 09:01:55.534 26293 26293 V BaseActivity: loading layout is not null... isOn: false
	11-09 09:01:55.535 26293 26293 E MainActivity: Fetch gatekeeper call failed
	11-09 09:01:55.540 26293 26293 E MainActivity: Fetch gatekeeper call failed
	11-09 09:01:55.540 26293 26293 E MainActivity: javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	11-09 09:01:55.540 26293 26293 E MainActivity:  at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:368)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.connection.RealConnection.a(SourceFile:299)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.connection.RealConnection.a(SourceFile:268)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.connection.RealConnection.connect(SourceFile:160)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.connection.StreamAllocation.a(SourceFile:256)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.connection.StreamAllocation.a(SourceFile:134)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:113)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:42)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:93)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:125)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.logging.HttpLoggingInterceptor.intercept(SourceFile:212)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at com.___.___.api.LoggingInterceptor.intercept(SourceFile:22)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at com.___.___.api.HeaderInterceptor.intercept(SourceFile:39)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at biv.e(SourceFile:200)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at biv$a.execute(SourceFile:147)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at okhttp3.internal.NamedRunnable.run(SourceFile:32)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at java.lang.Thread.run(Thread.java:762)
	11-09 09:01:55.540 26293 26293 E MainActivity: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	11-09 09:01:55.540 26293 26293 E MainActivity:  at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:546)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:427)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:491)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:387)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:361)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:290)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:178)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:617)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	11-09 09:01:55.540 26293 26293 E MainActivity:  at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:364)
	11-09 09:01:55.540 26293 26293 E MainActivity:  ... 32 more
	11-09 09:01:55.540 26293 26293 E MainActivity: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
	11-09 09:01:55.540 26293 26293 E MainActivity:  ... 44 more

To recreate, this behavior is present in apps using okhttp in Google Play such as https://play.google.com/store/apps/details?id=com.fandango and https://play.google.com/store/apps/details?id=com.stockx.stockx

Apps not using okhttp allow using a proxy with a user installed certificate normally.

The purpose of this is to be able to monitor network traffic for vulnerabilities using proxy tools such as https://portswigger.net/ or https://www.charlesproxy.com/ or https://www.owasp.org/index.php/OWASP_Zed_Attack_Proxy_Project

**Comment by swankjesse** [comment]
Which version of Android?

**Comment by phlogistic** [comment]
Confirmed on 5 & 7

**Comment by swankjesse** [comment]
Strange. Note that OkHttp doesn’t manage the list of root certificates and can’t differentiate between system CAs and user CAs.

**Comment by phlogistic** [comment]
*shrug* in other apps w/o later versions of okhttp this works

**Comment by ubuntudroid** [comment]
Can't confirm, using OkHttp with Charles proxy and user CA without any problems.

**Comment by phlogistic** [comment]
Did you try the apps aforementioned?

**Comment by ubuntudroid** [comment]
No, but works perfectly fine with my own apps.

**Comment by phlogistic** [comment]
OK, let us know when you try the apps in question having a problem. You can get them straight from google play.

**Comment by yschimke** [comment]
This seems like this might possibly relate to this https://stackoverflow.com/a/38770284/1542667

But generally this is probably a better question for Stackoverflow than our bug tracker.

Also, how certain are we that these particular apps don't use Certificate pinning, host verification or specific known CA certificates for their connections?  As these are reasonably sized apps, I'd be very surprised if they left themselves open the MITM scenarios.

**Comment by phlogistic** [comment]
100% sure that the apps are not using certificate pinning.

**Comment by somdas** [comment]
I am also facing the same issue. I was able to make it work properly with charles proxy with user installed CA and putting network security config, where I trusted system and user CAs.  But all of a sudden, its not working today. My version is  3.6.0. The CONNECT fails.

@phlogistic did your problem get solved.

**Comment by GaborPeto** [comment]
It is also failing for me on version 3.9.0 and 3.10.0
I have `android:networkSecurityConfig` setup in my project and it was previously working just fine.

**Comment by cogentParadigm** [comment]
Adding a network security configuration as described in the link provided by @yschimke worked for me.
