### ISSUE TITLE
unexpected end of stream,content length is correct.

### ISSUE THREAD

**Issue by liqian685** [square/okhttp#3682]
The Exception will happen sometime,when i download file form a same url. The content-length is same value，so I guess the content-length is correct. what should i do？

use URLConnection
 java.net.ProtocolException: unexpected end of stream
      at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:421)
      at com.android.okhttp.okio.RealBufferedSource$1.read(RealBufferedSource.java:371)
      at java.io.InputStream.read(InputStream.java:101)
      at com.liulishuo.filedownloader.download.FetchDataTask.run(FetchDataTask.java:139)
      at com.liulishuo.filedownloader.download.DownloadRunnable.run(DownloadRunnable.java:115)
      at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
      at java.util.concurrent.FutureTask.run(FutureTask.java:237)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
      at java.lang.Thread.run(Thread.java:761)

use okhttp3
java.net.ProtocolException: unexpected end of stream
     at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:398)
     at okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
     at java.io.InputStream.read(InputStream.java:101)
     at com.liulishuo.filedownloader.download.FetchDataTask.run(FetchDataTask.java:133)
     at com.liulishuo.filedownloader.download.DownloadRunnable.run(DownloadRunnable.java:114)
     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
     at java.lang.Thread.run(Thread.java:761)

**Comment by yschimke** [comment]
Given the scope of these projects is multithreaded chunked downloads etc

https://github.com/lingochamp/FileDownloader
https://github.com/Jacksgong/filedownloader-okhttp3-connection

I would suggest starting with raising an issue on these projects.  Or produce a reproducing test case app using these libraries that we can test with without writing it ourselves.

Also details like the url or size of files you are downloading.

I've got an example app I could share with you as a base if it helps.

**Comment by liqian685** [comment]
i found the exception when i use the FileDownloader demo.

**Comment by yschimke** [comment]
@liqian685 awesome, I'll try reproducing with the demo.

**Comment by yschimke** [comment]
The demo worked for me, do you have more details about what can trigger the failure?

**Comment by swankjesse** [comment]
No action for us to take on this.
