### ISSUE TITLE
java.net.UnknownHostException with OkHttp, but HttpURLConnection works normally

### ISSUE THREAD

**Issue by don11995** [square/okhttp#3684]
Hello! I faced with strange problem and I do not know what to do. My code:

```
OkHttpClient client = new OkHttpClient.Builder()
                .connectTimeout(TIMEOUT_MILLIS, TimeUnit.MILLISECONDS)
                .readTimeout(TIMEOUT_MILLIS, TimeUnit.MILLISECONDS)
                .writeTimeout(TIMEOUT_MILLIS, TimeUnit.MILLISECONDS)
                .followRedirects(true)
                .followSslRedirects(true)
                .build();
        final String finalUrl = updateUrl + "?model=" + model + "&version=" + version;
        SimpleLog.d("Request url: %s", finalUrl);

        try {
            URL obj = new URL(finalUrl);
            HttpURLConnection con = (HttpURLConnection) obj.openConnection();

            // optional default is GET
            con.setRequestMethod("GET");

            int responseCode = con.getResponseCode();
            System.out.println("\nSending 'GET' request to URL : " + finalUrl);
            System.out.println("Response code : " + responseCode);

            BufferedReader in = new BufferedReader(
                    new InputStreamReader(con.getInputStream()));
            String inputLine;
            StringBuilder response = new StringBuilder();

            while ((inputLine = in.readLine()) != null) {
                response.append(inputLine);
            }
            in.close();
            SimpleLog.d("Response: %s", response.toString());
        } catch (Throwable e) {
            SimpleLog.e(e);
        }

        Request request = new Request.Builder()
                .url(finalUrl)
                .get()
                .build();
        Response response = null;
        try {
            response = client.newCall(request).execute(); //here is an error
       } catch (Throwable e) {
            SimpleLog.e(e);
       }
```

This code works absolutely fine on OnePlus 5 and emulator, but on Set-top-box I have an error only with OkHttp Request, but not with `HttpURLConnection`. Logs (I removed urls from log, because this is a real server, url and json are correct at runtime):
```
D/GetUpdateInfoTask: Request url: http://<url>
I/System.out: Sending 'GET' request to URL : http://<url>
I/System.out: Response code : 200
D/GetUpdateInfoTask: Response: { <json> }
E/GetUpdateInfoTask: java.net.UnknownHostException: Unable to resolve host "0": No address associated with hostname
                                                                                 at java.net.InetAddress.lookupHostByName(InetAddress.java:470)
                                                                                 at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252)
                                                                                 at java.net.InetAddress.getAllByName(InetAddress.java:214)
                                                                                 at okhttp3.Dns$1.lookup(Dns.java:39)
                                                                                 at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
                                                                                 at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
                                                                                 at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
                                                                                 at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:213)
                                                                                 at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
                                                                                 at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
                                                                                 at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                 at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                 at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                 at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                                 at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
                                                                                 at okhttp3.RealCall.execute(RealCall.java:77)
                                                                                 at com.infomir.updateutility.tasks.GetUpdateInfoTask.run(GetUpdateInfoTask.java:99)
                                                                              Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
                                                                                 at libcore.io.Posix.android_getaddrinfo(Native Method)
                                                                                 at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:55)
                                                                                 at java.net.InetAddress.lookupHostByName(InetAddress.java:451)
                                                                                 at java.net.InetAddress.getAllByNameImpl(InetAddress.java:252) 
                                                                                 at java.net.InetAddress.getAllByName(InetAddress.java:214) 
                                                                                 at okhttp3.Dns$1.lookup(Dns.java:39) 
                                                                                 at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185) 
                                                                                 at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149) 
                                                                                 at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84) 
                                                                                 at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:213) 
                                                                                 at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134) 
                                                                                 at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113) 
                                                                                 at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42) 
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
                                                                                 at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
                                                                                 at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                                                                                 at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125) 
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
                                                                                 at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
                                                                                 at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) 
                                                                                 at okhttp3.RealCall.execute(RealCall.java:77) 
                                                                                 at com.infomir.updateutility.tasks.GetUpdateInfoTask.run(GetUpdateInfoTask.java:99) 

```

***Environment:***
**System:** Windows 10
**IDE:** Android Studio 3.0.0
**Gradle:** 4.1
**OkHttp version:** 3.9.0
**Test devices:** OnePlus 5, Set-top-box, Emulator

**Comment by yschimke** [comment]
Where does the 0 come from?  Any chance you are getting a redirect to 0?

**Comment by don11995** [comment]
I do not know where the "0" comes from, the only "0" is in the link. There are no redirects at all. BUT! I made a full reset of the set-top-box and the problem was gone, but now I can not reproduce this error anyway.
