### ISSUE TITLE
java.lang.NullPointerException

### ISSUE THREAD

**Issue by sws1011** [square/okhttp#3694]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean okhttp3.internal.d.a(okhttp3.i, okhttp3.internal.a.b)' on a null object reference
       at okhttp3.internal.http.StreamAllocation.deallocate(StreamAllocation.java:250)
       at okhttp3.internal.http.StreamAllocation.streamFailed(StreamAllocation.java:306)
       at okhttp3.internal.http.HttpEngine.close(HttpEngine.java:478)
       at okhttp3.RealCall.getResponse(RealCall.java:273)
       at okhttp3.RealCall$ApplicationInterceptorChain.proceed(RealCall.java:201)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:163)
       at okhttp3.RealCall.access$100(RealCall.java:30)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:127)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by JakeWharton** [comment]
What version? Also please provide a deobfuscated stack trace.

**Comment by sws1011** [comment]
[crash_okhttp3_3.4.1.txt](https://github.com/square/okhttp/files/1529333/crash_okhttp3_3.4.1.txt)

**Comment by yschimke** [comment]
It can only really be this line, but instance can't be null once the concrete class in OkHttpClient static initializer is made.

```
 if (Internal.instance.connectionBecameIdle(connectionPool, connection)) {
```

But I don't find a version in git where that is line 250

```
for i in `git log --pretty=format:"%H" $file`; do echo $i; git show $i:$file | sed '250q;d' ; done
```

As @JakeWharton asked, please provide more information like the version you are running.  Is it occurring frequently.

**Comment by sws1011** [comment]
solved

**Comment by yschimke** [comment]
![image](https://user-images.githubusercontent.com/231923/34552817-c24807d4-f11b-11e7-8e72-47391ad3fdc2.png)

https://xkcd.com/979/
