### ISSUE TITLE
Received fatal alert: close_notify this is error How to solve? help me

### ISSUE THREAD

**Issue by z589533** [square/okhttp#3697]
javax.net.ssl.SSLException: Received fatal alert: close_notify
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:208)
	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:2033)
	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1135)
	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1385)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1413)
	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1397)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:299)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)

**Comment by z589533** [comment]
![image](https://user-images.githubusercontent.com/12063612/33123808-2680a9e0-cfb6-11e7-85ba-108431982577.png)

**Comment by z589533** [comment]
jdk1.8.0_151
okttp 3.9.0

**Comment by z589533** [comment]
<dependency>
    <groupId>com.squareup.okhttp3</groupId>
    <artifactId>okhttp</artifactId>
    <version>3.9.0</version>
</dependency>

**Comment by z589533** [comment]
http url is https,i do not know https version "TLSv1", "TLSv1.1", "TLSv1.2", "SSLv3" ? i do not know  if http2

**Comment by z589533** [comment]
help me,Thank

**Comment by z589533** [comment]
![image](https://user-images.githubusercontent.com/12063612/33124387-b64d8736-cfb7-11e7-9d64-63bec2d6fa71.png)

**Comment by z589533** [comment]
com.squareup.okhttp3 okhttp 3.9.1 fail

**Comment by z589533** [comment]
![image](https://user-images.githubusercontent.com/12063612/33125295-ebb8cee6-cfba-11e7-9be1-919cf0cb3d4d.png)
skip https fail

**Comment by yschimke** [comment]
Because this is failing while handshaking, I think you'll need to use the debug information from the JVM.

http://www.madhur.co.in/blog/2016/10/30/debugging-ssl-issues-java.html

-Djavax.net.debug=all
