### ISSUE TITLE
WebSocket  java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by Harlber** [square/okhttp#3722]
[Status Code 1001](https://tools.ietf.org/html/rfc6455#section-7.4)  in okhttp was a SocketException 

Response from server   `1001, Stream end encountered`

 ```java
 java.net.SocketException: Connection reset
       at java.net.SocketInputStream.read(SocketInputStream.java:192)
       at java.net.SocketInputStream.read(SocketInputStream.java:120)
       at okio.Okio$2.read(Okio.java:139)
       at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
       at okio.RealBufferedSource.request(RealBufferedSource.java:67)
       at okio.RealBufferedSource.require(RealBufferedSource.java:60)
       at okio.RealBufferedSource.readByte(RealBufferedSource.java:73)
       at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:113)
       at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:97)
       at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:262)
       at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:201)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:141)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:776)
```

okhttp version `3.8.0`

**Comment by yschimke** [comment]
I can't reproduce this for the client.  Can you provide more information or preferably a test showing the problem.

https://github.com/square/okhttp/pull/3725

I get a similar exception logged (not actually a problem) via the MockWebServer but I'm inclined to ignore that.  Barring a reproduction, I'll need to close the issue.

**Comment by Harlber** [comment]
*problem detail*
 - Establish a connection with the server
 - After a few minutes, there are no more `ping frame `  send caused by NetWork 
 - Send normal data  `SocketException ` appeared

`SocketException` did not invoke 
```java
WebSocketListener.onFailure(WebSocket webSocket, Throwable t, Response response)
```

**Comment by yschimke** [comment]
IIUC It should not be an exception.  Have you implemented?

```
@Override public void onClosing(WebSocket webSocket, int code, String reason) {
        // do something
}
```

**Comment by Harlber** [comment]
Yep,
```java
@Override public void onClosing(WebSocket webSocket, int code, String reason) {
       Log.i(TAG, "onClosing:");
       super.onClosing(webSocket, code, reason);
}

@Override public void onClosed(WebSocket webSocket, int code, String reason) {
      Log.i(TAG, "onClosed:"); 
      super.onClosed(webSocket, code, reason);
}

```

Unfortunately , method `onClosing`  `onClosed` also did not invoked.

**Comment by Harlber** [comment]
Another way can solve my problem
