### ISSUE TITLE
java.net.SocketTimeoutException: connect timed out

### ISSUE THREAD

**Issue by LibraZhu** [square/okhttp#3724]
Same wifi environment，sometimes the sokect timed out。
The place: 
    AndroidPlatform.connectSocket()
    try {
      socket.connect(address, connectTimeout);
    } 
Exception is: 
java.net.SocketTimeoutException: connect timed out
     at java.net.PlainSocketImpl.socketConnect(Native Method) 
     at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
     at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
     at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
     at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
     at java.net.Socket.connect(Socket.java:605)
     at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:70)
     at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:238)
     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:158)
     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:113)
     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)

**Comment by JakeWharton** [comment]
This is a normal exception to receive. Networks are volatile things that
frequently don't work. You must always expect it to fail at some point.
