### ISSUE TITLE
The following problem when uploading large files, how to solve？

### ISSUE THREAD

**Issue by 939582415** [square/okhttp#3729]
12-19 14:20:24.376 28950-29644/com.hbrb.hbrbcjxt E/AndroidRuntime: FATAL EXCEPTION: RxCachedThreadScheduler-2
                                                                   Process: com.hbrb.hbrbcjxt, PID: 28950
                                                                   io.reactivex.exceptions.UndeliverableException: java.lang.OutOfMemoryError
                                                                       at io.reactivex.plugins.RxJavaPlugins.onError(RxJavaPlugins.java:349)
                                                                       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:64)
                                                                       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152)
                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                       at java.lang.Thread.run(Thread.java:841)
                                                                    Caused by: java.lang.OutOfMemoryError
                                                                       at okio.Segment.<init>(Segment.java:63)
                                                                       at okio.SegmentPool.take(SegmentPool.java:48)
                                                                       at okio.Buffer.writableSegment(Buffer.java:1169)
                                                                       at okio.Okio$2.read(Okio.java:137)
                                                                       at okio.Buffer.writeAll(Buffer.java:1005)
                                                                       at okhttp3.RequestBody$3.writeTo(RequestBody.java:120)
                                                                       at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
                                                                       at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
                                                                       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:189)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
                                                                       at okhttp3.RealCall.execute(RealCall.java:77)
                                                                       at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
                                                                       at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
                                                                       at io.reactivex.Observable.subscribe(Observable.java:10955)
                                                                       at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
                                                                       at io.reactivex.Observable.subscribe(Observable.java:10955)
                                                                       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
                                                                       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
                                                                       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
                                                                       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52) 
                                                                       at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:152) 
                                                                       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:265) 
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                       at java.lang.Thread.run(Thread.java:841)

**Comment by swankjesse** [comment]
Turn off the logging interceptor here.
