### ISSUE TITLE
AndroidPlatform line 63 okhttp3.internal.platform.AndroidPlatform.connectSocket

### ISSUE THREAD

**Issue by zahidgirnar** [square/okhttp#3760]
com.squareup.okhttp3:okhttp:3.6.0

----------------

Fatal Exception: java.lang.NullPointerException: The supplied value is null
       at io.reactivex.internal.operators.observable.ObservableOnErrorReturn$OnErrorReturnObserver.onError(SourceFile:81)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeOnObserver.onError(SourceFile:63)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.checkTerminate(SourceFile:495)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drainLoop(SourceFile:331)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.drain(SourceFile:323)
       at io.reactivex.internal.operators.observable.ObservableFlatMap$MergeObserver.onError(SourceFile:288)
       at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(SourceFile:55)
       at io.reactivex.Observable.subscribe(SourceFile:10903)
       at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(SourceFile:55)
       at io.reactivex.Observable.subscribe(SourceFile:10903)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(SourceFile:96)
       at io.reactivex.Scheduler$DisposeTask.run(SourceFile:452)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(SourceFile:61)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(SourceFile:52)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by java.net.SocketTimeoutException: failed to connect to www.cardekho.com/180.179.212.148 (port 443) after 90000ms: isConnected failed: ETIMEDOUT (Connection timed out)
       at libcore.io.IoBridge.isConnected(IoBridge.java:232)
       at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
       at libcore.io.IoBridge.connect(IoBridge.java:122)
       at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
       at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
       at java.net.Socket.connect(Socket.java:884)
       at okhttp3.internal.platform.AndroidPlatform.connectSocket(SourceFile:63)
       at okhttp3.internal.connection.RealConnection.connectSocket(SourceFile:220)
       at okhttp3.internal.connection.RealConnection.connect(SourceFile:146)
       at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:186)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:121)
       at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:100)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:120)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at com.girnarsoft.framework.network.retrofit.interceptor.UnzippingInterceptor.intercept(SourceFile:17)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at com.girnarsoft.framework.network.retrofit.RetrofitApiServiceFactory$1.intercept(SourceFile:68)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:179)
       at okhttp3.RealCall.execute(SourceFile:63)
       at retrofit2.OkHttpCall.execute(SourceFile:174)
       at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(SourceFile:41)
       at io.reactivex.Observable.subscribe(SourceFile:10903)
       at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(SourceFile:55)
       at io.reactivex.Observable.subscribe(SourceFile:10903)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(SourceFile:96)
       at io.reactivex.Scheduler$DisposeTask.run(SourceFile:452)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(SourceFile:61)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(SourceFile:52)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
Caused by android.system.ErrnoException: isConnected failed: ETIMEDOUT (Connection timed out)
       at libcore.io.IoBridge.isConnected(IoBridge.java:223)
       at libcore.io.IoBridge.connectErrno(IoBridge.java:171)
       at libcore.io.IoBridge.connect(IoBridge.java:122)
       at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:183)
       at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:452)
       at java.net.Socket.connect(Socket.java:884)
       at okhttp3.internal.platform.AndroidPlatform.connectSocket(SourceFile:63)
       at okhttp3.internal.connection.RealConnection.connectSocket(SourceFile:220)
       at okhttp3.internal.connection.RealConnection.connect(SourceFile:146)
       at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:186)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:121)
       at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:100)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:120)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at com.girnarsoft.framework.network.retrofit.interceptor.UnzippingInterceptor.intercept(SourceFile:17)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at com.girnarsoft.framework.network.retrofit.RetrofitApiServiceFactory$1.intercept(SourceFile:68)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:179)
       at okhttp3.RealCall.execute(SourceFile:63)
       at retrofit2.OkHttpCall.execute(SourceFile:174)
       at com.jakewharton.retrofit2.adapter.rxjava2.CallObservable.subscribeActual(SourceFile:41)
       at io.reactivex.Observable.subscribe(SourceFile:10903)
       at io.reactivex.internal.operators.observable.ObservableFlatMap.subscribeActual(SourceFile:55)
       at io.reactivex.Observable.subscribe(SourceFile:10903)
       at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(SourceFile:96)
       at io.reactivex.Scheduler$DisposeTask.run(SourceFile:452)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(SourceFile:61)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(SourceFile:52)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:154)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)

**Comment by JakeWharton** [comment]
Your `onErrorReturn` lambda is returning `null` which is not allowed.

**Comment by zahidgirnar** [comment]
Here is our code. What should we return if null is cause.

.onErrorReturn(new Function<Throwable, T>()
{
    @Override
    public T apply(
            @NonNull
                    Throwable throwable) throws Exception
    {
        throwable.printStackTrace();
        return null;
    }
});



[image: border] [image: border] [image: border] [image: border] [image:
border]


[image: CarDekho] <http://www.cardekho.com/>

  [image: facebook]
<https://www.facebook.com/pages/CarDekho/179167414600>   [image:
twitter] <https://twitter.com/CarDekho>   [image: google plus]
<https://plus.google.com/+cardekho>   [image: youtube]
<https://www.youtube.com/user/CarDekhoChannel>


[image: Location]
*Zahid Naqvi | Senior Architect (Mobile Apps)Skype: arcsoft_zahid |
+91-823-333-2828*
Girnar Software Pvt. Ltd., JTM, Model Town, Near Jagatpura Flyover,
Jaipur-302017, Rajasthan, India

    Office Ph: 0141- 6666 625


CarDekho.com <http://www.cardekho.com/>   GirnarSoft.com
<http://www.girnarsoft.com/>   Gaadi.com <http://www.gaadi.com/>
Zigwheels.com <http://www.zigwheels.com/>   BikeDekho.com
<https://www.bikedekho.com/>

TrucksDekho.com <http://trucks.cardekho.com/>   TyreDekho.com
<http://tyres.cardekho.com/>   CarBay.com <http://www.carbay.com/>
PriceDekho.com <http://www.pricedekho.com/>   CollegeDekho.com
<http://www.collegedekho.com/>
[image: Wave Image]   [image: Wave Image]
