### ISSUE TITLE
java.lang.AssertionError: No System TLS in Android 7.0

### ISSUE THREAD

**Issue by weidongjian** [square/okhttp#3768]
java.lang.AssertionError: No System TLS
	at okhttp3.internal.Util.assertionError(Util.java:482)
	at okhttp3.OkHttpClient.systemDefaultSslSocketFactory(OkHttpClient.java:302)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:253)
	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:919)
	at com.networkbench.agent.impl.instrumentation.NBSOkHttp3Instrumentation.init(SourceFile:24)
	at com.meitu.pushkit.e.a(PushHelper.java:334)
	at com.meitu.pushkit.b.handleMessage(MeituPushControl.java:139)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:156)
	at android.os.HandlerThread.run(HandlerThread.java:61)
Caused by: java.security.NoSuchAlgorithmException: Service not registered with Provider AndroidOpenSSL: AndroidOpenSSL: SSLContext.TLS -> com.android.org.conscrypt.OpenSSLContextImpl$TLSv12

	at java.security.Provider$Service.newInstance(Provider.java:1243)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:176)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:189)
	at okhttp3.OkHttpClient.systemDefaultSslSocketFactory(OkHttpClient.java:298)
	... 8 more
java.security.NoSuchAlgorithmException: Service not registered with Provider AndroidOpenSSL: AndroidOpenSSL: SSLContext.TLS -> com.android.org.conscrypt.OpenSSLContextImpl$TLSv12

	at java.security.Provider$Service.newInstance(Provider.java:1243)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:236)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:176)
	at javax.net.ssl.SSLContext.getInstance(SSLContext.java:189)
	at okhttp3.OkHttpClient.systemDefaultSslSocketFactory(OkHttpClient.java:298)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.java:253)
	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:919)
	at com.networkbench.agent.impl.instrumentation.NBSOkHttp3Instrumentation.init(SourceFile:24)
	at com.meitu.pushkit.e.a(PushHelper.java:334)
	at com.meitu.pushkit.b.handleMessage(MeituPushControl.java:139)
	at android.os.Handler.dispatchMessage(Handler.java:101)
	at android.os.Looper.loop(Looper.java:156)
	at android.os.HandlerThread.run(HandlerThread.java:61)

![tls_error](https://user-images.githubusercontent.com/6983015/34657165-9c1bdca2-f45e-11e7-944c-1e0ff112fac7.PNG)

I receive this error occasionally in my feedback, android version is 7.0, I have no idea why this error happen, below is the code throw the error in OkHttp:

    private SSLSocketFactory systemDefaultSslSocketFactory(X509TrustManager trustManager) {
    try {
      SSLContext sslContext = SSLContext.getInstance("TLS");
      sslContext.init(null, new TrustManager[] { trustManager }, null);
      return sslContext.getSocketFactory();
    } catch (GeneralSecurityException e) {
      throw assertionError("No System TLS", e); // The system has no TLS. Just give up.
    }
    }

  **My Okhttp version is 3.9.0, the old version have no this kind error**

**Comment by gdky005** [comment]
I in 3.9.1 version, the same question. I want to get this answer.

**Comment by yschimke** [comment]
Does NBSOkHttp3Instrumentation imply instrumentation tests? 

Anyway, this sort of questions isn't specific to OkHttp, it's generally something best asked on stackoverflow if you want more attention.  I suggest asking there, there isn't much we can do unless you make a reproducible test case.

**Comment by gdky005** [comment]
@yschimke 

NBSOkHttp3Instrumentation is inserted code, on some Android phones, HTTPS requests will crash directly, because of the mobile phone, there is no relevant certificate of TLS.

**Comment by gdky005** [comment]
We use the http://www.tingyun.com/  server，resolve the bugs that are used online.

**Comment by yschimke** [comment]
It was previously thrown without any root cause, so it now show

Caused by: java.security.NoSuchAlgorithmException...

But it was likely happening as a opaque AssertionError before 3.9.0

**Comment by gdky005** [comment]
I know, I will try catch。 Thanks!
