### ISSUE TITLE
High CPU usage when uploading file with OkHTTP

### ISSUE THREAD

**Issue by TalKashi** [square/okhttp#3786]
Hi,
I am using okhttp to upload a file to a server (actually presigned URL of AWS S3).
My server (the one which uses okhttp and does the upload) is also hosted on AWS and is deployed within a docker.
I noticed that it takes about 8 seconds to upload a 30MB file, where if I just use a cURL command that does the same thing (also inside the docker) it takes 1.5 seconds.
After some digging I noticed that when okhttp is working the CPU is reaching 100%, where with cURL it is not really affected. I also tested using a much stronger ec2 instance (40vCPU), and still took 8 seconds and 100% CPU of the docker.
When I run my JAR outside of the docker it actually worked in appropriate time (2~ seconds), but I still noticed a significant CPU spike during the upload.
Eventually I changed to a different http library ([apache HttpClient](https://hc.apache.org/httpcomponents-client-4.5.x/httpclient/apidocs/index.html)) and it is working just like the cURL command (1.5 seonds and not CPU spikes)

### Code snippet of okhttp usage of uploading:
```java
RequestBody body = RequestBody.create(MediaType.parse("multipart/form-data"), new File(filePath));
Request req = new Request.Builder()
                        .url(signedUrl)
                        .put(body)                        
                        .build();
client.newCall(req).execute();
```

### Code snippet of different http lib which is working well:
```java
File file = new File(filePath);
MultipartEntityBuilder builder = MultipartEntityBuilder.create();
builder.addBinaryBody("file", file, ContentType.MULTIPART_FORM_DATA, file.getName())
            .setMode(HttpMultipartMode.BROWSER_COMPATIBLE);
HttpPut put = new HttpPut(signedUrl);
put.setEntity(builder.build());
HttpClient client = HttpClientBuilder.create().build();
client.execute(put);
```

If you need more details I will gladly add whatever is needed

**Comment by swankjesse** [comment]
Wow, yeah that isn't good. Can you sample a stacktrace of the service while it's being slow? I wonder if OkHttp is negotiating HTTP/2 which could explain dramatically different performance vs. other clients.

Tracing information is available either with a profiler, or just with calling jstack while OkHttp is spinning.

**Comment by TalKashi** [comment]
I am not familiar with jstack but will try to take a look at it next week. 
Forgot to mention that some of my digging I listened to the okhttp events and most of those 8 seconds are being while it is writing the http body. Also I can say that it is trying HTTP/1.1 and one of my tests was with this portocol only.

**Comment by swankjesse** [comment]
Interesting! Yeah if you could take a stack dump it'll show whether there's a case in OkHttp that's slow or if it's something in the socket code.

**Comment by TalKashi** [comment]
[dump.txt](https://github.com/square/okhttp/files/1677008/dump.txt)
Dump is attached. The dump was taken between requestBodyStart event (which was fired after 0.078 seconds) and requestBodyEnd event (which was fired after 8.056 seconds)

**Comment by swankjesse** [comment]
Looks like the CPU is busy doing AES for HTTPS. Might be something that performs better when Conscrypt support lands (soon!).

```
"http-nio-8090-exec-3" #31 daemon prio=5 os_prio=0 tid=0x00007f0c9c02b000 nid=0x23a runnable [0x00007f0cac112000]
   java.lang.Thread.State: RUNNABLE
        at com.sun.crypto.provider.GHASH.update(GHASH.java:167)
        at com.sun.crypto.provider.GaloisCounterMode.doLastBlock(GaloisCounterMode.java:362)
        at com.sun.crypto.provider.GaloisCounterMode.encryptFinal(GaloisCounterMode.java:419)
        at com.sun.crypto.provider.CipherCore.finalNoPadding(CipherCore.java:1025)
        at com.sun.crypto.provider.CipherCore.doFinal(CipherCore.java:984)
        at com.sun.crypto.provider.AESCipher.engineDoFinal(AESCipher.java:479)
        at javax.crypto.Cipher.doFinal(Cipher.java:2333)
        at sun.security.ssl.CipherBox.encrypt(CipherBox.java:315)
        at sun.security.ssl.OutputRecord.encrypt(OutputRecord.java:264)
        at sun.security.ssl.SSLSocketImpl.writeRecordInternal(SSLSocketImpl.java:840)
        at sun.security.ssl.SSLSocketImpl.writeRecord(SSLSocketImpl.java:828)
        at sun.security.ssl.AppOutputStream.write(AppOutputStream.java:123)
        - locked <0x0000000086a3c2b8> (a sun.security.ssl.AppOutputStream)
        at okio.Okio$1.write(Okio.java:79)
        at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
        at okio.RealBufferedSink.write(RealBufferedSink.java:41)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSink.write(Http1Codec.java:292)
        at okio.ForwardingSink.write(ForwardingSink.java:35)
        at okhttp3.internal.http.CallServerInterceptor$CountingSink.write(CallServerInterceptor.java:134)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:171)
        at okio.RealBufferedSink.write(RealBufferedSink.java:91)
        at okhttp3.RequestBody$2.writeTo(RequestBody.java:98)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:72)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:212)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
```

**Comment by swankjesse** [comment]
No action for us to take on this, unfortunately.

**Comment by mufumbo** [comment]
@swankjesse any recommendation about how to get better performance? I use okhttp3 to upload many 20mb videos on Android and it fries the user phones..

**Comment by swankjesse** [comment]
@mufumbo please don't add new questions on old issues. If you'd like to report an Android performance bug, create a new issue. This issue is about JVM performance.
