### ISSUE TITLE
Fatal Exception: ArrayIndexOutOfBoundsException in Hpack.java

### ISSUE THREAD

**Issue by AndrazP** [square/okhttp#3793]
- Okhttp version: 3.9.1
- Retrofit version: 2.3.0

Received crash report from SM-G950F on Android 7.0.
Stacktrace
```
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=8; index=8
       at okhttp3.internal.http2.Hpack$Reader.getName(Hpack.java:265)
       at okhttp3.internal.http2.Hpack$Reader.readLiteralHeaderWithIncrementalIndexingIndexedName(Hpack.java:250)
       at okhttp3.internal.http2.Hpack$Reader.readHeaders(Hpack.java:195)
       at okhttp3.internal.http2.Http2Reader.readHeaderBlock(Http2Reader.java:196)
       at okhttp3.internal.http2.Http2Reader.readHeaders(Http2Reader.java:182)
       at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.java:129)
       at okhttp3.internal.http2.Http2Connection$ReaderRunnable.execute(Http2Connection.java:566)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.lang.Thread.run(Thread.java:762)
```

**Comment by yschimke** [comment]
Not sure if this is a purely client bug, but even assuming an invalid server response, this should fail a single connection (IOException), closing all streams and not kill the client instance or the app.

**Comment by swankjesse** [comment]
This is fixed.
