### ISSUE TITLE
the latest version3.9.1 

### ISSUE THREAD

**Issue by LiuzxGeek** [square/okhttp#3805]
when open the app，crash occured .
Andorid System：4.2       Cpu：X86     

FATAL EXCEPTION: OkHttp Dispatcher
                                                                   java.lang.NullPointerException
                                                                       at okhttp3.internal.io.FileSystem$1.sink(FileSystem.java:52)
                                                                       at okhttp3.internal.cache.DiskLruCache.rebuildJournal(DiskLruCache.java:396)
                                                                       at okhttp3.internal.cache.DiskLruCache.initialize(DiskLruCache.java:246)
                                                                       at okhttp3.internal.cache.DiskLruCache.get(DiskLruCache.java:436)
                                                                       at okhttp3.Cache.get(Cache.java:195)
                                                                       at okhttp3.Cache$1.get(Cache.java:145)
                                                                       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:54)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
                                                                       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
                                                                       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
                                                                       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
                                                                       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
                                                                       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
                                                                       at java.lang.Thread.run(Thread.java:856)

**Comment by swankjesse** [comment]
This looks impossible. Could you provide an executable test case?

**Comment by yschimke** [comment]
reopen if you can reproduce this, with more information.

**Comment by droidekas** [comment]
I see this happening, And I see a possible reason being using `context.getExternalCacheDir()` . @LiuzxGeek  Can you confirm if you are using the same API to build your cache file?
