### ISSUE TITLE
Benchmarks execution produces OutOfMemoryError

### ISSUE THREAD

**Issue by ming13** [square/okhttp#3812]
#### Software

```
$ mvn --version
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T10:58:13+03:00)
Maven home: /usr/local/Cellar/maven/3.5.2/libexec
Java version: 1.8.0_102, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_102.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.11.6", arch: "x86_64", family: "mac"

$ git rev-parse HEAD
a77c781d4af0d5a2bf2ca72d409251ded604a1e1
```

#### Hardware

```
Model Name:	MacBook Pro
Model Identifier:	MacBookPro12,1
Processor Name:	Intel Core i5
Processor Speed:	2.7 GHz
Number of Processors:	1
Total Number of Cores:	2
L2 Cache (per Core):	256 KB
L3 Cache:	3 MB
Memory:	8 GB
```

#### Execution

```
$ cd benchmarks/
$ mvn compile exec:exec
```
<details/>
  <summary>Result</summary>

```
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] Building Benchmarks 3.10.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:exec (default-cli) @ benchmarks ---
Experiment selection: 
  Instruments:   [arbitrary]
  User parameters:   {bodyByteCount=[128, 1048576], chunked=[true, false], client=[OkHttp, OkHttpAsync, Apache, UrlConnection, Netty], concurrencyLevel=[1, 10], gzip=[true, false], headerCount=[0, 20], targetBacklog=[10], tls=[true, false]}
  Virtual machines:  [default]
  Selection type:    Full cartesian product

This selection yields 320 experiments.
com.google.caliper.runner.UserCodeException: An exception was thrown from the benchmark code
	at com.google.caliper.runner.ArbitraryMeasurementInstrument.dryRun(ArbitraryMeasurementInstrument.java:89)
	at com.google.caliper.runner.ExperimentingCaliperRun.dryRun(ExperimentingCaliperRun.java:420)
	at com.google.caliper.runner.ExperimentingCaliperRun.run(ExperimentingCaliperRun.java:183)
	at com.google.caliper.runner.CaliperMain.exitlessMain(CaliperMain.java:131)
	at com.google.caliper.runner.CaliperMain.main(CaliperMain.java:78)
	at com.google.caliper.runner.CaliperMain.main(CaliperMain.java:66)
	at okhttp3.benchmarks.Benchmark.main(Benchmark.java:92)
Caused by: java.lang.OutOfMemoryError: GC overhead limit exceeded
	at okhttp3.RealCall.<init>(RealCall.java:54)
	at okhttp3.RealCall.newRealCall(RealCall.java:59)
	at okhttp3.OkHttpClient.newCall(OkHttpClient.java:430)
	at okhttp3.benchmarks.OkHttp.request(OkHttp.java:57)
	at okhttp3.benchmarks.SynchronousHttpClient.enqueue(SynchronousHttpClient.java:37)
	at okhttp3.benchmarks.Benchmark.run(Benchmark.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.google.caliper.runner.ArbitraryMeasurementInstrument.dryRun(ArbitraryMeasurementInstrument.java:83)
	... 6 more
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:134)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:208)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:154)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:146)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:51)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:309)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:194)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:107)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:955)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:290)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:194)
    at sun.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:498)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:289)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:229)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:415)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:356)
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:10 min
[INFO] Finished at: 2018-02-01T16:40:51+03:00
[INFO] Final Memory: 9M/155M
```
</details>

#### Questions and Suggestions

* Is it possible to publish the latests results? I’ve only found [some from 2014](https://plus.google.com/+JesseWilson/posts/EJCDEiPrN42).
* Is there a real benefit of using `enqueue` vs. `execute` + IO scheduler?

**Comment by swankjesse** [comment]
We could attempt more current results. Gotta upgrade the alternatives!

If you have your own IO threads, execute is just fine. Someday we might implementation async IO in Okio (not using java.nio!) in which case enqueue() might use fewer threads.

**Comment by ming13** [comment]
Thanks, it would be great to see some nice graphs!

The reason I’m asking about `enqueue` vs. `execute` is because I’ve just compared `createAsync` vs. `createWithScheduler` using Retrofit and `enqueue` is kind of faster — `40.7798` vs. `42.123`. I’ve done a number of passes using isolated integration tests which use `MockWebServer`, of course.

**Comment by swankjesse** [comment]
Neat. The enqueue and execute APIs do mostly the same stuff. Enqueue holds a thread pool for you and limits which requests are executed concurrently. Changing the Dispatcher settings may be the difference here.

**Comment by swankjesse** [comment]
Obsoleted by deleting the benchmarks module.
https://github.com/square/okhttp/pull/4463
