### ISSUE TITLE
java.lang.NullPointerException in CacheControl

### ISSUE THREAD

**Issue by zstartw** [square/okhttp#3815]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
       at okhttp3.CacheControl.parse(CacheControl.java:173)
       at okhttp3.Request.cacheControl(Request.java:83)
       at okhttp3.internal.cache.CacheStrategy$Factory.get(CacheStrategy.java:175)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:59)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```
I had the exception in fabric. I check my project code, it may be found using a single instance of each request, I'm not too sure.

This is the official demo.
```
private final OkHttpClient client = new OkHttpClient();
 Request request = new Request.Builder() 
        .url("https://api.github.com/markdown/raw")
        .post(RequestBody.create(MEDIA_TYPE_MARKDOWN, postBody))
        .build();
    try (Response response = client.newCall(request).execute()) {
      if (!response.isSuccessful()) throw new IOException("Unexpected code " + response);

      Headers responseHeaders = response.headers();
      for (int i = 0; i < responseHeaders.size(); i++) {
        System.out.println(responseHeaders.name(i) + ": " + responseHeaders.value(i));
      }
      System.out.println(response.body().string());
    }
```
and i replace` new Request.Builder()`  to `getRequestBuilder()`.

```
 private static Request.Builder requestBuilder;
  public synchronized Request.Builder getRequestBuilder() {
        if (requestBuilder == null) {
            requestBuilder = new Request.Builder();
        }
        return requestBuilder;
    }
```
and I want to sure the Request object can use a Singleton Pattern when run request.Ths.

**Comment by zstartw** [comment]
```
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
       at okhttp3.CacheControl.parse(CacheControl.java:173)
       at okhttp3.Request.cacheControl(Request.java:83)
       at okhttp3.internal.cache.CacheStrategy$Factory.get(CacheStrategy.java:175)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:59)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)
```
I had the exception in fabric. I check my project code, it may be found using a single instance of each request, I'm not too sure.

This is the official demo.
```
private final OkHttpClient client = new OkHttpClient();
 Request request = new Request.Builder() 
        .url("https://api.github.com/markdown/raw")
        .post(RequestBody.create(MEDIA_TYPE_MARKDOWN, postBody))
        .build();
    try (Response response = client.newCall(request).execute()) {
      if (!response.isSuccessful()) throw new IOException("Unexpected code " + response);

      Headers responseHeaders = response.headers();
      for (int i = 0; i < responseHeaders.size(); i++) {
        System.out.println(responseHeaders.name(i) + ": " + responseHeaders.value(i));
      }
      System.out.println(response.body().string());
    }
```
and i replace` new Request.Builder()`  to `getRequestBuilder()`.

```
 private static Request.Builder requestBuilder;
  public synchronized Request.Builder getRequestBuilder() {
        if (requestBuilder == null) {
            requestBuilder = new Request.Builder();
        }
        return requestBuilder;
    }
```
and I want to sure the Request object can use a Singleton Pattern when run request.Ths.

**Comment by swankjesse** [comment]
Strange. Looks like something the headers got a null key, which it should never have.

Can you provide an executable test case?

**Comment by 654277633** [comment]
i have used "Interceptor"

public Response intercept(Chain chain) throws IOException {
Request request = chain.request();
Response response = chain.proceed(request );//NullPointerException CacheControl.java:173
//...
}

can you please add some jugdement in CacheControl.java line 173? 
such as if(name==null||value==null) continue?

**Comment by yschimke** [comment]
This shouldn't be happening i.e. a logic bug, so I think the main reason for wanting a reproduction is to fix the root cause. 

If you can make a unit test or reproducible test then we will know the bug is really fixed and we are not silently dropping data or handling caching incorrectly etc.

**Comment by zstartw** [comment]
My project is very huge. and Providing a demo is inconvenient. So I provide some code that may have problems.
Because I want to get to **MPHPSESSID**, so every time my request interceptor use of the project.
The code below.

```
public class LoggingInterceptor implements Interceptor {

    public static final String TAG = "LoggingInterceptor";

    @Override
    public Response intercept(Chain chain) throws IOException {
        Request request = chain.request();
        Response response = chain.proceed(request);
        List<Cookie> cookieStrings = Cookie.parseAll(request.url(), response.headers());
        MyApplication instance = MyApplication.getInstance();
        if (instance != null) {
            String ssid = instance.getSession_id();
            for (Cookie cookie : cookieStrings) {
                String name = cookie.name();
                if ("MPHPSESSID".equals(name)) {
                    String session_id = cookie.value();
                    if (!TextUtils.isEmpty(session_id) && !session_id.equals(ssid)) {
                        MyApplication.getInstance().setSession_id(session_id);
                    }
                }
            }
        }
        return response;
    }

}
```

**Comment by swankjesse** [comment]
Nothing actionable here unfortunately. If you can extract a standalone test case, we can fix.

**Comment by ferdinandtaishev** [comment]
got this issue in 4.9.1 okhttp version

**Comment by yschimke** [comment]
I suspect from the original report,  "new Request.Builder() to getRequestBuilder()" the Request.Builder is being reused, probably in multiple threads? Are you creating a fresh Request.Builder on each request?
