### ISSUE TITLE
NullPointerException CacheControl.java:173

### ISSUE THREAD

**Issue by 654277633** [square/okhttp#3816]
Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean java.lang.String.equalsIgnoreCase(java.lang.String)' on a null object reference
       at okhttp3.CacheControl.parse(CacheControl.java:173)
       at okhttp3.Request.cacheControl(Request.java:83)
       at okhttp3.internal.cache.CacheStrategy$Factory.get(CacheStrategy.java:175)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:59)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:760)

**Comment by 654277633** [comment]
force closed 20K times because this error!!!

**Comment by yschimke** [comment]
Same as https://github.com/square/okhttp/issues/3815
