### ISSUE TITLE
SSL Error

### ISSUE THREAD

**Issue by sthaiya** [square/okhttp#3913]
I am receiving an SSL handshake error on android 4.4.4

javax.net.ssl.SSLHandshakeException: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x6c67b6c0: Failure in SSL library, usually a protocol error
                                                                                        error:14077410:SSL routines:SSL23_GET_SERVER_HELLO:sslv3 alert handshake failure (external/openssl/ssl/s23_clnt.c:744 0x686c2f10:0x00000000)
                                                                                            at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:448)
                                                                                            at com.android.okhttp.Connection.upgradeToTls(Connection.java:146)
                                                                                            at com.android.okhttp.Connection.connect(Connection.java:107)
                                                                                            at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:294)
                                                                                            at com.android.okhttp.internal.http.HttpEngine.sendSocketRequest(HttpEngine.java:255)
                                                                                            at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:206)
                                                                                            at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:345)
                                                                                            at com.android.okhttp.internal.http.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:89)
                                                                                            at com.android.okhttp.internal.http.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:197)
                                                                                            at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:254)
                                                                                            at com.oppwa.mobile.connect.utils.b.a(Unknown Source)
                                                                                            at com.oppwa.mobile.connect.utils.b.a(Unknown Source)
                                                                                            at com.oppwa.mobile.connect.utils.b.doInBackground(Unknown Source)
                                                                                            at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                                            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                            at java.lang.Thread.run(Thread.java:841)

**Comment by swankjesse** [comment]
This is the version of OkHttp that’s embedded in Android. If you want to try using the OkHttp library instead you’ll get something that’s more recently updated and unlikely to have this problem.
