### ISSUE TITLE
okio writeByte ArrayIndexOutOfBoundsException length=8192; index=8192

### ISSUE THREAD

**Issue by huangliqiang** [square/okhttp#3938]
java.lang.ArrayIndexOutOfBoundsException: length=8192; index=8192
	at com.android.okhttp.okio.Buffer.writeByte(Buffer.java:973)
	at com.android.okhttp.internal.Platform.concatLengthPrefixed(Platform.java:130)
	at com.android.okhttp.internal.Platform.configureTlsExtensions(Platform.java:84)
	at com.android.okhttp.Connection.connectTls(Connection.java:230)
	at com.android.okhttp.Connection.connectSocket(Connection.java:199)
	at com.android.okhttp.Connection.connect(Connection.java:172)
	at com.android.okhttp.Connection.connectAndSetOwner(Connection.java:367)
	at com.android.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:130)
	at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:329)
	at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:246)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:457)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:126)
	at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:257)
	at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:218)
	at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java)
	at org.piwik.sdk.dispatcher.Dispatcher.dispatch(Dispatcher.java)
	at org.piwik.sdk.dispatcher.Dispatcher$1.run(Dispatcher.java)
	at java.lang.Thread.run(Thread.java:776)

**Comment by kozer** [comment]
Any updates on this?

**Comment by NightlyNexus** [comment]
This is code in the Android SDK (com.android.okhttp...), not this library.
Try out OkHttp 3.10.0.

**Comment by dryganets** [comment]
This happens in 3.10.0 as well ...

**Comment by dryganets** [comment]
@swankjesse, what bothers me about this bug is that in our case HockeyApp calls the okhttp.

I go through the codebase of the HockeyApp version we are using and it directly creates HttpUrlConnection.

Is there some magic hook in the OkHttp which does that? I'm not aware of the way to do, so my curiosity driving me nuts :)

Maybe there are vendors know for replacing the UrlConnection with OkHttpUrlConnection?

**Comment by swankjesse** [comment]
@dryganets you got it. The library’s package is `okhttp3` but the OkHttp that is behind the scenes in HttpURLConnection is in `com.android.okhttp`.

**Comment by bubblexin** [comment]
So.What's the solution of this problem.Anyone else knows?

**Comment by odbol** [comment]
I had a similar problem. Seemed the cache was corrupted or something? I was able to recover by calling Cache.delete() and then recreating the Cache object and retrying.

**Comment by odbol** [comment]
Here's my stack trace if it helps. I don't even understand how index could be negative at that point. Perhaps there's some check that is wrong, or the long overflowing into an int or something?

```
Error retreiving location (Ask Studio Bot)
                                                                                                    java.io.IOException: canceled due to java.lang.ArrayIndexOutOfBoundsException: length=8192; index=-6
                                                                                                    	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:185)
                                                                                                    	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    	Suppressed: java.lang.ArrayIndexOutOfBoundsException: length=8192; index=-6
                                                                                                    		at okio.Buffer.indexOf(Buffer.java:1466)
                                                                                                    		at okio.RealBufferedSource.indexOf(RealBufferedSource.java:352)
                                                                                                    		at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
                                                                                                    		at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:224)
                                                                                                    		at okhttp3.internal.cache.DiskLruCache.readJournal(DiskLruCache.java:294)
                                                                                                    		at okhttp3.internal.cache.DiskLruCache.initialize(DiskLruCache.java:228)
                                                                                                    		at okhttp3.internal.cache.DiskLruCache.get(DiskLruCache.java:430)
                                                                                                    		at okhttp3.Cache.get(Cache.java:198)
                                                                                                    		at okhttp3.Cache$1.get(Cache.java:145)
                                                                                                    		at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:55)
                                                                                                    		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
                                                                                                    		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
                                                                                                    		at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                                                                                                    		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
                                                                                                    		at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
                                                                                                    		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
                                                                                                    		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
                                                                                                    		at com.odbol.wear.airquality.purpleair.CachingClient.createClient$lambda$1(CachingClient.kt:61)
                                                                                                    		at com.odbol.wear.airquality.purpleair.CachingClient.$r8$lambda$dieXNzrD9l4hvF6JQkAhyOPAbjE(Unknown Source:0)
                                                                                                    		at com.odbol.wear.airquality.purpleair.CachingClient$$ExternalSyntheticLambda1.intercept(Unknown Source:0)
```

**Comment by dryganets** [comment]
You might want to review threading. Likely some race. In this particular
case the Okhttp was distributed with the phone - the hockeapp was using
HttpUrlConnectio if I remember correctly

**Comment by odbol** [comment]
Yep the problem was using two different Cache objects pointed to the same file/directory. Needed to make it a singleton and access from only one thread: https://github.com/square/okhttp/issues/8080

**Comment by yschimke** [comment]
It's not really about multiple threads. But two cache instances operating on the same cache directory.
