### ISSUE TITLE
connectionPool().evictAll() works in HTTP but fails in HTTPS

### ISSUE THREAD

**Issue by Theofilos-Chamalis** [square/okhttp#3947]
When switching over from **HTTP** to **HTTPS** calls in my OkHttpClient in my Android Application this error is produced at runtime when using **connectionPool().evictAll();** 

```
03-29 12:53:00.537 21542-21542/com.myapp E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.myapp, PID: 21542
    java.lang.RuntimeException: Unable to destroy activity {com.myapp/com.myapp.UserDetailsActivity}: android.os.NetworkOnMainThreadException
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3791)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3809)
        at android.app.ActivityThread.access$1400(ActivityThread.java:155)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1371)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.app.ActivityThread.main(ActivityThread.java:5343)
        at java.lang.reflect.Method.invoke(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:372)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
     Caused by: android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1161)
        at com.android.org.conscrypt.OpenSSLSocketImpl.shutdownAndFreeSslNative(OpenSSLSocketImpl.java:1115)
        at com.android.org.conscrypt.OpenSSLSocketImpl.close(OpenSSLSocketImpl.java:1110)
        at okhttp3.internal.Util.closeQuietly(Util.java:125)
        at okhttp3.ConnectionPool.evictAll(ConnectionPool.java:188)
        at com.myapp.UserDetailsActivity.killNetworkConnections(UserDetailsActivity.java:313)
        at com.myapp.UserDetailsActivity.onDestroy(UserDetailsActivity.java:329)
        at android.app.Activity.performDestroy(Activity.java:6189)
        at android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1164)
        at android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3778)
        at android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3809) 
        at android.app.ActivityThread.access$1400(ActivityThread.java:155) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1371) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:135) 
        at android.app.ActivityThread.main(ActivityThread.java:5343) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:372) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

Thank you

**Comment by yschimke** [comment]
You should call this from a non main thread.  Doing this operation causes socket activity, so it's not clear what fix you expect here.

Perhaps ask for advice in stackoverflow if you want to work out the best way to achieve this based on the libraries you use in your app.
