### ISSUE TITLE
okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL

### ISSUE THREAD

**Issue by FreshopJosiah** [square/okhttp#3948]
We getting the following issue in 3.8.

Back end is AWS ELB and Ruby's PUMA web server.

Does 3.10 retry the request in this scenario?  If so, how many times does it retry the request?

```
okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
        at okhttp3.internal.http2.Http2Stream$FramingSource.checkNotClosed(Http2Stream.java:436)
        at okhttp3.internal.http2.Http2Stream$FramingSource.read(Http2Stream.java:338)
        at okio.ForwardingSource.read(ForwardingSource.java:35)
        at okio.RealBufferedSource.read(RealBufferedSource.java:46)
        at okio.RealBufferedSource.exhausted(RealBufferedSource.java:56)
        at okio.InflaterSource.refill(InflaterSource.java:101)
        at okio.InflaterSource.read(InflaterSource.java:62)
        at okio.GzipSource.read(GzipSource.java:80)
        at okio.RealBufferedSource.read(RealBufferedSource.java:46)
        at okio.ForwardingSource.read(ForwardingSource.java:35)
        at retrofit2.OkHttpCall$ExceptionCatchingRequestBody$1.read(OkHttpCall.java:291)
        at okio.RealBufferedSource$1.read(RealBufferedSource.java:430)
        at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:287)
        at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:350)
        at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:179)
        at java.io.InputStreamReader.read(InputStreamReader.java:184)
        at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.java:252)
        at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1287)
        at com.google.gson.stream.JsonReader.nextQuotedValue(JsonReader.java:1016)
        at com.google.gson.stream.JsonReader.nextString(JsonReader.java:815)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:718)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:731)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:739)
        at com.google.gson.internal.bind.TypeAdapters$29.read(TypeAdapters.java:714)
        at com.google.gson.internal.Streams.parse(Streams.java:48)
        at com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:65)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:37)
        at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:25)
        at com.freshop.android.consumer.api.factory.NullOnEmptyConverterFactory$1.convert(NullOnEmptyConverterFactory.java:23)
        at com.freshop.android.consumer.api.factory.NullOnEmptyConverterFactory$1.convert(NullOnEmptyConverterFactory.java:19)
        at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:119)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:218)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:40)
        at retrofit2.adapter.rxjava.CallExecuteOnSubscribe.call(CallExecuteOnSubscribe.java:24)
        at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:36)
        at retrofit2.adapter.rxjava.BodyOnSubscribe.call(BodyOnSubscribe.java:28)
        at rx.Observable.unsafeSubscribe(Observable.java:10256)
        at rx.internal.operators.OperatorZip$Zip.start(OperatorZip.java:202)
        at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:143)
        at rx.internal.operators.OperatorZip$ZipSubscriber.onNext(OperatorZip.java:109)
        at rx.internal.util.ScalarSynchronousObservable$WeakSingleProducer.request(ScalarSynchronousObservable.java:276)
        at rx.Subscriber.setProducer(Subscriber.java:209)
        at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:138)
        at rx.internal.util.ScalarSynchronousObservable$JustOnSubscribe.call(ScalarSynchronousObservable.java:129)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:48)
        at rx.internal.operators.OnSubscribeLift.call(OnSubscribeLift.java:30)
        at rx.Observable.unsafeSubscribe(Observable.java:10256)
        at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
        at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:428)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:272)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)
```

**Comment by JRLin** [comment]
Hi,FreshopJosiah:
    We have the same issue when we enable HTTP2 in our application occasionally: we can get the header correctly, when we read the body,  it will expose the exception :"stream was reset: CANCEL" or "stream was reset: PROTOCOL ERROR" sometimes. Have you confirmed this issue is due to the server side(AWS ELB) or the client side?

**Comment by FreshopJosiah** [comment]
@JRLin,

We ended up reverting back to HTTP1 and the issue seemed to go away.  

There could be an issue with OkHttp and HTTP2 given the following:

* We didn't end up making any changes on the server side
* Our iOS and web clients do not seem to experience this issue and both use HTTP2

Bottom line, I'm still not sure what the actual cause is.

**Comment by swankjesse** [comment]
@FreshopJosiah can you confirm you’re getting `PROTOCOL_ERROR` responses? Is HTTP/2 terminated by the ELBs or by PUMA?

**Comment by alittlecup** [comment]
i have the same problem , tell my solution 

my problem cause by repeat search the same api  then i control the frequency of the calling api 

it will be ok 

i'm not sure it be suitable for you

**Comment by matemink** [comment]
> @JRLin,
> 
> We ended up reverting back to HTTP1 and the issue seemed to go away.
> 
> There could be an issue with OkHttp and HTTP2 given the following:
> 
> * We didn't end up making any changes on the server side
> * Our iOS and web clients do not seem to experience this issue and both use HTTP2
> 
> Bottom line, I'm still not sure what the actual cause is.

Did you find any solution for Android now?

**Comment by ylbkoo** [comment]
okHttpClient = new OkHttpClient.Builder()
                    .pingInterval(100, TimeUnit.MILLISECONDS)
                    .build();
when i use the client to visit http2 server, must throw "okhttp3.internal.http2.StreamResetException: stream was reset: PROTOCOL_ERROR"

bug? or there's  something wrong with the server？

**Comment by swankjesse** [comment]
Bug somewhere. Which server are you using?

**Comment by ylbkoo** [comment]
@swankjesse I have tried both nginx(1.10.3) and caddy(1.0.0), the same error as described before.

**Comment by whysqwhw** [comment]
Batch download, this problem occurs probabilistically.
