### ISSUE TITLE
Certificate Pinning example fails with incorrect exception

### ISSUE THREAD

**Issue by Fuzion24** [square/okhttp#3951]
I'm using Android 8.1.0, with OkHttp version 'com.squareup.okhttp3:okhttp:3.9.1'.

The following code 
```java
            try {
                 // Pin is `echo "aaaaaaaa" | base64`
                CertificatePinner certPinner = new CertificatePinner.Builder()
                        .add("google.com",
                                "sha256/YWFhYWFhYQo=")    
                        .build();

                client = new OkHttpClient.Builder()
                        .certificatePinner(certPinner)
                        .build();

                Request request = new Request.Builder()
                        .url("https://google.com/")
                        .build();
                Response response = client.newCall(request).execute();
                Log.d("OkHttpTest", "Response code: " + response.code());
            }catch (Exception e)
            {
                e.printStackTrace();
            }
```

fails with exception/stacktrace:

```
 javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:219)
     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:299)
     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:268)
     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:160)
     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:256)
     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:134)
```

According to the documentation [here](https://square.github.io/okhttp/3.x/okhttp/okhttp3/CertificatePinner.html) , it should be failing with  `javax.net.ssl.SSLPeerUnverifiedException: Certificate pinning failure!`

Also, the code in the example doesn't look like it's ever been used/compiled because the line:

`OkHttpClient client = OkHttpClient.Builder()` should be 
`OkHttpClient client = new OkHttpClient.Builder()`

**Comment by swankjesse** [comment]
Your device first needs to trust Google’s CA certificate. It’s failing to connect before it gets to the certificate pinning phase.

**Comment by Fuzion24** [comment]
The use case here is being able to pin a self-signed cert.

**Comment by Fuzion24** [comment]
https://github.com/square/okhttp/issues/1352 ... Ok, I guess it's just not supported. Bummer.

**Comment by Fuzion24** [comment]
```
                    Log.d("OKHTTPTEST","okhttp3 code starting" );
                    String hostname = "some.domain.com";

                    okhttp3.CertificatePinner certificatePinner = new okhttp3.CertificatePinner.Builder()
                            .add("*.*", "sha1/YWFhYWEK=")
                            .build();

                    // Create a trust manager that does not validate certificate chains
                    final TrustManager[] trustAllCerts = new TrustManager[] {
                            new X509TrustManager() {
                                @Override
                                public void checkClientTrusted(java.security.cert.X509Certificate[] chain, String authType) throws CertificateException {
                                }

                                @Override
                                public void checkServerTrusted(java.security.cert.X509Certificate[] chain, String authType) throws CertificateException {
                                }

                                @Override
                                public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                                    return new X509Certificate[0];
                                }
                            }
                    };

                    final SSLContext sslContext = SSLContext.getInstance("SSL");
                    sslContext.init(null, trustAllCerts, new java.security.SecureRandom());
                    // Create an ssl socket factory with our all-trusting manager
                    final SSLSocketFactory sslSocketFactory = sslContext.getSocketFactory();

                    okhttp3.OkHttpClient okclient = new okhttp3.OkHttpClient.Builder()
                            .certificatePinner(certificatePinner)
                            .sslSocketFactory(sslSocketFactory, (X509TrustManager)trustAllCerts[0])
                            .hostnameVerifier(new HostnameVerifier() {
                                @Override
                                public boolean verify(String hostname, SSLSession session) {
                                    return true;
                                }
                            })
                            .build();


                    okhttp3.Request request = new okhttp3.Request.Builder()
                            .url("https://" + hostname )
                            .build();
                    okclient.newCall(request).execute();
                    Log.d("OKHTTPTEST", "okhttp3 code finished" );
                } catch (Exception e) {
                    e.printStackTrace();
                    Log.d("OKHTTPTEST", "okhttp3 code crashed" );
                }
            }
```

**Comment by Fuzion24** [comment]
@swankjesse is there some reason that code shouldn't pin a self signed cert ^

**Comment by swankjesse** [comment]
Can you please provide an executable test case that demonstrates the problem? We have lots of tests for certificate pinning to get you started.

**Comment by Fuzion24** [comment]
With a selfsigned certificate, this code fails:
```java
            final TrustManager[] trustAllCerts = new TrustManager[] {
                    new X509TrustManager() {
                        @Override
                        public void checkClientTrusted(java.security.cert.X509Certificate[] chain, String authType) throws CertificateException {
                        }

                        @Override
                        public void checkServerTrusted(java.security.cert.X509Certificate[] chain, String authType) throws CertificateException {
                        }

                        @Override
                        public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                            return new X509Certificate[0];
                        }
                    }
            };
            try {


                final SSLContext sslContext = SSLContext.getInstance("SSL");
                sslContext.init(null, trustAllCerts, new java.security.SecureRandom());
                // Create an ssl socket factory with our all-trusting manager
                final SSLSocketFactory sslSocketFactory = sslContext.getSocketFactory();
                


                CertificatePinner certPinner = new CertificatePinner.Builder()
                        .add("*",
                                "sha256/NEGpkNhlaz0SO4q4ovoSAytFeqwCA4Xi+ZEQMbHSSB4=")
                        .build();

                client = new OkHttpClient.Builder()
                        .certificatePinner(certPinner)
                        .hostnameVerifier(new HostnameVerifier() {
                            @Override
                            public boolean verify(String hostname, SSLSession session) {
                                return true;
                            }
                        })
                        .sslSocketFactory(sslSocketFactory, (X509TrustManager)trustAllCerts[0])
                        .build();
```

and this code succeeds
```
            final TrustManager[] trustAllCerts = new TrustManager[] {
                    new X509TrustManager() {
                        @Override
                        public void checkClientTrusted(java.security.cert.X509Certificate[] chain, String authType) throws CertificateException {
                        }

                        @Override
                        public void checkServerTrusted(java.security.cert.X509Certificate[] chain, String authType) throws CertificateException {
                        }

                        @Override
                        public java.security.cert.X509Certificate[] getAcceptedIssuers() {
                            return new X509Certificate[0];
                        }
                    }
            };
            try {


                final SSLContext sslContext = SSLContext.getInstance("SSL");
                sslContext.init(null, trustAllCerts, new java.security.SecureRandom());
                // Create an ssl socket factory with our all-trusting manager
                final SSLSocketFactory sslSocketFactory = sslContext.getSocketFactory();
                


                CertificatePinner certPinner = new CertificatePinner.Builder()
                        .add("*",
                                "sha256/NEGpkNhlaz0SO4q4ovoSAytFeqwCA4Xi+ZEQMbHSSB4=")
                        .build();

                client = new OkHttpClient.Builder()
                        //.certificatePinner(certPinner)
                        .hostnameVerifier(new HostnameVerifier() {
                            @Override
                            public boolean verify(String hostname, SSLSession session) {
                                return true;
                            }
                        })
                        .sslSocketFactory(sslSocketFactory, (X509TrustManager)trustAllCerts[0])
                        .build();
```

**Comment by avently** [comment]
@swankjesse any news? 
I need to pin self-signed cert too but getting this:
```
javax.net.ssl.SSLPeerUnverifiedException: Failed to find a trusted cert that signed Certificate
at okhttp3.internal.tls.BasicCertificateChainCleaner.clean(BasicCertificateChainCleaner.java:97)
at okhttp3.CertificatePinner.check(CertificatePinner.java:166)
```
I do the same steps as @Fuzion24

**Comment by swankjesse** [comment]
BTW, don't use `add("*", ...)`. An asterisk never matches a dot, so `*` matches `squareup` but not `squareup.com`.

**Comment by avently** [comment]
@swankjesse I use local ip as a pattern, like
```
.add("192.168.1.2", "sha256/...")
``
I don't need domains in a project

**Comment by BulatMukhutdinov** [comment]
any updates on this?

**Comment by filipatbnp** [comment]
what happened here?
