### ISSUE TITLE
Retry UnknownHostExceptions thrown by InetAddress?

### ISSUE THREAD

**Issue by jpd236** [square/okhttp#3981]
On desktop (Mac) Java 8, using okhttp 3.10.0, I hit the following failure, but the request succeeded on a subsequent try a few seconds later:

```
    java.net.UnknownHostException: [host redacted]: nodename nor servname provided, or not known
    	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
    	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
    	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1323)
    	at java.net.InetAddress.getAllByName0(InetAddress.java:1276)
    	at java.net.InetAddress.getAllByName(InetAddress.java:1192)
    	at java.net.InetAddress.getAllByName(InetAddress.java:1126)
    	at okhttp3.Dns$1.lookup(Dns.java:40)
    	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.java:185)
    	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.java:149)
    	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:84)
    	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:214)
    	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
    	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
    	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
    	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
    	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
    	at java.lang.Thread.run(Thread.java:748)
```

FWIW I'm using my ISP's default DNS servers.

It seems that OkHttp's policy in general is to retry failures for various connectivity errors, particularly in situations that the request could not possibly have reached a backend. InetAddress will throw UnknownHostException "if no IP address for the host could be found". Seems to me like this could potentially include transient failures to communicate with the DNS server. But I'm unclear from the stack above whether the DNS server was reached and just returned an invalid response, or if it couldn't be reached at all, or if it doesn't really matter either way because the failure was transient so it should be retried.

I can look into a patch/failing test if there's agreement that the behavior here should change.

Thanks!

**Comment by swankjesse** [comment]
This one you'll need to retry on your own. We do retry automatically, but only when failures are due to known transient problems like stale connections. If a DNS request fails it's very likely to fail again on an immediate retry.

**Comment by jpd236** [comment]
That seems reasonable, and I'd agree from the error that there's no real indication that this should be transient. Thanks.
