### ISSUE TITLE
No route to host

### ISSUE THREAD

**Issue by CHRehan** [square/okhttp#3982]
**AndroidPlatform line 63**
**okhttp3.internal.platform.AndroidPlatform.connectSocket**

My Crashlytics report this crash of okhttp lib.
```
Caused by java.net.NoRouteToHostException: No route to host
       at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java)
       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:334)
       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:196)
       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:178)
       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
       at java.net.Socket.connect(Socket.java:586)
       at okhttp3.internal.platform.AndroidPlatform.connectSocket(SourceFile:63)
       at okhttp3.internal.connection.RealConnection.connectSocket(SourceFile:223)
       at okhttp3.internal.connection.RealConnection.connect(SourceFile:149)
       at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:195)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:121)
       at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:100)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:120)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
       at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:185)
       at okhttp3.RealCall.execute(SourceFile:69)
       at com.jakewharton.retrofit.Ok3Client.execute(SourceFile:40)
       at retrofit.RestAdapter$RestHandler.invokeRequest(SourceFile:326)
       at retrofit.RestAdapter$RestHandler.invoke(SourceFile:240)
       at java.lang.reflect.Proxy.invoke(Proxy.java:813)
       at $Proxy1.getUserStatus(Unknown Source)
       at com.shahisawari.JSONParser.getUserStatus(SourceFile:404)
       at com.shahisawari.dashboards.PrimaryDashboard$108.run(SourceFile:6967)
       at java.lang.Thread.run(Thread.java:762)
```

**Comment by swankjesse** [comment]
Typically this indicates a connectivity error,m either client side or server-side. No action for us to take on this.
