### ISSUE TITLE
OutOfMemoryError

### ISSUE THREAD

**Issue by louiewh** [square/okhttp#4002]
05-14 19:01:04.292 28832-29788/com.nio.bigdataservice I/art: Starting a blocking GC Alloc
05-14 19:01:04.292 28832-29788/com.nio.bigdataservice E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
                                                                        Process: com.nio.bigdataservice, PID: 28832
                                                                        java.lang.OutOfMemoryError: Failed to allocate a 8204 byte allocation with 5920 free bytes and 5KB until OOM
                                                                            at okio.Segment.<init>(Segment.java:61)
                                                                            at okio.SegmentPool.take(SegmentPool.java:46)
                                                                            at okio.Buffer.writableSegment(Buffer.java:1157)
                                                                            at okio.Okio$2.read(Okio.java:136)
                                                                            at okio.Buffer.writeAll(Buffer.java:993)
                                                                            at okhttp3.RequestBody$3.writeTo(RequestBody.java:120)
                                                                            at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:173)
                                                                            at okhttp3.MultipartBody.writeTo(MultipartBody.java:114)
                                                                            at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:189)
                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
                                                                            at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
                                                                            at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
                                                                            at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
                                                                            at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
                                                                            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                            at java.lang.Thread.run(Thread.java:818)
05-14 19:01:04.293 28832-28854/com.nio.bigdataservice I/art: WaitForGcToComplete blocked for 59.178ms for cause Alloc
05-14 19:01:04.293 28832-28854/com.nio.bigdataservice I/art: Starting a blocking GC Alloc

**Comment by louiewh** [comment]
![image](https://user-images.githubusercontent.com/7629135/39995075-d5413876-57ad-11e8-9f34-7c41e46da1e4.png)

**Comment by MasoomBadi** [comment]
@louiewh You found any work around or solution?
