### ISSUE TITLE
SSLHandshakeException 

### ISSUE THREAD

**Issue by thymleaf** [square/okhttp#4005]
javax.net.ssl.SSLHandshakeException: java.lang.RuntimeException: error:04000071:RSA routines:OPENSSL_internal:DATA_TOO_LARGE

android 8.1.0

X509TrustManager:

```
public void checkServerTrusted(X509Certificate[] chain, String authType) throws CertificateException
 {
                if (chain == null)
                {
                    throw new IllegalArgumentException("Check Server X509Certificate Is Null");
                }
                if (chain.length < 0)
                {
                    throw new IllegalArgumentException("Check Server X509Certificate Is Empty");
                }

                for (X509Certificate cert : chain)
                {
                    cert.checkValidity();
                    try
                    {
                        InputStream is = new BufferedInputStream(context.getAssets().open("my.pem"));
                        CertificateFactory certificateFactory = CertificateFactory.getInstance("X.509");
                        X509Certificate serverCert = (X509Certificate) certificateFactory.generateCertificate(is);
                        cert.verify(serverCert.getPublicKey());
                    }
                    catch (NoSuchAlgorithmException e)
                    {
                        e.printStackTrace();
                    }
                    catch (InvalidKeyException e)
                    {
                        e.printStackTrace();
                    }
                    catch (NoSuchProviderException e)
                    {
                        e.printStackTrace();
                    }
                    catch (SignatureException e)
                    {
                        e.printStackTrace();
                    }
                    catch (IOException e)
                    {
                        e.printStackTrace();
                    }
                }
 }
```

and SSLContext:

```
private SSLContext getSslContext(Context context)
    {
        SSLContext sslContext = null;
        try
        {
//            sslContext = SSLContext.getInstance("TLS");
            sslContext = SSLContext.getInstance("SSL");
            sslContext.init(null, getTrustAllCerts(context), null);
        }
        catch (NoSuchAlgorithmException e)
        {
            e.printStackTrace();
        }
        catch (KeyManagementException e)
        {
            e.printStackTrace();
        }
        return  sslContext;
    }
```

please help me

**Comment by yschimke** [comment]
This type of question should really go to stackoverflow.  This doesn't look like an OkHttp specific error, but a problem with the SSL connection/implementation.  You will get a lot more eyes on this in stackoverflow.

Feel free to link the question here, but I'm closing this in the issue tracker.

**Comment by thymleaf** [comment]
sorry , I should append more info,  detail log about okhttp:

<-- HTTP FAILED: javax.net.ssl.SSLHandshakeException: java.lang.RuntimeException: error:04000071:RSA routines:OPENSSL_internal:DATA_TOO_LARGE
 javax.net.ssl.SSLHandshakeException: java.lang.RuntimeException: error:04000071:RSA routines:OPENSSL_internal:DATA_TOO_LARGE
    at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:219)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:281)
    at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:251)
    at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:151)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:211)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at com.qiandw.app.GlobalConfiguration$2.intercept(GlobalConfiguration.java:164)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
at okhttp3.RealCall.execute(RealCall.java:69)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:180)
        at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
   at io.reactivex.Observable.subscribe(Observable.java:10901)
        at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
        at io.reactivex.Observable.subscribe(Observable.java:10901)
     at io.reactivex.internal.operators.flowable.FlowableFromObservable.subscribeActual(FlowableFromObservable.java:29)
     at io.reactivex.Flowable.subscribe(Flowable.java:12995)
    at io.reactivex.internal.operators.flowable.FlowableOnBackpressureLatest.subscribeActual(FlowableOnBackpressureLatest.java:32)
        at io.reactivex.Flowable.subscribe(Flowable.java:12995)
        at io.reactivex.Flowable.subscribe(Flowable.java:12941)
        at io.reactivex.internal.operators.flowable.FlowableSubscribeOn$SubscribeOnSubscriber.run(FlowableSubscribeOn.java:82)
        at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
     at java.lang.Thread.run(Thread.java:764)
 Caused by: java.security.cert.CertificateException: java.lang.RuntimeException: error:04000071:RSA routines:OPENSSL_internal:DATA_TOO_LARGE
     at com.android.org.conscrypt.OpenSSLX509Certificate.verifyOpenSSL(OpenSSLX509Certificate.java:366)
     at com.android.org.conscrypt.OpenSSLX509Certificate.verify(OpenSSLX509Certificate.java:394)
        at com.library.common.di.module.ClientModule$2.checkServerTrusted(ClientModule.java:286)
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:201)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:399)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.SslWrapper.doHandshake(SslWrapper.java:374)
    at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:217)
 	... 43 more
 Caused by: java.lang.RuntimeException: error:04000071:RSA routines:OPENSSL_internal:DATA_TOO_LARGE
    at com.android.org.conscrypt.NativeCrypto.X509_verify(Native Method)
        at com.android.org.conscrypt.OpenSSLX509Certificate.verifyOpenSSL(OpenSSLX509Certificate.java:364)
    	... 50 more
