### ISSUE TITLE
UNIX domain sockets should close gracefully

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#4106]
Currently there's an exception.

```
java.io.IOException: accept failed: Software caused connection abort
	at jnr.unixsocket.UnixServerSocketChannel.accept(UnixServerSocketChannel.java:61)
	at okhttp3.unixdomainsockets.UnixDomainServerSocketFactory$UnixDomainServerSocket.accept(UnixDomainServerSocketFactory.java:85)
	at okhttp3.mockwebserver.MockWebServer$2.acceptConnections(MockWebServer.java:359)
	at okhttp3.mockwebserver.MockWebServer$2.execute(MockWebServer.java:336)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by swankjesse** [comment]
Fixed upstream in jnr-unixsocket 0.22.
