### ISSUE TITLE
Invalid json in OkHttp(3.11.0), but original json is valid

### ISSUE THREAD

**Issue by e16din** [square/okhttp#4154]
Http client:
```
        val loggingInterceptor = HttpLoggingInterceptor()
        loggingInterceptor.level = HttpLoggingInterceptor.Level.BODY

        val httpClient = OkHttpClient.Builder()
                .retryOnConnectionFailure(true)
                .readTimeout(60, TimeUnit.SECONDS)
                .connectTimeout(10, TimeUnit.SECONDS)
                .addInterceptor(loggingInterceptor)
                .build()
```

Exception:
```
W: com.squareup.moshi.JsonDataException: Expected BEGIN_OBJECT but was BEGIN_ARRAY at path $[3].history
        at com.squareup.moshi.JsonUtf8Reader.beginObject(JsonUtf8Reader.java:141)
W:     at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:156)
W:     at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
        at com.squareup.moshi.ClassJsonAdapter$FieldBinding.read(ClassJsonAdapter.java:205)
W:     at com.squareup.moshi.ClassJsonAdapter.fromJson(ClassJsonAdapter.java:167)
        at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
        at com.squareup.moshi.ArrayJsonAdapter.fromJson(ArrayJsonAdapter.java:56)
W:     at com.squareup.moshi.JsonAdapter$2.fromJson(JsonAdapter.java:128)
        at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:45)
        at retrofit2.converter.moshi.MoshiResponseBodyConverter.convert(MoshiResponseBodyConverter.java:27)
W:     at retrofit2.ServiceMethod.toResponse(ServiceMethod.java:122)
        at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:217)
W:     at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:116)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
W:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)
```

Original json:
https://gist.github.com/e16din/ba98346d43ed0e01c040f75f2d2ffd91#file-test_json_original

Json from OkHttp logs:
https://gist.github.com/e16din/e1eabbed87e15982c217695b85d93aa9#file-test_json_from_okhttp_logs

**Comment by swankjesse** [comment]
Yikes. I have no idea what could cause this regression but it's very serious.

If you have it, could you email me the URL that triggers this? My email address is `jwilson@squareup.com`.

**Comment by e16din** [comment]
@swankjesse I sent

**Comment by e16din** [comment]
You may use this url to reproduce the issue:
http://www.mocky.io/v2/5b4c9771310000482aa7e0b9

**Comment by swankjesse** [comment]
@e16din can you make us an executable test case to reproduce this? I couldn't reproduce locally.

**Comment by e16din** [comment]
@yschimke 
Yes, this is the case. Thank you very much!

I did not check this case on other versions.

**Comment by e16din** [comment]
> can you make us an executable test case to reproduce this? I couldn't reproduce locally.

@swankjesse 

I solved my problem on the server side.
Do you still need an example to reproduce this case?

**Comment by swankjesse** [comment]
Nope!
