### ISSUE TITLE
java.lang.ClassCastException: android.system.UnixSocketAddress cannot be cast to java.net.InetSocketAddress

### ISSUE THREAD

**Issue by XuMuFei** [square/okhttp#4181]
java.lang.ClassCastException: android.system.UnixSocketAddress cannot be cast to java.net.InetSocketAddress
	at libcore.io.IoBridge.getLocalInetSocketAddress(IoBridge.java:700)
	at libcore.io.IoBridge.connectDetail(IoBridge.java:197)
	at libcore.io.IoBridge.connect(IoBridge.java:138)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
	at java.net.Socket.connect(Socket.java:616)
	at okhttp3.internal.platform.AndroidPlatform.connectSocket(SourceFile:61)
	at okhttp3.internal.connection.RealConnection.connectSocket(SourceFile:187)
	at okhttp3.internal.connection.RealConnection.buildConnection(SourceFile:173)
	at okhttp3.internal.connection.RealConnection.connect(SourceFile:114)
	at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:193)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:129)
	at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:98)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:124)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
	at okhttp3.a.e(SourceFile:170)
	at okhttp3.a.a(SourceFile:33)
	at okhttp3.a$a.execute(SourceFile:120)
	at okhttp3.internal.NamedRunnable.run(SourceFile:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

Phone model：MI5  
system version：8.0

**Comment by swankjesse** [comment]
Executable test case?

**Comment by Kyson** [comment]
I have the same problem occasionally

# OkHttp Dispatcher(2540)
java.lang.ClassCastException
android.system.UnixSocketAddress cannot be cast to java.net.InetSocketAddress
--
libcore.io.IoBridge.getLocalInetSocketAddress(IoBridge.java:700)

2 libcore.io.IoBridge.connectDetail(IoBridge.java:197)
3 libcore.io.IoBridge.connect(IoBridge.java:138)
4 java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
5 java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
6 java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
7 java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
8 java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
9 java.net.Socket.connect(Socket.java:616)
10 okhttp3.internal.platform.AndroidPlatform.connectSocket(SourceFile:63)
11 okhttp3.internal.connection.RealConnection.connectSocket(SourceFile:220)
12 okhttp3.internal.connection.RealConnection.connect(SourceFile:146)
13 okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:186)
14 okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:121)
15 okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:100)
16 okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:42)
17 okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
18 okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
19 okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:93)
20 okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
21 okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
22 okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
23 okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
24 okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:120)
25 okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
26 okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
27 okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:179)
28 okhttp3.RealCall$AsyncCall.execute(SourceFile:129)
29 okhttp3.internal.NamedRunnable.run(SourceFile:32)
30 java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
31 java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
32 java.lang.Thread.run(Thread.java:764)

**phone model:samsung SM N9500
system version:Android 8.0.0,level 26**

**Comment by XuMuFei** [comment]
There are no test cases here, and it works with Retrofit, and this problem is not necessarily

**Comment by mjmasn** [comment]
Also seeing this in our crash logs for a React Native app (0.56.0). Only happens on Android Oreo 8.0.0 devices, RN appears to be running OkHttp 3.10 which supposedly worked around the underlying Android bug.

Relevant modules: 
* com.squareup.okhttp3:okhttp:3.10.0
* com.squareup.okhttp3:okhttp-urlconnection:3.10.0
* (also com.facebook.fresco:imagepipeline-okhttp3:1.9.0)

```
java.lang.ClassCastException: android.system.UnixSocketAddress cannot be cast to java.net.InetSocketAddress
  at libcore.io.IoBridge.getLocalInetSocketAddress(IoBridge.java:700)
  at libcore.io.IoBridge.connectDetail(IoBridge.java:197)
  at libcore.io.IoBridge.connect(IoBridge.java:138)
  at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
  at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
  at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
  at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
  at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:356)
  at java.net.Socket.connect(Socket.java:616)
  at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:63)
  at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:223)
  at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:149)
  at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:195)
  at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
  at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
  at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:185)
  at okhttp3.RealCall$AsyncCall.execute(RealCall.java:135)
  at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
  at java.lang.Thread.run(Thread.java:764)
```

**Comment by yschimke** [comment]
@mjmasn it looks like your stacktrace is from 3.8.0 https://github.com/square/okhttp/blob/parent-3.8.0/okhttp/src/main/java/okhttp3/internal/platform/AndroidPlatform.java

Please retest with 3.11

**Comment by mjmasn** [comment]
@yschimke ah you're right sorry, I think the upgrade to 3.10 was in RN 0.56, and this stack trace was from a 0.54 version of the app. Problem should be resolved going forward then which is good :) Ignore me!
