### ISSUE TITLE
NoSuchAlgorithmException: no such algorithm: ECDSA for provider BC

### ISSUE THREAD

**Issue by sockeqwe** [square/okhttp#4183]
Since `3.11.0` I get the following problems on Android emulators (tested in API 21 - API 28). Please note that it works on jvm on my machine perfectly fine but not on Android (emulators).

```
 java.lang.AssertionError: java.security.NoSuchAlgorithmException: no such algorithm: ECDSA for provider BC
        at okhttp3.tls.HeldCertificate$Builder.generateKeyPair(HeldCertificate.java:429)
        at okhttp3.tls.HeldCertificate$Builder.build(HeldCertificate.java:353)
        at com.hannesdorfmann.okhttpcertificate.MainActivity$onCreate$1.invoke(MainActivity.kt:22)
```

Here is a sample project showing the certificate tls problem:

https://github.com/sockeqwe/OkHttpCertificate

Just lunch the MainActivity and it produces the error stacktrace shown above.

**Comment by swankjesse** [comment]
Can fix.

**Comment by kagile** [comment]
Is it fixed?
