### ISSUE TITLE
java.lang.IllegalArgumentException: Unexpected TLS version: NONE

### ISSUE THREAD

**Issue by XuMuFei** [square/okhttp#4211]
java.lang.IllegalArgumentException: Unexpected TLS version: NONE
	at okhttp3.TlsVersion.forJavaName(SourceFile:46)
	at okhttp3.Handshake.get(SourceFile:55)
	at okhttp3.internal.connection.RealConnection.connectTls(SourceFile:242)
	at okhttp3.internal.connection.RealConnection.establishProtocol(SourceFile:198)
	at okhttp3.internal.connection.RealConnection.buildConnection(SourceFile:174)
	at okhttp3.internal.connection.RealConnection.connect(SourceFile:114)
	at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:193)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:129)
	at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:98)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:109)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:124)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
	at okhttp3.a.e(SourceFile:170)
	at okhttp3.a.a(SourceFile:33)
	at okhttp3.a$a.execute(SourceFile:120)
	at okhttp3.internal.NamedRunnable.run(SourceFile:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

model：vivo X21A
system version：8.1.0

**Comment by yschimke** [comment]
This is fixed already in 3.11, can you let me know if you can still reproduce this after upgrading.
