### ISSUE TITLE
NullPointerException if default ProxySelector is null

### ISSUE THREAD

**Issue by Vampire** [square/okhttp#4232]
Here the test:

```java
private final MockWebServer server = new MockWebServer();
@Before public void setUp() throws Exception { server.start(); }
@After public void tearDown() throws Exception { server.shutdown(); }
@Test public void nullDefaultProxySelector() throws Exception {
  server.enqueue(new MockResponse().setBody("abc"));

  ProxySelector.setDefault(null);

  OkHttpClient client = defaultClient().newBuilder()
      .build();

  Request request = new Request.Builder().url(server.url("/")).build();
  Response response = client.newCall(request).execute();
  assertEquals("abc", response.body().string());
}
```

And the result:

```java
Aug 25, 2018 4:36:39 PM okhttp3.mockwebserver.MockWebServer$2 execute
INFORMATION: MockWebServer[57774] starting to accept connections
Aug 25, 2018 4:36:39 PM okhttp3.mockwebserver.MockWebServer$2 acceptConnections
INFORMATION: MockWebServer[57774] done accepting connections: socket closed
Aug 25, 2018 4:36:39 PM okhttp3.SocksProxy$1 execute
INFORMATION: SocksProxy 57775 done accepting connections: socket closed

java.lang.NullPointerException: proxySelector == null

	at okhttp3.Address.<init>(Address.java:79)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.createAddress(RetryAndFollowUpInterceptor.java:212)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall.execute(RealCall.java:77)
	at okhttp3.SocksProxyTest.nullDefaultProxySelector(SocksProxyTest.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
```

To quote https://docs.oracle.com/javase/8/docs/api/java/net/ProxySelector.html#setDefault-java.net.ProxySelector-: `ps - The HTTP proxy selector, or null to unset the proxy selector.`, so `null` is an acceptable value that OkHttp should be able to cope with.

**Comment by swankjesse** [comment]
Yep, you’re right. We need a NullProxySelector or something.

Want to send a PR?

**Comment by Vampire** [comment]
There you have it :-)
