### ISSUE TITLE
NullPointerException adding request cookies

### ISSUE THREAD

**Issue by resonetmobiledev** [square/okhttp#4251]
Hi, not really sure what's the cause and can't replicate this crash, getting this crash in crashlytics, it looks like the retrieved cookie is null. Below is the crash log:

```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String okhttp3.l.a()' on a null object reference
       at okhttp3.internal.http.BridgeInterceptor.cookieHeader(BridgeInterceptor.java:124)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:86)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
       at okhttp3.RealCall.execute(RealCall.java:77)
       at appzilo.core.Http$Request.e(Http.java:317)
       at common.Gigs.backend.GigsBackend.getTasks(GigsBackend.java:51)
       at common.EarnTab.ui.m.a(OfferTabFragment.java:451)
       at appzilo.core.BackgroundWorker$BackgroundTask.doInBackground(BackgroundWorker.java:100)
       at appzilo.core.BackgroundWorker$BackgroundTask.doInBackground(BackgroundWorker.java:84)
       at android.os.AsyncTask$2.call(AsyncTask.java:333)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

```

**Comment by JakeWharton** [comment]
What version? Also please deobfuscate stack traces in the future before reporting problems.

**Comment by marcosalis** [comment]
I'm getting crash logs with this exception on OkHttp `3.11.0` from a live app.

Not sure it's related to #2948, however our implementation of `CookieJar` never returns null in `loadForRequest(HttpUrl)`

```
java.lang.NullPointerException: 
  at okhttp3.internal.http.BridgeInterceptor.cookieHeader (BridgeInterceptor.java:124)
  at okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.java:86)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:126)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
  at com.teamwork.auth.TeamworkAuthInterceptor.intercept (TeamworkAuthInterceptor.java:83)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:147)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:121)
  at okhttp3.RealCall.getResponseWithInterceptorChain (RealCall.java:200)
  at okhttp3.RealCall$AsyncCall.execute (RealCall.java:147)
```

**Comment by swankjesse** [comment]
@marcosalis executable test case/

**Comment by swankjesse** [comment]
I think OkHttp is correct to throw a NullPointerException in that case. No further action to take here.
