### ISSUE TITLE
java.lang.IllegalArgumentException: Unexpected TLS version: NONE

### ISSUE THREAD

**Issue by XuMuFei** [square/okhttp#4259]
java.lang.IllegalArgumentException: Unexpected TLS version: NONE
	at okhttp3.TlsVersion.forJavaName(SourceFile:53)
	at okhttp3.Handshake.get(SourceFile:56)
	at okhttp3.internal.connection.RealConnection.connectTls(SourceFile:282)
	at okhttp3.internal.connection.RealConnection.establishProtocol(SourceFile:251)
	at okhttp3.internal.connection.RealConnection.connect(SourceFile:151)
	at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:195)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:121)
	at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
	at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
	at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:120)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:92)
	at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:67)
	at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:185)
	at okhttp3.RealCall$AsyncCall.execute(SourceFile:135)
	at okhttp3.internal.NamedRunnable.run(SourceFile:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)

PACM00

8.1.0

**Comment by yschimke** [comment]
duplicate
