### ISSUE TITLE
Matrix test of conscrypt (1.2,1.3), jdk (7,8,10,11), tls (1.2,1.3)

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#4276]
I think users upgrading to 3.12 without upgrading conscrypt from 1.1.4 or 1.2.0 will hit a bug in the call to

    return Conscrypt.newProviderBuilder().provideTrustManager().build();

Before release, I'd like to test various cases and handle safely

**Comment by yschimke** [comment]
Error when running with Conscrypt 1.2, and using `Security.insertProviderAt(OpenSSLProvider(), 1)`

```
javax.net.ssl.SSLHandshakeException: Unknown authType: GENERIC
	at org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:373)
	at org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1148)
	at org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1103)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:851)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:723)
	at org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:688)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.readInternal(ConscryptEngineSocket.java:705)
	at org.conscrypt.ConscryptEngineSocket$SSLInputStream.access$100(ConscryptEngineSocket.java:607)
	at org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:171)
	at org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:150)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:318)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:282)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:167)
	at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
	at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.security.cert.CertificateException: Unknown authType: GENERIC
	at sun.security.validator.EndEntityChecker.checkTLSServer(EndEntityChecker.java:281)
	at sun.security.validator.EndEntityChecker.check(EndEntityChecker.java:141)
	at sun.security.validator.Validator.validate(Validator.java:264)
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324)
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:229)
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:105)
	at com.baulsupp.okurl.security.MergedX509TrustManager.checkServerTrusted(MergedX509TrustManager.kt:18)
	at org.conscrypt.Java7PlatformUtil.checkServerTrusted(Java7PlatformUtil.java:80)
	at org.conscrypt.Platform.checkServerTrusted(Platform.java:299)
	at org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1643)
	at org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:539)
	at org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1109)
	at org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1093)
	... 30 more
```

**Comment by yschimke** [comment]
I'm tempted to draw a hard line of only supporting Conscrypt > 1.3.  I think anyone adopting this in JVM (non-android) setting could upgrade trivially.  It would be nice to handle gracefully though.

**Comment by swankjesse** [comment]
I think you’re right. Especially because Conscrypt is used by few other libraries so we don’t have to worry much about version conflicts.
