### ISSUE TITLE
Getting "source exhuasted prematurely" error while data seems to be readable

### ISSUE THREAD

**Issue by ethanyuwang** [square/okhttp#4277]
I'm getting this error when I try to make a HTTP call with okhttp:

```
W/System.err: java.io.EOFException: source exhausted prematurely
W/System.err:     at okio.InflaterSource.read(InflaterSource.java:83)
W/System.err:     at okio.GzipSource.read(GzipSource.java:80)
W/System.err:     at okio.Buffer.writeAll(Buffer.java:1135)
W/System.err:     at okio.RealBufferedSource.readString(RealBufferedSource.java:199)
W/System.err:     at okhttp3.ResponseBody.string(ResponseBody.java:176)
W/System.err:     at com.ethanwang.andplay.OKHttpTaskTag.doInBackground(OKHttpTaskTag.java:41)
W/System.err:     at com.ethanwang.andplay.OKHttpTaskTag.doInBackground(OKHttpTaskTag.java:20)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
W/System.err:     at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)

```

I have logged the request and response with an interceptor:

```
 I/System.out: INFO: Sending request http://test.essaybot.com/msg/tag_search on Connection{test.essaybot.com:80, proxy=DIRECT hostAddress=test.essaybot.com/54.218.32.232:80 cipherSuite=none protocol=http/1.1}
 I/System.out: Content-Type: application/x-www-form-urlencoded
 I/System.out: Content-Length: 33
 I/System.out: Host: test.essaybot.com
 I/System.out: Connection: Keep-Alive
 I/System.out: Accept-Encoding: gzip
 I/System.out: User-Agent: okhttp/3.11.0

 I/System.out: INFO: Received response for http://test.essaybot.com/msg/tag_search in 41.2ms
 I/System.out: Cache-Control: no-cache
 I/System.out: Content-Encoding: gzip
 I/System.out: Content-Length: 139
 I/System.out: Content-Type: application/json
 I/System.out: Set-Cookie: PHP_SESSION=yjslS045YZTujhZrLAh1; Path=/; Max-Age=2592000
 I/System.out: Set-Cookie: VISITOR_ID=A9SxFrWtn4ksJeKb; Path=/; Max-Age=31536000
 I/System.out: Date: Tue, 18 Sep 2018 23:25:57 GMT
```

I have also tried to use a debugger to track where this errro comes from:
<img width="1680" alt="screen shot 2018-09-18 at 4 17 32 pm" src="https://user-images.githubusercontent.com/17556945/45721892-bef75400-bb5e-11e8-9c6e-359b0504f2cc.png">

Strangely it seems like the data in the buffer is readable since there's the correct response annotated after the buffer variable:

sink = {Buffer@4764} "[size=185 text={"err_no":0,"result":["Adventure","Advice","Art","Africa","Airli…]"

sink.head.data contains this following byte array:

```
0 = 123
1 = 34
2 = 101
3 = 114
4 = 114
5 = 95
6 = 110
7 = 111
8 = 34
9 = 58
10 = 48
11 = 44
12 = 34
13 = 114
14 = 101
15 = 115
16 = 117
17 = 108
18 = 116
19 = 34
20 = 58
21 = 91
22 = 34
23 = 65
24 = 100
25 = 118
26 = 101
27 = 110
28 = 116
29 = 117
30 = 114
31 = 101
32 = 34
33 = 44
34 = 34
35 = 65
36 = 100
37 = 118
38 = 105
39 = 99
40 = 101
41 = 34
42 = 44
43 = 34
44 = 65
45 = 114
46 = 116
47 = 34
48 = 44
49 = 34
50 = 65
51 = 102
52 = 114
53 = 105
54 = 99
55 = 97
56 = 34
57 = 44
58 = 34
59 = 65
60 = 105
61 = 114
62 = 108
63 = 105
64 = 110
65 = 101
66 = 115
67 = 34
68 = 44
69 = 34
70 = 65
71 = 110
72 = 120
73 = 105
74 = 101
75 = 116
76 = 121
77 = 34
78 = 44
79 = 34
80 = 65
81 = 114
82 = 116
83 = 105
84 = 102
85 = 105
86 = 99
87 = 105
88 = 97
89 = 108
90 = 32
91 = 73
92 = 110
93 = 116
94 = 101
95 = 108
96 = 108
97 = 105
98 = 103
99 = 101
100 = 110
101 = 99
102 = 101
103 = 34
104 = 44
105 = 34
106 = 65
107 = 112
108 = 112
109 = 115
110 = 34
111 = 44
112 = 34
113 = 65
114 = 100
115 = 100
116 = 105
117 = 99
118 = 116
119 = 105
120 = 111
121 = 110
122 = 34
123 = 44
124 = 34
125 = 65
126 = 117
127 = 115
128 = 116
129 = 114
130 = 97
131 = 108
132 = 105
133 = 97
134 = 34
135 = 44
136 = 34
137 = 65
138 = 105
139 = 114
140 = 98
141 = 110
142 = 98
143 = 34
144 = 44
145 = 34
146 = 65
147 = 103
148 = 105
149 = 110
150 = 103
151 = 34
152 = 44
153 = 34
154 = 65
155 = 100
156 = 118
157 = 101
158 = 114
159 = 116
160 = 105
161 = 115
162 = 105
163 = 110
164 = 103
165 = 34
166 = 44
167 = 34
168 = 65
169 = 108
170 = 99
171 = 111
172 = 104
173 = 111
174 = 108
175 = 34
176 = 44
177 = 34
178 = 65
179 = 115
180 = 105
181 = 97
182 = 34
183 = 93
184 = 125
```

What went wrong here?

**Comment by swankjesse** [comment]
Typically this occurs when the trailer bytes at the end of the compressed stream are missing.

**Comment by swankjesse** [comment]
No clear action to take on this.

**Comment by ethanyuwang** [comment]
I used the debugger to trace the problem and it seems like the gzipped response was decompressed twice. As shown in the pictures attached, `read` in `InflaterSource.java` is called twice.  The exception is thrown at the second time it's being decompressed. 

![screen shot 2018-11-28 at 11 33 38 am](https://user-images.githubusercontent.com/17556945/49177296-b6ab5a00-f301-11e8-978e-1723a367c27d.png)
![screen shot 2018-11-28 at 11 32 59 am](https://user-images.githubusercontent.com/17556945/49177297-b6ab5a00-f301-11e8-9883-8f61ee3a1042.png)

**Comment by jayclf** [comment]
I get the same problem，YI~~~~~~~
