### ISSUE TITLE
Error networkResponse.networkResponse != null

### ISSUE THREAD

**Issue by LomikXP** [square/okhttp#4303]
https://github.com/square/okhttp/blob/ceb42f132220c71c7ad9a2948b24ee4f9e7df8e0/okhttp/src/main/java/okhttp3/internal/cache/CacheInterceptor.java#L125
Is this line is right, and what it for?
I get error from some users, and dont get how it does.

**Comment by LomikXP** [comment]
```
java.lang.IllegalArgumentException: networkResponse.networkResponse != null
	at okhttp3.Response$Builder.checkSupportResponse(Response.java:406)
	at okhttp3.Response$Builder.networkResponse(Response.java:391)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:125)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at org.mangawatcher2.helper.r$3.intercept(OkClient.java:389)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
```

**Comment by LomikXP** [comment]
```
@Override
					public Response intercept(Chain chain) throws IOException {
						Uri url = Uri.parse(chain.request().url().toString());
						Request.Builder newRequest = chain.request().newBuilder();
						if (GUString.isEmpty(chain.request().header(KEY_USER_AGENT)))
							newRequest.addHeader(KEY_USER_AGENT, GULink.USER_AGENT_RANDOM);
						// parser interceptor set
						WeakReference<ParserClass> parserRef = interceptorsWParser.get(url);
						if (parserRef != null) {
							ParserClass parser = parserRef.get();
							if (parser != null && parser.getAuthorization() != null) {
								parser.getAuthorization().setCredentials(newRequest, false);
							}
							interceptorsWParserCheck.put(url, parserRef);
							interceptorsWParser.remove(url);
						}
						Response proceedResponse = null;
						try {
							proceedResponse = chain.proceed(newRequest.build());
						} catch (IllegalArgumentException e) {
							GUFile.closeQuietly(proceedResponse);
							if (GUType.getErrorMessageSafe(e).contains("networkResponse != null")){
								proceedResponse = chain.proceed(newRequest.cacheControl(CacheControl.FORCE_NETWORK).build());
							}
							else
								throw e;
						}
						return proceedResponse;
					}
				}
```

**Comment by swankjesse** [comment]
Can you write a test case to reproduce the problem?

**Comment by LomikXP** [comment]
> Can you write a test case to reproduce the problem?

I dont know how it happer. On some devices. Not all.

**Comment by LomikXP** [comment]
Need expert or code author, I want ask how can be networkResponse null on network force request? (see first message)

**Comment by swankjesse** [comment]
Unclear what action to take here.

**Comment by aliiizzz** [comment]
i think if you call httpException.response().raw() twice you get this error

**Comment by aliiizzz** [comment]
`java.lang.IllegalArgumentException: networkResponse.networkResponse != null
        at okhttp3.Response$Builder.checkSupportResponse(Response.java:411)
        at okhttp3.Response$Builder.networkResponse(Response.java:396)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:225)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)`
