### ISSUE TITLE
WebSocketWriter.writeClose crashes the app

### ISSUE THREAD

**Issue by GurvinderBawa** [square/okhttp#4325]
Android app
using SOCKET.io version 0.5.0
implementation 'com.github.nkzawa:socket.io-client:0.5.0'

i can only see in fabrics crashlytics, the users are facing this crash, but i have no idea why this is coming up, most probably it has something related to webSocket.Writer.writeClose.
How to fix this ?

Crashed: OkHttp http://17.176.117.92:3007/socket.io/?EIO=3&transport=websocket&sid=P5vRfdWExfmHPuAAAV WebSocket
at com.squareup.okhttp.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:110)
at com.squareup.okhttp.internal.ws.RealWebSocket.peerClose(RealWebSocket.java:146)
at com.squareup.okhttp.internal.ws.RealWebSocket.access$100(RealWebSocket.java:31)
at com.squareup.okhttp.internal.ws.RealWebSocket$1$2.execute(RealWebSocket.java:74)
at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)

--

Fatal Exception: java.lang.IllegalArgumentException: Code required to include reason.
at com.squareup.okhttp.internal.ws.WebSocketWriter.writeClose(WebSocketWriter.java:110)
at com.squareup.okhttp.internal.ws.RealWebSocket.peerClose(RealWebSocket.java:146)
at com.squareup.okhttp.internal.ws.RealWebSocket.access$100(RealWebSocket.java:31)
at com.squareup.okhttp.internal.ws.RealWebSocket$1$2.execute(RealWebSocket.java:74)
at com.squareup.okhttp.internal.NamedRunnable.run(NamedRunnable.java:33)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
at java.lang.Thread.run(Thread.java:764)

**Comment by swankjesse** [comment]
Your stacktrace suggests a very old version of OkHttp. 
Please upgrade to a recent OkHttp before reporting future bugs!

**Comment by GurvinderBawa** [comment]
implementation 'com.squareup.okhttp3:logging-interceptor:3.10.0'
    implementation 'com.squareup.retrofit2:retrofit:2.3.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'

do i need to explicity add " implementation 'com.squareup.okhttp3:okhttp:3.11.0'"  ???? retrofit doesn't implement it inside the lib ?

**Comment by dhruvkaushal11** [comment]
@GurvinderBawa Able to fix it?

**Comment by GurvinderBawa** [comment]
@dhruvkaushal11 - i was not able to test it later, you can try what i wrote in the above comment and as suggested by swankjesse
