### ISSUE TITLE
why connectionReleased is called after calling responseHeadersStart immediately

### ISSUE THREAD

**Issue by mio4kon** [square/okhttp#4347]
`okhttp version : 3.11.0`
`http/1.1`

why connectionReleased is called after calling responseHeadersStart immediately?

method connectionAcquired and method callFailed are being  4g network.

and where throw the IOException, and message is null ?

> #!v1#!HttpLogEvent#*call id :13, request url :
#!v1#!HttpLogEvent#*call id :13, elapsed :1.7447E-5, event: callStart
#!v1#!HttpLogEvent#*call id :13, elapsed :0.001936458, event: connectionAcquired #NET# 4g
#!v1#!HttpLogEvent#*call id :13, elapsed :0.002123593, event: requestHeadersStart
#!v1#!HttpLogEvent#*call id :13, elapsed :0.003039739, event: requestHeadersEnd
#!v1#!HttpLogEvent#*call id :13, elapsed :0.003174479, **event: responseHeadersStart**
#!v1#!HttpLogEvent#*call id :13, elapsed :0.035882552, **event: connectionReleased** 
#!v1#!HttpLogEvent#*call id :13, elapsed :0.035959114, event: callEnd
#!v1#!HttpLogEvent#*call id :13, elapsed :0.036975937, event: callFailed
#!v1#!HttpLogEvent#*call id :13 , callFailed reason IOException:null #NET# 4g

**Comment by swankjesse** [comment]
Executable test case?

**Comment by yschimke** [comment]
There was a bug in a previous version before 3.11

https://github.com/square/okhttp/pull/3551

Please confirm it still happens in 3.11

**Comment by mio4kon** [comment]
> There was a bug in a previous version before 3.11
> 
> #3551
> 
> Please confirm it still happens in 3.11

I am sure I am using **3.11** version

`compile 'com.squareup.okhttp3:okhttp:3.11.0'`
`compile 'com.squareup.okhttp3:logging-interceptor:3.11.0'`

**Comment by yschimke** [comment]
Can you print the stacktrace (IOException:null) that shows up on the last line also?

Thanks

**Comment by mio4kon** [comment]
> Can you print the stacktrace (IOException:null) that shows up on the last line also?
> 
> Thanks

Then I will add the log first and give you feedback in time.

**Comment by mio4kon** [comment]
> Can you print the stacktrace (IOException:null) that shows up on the last line also?
> 
> Thanks

i got the stacktrace log.

> #!HttpLogEvent#*call id :722, request url :
#!HttpLogEvent#*call id :722, elapsed :6.4062E-5, event: callStart
#!HttpLogEvent#*call id :722, elapsed :0.001953125, event: connectionAcquired #NET# 4
#!HttpLogEvent#*call id :722, elapsed :0.002261979, event: requestHeadersStart
#!HttpLogEvent#*call id :722, elapsed :0.003109375, event: requestHeadersEnd
#!HttpLogEvent#*call id :722, elapsed :0.003411979, event: responseHeadersStart
#!HttpLogEvent#*call id :722, elapsed :6.646547915, event: connectionReleased
#!HttpLogEvent#*call id :722, elapsed :6.646704165, event: callEnd
#!HttpLogEvent#*call id :722, elapsed :6.647768749, event: callFailed
#!HttpLogEvent#*call id :722 , callFailed reason IOException:null #NET# 4
#!HttpLogEvent#*call id :722 , callFailed Exception trace :
#!HttpLogEvent#*call id :722 , callFailed Exception trace : 
okhttp3.internal.http2.Http2Stream.waitForIo(SourceFile:602)
okhttp3.internal.http2.Http2Stream.takeResponseHeaders(SourceFile:143)
okhttp3.internal.http2.Http2Codec.readResponseHeaders$___twin___(SourceFile:127)
okhttp3.internal.http2.Http2Codec.access$002(Unknown Source:0)
okhttp3.internal.http2.Http2Codec.readResponseHeaders(Unknown Source:0)
okhttp3.internal.http.CallServerInterceptor.intercept(SourceFile:88)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
okhttp3.internal.connection.ConnectInterceptor.intercept$___twin___(SourceFile:45)
okhttp3.internal.connection.ConnectInterceptor.access$000(Unknown Source:0)
okhttp3.internal.connection.ConnectInterceptor.intercept(Unknown Source:0)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:93)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:126)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
me.ele.talariskernel.network.b.intercept(SourceFile:37)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
me.ele.talariskernel.network.e.intercept(SourceFile:21)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
me.ele.skynet.network.hook.a.i.intercept(SourceFile:31)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:200)
okhttp3.RealCall.execute(SourceFile:77)

**Comment by manickamviswa** [comment]
The same issues happens. I am using the okhttp version 3.11.0. 

Please find the exception stacktrace:

INFO  11097 : 2.1701E-5 -- callStart
INFO  11097 : 1.44572E-4 -- connectionAcquired
INFO  11097 : 0.001036047 -- requestHeadersStart
INFO  11097 : 0.001064492 -- requestHeadersEnd 
INFO  11097 : 0.001084433 -- requestBodyStart 
INFO  11097 : 0.001103787 -- requestBodyEnd
INFO  11097 : 0.001279736 -- responseHeadersStart
INFO  11097 : 1.007175496 -- responseHeadersEnd
INFO  11097 : 1.007247928 -- responseBodyStart
INFO  11097 : 31.082725087 -- connectionReleased
INFO  11097 : 31.083717147 -- callFailed
INFO  11097 : 31.092341876 -- 

java.net.SocketTimeoutException: Read timed out
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:171)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
    at sun.security.ssl.InputRecord.read(InputRecord.java:503)
    at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:983)
    at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:940)
    at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
    at okio.Okio$2.read(Okio.java:140)
    at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
    at okio.RealBufferedSource.request(RealBufferedSource.java:68)
    at okio.RealBufferedSource.require(RealBufferedSource.java:61)
    at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:304)
    at okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:469)
    at okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:449)
    at okio.RealBufferedSource.request(RealBufferedSource.java:68)
    at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:241)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:213)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
    at okhttp3.RealCall.execute(RealCall.java:77)
    at okhttp3.Call$execute.call(Unknown Source)

**Comment by vedydev** [comment]
@swankjesse @yschimke What changes can we make locally now to the code to overcome issue #4347 and #3551 before the fix in 3.13 is released?

**Comment by swankjesse** [comment]
If we had that handy we'd just commit a fix!

**Comment by swankjesse** [comment]
Unclear what action to take here. If you’re still unhappy with our current behavior, please make an executable test case to demonstrate your desired behavior!
