### ISSUE TITLE
On-device test failure: "IllegalStateException: attempt to use Deflater after calling end"

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#436]
I'm running a test on a device with vogar and it looks like closing streams can be re-entrant.

```
  com.squareup.okhttp.ConnectionPoolTest#maxConnections
    Jan 12, 2014 8:09:12 AM com.squareup.okhttp.mockwebserver.MockWebServer$3 processConnection
    WARNING: MockWebServer connection didn't make a request
    Jan 12, 2014 8:09:12 AM com.squareup.okhttp.mockwebserver.MockWebServer$3 processConnection
    WARNING: MockWebServer connection didn't make a request
    Jan 12, 2014 8:09:13 AM com.squareup.okhttp.mockwebserver.MockWebServer$3 processConnection
    WARNING: MockWebServer connection didn't make a request
    Jan 12, 2014 8:09:13 AM com.squareup.okhttp.mockwebserver.MockWebServer$3 processConnection
    WARNING: MockWebServer connection didn't make a request
    Jan 12, 2014 8:09:13 AM com.squareup.okhttp.mockwebserver.MockWebServer$3 processConnection
    WARNING: MockWebServer connection didn't make a request
    java.lang.IllegalStateException: attempt to use Deflater after calling end
        at java.util.zip.Deflater.checkOpen(Deflater.java:476)java.lang.IllegalStateException: attempt to use Deflater after calling end
        at java.util.zip.Deflater.checkOpen(Deflater.java:476)
        at java.util.zip.Deflater.deflateImpl(Deflater.java:236)
        at java.util.zip.Deflater.deflate(Deflater.java:232)
        at java.util.zip.DeflaterOutputStream.flush(DeflaterOutputStream.java:193)
        at java.io.FilterOutputStream.flush(FilterOutputStream.java:88)
        at java.io.DataOutputStream.flush(DataOutputStream.java:63)
        at java.io.FilterOutputStream.close(FilterOutputStream.java:61)
        at com.squareup.okhttp.internal.Util.closeAll(Util.java:166)
        at com.squareup.okhttp.internal.spdy.Spdy3$Writer.close(Spdy3.java:468)
        at com.squareup.okhttp.internal.spdy.SpdyConnection.close(SpdyConnection.java:361)
        at com.squareup.okhttp.internal.spdy.SpdyConnection.close(SpdyConnection.java:313)
        at com.squareup.okhttp.internal.Util.closeQuietly(Util.java:116)
        at com.squareup.okhttp.mockwebserver.MockWebServer$2.run(MockWebServer.java:264)
        at com.squareup.okhttp.mockwebserver.MockWebServer$4.run(MockWebServer.java:634)

        at java.util.zip.Deflater.deflateImpl(Deflater.java:236)
        at java.util.zip.Deflater.deflate(Deflater.java:232)
        at java.util.zip.DeflaterOutputStream.flush(DeflaterOutputStream.java:193)
        at java.io.FilterOutputStream.flush(FilterOutputStream.java:88)
        at java.io.DataOutputStream.flush(DataOutputStream.java:63)

        at java.io.FilterOutputStream.close(FilterOutputStream.java:61)
        at com.squareup.okhttp.internal.Util.closeAll(Util.java:166)
        at com.squareup.okhttp.internal.spdy.Spdy3$Writer.close(Spdy3.java:468)
        at com.squareup.okhttp.internal.spdy.SpdyConnection.close(SpdyConnection.java:361)
        at com.squareup.okhttp.internal.spdy.SpdyConnection.access$1000(SpdyConnection.java:45)
        at com.squareup.okhttp.internal.spdy.SpdyConnection$Reader.run(SpdyConnection.java:455)
        at java.lang.Thread.run(Thread.java:841)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at java.lang.Thread.run(Thread.java:841)
    junit.framework.AssertionFailedError: expected:<1> but was:<2>
        at junit.framework.Assert.assertEquals(Assert.java:205)
        at com.squareup.okhttp.ConnectionPoolTest.maxConnections(ConnectionPoolTest.java:320)
```

**Comment by ashishb** [comment]
Was this issue ever resolved?

**Comment by swankjesse** [comment]
Yep.

**Comment by ashishb** [comment]
Thanks. Can you please point me to the fix?
