### ISSUE TITLE
Conscrypt >= 1.3 failing with HandshakeCertificatesTest.clientAndServer

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#4360]
From https://github.com/square/okhttp/pull/4349

```
java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: Handshake failed

	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at okhttp3.tls.HandshakeCertificatesTest.clientAndServer(HandshakeCertificatesTest.java:96)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: javax.net.ssl.SSLHandshakeException: Handshake failed
	at org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:287)
	at okhttp3.tls.HandshakeCertificatesTest$1.call(HandshakeCertificatesTest.java:165)
	at okhttp3.tls.HandshakeCertificatesTest$1.call(HandshakeCertificatesTest.java:154)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x7febda6739c8: Failure in SSL library, usually a protocol error
error:10000416:SSL routines:OPENSSL_internal:SSLV3_ALERT_CERTIFICATE_UNKNOWN (../ssl/tls_record.cc:587 0x7febda673f18:0x00000001)
	at org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
	at org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:385)
	at org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:225)
	... 6 more
```

**Comment by yschimke** [comment]
HandshakeCertificatesTest.clientAndServer fails regardless of engine/fd socket being configured. Still investigating.

**Comment by yschimke** [comment]
cc @flooey - Any known reasons why a test using self signed certs to do SSL handshake (no http) would regress with conscrypt 1.3?

**Comment by flooey** [comment]
The main thing in 1.3 was TLS 1.3 support, which I wouldn't expect to change much if you're aren't enabling it.  I can't think of anything else we changed in that release that would affect cert validation.

We disable logging in our release builds.  If you want to see everything that's happening, you can change `kWithJniTrace` to `true` in https://github.com/google/conscrypt/blob/master/common/src/jni/main/cpp/conscrypt/trace.cc and rebuild, that'll output traces of every JNI call to stdout.

**Comment by yschimke** [comment]
@flooey I'm still hoping for a SSL library that publishes handshake events via an API, and returns introspectible errors...

**Comment by iddoeldor** [comment]
> kWithJniTrace

where do I put the new build ? 
can I change the `so` in `/system/lib` ?

**Comment by flooey** [comment]
You probably want to build the AAR (the conscrypt-android:build gradle target) and include that in your app instead of trying to change the platform copy of Conscrypt (which would require building large chunks of AOSP).

**Comment by iddoeldor** [comment]
> You probably want to build the AAR (the conscrypt-android:build gradle target) and include that in your app instead of trying to change the platform copy of Conscrypt (which would require building large chunks of AOSP).

I've build the AOSP got Android8.0 emulator working
Installed Twitter APK on the emulator
I want to Twitter to use my patched conscrypt.so the get the master keys from logcat

How do I do that ?

**Comment by flooey** [comment]
@iddoeldor You'd need to change external/conscrypt/common/src/jni/main/cpp/conscrypt/trace.cc in AOSP and then rebuild AOSP and reflash.

**Comment by iddoeldor** [comment]
> @iddoeldor You'd need to change external/conscrypt/common/src/jni/main/cpp/conscrypt/trace.cc in AOSP and then rebuild AOSP and reflash.

Thanks again.

I will understand if you can't answer the following question but the scenario is that I can't reflash
so there will be compiler optimizations due to `kWithJniTraceKeys = false`
what do I need to hook to print out the master keys ?

**Comment by flooey** [comment]
@iddoeldor I'm not sure why you can't reflash (or rebuild the OS on the emulator, whatever method you want), but without one of the flags in trace.cc set to true, there aren't any hooks to get debugging information or keys out.

**Comment by iddoeldor** [comment]
> @iddoeldor I'm not sure why you can't reflash (or rebuild the OS on the emulator, whatever method you want), but without one of the flags in trace.cc set to true, there aren't any hooks to get debugging information or keys out.

Damn, I had a plan to hook `SSL_do_handshake` and extract keys from `ctx.get()`.

I can't reflash because I mostly work with real devices.

& Thank you !

**Comment by yschimke** [comment]
Flagged again in circleci

https://534-5152285-gh.circle-artifacts.com/0/home/circleci/reports/mockwebserver/build/reports/tests/test/classes/okhttp3.mockwebserver.MockWebServerTest.html

https://534-5152285-gh.circle-artifacts.com/0/home/circleci/reports/okhttp-tls/build/reports/tests/test/classes/okhttp3.tls.HandshakeCertificatesTest.html#clientAndServer
