### ISSUE TITLE
Benchmarks execution fails, caliper produces InvalidPathException

### ISSUE THREAD

**Issue by uvletter** [square/okhttp#4411]
Error injecting method, java.nio.file.InvalidPathException: Illegal char <:> at index 39: C:\Users\luv\.caliper\log\2018-11-24T07:41:12.520Z.ac71153b-c316-473c-a8b3-e3db2a98644
0.log.lck
  at com.google.caliper.config.LoggingConfigLoader.loadLoggingConfig(LoggingConfigLoader.java:56)
  at com.google.caliper.config.ConfigModule.configure(ConfigModule.java:31)
  while locating com.google.caliper.config.LoggingConfigLoader

1 error
        at com.google.inject.internal.Errors.throwCreationExceptionIfErrorsExist(Errors.java:435)
        at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:183)
        at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
        at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:217)
        at com.google.inject.internal.InjectorImpl.createChildInjector(InjectorImpl.java:224)
        at com.google.caliper.runner.CaliperMain.exitlessMain(CaliperMain.java:116)
        at com.google.caliper.runner.CaliperMain.main(CaliperMain.java:78)
        at com.google.caliper.runner.CaliperMain.main(CaliperMain.java:66)
        at okhttp3.benchmarks.Benchmark.main(Benchmark.java:94)

Environment: windows 10  jdk1.8

**Comment by swankjesse** [comment]
I think we gotta switch to JMH.
