### ISSUE TITLE
ProgressResponseBody SSLException on Network on/off

### ISSUE THREAD

**Issue by kagile** [square/okhttp#4418]
OkHttp Version : 
**Steps to reproduce:**

1. Use ProgressResponseBody and make a request on URL as shown below. 
2. Turn netowork off while response is read.

**Expected:** 
ConnectException or more specific Exception that would indicate network error
**StackTrace:**
```
javax.net.ssl.SSLException: Read error: ssl=0x84c3f200: I/O error during system call, Software caused connection abort
        at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:758)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.read(RealBufferedSource.java:47)
        at okhttp3.internal.http1.Http1Codec$AbstractSource.read(Http1Codec.java:363)
        at okhttp3.internal.http1.Http1Codec$FixedLengthSource.read(Http1Codec.java:407)
        at okio.RealBufferedSource.read(RealBufferedSource.java:47)
        at okio.ForwardingSource.read(ForwardingSource.java:35)

```
Code for **Request**
```
Request request = new Request.Builder()
                    .url(url)
                    .build();

            OkHttpClient client = new OkHttpClient.Builder()
                    .connectTimeout(ApiConfig.Timeouts.DOWNLOAD_CONNECT, TimeUnit.SECONDS)
                    .readTimeout(ApiConfig.Timeouts.DOWNLOAD_READ, TimeUnit.SECONDS)
                    .writeTimeout(ApiConfig.Timeouts.DOWNLOAD_WRITE, TimeUnit.SECONDS)
                    .cache(ApiConfig.getHttpCache())
                    .addNetworkInterceptor(chain -> {
                        Response originalResponse = chain.proceed(chain.request());
                        return originalResponse.newBuilder()
                                .body(new ProgressResponseBody(originalResponse.body(), progressListener))
                                .build();
                    })
                    .build();
```
Code for **ProgressResponseBody.java**:

```
public class ProgressResponseBody extends ResponseBody {

    private final ResponseBody responseBody;
    private final ProgressListener progressListener;
    private BufferedSource bufferedSource;

    ProgressResponseBody(ResponseBody responseBody, ProgressListener progressListener) {
        this.responseBody = responseBody;
        this.progressListener = progressListener;
    }

    @Override
    public MediaType contentType() {
        return responseBody.contentType();
    }

    @Override
    public long contentLength() {
        return responseBody.contentLength();
    }

    @Override
    public BufferedSource source() {
        if (bufferedSource == null) {
            bufferedSource = Okio.buffer(source(responseBody.source()));
        }
        return bufferedSource;
    }

    private Source source(Source source) {
        return new ForwardingSource(source) {
            long totalBytesRead = 0L;

            @Override
            public long read(Buffer sink, long byteCount) throws IOException {
                try {
                    long bytesRead = super.read(sink, byteCount);
                    // read() returns the number of bytes read, or -1 if this source is exhausted.
                    totalBytesRead += bytesRead != -1 ? bytesRead : 0;
                    progressListener.update(totalBytesRead, responseBody.contentLength(), bytesRead == -1);
                    return bytesRead;
                } catch (Exception e) {
                    e.printStackTrace();
                    return 0;
                }
            }
        };
    }


}
```

**Comment by swankjesse** [comment]
Please rewrite as an executable test case.

**Comment by kagile** [comment]
@swankjesse I don't know how to

**Comment by Adza93** [comment]
@swankjesse I am also having this issue via cordova-plugin-advanced-http, Ionic cordova plugin which use OkHttpClient as network layer for request response.

Same issue is happening with a lot of android users without any specific reason. I managed to catch exception mentioned @kagile, in same scenario. When Android system applies network change due to any reason (maybe wifi connection is offline, so it switches to 4g), exception is raised regarding SSL error, which is not correct, and should probably be timeout, or connection error on client side.

2019-06-12 13:34:16.873 619-826/ W/Cordova-Plugin-HTTP: TLS connection could not be established
    com.silkimen.http.HttpRequest$HttpRequestException: javax.net.ssl.SSLException: Read error: ssl=0x7321595188: I/O error during system call, Software caused connection abort
        at com.silkimen.http.HttpRequest.code(HttpRequest.java:1449)
        at com.silkimen.http.HttpRequest.stream(HttpRequest.java:1740)
        at com.silkimen.http.HttpRequest.buffer(HttpRequest.java:1729)
        at com.silkimen.http.HttpRequest.receive(HttpRequest.java:1856)
        at com.silkimen.cordovahttp.CordovaHttpBase.processResponse(CordovaHttpBase.java:159)
        at com.silkimen.cordovahttp.CordovaHttpBase.run(CordovaHttpBase.java:74)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: javax.net.ssl.SSLException: Read error: ssl=0x7321595188: I/O error during system call, Software caused connection abort
        at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
        at com.android.org.conscrypt.NativeSsl.read(NativeSsl.java:399)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(ConscryptFileDescriptorSocket.java:546)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.java:355)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:227)
        at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
        at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.huc.OkHttpURLConnection$NetworkInterceptor.intercept(OkHttpURLConnection.java:647)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.huc.OkHttpURLConnection$UnexpectedException$1.intercept(OkHttpURLConnection.java:582)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
        at okhttp3.RealCall.execute(RealCall.java:77)
        at okhttp3.internal.huc.OkHttpURLConnection.getResponse(OkHttpURLConnection.java:454)
        at okhttp3.internal.huc.OkHttpURLConnection.getResponseCode(OkHttpURLConnection.java:491)
        at okhttp3.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:106)
        at okhttp3.internal.huc.OkHttpsURLConnection.getResponseCode(OkHttpsURLConnection.java:26)
        at com.silkimen.http.HttpRequest.code(HttpRequest.java:1447)
        at com.silkimen.http.HttpRequest.stream(HttpRequest.java:1740) 
        at com.silkimen.http.HttpRequest.buffer(HttpRequest.java:1729) 
        at com.silkimen.http.HttpRequest.receive(HttpRequest.java:1856) 
        at com.silkimen.cordovahttp.CordovaHttpBase.processResponse(CordovaHttpBase.java:159) 
        at com.silkimen.cordovahttp.CordovaHttpBase.run(CordovaHttpBase.java:74) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
2019-06-12 13:34:26.735 619-640/ W/System: A resource failed to call close. 
2019-06-12 13:34:26.772 619-640/ W/System: A resource failed to call close. 


Please help us out with this issue :)

Thanks in advance!
