### ISSUE TITLE
Internal crash UnknownHostException

### ISSUE THREAD

**Issue by Khang-NT** [square/okhttp#4431]
What kind of issue is this?

 - [x] Question. This issue tracker is not the place for questions. If you want to ask how to do
       something, or to understand why something isn't working the way you expect it to, use Stack
       Overflow. https://stackoverflow.com/questions/tagged/okhttp

 - [x] Bug report. If you’ve found a bug, spend the time to write a failing test. Bugs with tests
       get fixed. Here’s an example: https://gist.github.com/swankjesse/981fcae102f513eb13ed

 - [ ] Feature Request. Start by telling us what problem you’re trying to solve. Often a solution
       already exists! Don’t send pull requests to implement new features without first getting our
       support. Sometimes we leave features out on purpose to keep the project small.

-----

I saw this crash in Crashlytics:
```
Fatal Exception: java.net.UnknownHostException: Unable to resolve host "authz-wifi.telecentro.net.ar": No address associated with hostname
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:95)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:74)
       at java.net.InetAddress.getAllByName(InetAddress.java:752)
       at okhttp3.Dns$1.lookup(SourceFile:40)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(SourceFile:185)
       at okhttp3.internal.connection.RouteSelector.nextProxy(SourceFile:149)
       at okhttp3.internal.connection.RouteSelector.next(SourceFile:84)
       at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile:214)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile:135)
       at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile:114)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
       at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile:126)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile:200)
       at okhttp3.RealCall$AsyncCall.execute(SourceFile:147)
       at okhttp3.internal.NamedRunnable.run(SourceFile:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:762)
```

Seem like this is OkHttp internal crash, isn't it?
OkHttp version: `3.11.0`
Android version: 7.x

**Comment by swankjesse** [comment]
Nope, that's expected. I assume you're probably not doing HTTPS and getting redirected by a WiFi gateway. You should use HTTPS.

**Comment by Khang-NT** [comment]
How possible to handle this error?
