### ISSUE TITLE
HeldCertificate.Builder().build() throws java.security.NoSuchAlgorithmException on Android if targetSdk is 28

### ISSUE THREAD

**Issue by geaden** [square/okhttp#4443]
okhttp version: 3.12
Testcase: https://gist.github.com/geaden/59da90b01e8419a09d2a9704989b0c77

If app targetSdk is 28 the test is failed with exception:

```bash
java.lang.SecurityException: exception: java.security.NoSuchAlgorithmException: The BC provider no longer provides an implementation for Signature.SHA256withECDSA.  Please see https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html for more details.
at org.bouncycastle.x509.X509V3CertificateGenerator.generateX509Certificate(Unknown Source:25)
at org.bouncycastle.x509.X509V3CertificateGenerator.generateX509Certificate(Unknown Source:3)
at okhttp3.tls.HeldCertificate$Builder.build(HeldCertificate.java:403)
```

If app targetSdk is lower then 28 it passes as described in androiddev blog post: https://android-developers.googleblog.com/2018/03/cryptography-changes-in-android-p.html 

>  For apps targeting an API level before P, the call will return the BC implementation and log a warning in the application log. For apps targeting Android P or later, the call will throw NoSuchAlgorithmException.

It seems [`org.bouncycastle.x509.X509V3CertificateGenerator`](https://github.com/bcgit/bc-java/blob/02b274e76895b6a1844d691c7c50a694b1d98d3c/prov/src/main/jdk1.1/org/bouncycastle/x509/X509V3CertificateGenerator.java#L40) is deprecated

**Comment by swankjesse** [comment]
@geaden can you check the fix above?

**Comment by geaden** [comment]
Hi @swankjesse! I did check `okhttp-tls` version from your branch and the test passed. Thanks!

**Comment by yschimke** [comment]
No, 3.12.X is not actively maintained.  So you will need to patch and build it yourself if this is blocking you.
