### ISSUE TITLE
The response not closed if this exceptions, I think

### ISSUE THREAD

**Issue by gMan1990** [square/okhttp#4447]
https://github.com/square/retrofit/issues/2990

**Comment by swankjesse** [comment]
Executable test case please.

**Comment by gMan1990** [comment]
@swankjesse mock a exception from "StackTrace" that  I commented with logging-interceptor-3.10.0, like:
https://github.com/square/okhttp/blob/c0739a419949a24d0c34cf38a25953c60871268b/okhttp-logging-interceptor/src/main/java/okhttp3/logging/HttpLoggingInterceptor.java#L241
```java
      if (!logBody || !HttpHeaders.hasBody(response)) {
        logger.log("<-- END HTTP");
      } else if (bodyHasUnknownEncoding(response.headers())) {
        logger.log("<-- END HTTP (encoded body omitted)");
      } else {
        BufferedSource source = responseBody.source();
        // mock here: 😀😀😀
        if("1".equals("1")) {
        // throw new java.io.EOFException();
        // throw new java.io.IOException("gzip finished without exhausting source");
        // throw new java.net.ProtocolException("Expected leading [0-9a-fA-F] character but was 0x48");
        // the var response/responseBody/source not closed.
        }
        source.request(Long.MAX_VALUE); // Buffer the entire body.
        Buffer buffer = source.buffer();
```
```java
    // test code
    HttpLoggingInterceptor httpLoggingInterceptor = new HttpLoggingInterceptor()
            .setLevel(HttpLoggingInterceptor.Level.BODY);
    OkHttpClient httpClient = new OkHttpClient.Builder().addInterceptor(httpLoggingInterceptor)
            .build();
    Request request = new Request.Builder().url("http://httpbin.org/get").build();
    try (Response response = httpClient.newCall(request).execute()) {
    } catch (IOException e) {
        throw new RuntimeException(e);
    }
```

**Comment by gMan1990** [comment]
just mock a exception to bug it

**Comment by yschimke** [comment]
@gMan1990 Ideally a bug report includes a test case written by the reporter that allows us to be sure we are fixing the same case.  Quite often descriptions of how to reproduce a bug are not complete enough to reproduce in a different environment.

Bug reports with test cases are much easier for any of the maintainers to pick up and fix and include as a regression test afterwards also.

**Comment by gMan1990** [comment]
@yschimke these exceptions are network exceptions, write a test case maybe a little difficult. Even if there is no test cases, this bug exists. you can find by code review at where I said

**Comment by metinavci** [comment]
Hello, I got this error. Is there any solution to this issue?

2019-01-08 11:36:19.789 [OkHttp http://10.20.15.15/...] ERROR - Received WS error
java.io.EOFException: null
	at okio.RealBufferedSource.require(RealBufferedSource.java:61) ~[okio-1.15.0.jar:?]
	at okio.RealBufferedSource.readByte(RealBufferedSource.java:74) ~[okio-1.15.0.jar:?]
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117) ~[okhttp-3.12.0.jar:?]
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101) ~[okhttp-3.12.0.jar:?]
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274) [okhttp-3.12.0.jar:?]
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214) [okhttp-3.12.0.jar:?]
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206) [okhttp-3.12.0.jar:?]
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.12.0.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
	at java.lang.Thread.run(Thread.java:844) [?:?]
