### ISSUE TITLE
HttpUrl host decode IPv6 address issue

### ISSUE THREAD

**Issue by Yphyllis** [square/okhttp#4451]
@Test
    public void test() {

        String host_ipv4 = "192.168.1.254";
        String host_ipv6 = "::ffff:c0a8:1fe";

        HttpUrl.Builder builder = new HttpUrl.Builder();
        builder.scheme("http");
        builder.host(host_ipv6);

        System.out.println(builder.build().toString());
    }

java.lang.AssertionError: Invalid IPv6 address: '::ffff:c0a8:1fe'

	at okhttp3.internal.Util.canonicalizeHost(Util.java:408)
	at okhttp3.HttpUrl$Builder.canonicalizeHost(HttpUrl.java:1592)
	at okhttp3.HttpUrl$Builder.host(HttpUrl.java:1026)
	at us.nonda.zus.TimestampTest.test(TimestampTest.java:22)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.intellij.rt.execution.application.AppMainV2.main(AppMainV2.java:131)

The network is right , I can request with IPv4 , but cant with IPv6,  please tell me how?

**Comment by swankjesse** [comment]
Ugh, OkHttp shouldn't fail like this. It should detect IPv4 mapped addresses and respond accordingly.

https://en.m.wikipedia.org/wiki/IPv6#IPv4-mapped_IPv6_addresses

**Comment by Yphyllis** [comment]
yeah, as you say,  "::ffff:c0a8:1fe" is a IPv4-mapped IPv6 addresses
but I'm confused, is OkHttp couldn't  request with IPv4-mapped IPv6 addresses ?
or I was in a incorrect way?

I also tried "::ffff:192.0.2.128"、"::192.0.2.128"、"0000:0000:0000:0000:0000:FFFF:C0A8:01FE"
they all throwed java.lang.AssertionError: Invalid IPv6 address

very thanks for you replay.

**Comment by swankjesse** [comment]
Because it's an IPv4 address OkHttp will only use IPv4 to connect to this host.

**Comment by Yphyllis** [comment]
oh, thanks very much
