### ISSUE TITLE
Attempt to invoke interface method 'java.net.SocketImpl java.net.SocketImplFactory.createSocketImpl()' on a null object reference

### ISSUE THREAD

**Issue by android-ext** [square/okhttp#4538]
Good bug reports include a failing test! Writing a test helps you to isolate and describe the problem, and it helps us to fix it fast. Bug reports without a failing test or reproduction steps are likely to be closed.

Here’s an example test to get you started.
https://gist.github.com/swankjesse/981fcae102f513eb13ed

java.lang.NullPointerException: Attempt to invoke interface method 'java.net.SocketImpl java.net.SocketImplFactory.createSocketImpl()' on a null object reference
at java.net.Socket.setImpl(Socket.java:525)
at java.net.Socket.<init>(Socket.java:86)
at javax.net.DefaultSocketFactory.createSocket(SocketFactory.java:273)
at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:216)
at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:147)
at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:192)
at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:121)
at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:100)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)

**Comment by android-ext** [comment]
okhttp version is 3.7.0

**Comment by swankjesse** [comment]
We can't do anything to help you without steps or a test to reproduce.
