### ISSUE TITLE
EOFException on websocket

### ISSUE THREAD

**Issue by metinavci** [square/okhttp#4543]
Hello, I got this error. Is there any solution to this issue?

2019-01-08 11:36:19.789 [OkHttp http://10.20.15.15/...] ERROR - Received WS error
java.io.EOFException: null
at okio.RealBufferedSource.require(RealBufferedSource.java:61) ~[okio-1.15.0.jar:?]
at okio.RealBufferedSource.readByte(RealBufferedSource.java:74) ~[okio-1.15.0.jar:?]
at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117) ~[okhttp-3.12.0.jar:?]
at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101) ~[okhttp-3.12.0.jar:?]
at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274) [okhttp-3.12.0.jar:?]
at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214) [okhttp-3.12.0.jar:?]
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206) [okhttp-3.12.0.jar:?]
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) [okhttp-3.12.0.jar:?]
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1135) [?:?]
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) [?:?]
at java.lang.Thread.run(Thread.java:844) [?:?]

**Comment by swankjesse** [comment]
I've seen you added this three times on three issues. One comment on one issue is enough.

Please provide steps to reproduce. Right now this just looks like a server that's hanging up.

**Comment by metinavci** [comment]
I removed the others. All good?

**Comment by swankjesse** [comment]
I'm looking for steps to reproduce your problem in particular.

**Comment by metinavci** [comment]
When the WebSocket is closing it gives that error There is no problem opening socket, sending or receiving a message.

**Comment by swankjesse** [comment]
Please provide steps to reproduce. Right now this just looks like a server that's hanging up.

**Comment by anidotnet** [comment]
@swankjesse I am also facing this issue. I didn't see this issue earlier, so I have commented on #3113 .

Now to reproduce this issue, please see this file - https://github.com/anidotnet/nitrite-java/blob/a88add6c6a/nitrite-replication/src/main/java/org/dizitart/no2/sync/Replica.java

The server is a tyrus server and is at - https://github.com/anidotnet/nitrite-java/blob/a88add6c6a/nitrite-replication/src/test/java/org/dizitart/no2/test/server/SimpleDataGateEndpoint.java and you can reproduce this issue if you run the junit test file - https://github.com/anidotnet/nitrite-java/blob/a88add6c6a/nitrite-replication/src/test/java/org/dizitart/no2/test/ReplicaTest.java

I am not sure if client is sending any ping message to the server, as I can't see any message at server end.

Sorry I could not give you an isolated project for it, I am working on this project and this issue pops up and I have not enough time to isolate it to a separate project. Sorry for the inconvenience.
