### ISSUE TITLE
SocketTimeoutException on cellular data connection    okHttp 2.7.5 + Retrofit 1.9.0

### ISSUE THREAD

**Issue by ashwinqb** [square/okhttp#4544]
D/CONNECTION_ISSUE: ERROR : java.net.SocketTimeoutException: timeout
D/CONNECTION_ISSUE: Message : timeout
D/CONNECTION_ISSUE: StackTrace : retrofit.RetrofitError: timeout
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:395)
        at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220)
        at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265)
        at retrofit.RxSupport$2.run(RxSupport.java:55)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
        at retrofit.Platform$Android$2$1.run(Platform.java:142)
        at java.lang.Thread.run(Thread.java:818)
     Caused by: java.net.SocketTimeoutException: timeout
        at com.squareup.okhttp.internal.framed.FramedStream$StreamTimeout.newTimeoutException(FramedStream.java:605)
        at com.squareup.okhttp.internal.framed.FramedStream$StreamTimeout.exitAndThrowIfTimedOut(FramedStream.java:613)
        at com.squareup.okhttp.internal.framed.FramedStream.getResponseHeaders(FramedStream.java:143)
        at com.squareup.okhttp.internal.http.Http2xStream.readResponseHeaders(Http2xStream.java:150)
        at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
        at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:87)
        at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:722)
        at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:576)
        at com.squareup.okhttp.Call.getResponse(Call.java:287)
        at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:243)
        at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:205)
        at com.squareup.okhttp.Call.execute(Call.java:80)
        at retrofit.client.OkClient.execute(OkClient.java:53)
        at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:326)
        at retrofit.RestAdapter$RestHandler.access$100(RestAdapter.java:220) 
        at retrofit.RestAdapter$RestHandler$1.invoke(RestAdapter.java:265) 
        at retrofit.RxSupport$2.run(RxSupport.java:55) 
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:237) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
        at retrofit.Platform$Android$2$1.run(Platform.java:142) 
        at java.lang.Thread.run(Thread.java:818) 

I tried increasing time out to 30 sec.
        client.setConnectTimeout(30, TimeUnit.SECONDS); // connect timeout
        client.setReadTimeout(30, TimeUnit.SECONDS);
        client.setWriteTimeout(30, TimeUnit.SECONDS);

Also tried adding 
        android:vmSafeMode="true"

**Comment by swankjesse** [comment]
Executable test case please.

**Comment by ashwinqb** [comment]
@swankjesse Please share your thoughts

**Comment by swankjesse** [comment]
You should upgrade to a recent OkHttp first. Then if you still have problems you should ask on StackOverflow.
