### ISSUE TITLE
javax.net.ssl.SSLException: Unable to create application data

### ISSUE THREAD

**Issue by jaydenyuhy** [square/okhttp#4546]
Caused by javax.net.ssl.SSLException: Unable to create application data
       at com.android.org.conscrypt.NativeCrypto.SSL_new(NativeCrypto.java)
       at com.android.org.conscrypt.SslWrapper.newInstance(SslWrapper.java:58)
       at com.android.org.conscrypt.ConscryptFileDescriptorSocket.newSsl(ConscryptFileDescriptorSocket.java:159)
       at com.android.org.conscrypt.ConscryptFileDescriptorSocket.(ConscryptFileDescriptorSocket.java:152)
       at com.android.org.conscrypt.OpenSSLSocketFactoryImpl.createSocket(OpenSSLSocketFactoryImpl.java:149)
       at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:308)
       at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)
       at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
       at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
       at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
       at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)

model:ONEPLUS A5000
android version:8.1
okhttp version:3.12.1

**Comment by swankjesse** [comment]
Not actionable by us. Executable test case, steps to reproduce, give us something to help us to fix this.

**Comment by chinacuizichao** [comment]
@jaydenyuhy did u fix it? i meet same bug

**Comment by reachzhai** [comment]
same bug +1

**Comment by yschimke** [comment]
You can raise with the conscrypt project. Or stackoverflow. But there are also similar reports. It’s likely a handshake failure or simple resource limit problem in native code. But not really for me to guess.

**Comment by Shaooooo** [comment]
解决了吗？

**Comment by mayurpatil307** [comment]
Facing the same issue. bug +1

**Comment by shinebar** [comment]
oh my god,I have meet this same bug. Who did solve this problem? thanks.

**Comment by purvesh-d** [comment]
Facing same issue

**Comment by DaphnevdVeeke** [comment]
Same

**Comment by ugurdundar34** [comment]
same

**Comment by chenyunecjtu** [comment]
same

**Comment by RongzhiLiu** [comment]
oh my god,I have meet this same bug. Who did solve this problem? thanks.

**Comment by shinebar** [comment]
> oh my god,I have meet this same bug. Who did solve this problem? thanks.

you can try extend the number of FD(file description)  in your device.   you should  solve this problem. Now I don't meet this bug.
