### ISSUE TITLE
RequestBody- Multipart (contentType) NullPointerException

### ISSUE THREAD

**Issue by enriquebautista** [square/okhttp#4552]
Help!. "com.squareup.okhttp3:okhttp:3.12.1"

```
public static String signUp(Context context,
                                int registerType,
                                String name,
                                String email,
                                int gender,
                                String birthdate,
                                String imagePath,
                                String password,
                                long countryId,
                                long stateId,
                                long cityId,
                                int reasonId,
                                String facebookId,
                                String googleId) throws IOException {
        final String firebaseToken = Prefs.get(context).getFirebaseToken();
        MultipartBody.Builder builder = new MultipartBody.Builder()
                .setType(MultipartBody.FORM)
                .addFormDataPart("name", name)
                .addFormDataPart("email", email)
                .addFormDataPart("country", String.valueOf(countryId))
                .addFormDataPart("state", String.valueOf(stateId))
                .addFormDataPart("city", String.valueOf(cityId))
                .addFormDataPart("os", "2")
                .addFormDataPart("register_type", String.valueOf(registerType))
                .addFormDataPart("id_device", firebaseToken);
        if(imagePath != null && imagePath.length() > 0) {
            builder.addFormDataPart("image_profile", "avatar.png",
                    RequestBody.create(MEDIA_TYPE_PNG, new File(imagePath)));
        }
        if(birthdate != null && birthdate.length() > 0) {
            builder.addFormDataPart("birthdate", birthdate);
        }
        if(gender != 0) {
            builder.addFormDataPart("gender", String.valueOf(gender));
        }
        if(reasonId != 0) {
            builder.addFormDataPart("reason", String.valueOf(reasonId));
        }
        if(registerType == 1) {
            builder.addFormDataPart("password", password);
        } else if(registerType == 2) {
            builder.addFormDataPart("idFacebook", facebookId);
        } else if(registerType == 3) {
            builder.addFormDataPart("idGoogle", googleId);
        }
        return performPostCall(null, fullUrl(URL_API_REGISTER), builder.build());
    }
```

Crashlytics Log:
```
Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'byte[] java.lang.String.getBytes(java.nio.charset.Charset)' on a null object reference
       at okhttp3.RequestBody.contentType(Unknown Source)
       at okhttp3.MultipartBody$Part.create(Unknown Source)
       at okhttp3.MultipartBody$Builder.setType(Unknown Source)
       at com.turismonl.pasaportenle.data.api.ApiHelper.getTermsAndConditions(Unknown Source)
       at com.turismonl.pasaportenle.data.loader.SignupLoader.loadData(Unknown Source)
       at com.turismonl.pasaportenle.data.loader.BaseLoader.loadInBackground(Unknown Source)
       at com.turismonl.pasaportenle.data.loader.BaseLoader.loadInBackground(Unknown Source)
       at android.support.v4.content.AsyncTaskLoader.onLoadInBackground(Unknown Source)
       at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(Unknown Source)
       at android.support.v4.content.AsyncTaskLoader$LoadTask.doInBackground(Unknown Source)
       at android.support.v4.content.ModernAsyncTask$2.call(Unknown Source)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
       at java.lang.Thread.run(Thread.java:818)
```

**Comment by MONIKA-KUMAR-JETHANI** [comment]
Hi @enriquebautista, Is this issue still open?
