### ISSUE TITLE
SocketTimeoutException after I change WIFI without proxy

### ISSUE THREAD

**Issue by hansionit** [square/okhttp#4563]
okhttp:3.9.0  and  okhttp:3.12.1 

steps:
1.Connection Fiddler and set proxy on WIFi Setting (172.30.161.185:8888)
2.Start My APP,do some request by okhttp,Now that the request fails, I can accept it
3.But Do not quit APP,change WIFI to which WIFI without Proxy.
4.request by okhttp is socket timeout all time.

I found a solution.

OkHttpClient.Builder builder = new OkHttpClient.Builder();
builder.proxy(Proxy.NO_PROXY)
if I set Proxy.NO_PROXY,it's ok

But it's not a good way. I think it's a bug and I should fix it.

I guess RouteSelector -> resetNextProxy -> address.proxySelector().select(url.uri())  caused it. it return invalid proxy(HTTP @ 172.30.161.185:8888) but not DIRECT.

some logs:

    01-17 11:00:37.537 31892-32423/com.hansion.app W/System.err: java.net.SocketTimeoutException: timeout
    01-17 11:00:37.538 31892-32423/com.hansion.app W/System.err:     at okio.SocketAsyncTimeout.newTimeoutException(Okio.kt:159)
            01-17 11:00:37.539 31892-32423/com.hansion.app W/System.err:     at okio.AsyncTimeout.exit$jvm(AsyncTimeout.kt:203)
            01-17 11:00:37.539 31892-32423/com.hansion.app W/System.err:     at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:163)
            01-17 11:00:37.539 31892-32423/com.hansion.app W/System.err:     at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:349)
            01-17 11:00:37.539 31892-32423/com.hansion.app W/System.err:     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:222)
            01-17 11:00:37.539 31892-32423/com.hansion.app W/System.err:     at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
            01-17 11:00:37.540 31892-32423/com.hansion.app W/System.err:     at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
            01-17 11:00:37.540 31892-32423/com.hansion.app W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
            01-17 11:00:37.542 31892-32423/com.hansion.app W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
            01-17 11:00:37.542 31892-32423/com.hansion.app W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
            01-17 11:00:37.542 31892-32423/com.hansion.app W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
            01-17 11:00:37.543 31892-32423/com.hansion.app W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
            01-17 11:00:37.543 31892-32423/com.hansion.app W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
            01-17 11:00:37.543 31892-32423/com.hansion.app W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
            01-17 11:00:37.543 31892-32423/com.hansion.app W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
            01-17 11:00:37.543 31892-32423/com.hansion.app W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
            01-17 11:00:37.543 31892-32423/com.hansion.app W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
            01-17 11:00:37.544 31892-32423/com.hansion.app W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
            01-17 11:00:37.544 31892-32423/com.hansion.app W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
            01-17 11:00:37.544 31892-32423/com.hansion.app W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
            01-17 11:00:37.544 31892-32423/com.hansion.app W/System.err:     at com.networkbench.agent.impl.i.b.intercept(SourceFile:69)
            01-17 11:00:37.544 31892-32423/com.hansion.app W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
            01-17 11:00:37.544 31892-32423/com.hansion.app W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
            01-17 11:00:37.544 31892-32423/com.hansion.app W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
            01-17 11:00:37.544 31892-32423/com.hansion.app W/System.err:     at okhttp3.RealCall.execute(RealCall.java:92)
            01-17 11:00:37.544 31892-32423/com.hansion.app W/System.err:     at com.networkbench.agent.impl.i.c.execute(SourceFile:39)
            01-17 11:00:37.545 31892-32423/com.hansion.app W/System.err:     at com.hansion.app.util.download.core.DownLoadTask.writeFileFromRequest(DownLoadTask.java:279)
            01-17 11:00:37.545 31892-32423/com.hansion.app W/System.err:     at com.hansion.app.util.download.core.DownLoadTask.run(DownLoadTask.java:212)
            01-17 11:00:37.545 31892-32423/com.hansion.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
            01-17 11:00:37.545 31892-32423/com.hansion.app W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
            01-17 11:00:37.546 31892-32423/com.hansion.app W/System.err:     at java.lang.Thread.run(Thread.java:761)
            01-17 11:00:37.547 31892-32423/com.hansion.app W/System.err: Caused by: java.net.SocketException: Socket closed
    01-17 11:00:37.547 31892-32423/com.hansion.app W/System.err:     at java.net.SocketInputStream.socketRead0(Native Method)
            01-17 11:00:37.548 31892-32423/com.hansion.app W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:151)
            01-17 11:00:37.548 31892-32423/com.hansion.app W/System.err:     at java.net.SocketInputStream.read(SocketInputStream.java:120)
            01-17 11:00:37.548 31892-32423/com.hansion.app W/System.err:     at okio.InputStreamSource.read(Okio.kt:102)
            01-17 11:00:37.548 31892-32423/com.hansion.app W/System.err:     at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:159)
            01-17 11:00:37.548 31892-32423/com.hansion.app W/System.err: 	... 28 more

**Comment by hansionit** [comment]
no problem
