### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException:Null interceptorFatal Exception: java.lang.IllegalStateException:Null interceptor

### ISSUE THREAD

**Issue by android-ext** [square/okhttp#4579]
Fatal Exception: java.lang.IllegalStateException:Null interceptor: [null, com.xxx.inspectionsign.LJISHeaderInterceptor@5151e9d]
at okhttp3.OkHttpClient.<init>(OkHttpClient.java:283)
at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1040)
at com.xxx.LJTSSampleApi.init(LJTSSampleApi.java:91)
at com.xxx.sample.LJTSSampleApi.fetchSampleInfo(LJTSSampleApi.java:105)
at com.xxx.sample.LJTSSampleManager.fetchSampleNetStatsInfo(LJTSSampleManager.java:197)
at com.xxx.sample.LJTSSampleManager.getCacheSampleNetStatsInfo(LJTSSampleManager.java:113)
at com.xxx.sample.LJTSSampleManager.shouldIntercept(LJTSSampleManager.java:126)
at com.xxx.trafficstats.LJTrafficStats.handleNetResponse(LJTrafficStats.java:165)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:776)

**Comment by SaeedJinat** [comment]
could you please attach the code snippet that crashed ? or the snippet of the method calls ?

**Comment by XiaoDuZi** [comment]
How to solve this problem? @swankjesse

**Comment by swankjesse** [comment]
Please ask on StackOverflow.
