### ISSUE TITLE
Tests fail on Java 1.8 v202

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#4588]
We’re testing that obsolete TLS things don’t work and the new JDKs won’t even let us do that.

```
java.lang.AssertionError: No appropriate protocol (protocol is disabled or cipher suites are inappropriate)
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at okhttp3.RecordedResponse.assertFailure(RecordedResponse.java:162)
	at okhttp3.CallTest.tlsHostnameVerificationFailureNoPeerCertificates(CallTest.java:1272)
```

**Comment by valepakh** [comment]
There are more tests fail on this Java version in the 3.12.x branch as well, see build https://travis-ci.org/square/okhttp/builds/493730185 from the PR #4618 
Looking at the changelog, it's probably [JDK-8211883 : Disable anon and NULL cipher suites](https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8211883)
