### ISSUE TITLE
Error on retrofit when add dependencies of okhttp

### ISSUE THREAD

**Issue by dennykurniawan48** [square/okhttp#4622]
Hello, when I am using Retrofit without Okhttp dependencies, its working fine, but when I want to add okhttp for logging to my dependencies.
It show error in my logcat:
``` E/AndroidRuntime: FATAL 
EXCEPTION: main
    Process: com.myapp., PID: 2687
    java.lang.ExceptionInInitializerError
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:296)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:262)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:235)
        at retrofit2.Retrofit$Builder.build(Retrofit.java:580)
        at com.myapp..fragment.LoginFragment.onCreate(LoginFragment.java:73)
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2414)
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418)
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195)
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078)
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117)
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408)
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366)
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273)
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273)
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229)
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201)
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620)
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178)
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1188)
        at android.app.Activity.performStart(Activity.java:5241)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2166)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2243)
        at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5019)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 19
        at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:238)
        at okhttp3.internal.platform.Platform.findPlatform(Platform.java:202)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:296) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:262) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:235) 
        at retrofit2.Retrofit$Builder.build(Retrofit.java:580) 
        at com.myapp.fragment.LoginFragment.onCreate(LoginFragment.java:73) 
        at android.support.v4.app.Fragment.performCreate(Fragment.java:2414) 
        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1418) 
        at android.support.v4.app.FragmentTransition.addToFirstInLastOut(FragmentTransition.java:1195) 
        at android.support.v4.app.FragmentTransition.calculateFragments(FragmentTransition.java:1078) 
        at android.support.v4.app.FragmentTransition.startTransitions(FragmentTransition.java:117) 
        at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(FragmentManager.java:2408) 
        at android.support.v4.app.FragmentManagerImpl.removeRedundantOperationsAndExecute(FragmentManager.java:2366) 
        at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:2273) 
        at android.support.v4.app.FragmentManagerImpl.dispatchStateChange(FragmentManager.java:3273) 
        at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:3229) 
        at android.support.v4.app.FragmentController.dispatchActivityCreated(FragmentController.java:201) 
        at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:620) 
        at android.support.v7.app.AppCompatActivity.onStart(AppCompatActivity.java:178) 
        at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1188) 
        at android.app.Activity.performStart(Activity.java:5241) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2166) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2243) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5019) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method) 
```
No problem when I using retrofit only

**Comment by JakeWharton** [comment]
OkHttp 3.13 requires Java 8. You need to enable it in your build configuration. See: https://github.com/square/okhttp/issues/4597#issuecomment-461204144

**Comment by dennykurniawan48** [comment]
Thanks for your reply sir, I have added this
```
 compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
```
to my build gradle file,but I still have same error output. Is there any additional step for this?

**Comment by JakeWharton** [comment]
You put that at the top-level or inside the Android block?

**Comment by dennykurniawan48** [comment]
I put inside android block sir, if i put it outside there Gradle error.

**Comment by rockfirm** [comment]
okhttp above 3.13 has a problem with Android4.4（ about ssl ）, so use 3.12.1( or under) prevent this problem.

**Comment by pdapnz** [comment]
Same problem. 

This is because: 

> OkHttp works on Android 5.0+ (API level 21+) and on Java 8+.

https://medium.com/square-corner-blog/okhttp-3-13-requires-android-5-818bb78d07ce

The only way is use  OkHttp 3.12.x if your minSDK lower 21.

**Comment by jenmo917** [comment]
+1

**Comment by DDihanov** [comment]
If you guys are still crashing on Android 4 using the latest `2.7.1` Retrofit version, after setting the source and target compability version to 1.8 force the old OkHttp version like this, and it should work:
```
implementation("com.squareup.retrofit2:retrofit:2.7.1")

implementation("com.squareup.okhttp3:okhttp:3.12.8") {
    force = true
}

implementation "com.squareup.okhttp3:logging-interceptor:3.12.8"
```

**Comment by doctor-henry** [comment]
Just downgrade Retrofit to `2.7.0`. The problem will go away.

**Comment by tas-wtag** [comment]
> If you guys are still crashing on Android 4 using the latest `2.7.1` Retrofit version, after setting the source and target compability version to 1.8 force the old OkHttp version like this, and it should work:
> 
> ```
> implementation("com.squareup.retrofit2:retrofit:2.7.1")
> 
> implementation("com.squareup.okhttp3:okhttp:3.12.8") {
>     force = true
> }
> 
> implementation "com.squareup.okhttp3:logging-interceptor:3.12.8"
> ```

Thank you so so much!

**Comment by gilberty227** [comment]
Update version OK-Https 

implementation ("com.squareup.okhttp3:okhttp:4.9.0")
