### ISSUE TITLE
InterceptorTest.connectTimeout fails when wifi disabled

### ISSUE THREAD

**Issue by galderz** [square/okhttp#4682]
`InterceptorTest.connectTimeout` fails when WIFI is disabled on my laptop.

```
INFO: MockWebServer[64062] starting to accept connections
Mar 04, 2019 8:18:54 PM okhttp3.mockwebserver.MockWebServer$3 acceptConnections
INFO: MockWebServer[64062] done accepting connections: Socket closed

java.net.ConnectException: Operation timed out (Connection timed out)
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:204)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at okhttp3.InterceptorTest.connectTimeout(InterceptorTest.java:693)
```

I can look into it

**Comment by galderz** [comment]
PR(#4693) sent

**Comment by yschimke** [comment]
Seems fixed
