### ISSUE TITLE
LoggingEventListenerTest.secureGet failing with incorrect cipher suite

### ISSUE THREAD

**Issue by galderz** [square/okhttp#4685]
`LoggingEventListenerTest.secureGet` failing on `jdk1.8.0_144` with:

```
java.lang.AssertionError: 
<[382 ms] secureConnectEnd: Handshake{tlsVersion=TLS_1_2 cipherSuite=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256 peerCertificates=[CN=localhost] localCertificates=[]}>
did not match pattern
<\[\d+ ms] secureConnectEnd: Handshake\{tlsVersion=TLS_1_[23] cipherSuite=(?:TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384|TLS_AES_128_GCM_SHA256) peerCertificates=\[CN=localhost\] localCertificates=\[\]}>

	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.assertTrue(Assert.java:41)
	at okhttp3.logging.HttpLoggingInterceptorTest$LogRecorder.assertLogMatch(HttpLoggingInterceptorTest.java:861)
	at okhttp3.logging.LoggingEventListenerTest$LogRecorder.assertLogMatch(LoggingEventListenerTest.java:224)
	at okhttp3.logging.LoggingEventListenerTest.secureGet(LoggingEventListenerTest.java:148)
```

**Comment by galderz** [comment]
PR: https://github.com/square/okhttp/pull/4686
