### ISSUE TITLE
SocketTimeoutException when using Http2

### ISSUE THREAD

**Issue by SwordBearer** [square/okhttp#4694]
OkHttp Version : okhttp/3.12.1
Http protocol : h2

Here is the request log:
![image](https://user-images.githubusercontent.com/1811579/54020768-8a895a00-41c9-11e9-98b9-3cef1953a641.png)

I got this Excpeption:

LoggingEventListener: [10061 ms] connectionReleased
2019-03-08 17:41:04.904 27183-27248/com.immomo.momo.dev D/LoggingEventListener: [10061 ms] callEnd
2019-03-08 17:41:04.905 27183-27248/com.immomo.momo.dev D/LoggingEventListener: [10061 ms] callFailed: java.net.SocketTimeoutException: timeout
2019-03-08 17:41:04.905 27183-27248/com.immomo.momo.dev W/System.err: java.net.SocketTimeoutException: timeout
2019-03-08 17:41:04.905 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:656)
2019-03-08 17:41:04.905 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.java:664)
2019-03-08 17:41:04.906 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.java:153)
2019-03-08 17:41:04.906 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.internal.http2.Http2Codec.readResponseHeaders(Http2Codec.java:131)
2019-03-08 17:41:04.906 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:61)
2019-03-08 17:41:04.906 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-03-08 17:41:04.906 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
2019-03-08 17:41:04.906 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-03-08 17:41:04.906 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-03-08 17:41:04.906 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
2019-03-08 17:41:04.906 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-03-08 17:41:04.906 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-03-08 17:41:04.906 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2019-03-08 17:41:04.906 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-03-08 17:41:04.906 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
2019-03-08 17:41:04.906 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
2019-03-08 17:41:04.906 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
2019-03-08 17:41:04.906 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
2019-03-08 17:41:04.906 27183-27248/com.immomo.momo.dev W/System.err:     at okhttp3.RealCall.execute(RealCall.java:92)

But when i force use Protocol.HTTP_1_1 , every request is ok, how can I fix this problem , thanks 👍

**Comment by SwordBearer** [comment]
sorry for this issue, i make wrong http header

**Comment by 1030310877** [comment]
Hi guy, I got the same error from users, and it took 50% in all timeout error. However, I can't re-produce the bug. If it was caused by the wrong http header, I want to know the reason that which header could cause this error.
