### ISSUE TITLE
WebSocketHttpTest.missingConnectionHeader failing randomly

### ISSUE THREAD

**Issue by galderz** [square/okhttp#4695]
I've just seen this fail locally with latest master (which includes fix for #4658)

```
[ERROR] Tests run: 40, Failures: 1, Errors: 0, Skipped: 1, Time elapsed: 8.026 s <<< FAILURE! - in okhttp3.internal.ws.WebSocketHttpTest
[ERROR] missingConnectionHeader(okhttp3.internal.ws.WebSocketHttpTest)  Time elapsed: 0.013 s  <<< FAILURE!
java.lang.AssertionError: expected:<0> but was:<1>
	at okhttp3.internal.ws.WebSocketHttpTest.missingConnectionHeader(WebSocketHttpTest.java:309)
```

FINE logs of testsuite [here](https://www.dropbox.com/s/sbb21spbn43j69y/okhttp-missingConnectionHeader.tgz?dl=0).

**Comment by galderz** [comment]
The stacktrace is a little odd, but managed to get it failing quite quickly via IDE:

```
java.lang.AssertionError: 
Expected :0
Actual   :1
	at org.junit.Assert.fail(Assert.java:88)
	at org.junit.Assert.failNotEquals(Assert.java:834)
	at org.junit.Assert.assertEquals(Assert.java:645)
	at org.junit.Assert.assertEquals(Assert.java:631)
	at okhttp3.TestUtil.ensureAllConnectionsReleased(TestUtil.java:91)
	at okhttp3.internal.ws.WebSocketHttpTest.missingConnectionHeader(WebSocketHttpTest.java:309)
```

Looking into it

**Comment by galderz** [comment]
It appears the queued websocket call as result of websocket.connect() is sometimes not consumed by the time the pool is evicted, hence the connection sticks around. Looking into how to guarantee that the call is consumed.

**Comment by galderz** [comment]
Correction: the call is consumed (since client listener asserts failure), but the transmitter associated with the connection has not been removed by the time evictAll is called.

**Comment by galderz** [comment]
`exchange.webSocketUpgradeFailed()` call is what triggers transmitters to be removed, so I've moved that up before calling `failWebSocket` and `closeQuietly` and that might do the trick?

**Comment by galderz** [comment]
PR (#4696)
