### ISSUE TITLE
IllegalStateException: closed

### ISSUE THREAD

**Issue by wuhao-ouyang** [square/okhttp#4722]
We have faced this issue for certain users. And we know it can be reproduced under certain environment, since it will block these users constantly while it happens. But our developers cannot reproduce this issue.
Just want to see if anyone has insights about it
```
okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:445)
okio.RealBufferedSource.readAll(RealBufferedSource.java:173)
retrofit2.Utils.buffer(Utils.java:303)
retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:198)
retrofit2.OkHttpCall.execute(OkHttpCall.java:174)
retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:41)
io.reactivex.Observable.subscribe(Observable.java:10910)
retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
io.reactivex.Observable.subscribe(Observable.java:10910)
io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:33)
io.reactivex.Observable.subscribe(Observable.java:10910)
io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:452)
io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
java.util.concurrent.FutureTask.run(FutureTask.java:266)
java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
java.lang.Thread.run(Thread.java:764)
```

**Comment by swankjesse** [comment]
Got any interesting interceptors?

**Comment by PaulWoitaschek** [comment]
Same here. My interceptors don't do sth too fancy.

# Stacktrace
```
java.lang.IllegalStateException: closed
       at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.java:284)
       at okio.RealBufferedSource.readAll(RealBufferedSource.java:176)
       at retrofit2.Utils.buffer(Utils.java:322)
       at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:209)
       at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
       at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
       at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

# Interceptors
```kotlin
class ErrorDelegatingInterceptor @Inject constructor(
  private val backendErrorReceived: BackendErrorReceived
) : Interceptor {

  override fun intercept(chain: Interceptor.Chain): Response {
    val response = chain.proceed(chain.request())
    if (response.code() == 503) {
      backendErrorReceived.backendUnavailable()
    }
    return response
  }
}
```

```kotlin
class AttachRequestInfoToIOExceptionInterceptor @Inject constructor() : Interceptor {

  override fun intercept(chain: Interceptor.Chain): Response {
    val request = chain.request()
    return try {
      chain.proceed(request)
    } catch (ioException: IOException) {
      throw IOException(request.toString(), ioException)
    }
  }
}
```

```kotlin
@Reusable
class UserAgentInterceptor
@Inject constructor(appInfo: AppInfo) : Interceptor {

  private val userAgent = "y.android,v=${appInfo.versionCode},n=${appInfo.versionName}"

  override fun intercept(chain: Interceptor.Chain): Response {
    val requestWithHeader = chain.request().newBuilder()
      .header("User-Agent", userAgent)
      .build()
    return chain.proceed(requestWithHeader)
  }
}
```

```kotlin
@Singleton
class OAuth @Inject constructor(
  @Named(PrefKey.TOKEN)
  tokenPref: OptionalPref<Token>,
  private val logoutManager: Lazy<LogoutManager>
) : Interceptor {

  private var token by tokenPref

  @Synchronized
  override fun intercept(chain: Interceptor.Chain): Response {
    val modifiedRequest = runBlocking { attachToken(chain.request()) }
    return chain.proceed(modifiedRequest)
  }

  private suspend fun attachToken(oldRequest: Request): Request {
    val token = token
    if (token == null) {
      Timber.e("token is null. Logout and throw")
      logoutManager.get().logout()
      throw IOException("No token")
    }

    return attach(oldRequest, token)
  }

  private fun attach(request: Request, token: Token): Request {
    val builder = request.newBuilder()
      .header("Authorization", token.authHeader())
    return builder.build()
  }
}
```

**Comment by marilion** [comment]
We were experiencing da similar issue today during a 3 minute network outage.

```
okhttp3.internal.connection.Transmitter.prepareToConnect (Transmitter.java:129)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.java:79)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
...$AuthInterceptor.intercept (HttpClient.java:94)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
...$userAgentInterceptor$1.intercept (HttpClient.java:121)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
...$retryThreeHoursStaleInterceptor$1.intercept (HttpClient.java:62)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:142)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.java:117)
okhttp3.RealCall.getResponseWithInterceptorChain (RealCall.java:221)
okhttp3.RealCall$AsyncCall.execute (RealCall.java:172)
okhttp3.internal.NamedRunnable.run (NamedRunnable.java:32)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1162)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:636)
java.lang.Thread.run (Thread.java:764)
```

for me, the main issue is, that the exception in this callstack is not properly handled by okhttp which causes the whole thread and with the thread the whole application to crash.

**Comment by swankjesse** [comment]
@marilion looks like you’ve got an unrelated stacktrace. Can you open a new bug, ideally with an executable test case?

Everyone else – executable test cases will help to fix this!

**Comment by PaulWoitaschek** [comment]
If I could have a simple reproducer I would have posted it already, I only see this in crash reports.

Maybe noteworthy: I'm using the rxjava calladapter in async mode:
`.addCallAdapterFactory(RxJava2CallAdapterFactory.createAsync())`

Do others with this crash do the same?

**Comment by PaulWoitaschek** [comment]
Okay I disabled the `createAsync` and I still have the crash. Is there anything I can do to help find the cause of the issue? This is my crash number 1 with about 1000 crashing users each day.

There seem to be no pixel devices involved, maybe this is manufactor specific?
<img width="658" alt="grafik" src="https://user-images.githubusercontent.com/743462/58374145-3a54a500-7f39-11e9-96d7-c9569a71e60a.png">

**Comment by marilion** [comment]
Fyi, we fixed our issue with closing the old response in one of our interceptors bevor starting the new one, maybe the same problem here in the OAuth Interceptor?

**Comment by wuhao-ouyang** [comment]
It is related to the OAuth interceptor trying to parse the error message.
Thanks for all the replies.
