### ISSUE TITLE
[3.13.1] Program type already present: okhttp3.EventListener$Factory

### ISSUE THREAD

**Issue by gubatron** [square/okhttp#4724]
To replicate I went from `okhttp 3.12.1`-> `3.13.1`

`implementation 'com.squareup.okhttp3:okhttp:3.13.1'`

on a multidex project, now when I try to build:

```
AGPBI: {"kind":"error","text":"Program type already present: okhttp3.EventListener$Factory","sources":[{}],"tool":"D8"}
> Task :transformDexArchiveWithDexMergerForBasicDebug FAILED
java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/0, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/1, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/2, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/3, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/4, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/5, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/6, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/7, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/8, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/9, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/10, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/11, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/12, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/13, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/14, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/15, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/16, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/17, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/18, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/19, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/20, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/21, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/22, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/23, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/24, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/25, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/26, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/27, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/28, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/29, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/30, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/31, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/32, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/33, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/34, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/35, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/36, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/37, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/38, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/39, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/40, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/41, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/42, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/43, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/44, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/45, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/46, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/47, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/48, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/49, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/50, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/51, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/52, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/53, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/54, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/55, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/56, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/57, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/58, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/59, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/60, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/61, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/62, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/63, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/64, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/65, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/66, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/67, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/68, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/69, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/70, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/71
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: okhttp3.EventListener$Factory
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.util.concurrent.ForkJoinTask.getThrowableException(ForkJoinTask.java:593)
	at java.util.concurrent.ForkJoinTask.reportException(ForkJoinTask.java:677)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:720)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:406)
	at com.android.build.gradle.internal.transforms.DexMergerTransform.transform(DexMergerTransform.java:233)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:239)
	at com.android.build.gradle.internal.pipeline.TransformTask$2.call(TransformTask.java:235)
	at com.android.builder.profile.ThreadRecorder.record(ThreadRecorder.java:102)
	at com.android.build.gradle.internal.pipeline.TransformTask.transform(TransformTask.java:230)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.IncrementalTaskAction.doExecute(IncrementalTaskAction.java:50)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
	at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
	at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
	at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
	at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
	at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
	at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
	at java.lang.Thread.run(Thread.java:745)
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: okhttp3.EventListener$Factory
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1431)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
Program type already present: okhttp3.EventListener$Factory
	at com.android.builder.dexing.D8DexArchiveMerger.getExceptionToRethrow(D8DexArchiveMerger.java:132)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:117)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:101)
	at com.android.build.gradle.internal.transforms.DexMergerTransformCallable.call(DexMergerTransformCallable.java:36)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	... 4 more
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:65)
	at com.android.tools.r8.utils.ExceptionUtils.withD8CompilationHandler(ExceptionUtils.java:43)
	at com.android.tools.r8.D8.run(D8.java:90)
	at com.android.builder.dexing.D8DexArchiveMerger.mergeDexArchives(D8DexArchiveMerger.java:115)
	... 7 more
	at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:116)
	at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:74)
	at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:59)
	... 10 more
FAILURE: Build failed with an exception.
* What went wrong:
Execution failed for task ':transformDexArchiveWithDexMergerForBasicDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/0, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/1, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/2, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/3, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/4, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/5, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/6, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/7, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/8, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/9, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/10, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/11, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/12, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/13, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/14, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/15, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/16, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/17, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/18, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/19, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/20, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/21, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/22, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/23, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/24, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/25, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/26, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/27, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/28, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/29, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/30, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/31, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/32, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/33, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/34, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/35, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/36, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/37, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/38, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/39, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/40, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/41, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/42, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/43, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/44, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/45, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/46, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/47, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/48, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/49, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/50, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/51, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/52, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/53, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/54, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/55, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/56, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/57, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/58, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/59, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/60, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/61, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/62, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/63, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/64, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/65, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/66, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/67, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/68, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/69, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/70, /Users/gubatron/workspace.frostwire/frostwire/android/build/intermediates/transforms/dexBuilder/basic/debug/71
  Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
  Program type already present: okhttp3.EventListener$Factory
```

**Comment by swankjesse** [comment]
Not clear what action we can take here. Seems like you’ve got duplicate classes.

**Comment by gubatron** [comment]
after applying an Android SDK platform tools update this morning the problem went away.

Thanks @swankjesse

 
![Screen Shot 2019-03-18 at 11 03 27 AM](https://user-images.githubusercontent.com/163977/54548441-8ac5ea00-496d-11e9-95c5-77c1ea2dd1bc.png)
