### ISSUE TITLE
Can’t create invalid certificate chains on Java 11

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#4729]
We create invalid certificate chains in tests for MockWebServer to confirm that OkHttp refuses to accept them.

But in Java 11, we get an exception creating invalid certificate chains through the standard APIs:
```
java.security.KeyStoreException: Key protection  algorithm not found: java.security.KeyStoreException: Certificate chain is not valid

	at java.base/sun.security.pkcs12.PKCS12KeyStore.setKeyEntry(PKCS12KeyStore.java:704)
	at java.base/sun.security.pkcs12.PKCS12KeyStore.engineSetKeyEntry(PKCS12KeyStore.java:601)
	at java.base/sun.security.util.KeyStoreDelegator.engineSetKeyEntry(KeyStoreDelegator.java:111)
	at java.base/java.security.KeyStore.setKeyEntry(KeyStore.java:1174)
	at okhttp3.tls.internal.TlsUtil.newKeyManager(TlsUtil.java:95)
	at okhttp3.internal.tls.CertificatePinnerChainValidationTest.newServerSocketFactory(CertificatePinnerChainValidationTest.java:344)
	at okhttp3.internal.tls.CertificatePinnerChainValidationTest.unrelatedPinnedLeafCertificateInChain(CertificatePinnerChainValidationTest.java:233)
```

**Comment by yschimke** [comment]
Should we prebuild the certs and checkin?

**Comment by swankjesse** [comment]
Great idea. I'd love to add APIs to HeldCertificate to encode and decode so this doesn't feel one-off.

The manual decoding for this gist was unpleasant.

https://gist.github.com/swankjesse/589e3e1c4a566e4a9aaec66f0f3a6223

**Comment by yschimke** [comment]
Won't fix.  We should stick with happy path for any APIs.
