### ISSUE TITLE
BLOCKED  and eat cpu

### ISSUE THREAD

**Issue by dongdongyang** [square/okhttp#4810]
ttp-nio-8081-exec-8" Id=51 cpuUsage=1% BLOCKED on okhttp3.internal.connection.RealConnectionPool@7a5b3b68 owned by "http-nio-8081-exec-64" Id=256
    at okhttp3.internal.connection.Transmitter.isCanceled(Transmitter.java:342)
    -  blocked on okhttp3.internal.connection.RealConnectionPool@7a5b3b68
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:222)
    at okhttp3.RealCall.execute(RealCall.java:81)

"http-nio-8081-exec-116" Id=354 cpuUsage=2% RUNNABLE
    at java.net.SocketInputStream.socketRead0(Native Method)
    at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
    at java.net.SocketInputStream.read(SocketInputStream.java:170)
    at java.net.SocketInputStream.read(SocketInputStream.java:141)
    at okio.Okio$2.read(Okio.java:140)
    at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
    at okio.RealBufferedSource.indexOf(RealBufferedSource.java:358)
    at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:230)
    at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.java:238)
    at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.java:213)
    at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.java:115)
    at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:94)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
    at okhttp3.RealCall.execute(RealCall.java:81)

**Comment by swankjesse** [comment]
Executable test case?

**Comment by dongdongyang** [comment]
> Executable test case?

pressure test

**Comment by dongdongyang** [comment]
"http-nio-8081-exec-12" Id=189 cpuUsage=2% BLOCKED on okhttp3.internal.connection.RealConnectionPool@572311d owned by "http-nio-8081-exec-22" Id=199
    at okhttp3.internal.connection.Transmitter.isCanceled(Transmitter.java:342)
    -  blocked on okhttp3.internal.connection.RealConnectionPool@572311d
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:222)
    at okhttp3.RealCall.execute(RealCall.java:81)
    at com.ly.spat.dsf.client.v2.HttpService.action(HttpService.java:659)
    at com.ly.spat.dsf.client.v2.HttpService.action(HttpService.java:454)
    at com.tc.ly.neo.boot.controller.DemoController.getUserBySync(DemoController.java:111)
    at sun.reflect.GeneratedMethodAccessor44.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)

**Comment by swankjesse** [comment]
Unclear what action to take here.

**Comment by poorduckling** [comment]
I have the question ,okhttp version: 3.14.9
