### ISSUE TITLE
Flaky test: HttpOverHttp2Test#responseHeadersAfterGoaway

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#4836]
https://227-5152285-gh.circle-artifacts.com/0/home/circleci/testrepo11/reports/okhttp/build/reports/tests/test/classes/okhttp3.internal.http2.HttpOverHttp2Test.html#responseHeadersAfterGoaway[h2]

```
org.junit.ComparisonFailure: expected:<"[DEF]"> but was:<"[ABC]">
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at okhttp3.internal.http2.HttpOverHttp2Test.responseHeadersAfterGoaway(HttpOverHttp2Test.java:1421)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at okhttp3.OkHttpClientTestRule$1.evaluate(OkHttpClientTestRule.java:37)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:298)
	at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:292)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by amirlivneh** [comment]
There are a number of root causes for the flakiness, each has a different symptom. The failure mentioned in the description occurs when MockWebServer executes this line concurrently for both the requests it receives:
https://github.com/square/okhttp/blob/077281796ed65222e24e70b2233c9e1a7e21d4a2/mockwebserver/src/main/java/okhttp3/mockwebserver/RecordedRequest.java#L75
The second call to `getHostName()` hangs for five seconds. As a result, the "ABC" response, which is only delayed by one second, beats the "DEF" response, which is asserted to be received first.

**Comment by yschimke** [comment]
Not seeing in current failures list https://circleci.com/build-insights/gh/square/okhttp/master

**Comment by yschimke** [comment]
Saw again https://github.com/square/okhttp/issues/6648
