### ISSUE TITLE
Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException

### ISSUE THREAD

**Issue by lly835** [square/okhttp#4919]
`mvn springboot:run`  is ok.

`java -jar target/*.jar`  error.
```
Exception in thread "OkHttp Dispatcher" java.lang.NullPointerException
        at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.java:570)
        at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:211)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
2019-04-09 23:28:10.123  INFO 41265 --- [           main] o.s.s.concurrent.ThreadPoolTaskExecutor  : Initializing ExecutorService 'applicationTaskExecutor'
2019-04-09 23:28:10.320  INFO 41265 --- [           main] o.s.s.c.ThreadPoolTaskScheduler          : Initializing ExecutorService 'taskScheduler'

```

**Comment by swankjesse** [comment]
OkHttp version?

**Comment by swankjesse** [comment]
At first glance this appears to be a null `WebSocketListener`.
