### ISSUE TITLE
java.net.SocketException: Bad file descriptor (Write failed)

### ISSUE THREAD

**Issue by victorlaerte** [square/okhttp#4921]
I'm reading a file and sending each line of the file to a server using okHttp. The file is really big, almost 10 millions of lines. 

I'm reusing the client to send the requests, even though after some 4 thousand or 5 thousand requests I get the following stack trace:

```
java.net.SocketException: Bad file descriptor (Write failed)

	at java.net.SocketOutputStream.socketWrite0(Native Method)
	at java.net.SocketOutputStream.socketWrite(SocketOutputStream.java:111)
	at java.net.SocketOutputStream.write(SocketOutputStream.java:155)
	at okio.Okio$1.write(Okio.java:79)
	at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
	at okio.RealBufferedSink.flush(RealBufferedSink.java:224)
	at okhttp3.internal.http1.Http1Codec.finishRequest(Http1Codec.java:166)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:84)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
	at okhttp3.RealCall.execute(RealCall.java:92)
```

Code example:
```
val lines = Files.lines(Paths.get(File("myfile.csv").toURI()))

val httpClientConfig = HttpClientConfig()
val builder = getBuilder(httpClientConfig)
var client = builder.build()

lines.parallel().forEach {
	try {
	        val body = RequestBody.create(HttpClient.MEDIA_TYPE, JSONParser.toJSON({"myJson" : "test"}))
		val requestBuilder = Request.Builder()
			.url(Analytics.endpointURL)
			.post(body)

		val request = requestBuilder.build()
		client.newCall(request).execute()
}
```

**Comment by swankjesse** [comment]
You aren’t closing the response returned by `execute()`, which causes you to exhaust the supply of file descriptors. Close that and you’re good.
