### ISSUE TITLE
Invalid Malformed URL

### ISSUE THREAD

**Issue by nathancassano** [square/okhttp#4934]
The path of a URL contains a colon symbol which is causing the call to fail.

Using version com.squareup.retrofit2:retrofit:2.5.0

Code:
```
public interface ClientApi {
    @PUT("user:email={email}/login")
    Call<WrappedResponse<String>> login(@Path("email") String email, @Body String pass);
...
```

Stack trace:
```
Caused by: java.lang.IllegalArgumentException: Malformed URL. Base: https://test.com/restapi/, Relative: user:email=me@test.com/login
        at retrofit2.RequestBuilder.get(RequestBuilder.java:221)
        at retrofit2.RequestFactory.create(RequestFactory.java:111)
        at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:190)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:173)
        at Service.login(Service.java:38)
```

Think the code needs to treat the relative portion of the URL like an absolute URL when parsing.

**Comment by swankjesse** [comment]
Try adding `./` to the annotation:

```
public interface ClientApi {
    @PUT("./user:email={email}/login")
    Call<WrappedResponse<String>> login(@Path("email") String email, @Body String pass);
...
```

**Comment by nathancassano** [comment]
Using a retaliative path  annotation `./` does not solve this issue. This is still an open issue.
```
Caused by: java.lang.IllegalArgumentException: @Path parameters shouldn't perform path traversal ('.' or '..'):
        at retrofit2.RequestBuilder.addPathParam(RequestBuilder.java:113)
        at retrofit2.ParameterHandler$Path.apply(ParameterHandler.java:99)
        at retrofit2.RequestFactory.create(RequestFactory.java:108)
        at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:190)
        at retrofit2.OkHttpCall.execute(OkHttpCall.java:173)
```
