### ISSUE TITLE
Permission Denied: Connect after timeouts

### ISSUE THREAD

**Issue by danielflower** [square/okhttp#4965]
There is a change in behaviour introduced in `3.14.0`. The background is I have a test to make sure that after many client timeouts, subsequent requests succeed.

The test goes like this:

1. Start a web server
2. Create a client with a 10 millisecond timeout
3. Fire 200 calls at the server (some will finish in time, many will timeout)
4. Use a client with a default timeout to call the server

In this case, I expect many calls in step 3 to fail, however after going back to a normal timeout the call in step 4 should succeed. This test passes with `3.13.1` and earlier, however after upgrading to `3.14.0` (and `3.14.1`) the call with the "normal" client fails with a SocketException.

Here is the test:

````java
    @Test
    public void canHandleStuffWithoutBreaking() throws InterruptedException, IOException {
        server = httpServer()
            .addHandler(Method.GET, "/full", (req, resp, pp) -> {
                try {
                    resp.write("A full length message");
                } catch (Exception ignored) {
                }
            })
            .addHandler(Method.GET, "/chunks", (req, resp, pp) -> {
                Thread.sleep(4);
                try {
                    resp.sendChunk("Chunk one");
                    resp.sendChunk("Chunk two");
                } catch (Exception ignored) {
                }
            })
            .start();

        OkHttpClient shortReader = ClientUtils.client.newBuilder()
            .readTimeout(10, TimeUnit.MILLISECONDS)
            .build();

        int calls = 200;
        CountDownLatch latch = new CountDownLatch(calls * 2);
        for (int i = 0; i < calls; i++) {
            Callback responseCallback = new Callback() {
                public void onFailure(Call call, IOException e) {
                    latch.countDown();
                }
                public void onResponse(Call call, Response response) {
                    latch.countDown();
                    response.close();
                }
            };
            shortReader.newCall(request(server.uri().resolve("/full")).build()).enqueue(responseCallback);
            shortReader.newCall(request(server.uri().resolve("/chunks")).build()).enqueue(responseCallback);
        }

        assertThat(latch.await(2, TimeUnit.MINUTES), is(true));

        try (Response resp = call(request(server.uri().resolve("/full")))) {
            assertThat(resp.body().string(), is("A full length message"));
        }
        try (Response resp = call(request(server.uri().resolve("/chunks")))) {
            assertThat(resp.body().string(), is("Chunk oneChunk two"));
        }
    }
````

The exception is thrown by `try (Response resp = call(request(server.uri().resolve("/full")))) {`

    Caused by: java.net.SocketException: Permission denied: connect
	at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:107)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:87)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
	at okhttp3.RealCall.execute(RealCall.java:81)

Note that using HTTP and HTTPS has the same result.

That test depends on various utilities however it can be run if the repo is cloned: https://github.com/3redronin/mu-server/blob/master/src/test/java/io/muserver/FlakyClientTest.java

The test fails when changing the okhttpclient in pom.xml to `3.14.0`

If it helps, I can try to isolate this further into a smaller standalone test.

**Comment by swankjesse** [comment]
Presumably on 3.13 some calls completed successfully and their connections were pooled, which caused later calls to use the pooled connections. With 3.14 we’re probably pooling fewer connections.

Worth a look!

**Comment by swankjesse** [comment]
@danielflower I recently did some stress testing of my own. I wasn’t able to reproduce this particular problem, even using your test suite.
https://github.com/square/okhttp/pull/5414
https://gist.github.com/swankjesse/a7b74957314c208c1027a41e969e076e

If you can provide a self-contained reproducing test case, please let me know!
