### ISSUE TITLE
App crash at start up on Android 8.0

### ISSUE THREAD

**Issue by CollinDai** [square/okhttp#4969]
Android Studio: 3.3.2
Device OS: 26
Kotlin version: 1.3.30
Gradle wrapper: 4.10.1
Steps to reproduce:
1. Create a new project using Android Studio, set the minimal sdk level to 26, and check "Use AndroidX artifact"
2. Without changing anything, add this line to the app's dependency
`    implementation 'com.squareup.okhttp3:logging-interceptor:3.14.1'`
3. Run the app on Android 8.0 (SDK 26)

The app will crash when starting up, with this stacktrace
```
java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{peike.testokhttp/peike.testokhttp.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "peike.testokhttp.MainActivity" on path: DexPathList[[zip file "/data/app/peike.testokhttp-8XiJCpXfzD7iFbbBYv9HJw==/base.apk"],nativeLibraryDirectories=[/data/app/peike.testokhttp-8XiJCpXfzD7iFbbBYv9HJw==/lib/x86, /system/lib, /vendor/lib]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2718)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6541)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "peike.testokhttp.MainActivity" on path: DexPathList[[zip file "/data/app/peike.testokhttp-8XiJCpXfzD7iFbbBYv9HJw==/base.apk"],nativeLibraryDirectories=[/data/app/peike.testokhttp-8XiJCpXfzD7iFbbBYv9HJw==/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1173)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2708)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6541) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Landroidx/appcompat/app/AppCompatActivity;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:363)
        		... 12 more
     Caused by: java.lang.ClassNotFoundException: Didn't find class "androidx.appcompat.app.AppCompatActivity" on path: DexPathList[[zip file "/data/app/peike.testokhttp-8XiJCpXfzD7iFbbBYv9HJw==/base.apk"],nativeLibraryDirectories=[/data/app/peike.testokhttp-8XiJCpXfzD7iFbbBYv9HJw==/lib/x86, /system/lib, /vendor/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        		... 15 more
```

But this crash will not happen on a device running Android 9.0, or on the same 8.0 device but this is added in the gradle
```
compileOptions {
    sourceCompatibility = JavaVersion.VERSION_1_8
    targetCompatibility = JavaVersion.VERSION_1_8
}
```
Is this a bug?

**Comment by JakeWharton** [comment]
The exception message indicates that Android cannot find AppCompatActivity. It's not clear why you think OkHttp is at fault here.

**Comment by CollinDai** [comment]
@JakeWharton Yeah I was curious about that too. Why adding a dependency with no code using it and no compilation error will crash the app, and removing that dependency the crash stops?

After changing things around, I found out that the crash will only happen with OkHttp 3.13.0 and up. 3.12.2, 3.12.0 are all working fine, even with the Gradle 5.4, Android plugin 3.4.0 and `implementation 'com.squareup.okhttp3:okhttp:3.13.0'`.

**Comment by TangHuaiZhe** [comment]
@CollinDai The difference between 3.12.0  and 3.13.0 is that 3.12.0  was compiled by Java 1.7 and 3.13.0 was compiled by Java 1.8. Perhaps that's Why your app is no crash When your java version set to 1.8.
But don't know  why this crash will not happen on a device running Android 9.0 with java1.7.
Also don't know why the exception message indicates that Android cannot find AppCompatActivity.

**Comment by peikedai** [comment]
@TangHuaiZhe Exactly! That error message cost my hours to isolate the cause of the crash. It would be nice if the message could suggest the OkHttp is not compatible or even better if it could just fail the build.

**Comment by swankjesse** [comment]
@peikedai seems like a bug in the Android Gradle plugin? Not sure what OkHttp can do here.

**Comment by CollinDai** [comment]
@swankjesse yeah agree now that I know a little better about this issue. 

Thank you all for your help, I will close this issue

**Comment by GitJoBo** [comment]
I have also encountered this problem. The current solution is to use OKHttp3.10.0. I hope to solve it better in the future
