### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'java.util.Map java.net.CookieHandler.get(java.net.URI, java.util.Map)' on a null object reference

### ISSUE THREAD

**Issue by JuKu** [square/okhttp#4977]
I get this exception:
```java
2019-04-26 00:22:20.298 3186-3265/com.jukusoft.rise E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.jukusoft.rise, PID: 3186
    java.lang.NullPointerException: Attempt to invoke virtual method 'java.util.Map java.net.CookieHandler.get(java.net.URI, java.util.Map)' on a null object reference
        at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.java:61)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:223)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
        at java.lang.Thread.run(Thread.java:764)

```

Code:
```java
import android.text.TextUtils;

import com.jukusoft.rise.BuildConfig;
import com.jukusoft.rise.Const;

import java.net.CookieHandler;

import okhttp3.Credentials;
import okhttp3.JavaNetCookieJar;
import okhttp3.OkHttpClient;
import okhttp3.logging.HttpLoggingInterceptor;
import retrofit2.Retrofit;
import retrofit2.converter.gson.GsonConverterFactory;

public class ServiceGenerator {

    //protected static final Retrofit retrofit;

    private static Retrofit.Builder builder =
            new Retrofit.Builder()
                    .baseUrl(Const.getRestServerBaseURL())
                    .addConverterFactory(GsonConverterFactory.create())
                    .client(OkHttpClientFactory.getUnsafeOkHttpClient());

    private static Retrofit retrofit = builder.build();

    private static JavaNetCookieJar jncj = new JavaNetCookieJar(CookieHandler.getDefault());

    private static OkHttpClient.Builder httpClient =
            new OkHttpClient.Builder()
                    .cookieJar(jncj);

    private static HttpLoggingInterceptor logging =
            new HttpLoggingInterceptor()
                    .setLevel(HttpLoggingInterceptor.Level.BODY);

    protected ServiceGenerator () {
        //
    }

    public static <S> S createService(Class<S> serviceClass) {
        return createService(serviceClass, null, null);
    }

    public static <S> S createService(
            Class<S> serviceClass, String username, String password) {
        if (!TextUtils.isEmpty(username)
                && !TextUtils.isEmpty(password)) {
            String authToken = Credentials.basic(username, password);
            return createService(serviceClass, authToken);
        }

        return createService(serviceClass, null);
    }

    public static <S> S createService(
            Class<S> serviceClass, final String authToken) {
        if (!TextUtils.isEmpty(authToken)) {
            AuthenticationInterceptor interceptor =
                    new AuthenticationInterceptor(authToken);

            if (!httpClient.interceptors().contains(interceptor)) {
                httpClient.addInterceptor(interceptor);

                builder.client(httpClient.build());
                retrofit = builder.build();
            }
        }

        //add logging
        if (!httpClient.interceptors().contains(logging)) {
            if (BuildConfig.DEBUG) {
                // development build
                logging.setLevel(HttpLoggingInterceptor.Level.BODY);
            } else {
                // production build
                logging.setLevel(HttpLoggingInterceptor.Level.BASIC);
            }

            //don't log sensitive information
            logging.redactHeader("Authorization");

            httpClient.addInterceptor(logging);
            builder.client(httpClient.build());
            retrofit = builder.build();
        }

        return retrofit.create(serviceClass);
    }

}
```

**Comment by swankjesse** [comment]
Looks like your CookieHandler is null. Try providing one.

**Comment by JuKu** [comment]
@swankjesse Thank you for your fast answer! :)
I have already found another solution which is working for me.
So you can close this issue.

**Comment by mraj0045** [comment]
> @swankjesse Thank you for your fast answer! :)
> I have already found another solution which is working for me.
> So you can close this issue.

@JuKu Im also facing the same issue. Please provide suggestion to fix. Thanks
