### ISSUE TITLE
3.14.1 interceptor regression

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#4986]
I think this is probably a bug in my client code, but it's a new behaviour so flagging anyway

https://github.com/yschimke/okurl/blob/5a40144ff173e055d60a67f0c51df1ccad07a419/src/main/kotlin/com/baulsupp/okurl/authenticator/RenewingInterceptor.kt#L34

```
Apr 27, 2019 9:25:20 AM com.baulsupp.cooee.ProdAppServices$client$1$1 log
INFO: [33 ms] requestHeadersStart
Apr 27, 2019 9:25:20 AM com.baulsupp.cooee.ProdAppServices$client$1$1 log
INFO: [33 ms] requestHeadersEnd
Apr 27, 2019 9:25:20 AM com.baulsupp.cooee.ProdAppServices$client$1$1 log
INFO: [34 ms] responseHeadersStart
Apr 27, 2019 9:25:20 AM com.baulsupp.cooee.ProdAppServices$client$1$1 log
INFO: [2835 ms] connectionReleased
Apr 27, 2019 9:25:20 AM com.baulsupp.cooee.ProdAppServices$client$1$1 log
INFO: [2836 ms] callEnd
Exception in thread "OkHttp Dispatcher" java.lang.IllegalStateException: cannot make a new request because the previous response is still open: please call response.close()
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:164)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at com.baulsupp.okurl.authenticator.RenewingInterceptor$intercept$1.invokeSuspend(RenewingInterceptor.kt:34)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.kt:116)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:80)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:54)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:36)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at com.baulsupp.okurl.authenticator.RenewingInterceptor.intercept(RenewingInterceptor.kt:28)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
```

**Comment by yschimke** [comment]
Closing under the assumption it's my bug

**Comment by swankjesse** [comment]
Yep, I think that might have previously been a leak.

**Comment by hqzxzwb** [comment]
Would you share what caused this? I just now encountered the same problem.

**Comment by alexv-anyvision** [comment]
Encountered the same error in 3.14.0 and above, in lower versions everything working.

**Comment by swankjesse** [comment]
@alexv-anyvision this leak was previously silent; in OkHttp 3.14 we started to detect it and report on it.

**Comment by BugsBunnyBR** [comment]
Is there any workaround?

**Comment by yschimke** [comment]
Is this the leak within an interceptor case? e.g. RenewingInterceptor in my case?

**Comment by swankjesse** [comment]
Yeah, interceptors must close the previous response before proceeding to the next.

**Comment by BugsBunnyBR** [comment]
So, this is still needed in the release 3.14.2 and 4.0.0, right ?

**Comment by ysy950803** [comment]
So how to ifx?
I have the same problem when adding a RetryInterceptor like this:
```java
private static class RetryInterceptor implements Interceptor {
    @Override
    public okhttp3.Response intercept(Chain chain) throws IOException {
        int retryCount = 0;
        Request request = chain.request();
        okhttp3.Response response = chain.proceed(request);
        while (!response.isSuccessful() && retryCount < RETRY_MAX_COUNT - 1) {
            retryCount++;
            response = chain.proceed(request);
        }
        if (retryCount > 0) {
            Logger.w(TAG, "retryCount:" + retryCount);
        }
        return response;
    }
}
```

**Comment by yschimke** [comment]
@ysy950803 close the response before replacing it with the chain.proceed inside the while loop.

**Comment by ysy950803** [comment]
> @ysy950803 close the response before replacing it with the chain.proceed inside the while loop.

Thanks! It works!

**Comment by noway** [comment]
How would I approach closing previous response in this code? Seems to be non-trivial since I don't have access to previous response. I only get access to current response from `chain.proceed(req)`.
```java

            // #156 fix cookie issue
            final Request req = builder.build();
            clientBuilder.addNetworkInterceptor(new Interceptor() {
                @Override
                public Response intercept(Chain chain) throws IOException {
                    redirects.add(chain.request().url().toString());
                    return chain.proceed(chain.request());
                }
            });
            // Add request interceptor for upload progress event
            clientBuilder.addInterceptor(new Interceptor() {
                @Override
                public Response intercept(@NonNull Chain chain) throws IOException {
                    try {
                        Response originalResponse = chain.proceed(req);
                        ResponseBody extended;
                        switch (responseType) {
                            case KeepInMemory:
                                extended = new ReactNativeBlobUtilDefaultResp(
                                        ReactNativeBlobUtil.RCTContext,
                                        taskId,
                                        originalResponse.body(),
                                        options.increment);
                                break;
                            case FileStorage:
                                extended = new ReactNativeBlobUtilFileResp(
                                        ReactNativeBlobUtil.RCTContext,
                                        taskId,
                                        originalResponse.body(),
                                        destPath,
                                        options.overwrite);
                                break;
                            default:
                                extended = new ReactNativeBlobUtilDefaultResp(
                                        ReactNativeBlobUtil.RCTContext,
                                        taskId,
                                        originalResponse.body(),
                                        options.increment);
                                break;
                        }
                        return originalResponse.newBuilder().body(extended).build();
                    } catch (SocketException e) {
                        timeout = true;
                    } catch (SocketTimeoutException e) {
                        timeout = true;
                        //ReactNativeBlobUtilUtils.emitWarningEvent("ReactNativeBlobUtil error when sending request : " + e.getLocalizedMessage());
                    } catch (Exception ex) {

                    }
                    return chain.proceed(chain.request());
                }
            });
```

**Comment by yschimke** [comment]
@noway it looks like you probably just want to assign originalResponse to a variable scoped outside the try/catch, and close it in a finally.

This sort of question is best for stackoverflow, please only continue the discussion here with a reproducing bug case.  I suspect this is a usage question, we can't provide 1:1 advice through the issue tracker.
