### ISSUE TITLE
🙉TimeOut's test - java.lang.RuntimeException: No activities found

### ISSUE THREAD

**Issue by lmdic** [square/okhttp#4992]
Android Studio 3.3, Koltlin 1.3
Java 1.8

Here my Espresso's test with MockWebServer.

  
  ```
 import android.content.Intent
import androidx.test.espresso.Espresso
import androidx.test.espresso.Espresso.onView
import androidx.test.espresso.action.ViewActions
import androidx.test.espresso.action.ViewActions.click
import androidx.test.espresso.action.ViewActions.typeText
import androidx.test.espresso.assertion.ViewAssertions
import androidx.test.espresso.assertion.ViewAssertions.matches
import androidx.test.espresso.intent.rule.IntentsTestRule
import androidx.test.espresso.matcher.ViewMatchers
import androidx.test.espresso.matcher.ViewMatchers.*
import androidx.test.platform.app.InstrumentationRegistry
import androidx.test.runner.AndroidJUnit4
import okhttp3.mockwebserver.MockResponse
import okhttp3.mockwebserver.MockWebServer
import org.junit.After
import org.junit.Before
import org.junit.Rule
import org.junit.Test
import org.junit.runner.RunWith
import java.util.concurrent.TimeUnit
    
    @RunWith(AndroidJUnit4::class)
    class AddTraderActivityNetworkTest {
        private lateinit var mockServer: MockWebServer
    
        @Rule
        @JvmField
        var addTraderIntentTestRule: IntentsTestRule<AddTraderActivity> = IntentsTestRule(AddTraderActivity::class.java)
    
        @Before
        fun setup() {
            mockServer = MockWebServer()
            mockServer.start(8081)
         }
     
        @Test
        fun buttonStart_click_serverError_showToast() {
            mockServer.enqueue(MockResponse()
                    .setResponseCode(500))
            
            onView(withId(R.id.startButton))
                    .perform(click())
            onView(withText(R.string.server_error)).inRoot(ToastMatcher())
                    .check(matches(isDisplayed()))
        }
    
         @Test
        fun buttonStart_click_timeOut_showToast() {
            mockServer.enqueue(MockResponse()
                    .setResponseCode(200)
                    .throttleBody(1024, 1, TimeUnit.SECONDS)) 
           
            onView(withId(R.id.startButton))
                    .perform(click())
            onView(withText(R.string.service_unavailable)).inRoot(ToastMatcher())
                    .check(matches(isDisplayed()))
        }
    
        @After
        @Throws
        fun tearDown() {
            // We're done with tests, shut it down
            mockServer.shutdown()
        }
    }
```

When start test buttonStart_click_serverError_showToast it's success pass. But when I start test buttonStart_click_timeOut_showToast I get error:

  ```
  java.lang.RuntimeException: No activities found. Did you forget to launch the activity by calling getActivity() or startActivitySync or similar?
at androidx.test.espresso.base.RootViewPicker.waitForAtLeastOneActivityToBeResumed(RootViewPicker.java:169)
at androidx.test.espresso.base.RootViewPicker.get(RootViewPicker.java:83)
at androidx.test.espresso.ViewInteractionModule.provideRootView(ViewInteractionModule.java:77)
at androidx.test.espresso.ViewInteractionModule_ProvideRootViewFactory.provideRootView(ViewInteractionModule_ProvideRootViewFactory.java:35)
at androidx.test.espresso.ViewInteractionModule_ProvideRootViewFactory.get(ViewInteractionModule_ProvideRootViewFactory.java:24)
at androidx.test.espresso.ViewInteractionModule_ProvideRootViewFactory.get(ViewInteractionModule_ProvideRootViewFactory.java:10)
at androidx.test.espresso.base.ViewFinderImpl.getView(ViewFinderImpl.java:62)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:276)
at androidx.test.espresso.ViewInteraction$2.call(ViewInteraction.java:268)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.Handler.handleCallback(Handler.java:739)
at android.os.Handler.dispatchMessage(Handler.java:95)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)


```
 

How I can fix this?

**Comment by JakeWharton** [comment]
It's not clear why you think MockWebServer would be causing this.

**Comment by lmdic** [comment]
I found solution

```
 @Test
    fun buttonStart_click_timeOut_showToast() {
        onView(withId(R.id.baseTextInputEditText))
                .perform(typeText(BASE_TEST))
        onView(withId(R.id.quoteTextInputEditText))
                .perform(typeText(QUOTE_TEST))
        onView(withId(R.id.startButton))
                .perform(click())
        mockServer.enqueue(MockResponse()
                .setResponseCode(200)
                .throttleBody(1024, 1, TimeUnit.SECONDS))

        onView(withText(R.string.service_unavailable)).inRoot(ToastMatcher())
                .check(matches(isDisplayed()))
```

I call `enqueue` after `perform(click()`. And now it's work.

Is it good solution?
