### ISSUE TITLE
java.lang.RuntimeException: Could not launch intent Intent

### ISSUE THREAD

**Issue by lmdic** [square/okhttp#4993]
My Espresso's tests:

```
import okhttp3.mockwebserver.MockResponse
import okhttp3.mockwebserver.MockWebServer
import org.junit.*

@RunWith(AndroidJUnit4::class)
class TradersActivityTest {
    private val TRADERS_EMPTY_LIST = "tm_get_0_trader_response_json_200_from_file.json"
    private val TEN_TRADERS_LIST = "tm_get_10_traders_response_json_200_from_file.json"
    private val DEFAULT_TRADERS_LIST = TEN_TRADERS_LIST

    @Rule
    @JvmField
    var tradersIntentTestRule = IntentsTestRule(TradersActivity::class.java, false, false)
 
    @Before
    fun setup() {
        mockServer = MockWebServer()
        mockServer.start(8081)

        mockServer.enqueue(MockResponse()
                .setResponseCode(200)
                .setBody(FileUtil.getStringFromFile(context, DEFAULT_TRADERS_LIST)))
        tradersIntentTestRule.launchActivity(Intent())

        val recyclerView = tradersIntentTestRule.activity.findViewById<View>(R.id.tradersRecyclerView) as RecyclerView
        itemCount = recyclerView.adapter?.itemCount!!
        traderRandomPos = (0..itemCount).random()
}

    @Test
    fun noTradersText_gravity() {
        onView(withId(R.id.noTradersTextView))
                .check(matches(withTextViewGravity(Gravity.CENTER)))
    }

    @Test
    fun noTraders_noTradersTextView_isDisplayed() {
        mockServer.enqueue(MockResponse()
                .setResponseCode(200)
                .setBody(FileUtil.getStringFromFile(context, TRADERS_EMPTY_LIST)));
        tradersIntentTestRule.launchActivity(Intent()) // error here
        onView(withId(R.id.noTradersTextView))
                .check(matches(isDisplayed()))
    }
```

When I start test "`noTradersText_gravity`" first load stubbed response form file **DEFAULT_TRADERS_LIST** and then check gravity of `noTradersTextView`.
Nice. It's work fine.

But I need in test `noTraders_noTradersTextView_isDisplayed `to stubbed response from ANOTHER file **TRADERS_EMPTY_LIST**.
As result in test `noTraders_noTradersTextView_isDisplayed` I stub response from file **TRADERS_EMPTY_LIST**.
But when I start test `noTraders_noTradersTextView_isDisplayed `I get error in this line:

       ` tradersIntentTestRule.launchActivity(Intent())`

Details:

```
java.lang.RuntimeException: Could not launch intent Intent { flg=0x10000000 cmp=com.myproject/com.myproject.activity.TradersActivity } within 45 seconds. Perhaps the main thread has not gone idle within a reasonable amount of time? There could be an animation or something constantly repainting the screen. Or the activity is doing network calls on creation? See the threaddump logs. For your reference the last time the event queue was idle before your activity launch request was 1556553142425 and now the last time the queue went idle was: 1556553151185. If these numbers are the same your activity might be hogging the event queue.
at androidx.test.runner.MonitoringInstrumentation.startActivitySync(MonitoringInstrumentation.java:459)
at androidx.test.rule.ActivityTestRule.launchActivity(ActivityTestRule.java:358)
at md.dotfinance.tm.android.activity.TradersActivityTest.noTraders_noTradersTextView_isDisplayed(TradersActivityTest.kt:113)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
at androidx.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
at androidx.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
at androidx.test.rule.ActivityTestRule$ActivityStatement.evaluate(ActivityTestRule.java:531)
at org.junit.rules.RunRules.evaluate(RunRules.java:20)
at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at androidx.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:104)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:392)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:1879)

```

**Comment by vashisthg** [comment]
How is this connected to OkHttp?

**Comment by lmdic** [comment]
This is connect with MockWebServer
