### ISSUE TITLE
webSocket.cancel() 

### ISSUE THREAD

**Issue by g754687222** [square/okhttp#5056]
java.net.SocketException: Socket closed
        at com.android.org.conscrypt.NativeCrypto.SSL_read(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl$SSLInputStream.read(OpenSSLSocketImpl.java:811)
        at okio.Okio$2.read(Okio.java:140)
        at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
        at okio.RealBufferedSource.request(RealBufferedSource.java:72)
        at okio.RealBufferedSource.require(RealBufferedSource.java:65)
        at okio.RealBufferedSource.readByte(RealBufferedSource.java:78)
        at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.java:117)
        at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:101)
        at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:273)
        at okhttp3.internal.ws.RealWebSocket$1.onResponse(RealWebSocket.java:209)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:174)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
        at java.lang.Thread.run(Thread.java:818)

**Comment by JakeWharton** [comment]
This looks like a normal exception that should be expected when invoking cancel. Perhaps we need an `isCanceled` to check in `onFailure`?

**Comment by swankjesse** [comment]
This exception is getting delivered to your listener? That’s working as designed though wrapping the exception with `IOException("canceled")` would be less alarming.

**Comment by g754687222** [comment]
Thank you for reminding me that when onFailure has a message, I will detect if it is triggered by cancel.
