### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: size=0 offset=0 byteCount=64

### ISSUE THREAD

**Issue by Shawpoo** [square/okhttp#5145]
Using:
api 'com.squareup.okhttp3:okhttp:3.10.0'
api 'com.squareup.okio:okio:1.14.0'
api 'com.squareup.okhttp3:logging-interceptor:3.10.0'

java.lang.ArrayIndexOutOfBoundsException: size=0 offset=0 byteCount=64
at okio.Util.checkOffsetAndCount(Util.java:30)
at okio.Buffer.copyTo(Buffer.java:175)
at okhttp3.logging.HttpLoggingInterceptor.isPlaintext(HttpLoggingInterceptor.java:296)
at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:265)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
at java.lang.Thread.run(Thread.java:761)

**Comment by swankjesse** [comment]
Most likely cause is concurrent access to buffers, which can cause things to crash. You should fix your concurrency issue and we should fix OkHttp to be resilient even if you have a concurrency issue.

We’re tracking that here: https://github.com/square/okio/issues/163
