### ISSUE TITLE
java.lang.IllegalStateException: Expected Android API level 21+ but was 19

### ISSUE THREAD

**Issue by fishsoft** [square/okhttp#5162]
version:3.14.2
android-version:4.4

compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
}

java8 is already configured

implementation 'com.squareup.retrofit2:retrofit:2.5.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation 'io.reactivex.rxjava2:rxjava:2.2.8'
    implementation 'com.squareup.retrofit2:retrofit:2.5.0'
    implementation 'com.squareup.okhttp3:okhttp:3.14.2'
    implementation 'com.google.code.gson:gson:2.8.2'//使用最新版本解析会出问题
    implementation 'io.reactivex.rxjava2:rxandroid:2.1.1'
    implementation 'com.squareup.retrofit2:converter-gson:2.3.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.3.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.14.1'

06-03 12:07:03.205 12012-12012/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.yindex.yindexclient, PID: 12012
    java.lang.ExceptionInInitializerError
        at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:2)
        at com.yindex.yindexclient.http.RetrofitCreateHelper.<init>(RetrofitCreateHelper.kt:3)
        at com.yindex.yindexclient.http.RetrofitCreateHelper.<init>(RetrofitCreateHelper.kt:25)
        at com.yindex.yindexclient.http.RetrofitCreateHelper$Companion.getInstance(RetrofitCreateHelper.kt:4)
        at com.yindex.yindexclient.ui.activity.login.LoginMode.login(LoginMode.kt:1)
        at com.yindex.yindexclient.ui.activity.login.LoginPresenter.login(LoginPresenter.kt:6)
        at com.yindex.yindexclient.ui.activity.login.LoginActivity.login(LoginActivity.kt:6)
        at com.yindex.yindexclient.ui.activity.login.LoginActivity.cliclView(LoginActivity.kt:20)
        at com.yindex.yindexclient.ui.base.BaseMvpActivity.onClick(BaseMvpActivity.kt:2)
        at android.view.View.performClick(View.java:4457)
        at android.view.View$PerformClick.run(View.java:18477)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5143)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 19
        at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:9)
        at okhttp3.internal.platform.Platform.findPlatform(Platform.java:1)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.java:1)
        at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:2) 
        at com.yindex.yindexclient.http.RetrofitCreateHelper.<init>(RetrofitCreateHelper.kt:3) 
        at com.yindex.yindexclient.http.RetrofitCreateHelper.<init>(RetrofitCreateHelper.kt:25) 
        at com.yindex.yindexclient.http.RetrofitCreateHelper$Companion.getInstance(RetrofitCreateHelper.kt:4) 
        at com.yindex.yindexclient.ui.activity.login.LoginMode.login(LoginMode.kt:1) 
        at com.yindex.yindexclient.ui.activity.login.LoginPresenter.login(LoginPresenter.kt:6) 
        at com.yindex.yindexclient.ui.activity.login.LoginActivity.login(LoginActivity.kt:6) 
        at com.yindex.yindexclient.ui.activity.login.LoginActivity.cliclView(LoginActivity.kt:20) 
        at com.yindex.yindexclient.ui.base.BaseMvpActivity.onClick(BaseMvpActivity.kt:2) 
        at android.view.View.performClick(View.java:4457) 
        at android.view.View$PerformClick.run(View.java:18477) 
        at android.os.Handler.handleCallback(Handler.java:733) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5143) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:602) 
        at dalvik.system.NativeStart.main(Native Method) 

why?

**Comment by yschimke** [comment]
https://github.com/square/okhttp/

The OkHttp 3.12.x branch supports Android 2.3+ (API level 9+) and Java 7+. These platforms lack support for TLS 1.2 and should not be used. But because upgrading is difficult we will backport critical fixes to the 3.12.x branch through December 31, 2020.

**Comment by DDihanov** [comment]
This might help: https://github.com/square/okhttp/issues/4622#issuecomment-588261353

**Comment by JordanLongstaff** [comment]
It doesn't help me. I'm seeing the same `IllegalStateException` and I'm not using Retrofit.
