### ISSUE TITLE
NPE building HandshakeCertificates when Proguard is enabled

### ISSUE THREAD

**Issue by nimeacuerdo** [square/okhttp#5172]
Hi there,

I'm using the following code with version **3.13.1** to create a `HandshakeCertificates` that is going to be used to configure `MockWebserver` to enable https in acceptance tests where our api is mocked this way, running on **Android P** emulators.

```
HandshakeCertificates serverCertificates = new HandshakeCertificates.Builder()
		.heldCertificate(certificate)
		.build();

mockWebServer.useHttps(serverCertificates.sslSocketFactory(), false);
```

as described in [this example gist](https://github.com/square/okhttp/blob/master/samples/guide/src/main/java/okhttp3/recipes/HttpsServer.java) you published.

Everything works fine (configuring the certificate in client side, handshaking of the connection, etc), without **Proguard** but when we enable it the following error occurs while initialising test code:

```
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.security.PublicKey.getAlgorithm()' on a null object reference
        at java.security.KeyStore$PrivateKeyEntry.<init>(KeyStore.java:576)
        at java.security.KeyStore$PrivateKeyEntry.<init>(KeyStore.java:526)
        at java.security.KeyStoreSpi.engineGetEntry(KeyStoreSpi.java:485)
        at java.security.KeyStore.getEntry(KeyStore.java:1560)
        at com.android.org.conscrypt.KeyManagerImpl.<init>(KeyManagerImpl.java:71)
        at com.android.org.conscrypt.KeyManagerFactoryImpl.engineGetKeyManagers(KeyManagerFactoryImpl.java:114)
        at javax.net.ssl.KeyManagerFactory.getKeyManagers(KeyManagerFactory.java:305)
        at okhttp3.tls.internal.TlsUtil.newKeyManager(SourceFile:101)
        at okhttp3.tls.HandshakeCertificates$Builder.build(SourceFile:164)
```

so I don't know if there is something I should be excluding explicitly in our config in order to avoid this problem.

The certificate used to configure `HandshakeCertificates` is provided here:

```
@Provides
@Singleton
HeldCertificate provideHeldCertificate() {
	return new HeldCertificate.Builder()
			.addSubjectAlternativeName("localhost")
			.build();
}
```

**Comment by swankjesse** [comment]
Yuck. If you can figure out why, please share.

**Comment by nimeacuerdo** [comment]
Got it working by adding the following to the test-specific proguard configuration:

`-keep class org.bouncycastle.** { *; } `

**Comment by swankjesse** [comment]
Gotcha. Presumably we want the Proguard project to add that to their config.

**Comment by yschimke** [comment]
Won't fix, not for us.
