### ISSUE TITLE
SocketTimeoutException on IPv6 from okhttp 3.14.1 

### ISSUE THREAD

**Issue by crossle** [square/okhttp#5186]
Okhttp 3.14.0 work ok, but from 3.14.1, IPv6 SocketTimeoutException
```
  java.net.SocketTimeoutException: failed to connect to xxx/2606:4700::6810:7c11 (port 443) from /2409:8900:2908:45a4:20:4951:b35b:d9e2 (port 34876) after 10000ms
                         E      at libcore.io.IoBridge.connectErrno(IoBridge.java:185)
                         E      at libcore.io.IoBridge.connect(IoBridge.java:129)
                         E      at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:137)
                         E      at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
                         E      at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
                         E      at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
                         E      at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
                         E      at java.net.Socket.connect(Socket.java:621)
                         E      at okhttp3.internal.platform.AndroidPlatform.connectSocket(AndroidPlatform.java:71)
                         E      at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263)
                         E      at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183)
                         E      at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
                         E      at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
                         E      at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
                         E      at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
                         E      at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
                         E      at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
                         E      at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
                         E      at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
                         E      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
                         E      at
```

**Comment by swankjesse** [comment]
Unclear that there’s anything OkHttp can do in this case.

**Comment by swankjesse** [comment]
Typically this is a bad network, and I’m suspicious that this would be different between 3.14 and 3.14.1, the diff is unrelated.

https://github.com/square/okhttp/compare/parent-3.14.0...parent-3.14.1?expand=1

**Comment by crossle** [comment]
How to debug this SocketTimeoutException on Okhttp? i use chrome open the api url, it's ok

**Comment by crossle** [comment]
Mobile 4G, ipv6 many SocketTimeoutException

**Comment by felixlix45** [comment]
Got the same issue with the latest version 4.9.3.

```
java.net.SocketTimeoutException: failed to connect to xxx/2606:4700:10::6816:4993 (port 443) from /2001:db8:1111::1 (port 49714) after 10000ms 
```
it only occurs when connecting with 1.1.1.1 DNS (not WARP) from 1.1.1.1 Apps. After retrying 3 times, it will fall back to IPv4 and succeed. Access on website is fine with the same condition, only on mobile.

Any recommendation?

**Comment by yschimke** [comment]
OkHttp 5 will use the happy eyeballs algorithm to connect race to ipv4 and ipv6. It's production quality, so if you avoid any new APIs which could change it's your best bet.

**Comment by felixlix45** [comment]
Yes, I read about OkHTTP 5 and the new happy eyeballs algorithm. But happy eyeballs will only make it faster to fall back to IPv4 right? 

I still don't get it why it can't connect to IPv6. The DNS log says it resolve the IPv6 but on `EventListener`, `connectFailed` still occurred with the same [error](https://github.com/square/okhttp/issues/5186#issuecomment-1477241746).

Is it because that Android doesn't support DHCPv6 as said in [here](https://issuetracker.google.com/issues/36949085#comment53)? And that's why Happy Eyeballs is required to support Dual Stack Hosts specifically on Android? If yes, then nothing I can do except using OkHTTP 5

Apparently Reddit also got this issue when they deploying IPv6 for their image loading as described in [here](https://www.reddit.com/r/RedditEng/comments/v1upr8/ipv6_support_on_android/)
