### ISSUE TITLE
HttpOverHttp2Test.missingPongsFailsConnection failing in JDK 12

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5221]
https://circleci.com/gh/square/okhttp/3612?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

```
missingPongsFailsConnection[h2] - okhttp3.internal.http2.HttpOverHttp2Test

org.junit.runners.model.TestTimedOutException: test timed out after 5 seconds
	at java.base@12.0.1/sun.security.ssl.SSLSocketImpl$AppInputStream.deplete(SSLSocketImpl.java:921)
	at java.base@12.0.1/sun.security.ssl.SSLSocketImpl.bruteForceCloseInput(SSLSocketImpl.java:615)
	at java.base@12.0.1/sun.security.ssl.SSLSocketImpl.duplexCloseInput(SSLSocketImpl.java:583)
	at java.base@12.0.1/sun.security.ssl.SSLSocketImpl.close(SSLSocketImpl.java:484)
	at app//okhttp3.internal.Util.closeQuietly(Util.kt:490)
	at app//okhttp3.internal.connection.Transmitter.maybeReleaseConnection(Transmitter.kt:285)
	at app//okhttp3.internal.connection.Transmitter.noMoreExchanges(Transmitter.kt:257)
	at app//okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:192)
	at app//okhttp3.RealCall.execute(RealCall.kt:66)
	at app//okhttp3.internal.http2.HttpOverHttp2Test.missingPongsFailsConnection(HttpOverHttp2Test.java:1244)
```

**Comment by monkey-mas** [comment]
Seems like a deadlock problem? Probably related issue was resolved and fixed in JDK 13.
[JDK-8219658 Deadlock in sun.security.ssl.SSLSocketImpl](https://bugs.openjdk.java.net/browse/JDK-8219658)

> This custom branch helped me to produce debug log (I'm attaching - openjdk.debug) where I discovered this SSL issue. 
In the end of that log you can see that in some usecases SSLSocketImpl$AppInputStream.read() 
method may hold inner class intrinsic lock when SSLSocketImpl$AppInputStream.deplete() method is being called 
and thread invoking that deplete() method will never succeed with inner class intrinsic lock acquisition.

**Comment by yschimke** [comment]
Should also be fixed in 12.0.2? https://bugs.openjdk.java.net/browse/JDK-8219991

**Comment by swankjesse** [comment]
Any further action on this?

**Comment by yschimke** [comment]
https://app.circleci.com/jobs/github/square/okhttp/6691

```
okhttp3.internal.http2.HttpOverHttp2Test > missingPongsFailsConnection[h2] FAILED
    java.lang.AssertionError: Queue still active after 1000ms
```

**Comment by yschimke** [comment]
Closing out as 12 isn't somewhere we should focus on, works in 11 and 13.
