### ISSUE TITLE
OkHttpClient.Builder().protocols() 4.0.0 throws NullPointerException

### ISSUE THREAD

**Issue by fastily** [square/okhttp#5257]
Using the current `4.0.0` release and JDK 11, the following code (in a file named `Foo.java`; compile with `javac` or your favorite IDE):

```java
import java.util.List;

import okhttp3.OkHttpClient;
import okhttp3.Protocol;

public class Foo
{
	public static void main(String[] args)
	{
		new OkHttpClient.Builder().protocols(List.of(Protocol.HTTP_1_1));
	}
}
```

always results in a NullPointerException
```
Exception in thread "main" java.lang.NullPointerException
	at java.base/java.util.Objects.requireNonNull(Objects.java:221)
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.indexOf(ImmutableCollections.java:169)
	at java.base/java.util.ImmutableCollections$AbstractImmutableList.contains(ImmutableCollections.java:200)
	at okhttp3.OkHttpClient$Builder.protocols(OkHttpClient.kt:770)
	at Foo.main(Foo.java:10)
```

**Comment by JakeWharton** [comment]
This seems like a bug in the JDK. We're calling `contains(null)` to ensure no `null` values are in the list. While the collection factories don't allow null elements, checking them for null seems like a perfectly valid thing to do.

**Comment by JakeWharton** [comment]
Ok it looks like the Javadoc permits this behavior and we need to be defensive about it either by traversing the list manually or just try/catching.
