### ISSUE TITLE
🙉I have encountered many such problems. When it happens, the subsequent requests will be wrong. Restarting the app can't solve the problem, but restarting the network can

### ISSUE THREAD

**Issue by MrYang12** [square/okhttp#5262]
java.net.ConnectException: Failed to connect to app.shubl.com/101.37.31.235:80
	at okhttp3.internal.connection.RealConnection.connectSocket(Unknown Source:145)
	at okhttp3.internal.connection.RealConnection.connect(Unknown Source:190)
	at okhttp3.internal.connection.StreamAllocation.findConnection(Unknown Source:264)
	at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(Unknown Source:0)
	at okhttp3.internal.connection.StreamAllocation.newStream(Unknown Source:22)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(Unknown Source:25)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:161)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:6)
	at okhttp3.internal.cache.CacheInterceptor.intercept(Unknown Source:136)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:161)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:6)
	at okhttp3.internal.http.BridgeInterceptor.intercept(Unknown Source:173)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:161)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(Unknown Source:59)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:161)
	at okhttp3.internal.http.RealInterceptorChain.proceed(Unknown Source:6)
	at okhttp3.RealCall.getResponseWithInterceptorChain(Unknown Source:115)
	at okhttp3.RealCall$AsyncCall.execute(Unknown Source:10)
	at okhttp3.internal.NamedRunnable.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	at java.lang.Thread.run(Thread.java:764)
Caused by: java.net.ConnectException: failed to connect to app.shubl.com/101.37.31.235 (port 80) from /10.211.37.210 (port 38281) after 60000ms: isConnected failed: ECONNABORTED (Software caused connection abort)
	at libcore.io.IoBridge.isConnected(IoBridge.java:273)
	at libcore.io.IoBridge.connectErrno(IoBridge.java:188)
	at libcore.io.IoBridge.connect(IoBridge.java:130)
	at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:129)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:356)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:182)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:357)
	at java.net.Socket.connect(Socket.java:616)
	at okhttp3.internal.platform.AndroidPlatform.connectSocket(Unknown Source:0)
	at okhttp3.internal.connection.RealConnection.connectSocket(Unknown Source:71)
	... 21 more
Caused by: android.system.ErrnoException: isConnected failed: ECONNABORTED (Software caused connection abort)
	at libcore.io.IoBridge.isConnected(IoBridge.java:262)
	... 31 more

**Comment by MrYang12** [comment]
My Okhttp version is  3.11.0

**Comment by yschimke** [comment]
Hi,

Please use sites like stackoverflow for such types of questions.  Generally you will get a wider range of responses, and the fix is often not specific to okhttp.

**Comment by yschimke** [comment]
Feel free to link the stackoverflow question here as well, but in future stackoverflow is the way to go until its a reproducible bug we can investigate.
