### ISSUE TITLE
Code 1013 is reserved and may not be used

### ISSUE THREAD

**Issue by changealice** [square/okhttp#5275]
🛑 𝙎𝙏𝙊𝙋

When the server closes by sending a Close control frame, and there is no body, I received the following exception:
java.net.ProtocolException: Code 1013 is reserved and may not be used.
	at okhttp3.internal.ws.WebSocketReader.readControlFrame(WebSocketReader.java:200)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.java:103)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.java:274)
	at okhttp3.internal.ws.RealWebSocket$2.onResponse(RealWebSocket.java:214)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:206)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1152)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:627)
	at java.lang.Thread.run(Thread.java:882)

I found this confusing because as stated in https://developer.mozilla.org/en-US/docs/Web/API/CloseEvent
it indices 
![image](https://user-images.githubusercontent.com/7836865/60830125-1b5c5a80-a1e9-11e9-8bd5-293e877acd18.png)

the websocket server has session limit , why code 1013 is reserved and throw ProtocolException not invoking frameCallback.onReadClose(code, reason); and finaly 
invoke listener.onClosing(this, code, reason);
is is bug ?

the okhttp version :
<dependency>
                <groupId>com.squareup.okhttp3</groupId>
                <artifactId>okhttp</artifactId>
                <version>3.12.0</version>
</dependency>

**Comment by JakeWharton** [comment]
The code mapping just needs updated to comply with https://www.iana.org/assignments/websocket/websocket.xml

**Comment by changealice** [comment]
@JakeWharton 
`
static String closeCodeExceptionMessage(int code) {
    if (code < 1000 || code >= 5000) {
      return "Code must be in range [1000,5000): " + code;
    } else if ((code >= 1004 && code <= 1006) || (code >= 1012 && code <= 2999)) {
      return "Code " + code + " is reserved and may not be used.";
    } else {
      return null;
    }
  }
`
 this source code is detect 1013  is reserved and may not be used. i dont't understand why  ?

**Comment by JakeWharton** [comment]
Because that's what the original RFC mandates
