### ISSUE TITLE
java.lang.Throwable: Explicit termination method 'close' not called

### ISSUE THREAD

**Issue by lougw** [square/okhttp#5282]
use version okhttp:3.14.0

java.lang.Throwable: Explicit termination method 'close' not called
	at dalvik.system.CloseGuard.open(CloseGuard.java:223)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:224)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:171)
	at okio.Okio.sink(Okio.java:181)
	at okhttp3.internal.io.FileSystem$1.sink(FileSystem.java:49)
	at okhttp3.internal.cache.DiskLruCache$Editor.newSink(DiskLruCache.java:899)
	at okhttp3.Cache$CacheRequestImpl.<init>(Cache.java:442)
	at okhttp3.Cache.put(Cache.java:254)
	at okhttp3.Cache$1.put(Cache.java:149)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:131)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)

**Comment by swankjesse** [comment]
Executable test case?

**Comment by lougw** [comment]
Monkey test problems

**Comment by yschimke** [comment]
OK, please reopen if you have a reproducible test case we can use.
