### ISSUE TITLE
NoClassDefFoundError when initializing HttpLoggingInterceptor

### ISSUE THREAD

**Issue by Archcry** [square/okhttp#5299]
I updated to the latest version of `logging-interceptor` and creating a loggingInterceptor no longer works. I wrote a small test that illustrated the problem, when i run it it throws a ClassNotfoundException:

```java
import okhttp3.logging.HttpLoggingInterceptor;
import org.checkerframework.checker.nullness.qual.NonNull;
import org.junit.jupiter.api.Test;

public class LogInterceptorTest {

    @Test
    void itShouldCreateALoggingInterceptor() {
        final HttpLoggingInterceptor loggingInterceptor = new HttpLoggingInterceptor(new HttpLoggingInterceptor.Logger() {
            @Override
            public void log(@NonNull final String msg) {
                System.out.println(msg);
            }
        });
    }
}
```

```bash
java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics

	at okhttp3.logging.HttpLoggingInterceptor.<init>(HttpLoggingInterceptor.kt)
	at nl.qbuzz.planner.mapper.LogInterceptorTest.itShouldCreateALoggingInterceptor(LogInterceptorTest.java:11)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:628)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:117)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:184)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:180)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:127)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:229)
	at org.junit.platform.launcher.core.DefaultLauncher.lambda$execute$6(DefaultLauncher.java:197)
	at org.junit.platform.launcher.core.DefaultLauncher.withInterceptedStreams(DefaultLauncher.java:211)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:191)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:128)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:69)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
```

I am not sure what causes this error and I don't even use kotlin in my project. It's just a simple maven java project.

**Comment by yschimke** [comment]
This class comes from kotlin-stdlib-1.3.41.jar, so most likely you are bundling some dependencies without using gradle or maven metadata.

https://github.com/square/okhttp

> OkHttp depends on Okio for high-performance I/O and the Kotlin standard library. Both are small libraries with strong backwards-compatibility.

**Comment by zhouyingge1104** [comment]
> This class comes from kotlin-stdlib-1.3.41.jar, so most likely you are bundling some dependencies without using gradle or maven metadata.
> 
> https://github.com/square/okhttp
> 
> > OkHttp depends on Okio for high-performance I/O and the Kotlin standard library. Both are small libraries with strong backwards-compatibility.

This answer solved my problem. I put okhttp and okio on server, but missed kotlin-stdlib.

**Comment by davidyscott** [comment]
Hi folks!
I just ran into this issue as well, but I'm afraid I don't understand the solution.  I tried adding the kotlin jvm plugin to my Gradle build, but that doesn't seem to help.

@yschimke could you please explain what you mean by

> bundling some dependencies without using gradle or maven metadata

?

**Comment by yschimke** [comment]
If you have a valid classpath from gradle or maven and are using a consistent version of OkHttp you probably wouldn't see this exception.

So I'd check that first. There likely isn't any fix for OkHttp project. It's most likely something that requires analysing your projects dependencies to solve.

**Comment by davidyscott** [comment]
@yschimke  Interesting.  So I was able to get past this problem by adding

```runtime group: 'org.jetbrains.kotlin', name: 'kotlin-stdlib-jdk8', version: '1.3.72'```

to my build.gradle, but it sounds like you're saying that shouldn't be necessary?

**Comment by yschimke** [comment]
There is something else going on. If you have a repro you can share I can take a look.

**Comment by davidyscott** [comment]
@yschimke Thanks!!  It's a personal project but it's pretty rough still, so I just invited you to the repo.  There's only one test case (rough, as I mentioned...), easy to repro by trying to run it.

**Comment by davidyscott** [comment]
Interesting, so adding the okio dependency instead of the kotlin-stdlib dependency works.  But I'm not directly using anything from okio, so that's why I didn't have it before.

(Anyway, onto the next issue... whee)

**Comment by davidyscott** [comment]
Oh ok, it's all caused by exactly what you said...  thanks, spring, for transitively including okhttp 3.14.8.  Thanks again @yschimke !!
