### ISSUE TITLE
Warning: Long monitor contention with owner Thread-6

### ISSUE THREAD

**Issue by boyfox** [square/okhttp#5306]
OkHttp initializing:

    OkHttpClient mHttpClient = new OkHttpClient.Builder()
        .readTimeout(20, TimeUnit.SECONDS)
        .connectTimeout(20, TimeUnit.SECONDS)
        .writeTimeout(20, TimeUnit.SECONDS)
        .addInterceptor(chain -> {
            Request request = chain.request().newBuilder().addHeader("Locale", LocaleRepo.getLocaleShortName()).build();
                    return chain.proceed(request);
                })
                .build();
        AndroidNetworking.initialize(getApplicationContext(), mHttpClient);
        AndroidNetworking.setParserFactory(new GsonParserFactory(appGson));

I have the following warning in log:

	2019-07-25 12:11:35.347 29215-29456/uz.myapp.store W/z.myapp.stor: Long monitor contention with owner Thread-6 (29455) at boolean java.io.UnixFileSystem.checkAccess(java.io.File, int)(UnixFileSystem.java:251) waiters=0 in okhttp3.internal.cache.DiskLruCache$Snapshot okhttp3.internal.cache.DiskLruCache.get(java.lang.String) for 6.366s
	2019-07-25 12:11:35.350 29215-29456/uz.myapp.store W/z.myapp.stor: Current owner stack:
	2019-07-25 12:11:35.350 29215-29456/uz.myapp.store W/z.myapp.stor:     at okhttp3.Cache.get(Cache.java:208)
	2019-07-25 12:11:35.350 29215-29456/uz.myapp.store W/z.myapp.stor:     at okhttp3.Cache$1.get(Cache.java:145)
	2019-07-25 12:11:35.350 29215-29456/uz.myapp.store W/z.myapp.stor:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:54)
	2019-07-25 12:11:35.350 29215-29456/uz.myapp.store W/z.myapp.stor:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	2019-07-25 12:11:35.350 29215-29456/uz.myapp.store W/z.myapp.stor:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	2019-07-25 12:11:35.350 29215-29456/uz.myapp.store W/z.myapp.stor:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	2019-07-25 12:11:35.350 29215-29456/uz.myapp.store W/z.myapp.stor:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	2019-07-25 12:11:35.350 29215-29456/uz.myapp.store W/z.myapp.stor:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	2019-07-25 12:11:35.350 29215-29456/uz.myapp.store W/z.myapp.stor:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	2019-07-25 12:11:35.350 29215-29456/uz.myapp.store W/z.myapp.stor:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	2019-07-25 12:11:35.350 29215-29456/uz.myapp.store W/z.myapp.stor:     at com.androidnetworking.interceptors.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:221)
	2019-07-25 12:11:35.350 29215-29456/uz.myapp.store W/z.myapp.stor:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	2019-07-25 12:11:35.350 29215-29456/uz.myapp.store W/z.myapp.stor:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	2019-07-25 12:11:35.350 29215-29456/uz.myapp.store W/z.myapp.stor:     at uz.myapp.store.MyApp.lambda$initNetworkServices$0(MyApp.java:105)
	2019-07-25 12:11:35.350 29215-29456/uz.myapp.store W/z.myapp.stor:     at uz.myapp.store.-$$Lambda$MyApp$hlKbrnUSpv3x_1XvrLRIEglXFdU.intercept(lambda:-1)
	2019-07-25 12:11:35.350 29215-29456/uz.myapp.store W/z.myapp.stor:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	2019-07-25 12:11:35.350 29215-29456/uz.myapp.store W/z.myapp.stor:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	2019-07-25 12:11:35.351 29215-29456/uz.myapp.store W/z.myapp.stor:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:250)
	2019-07-25 12:11:35.351 29215-29456/uz.myapp.store W/z.myapp.stor:     at okhttp3.RealCall.execute(RealCall.java:93)
	2019-07-25 12:11:35.351 29215-29456/uz.myapp.store W/z.myapp.stor:     at com.androidnetworking.internal.InternalNetworking.performSimpleRequest(InternalNetworking.java:117)
	2019-07-25 12:11:35.351 29215-29456/uz.myapp.store W/z.myapp.stor:     at com.androidnetworking.internal.InternalRunnable.executeSimpleRequest(InternalRunnable.java:70)
	2019-07-25 12:11:35.351 29215-29456/uz.myapp.store W/z.myapp.stor:     at com.androidnetworking.internal.InternalRunnable.run(InternalRunnable.java:55)
	2019-07-25 12:11:35.351 29215-29456/uz.myapp.store W/z.myapp.stor:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:458)
	2019-07-25 12:11:35.351 29215-29456/uz.myapp.store W/z.myapp.stor:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	2019-07-25 12:11:35.351 29215-29456/uz.myapp.store W/z.myapp.stor:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	2019-07-25 12:11:35.351 29215-29456/uz.myapp.store W/z.myapp.stor:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	2019-07-25 12:11:35.351 29215-29456/uz.myapp.store W/z.myapp.stor:     at com.androidnetworking.core.PriorityThreadFactory$1.run(PriorityThreadFactory.java:47)
	2019-07-25 12:11:35.351 29215-29456/uz.myapp.store W/z.myapp.stor:     at java.lang.Thread.run(Thread.java:764)

**Comment by yschimke** [comment]
Can you post your issue to stackoverflow.  Unless you can provide a reproducible test case there isn't much we can do to help here.

**Comment by yschimke** [comment]
Closing, as I don't think there is much we can do to help, nor clear evidence that it is a bug instead of a usage problem.  If you link back to your stackoverflow question, then someone else hitting the same problem can follow along there.
