### ISSUE TITLE
java.net.BindException: Address already in use: connect on HTTP Proxies

### ISSUE THREAD

**Issue by mcjp78** [square/okhttp#5313]
Hi all,
I'm encountering a bind error whenever I use a single rotating HTTP Proxies with a high amount of threads (800).

The error comes in at about 10-16k requests to the same proxy, which is interesting because as far as I can tell, HTTP Proxy sockets are constructed the same way as normal no proxy sockets.

I'm using SmartProxy as a proxy solution right now and it happens under them, but should happen with any provider or a Squid server.

The full Stacktrace is:
```
at java.base/java.net.PlainSocketImpl.waitForConnect(Native Method)
	at java.base/java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:107)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
	at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:126)
	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:268)
	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:234)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:170)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
	at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at io.kekr.core.base.Kekr$launchCheck$1$invokeSuspend$$inlined$-addInterceptor$1.intercept(Interceptor.kt:82)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
	at okhttp3.RealCall.execute(RealCall.kt:66)
	at io.kekr.core.connection.OkHttpHelperKt$await$2$1.invokeSuspend(OkHttpHelper.kt:56)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
```

Using OkHttp 4.0.1 but also happens on 3.14.0

Thanks!

**Comment by mcjp78** [comment]
Update:

I found the exact error. SmartProxy uses a session based system, so every `Proxy Authenticator` instance has to be different. This makes every `Address` distinct, so OkHttp cannot pool connections and we wind up with this error. I was using Proxy Authenticator as a backup authentication mechanism if for whatever reason my `Interceptor` failed. Removing that fixes the issue, had to look at okhttp code first.

I would document this somewhere as it could be irritating for someone in my same position.

**Comment by yschimke** [comment]
This is a better question for stackoverflow.

For now, I guess limit concurrency.  But it seems like this problem exists outside of OkHttp, just by usage.

**Comment by swankjesse** [comment]
@mcjp78 which docs did you read prior to encountering this? We wanna put documentation where it'll be useful!

**Comment by mcjp78** [comment]
I read the Connection Pool documentation, and then had to take a peek at the Address.kt class and the .equals() method to find it wouldn't pool.
Not really sure where the best place to put this info is.
I think this is fixable by allowing connections to the same server but different authenticators to pool, not sure if this is totally possible but I'm assuming it is.

**Comment by mcjp78** [comment]
Oh and limiting concurrency won't fix the issue. Windows can't close and reuse TCP connections for two minutes. You would be able to execute 5-7k requests but then I suspect it would fail. I tested this and it seemed accurate

**Comment by mcjp78** [comment]
Thinking about it for a sec, simply removing the `Authenticator` equality check in `Address#equals` should do the trick.

**Comment by yschimke** [comment]
I don't think we should remove it from `Address#equals` because that already isn't the complete story.  equals is used for the quick path, but we do a slower second path to look for connection coalescing opportunities.

If you look at both `Address#equalsNonHost` and `RealConnection#isEligible`, you can see the logic.

But it isn't clear to me that OkHttp can know that proxy auth changing doesn't taint the connection.  So I think OkHttp is doing the correct thing here.

Just looking into it for smartproxy, I don't follow why you want a different Authenticator?  Can't you use a single Authenticator, but make the logic inside the Authenticator conditional?  potentially split out whatever is different and put it in a payload of the Request tag?

**Comment by mcjp78** [comment]
They have a session control system, so adding `-session` to the proxy username changes the exit ip. I can devise a workaround for it with a conditional authenticator, but it gets very messy very quickly. The only thing that changes in that is the `Proxy-Authentication` header, which when I'm using https i have to control with the Authenticator.

**Comment by mcjp78** [comment]
> I don't think we should remove it from `Address#equals` because that already isn't the complete story. equals is used for the quick path, but we do a slower second path to look for connection coalescing opportunities.
> 
> If you look at both `Address#equalsNonHost` and `RealConnection#isEligible`, you can see the logic.
> 
> But it isn't clear to me that OkHttp can know that proxy auth changing doesn't taint the connection. So I think OkHttp is doing the correct thing here.
> 
> Just looking into it for smartproxy, I don't follow why you want a different Authenticator? Can't you use a single Authenticator, but make the logic inside the Authenticator conditional? potentially split out whatever is different and put it in a payload of the Request tag?

isEligible requires .equalsNonHost to be true, which will never happen because the proxy authenticator's don't equal. No coalescing, no pooling, but nothing differs beyond that.

**Comment by yschimke** [comment]
I’d argue that proxy auth being different could be significant. OkHttp can’t know it’s not.

**Comment by mcjp78** [comment]
It for sure is significant, but how is it significant for connection pooling? I don't see how it modifies anything with regards to that.

**Comment by yschimke** [comment]
Is the proxy send you to different origin servers based on the with credentials.

**Comment by mcjp78** [comment]
> Is the proxy send you to different origin servers based on the with credentials.

The proxy sends via different IPs based on that but no not different origins. I can see how that may be an issue though, pooling wouldn't work right.

In that case, maybe provide a way to force it to pool?

**Comment by swankjesse** [comment]
I don't think this feature request fits our security goals. The downsides of sharing authenticators are many; the upsides are few!
