### ISSUE TITLE
app:transformClassesWithDexBuilderForDevDebug

### ISSUE THREAD

**Issue by jmheart** [square/okhttp#5326]
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:transformClassesWithDexBuilderForDevDebug'.
  okhttp3              : '4.0.1'
   kotlin               : '1.3.41'
  classpath 'com.android.tools.build:gradle:3.4.2'
   gradle 5.1.1

Caused by: com.android.builder.dexing.DexArchiveBuilderException: Failed to process C:\android\android_xxx\app\build\intermediates\transforms\profilers-transform\dev\debug\36.jar
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:909)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.lambda$convertToDexArchive$6(DexArchiveBuilderTransform.java:834)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: com.android.builder.dexing.DexArchiveBuilderException: Error while dexing.
	at com.android.builder.dexing.D8DexArchiveBuilder.getExceptionToRethrow(D8DexArchiveBuilder.java:124)
	at com.android.builder.dexing.D8DexArchiveBuilder.convert(D8DexArchiveBuilder.java:101)
	at com.android.build.gradle.internal.transforms.DexArchiveBuilderTransform.launchProcessing(DexArchiveBuilderTransform.java:904)
	... 6 more
Caused by: java.lang.NullPointerException

**Comment by jmheart** [comment]
Terms of settlement：
![image](https://user-images.githubusercontent.com/10995813/62408887-f7cadb00-b601-11e9-8360-c6d0b0e6bd15.png)
Allows the profilers to track data such as network payloads, application events and object counts, but it might have a minor performance impact on your build speeds.
