### ISSUE TITLE
SSLProtocolException while usinf Retrofit

### ISSUE THREAD

**Issue by gobandoGH** [square/okhttp#5329]
I am trying a Retrofit an android studio implementation on an Android Version 4.4.2, and having the following error:
Failure:javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x4ee7c5b0: Failure in SSL Library, usually a protocol error
error:1407742E:SSL
routines:SSL23_GET_SERVER_HELLO:tlsv1 alert
protocol version (external/openssl/ssl/s23.clnt.c:744 0x4ea4bcfc: 0x0000000)  

and this the Kotlin code:

```
private val retrofit = Retrofit.Builder()
        .baseUrl(BASE_URL)
        .addConverterFactory(ScalarsConverterFactory.create())
        .build()

interface MarsApiService {
    @GET("realestate")
    fun getProperties():
            Call<String>
}

object MarsApi {
    val retrofitService : MarsApiService by lazy {
        retrofit.create(MarsApiService::class.java)
    }
}
```

Appreciate highly your help
Thanks

**Comment by yschimke** [comment]
Can you provide more detail on version?  This is not actionable as is.

OkHttp is now Android 5+

> The OkHttp 3.12.x branch supports Android 2.3+ (API level 9+) and Java 7+. These platforms lack support for TLS 1.2 and should not be used. But because upgrading is difficult we will backport critical fixes to the 3.12.x branch through December 31, 2020.

https://medium.com/square-corner-blog/okhttp-3-13-requires-android-5-818bb78d07ce

**Comment by gobandoGH** [comment]
Thank you, Yuri,
I implemented a SocketFactory for older APIs to work

Best regards

**Comment by ankitkumar1994** [comment]
I have same problem for two way authentication  but in android version 9 (p) and it is working good in 8 and below.  Please suggest some solutions regarding it asap. Below is the preview of logcat running on android 9 ,this is the exception i am getting.


/SSL onFailure: javax.net.ssl.SSLHandshakeException: Handshake failed
2020-01-20 13:33:55.880 14098-14098/com.rank.bhartiaxa W/System.err: javax.net.ssl.SSLHandshakeException: Handshake failed
2020-01-20 13:33:55.880 14098-14098/com.rank.bhartiaxa W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:286)
2020-01-20 13:33:55.880 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:242)
2020-01-20 13:33:55.880 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:200)
2020-01-20 13:33:55.880 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.connection.RealConnection.buildConnection(RealConnection.java:174)
2020-01-20 13:33:55.880 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:114)
2020-01-20 13:33:55.880 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:196)
2020-01-20 13:33:55.880 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:132)
2020-01-20 13:33:55.881 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:101)
2020-01-20 13:33:55.881 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
2020-01-20 13:33:55.881 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
2020-01-20 13:33:55.881 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
2020-01-20 13:33:55.881 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
2020-01-20 13:33:55.881 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
2020-01-20 13:33:55.881 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
2020-01-20 13:33:55.881 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2020-01-20 13:33:55.881 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
2020-01-20 13:33:55.881 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:120)
2020-01-20 13:33:55.881 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:92)
2020-01-20 13:33:55.881 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:67)
2020-01-20 13:33:55.881 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:179)
2020-01-20 13:33:55.881 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.RealCall$AsyncCall.execute(RealCall.java:129)
2020-01-20 13:33:55.881 14098-14098/com.rank.bhartiaxa W/System.err:     at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
2020-01-20 13:33:55.881 14098-14098/com.rank.bhartiaxa W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
2020-01-20 13:33:55.881 14098-14098/com.rank.bhartiaxa W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
2020-01-20 13:33:55.881 14098-14098/com.rank.bhartiaxa W/System.err:     at java.lang.Thread.run(Thread.java:764)
2020-01-20 13:33:55.882 14098-14098/com.rank.bhartiaxa W/System.err: 	Suppressed: javax.net.ssl.SSLHandshakeException: Handshake failed
2020-01-20 13:33:55.882 14098-14098/com.rank.bhartiaxa W/System.err: 		... 25 more
2020-01-20 13:33:55.882 14098-14098/com.rank.bhartiaxa W/System.err: 	Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x74aa274308: Failure in SSL library, usually a protocol error
2020-01-20 13:33:55.882 14098-14098/com.rank.bhartiaxa W/System.err: error:10000412:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE (external/boringssl/src/ssl/tls_record.cc:592 0x74aa247988:0x00000001)
2020-01-20 13:33:55.882 14098-14098/com.rank.bhartiaxa W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
2020-01-20 13:33:55.882 14098-14098/com.rank.bhartiaxa W/System.err:     at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
2020-01-20 13:33:55.882 14098-14098/com.rank.bhartiaxa W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
2020-01-20 13:33:55.882 14098-14098/com.rank.bhartiaxa W/System.err: 		... 24 more
2020-01-20 13:33:55.883 14098-14098/com.rank.bhartiaxa W/System.err: Caused by: javax.net.ssl.SSLProtocolException: SSL handshake aborted: ssl=0x74aa274308: Failure in SSL library, usually a protocol error
2020-01-20 13:33:55.883 14098-14098/com.rank.bhartiaxa W/System.err: error:10000412:SSL routines:OPENSSL_internal:SSLV3_ALERT_BAD_CERTIFICATE (external/boringssl/src/ssl/tls_record.cc:592 0x74aa248888:0x00000001)
2020-01-20 13:33:55.883 14098-14098/com.rank.bhartiaxa W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
2020-01-20 13:33:55.883 14098-14098/com.rank.bhartiaxa W/System.err:     at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:375)
2020-01-20 13:33:55.883 14098-14098/com.rank.bhartiaxa W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:224)
2020-01-20 13:33:55.883 14098-14098/com.rank.bhartiaxa W/System.err: 	... 24 more
