### ISSUE TITLE
OpenJSSE causes failures in Android connectedTest

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5406]
Hopefully this is just related to tests that eagerly depend on OpenJSSE classes loading without a failure boundary.

But potentially a blocker for releasing 4.2 if it also affects the main code path.

**Comment by yschimke** [comment]
```
09-03 11:32:54.213 11615 12197 W droid.test.tes: Opening an oat file without a class loader. Are you using the deprecated DexFile APIs?
09-03 11:32:55.416 11615 12197 E TestLoader: Could not find class: org.assertj.core.api.JUnitJupiterBDDSoftAssertions
09-03 11:32:55.423 11615 12197 E TestLoader: Could not find class: org.assertj.core.api.JUnitJupiterSoftAssertions
09-03 11:32:55.661 11615 12197 E TestLoader: Could not find class: org.assertj.core.internal.bytebuddy.agent.builder.ResettableClassFileTransformer
09-03 11:32:55.680 11615 12197 E TestLoader: Could not find class: org.assertj.core.internal.bytebuddy.dynamic.loading.NoOpClassFileTransformer
09-03 11:32:56.403 11615 12197 E TestLoader: Could not find class: org.openjsse.com.sun.net.ssl.internal.www.protocol.https.DelegateHttpsURLConnection
09-03 11:32:56.404 11615 12197 E TestLoader: Could not find class: org.openjsse.com.sun.net.ssl.internal.www.protocol.https.Handler
09-03 11:32:56.411 11615 12197 E TestLoader: Could not find class: org.openjsse.net.www.protocol.https.Handler
09-03 11:32:56.414 11615 12197 E AndroidRuntime: FATAL EXCEPTION: Instr: android.support.test.runner.AndroidJUnitRunner
09-03 11:32:56.414 11615 12197 E AndroidRuntime: Process: okhttp.android.test.test, PID: 11615
09-03 11:32:56.414 11615 12197 E AndroidRuntime: java.lang.NoClassDefFoundError: Failed resolution of: Lsun/net/www/protocol/http/HttpURLConnection;
09-03 11:32:56.414 11615 12197 E AndroidRuntime: 	at java.lang.Class.classForName(Native Method)
09-03 11:32:56.414 11615 12197 E AndroidRuntime: 	at java.lang.Class.forName(Class.java:454)
09-03 11:32:56.414 11615 12197 E AndroidRuntime: 	at android.support.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:72)
09-03 11:32:56.414 11615 12197 E AndroidRuntime: 	at android.support.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
09-03 11:32:56.414 11615 12197 E AndroidRuntime: 	at android.support.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:789)
09-03 11:32:56.414 11615 12197 E AndroidRuntime: 	at android.support.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:539)
09-03 11:32:56.414 11615 12197 E AndroidRuntime: 	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:382)
09-03 11:32:56.414 11615 12197 E AndroidRuntime: 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
09-03 11:32:56.414 11615 12197 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "sun.net.www.protocol.http.HttpURLConnection" on path: DexPathList[[zip file "/data/app/okhttp.android.test.test-XpF47yDpA5enm_yaR_aYYg==/base.apk"],nativeLibraryDirectories=[/data/app/okhttp.android.test.test-XpF47yDpA5enm_yaR_aYYg==/lib/x86, /system/lib, /system/product/lib]]
09-03 11:32:56.414 11615 12197 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
09-03 11:32:56.414 11615 12197 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
09-03 11:32:56.414 11615 12197 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
09-03 11:32:56.414 11615 12197 E AndroidRuntime: 	... 8 more
09-03 11:32:56.430  2210  2252 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.stats.service.DropBoxEntryAddedReceiver
09-03 11:32:56.430  2210  2252 W BroadcastQueue: Background execution not allowed: receiving Intent { act=android.intent.action.DROPBOX_ENTRY_ADDED flg=0x10 (has extras) } to com.google.android.gms/.chimera.GmsIntentOperationService$PersistentTrustedReceiver
09-03 11:32:56.505  2210  5600 W ActivityManager: Crash of app okhttp.android.test.test running instrumentation ComponentInfo{okhttp.android.test.test/android.support.test.runner.AndroidJUnitRunner}
```

**Comment by yschimke** [comment]
Device Tests working with just test code changed https://github.com/square/okhttp/pull/5407
