### ISSUE TITLE
toString method is no longer present (or visible), causing runtime exceptions

### ISSUE THREAD

**Issue by jimshowalter** [square/okhttp#5425]
We upgraded to the latest, and now our build fails with:

[2019-09-06T01:15:49.953Z] Caused by: java.lang.NoSuchMethodError: okhttp3.Cookie.toString(Z)Ljava/lang/String;
[2019-09-06T01:15:49.953Z] 	at okhttp3.JavaNetCookieJar.saveFromResponse(JavaNetCookieJar.java:43)
[2019-09-06T01:15:49.953Z] 	at okhttp3.internal.http.HttpHeaders.receiveHeaders(HttpHeaders.kt:207)
[2019-09-06T01:15:49.953Z] 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:86)
[2019-09-06T01:15:49.953Z] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
[2019-09-06T01:15:49.953Z] 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
[2019-09-06T01:15:49.953Z] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
[2019-09-06T01:15:49.953Z] 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
[2019-09-06T01:15:49.953Z] 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
[2019-09-06T01:15:49.953Z] 	at okhttp3.RealCall.execute(RealCall.kt:66)
[2019-09-06T01:15:49.953Z] 	at com.blackducksoftware.integration.hub.rest.CredentialsRestConnection.clientAuthenticate(CredentialsRestConnection.java:86)
[2019-09-06T01:15:49.953Z] 	at com.blackducksoftware.integration.hub.rest.RestConnection.connect(RestConnection.java:128)
[2019-09-06T01:15:49.953Z] 	at com.blackducksoftware.integration.hub.rest.RestConnection.handleExecuteClientCall(RestConnection.java:350)
[2019-09-06T01:15:49.953Z] 	at com.blackducksoftware.integration.hub.rest.RestConnection.handleExecuteClientCall(RestConnection.java:317)
[2019-09-06T01:15:49.953Z] 	at com.blackducksoftware.integration.hub.request.HubRequest.executePost(HubRequest.java:85)
[2019-09-06T01:15:49.953Z] 	at com.blackducksoftware.integration.hub.api.bom.BomImportRequestService.importBomFile(BomImportRequestService.java:55)
[2019-09-06T01:15:49.953Z] 	at com.blackducksoftware.integration.hub.buildtool.BuildToolHelper.deployHubOutput(BuildToolHelper.java:71)
[2019-09-06T01:15:49.953Z] 	at com.blackducksoftware.integration.gradle.task.BuildBomTask.deployHubBDIO(BuildBomTask.java:240)
[2019-09-06T01:15:49.953Z] 	at com.blackducksoftware.integration.gradle.task.BuildBomTask.performTask(BuildBomTask.java:153)
[2019-09-06T01:15:49.953Z] 	at com.blackducksoftware.integration.gradle.task.BuildBomTask.task(BuildBomTask.java:130)
[2019-09-06T01:15:49.953Z] 	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:103)

We don't see in the release notes anything saying that method has been removed.

Can you put it back? If not, we can't upgrade to your latest, because we need to run blackduck until we replace it (long process).

**Comment by yschimke** [comment]
Presumably you are mixing a 3.14 version of JavaNetCookieJar from okhttp-httpurlconnection with 4.x of okhttp.
