### ISSUE TITLE
Mockwebserver can't serve in AndroidTest in Dynamic Feature Module

### ISSUE THREAD

**Issue by BugsBunnyBR** [square/okhttp#5430]
Ok, so this is the scenario.
On **master** branch with AndroidTest in the "app" module, the tests are ok.
On **delivery** branch where I migrated "charts" module to use dynamic feature delivery, MockWebserver always fails to serve, so some tests fail.

I know you will ask a minimal repro project, but this is what I can offer
https://github.com/BugsBunnyBR/bit-chain/tree/delivery

The tests
`should_show_card_title_and_subtitle` and `should_show_try_again_alert_and_try_again` are failing as they expect the request to be served with success.

Error log:
```
09-07 20:16:51.149  6736  6785 D OkHttp  : --> GET http://localhost:39527/market-price
09-07 20:16:51.149  6736  6785 D OkHttp  : --> END GET
09-07 20:16:51.203  2022  2046 W InputReader: Device has associated, but no associated display id.
09-07 20:16:51.203  2022  2046 I chatty  : uid=1000(system) android.anim identical 8 lines
09-07 20:16:51.203  2022  2046 W InputReader: Device has associated, but no associated display id.
09-07 20:16:51.214  6736  6736 D LifecycleMonitor: Lifecycle status change: br.com.bit.chain.charts.presentation.ChartActivity@a638679 in: CREATED
09-07 20:16:51.218  6736  6736 D LifecycleMonitor: Lifecycle status change: br.com.bit.chain.charts.presentation.ChartActivity@a638679 in: STARTED
09-07 20:16:51.221  6736  6736 D LifecycleMonitor: Lifecycle status change: br.com.bit.chain.charts.presentation.ChartActivity@a638679 in: RESUMED
09-07 20:16:51.254  2022  4489 I WifiService: releaseWifiLock uid=10095
09-07 20:16:51.293  1746  1746 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
09-07 20:16:51.304  1746  1746 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
09-07 20:16:51.311  1746  2985 D gralloc_ranchu: gralloc_alloc: Creating ashmem region of size 8298496
09-07 20:16:51.335  6736  6780 D EGL_emulation: eglMakeCurrent: 0xf2e7f8e0: ver 3 0 (tinfo 0xebba7cb0)
09-07 20:16:51.448  2022  2050 I ActivityTaskManager: Displayed br.com.bit.chain.dev/br.com.bit.chain.charts.presentation.ChartActivity: +529ms
09-07 20:16:51.522  6736  6768 W m.bit.chain.de: Accessing hidden method Lsun/misc/Unsafe;->compareAndSwapObject(Ljava/lang/Object;JLjava/lang/Object;Ljava/lang/Object;)Z (greylist, linking, allowed)
09-07 20:16:51.531  3058  3186 D EGL_emulation: eglMakeCurrent: 0xebbc36e0: ver 3 0 (tinfo 0xc3ba99a0)
09-07 20:16:51.580  2593  3239 W GCoreFlp: No location to return for getLastLocation()
09-07 20:16:51.592  2593  6814 I PlaceInferenceEngine: [anon] Changed inference mode: 0
09-07 20:16:51.600  2473  2870 D EGL_emulation: eglMakeCurrent: 0xebb75180: ver 3 0 (tinfo 0xebc564d0)
09-07 20:16:51.607  2593  2593 I GeofencerStateMachine: removeGeofences: removeRequest=RemoveGeofencingRequest[REMOVE_BY_PENDING_INTENT pendingIntent=PendingIntent[creatorPackage=com.google.android.gms], packageName=com.google.android.gms]
09-07 20:16:51.618  2593  2593 I GeofencerStateMachine: removeGeofences: removeRequest=RemoveGeofencingRequest[REMOVE_BY_PENDING_INTENT pendingIntent=PendingIntent[creatorPackage=com.google.android.gms], packageName=com.google.android.gms]
09-07 20:16:51.631  2593  3239 W GCoreFlp: No location to return for getLastLocation()
09-07 20:16:51.646  3058  6418 I PBSessionCacheImpl: Deleted sessionId[13450794126119140] from persistence.
09-07 20:16:51.646  2022  2032 I system_server: NativeAlloc concurrent copying GC freed 44509(2450KB) AllocSpace objects, 9(260KB) LOS objects, 32% free, 12MB/18MB, paused 89us total 857.946ms
09-07 20:16:51.663  3058  3192 W SearchServiceCore: Abort, client detached.
09-07 20:16:51.759  2022  2838 W AppOps  : Noting op not finished: uid 10095 pkg com.google.android.gms code 79 time=1567898205754 duration=0
09-07 20:16:51.773  2022  2838 W AppOps  : Noting op not finished: uid 10095 pkg com.google.android.gms code 79 time=1567898211759 duration=0
09-07 20:16:51.776  2022  2838 W AppOps  : Noting op not finished: uid 10095 pkg com.google.android.gms code 41 time=1567898205542 duration=0
09-07 20:16:51.793  2022  2838 W AppOps  : Noting op not finished: uid 10105 pkg com.google.android.googlequicksearchbox code 79 time=1567898145009 duration=0
09-07 20:16:51.919  2593  5320 I ctxmgr  : [ProducerStatusImpl] updateStateForNewContextData: inactive, contextName=7 [CONTEXT service_id=47 ]
09-07 20:16:51.943  2593  3239 W GCoreFlp: No location to return for getLastLocation()
09-07 20:16:51.982  2022  2838 W AppOps  : Noting op not finished: uid 10095 pkg com.google.android.gms code 79 time=1567898211773 duration=0
09-07 20:16:51.995  2022  4489 W AppOps  : Noting op not finished: uid 10095 pkg com.google.android.gms code 79 time=1567898211983 duration=0
09-07 20:16:52.037  2593  3239 I chatty  : uid=10095(com.google.android.gms) FlpThread identical 2 lines
09-07 20:16:52.038  2593  3239 W GCoreFlp: No location to return for getLastLocation()
09-07 20:16:52.041  2593  6814 I Places  : ?: PlacesBleScanner start() with priority 2
09-07 20:16:52.042  2593  6814 I PlaceInferenceEngine: [anon] Changed inference mode: 1
09-07 20:16:52.098  2022  4489 I WifiService: acquireWifiLock uid=10095 lockMode=2
09-07 20:16:52.100  2593  2593 E BeaconBle: Missing BluetoothAdapter
09-07 20:16:52.100  2593  2593 I BeaconBle: BLE 'KK+' software access layer enabled
09-07 20:16:52.203  2593  3239 W GCoreFlp: No location to return for getLastLocation()
09-07 20:16:52.241  2022  4489 W AppOps  : Noting op not finished: uid 10095 pkg com.google.android.gms code 79 time=1567898211995 duration=0
09-07 20:16:52.255  2022  4489 I WifiService: releaseWifiLock uid=10095
09-07 20:16:52.270  2022  4489 W AppOps  : Noting op not finished: uid 10095 pkg com.google.android.gms code 79 time=1567898212241 duration=0
09-07 20:16:52.278  2593  2593 I BeaconBle: Client requested scan, settings=BleSettings [scanMode=ZERO_POWER, callbackType=ALL_MATCHES, reportDelayMillis=0, 1 filters, 0 clients, callingClientName=Places]
09-07 20:16:52.286  2593  2593 I BeaconBle: Scan : No clients left, canceling alarm.
09-07 20:16:52.287  2593  2593 E BeaconBle: Scan couldn't start for Places
09-07 20:16:52.287  2593  2593 W Places  : BLE failure while scanning - code 5
09-07 20:16:52.386  2022  4489 W AppOps  : Noting op not finished: uid 10095 pkg com.google.android.gms code 79 time=1567898212270 duration=0
09-07 20:16:52.390  2022  4489 W AppOps  : Noting op not finished: uid 10095 pkg com.google.android.gms code 79 time=1567898212386 duration=0
09-07 20:16:52.408  2022  4489 W AppOps  : Noting op not finished: uid 10095 pkg com.google.android.gms code 79 time=1567898212390 duration=0
09-07 20:16:52.410  2022  4489 W AppOps  : Noting op not finished: uid 10095 pkg com.google.android.gms code 79 time=1567898212408 duration=0
09-07 20:16:52.427  2022  4489 W AppOps  : Noting op not finished: uid 10105 pkg com.google.android.googlequicksearchbox code 79 time=1567898211793 duration=0
09-07 20:16:53.212  2473  3124 E ActivityThread: Failed to find provider info for com.google.android.apps.wellbeing.api
09-07 20:16:53.688  3098  3098 I Finsky  : [2] com.google.android.finsky.scheduler.JobSchedulerEngine$PhoneskyJobSchedulerJobService.onStartJob(3): onJobSchedulerWakeup with jobId 9005
09-07 20:16:53.689  3098  3098 I Finsky  : [2] rsl.a(22): Scheduling fallback job with id: 9034, and delay: 43200000 ms
09-07 20:16:53.691  3098  3098 I Finsky  : [2] rsl.a(5): Scheduling fallback in 64799999 (absolute: 67892446)
09-07 20:16:53.738  3098  3098 I Finsky  : [2] rsw.handleMessage(9): DeviceState: DeviceState{currentTime=1567898213732, isCharging=false, isIdle=false, netAny=true, netNotRoaming=true, netUnmetered=true, batteryPercent=100.0}
09-07 20:16:53.742  3098  6675 I Finsky  : [307] rui.b(7): Jobs in database: 1-1337 3-4 12-1 24-77777777 26-1414141414 
09-07 20:16:53.760  3098  3098 I Finsky  : [2] rsp.a(22): Running job: 12-1
09-07 20:16:53.761  3098  3098 I Finsky  : [2] com.google.android.finsky.contentsync.ContentSyncJob.a(19): ContentSyncJob started
09-07 20:16:53.761  3098  3098 I Finsky  : [2] rsw.handleMessage(101): RunningQueue size: 1, PendingQueue size: 0
09-07 20:16:53.761  3098  3098 I Finsky  : [2] rsw.handleMessage(110): Running queue: 12-1 
09-07 20:16:53.947  3098  6822 I Finsky  : [314] ebw.a(14): Completed 0 account content syncs with 0 successful.
09-07 20:16:53.947  3098  3098 I Finsky  : [2] com.google.android.finsky.contentsync.ContentSyncJob.a(17): Installation state replication succeeded.
09-07 20:16:53.947  3098  3098 I Finsky  : [2] ruf.a(28): jobFinished: 12-1. TimeElapsed: 188ms.
09-07 20:16:53.947  3098  3098 I Finsky  : [2] rsp.c(6): Job 12-1 finished. Not rescheduling.
09-07 20:16:53.948  3098  3098 I Finsky  : [2] rsw.handleMessage(101): RunningQueue size: 0, PendingQueue size: 0
09-07 20:16:53.948  3098  3098 I Finsky  : [2] rsw.handleMessage(48): Executor finished
09-07 20:16:53.984  3098  3098 I Finsky  : [2] rui.b(7): Jobs in database: 1-1337 3-4 24-77777777 26-1414141414 
09-07 20:16:53.985  3098  3098 I Finsky  : [2] rrm.a(59): ConstraintMapping: 24-77777777,  -> L: 0ms, D: 76759303ms, C: false, I: true, N: 0
09-07 20:16:53.985  3098  3098 I Finsky  : [2] rrm.a(59): ConstraintMapping: 1-1337,  -> L: 29119075ms, D: 72319075ms, C: false, I: false, N: 1
09-07 20:16:53.985  3098  3098 I Finsky  : [2] rrm.a(59): ConstraintMapping: 3-4,  -> L: 0ms, D: 83355079ms, C: true, I: true, N: 2
09-07 20:16:53.987  3098  3098 I Finsky  : [2] rrm.a(59): ConstraintMapping: 26-1414141414,  -> L: 38060938ms, D: 38960938ms, C: false, I: false, N: 0
09-07 20:16:53.996  3098  3098 I Finsky  : [2] rtr.a(45): Cancelling existing jobscheduler jobs: 9004 9006 9007 
09-07 20:16:53.996  3098  3098 I Finsky  : [2] rtr.a(15): Throttling wakeup for job 9000 (expected to run in 0 ms) due to recent wakeup
09-07 20:16:53.996  3098  3098 I Finsky  : [2] rtr.a(1): Scheduling job Id: 9000, L: 30000, D: 76759303, C: false, I: true, N: 0
09-07 20:16:53.997  3098  3098 I Finsky  : [2] rtr.a(1): Scheduling job Id: 9001, L: 29119075, D: 72319075, C: false, I: false, N: 1
09-07 20:16:53.997  3098  3098 I Finsky  : [2] rtr.a(15): Throttling wakeup for job 9002 (expected to run in 0 ms) due to recent wakeup
09-07 20:16:53.997  3098  3098 I Finsky  : [2] rtr.a(1): Scheduling job Id: 9002, L: 30000, D: 83355079, C: true, I: true, N: 2
09-07 20:16:53.998  3098  3098 I Finsky  : [2] rtr.a(1): Scheduling job Id: 9003, L: 38060938, D: 38960938, C: false, I: false, N: 0
09-07 20:16:55.582  2022  4241 W AppOps  : Noting op not finished: uid 10095 pkg com.google.android.gms code 41 time=1567898211776 duration=0
09-07 20:16:56.531  6736  6736 W IdlingPolicy: These resources are not idle: [RxJava 2.x IO Scheduler]
09-07 20:16:56.737  2593  3239 W GCoreFlp: No location to return for getLastLocation()
09-07 20:16:56.834  2022  2323 W AppOps  : Noting op not finished: uid 10095 pkg com.google.android.gms code 79 time=1567898212410 duration=0
09-07 20:16:56.837  2022  2838 W AppOps  : Noting op not finished: uid 10095 pkg com.google.android.gms code 79 time=1567898216834 duration=0
09-07 20:16:56.839  2593  3239 W GCoreFlp: No location to return for getLastLocation()
09-07 20:16:56.907  2022  2050 E memtrack: Couldn't load memtrack module
09-07 20:16:56.907  2022  2050 W android.os.Debug: failed to get memory consumption info: -1
09-07 20:16:56.927  2593  6814 I Places  : ?: PlacesBleScanner stop()
09-07 20:16:56.928  2593  2593 I BeaconBle: Scan : No clients left, canceling alarm.
09-07 20:16:56.928  2593  2593 I BeaconBle: Scan canceled successfully.
09-07 20:16:56.943  2593  6814 I PlaceInferenceEngine: [anon] Changed inference mode: 0
09-07 20:16:56.947  2593  3239 W GCoreFlp: No location to return for getLastLocation()
09-07 20:16:57.001  2593  2593 I GeofencerStateMachine: removeGeofences: removeRequest=RemoveGeofencingRequest[REMOVE_BY_PENDING_INTENT pendingIntent=PendingIntent[creatorPackage=com.google.android.gms], packageName=com.google.android.gms]
09-07 20:16:57.002  2593  3239 W GCoreFlp: No location to return for getLastLocation()
09-07 20:16:57.435  2022  2323 W AppOps  : Noting op not finished: uid 10095 pkg com.google.android.gms code 79 time=1567898216837 duration=0
09-07 20:16:57.450  2022  2323 W AppOps  : Noting op not finished: uid 10095 pkg com.google.android.gms code 79 time=1567898217435 duration=0
09-07 20:16:57.706  2022  4241 D WificondControl: Scan result ready event
09-07 20:17:00.674  2022  2323 W AppOps  : Noting op not finished: uid 10095 pkg com.google.android.gms code 41 time=1567898215582 duration=0
09-07 20:17:01.224  6736  6785 D OkHttp  : <-- HTTP FAILED: java.net.SocketTimeoutException: timeout
09-07 20:17:01.248  6736  6736 W System.err: java.net.SocketTimeoutException: timeout
09-07 20:17:01.249  6736  6736 W System.err: 	at okio.SocketAsyncTimeout.newTimeoutException(Okio.kt:159)
09-07 20:17:01.249  6736  6736 W System.err: 	at okio.AsyncTimeout.exit$jvm(AsyncTimeout.kt:203)
09-07 20:17:01.249  6736  6736 W System.err: 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:163)
09-07 20:17:01.249  6736  6736 W System.err: 	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:349)
09-07 20:17:01.249  6736  6736 W System.err: 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:222)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.kt:210)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:181)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:105)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:82)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:37)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:215)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
09-07 20:17:01.249  6736  6736 W System.err: 	at okhttp3.RealCall.execute(RealCall.kt:66)
09-07 20:17:01.249  6736  6736 W System.err: 	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
09-07 20:17:01.249  6736  6736 W System.err: 	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
09-07 20:17:01.250  6736  6736 W System.err: 	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.Single.subscribe(Single.java:3603)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.single.SingleMap.subscribeActual(SingleMap.java:34)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.Single.subscribe(Single.java:3603)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.single.SingleFlatMap.subscribeActual(SingleFlatMap.java:36)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.Single.subscribe(Single.java:3603)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.single.SingleCache.subscribeActual(SingleCache.java:65)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.Single.subscribe(Single.java:3603)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmptySingle$SwitchIfEmptyMaybeObserver.onComplete(MaybeSwitchIfEmptySingle.java:95)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.maybe.MaybeCreate$Emitter.onComplete(MaybeCreate.java:118)
09-07 20:17:01.250  6736  6736 W System.err: 	at br.com.bit.chain.charts.data.cache.ChartDataLocalCacheImpl$get$1.subscribe(ChartDataCache.kt:25)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.maybe.MaybeSwitchIfEmptySingle.subscribeActual(MaybeSwitchIfEmptySingle.java:45)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.Single.subscribe(Single.java:3603)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.single.SingleToFlowable.subscribeActual(SingleToFlowable.java:37)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onNext(FlowableFlatMap.java:163)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.flowable.FlowableFromArray$ArraySubscription.fastPath(FlowableFromArray.java:132)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.flowable.FlowableFromArray$BaseArraySubscription.request(FlowableFromArray.java:88)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.flowable.FlowableFlatMap$MergeSubscriber.onSubscribe(FlowableFlatMap.java:115)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.flowable.FlowableFromArray.subscribeActual(FlowableFromArray.java:38)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.flowable.FlowableFlatMapPublisher.subscribeActual(FlowableFlatMapPublisher.java:43)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.flowable.FlowableMap.subscribeActual(FlowableMap.java:35)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.flowable.FlowableDistinctUntilChanged.subscribeActual(FlowableDistinctUntilChanged.java:42)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.Flowable.subscribe(Flowable.java:14918)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.Flowable.subscribe(Flowable.java:14865)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.observable.ObservableFromPublisher.subscribeActual(ObservableFromPublisher.java:31)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
09-07 20:17:01.250  6736  6736 W System.err: 	at io.reactivex.Observable.subscribe(Observable.java:12267)
09-07 20:17:01.251  6736  6736 W System.err: 	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
09-07 20:17:01.251  6736  6736 W System.err: 	at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
09-07 20:17:01.251  6736  6736 W System.err: 	at com.squareup.rx2.idler.DelegatingIdlingResourceScheduler$ScheduledWork.run(DelegatingIdlingResourceScheduler.java:141)
09-07 20:17:01.251  6736  6736 W System.err: 	at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
09-07 20:17:01.251  6736  6736 W System.err: 	at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
09-07 20:17:01.251  6736  6736 W System.err: 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-07 20:17:01.251  6736  6736 W System.err: 	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
09-07 20:17:01.251  6736  6736 W System.err: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
09-07 20:17:01.251  6736  6736 W System.err: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
09-07 20:17:01.251  6736  6736 W System.err: 	at java.lang.Thread.run(Thread.java:919)
09-07 20:17:01.255  6736  6736 W System.err: Caused by: java.net.SocketTimeoutException: Read timed out
09-07 20:17:01.255  6736  6736 W System.err: 	at java.net.SocketInputStream.socketRead0(Native Method)
09-07 20:17:01.255  6736  6736 W System.err: 	at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
09-07 20:17:01.255  6736  6736 W System.err: 	at java.net.SocketInputStream.read(SocketInputStream.java:176)
09-07 20:17:01.255  6736  6736 W System.err: 	at java.net.SocketInputStream.read(SocketInputStream.java:144)
09-07 20:17:01.255  6736  6736 W System.err: 	at okio.InputStreamSource.read(Okio.kt:102)
09-07 20:17:01.255  6736  6736 W System.err: 	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:159)
09-07 20:17:01.255  6736  6736 W System.err: 	... 74 more
```

**Comment by yschimke** [comment]
It feels like you are asking us to debug your PR in an IDE rather than a colleague.  This doesn't feel like an appropriate for for this issue list or Stackoverflow. It's not complete in that its not just the PR, but you need to see the rest of the code.  I can't even see where you call the enqueue methods.

A good read on http://sscce.org/

**Comment by BugsBunnyBR** [comment]
@yschimke , which PR? I have no PR here.
I am asking the developers to take a look into the issue that I found. Yes, it is in my project, but I am confident that it is something inside mockwebserver and not in my code, that is why I opened this issue. 
I have provided tests method names in the issue description, so how you can't find the
 enqueue call? Here https://github.com/BugsBunnyBR/bit-chain/blob/delivery/charts/src/androidTest/java/br/com/bit/chain/tests/charts/ChartActivityTest.kt#L109 that is one of the methods. Clone the project, open in Android Studio and try to run the test.
