### ISSUE TITLE
LoggingEventListener triggers failures in Android MockWebServer response

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5464]
I suspect only an issue if we look at the handshake certificates on Android with the MockWebServer.

```
07:13:09 V/InstrumentationResultParser: There was 1 failure:
07:13:09 V/InstrumentationResultParser: 1) testMockWebserverRequest(okhttp.android.test.OkHttpTest)
07:13:09 V/InstrumentationResultParser: javax.net.ssl.SSLPeerUnverifiedException
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.platform.AndroidPlatform$AndroidCertificateChainCleaner.clean(AndroidPlatform.kt:189)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:377)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:70)
07:13:09 V/InstrumentationResultParser: at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
07:13:09 V/InstrumentationResultParser: at okhttp3.Handshake.peerCertificates(Unknown Source:7)
07:13:09 V/InstrumentationResultParser: at okhttp3.Handshake.toString(Handshake.kt:127)
07:13:09 V/InstrumentationResultParser: at java.lang.String.valueOf(String.java:2924)
07:13:09 V/InstrumentationResultParser: at java.lang.StringBuilder.append(StringBuilder.java:132)
07:13:09 V/InstrumentationResultParser: at okhttp3.logging.LoggingEventListener.secureConnectEnd(LoggingEventListener.kt:76)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:311)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:178)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
07:13:09 V/InstrumentationResultParser: at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:192)
07:13:09 V/InstrumentationResultParser: at okhttp3.RealCall.execute(RealCall.kt:66)
07:13:09 V/InstrumentationResultParser: at okhttp.android.test.OkHttpTest.testMockWebserverRequest(OkHttpTest.kt:198)
07:13:09 V/InstrumentationResultParser: at java.lang.reflect.Method.invoke(Native Method)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
07:13:09 V/InstrumentationResultParser: at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
07:13:09 V/InstrumentationResultParser: at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
07:13:09 V/InstrumentationResultParser: at android.support.test.internal.runner.junit4.statement.RunBefores.evaluate(RunBefores.java:80)
07:13:09 V/InstrumentationResultParser: at android.support.test.internal.runner.junit4.statement.RunAfters.evaluate(RunAfters.java:61)
07:13:09 V/InstrumentationResultParser: at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:48)
07:13:09 V/InstrumentationResultParser: at org.junit.rules.RunRules.evaluate(RunRules.java:20)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
07:13:09 V/InstrumentationResultParser: at android.support.test.runner.AndroidJUnit4.run(AndroidJUnit4.java:101)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.Suite.runChild(Suite.java:128)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.Suite.runChild(Suite.java:27)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
07:13:09 V/InstrumentationResultParser: at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
07:13:09 V/InstrumentationResultParser: at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
07:13:09 V/InstrumentationResultParser: at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
07:13:09 V/InstrumentationResultParser: at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
07:13:09 V/InstrumentationResultParser: at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:384)
07:13:09 V/InstrumentationResultParser: at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2189)
07:13:09 V/InstrumentationResultParser: Caused by: java.lang.reflect.InvocationTargetException
07:13:09 V/InstrumentationResultParser: at java.lang.reflect.Method.invoke(Native Method)
07:13:09 V/InstrumentationResultParser: at okhttp3.internal.platform.AndroidPlatform$AndroidCertificateChainCleaner.clean(AndroidPlatform.kt:186)
07:13:09 V/InstrumentationResultParser: ... 60 more
07:13:09 V/InstrumentationResultParser: Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
07:13:09 V/InstrumentationResultParser: at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:674)
07:13:09 V/InstrumentationResultParser: at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:551)
07:13:09 V/InstrumentationResultParser: at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:507)
07:13:09 V/InstrumentationResultParser: at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:335)
07:13:09 V/InstrumentationResultParser: at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:113)
07:13:09 V/InstrumentationResultParser: at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:133)
07:13:09 V/InstrumentationResultParser: at java.lang.reflect.Method.invoke(Native Method)
07:13:09 V/InstrumentationResultParser: at android.net.http.X509TrustManagerExtensions.checkServerTrusted(X509TrustManagerExtensions.java:101)
07:13:09 V/InstrumentationResultParser: ... 62 more
07:13:09 V/InstrumentationResultParser: Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
07:13:09 V/InstrumentationResultParser: ... 70 more
```

**Comment by yschimke** [comment]
I'm not sure how serious this is, I suspect not very.  But it is at least a new stacktrace we will see.  Any logger calling Handshake.toString can invoke a clean.

**Comment by yschimke** [comment]
@swankjesse is this expected with self signed certs on Android?

**Comment by swankjesse** [comment]
I don't get this one. Why didn't it validate in the initial handshake?

We should fix our cleaner to catch, log a warning, and return unclean certificates in this case?

**Comment by swankjesse** [comment]
Are we cleaning with different roots than verifying? I assume that's the bug.

**Comment by yschimke** [comment]
I assumed it was because while we now clean at most once, it is only if you use either pinning, or access the cleaned certs. We didn't previously clean if it was enough that the SSL handshake code (Android or JVM) found a valid chain to the known root CA.  And the root CA doesn't need to be in the list provided by the server IIUC.

I'll try to prove we use the same certs for verifying.  I hope it's not a new bug, prefer it to a broken assumption with self signed certs. :)

**Comment by swankjesse** [comment]
The trouble is that this is a verification issue, which shouldn't happen unless the trust roots are different.

**Comment by yschimke** [comment]
I'm pretty sure the cleaner is using the right certificates for the server.

```
09-23 19:50:36.219 20166 21438 W OkHttp  : issuers [CN=localhost]
09-23 19:50:36.324 20166 21438 W OkHttp  : hostname localhost
09-23 19:50:36.327 20166 21438 W OkHttp  : certificates [Certificate:
09-23 19:50:36.329 20166 21438 W OkHttp  :     Data:
09-23 19:50:36.333 20166 21438 W OkHttp  :         Version: 3 (0x2)
09-23 19:50:36.333 20166 21438 W OkHttp  :         Serial Number: 1 (0x1)
09-23 19:50:36.341 20166 21438 W OkHttp  :     Signature Algorithm: ecdsa-with-SHA256
09-23 19:50:36.341 20166 21438 W OkHttp  :         Issuer: CN=localhost
09-23 19:50:36.341 20166 21438 W OkHttp  :         Validity
09-23 19:50:36.341 20166 21438 W OkHttp  :             Not Before: Sep 23 18:50:22 2019 GMT
09-23 19:50:36.341 20166 21438 W OkHttp  :             Not After : Sep 24 18:50:22 2019 GMT
09-23 19:50:36.341 20166 21438 W OkHttp  :         Subject: CN=localhost
09-23 19:50:36.341 20166 21438 W OkHttp  :         Subject Public Key Info:
09-23 19:50:36.342 20166 21438 W OkHttp  :             Public Key Algorithm: id-ecPublicKey
09-23 19:50:36.343 20166 21438 W OkHttp  :                 Public-Key: (256 bit)
09-23 19:50:36.343 20166 21438 W OkHttp  :                 00000000  04 18 af 11 6f 82 90 d5  44 ed f7 f3 f2 98 44 be  |....o...D.....D.|
09-23 19:50:36.344 20166 21438 W OkHttp  :                 00000010  1d 2a bb 55 d3 06 ee 0e  5a 34 91 91 72 0c 60 6b  |.*.U....Z4..r.`k|
09-23 19:50:36.344 20166 21438 W OkHttp  :                 00000020  e8 ec 67 18 4a 89 19 df  d1 25 93 4f da 36 cd 8c  |..g.J....%.O.6..|
09-23 19:50:36.344 20166 21438 W OkHttp  :                 00000030  58 fe 12 69 79 4d 9c d9  30 5f bc 47 ea 78 ff e1  |X..iyM..0_.G.x..|
09-23 19:50:36.345 20166 21438 W OkHttp  :                 00000040  a6                                                |.|
09-23 19:50:36.346 20166 21438 W OkHttp  :         X509v3 extensions:
09-23 19:50:36.347 20166 21438 W OkHttp  :             X509v3 Subject Alternative Name: critical
09-23 19:50:36.347 20166 21438 W OkHttp  :                 DNS:localhost
09-23 19:50:36.347 20166 21438 W OkHttp  :     Signature Algorithm: ecdsa-with-SHA256
09-23 19:50:36.347 20166 21438 W OkHttp  :          30:45:02:20:5b:0d:1b:b1:52:9f:d6:40:8c:89:e3:ef:29:ef:
09-23 19:50:36.347 20166 21438 W OkHttp  :          24:d9:9c:73:7f:8c:f4:39:77:44:12:e7:1a:a9:91:ec:a0:d9:
09-23 19:50:36.348 20166 21438 W OkHttp  :          02:21:00:eb:39:29:76:0f:5c:7b:f8:f6:93:8d:97:c6:9d:d7:
09-23 19:50:36.348 20166 21438 W OkHttp  :          a9:64:94:92:2f:61:3a:b8:74:05:a8:8b:0e:38:4b:35:67
09-23 19:50:36.349 20166 21438 W OkHttp  : ]
```

Compared with a non overridden request's issuers

```
09-23 19:50:36.437 20166 21438 W OkHttp  : issuers [OU=Security Communication RootCA2, O="SECOM Trust Systems CO.,LTD.", C=JP, CN=Starfield Services Root Certificate Authority - G2, O="Starfield Technologies, Inc.", L=Scottsdale, ST=Arizona, C=US, CN=QuoVadis Root CA 3, O=QuoVadis Limited, C=BM, CN=GeoTrust Primary Certification Authority, O=GeoTrust Inc., C=US, CN=SZAFIR ROOT CA2, O=Krajowa Izba Rozliczeniowa S.A., C=PL, CN=QuoVadis Root CA 2, O=QuoVadis Limited, C=BM, CN=E-Tugra Certification Authority, OU=E-Tugra Sertifikasyon Merkezi, O=E-Tuğra EBG Bilişim Teknolojileri ve Hizmetleri A.Ş., L=Ankara, C=TR, CN=EC-ACC, OU=Jerarquia Entitats de Certificacio Catalanes, OU=Vegeu https://www.catcert.net/verarrel (c)03, OU=Serveis Publics de Certificacio, O=Agencia Catalana de Certificacio (NIF Q-0801176-I), C=ES, CN=COMODO ECC Certification Authority, O=COMODO CA Limited, L=Salford, ST=Greater Manchester, C=GB, CN=GeoTrust Universal CA 2, O=GeoTrust Inc., C=US, EMAILADDRESS=info@e-szigno.hu, CN=Microsec e-Szigno Root CA 2009, O=Microsec Ltd., L=Budapest, C=HU, CN=D-TRUST Root Class 3 CA 2 EV 2009, O=D-Trust GmbH, C=DE, CN=AAA Certificate Servic
```

So I'm try to understand what android is doing.

**Comment by yschimke** [comment]
n.b. I haven't gotten the same test to fail for JVM, which uses the project BasicCertificateChainCleaner

**Comment by swankjesse** [comment]
I think this was fixed here: https://github.com/square/okhttp/pull/5511
