### ISSUE TITLE
Android test is broken due to Conscrypt socket support

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5480]
A merge conflict with the AndroidQPlatform and ConscryptTest.  I'll work on the correct fix tomorrow.  I didn't think about what would happen if conscrypt is enabled since AndroidQPlatform is mostly the JDK9 platform code.

**Comment by yschimke** [comment]
Also double import of Platform

**Comment by yschimke** [comment]
```
okhttp.android.test.OkHttpTest > testConscryptRequest[New_Device_API_29(AVD) - 10] FAILED
	java.lang.AssertionError: expected:<h2> but was:<http/1.1>
	at org.junit.Assert.fail(Assert.java:88)
11:26:07 V/InstrumentationResultParser: INSTRUMENTATION_STATUS_CODE: -2
11:26:07 V/InstrumentationResultParser: INSTRUMENTATION_RESULT: stream=
11:26:07 V/InstrumentationResultParser:
11:26:07 V/InstrumentationResultParser: Time: 13.001
11:26:07 V/InstrumentationResultParser: There was 1 failure:
11:26:07 V/InstrumentationResultParser: 1) testConscryptRequest(okhttp.android.test.OkHttpTest)
11:26:07 V/InstrumentationResultParser: java.lang.AssertionError: expected:<h2> but was:<http/1.1>
11:26:07 V/InstrumentationResultParser: at org.junit.Assert.fail(Assert.java:88)
11:26:07 V/InstrumentationResultParser: at org.junit.Assert.failNotEquals(Assert.java:834)
11:26:07 V/InstrumentationResultParser: at org.junit.Assert.assertEquals(Assert.java:118)
11:26:07 V/InstrumentationResultParser: at org.junit.Assert.assertEquals(Assert.java:144)
11:26:07 V/InstrumentationResultParser: at okhttp.android.test.OkHttpTest.testConscryptRequest(OkHttpTest.kt:128)
```

**Comment by yschimke** [comment]
Fixed on this PR https://github.com/square/okhttp/pull/5483
