### ISSUE TITLE
Intellij launch failing because Android classes present

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5490]
android-all makes the Class.forName succeed.

```
    val isSupported: Boolean = try {
      // Trigger an early exception over a fatal error, prefer a RuntimeException over Error.
      Class.forName("com.android.org.conscrypt.OpenSSLSocketImpl")

      // Fail Fast
      check(
          Build.VERSION.SDK_INT >= 21) { "Expected Android API level 21+ but was ${Build.VERSION.SDK_INT}" }

      true
    } catch (_: ClassNotFoundException) {
      false
    }
```

```
java.lang.UnsatisfiedLinkError: 'java.lang.String android.os.SystemProperties.native_get(java.lang.String, java.lang.String)'

	at android.os.SystemProperties.native_get(Native Method)
	at android.os.SystemProperties.get(SystemProperties.java:118)
	at android.os.Build.getString(Build.java:1107)
	at android.os.Build.<clinit>(Build.java:45)
	at android.os.Build$VERSION.<clinit>(Build.java:197)
	at okhttp3.internal.platform.AndroidPlatform.<clinit>(AndroidPlatform.kt:207)
	at okhttp3.internal.platform.Android10Platform.<clinit>(Android10Platform.kt:65)
	at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:200)
	at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:168)
	at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:169)
	at okhttp3.testing.PlatformRule$Companion.getPlatformSystemProperty(PlatformRule.kt:277)
	at okhttp3.testing.PlatformRule.<clinit>(PlatformRule.kt:245)
	at okhttp3.CallTest.<init>(CallTest.java:104)
```

**Comment by yschimke** [comment]
Experimenting with a fix here https://github.com/square/okhttp/pull/5491/files

Advice welcome!
