### ISSUE TITLE
Got NoSuchMethodError after enable proguard

### ISSUE THREAD

**Issue by RuslanSelenium** [square/okhttp#5495]
I used 3.12.3 okhttp(and mockwebserver) version.

When mockserver started all is fine. But when it get some request, it fails:

Caused by: java.lang.NoSuchMethodError: No static method b(Ljava/net/Socket;)Lokio/Source; in class Lb81; or its super classes (declaration of 'b81' appears in /data/app/myapp/base.apk:classes3.dex)
        at okhttp3.mockwebserver.MockWebServer$3.processConnection(MockWebServer.java:513)
        at okhttp3.mockwebserver.MockWebServer$3.execute(MockWebServer.java:443)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
        at java.lang.Thread.run(Thread.java:761)

I add keep rules for this class in proguard, but it doesn't help me. 

So is it a bug or my bad ?

**Comment by RuslanSelenium** [comment]
solved
