### ISSUE TITLE
NullPointerException: realConnectionPool

### ISSUE THREAD

**Issue by palicka** [square/okhttp#5506]
stack trace:
 java.lang.NullPointerException: Attempt to invoke virtual method 'okhttp3.internal.connection.RealConnectionPool okhttp3.internal.Internal.realConnectionPool(okhttp3.ConnectionPool)' on a null object reference
     at okhttp3.internal.connection.Transmitter.<init>(Transmitter.java:81)
     at okhttp3.RealCall.newRealCall(RealCall.java:64)
     at okhttp3.OkHttpClient.newCall(OkHttpClient.java:401)
     at retrofit2.ServiceMethod.toCall(ServiceMethod.java:113)
     at retrofit2.OkHttpCall.createRawCall(OkHttpCall.java:184)
     at retrofit2.OkHttpCall.execute(OkHttpCall.java:167)
     at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:42)
     at io.reactivex.Observable.subscribe(Observable.java:12246)
     at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
     at io.reactivex.Observable.subscribe(Observable.java:12246)
     at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
     at io.reactivex.Single.subscribe(Single.java:3575)
     at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
     at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
     at java.lang.Thread.run(Thread.java:764)

version: latest

we use dagger to initialize okhttp and retrofit instances:

```
    @Provides
    @Singleton
    fun providesRetrofit(gsonConverterFactory: GsonConverterFactory, rxJava2CallAdapterFactory: RxJava2CallAdapterFactory,
                         okHttpClient: OkHttpClient, context: Context): Retrofit =
            Retrofit.Builder().baseUrl(context.getString(R.string.api_endpoint))
                    .addConverterFactory(gsonConverterFactory)
                    .addCallAdapterFactory(rxJava2CallAdapterFactory)
                    .client(okHttpClient)
                    .build()

    @Provides
    @Singleton
    fun providesOkHttpClient(cache: Cache): OkHttpClient {
        val client = OkHttpClient.Builder()
                .cache(cache)
                .connectTimeout(20, TimeUnit.SECONDS)
                .writeTimeout(30, TimeUnit.SECONDS)
                .readTimeout(10, TimeUnit.SECONDS)
                .addInterceptor(HttpLoggingInterceptor().setLevel(HttpLoggingInterceptor.Level.BODY))

        return client.build()
    }

```
bug happens when in single activity app with "do not keep activities" setting in developer options flag turned on and when pick photo intent is executed and then in onActivityResult we try to upload this photo....activity is recreated but okhttp instance is somehow not properly/completely initialised (for test purposes I added 5 seconds delay to wait if it will be initialised, but with no luck, the same error occured.. to sum it up, after reset, it's unusable)

**Comment by swankjesse** [comment]
This is wild. Your `Internal.instance` is null, but that _should_ have been initialized before Retrofit was able to call `OkHttpClient.newCall()`.

**Comment by swankjesse** [comment]
Can you confirm this in a debugger? Put breakpoints on OkHttpClient.java lines 131 and 141 and tell me which hits first.

**Comment by palicka** [comment]
when app first starts , `  Internal.instance = new Internal() `at  line 131 is called, and then  `return connectionPool.delegate;` at line 141 is called.  After photo gallery windows is shown and returned back, when call is made, neither of previous lines are called.. I also checked if injected version of OkHttpClient is the same and it is..

I also noticed another crash (probably the same reason) during  the call that was made right before activity was destroyed.

```
   @Override public RealConnectionPool realConnectionPool(ConnectionPool connectionPool) {
        return connectionPool.delegate;
      }
```
was called but  `Internal.instance` was null, as shown at the picture:
<img width="1040" alt="Screenshot 2019-09-28 at 01 50 03" src="https://user-images.githubusercontent.com/6105846/65808194-0e6d5880-e193-11e9-8a20-0be85a037f3b.png">

and then, the stack trace was:

```
    java.lang.NullPointerException: Attempt to invoke virtual method 'void okhttp3.internal.Internal.apply(okhttp3.ConnectionSpec, javax.net.ssl.SSLSocket, boolean)' on a null object reference
        at okhttp3.internal.connection.ConnectionSpecSelector.configureSecureSocket(ConnectionSpecSelector.java:77)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:329)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
        at okhttp3.RealCall.execute(RealCall.java:81)
```

It's different error, but probably the same problem, so I guess it's not necessary to create another issue for that...

**Comment by swankjesse** [comment]
@palicka very interesting. It’s the same process? I wonder how it became null?!

**Comment by palicka** [comment]
yes, I've checked it, it's the same application process (pid is the same)...

**Comment by swankjesse** [comment]
Can you get a debugger to signal when the field gets nulled out?

**Comment by swankjesse** [comment]
Unclear what action to take on this.
