### ISSUE TITLE
IndexOutOfBoundsException when unverifiedHandshake.peerCertificates().get(0) in Okhttp 3.13.1 

### ISSUE THREAD

**Issue by Malachiasz** [square/okhttp#5558]
I have been testing HTTP2 with Glide with Okhttp, both running on 16 threads. Glide has been downloading images from our server through Charles proxy. All from the same endpoint. We are using:  Okhttp 3.13.1. The crash happened randomly while downloading Nth element.

this line has a problem: 
X509Certificate cert = (X509Certificate) unverifiedHandshake.peerCertificates().get(0)
In below case there was no peerCertificates
```
/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.unitedinternet.portal.android.onlinestorage.gmx.debug, PID: 11010
    java.lang.IndexOutOfBoundsException: Index: 0
        at java.util.Collections$EmptyList.get(Collections.java:4511)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:326)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:283)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:168)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:200)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)

```

**Comment by swankjesse** [comment]
Duplicate! https://github.com/square/okhttp/issues/5029
Upgrade to Java 11.0.3.

**Comment by swankjesse** [comment]
I believe this duplicates #4427.
