### ISSUE TITLE
Crash: Unexpected TLS version: NONE In Android 9.0

### ISSUE THREAD

**Issue by out0fmemory** [square/okhttp#5562]
Hello, 

My Android app use okhttp 3.10.0 for almost 1year, and it is stable.  Just last month, we switch http to https, then many crash occur  In Android 9.0,
blew is the stacktrace,
```
java.lang.IllegalArgumentException Unexpected TLS version NONE
at okhttp3.TlsVersion.forJavaName(SourceFile 53)
at okhttp3.Handshake.get(SourceFile 56)
at okhttp3.internal.connection.RealConnection.connectTls(SourceFile 308)
at okhttp3.internal.connection.RealConnection.establishProtocol(SourceFile 270)
at okhttp3.internal.connection.RealConnection.connect(SourceFile 162)
at okhttp3.internal.connection.StreamAllocation.findConnection(SourceFile 257)
at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(SourceFile 135)
at okhttp3.internal.connection.StreamAllocation.newStream(SourceFile 114)
at okhttp3.internal.connection.ConnectInterceptor.intercept(SourceFile 42)
at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile 147)
at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile 121)
at okhttp3.internal.cache.CacheInterceptor.intercept(SourceFile 93)
at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile 147)
at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile 121)
at okhttp3.internal.http.BridgeInterceptor.intercept(SourceFile 93)
at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile 147)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(SourceFile 126)
at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile 147)
at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile 121)
at com.iflytek.common.lib.net.interceptor.BlcInterceptor.intercept(SourceFile 76)
at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile 147)
at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile 121)
at com.iflytek.common.lib.net.interceptor.BlcInterceptor.intercept(SourceFile 76)
at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile 147)
at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile 121)
at com.iflytek.common.lib.net.interceptor.BlcInterceptor.intercept(SourceFile 76)
at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile 147)
at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile 121)
at com.iflytek.common.lib.net.interceptor.CatchExceptionInterceptor.intercept(SourceFile 23)
at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile 147)
at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile 121)
at com.iflytek.eagleeye.e.c.d.intercept(SourceFile 52)
at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile 147)
at okhttp3.internal.http.RealInterceptorChain.proceed(SourceFile 121)
at okhttp3.RealCall.getResponseWithInterceptorChain(SourceFile 200)
at okhttp3.RealCall$AsyncCall.execute(SourceFile 147)
at okhttp3.internal.NamedRunnable.run(SourceFile 32)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java 1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java 641)
at java.lang.Thread.run(Thread.java 764)
```
Anyone get some ideas about this crash?

**Comment by out0fmemory** [comment]
As in this post[https://www.bountysource.com/issues/52602642-crash-unexpected-tls-version-none](https://www.bountysource.com/issues/52602642-crash-unexpected-tls-version-none), the 3.12.1 still have this problem.

as chwnFlyPig posted, the info is blew
```
this issue still exists in okhttp3.12.1.
here is my logs:
```
![image](https://user-images.githubusercontent.com/8176355/67175147-8546eb80-f3f7-11e9-9356-6b8ff83c691c.png)

**Comment by swankjesse** [comment]
@out0fmemory your stacktrace line numbers don’t line up with 3.12.1. Please make sure you don’t have another copy of OkHttp holding you back.
