### ISSUE TITLE
Failing CI test with JDK8: failingCallsDoNotInterfereWithConnection

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5576]
https://app.circleci.com/jobs/github/square/okhttp/6685

```
okhttp3.CallTest > failingCallsDoNotInterfereWithConnection FAILED
    org.junit.ComparisonFailure: expected:<"Response [1]"> but was:<"Response [2]">
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at okhttp3.CallTest.failingCallsDoNotInterfereWithConnection(CallTest.java:2991)
```

**Comment by yschimke** [comment]
Output from CI for successful test run

```
Events (29)
[0 ms] callStart: Request{method=POST, url=https://localhost:43321/}
[0 ms] proxySelectStart: https://localhost:43321/
[0 ms] proxySelectEnd: [DIRECT]
[0 ms] dnsStart: localhost
[0 ms] dnsEnd: [localhost/127.0.0.1]
[0 ms] connectStart: localhost/127.0.0.1:43321 DIRECT
[0 ms] secureConnectStart
[50 ms] secureConnectEnd: Handshake{tlsVersion=TLS_1_3 cipherSuite=TLS_AES_128_GCM_SHA256 peerCertificates=[CN=localhost] localCertificates=[]}
[51 ms] connectEnd: h2
[51 ms] connectionAcquired: Connection{localhost:43321, proxy=DIRECT hostAddress=localhost/127.0.0.1:43321 cipherSuite=TLS_AES_128_GCM_SHA256 protocol=h2}
[51 ms] requestHeadersStart
[51 ms] requestHeadersEnd
[51 ms] requestBodyStart
[0 ms] callStart: Request{method=POST, url=https://localhost:43321/}
[0 ms] proxySelectStart: https://localhost:43321/
[0 ms] proxySelectEnd: [DIRECT]
[0 ms] connectionAcquired: Connection{localhost:43321, proxy=DIRECT hostAddress=localhost/127.0.0.1:43321 cipherSuite=TLS_AES_128_GCM_SHA256 protocol=h2}
[0 ms] requestHeadersStart
[0 ms] requestHeadersEnd
[0 ms] requestBodyStart
[0 ms] connectionReleased
[0 ms] callFailed: java.io.IOException: write body fail!
[51 ms] requestBodyEnd: byteCount=6
[51 ms] responseHeadersStart
[93 ms] responseHeadersEnd: Response{protocol=h2, code=200, message=, url=https://localhost:43321/}
[93 ms] responseBodyStart
[93 ms] responseBodyEnd: byteCount=10
[93 ms] connectionReleased
[93 ms] callEnd
```

**Comment by yschimke** [comment]
In failing case it's negotiating http/1.1

```
Events (35)
[0 ms] callStart: Request{method=POST, url=https://localhost:43963/}
[0 ms] proxySelectStart: https://localhost:43963/
[0 ms] proxySelectEnd: [DIRECT]
[0 ms] dnsStart: localhost
[0 ms] dnsEnd: [localhost/127.0.0.1]
[0 ms] connectStart: localhost/127.0.0.1:43963 DIRECT
[0 ms] secureConnectStart
[91 ms] secureConnectEnd: Handshake{tlsVersion=TLS_1_2 cipherSuite=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 peerCertificates=[CN=localhost] localCertificates=[]}
[91 ms] connectEnd: http/1.1
[91 ms] connectionAcquired: Connection{localhost:43963, proxy=DIRECT hostAddress=localhost/127.0.0.1:43963 cipherSuite=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 protocol=http/1.1}
[91 ms] requestHeadersStart
[91 ms] requestHeadersEnd
[91 ms] requestBodyStart
[0 ms] callStart: Request{method=POST, url=https://localhost:43963/}
[0 ms] proxySelectStart: https://localhost:43963/
[0 ms] proxySelectEnd: [DIRECT]
[0 ms] dnsStart: localhost
[0 ms] dnsEnd: [localhost/127.0.0.1]
[0 ms] connectStart: localhost/127.0.0.1:43963 DIRECT
[0 ms] secureConnectStart
[2 ms] secureConnectEnd: Handshake{tlsVersion=TLS_1_2 cipherSuite=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 peerCertificates=[CN=localhost] localCertificates=[]}
[2 ms] connectEnd: http/1.1
[2 ms] connectionAcquired: Connection{localhost:43963, proxy=DIRECT hostAddress=localhost/127.0.0.1:43963 cipherSuite=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384 protocol=http/1.1}
[2 ms] requestHeadersStart
[2 ms] requestHeadersEnd
[2 ms] requestBodyStart
[2 ms] connectionReleased
[3 ms] callFailed: java.io.IOException: write body fail!
[94 ms] requestBodyEnd: byteCount=6
[94 ms] responseHeadersStart
[134 ms] responseHeadersEnd: Response{protocol=http/1.1, code=200, message=OK, url=https://localhost:43963/}
[134 ms] responseBodyStart
[177 ms] responseBodyEnd: byteCount=10
[177 ms] connectionReleased
[177 ms] callEnd
```

**Comment by yschimke** [comment]
I’m tempted to believe the test is overly strict. Both are valid and the thread ordering is just a lot tighter but different with http 1.1 v 2.

**Comment by yschimke** [comment]
https://github.com/square/okhttp/pull/5582
