### ISSUE TITLE
java.net.ProtocolException: Unexpected status line: 800

### ISSUE THREAD

**Issue by wubiaoi** [square/okhttp#5595]
The okhttp client  version is 3.11.0.
Exception is:
`
Caused by: java.net.ProtocolException: Unexpected status line: 800
       at okhttp3.internal.http.StatusLine.parse(StatusLine.java:69) 
       at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
       at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88) 
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45) 
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93) 
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) 
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147) 
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121) 
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200) 
       at okhttp3.RealCall.execute(RealCall.java:77) 
`

**Comment by swankjesse** [comment]
Most likely a disagreement in the content length of the previous response. Can you share the headers and status of the preceding response?

**Comment by wubiaoi** [comment]
> Most likely a disagreement in the content length of the previous response. Can you share the headers and status of the preceding response?

@swankjesse thanks for the comments.
The right response information is:
![image](https://user-images.githubusercontent.com/6115258/68674374-b8147780-0590-11ea-86c4-bfd420489c47.png)

**Comment by swankjesse** [comment]
Unfortunately this isn't sufficient to identify the problem. Somehow OkHttp and the server disagree on the length of the preceding response.
