### ISSUE TITLE
Travis CI snapshots failing

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5596]
https://travis-ci.org/square/okhttp/builds

e.g. https://travis-ci.org/square/okhttp/builds/610830250

```
> Task :okhttp:compileKotlin

e: /home/travis/build/square/okhttp/okhttp/src/main/java/okhttp3/internal/platform/Jdk9Platform.kt: (33, 19): Unresolved reference: applicationProtocols

e: /home/travis/build/square/okhttp/okhttp/src/main/java/okhttp3/internal/platform/Jdk9Platform.kt: (41, 43): Unresolved reference: applicationProtocol

e: /home/travis/build/square/okhttp/okhttp/src/main/java/okhttp3/internal/platform/android/Android10SocketAdapter.kt: (44, 38): Unresolved reference: applicationProtocol

e: /home/travis/build/square/okhttp/okhttp/src/main/java/okhttp3/internal/platform/android/Android10SocketAdapter.kt: (58, 19): Unresolved reference: applicationProtocols

> Task :okhttp:compileKotlin FAILED
```

My bad, related to the build with JDK11 change.

**Comment by RoseRo** [comment]
I have the same problem, I don't know how to fix it.

**Comment by yschimke** [comment]
@RoseRo We now build against a minimum of Java 9, but run our tests against JDK 8 to confirm we have a very specific controlled dependency.  So if you are building, just make sure you are using a newer JDK.

**Comment by yschimke** [comment]
https://travis-ci.org/square/okhttp/builds/612799745?utm_source=github_status&utm_medium=notification

```
okhttp3.ConnectionReuseTest > connectionsAreNotReusedIfHostnameVerifierChanges FAILED
    java.util.NoSuchElementException
        at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
        at okhttp3.internal.tls.BasicCertificateChainCleaner.clean(BasicCertificateChainCleaner.kt:49)
        at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:374)
        at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at okhttp3.Handshake.peerCertificates(Handshake.kt)
        at okhttp3.Handshake.toString(Handshake.kt:127)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
        at okhttp3.ClientRuleEventListener.secureConnectEnd(ClientRuleEventListener.kt:75)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:307)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:180)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:192)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at okhttp3.ConnectionReuseTest.connectionsAreNotReusedIfHostnameVerifierChanges(ConnectionReuseTest.java:289)
okhttp3.URLConnectionTest > streamedBodyIsRetriedOnHttp2Shutdown FAILED
    java.util.NoSuchElementException
        at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
        at okhttp3.internal.tls.BasicCertificateChainCleaner.clean(BasicCertificateChainCleaner.kt:49)
        at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:374)
        at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at okhttp3.Handshake.peerCertificates(Handshake.kt)
        at okhttp3.Handshake.toString(Handshake.kt:127)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
        at okhttp3.ClientRuleEventListener.secureConnectEnd(ClientRuleEventListener.kt:75)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:307)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:180)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:192)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at okhttp3.URLConnectionTest.getResponse(URLConnectionTest.java:3679)
        at okhttp3.URLConnectionTest.streamedBodyIsRetriedOnHttp2Shutdown(URLConnectionTest.java:3641)
okhttp3.URLConnectionTest > sslFallbackNotUsedWhenRecycledConnectionFails FAILED
    java.util.NoSuchElementException
        at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
        at okhttp3.internal.tls.BasicCertificateChainCleaner.clean(BasicCertificateChainCleaner.kt:49)
        at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:374)
        at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at okhttp3.Handshake.peerCertificates(Handshake.kt)
        at okhttp3.Handshake.toString(Handshake.kt:127)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
        at okhttp3.ClientRuleEventListener.secureConnectEnd(ClientRuleEventListener.kt:75)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:307)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:180)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:192)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at okhttp3.URLConnectionTest.getResponse(URLConnectionTest.java:3679)
        at okhttp3.URLConnectionTest.sslFallbackNotUsedWhenRecycledConnectionFails(URLConnectionTest.java:670)
okhttp3.CallTest > requestBodySurvivesRetries FAILED
    java.util.concurrent.RejectedExecutionException: Task okhttp3.internal.concurrent.TaskRunner$runnable$1@20cdaef1 rejected from java.util.concurrent.ThreadPoolExecutor@2d7de23d[Shutting down, pool size = 2, active threads = 2, queued tasks = 0, completed tasks = 0]
okhttp3.CallTest > recoverWhenRetryOnConnectionFailureIsTrue_HTTP2 FAILED
    java.util.NoSuchElementException
        at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
        at okhttp3.internal.tls.BasicCertificateChainCleaner.clean(BasicCertificateChainCleaner.kt:49)
        at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:374)
        at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at okhttp3.Handshake.peerCertificates(Handshake.kt)
        at okhttp3.Handshake.toString(Handshake.kt:127)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
        at okhttp3.ClientRuleEventListener.secureConnectEnd(ClientRuleEventListener.kt:75)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:307)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:180)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:192)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at okhttp3.CallTest.executeSynchronously(CallTest.java:3890)
        at okhttp3.CallTest.executeSynchronously(CallTest.java:3884)
        at okhttp3.CallTest.recoverWhenRetryOnConnectionFailureIsTrue(CallTest.java:1191)
        at okhttp3.CallTest.recoverWhenRetryOnConnectionFailureIsTrue_HTTP2(CallTest.java:1207)
okhttp3.CallTest > postBodyRetransmittedOnFailureRecovery_HTTP2 FAILED
    java.util.NoSuchElementException
        at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
        at okhttp3.internal.tls.BasicCertificateChainCleaner.clean(BasicCertificateChainCleaner.kt:49)
        at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:374)
        at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at okhttp3.Handshake.peerCertificates(Handshake.kt)
        at okhttp3.Handshake.toString(Handshake.kt:127)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
        at okhttp3.ClientRuleEventListener.secureConnectEnd(ClientRuleEventListener.kt:75)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:307)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:180)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:192)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at okhttp3.CallTest.postBodyRetransmittedOnFailureRecovery(CallTest.java:1541)
        at okhttp3.CallTest.postBodyRetransmittedOnFailureRecovery_HTTP2(CallTest.java:1558)
okhttp3.internal.ws.RealWebSocketTest > serverCloseThenClientClose FAILED
    java.lang.AssertionError: 
    Expecting empty but was:<[Closed[1000 Hello!]]>
        at okhttp3.internal.ws.WebSocketRecorder.assertExhausted(WebSocketRecorder.java:163)
        at okhttp3.internal.ws.RealWebSocketTest.tearDown(RealWebSocketTest.java:58)
okhttp3.CallTest > matchingPinnedCertificate FAILED
    java.util.NoSuchElementException
        at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
        at okhttp3.internal.tls.BasicCertificateChainCleaner.clean(BasicCertificateChainCleaner.kt:49)
        at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:374)
        at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at okhttp3.Handshake.peerCertificates(Handshake.kt)
        at okhttp3.internal.connection.RealConnection$connectTls$2.invoke(RealConnection.kt:380)
        at okhttp3.internal.connection.RealConnection$connectTls$2.invoke(RealConnection.kt:72)
        at okhttp3.CertificatePinner.check$okhttp(CertificatePinner.kt:151)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:306)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:180)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:192)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at okhttp3.CallTest.matchingPinnedCertificate(CallTest.java:1481)
okhttp3.CallTest > connectFails FAILED
    java.util.concurrent.RejectedExecutionException: Task okhttp3.internal.concurrent.TaskRunner$runnable$1@1e35f59c rejected from java.util.concurrent.ThreadPoolExecutor@5b37783e[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 0]
okhttp3.ConnectionCoalescingTest > coalescedConnectionDestroyedAfterAcquire FAILED
    javax.net.ssl.SSLPeerUnverifiedException: Hostname san.com not verified (no certificates)
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:365)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:306)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:180)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:192)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at okhttp3.ConnectionCoalescingTest.coalescedConnectionDestroyedAfterAcquire(ConnectionCoalescingTest.java:251)
okhttp3.internal.http2.HttpOverHttp2Test > recoverFromConnectionNoNewStreamsOnFollowUp[h2] FAILED
    org.junit.ComparisonFailure: expected:<[0]> but was:<[1]>
okhttp3.internal.http2.HttpOverHttp2Test > settingsLimitsMaxConcurrentStreams[h2] FAILED
    org.junit.ComparisonFailure: expected:<[0]> but was:<[1]>
okhttp3.internal.http2.HttpOverHttp2Test > recoverFromMultipleRefusedStreamsRequiresNewConnection[h2] FAILED
    java.util.NoSuchElementException
        at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
        at okhttp3.internal.tls.BasicCertificateChainCleaner.clean(BasicCertificateChainCleaner.kt:49)
        at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:374)
        at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at okhttp3.Handshake.peerCertificates(Handshake.kt)
        at okhttp3.Handshake.toString(Handshake.kt:127)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
        at okhttp3.ClientRuleEventListener.secureConnectEnd(ClientRuleEventListener.kt:75)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:307)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:180)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:192)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at okhttp3.internal.http2.HttpOverHttp2Test.recoverFromMultipleRefusedStreamsRequiresNewConnection(HttpOverHttp2Test.java:856)
okhttp3.internal.ws.WebSocketHttpTest > webSocketAndApplicationInterceptors FAILED
    org.junit.ComparisonFailure: expected:<[0]> but was:<[1]>
okhttp3.internal.http2.HttpOverHttp2Test > concurrentHttp2ConnectionsDeduplicated[h2] FAILED
    java.util.NoSuchElementException
        at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
        at okhttp3.internal.tls.BasicCertificateChainCleaner.clean(BasicCertificateChainCleaner.kt:49)
        at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:374)
        at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at okhttp3.Handshake.peerCertificates(Handshake.kt)
        at okhttp3.Handshake.toString(Handshake.kt:127)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
        at okhttp3.ClientRuleEventListener.secureConnectEnd(ClientRuleEventListener.kt:75)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:307)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:180)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:192)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at okhttp3.internal.http2.HttpOverHttp2Test.concurrentHttp2ConnectionsDeduplicated(HttpOverHttp2Test.java:1509)
okhttp3.internal.ws.WebSocketHttpTest > unplannedCloseHandledByCloseWithoutFailure FAILED
    org.junit.ComparisonFailure: expected:<[0]> but was:<[1]>
okhttp3.internal.ws.WebSocketHttpTest > webSocketAndNetworkInterceptors FAILED
    org.junit.ComparisonFailure: expected:<[0]> but was:<[1]>
okhttp3.internal.ws.WebSocketHttpTest > serverMessage FAILED
    org.junit.ComparisonFailure: expected:<[0]> but was:<[1]>
okhttp3.internal.http2.HttpOverHttp2Test > recoverFromOneInternalErrorRequiresNewConnection[h2] FAILED
    java.util.NoSuchElementException
        at java.base/java.util.ArrayDeque.removeFirst(ArrayDeque.java:363)
        at okhttp3.internal.tls.BasicCertificateChainCleaner.clean(BasicCertificateChainCleaner.kt:49)
        at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:374)
        at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:72)
        at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
        at okhttp3.Handshake.peerCertificates(Handshake.kt)
        at okhttp3.Handshake.toString(Handshake.kt:127)
        at java.base/java.lang.String.valueOf(String.java:2951)
        at java.base/java.lang.StringBuilder.append(StringBuilder.java:168)
        at okhttp3.ClientRuleEventListener.secureConnectEnd(ClientRuleEventListener.kt:75)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:307)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:180)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:236)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:109)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:77)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:162)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:192)
        at okhttp3.RealCall.execute(RealCall.kt:66)
        at okhttp3.internal.http2.HttpOverHttp2Test.recoverFromOneInternalErrorRequiresNewConnection(HttpOverHttp2Test.java:830)
okhttp3.CallKotlinTest > testHeadAfterPut FAILED
    java.lang.AssertionError: 
    Expecting actual not to be null
        at okhttp3.CallKotlinTest.testHeadAfterPut(CallKotlinTest.kt:166)
```

**Comment by yschimke** [comment]
Damn you Travis and your ancient Babylonian era 11.0.2 JDK!

https://github.com/square/okhttp/issues/5029

**Comment by SeniorZhai** [comment]
I have the same problem, is there any solution to solve

**Comment by yschimke** [comment]
Bump to 11.0.5 or a newer image.  We have generally moved builds from Travis to CircleCI for other reasons.
