### ISSUE TITLE
Fatal Exception: java.util.NoSuchElementException

### ISSUE THREAD

**Issue by rmdan90** [square/okhttp#5605]
Hey, some of users getting this weird crash.

The crash stack trace from crashlytics:

` Fatal Exception: java.util.NoSuchElementException at okhttp3.internal.connection.RouteSelector.next(RouteSelector.java:75) at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:187) at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:107) at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:87) at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) at com.goadroit.adroitdrivers.network.ConnectivityInterceptor.intercept(ConnectivityInterceptor.java:20) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221) at okhttp3.RealCall$AsyncCall.execute(RealCall.java:172) at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32) at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162) at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636) at java.lang.Thread.run(Thread.java:764)  `

OkHttp version: 3.14.1

I'm using the following dependencies:

com.squareup.retrofit2:retrofit:2.5.0
com.squareup.retrofit2:converter-gson:2.5.0
com.squareup.okhttp3:logging-interceptor:3.14.1
com.squareup.retrofit2:converter-scalars:2.5.0

Base requestsClient code:

` 
private long DEFUALT_CALL_TIMEOUT = 15;
private long DEFUALT_CONNECT_TIMEOUT = 5;

OkHttpClient.Builder okHttpClientBuilder = new OkHttpClient.Builder()
.callTimeout(DEFUALT_CALL_TIMEOUT,TimeUnit.SECONDS)
.connectTimeout(DEFUALT_CONNECT_TIMEOUT, TimeUnit.SECONDS);

if (BuildConfig.DEBUG) {
HttpLoggingInterceptor logging = new HttpLoggingInterceptor();
logging.setLevel(HttpLoggingInterceptor.Level.BODY);
okHttpClientBuilder.addInterceptor(logging);
}
okHttpClientBuilder.addInterceptor(new ConnectivityInterceptor());

retrofit = new Retrofit.Builder()
.baseUrl(AppConstants.SERVER_URL)
.addConverterFactory(GsonConverterFactory.create())
.client(okHttpClientBuilder.build())
.build();
 `

**Comment by swankjesse** [comment]
Try 3.14.4.

**Comment by spuday90** [comment]
Hey,

Im getting the same crash logs as
 RouteSelector.kt line 63
okhttp3.internal.connection.RouteSelector.next 


Fatal Exception: java.util.NoSuchElementException
       at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:63)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:197)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:107)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:75)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:245)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:74)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:219)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:502)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
       
       
       
       OkHttp version : 'com.squareup.okhttp3:logging-interceptor:4.4.0'.
       
       Let me know what can we do.

**Comment by swankjesse** [comment]
@puday90 please update your OkHttp version.
