### ISSUE TITLE
java.lang.IllegalArgumentException: byteCount < 0: -4114004776037900288

### ISSUE THREAD

**Issue by HMY314** [square/okhttp#5650]
com.squareup.okhttp3:okhttp:3.11.0

device：oppo、vivo 98.3%    huawei:ALE-UL00 1.7%
Android system version:  
oppo+vivo 6.0.1; huawei:6.0.0

java.lang.IllegalArgumentException: byteCount < 0: -4114004776037900288
	at okio.Okio$2.read(Okio.java:134)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:237)
	at okio.RealBufferedSource.request(RealBufferedSource.java:68)
	at okio.RealBufferedSource.require(RealBufferedSource.java:61)
	at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.java:95)
	at okhttp3.internal.http2.Http2Reader.readConnectionPreface(Http2Reader.java:80)
	at okhttp3.internal.http2.Http2Connection$ReaderRunnable.execute(Http2Connection.java:608)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.lang.Thread.run(Thread.java:818)

**Comment by swankjesse** [comment]
Let's track this here:
https://github.com/square/okhttp/issues/5651
