### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: size=1021 offset=0 byteCount=-791501174879550467

### ISSUE THREAD

**Issue by HMY314** [square/okhttp#5651]
com.squareup.okhttp3:okhttp:3.11.0

device：oppo、vivo 97% huawei:ALE-UL00 3.0%
Android system version:
oppo+vivo 6.0.1; huawei:6.0.0

java.lang.ArrayIndexOutOfBoundsException: size=1021 offset=0 byteCount=-791501174879550467
	at okio.Util.checkOffsetAndCount(Util.java:30)
	at okio.Buffer.write(Buffer.java:1275)
	at okio.RealBufferedSink.write(RealBufferedSink.java:41)
	at okhttp3.internal.http2.Http2Writer.headers(Http2Writer.java:307)
	at okhttp3.internal.http2.Http2Writer.synStream(Http2Writer.java:127)
	at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:258)
	at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:230)
	at okhttp3.internal.http2.Http2Codec.writeRequestHeaders(Http2Codec.java:113)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:50)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at com.facebook.react.modules.network.NetworkingModule$1.intercept(NetworkingModule.java:291)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:147)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

**Comment by swankjesse** [comment]
Looks like concurrent access to a buffer? Or perhaps a bug in the platform?

Can you reproduce this?

**Comment by HMY314** [comment]
> Looks like concurrent access to a buffer? Or perhaps a bug in the platform?
> 
> Can you reproduce this?

I use the oppo phone with system version 6.0.1, which can be reproduced, but most other phones are fine

**Comment by HMY314** [comment]
I found the reason, it was Tencent Legu reinforcement problem

**Comment by firsthubgit** [comment]
我也遇到了，也是腾讯渠道的加固包，你怎么解决呢

**Comment by HMY314** [comment]
> 我也遇到了，也是腾讯渠道的加固包，你怎么解决呢

用360加固
