### ISSUE TITLE
MockWebServer shutdown is not idempotent

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#5657]
We enqueue a task to await idle, and that fails.
```
java.util.concurrent.RejectedExecutionException: Task okhttp3.internal.concurrent.TaskRunner$runnable$1@83b95cb rejected from java.util.concurrent.ThreadPoolExecutor@7848d4ed[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 2]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at okhttp3.internal.concurrent.TaskRunner$RealBackend.execute(TaskRunner.kt:298)
	at okhttp3.internal.concurrent.TaskRunner.kickCoordinator$okhttp(TaskRunner.kt:91)
	at okhttp3.internal.concurrent.TaskQueue.awaitIdle(TaskQueue.kt:118)
	at okhttp3.mockwebserver.MockWebServer.shutdown(MockWebServer.kt:451)
	at okhttp3.mockwebserver.MockWebServer.after(MockWebServer.kt:460)
``

**Comment by swankjesse** [comment]
Fixed by https://github.com/square/okhttp/pull/5672

**Comment by swankjesse** [comment]
```
java.util.concurrent.RejectedExecutionException: Task okhttp3.internal.concurrent.TaskRunner$runnable$1@4267357c rejected from java.util.concurrent.ThreadPoolExecutor@1232116e[Shutting down, pool size = 1, active threads = 1, queued tasks = 0, completed tasks = 8]
	at java.base/java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2055)
	at java.base/java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:825)
	at java.base/java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1355)
	at okhttp3.internal.concurrent.TaskRunner$RealBackend.execute(TaskRunner.kt:298)
	at okhttp3.internal.concurrent.TaskRunner.kickCoordinator$okhttp(TaskRunner.kt:91)
	at okhttp3.internal.concurrent.TaskQueue.idleLatch(TaskQueue.kt:126)
	at okhttp3.mockwebserver.MockWebServer.shutdown(MockWebServer.kt:451)
	at okhttp3.mockwebserver.MockWebServer.after(MockWebServer.kt:460)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:59)
	at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
	at okhttp3.TestLogHandler$1.evaluate(TestLogHandler.java:50)
```

**Comment by yschimke** [comment]
Any hints on repro before I close?

**Comment by yschimke** [comment]
I suspect fixed, reopen with new report or repro hints.
