### ISSUE TITLE
Uncatchable URISyntaxException during call.enqueue

### ISSUE THREAD

**Issue by IvanShafran** [square/okhttp#5667]
Hi!

In my app, users can set custom server URL. I tested different corner cases. For example: "http://google.com`" -- \` at the end is an intentional mistake.
When I use `call.enqueue`, `java.lang.RuntimeException: java.net.URISyntaxException` is thrown from WorkerThread. And there is no way to catch it normally. I think a perfect place is the `onFailure` method.

Crash log:
```
Exception in thread "OkHttp Dispatcher" java.lang.RuntimeException: java.net.URISyntaxException: Illegal character in authority at index 8: https://google.com`/
	at okhttp3.HttpUrl.uri(HttpUrl.kt:419)
	at okhttp3.internal.connection.RouteSelector.resetNextProxy(RouteSelector.kt:103)
	at okhttp3.internal.connection.RouteSelector.<init>(RouteSelector.kt:53)
	at okhttp3.internal.connection.ExchangeFinder.<init>(ExchangeFinder.kt:59)
	at okhttp3.internal.connection.Transmitter.prepareToConnect(Transmitter.kt:133)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:62)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
	at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.net.URISyntaxException: Illegal character in authority at index 8: https://google.com`/
	at java.net.URI$Parser.fail(URI.java:2848)
	at java.net.URI$Parser.parseAuthority(URI.java:3186)
	at java.net.URI$Parser.parseHierarchical(URI.java:3097)
	at java.net.URI$Parser.parse(URI.java:3053)
	at java.net.URI.<init>(URI.java:588)
	at okhttp3.HttpUrl.uri(HttpUrl.kt:412)
	... 12 more
```

Reproducible test:
https://gist.github.com/IvanShafran/fbf1862af945f70bddf998038cf15b25

Thank you :)

**Comment by yschimke** [comment]
Keeping this open, because it's a valid bug.  Thanks for raising and the great repro.

But as a workaround, why not just prevalidate the custom server URL yourself for now?

**Comment by IvanShafran** [comment]
Thank you for the tip. I used prevalidation and it is okay for now.

**Comment by swankjesse** [comment]
I saw a similar failure crawling:

```
java.lang.RuntimeException: java.net.URISyntaxException: Illegal character in authority at index 7: http://do.not.use").newbuilder(/
	at okhttp3.HttpUrl.uri(HttpUrl.kt:419)
	at okhttp3.internal.connection.RouteSelector.resetNextProxy(RouteSelector.kt:103)
	at okhttp3.internal.connection.RouteSelector.<init>(RouteSelector.kt:53)
	at okhttp3.internal.connection.ExchangeFinder.<init>(ExchangeFinder.kt:61)
	at okhttp3.internal.connection.Transmitter.prepareToConnect(Transmitter.kt:134)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:62)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:194)
	at okhttp3.RealCall.execute(RealCall.kt:67)
	at okhttp3.sample.Crawler.fetch(Crawler.java:101)
	at okhttp3.sample.Crawler.drainQueue(Crawler.java:82)
```

The offending URL is `http://do.not.use").newbuilder(/`.
