### ISSUE TITLE
BC HandshakeCertificates NullPointerException

### ISSUE THREAD

**Issue by sonnyCZE** [square/okhttp#5684]
Hello,

I have probably found bug in ```HandshakeCertificates.Builder```.  When I am trying to build object with client certificate the BouncyCastle ```BcKeyStoreSpi.engineSetKeyEntry``` throws NPE. I am using okhttp and okhttp-tls version 4.1.0 but even older versions acts the same way. I am able to reproduce this on multiple devices (Android 9, 8.1, 7.0). Also I have already tried to disable proguard but still it is throwing the NPE.

Code
```
PrivateKey privateKey = KeyChain.getPrivateKey(context, certAlias);
X509Certificate[] certChain = KeyChain.getCertificateChain(context, certAlias);
X509Certificate mdmCert = certChain[0];

HandshakeCertificates.Builder builder = new HandshakeCertificates.Builder();
builder.addPlatformTrustedCertificates();

for (X509Certificate cert : certChain) {
    builder.addTrustedCertificate(cert);
}

builder.heldCertificate(        //if this is commented then everything is ok
        new HeldCertificate(
new KeyPair(
        mdmCert.getPublicKey(),
        privateKey
),
mdmCert
        ),
        certChain
);

HandshakeCertificates clientCertificates = builder.build(); //this throws exception
```

Stacktrace
```
Caused by: java.security.KeyStoreException: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
    at com.android.org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(BcKeyStoreSpi.java:685)
    at java.security.KeyStore.setKeyEntry(KeyStore.java:1179)
    at okhttp3.tls.internal.TlsUtil.newKeyManager(TlsUtil.kt:85)
    at okhttp3.tls.HandshakeCertificates$Builder.build(HandshakeCertificates.kt:144)
```

**Comment by swankjesse** [comment]
Could you please provide the full stacktrace? An executable test case would also be nice.

**Comment by sonnyCZE** [comment]
Right now I have only certificates from our clients so I can't share it. But the problem is with multiple certificates from multiple clients. Thank you

Complete code:
```
import android.annotation.SuppressLint;
import android.content.Context;
import android.os.AsyncTask;
import android.os.Bundle;
import android.security.KeyChain;
import android.security.KeyChainException;

import java.security.KeyPair;
import java.security.PrivateKey;
import java.security.cert.X509Certificate;

import androidx.annotation.Nullable;
import okhttp3.tls.HandshakeCertificates;
import okhttp3.tls.HeldCertificate;

public class MainActivity extends BaseActivity {
    @SuppressLint("StaticFieldLeak")
    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        new AsyncTask<Context, Void, Void>() {

            @Override
            protected Void doInBackground(Context... contexts) {
                Context context = contexts[0];

                try {
                    String certAlias = "CERTIFICATE:477:19855.31240";
                    PrivateKey privateKey = KeyChain.getPrivateKey(context, certAlias);

                    X509Certificate[] certChain = KeyChain.getCertificateChain(context, certAlias);
                    X509Certificate mdmCert = certChain[0];

                    HandshakeCertificates.Builder builder = new HandshakeCertificates.Builder();
                    builder.addPlatformTrustedCertificates();

                    for (X509Certificate cert : certChain) {
                        builder.addTrustedCertificate(cert);
                    }

                    builder.heldCertificate(        //if this is commented then everything is ok
                            new HeldCertificate(
                                    new KeyPair(
                                            mdmCert.getPublicKey(),
                                            privateKey
                                    ),
                                    mdmCert
                            ),
                            certChain
                    );

                    HandshakeCertificates clientCertificates = builder.build(); //this throws the NPE exception
                } catch (InterruptedException | KeyChainException e) {
                    e.printStackTrace();
                }

                return null;
            }
        }.execute(this);
    }
}
```

Stacktrace
```
2020-01-03 08:54:48.847 7729-7760/cz.sa.se E/cz.kct.se.app.MainApplication: handleUncaughtException(Thread thread, Throwable throwable)
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$3.done(AsyncTask.java:354)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
     Caused by: java.security.KeyStoreException: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object reference
        at com.android.org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(BcKeyStoreSpi.java:685)
        at java.security.KeyStore.setKeyEntry(KeyStore.java:1179)
        at okhttp3.tls.internal.TlsUtil.newKeyManager(TlsUtil.kt:85)
        at okhttp3.tls.HandshakeCertificates$Builder.build(HandshakeCertificates.kt:144)
        at cz.kct.se.ui.activity.MainActivity$1.doInBackground(MainActivity.java:155)
        at cz.kct.se.ui.activity.MainActivity$1.doInBackground(MainActivity.java:124)
        at android.os.AsyncTask$2.call(AsyncTask.java:333)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:764) 
```

**Comment by swankjesse** [comment]
@sonnyCZE that’s the entire stacktrace? Ugh, it omits the line the NPE occurred on.

**Comment by sonnyCZE** [comment]
@swankjesse yes, that is the entire stacktrace. As you can see it is
```
...
Caused by: java.security.KeyStoreException: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.String.length()' on a null object
  at com.android.org.bouncycastle.jcajce.provider.keystore.bc.BcKeyStoreSpi.engineSetKeyEntry(BcKeyStoreSpi.java:685)
...
```
That's all info about NPE I have :-(

**Comment by swankjesse** [comment]
Should be able to get the originating NullPointerException stack trace via a debugger.

**Comment by yschimke** [comment]
Reopen with a stacktrace from the NPE.
