### ISSUE TITLE
Android cleaning fails with custom trust manager and logging

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5689]
https://github.com/square/okhttp/pull/5688/files

Comment out 

```
         // avoid cleaning bug for now
-        .eventListener(EventListener.NONE)
+//        .eventListener(EventListener.NONE)
```

```
08:56:06 V/InstrumentationResultParser: There was 1 failure:
08:56:06 V/InstrumentationResultParser: 1) testCustomTrustManager(okhttp.android.test.OkHttpTest)
08:56:06 V/InstrumentationResultParser: javax.net.ssl.SSLPeerUnverifiedException: Failed to find a trusted cert that signed Certificate:
08:56:06 V/InstrumentationResultParser: Data:
08:56:06 V/InstrumentationResultParser: Version: 3 (0x2)
08:56:06 V/InstrumentationResultParser: Serial Number:
08:56:06 V/InstrumentationResultParser: 04:e1:e7:a4:dc:5c:f2:f3:6d:c0:2b:42:b8:5d:15:9f
08:56:06 V/InstrumentationResultParser: Signature Algorithm: sha256WithRSAEncryption
08:56:06 V/InstrumentationResultParser: Issuer: C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert High Assurance EV Root CA
08:56:06 V/InstrumentationResultParser: Validity
08:56:06 V/InstrumentationResultParser: Not Before: Oct 22 12:00:00 2013 GMT
08:56:06 V/InstrumentationResultParser: Not After : Oct 22 12:00:00 2028 GMT
08:56:06 V/InstrumentationResultParser: Subject: C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert SHA2 High Assurance Server CA
08:56:06 V/InstrumentationResultParser: Subject Public Key Info:
08:56:06 V/InstrumentationResultParser: Public Key Algorithm: rsaEncryption
08:56:06 V/InstrumentationResultParser: Public-Key: (2048 bit)
08:56:06 V/InstrumentationResultParser: Modulus:
08:56:06 V/InstrumentationResultParser: 00:b6:e0:2f:c2:24:06:c8:6d:04:5f:d7:ef:0a:64:
08:56:06 V/InstrumentationResultParser: 06:b2:7d:22:26:65:16:ae:42:40:9b:ce:dc:9f:9f:
08:56:06 V/InstrumentationResultParser: 76:07:3e:c3:30:55:87:19:b9:4f:94:0e:5a:94:1f:
08:56:06 V/InstrumentationResultParser: 55:56:b4:c2:02:2a:af:d0:98:ee:0b:40:d7:c4:d0:
08:56:06 V/InstrumentationResultParser: 3b:72:c8:14:9e:ef:90:b1:11:a9:ae:d2:c8:b8:43:
08:56:06 V/InstrumentationResultParser: 3a:d9:0b:0b:d5:d5:95:f5:40:af:c8:1d:ed:4d:9c:
08:56:06 V/InstrumentationResultParser: 5f:57:b7:86:50:68:99:f5:8a:da:d2:c7:05:1f:a8:
08:56:06 V/InstrumentationResultParser: 97:c9:dc:a4:b1:82:84:2d:c6:ad:a5:9c:c7:19:82:
08:56:06 V/InstrumentationResultParser: a6:85:0f:5e:44:58:2a:37:8f:fd:35:f1:0b:08:27:
08:56:06 V/InstrumentationResultParser: 32:5a:f5:bb:8b:9e:a4:bd:51:d0:27:e2:dd:3b:42:
08:56:06 V/InstrumentationResultParser: 33:a3:05:28:c4:bb:28:cc:9a:ac:2b:23:0d:78:c6:
08:56:06 V/InstrumentationResultParser: 7b:e6:5e:71:b7:4a:3e:08:fb:81:b7:16:16:a1:9d:
08:56:06 V/InstrumentationResultParser: 23:12:4d:e5:d7:92:08:ac:75:a4:9c:ba:cd:17:b2:
08:56:06 V/InstrumentationResultParser: 1e:44:35:65:7f:53:25:39:d1:1c:0a:9a:63:1b:19:
08:56:06 V/InstrumentationResultParser: 92:74:68:0a:37:c2:c2:52:48:cb:39:5a:a2:b6:e1:
08:56:06 V/InstrumentationResultParser: 5d:c1:dd:a0:20:b8:21:a2:93:26:6f:14:4a:21:41:
08:56:06 V/InstrumentationResultParser: c7:ed:6d:9b:f2:48:2f:f3:03:f5:a2:68:92:53:2f:
08:56:06 V/InstrumentationResultParser: 5e:e3
08:56:06 V/InstrumentationResultParser: Exponent: 65537 (0x10001)
08:56:06 V/InstrumentationResultParser: X509v3 extensions:
08:56:06 V/InstrumentationResultParser: X509v3 Basic Constraints: critical
08:56:06 V/InstrumentationResultParser: CA:TRUE, pathlen:0
08:56:06 V/InstrumentationResultParser: X509v3 Key Usage: critical
08:56:06 V/InstrumentationResultParser: Digital Signature, Certificate Sign, CRL Sign
08:56:06 V/InstrumentationResultParser: X509v3 Extended Key Usage:
08:56:06 V/InstrumentationResultParser: TLS Web Server Authentication, TLS Web Client Authentication
08:56:06 V/InstrumentationResultParser: Authority Information Access:
08:56:06 V/InstrumentationResultParser: OCSP - URI:http://ocsp.digicert.com
08:56:06 V/InstrumentationResultParser:
08:56:06 V/InstrumentationResultParser: X509v3 CRL Distribution Points:
08:56:06 V/InstrumentationResultParser:
08:56:06 V/InstrumentationResultParser: Full Name:
08:56:06 V/InstrumentationResultParser: URI:http://crl4.digicert.com/DigiCertHighAssuranceEVRootCA.crl
08:56:06 V/InstrumentationResultParser:
08:56:06 V/InstrumentationResultParser: X509v3 Certificate Policies:
08:56:06 V/InstrumentationResultParser: Policy: X509v3 Any Policy
08:56:06 V/InstrumentationResultParser: CPS: https://www.digicert.com/CPS
08:56:06 V/InstrumentationResultParser:
08:56:06 V/InstrumentationResultParser: X509v3 Subject Key Identifier:
08:56:06 V/InstrumentationResultParser: 51:68:FF:90:AF:02:07:75:3C:CC:D9:65:64:62:A2:12:B8:59:72:3B
08:56:06 V/InstrumentationResultParser: X509v3 Authority Key Identifier:
08:56:06 V/InstrumentationResultParser: keyid:B1:3E:C3:69:03:F8:BF:47:01:D4:98:26:1A:08:02:EF:63:64:2B:C3
08:56:06 V/InstrumentationResultParser:
08:56:06 V/InstrumentationResultParser: Signature Algorithm: sha256WithRSAEncryption
08:56:06 V/InstrumentationResultParser: 18:8a:95:89:03:e6:6d:df:5c:fc:1d:68:ea:4a:8f:83:d6:51:
08:56:06 V/InstrumentationResultParser: 2f:8d:6b:44:16:9e:ac:63:f5:d2:6e:6c:84:99:8b:aa:81:71:
08:56:06 V/InstrumentationResultParser: 84:5b:ed:34:4e:b0:b7:79:92:29:cc:2d:80:6a:f0:8e:20:e1:
08:56:06 V/InstrumentationResultParser: 79:a4:fe:03:47:13:ea:f5:86:ca:59:71:7d:f4:04:96:6b:d3:
08:56:06 V/InstrumentationResultParser: 59:58:3d:fe:d3:31:25:5c:18:38:84:a3:e6:9f:82:fd:8c:5b:
08:56:06 V/InstrumentationResultParser: 98:31:4e:cd:78:9e:1a:fd:85:cb:49:aa:f2:27:8b:99:72:fc:
08:56:06 V/InstrumentationResultParser: 3e:aa:d5:41:0b:da:d5:36:a1:bf:1c:6e:47:49:7f:5e:d9:48:
08:56:06 V/InstrumentationResultParser: 7c:03:d9:fd:8b:49:a0:98:26:42:40:eb:d6:92:11:a4:64:0a:
08:56:06 V/InstrumentationResultParser: 57:54:c4:f5:1d:d6:02:5e:6b:ac:ee:c4:80:9a:12:72:fa:56:
08:56:06 V/InstrumentationResultParser: 93:d7:ff:bf:30:85:06:30:bf:0b:7f:4e:ff:57:05:9d:24:ed:
08:56:06 V/InstrumentationResultParser: 85:c3:2b:fb:a6:75:a8:ac:2d:16:ef:7d:79:27:b2:eb:c2:9d:
08:56:06 V/InstrumentationResultParser: 0b:07:ea:aa:85:d3:01:a3:20:28:41:59:43:28:d2:81:e3:aa:
08:56:06 V/InstrumentationResultParser: f6:ec:7b:3b:77:b6:40:62:80:05:41:45:01:ef:17:06:3e:de:
08:56:06 V/InstrumentationResultParser: c0:33:9b:67:d3:61:2e:72:87:e4:69:fc:12:00:57:40:1e:70:
08:56:06 V/InstrumentationResultParser: f5:1e:c9:b4
08:56:06 V/InstrumentationResultParser:
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.tls.BasicCertificateChainCleaner.clean(BasicCertificateChainCleaner.kt:91)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:376)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.connection.RealConnection$connectTls$1.invoke(RealConnection.kt:73)
08:56:06 V/InstrumentationResultParser: at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
08:56:06 V/InstrumentationResultParser: at okhttp3.Handshake.peerCertificates(Unknown Source:7)
08:56:06 V/InstrumentationResultParser: at okhttp3.Handshake.toString(Handshake.kt:127)
08:56:06 V/InstrumentationResultParser: at java.lang.String.valueOf(String.java:2924)
08:56:06 V/InstrumentationResultParser: at java.lang.StringBuilder.append(StringBuilder.java:132)
08:56:06 V/InstrumentationResultParser: at okhttp3.ClientRuleEventListener.secureConnectEnd(ClientRuleEventListener.kt:75)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:309)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:182)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:238)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:111)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:79)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:163)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
08:56:06 V/InstrumentationResultParser: at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
08:56:06 V/InstrumentationResultParser: at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:194)
08:56:06 V/InstrumentationResultParser: at okhttp3.RealCall.execute(RealCall.kt:67)
08:56:06 V/InstrumentationResultParser: at okhttp.android.test.OkHttpTest.get(OkHttpTest.kt:483)
08:56:06 V/InstrumentationResultParser: at okhttp.android.test.OkHttpTest.testCustomTrustManager(OkHttpTest.kt:445)
```

**Comment by yschimke** [comment]
Older Android doesn't support anything except for

https://android.googlesource.com/platform/frameworks/base/+/3b3dd94/core/java/android/net/http/X509TrustManagerExtensions.java

```
    public X509TrustManagerExtensions(X509TrustManager tm) throws IllegalArgumentException {
        if (tm instanceof TrustManagerImpl) {
            mDelegate = (TrustManagerImpl) tm;
        } else {
            mDelegate = null;
            throw new IllegalArgumentException("tm is an instance of " + tm.getClass().getName() +
                    " which is not a supported type of X509TrustManager");
        }
    }
```

Current support duck typing

https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/net/http/X509TrustManagerExtensions.java

```
        public X509TrustManagerExtensions(X509TrustManager tm) throws IllegalArgumentException {
        if (tm instanceof TrustManagerImpl) {
            mDelegate = (TrustManagerImpl) tm;
            mTrustManager = null;
            mCheckServerTrusted = null;
            mIsSameTrustConfiguration = null;
            return;
        }
        // Use duck typing if possible.
        mDelegate = null;
        mTrustManager = tm;
        // Check that the hostname aware checkServerTrusted is present.
        try {
            mCheckServerTrusted = tm.getClass().getMethod("checkServerTrusted",
                    X509Certificate[].class,
                    String.class,
                    String.class);
        } catch (NoSuchMethodException e) {
            throw new IllegalArgumentException("Required method"
                    + " checkServerTrusted(X509Certificate[], String, String, String) missing");
        }
        // Get the option isSameTrustConfiguration method.
        Method isSameTrustConfiguration = null;
        try {
            isSameTrustConfiguration = tm.getClass().getMethod("isSameTrustConfiguration",
                    String.class,
                    String.class);
        } catch (ReflectiveOperationException ignored) {
        }
        mIsSameTrustConfiguration = isSameTrustConfiguration;
    }
```

**Comment by yschimke** [comment]
@swankjesse given above. Are there any situations we would prefer to use our cleaner instead of even the default Android logic?

**Comment by swankjesse** [comment]
Our cleaning is inefficient because we need to build an index of CAs. Using the built-in one is desirable whenever that's possible.
