### ISSUE TITLE
Fix bouncy castle platform bugs

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5698]
After https://github.com/square/okhttp/pull/5695 lands, there are plenty of failing tests that either need test or code fixes.  Previous testing has shown big differences between JDK 8 and JDK 11 for Bouncy Castle.

```
$ ./gradlew -Dokhttp.platform=bouncycastle test
```

**Comment by yschimke** [comment]
2 fixes here https://github.com/square/okhttp/pull/5741

**Comment by yschimke** [comment]
A test fix https://github.com/square/okhttp/pull/5747

**Comment by yschimke** [comment]
IIUC current Failing test relates to BouncyCastle provider using a default non BC KeyManager & TrustManager when used with client auth

```
okhttp3.tls.HandshakeCertificatesTest > clientAndServer FAILED
    java.util.concurrent.ExecutionException: org.bouncycastle.tls.TlsFatalAlert: handshake_failure(40)
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:191)
        at okhttp3.tls.HandshakeCertificatesTest.clientAndServer(HandshakeCertificatesTest.java:105)

        Caused by:
        org.bouncycastle.tls.TlsFatalAlert: handshake_failure(40)
            at org.bouncycastle.tls.AbstractTlsServer.getSelectedCipherSuite(AbstractTlsServer.java:387)
            at org.bouncycastle.jsse.provider.ProvTlsServer.getSelectedCipherSuite(ProvTlsServer.java:291)
            at org.bouncycastle.tls.TlsServerProtocol.sendServerHelloMessage(TlsServerProtocol.java:747)
            at org.bouncycastle.tls.TlsServerProtocol.handleHandshakeMessage(TlsServerProtocol.java:162)
            at org.bouncycastle.tls.TlsProtocol.processHandshakeQueue(TlsProtocol.java:546)
            at org.bouncycastle.tls.TlsProtocol.processRecord(TlsProtocol.java:464)
            at org.bouncycastle.tls.RecordStream.readRecord(RecordStream.java:224)
            at org.bouncycastle.tls.TlsProtocol.safeReadRecord(TlsProtocol.java:687)
            at org.bouncycastle.tls.TlsProtocol.blockForHandshake(TlsProtocol.java:325)
            at org.bouncycastle.tls.TlsServerProtocol.accept(TlsServerProtocol.java:83)
            at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(ProvSSLSocketWrap.java:606)
            at org.bouncycastle.jsse.provider.ProvSSLSocketWrap.startHandshake(ProvSSLSocketWrap.java:571)
            at okhttp3.tls.HandshakeCertificatesTest.lambda$doServerHandshake$2(HandshakeCertificatesTest.java:171)
```

**Comment by yschimke** [comment]
Debug testing branch https://github.com/square/okhttp/pull/5748/files

**Comment by yschimke** [comment]
I'm testing with JDK11 now, don't see the point with JDK8

**Comment by yschimke** [comment]
On Android https://github.com/bcgit/bc-java/issues/686

**Comment by VN-tunt89** [comment]
Thanks so much!
Have a nice day.

**Comment by yschimke** [comment]
@VN-tunt89 what's your setup, curious about BouncyCastle usage to be honest.

**Comment by VN-tunt89** [comment]
Thank for help. I have a trip with my parent 3 day. Thanks support to work

**Comment by VN-tunt89** [comment]
Why Log

**Comment by yschimke** [comment]
I don't understand the question.

**Comment by yschimke** [comment]
No plans to fix any issues with BouncyCastle and MockWebServer, closing.
