### ISSUE TITLE
SSLHandshakeException on Android 5 (API 21)

### ISSUE THREAD

**Issue by minas90** [square/okhttp#5700]
I pushed a new version of my app to production and started to get bunch of complains from users.
Turns out with okhttp 4.3.0 there is SSLHandshakeException happening only on Android 5 for some reason. I'm getting this exception for all my requests including requests from 3th party SDKs. It's reproducible on API 21 Emulator.

```
javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:306)
        at com.android.okhttp.Connection.upgradeToTls(Connection.java:197)
        at com.android.okhttp.Connection.connect(Connection.java:151)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323)
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:491)
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25)
...
     Caused by: java.security.cert.CertificateException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:318)
        at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:219)
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:113)
        at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:525)
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:302)
        at com.android.okhttp.Connection.upgradeToTls(Connection.java:197) 
        at com.android.okhttp.Connection.connect(Connection.java:151) 
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276) 
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211) 
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373) 
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323) 
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:491) 
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105) 
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25) 
...
     Caused by: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
        at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:318) 
        at com.android.org.conscrypt.TrustManagerImpl.checkServerTrusted(TrustManagerImpl.java:219) 
        at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:113) 
        at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:525) 
        at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) 
        at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:302) 
        at com.android.okhttp.Connection.upgradeToTls(Connection.java:197) 
        at com.android.okhttp.Connection.connect(Connection.java:151) 
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:276) 
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:211) 
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:373) 
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:323) 
        at com.android.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:491) 
        at com.android.okhttp.internal.http.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105) 
        at com.android.okhttp.internal.http.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:25) 
...
```

**Comment by yschimke** [comment]
Is there a server to test against?  What version did you upgrade from 4.2?

**Comment by yschimke** [comment]
If you can make a failing test case with our Android test it would make this quicker to debug

https://github.com/square/okhttp/tree/master/android-test

**Comment by minas90** [comment]
Hi, I was using 4.2.2 before.
It happens with almost every HTTPS request I believe on API 21, maybe with some exception as github pages worked fine.
Eg try with wikipedia on API 21: https://en.wikipedia.org/wiki/Logistic_function

**Comment by minas90** [comment]
I just noticed that I get different types of exceptions for different websites.
Sorry I have to go out now, will make tests in a few hours if it's still needed, but it's easy to repro.
Eg try with this url:  https://news.am/arm/news/552948.html
It works fine on 4.2.2, but I get `java.net.ConnectException: Failed to connect to news.am/2606:4700:20::681a:85c:443` on 4.3

**Comment by yschimke** [comment]
@minas90 That's enough.  Thanks!

**Comment by minas90** [comment]
And to repro SSLHandshakeException use this url: https://docs.fabric.io/android/changelog.html

**Comment by yschimke** [comment]
Two failing reproductions

```


  @Test
  fun testRequestFailing1() {
    assumeNetwork()

    client = client.newBuilder().connectionSpecs(listOf(ConnectionSpec.COMPATIBLE_TLS)).build()

    val request = Request.Builder().url("https://news.am/arm/news/552948.html").build()

    val response = client.newCall(request).execute()

    response.use {
      assertEquals(200, response.code)
    }
  }

  @Test
  fun testRequestFailing2() {
    assumeNetwork()

    client = client.newBuilder().connectionSpecs(listOf(ConnectionSpec.COMPATIBLE_TLS)).build()

    val request = Request.Builder().url("https://docs.fabric.io/android/changelog.html").build()

    val response = client.newCall(request).execute()

    response.use {
      assertEquals(200, response.code)
    }
  }
```

**Comment by yschimke** [comment]
SSL Labs https://www.ssllabs.com/ssltest/analyze.html?d=news.am&s=104.26.8.92&hideResults=on&latest

**Comment by yschimke** [comment]
Confirmed working against 4.2.2 https://github.com/yschimke/okhttp/tree/4.2.2_test

**Comment by yschimke** [comment]
Reviewing `git diff parent-4.2.2..parent-4.3.0`

It's mostly relevant functional changes in http/2 settings, pings, and AndroidSocketAdapter.  Starting with the latter.

**Comment by yschimke** [comment]
@swankjesse heads up another fix for 4.3.1

We lost this code in 4.3, which breaks some hosts on Android 5

          // This is SSLParameters.setServerNames() in API 24+.
          setHostname.invoke(sslSocket, hostname)

**Comment by vipulasri** [comment]
Issue still happening with `v4.9.0` on Android API 21.
`javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

`java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

**Comment by yschimke** [comment]
@vipulasri Is this only happening with Android 21? There are legitimate reasons why you might get this error because of client/server incompatibilities with the certificates, potentially ciphers?

**Comment by vipulasri** [comment]
@yschimke Yes, it's only happening on Android Lollipop. With all other versions, it's working fine.

**Comment by vipulasri** [comment]
Thanks for the insights. I will look into these.

**Comment by projectdelta6** [comment]
I'm also getting this on v4.4.0 and v4.9.0  with Android API 24, I've tested the app on API 25 and 26 ant they both work without issue, but on API 24 I'm getting SSLHandshakeException on all calls to our server

**Comment by yschimke** [comment]
The original issue was legitimate as I broken SNI on very old Android.  To investigate this, I'll need a test server to hit.  Otherwise I can't do much from these follow on report.  They are likely a different issue.

**Comment by vipulasri** [comment]
@yschimke Can you please try this endpoint: https://www.wikiart.org/en/popular-paintings/alltime/?json=2&page=1 for reproducing the behavior?

**Comment by yschimke** [comment]
I wonder whether it relates to two certificate paths and one requiring a download? That only makes sense if older Android only trusts the second root CA, and it's getting served an incomplete path.

https://www.ssllabs.com/ssltest/analyze.html?d=www.wikiart.org

<img width="950" alt="image" src="https://user-images.githubusercontent.com/231923/126532442-c3265706-c975-48e6-ad04-29c2450214fd.png">

**Comment by yschimke** [comment]
@vipulasri I can't reproduce on SDK 24

Can you run this test and send me the logcat output with the certificates displayed https://github.com/square/okhttp/pull/6760

**Comment by vipulasri** [comment]
> @vipulasri I can't reproduce on SDK 24
> 
> Can you run this test and send me the logcat output with the certificates displayed https://github.com/square/okhttp/pull/6760

Yeah, because it's only happening on SDK level 21

**Comment by yschimke** [comment]
Thanks, got confused by comment by project Delta who reported on 24. Thanks.

**Comment by yschimke** [comment]
@vipulasri this certificate chain isn't supported on Android 21, there is no root CA certificate in the Android TrustManager.

See https://talkatone.zendesk.com/hc/en-us/articles/360044415672-Android-Users-Running-OS-Versions-4-4-4-5-0-
https://serverfault.com/questions/792143/why-is-my-ssl-certificate-untrusted-on-android

**Comment by vipulasri** [comment]
@yschimke thank you so much for sharing your insights. Seems like something not related to okhttp.
