### ISSUE TITLE
Broken okhttp-tls tests with conscrypt

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5722]
https://app.circleci.com/jobs/github/square/okhttp/8416

```
> Task :samples:slack:testClasses UP-TO-DATE
> Task :samples:slack:test NO-SOURCE
> Task :samples:static-server:compileKotlin

> Task :okhttp-tls:test

okhttp3.tls.HandshakeCertificatesTest > platformTrustedCertificates FAILED
    java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 28
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at okhttp3.tls.HandshakeCertificatesTest.platformTrustedCertificates(HandshakeCertificatesTest.java:145)

okhttp3.tls.HeldCertificateTest > decodeMalformed FAILED
    java.util.NoSuchElementException
        at java.base/java.util.ArrayList$Itr.next(ArrayList.java:999)
        at okhttp3.tls.HeldCertificate$Companion.decodePem(HeldCertificate.kt:521)
        at okhttp3.tls.HeldCertificate$Companion.decode(HeldCertificate.kt:493)
        at okhttp3.tls.HeldCertificate$Companion.decode(HeldCertificate.kt:488)
        at okhttp3.tls.HeldCertificate.decode(HeldCertificate.kt)
        at okhttp3.tls.HeldCertificateTest.decodeMalformed(HeldCertificateTest.java:461)
```

**Comment by yschimke** [comment]
Narrator: "They weren't flaky, just broken."

https://github.com/square/okhttp/pull/5734
https://github.com/square/okhttp/pull/5733
