### ISSUE TITLE
NoSuchMethodError when trying to instantiate MockWebServer

### ISSUE THREAD

**Issue by jsoberg** [square/okhttp#5759]
When attempting to use Retrofit and MockWebServer in my project, I get the following exception when initializing a MockWebServer object in my unit tests:

```
java.lang.NoSuchMethodError: okhttp3.internal.Util.immutableListOf([Ljava/lang/Object;)Ljava/util/List;
	at okhttp3.mockwebserver.MockWebServer.<init>(MockWebServer.kt:176)
```

This bug can be reproduced in `MockWebServerInitializationBugTest.java` from https://github.com/jsoberg/OkHttp-MockWebServer-NoSuchMethorErrorBug.

The following is the gradle dependencies output for the example project:
```
compileClasspath - Compile classpath for source set 'main'.
\--- com.squareup.retrofit2:retrofit:2.7.0
     \--- com.squareup.okhttp3:okhttp:3.14.4
          \--- com.squareup.okio:okio:1.17.2

default - Configuration for default artifacts.
\--- com.squareup.retrofit2:retrofit:2.7.0
     \--- com.squareup.okhttp3:okhttp:3.14.4
          \--- com.squareup.okio:okio:1.17.2

implementation - Implementation only dependencies for source set 'main'. (n)
+--- unspecified (n)
\--- com.squareup.retrofit2:retrofit:2.7.0 (n)

runtimeClasspath - Runtime classpath of source set 'main'.
\--- com.squareup.retrofit2:retrofit:2.7.0
     \--- com.squareup.okhttp3:okhttp:3.14.4
          \--- com.squareup.okio:okio:1.17.2

testCompileClasspath - Compile classpath for source set 'test'.
+--- com.squareup.retrofit2:retrofit:2.7.0
|    \--- com.squareup.okhttp3:okhttp:3.14.4 -> 4.3.1
|         +--- com.squareup.okio:okio:2.4.1
|         |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 -> 1.3.61
|         |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.61
|         |    |    \--- org.jetbrains:annotations:13.0
|         |    \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50 -> 1.3.61
|         \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.61 (*)
+--- junit:junit:4.12
|    \--- org.hamcrest:hamcrest-core:1.3
+--- com.squareup.okhttp3:okhttp:4.3.1 (*)
\--- com.squareup.okhttp3:mockwebserver:4.3.1
     +--- com.squareup.okhttp3:okhttp:4.3.1 (*)
     \--- junit:junit:4.12 (*)

testImplementation - Implementation only dependencies for source set 'test'. (n)
+--- junit:junit:4.12 (n)
+--- com.squareup.okhttp3:okhttp:4.3.1 (n)
\--- com.squareup.okhttp3:mockwebserver:4.3.1 (n)

testRuntimeClasspath - Runtime classpath of source set 'test'.
+--- com.squareup.retrofit2:retrofit:2.7.0
|    \--- com.squareup.okhttp3:okhttp:3.14.4 -> 4.3.1
|         +--- com.squareup.okio:okio:2.4.1
|         |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 -> 1.3.61
|         |    |    +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.61
|         |    |    \--- org.jetbrains:annotations:13.0
|         |    \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50 -> 1.3.61
|         \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.61 (*)
+--- junit:junit:4.12
|    \--- org.hamcrest:hamcrest-core:1.3
+--- com.squareup.okhttp3:okhttp:4.3.1 (*)
\--- com.squareup.okhttp3:mockwebserver:4.3.1
     +--- com.squareup.okhttp3:okhttp:4.3.1 (*)
     \--- junit:junit:4.12 (*)
```
Seemingly, the MockWebServer and OkHttp dependencies are both using the same version (4.3.1), and I would therefore think that there would be no issues. 

Retrofit's OkHttp dependency appears to be being updated to the same (from the line `com.squareup.okhttp3:okhttp:3.14.4 -> 4.3.1`). If the Retrofit dependency is removed, it works as expected.

**Comment by austince** [comment]
I get the same type of error, but slightly different: `java.lang.NoSuchMethodError: 'void okhttp3.internal.Internal.initializeInstanceForTests()'`

**Comment by alireza-khosroabadi** [comment]
Hi @jsoberg 
I get the same type of error
Do you find any solution?

**Comment by swankjesse** [comment]
Can you share a full stack trace? I wonder if you’re using IntelliJ’s dependency resolution which might be different from Gradle’s.

**Comment by jsoberg** [comment]
> Hi @jsoberg
> I get the same type of error
> Do you find any solution?

If you downgrade OkHttp to the version that retrofit is using (3.14.4 in the example case I provided) it should work.


>
> 
> Can you share a full stack trace? I wonder if you’re using IntelliJ’s dependency resolution which might be different from Gradle’s.

Interestingly enough, I just went to run the example project I provided on my personal computer and it ran without errors (both through Gradle CLI and IntelliJ). I'll have to try again later on my work PC.

**Comment by alireza-khosroabadi** [comment]
Hi @swankjesse 
this log stack trace
`java.lang.NoSuchMethodError: okhttp3.internal.Util.immutableListOf([Ljava/lang/Object;)Ljava/util/List;

	at okhttp3.mockwebserver.MockWebServer.<init>(MockWebServer.kt:176)
	at com.rh.ot.android.mock.server.MockApiServer.<init>(MockApiServer.java:25)
	at com.rh.ot.android.mock.server.MockApiServer.getInstance(MockApiServer.java:31)
	at com.rh.ot.android.tools.MockServerRunner.startServer(MockServerRunner.java:17)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.robolectric.internal.SandboxTestRunner.invokeBeforeClass(SandboxTestRunner.java:115)
	at org.robolectric.internal.SandboxTestRunner.access$400(SandboxTestRunner.java:47)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:241)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)


java.lang.NullPointerException
	at com.rh.ot.android.tools.MockServerRunner.tearDown(MockServerRunner.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.robolectric.internal.SandboxTestRunner.invokeAfterClass(SandboxTestRunner.java:124)
	at org.robolectric.internal.SandboxTestRunner.access$100(SandboxTestRunner.java:47)
	at org.robolectric.internal.SandboxTestRunner$1.evaluate(SandboxTestRunner.java:98)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at com.intellij.junit4.JUnit4IdeaTestRunner.startRunnerWithArgs(JUnit4IdeaTestRunner.java:68)
	at com.intellij.rt.execution.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:47)
	at com.intellij.rt.execution.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:242)
	at com.intellij.rt.execution.junit.JUnitStarter.main(JUnitStarter.java:70)`

and my gradle dependencies is :

`
implementation 'com.squareup.retrofit2:retrofit:2.7.0'
testImplementation 'junit:junit:4.12'
    testImplementation "com.google.truth:truth:1.0.1"
    testImplementation 'org.mockito:mockito-core:3.1.0'
    testImplementation 'com.squareup.okhttp3:mockwebserver:4.3.1'
    testImplementation 'org.awaitility:awaitility:4.0.2'
    testImplementation 'org.robolectric:robolectric:4.3'
    testImplementation "org.robolectric:multidex:3.4.2"
    testImplementation 'androidx.multidex:multidex:2.0.1'`

test run on my System success and without error but on my teammate has this exception

**Comment by jsoberg** [comment]
@swankjesse - Seems that on my work PC where the problem originated, running the test through Gradle CLI works fine. The `NoSuchMethodError `only appears when running through IntelliJ.

**Comment by swankjesse** [comment]
I believe this is an issue with conflicting dependency versions. If it only occurs in IntelliJ it’s probably an IntelliJ bug, and they’ve got a redesign for their project model this year that might fix it.

In the interim you can either upgrade your dependencies to the same version, or configure IntelliJ to build and run tests with Gradle. This is in the Gradle section in settings.

**Comment by swankjesse** [comment]
No action for us to take on this.
