### ISSUE TITLE
UnsupportedOperationException on JDK 11

### ISSUE THREAD

**Issue by avdv** [square/okhttp#5780]
We are using a library that depends on okhttp3 3.2.0. Our service works fine on JDK 11.

Unfortunately, another dependency we have upgraded (splunk-java-logging) depends on a newer okhttp3 library (3.14.6). Now, our service fails:
```
Caused by: java.lang.UnsupportedOperationException: clientBuilder.sslSocketFactory(SSLSocketFactory) not supported on JDK 9+                      
        at okhttp3.internal.platform.Jdk9Platform.trustManager(Jdk9Platform.java:81)                                                               
        at okhttp3.internal.platform.Platform.buildCertificateChainCleaner(Platform.java:176)                                                      
        at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.java:655)                                                                    
        at io.featureflow.client.core.EventSource.<init>(EventSource.java:65)                                                                      
        at io.featureflow.client.core.FeatureControlStreamClient.start(FeatureControlStreamClient.java:62)                                         
        at io.featureflow.client.FeatureflowClient.<init>(FeatureflowClient.java:78)                                                               
        at io.featureflow.client.FeatureflowClient$Builder.build(FeatureflowClient.java:221)                                                       
```
Why? Apparently it would work totally fine, only the newer okhttp3 deliberately refuses to work... Wouldn't it make more sense to just try accessing it first, and then act accordingly instead of plainly throwing an exception?

Ref: https://github.com/featureflow/featureflow-java-sdk/issues/4

**Comment by swankjesse** [comment]
Java 9 started making it more difficult to reflect on Java implementation classes. 

Rather than trying to win an arms race against a host platform that doesn't like being accessed via reflection we decided to fix the root cause, which is that applications don't tell us their TrustManager.

I very much don't like that an upgrade from one OkHttp version to another introduced a run time crash. We're doing this because we think it's the least bad option. I'm worried about a much more severe problem, where say, Java 15 wouldn't work at all because this reflective operation is completely forbidden.

**Comment by JakeWharton** [comment]
https://twitter.com/nipafx/status/1224736167293222912

**Comment by avdv** [comment]
@swankjesse Thank you very much for your quick reply! :bowing_man:  Although it isn't what I had hoped for... Basically you're saying that in anticipation of the future, where something will not work anymore, you decided to  make it not work anymore now. :disappointed: 

I guess the right thing would be to fix the library, but featureflow/featureflow-java-sdk has really bit-rotted... no changes in a long tiem. As you said, they try to stick in their own TrustManager in order to let it support letsencrypt certificates on all targets. Am I right that one is rather supposed to use a `CertificatePinner` instead?

**Comment by swankjesse** [comment]
The featureflow SDK needs to be changed to use the two-argument overload of `OkHttpClient.Builder.sslSocketFactory()`.

**Comment by avdv** [comment]
> The featureflow SDK needs to be changed to use the two-argument overload of `OkHttpClient.Builder.sslSocketFactory()`.

Thank you. Now it's pretty obvious once IntelliJ loads the comment from the @deprecated annotation... Doh. :heart:

**Comment by yschimke** [comment]
Yep.  The client has the thing we need so can just trivially pass it on also.

The legacy logic is not guaranteed to work in different JDKs or SSL providers etc. And is a source of bugs and confusion to even partially support. 

https://github.com/square/okhttp/blob/c5ac86b83a22010dcc0b887db5b8c572d0ce136c/okhttp/src/main/java/okhttp3/internal/platform/Platform.kt#L85

**Comment by yschimke** [comment]
Yep.  The client has the thing we need so can just trivially pass it on also.

The legacy logic is not guaranteed to work in different JDKs or SSL providers etc. And is a source of bugs and confusion to even partially support. 

https://github.com/square/okhttp/blob/c5ac86b83a22010dcc0b887db5b8c572d0ce136c/okhttp/src/main/java/okhttp3/internal/platform/Platform.kt#L85

**Comment by avdv** [comment]
Thank you again guys. I've opened a PR in the featureflow repository with the trivial fix. Will see how that goes... But really fast replies and to the point. My pleasure!
