### ISSUE TITLE
Docs for building okhttp are missing

### ISSUE THREAD

**Issue by MSohm** [square/okhttp#5782]
A Google search for instructions to build okhttp points to this page:  https://github.com/square/okhttp/wiki/Building

That page has a HTTP/1.1 301 Moved Permanently and directs to https://square.github.io/okhttp/contributing/

But that page just talks about how to contribute and doesn't have any build instructions.  Do these exist somewhere else or were they lost in this move?  If they do exist I recommend updating that link so they can be easily found.

**Comment by yschimke** [comment]
https://square.github.io/okhttp/contributing/

**Comment by MSohm** [comment]
Yes, that is the link it redirects to, which I included in my report above.  That page doesn't have any build instructions, recommended tools, version requirements, etc.  Are those documented anywhere or was that information lost in the move?

**Comment by swankjesse** [comment]
What did you try?

**Comment by yschimke** [comment]
The instructions to build are in the page. I guess if you want a set of jars to test against we could include that, but that's awkward because most downstream build would prefer picking up a release version or at minimum snapshots from a central repo.

**Comment by yschimke** [comment]
The instructions to build are in the page. I guess if you want a set of jars to test against we could include that, but that's awkward because most downstream build would prefer picking up a release version or at minimum snapshots from a central repo.

**Comment by MSohm** [comment]
I tried building in Android Studio, but it fails with what looks like Java 9 dependencies.  I just switched to IntelliJ and that seems to be working.  My end goal is experimenting to make some changes to be used in an Android app.

Am I missing something from that page?  Here is what I see (using Chrome):

Contributing¶
Keeping the project small and stable limits our ability to accept new contributors. We are not seeking new committers at this time, but some small contributions are welcome.

If you’ve found a security problem, please follow our bug bounty program.

If you’ve found a bug, please contribute a failing test case so we can study and fix it.

If you have a new feature idea, please build it in an external library. There are many libraries that sit on top or hook in via existing APIs. If you build something that integrates with OkHttp, tell us so that we can link it!

Before code can be accepted all contributors must complete our Individual Contributor License Agreement (CLA).

Code Contributions¶
Get working code on a personal branch with tests passing before you submit a PR:


./gradlew clean check
Please make every effort to follow existing conventions and style in order to keep the code as readable as possible.

Contribute code changes through GitHub by forking the repository and sending a pull request. We squash all pull requests on merge.

**Comment by MSohm** [comment]
Scratch that, IntelliJ fails to build as well.  Trying to build artifacts fails with what looks like an error with the Kotlin compiler and seems to match an issue in Jetbrains issue list.  Error is below, but this is probably going on a bit of a tangent if I don't have the right environment set up.  It would be good to know what's known to work so I can just start from there.

Error:Kotlin: [Internal Error] org.jetbrains.kotlin.codegen.CompilationException: Back-end (JVM) Internal error: Failed to generate expression: KtObjectLiteralExpression
File being compiled at position: (96,14) in C:/Users/msohm/Downloads/okhttp/okhttp/src/main/java/okhttp3/internal/concurrent/TaskQueue.kt
The root cause org.jetbrains.kotlin.utils.KotlinExceptionWithAttachments was thrown at: org.jetbrains.kotlin.codegen.binding.CodegenBinding.asmTypeForAnonymousClass(CodegenBinding.java:122)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genQualified(ExpressionCodegen.java:324)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genQualified(ExpressionCodegen.java:284)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.gen(ExpressionCodegen.java:356)
	at org.jetbrains.kotlin.codegen.CallGenerator$DefaultCallGenerator.genValueAndPut(CallGenerator.kt:70)
	at org.jetbrains.kotlin.codegen.CallBasedArgumentGenerator.generateExpression(CallBasedArgumentGenerator.kt:42)
	at org.jetbrains.kotlin.codegen.ArgumentGenerator.generate(ArgumentGenerator.kt:68)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2504)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2476)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:41)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:13)
	at org.jetbrains.kotlin.codegen.OperationStackValue.putSelector(StackValue.kt:79)
	at org.jetbrains.kotlin.codegen.StackValueWithLeaveTask.putSelector(StackValue.kt:67)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:122)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:115)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.putStackValue(ExpressionCodegen.java:384)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.gen(ExpressionCodegen.java:365)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.returnExpression(ExpressionCodegen.java:1701)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$FunctionDefault.doGenerateBody(FunctionGenerationStrategy.java:64)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$CodegenBased.generateBody(FunctionGenerationStrategy.java:84)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:666)
	at org.jetbrains.kotlin.codegen.inline.PsiSourceCompilerForInline.generateMethodBody(SourceCompilerForInline.kt:203)
	at org.jetbrains.kotlin.codegen.inline.PsiSourceCompilerForInline.doCreateMethodNodeFromSource(SourceCompilerForInline.kt:312)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen$Companion.createInlineMethodNode$backend(InlineCodegen.kt:540)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegenForDefaultBody.genCallInner(InlineCodegenForDefaultBody.kt:42)
	at org.jetbrains.kotlin.codegen.CallGenerator$DefaultImpls.genCall(CallGenerator.kt:115)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegenForDefaultBody.genCall(InlineCodegenForDefaultBody.kt:20)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateDefaultImplBody(FunctionCodegen.java:1287)
	at org.jetbrains.kotlin.codegen.inline.PsiSourceCompilerForInline.doCreateMethodNodeFromSource(SourceCompilerForInline.kt:306)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen$Companion.createInlineMethodNode$backend(InlineCodegen.kt:540)
	at org.jetbrains.kotlin.codegen.inline.InlineCodegen.performInline(InlineCodegen.kt:139)
	at org.jetbrains.kotlin.codegen.inline.PsiInlineCodegen.genCallInner(PsiInlineCodegen.kt:67)
	at org.jetbrains.kotlin.codegen.CallGenerator$DefaultImpls.genCall(CallGenerator.kt:115)
	at org.jetbrains.kotlin.codegen.inline.PsiInlineCodegen.genCall(PsiInlineCodegen.kt:31)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2533)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.invokeMethodWithArguments(ExpressionCodegen.java:2476)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:41)
	at org.jetbrains.kotlin.codegen.Callable$invokeMethodWithArguments$1.invoke(Callable.kt:13)
	at org.jetbrains.kotlin.codegen.OperationStackValue.putSelector(StackValue.kt:79)
	at org.jetbrains.kotlin.codegen.StackValueWithLeaveTask.putSelector(StackValue.kt:67)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:122)
	at org.jetbrains.kotlin.codegen.StackValue.put(StackValue.java:115)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.putStackValue(ExpressionCodegen.java:384)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.gen(ExpressionCodegen.java:365)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.returnExpression(ExpressionCodegen.java:1701)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$FunctionDefault.doGenerateBody(FunctionGenerationStrategy.java:64)
	at org.jetbrains.kotlin.codegen.FunctionGenerationStrategy$CodegenBased.generateBody(FunctionGenerationStrategy.java:84)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:666)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethodBody(FunctionCodegen.java:473)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:260)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.generateMethod(FunctionCodegen.java:176)
	at org.jetbrains.kotlin.codegen.FunctionCodegen.gen(FunctionCodegen.java:147)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genSimpleMember(MemberCodegen.java:197)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateDeclaration(ClassBodyCodegen.java:166)
	at org.jetbrains.kotlin.codegen.ClassBodyCodegen.generateBody(ClassBodyCodegen.java:86)
	at org.jetbrains.kotlin.codegen.MemberCodegen.generate(MemberCodegen.java:129)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:302)
	at org.jetbrains.kotlin.codegen.MemberCodegen.genClassOrObject(MemberCodegen.java:286)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateClassesAndObjectsInFile(PackageCodegenImpl.java:118)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generateFile(PackageCodegenImpl.java:137)
	at org.jetbrains.kotlin.codegen.PackageCodegenImpl.generate(PackageCodegenImpl.java:68)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generatePackage(CodegenFactory.kt:96)
	at org.jetbrains.kotlin.codegen.DefaultCodegenFactory.generateModule(CodegenFactory.kt:67)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.doGenerateFiles(KotlinCodegenFacade.java:47)
	at org.jetbrains.kotlin.codegen.KotlinCodegenFacade.compileCorrectFiles(KotlinCodegenFacade.java:39)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.generate(KotlinToJVMBytecodeCompiler.kt:637)
	at org.jetbrains.kotlin.cli.jvm.compiler.KotlinToJVMBytecodeCompiler.compileModules$cli(KotlinToJVMBytecodeCompiler.kt:195)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:165)
	at org.jetbrains.kotlin.cli.jvm.K2JVMCompiler.doExecute(K2JVMCompiler.kt:55)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:84)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.kt:42)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:104)
	at org.jetbrains.kotlin.daemon.CompileServiceImpl.compile(CompileServiceImpl.kt:1479)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at java.rmi/sun.rmi.server.UnicastServerRef.dispatch(UnicastServerRef.java:359)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:200)
	at java.rmi/sun.rmi.transport.Transport$1.run(Transport.java:197)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.Transport.serviceCall(Transport.java:196)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport.handleMessages(TCPTransport.java:562)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run0(TCPTransport.java:796)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.lambda$run$0(TCPTransport.java:677)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.rmi/sun.rmi.transport.tcp.TCPTransport$ConnectionHandler.run(TCPTransport.java:676)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.jetbrains.kotlin.utils.KotlinExceptionWithAttachments: Couldn't compute ASM type for expression
	at org.jetbrains.kotlin.codegen.binding.CodegenBinding.asmTypeForAnonymousClass(CodegenBinding.java:122)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.generateObjectLiteral(ExpressionCodegen.java:225)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.visitObjectLiteralExpression(ExpressionCodegen.java:1051)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.visitObjectLiteralExpression(ExpressionCodegen.java:112)
	at org.jetbrains.kotlin.psi.KtObjectLiteralExpression.accept(KtObjectLiteralExpression.java:30)
	at org.jetbrains.kotlin.codegen.ExpressionCodegen.genQualified(ExpressionCodegen.java:302)
	... 88 more

**Comment by swankjesse** [comment]
I build with IntelliJ myself. The admittedly short gradle instructions are expected to be comprehensive; why describe dependencies in text when the build.gradle file can do that for us?

**Comment by yschimke** [comment]
Generally Intellij should *just* work when you import the build.gradle.  

Most common actions in this flow

1) Import and Build in Intellij - should *just* work.
2) Test locally - as described in the contributing doc.  ./gradlew test
3) Submit PR - should just work based on a simple github flow.  Just create a PR against our project and it shows whether it runs.  n.b. we have a few high value but flaky tests that mean a second run is required.  We build against multiple platforms to ensure that our code runs on JDK 8 -> JDK 13.

**Comment by yschimke** [comment]
Android studio and Developing against Android is where it's awkward, and we don't expect most people to tackle.  We don't advertise this in the instructions you read for this reason.

Instructions here https://github.com/square/okhttp/blob/master/android-test/README.md

1. Editing in Android Studio - This requires editing the lines you mention above, mostly comment them out temporarily, because Android Studio doesn't like you coding against JDK11.
2. Test locally - ANDROID_SDK_ROOT=XXX/Android/sdk ./gradlew :android-test:connectedCheck

**Comment by swankjesse** [comment]
Not sure what action we’ll take on this.
