### ISSUE TITLE
Logging interceptor causes app to crash in some cases

### ISSUE THREAD

**Issue by H4kt** [square/okhttp#5783]
Here goes the stacktrace:
`2020-02-13 19:27:43.048 24586-24688/com.flchat E/AndroidRuntime: FATAL EXCEPTION: OkHttp Dispatcher
    Process: com.flchat, PID: 24586
    java.lang.IllegalStateException: closed
        at okio.RealBufferedSource.request(RealBufferedSource.java:66)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:253)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:250)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)`

I cannot write a test for you, because I don't actually know why does it occurs.
Thanks in advance for fixing it.

**Comment by swankjesse** [comment]
Executable test case please? Typically this occurs if you close the response body yourself, such as by reading it as a string.

**Comment by fmmarzoa** [comment]
I'm seeing this issue too now, the crash happens in a line that just calls execute(). The Interceptor uses Java util logger. If I remove the interceptor, then it doesn't crash on the same call.
