### ISSUE TITLE
ConnectionPool.cleanup has ConcurrentModificationException

### ISSUE THREAD

**Issue by zzzzyf** [square/okhttp#5844]
I use okhttp 3.12.3 and found this crash:
java.util.ConcurrentModificationException	ArrayDeque.java	625
java.util.ConcurrentModificationException
	at java.util.ArrayDeque$DeqIterator.next(ArrayDeque.java:625)
	at okhttp3.ConnectionPool.cleanup(SourceFile:208)
	at okhttp3.ConnectionPool$1.run(SourceFile:60)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

**Comment by yschimke** [comment]
What's the crash rate? Any stats to judge the severity? We generally only bàckport critical fixes

**Comment by yschimke** [comment]
Unless you can provide more details, phone, VM, crash rates etc.  I suspect this might be a dodgy VM on a wild phone etc.  Closing for now if we can't repro this.
