### ISSUE TITLE
conscrypt: Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.platform.ConscryptPlatform$configureTrustManager$1>

### ISSUE THREAD

**Issue by rinav** [square/okhttp#5894]
I am unable to make network calls if I skip including conscrypt library
Following is the okhttp setup on the android app.
Do let me know if more info is required

okhttp version: `4.4.1`
retrofit version: `2.7.2`
okio version: `2.4.3`
    
    @Provides
    @Singleton
    fun provideClient(cache: Cache): OkHttpClient {
        return OkHttpClient.Builder()
            .cache(cache)
            .addNetworkInterceptor(networkCacheInterceptor())
            .addInterceptor(provideHttpLoggingInterceptor())
            .connectTimeout(1, TimeUnit.MINUTES)
            .readTimeout(1, TimeUnit.MINUTES)
            .writeTimeout(2, TimeUnit.MINUTES)
            .build()
    }

retrofit config

    @Provides
    @Singleton
    fun provideRetrofit(client: OkHttpClient): Retrofit {
        return Retrofit.Builder()
            .baseUrl(BuildConfig.BASE_URL)
            .client(client)
            .addCallAdapterFactory(LiveDataCallAdapterFactory())
            .addConverterFactory(GsonConverterFactory.create())
            .build()
    }

Following is the stack trace which I get while making network call

	I: Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.platform.ConscryptPlatform$configureTrustManager$1>: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/conscrypt/ConscryptHostnameVerifier;
	I:     at okhttp3.internal.platform.android.SocketAdapter okhttp3.internal.platform.android.ConscryptSocketAdapter$Companion.buildIfSupported() (ConscryptSocketAdapter.kt:62)
	I:     at void okhttp3.internal.platform.AndroidPlatform.<init>() (AndroidPlatform.kt:44)
	I:     at okhttp3.internal.platform.Platform okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported() (AndroidPlatform.kt:212)
	I:     at okhttp3.internal.platform.Platform okhttp3.internal.platform.Platform$Companion.findPlatform() (Platform.kt:212)
	I:     at okhttp3.internal.platform.Platform okhttp3.internal.platform.Platform$Companion.access$findPlatform(okhttp3.internal.platform.Platform$Companion) (Platform.kt:169)
	I:     at void okhttp3.internal.platform.Platform.<clinit>() (Platform.kt:170)
	I:     at void okhttp3.OkHttpClient.<init>(okhttp3.OkHttpClient$Builder) (OkHttpClient.kt:224)
	I:     at okhttp3.OkHttpClient okhttp3.OkHttpClient$Builder.build() (OkHttpClient.kt:1025)
	I:     at okhttp3.OkHttpClient com.xxx.di.module.NetworkModule.provideClient(okhttp3.Cache) (NetworkModule.kt:79)
	I:     at okhttp3.OkHttpClient com.xxx.di.module.NetworkModule_ProvideClientFactory.provideClient(com.xxx.di.module.NetworkModule, okhttp3.Cache) (NetworkModule_ProvideClientFactory.java:35)
	I:     at okhttp3.OkHttpClient com.xxx.di.module.NetworkModule_ProvideClientFactory.get() (NetworkModule_ProvideClientFactory.java:26)
	I:     at okhttp3.internal.platform.android.SocketAdapter okhttp3.internal.platform.android.ConscryptSocketAdapter$Companion.buildIfSupported() (ConscryptSocketAdapter.kt:62)
	I:     at void okhttp3.internal.platform.AndroidPlatform.<init>() (AndroidPlatform.kt:44)
	I:     at okhttp3.internal.platform.Platform okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported() (AndroidPlatform.kt:212)
	I:     at okhttp3.internal.platform.Platform okhttp3.internal.platform.Platform$Companion.findPlatform() (Platform.kt:212)
	I:     at okhttp3.internal.platform.Platform okhttp3.internal.platform.Platform$Companion.access$findPlatform(okhttp3.internal.platform.Platform$Companion) (Platform.kt:169)
	I:     at void okhttp3.internal.platform.Platform.<clinit>() (Platform.kt:170)
	I:     at void okhttp3.OkHttpClient.<init>(okhttp3.OkHttpClient$Builder) (OkHttpClient.kt:224)
	I:     at okhttp3.OkHttpClient okhttp3.OkHttpClient$Builder.build() (OkHttpClient.kt:1025)
	I:     at okhttp3.OkHttpClient com.xxx.di.module.NetworkModule.provideClient(okhttp3.Cache) (NetworkModule.kt:79)
	I:     at okhttp3.OkHttpClient com.xxx.di.module.NetworkModule_ProvideClientFactory.provideClient(com.xxx.di.module.NetworkModule, okhttp3.Cache) (NetworkModule_ProvideClientFactory.java:35)
	I:     at okhttp3.OkHttpClient com.xxx.di.module.NetworkModule_ProvideClientFactory.get() (NetworkModule_ProvideClientFactory.java:26)
	I: Rejecting re-init on previously-failed class java.lang.Class<okhttp3.internal.platform.ConscryptPlatform$configureTrustManager$1>: java.lang.NoClassDefFoundError: Failed resolution of: Lorg/conscrypt/ConscryptHostnameVerifier;
	I:     at okhttp3.internal.platform.android.SocketAdapter okhttp3.internal.platform.android.ConscryptSocketAdapter$Companion.buildIfSupported() (ConscryptSocketAdapter.kt:62)
	I:     at void okhttp3.internal.platform.AndroidPlatform.<init>() (AndroidPlatform.kt:44)
	I:     at okhttp3.internal.platform.Platform okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported() (AndroidPlatform.kt:212)
	I:     at okhttp3.internal.platform.Platform okhttp3.internal.platform.Platform$Companion.findPlatform() (Platform.kt:212)
	I:     at okhttp3.internal.platform.Platform okhttp3.internal.platform.Platform$Companion.access$findPlatform(okhttp3.internal.platform.Platform$Companion) (Platform.kt:169)
	I:     at void okhttp3.internal.platform.Platform.<clinit>() (Platform.kt:170)
	I:     at void okhttp3.OkHttpClient.<init>(okhttp3.OkHttpClient$Builder) (OkHttpClient.kt:224)
	I:     at okhttp3.OkHttpClient okhttp3.OkHttpClient$Builder.build() (OkHttpClient.kt:1025)
	I:     at okhttp3.OkHttpClient com.xxx.di.module.NetworkModule.provideClient(okhttp3.Cache) (NetworkModule.kt:79)
	I:     at okhttp3.OkHttpClient com.xxx.di.module.NetworkModule_ProvideClientFactory.provideClient(com.xxx.di.module.NetworkModule, okhttp3.Cache) (NetworkModule_ProvideClientFactory.java:35)
	I:     at okhttp3.OkHttpClient com.xxx.di.module.NetworkModule_ProvideClientFactory.get() (NetworkModule_ProvideClientFactory.java:26)
	I:     at okhttp3.internal.platform.android.SocketAdapter okhttp3.internal.platform.android.ConscryptSocketAdapter$Companion.buildIfSupported() (ConscryptSocketAdapter.kt:62)
	I:     at void okhttp3.internal.platform.AndroidPlatform.<init>() (AndroidPlatform.kt:44)
	I:     at okhttp3.internal.platform.Platform okhttp3.internal.platform.AndroidPlatform$Companion.buildIfSupported() (AndroidPlatform.kt:212)
	I:     at okhttp3.internal.platform.Platform okhttp3.internal.platform.Platform$Companion.findPlatform() (Platform.kt:212)
	I:     at okhttp3.internal.platform.Platform okhttp3.internal.platform.Platform$Companion.access$findPlatform(okhttp3.internal.platform.Platform$Companion) (Platform.kt:169)
	I:     at void okhttp3.internal.platform.Platform.<clinit>() (Platform.kt:170)
	I:     at void okhttp3.OkHttpClient.<init>(okhttp3.OkHttpClient$Builder) (OkHttpClient.kt:224)
	I:     at okhttp3.OkHttpClient okhttp3.OkHttpClient$Builder.build() (OkHttpClient.kt:1025)
	I:     at okhttp3.OkHttpClient com.xxx.di.module.NetworkModule.provideClient(okhttp3.Cache) (NetworkModule.kt:79)
	I:     at okhttp3.OkHttpClient com.xxx.di.module.NetworkModule_ProvideClientFactory.provideClient(com.xxx.di.module.NetworkModule, okhttp3.Cache) (NetworkModule_ProvideClientFactory.java:35)
	I:     at okhttp3.OkHttpClient com.xxx.di.module.NetworkModule_ProvideClientFactory.get() (NetworkModule_ProvideClientFactory.java:26)
	W: [AppCertManager] IOException while requesting key: 
	    java.net.SocketTimeoutException: timeout
	        at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)
	        at com.android.okhttp.okio.AsyncTimeout.exit(AsyncTimeout.java:261)
	        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:215)
	        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:306)
	        at com.android.okhttp.okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	        at com.android.okhttp.okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	        at com.android.okhttp.internal.http.Http1xStream.readResponse(Http1xStream.java:186)
	        at com.android.okhttp.internal.http.Http1xStream.readResponseHeaders(Http1xStream.java:127)
	        at com.android.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:737)
	        at com.android.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:609)
	        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:471)
	        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:407)
	        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:538)
	        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getResponseCode(DelegatingHttpsURLConnection.java:105)
	        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getResponseCode(Unknown Source:0)
	        at abxc.a(:com.google.android.gms@200914022@20.09.14 (040700-300565878):31)
	        at joq.a(:com.google.android.gms@200914022@20.09.14 (040700-300565878):5)
	        at hav.a(:com.google.android.gms@200914022@20.09.14 (040700-300565878):9)
	        at hav.a(:com.google.android.gms@200914022@20.09.14 (040700-300565878):5)
	        at ipd.a(:com.google.android.gms@200914022@20.09.14 (040700-300565878):31)
	        at ipb.a(:com.google.android.gms@200914022@20.09.14 (040700-300565878):41)
	        at iow.a(:com.google.android.gms@200914022@20.09.14 (040700-300565878):0)
	        at ioz.a(:com.google.android.gms@200914022@20.09.14 (040700-300565878):10)
	        at gzp.call(:com.google.android.gms@200914022@20.09.14 (040700-300565878):5)
	        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	        at tad.b(:com.google.android.gms@200914022@20.09.14 (040700-300565878):12)
	        at tad.run(:com.google.android.gms@200914022@20.09.14 (040700-300565878):7)
	        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
	        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
	        at tgd.run(:com.google.android.gms@200914022@20.09.14 (040700-300565878):0)
	        at java.lang.Thread.run(Thread.java:764)
	     Caused by: java.net.SocketException: socket is closed
	        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket$SSLInputStream.read(:com.google.android.gms@200914022@20.09.14 (040700-300565878):7)
	        at com.android.okhttp.okio.Okio$2.read(Okio.java:136)
	        at com.android.okhttp.okio.AsyncTimeout$2.read(AsyncTimeout.java:211)

**Comment by yschimke** [comment]
The first exception logged is unrelated to the second.  You are just getting a bog standard timeout.  Either raise your timeouts or look at the server.

Consider using a listener to print out the events

https://square.github.io/okhttp/events/

**Comment by yschimke** [comment]
Closing as this is not a reproducible bug.  The spam from Android is unrelated.

**Comment by castor55** [comment]
I see this issue on my side.

**Comment by elirehema** [comment]
`implementation 'org.conscrypt:conscrypt-android:2.2.1'`

**Comment by yschimke** [comment]
From the original report there are two log events

Info: "Rejecting re-init on previously-failed class" - This is purely a warning by Android, not an issue.

Then a generic network error that is unrelated

Warning: "[AppCertManager] IOException while requesting key: 
    java.net.SocketTimeoutException: timeout
        at com.android.okhttp.okio.Okio$3.newTimeoutException(Okio.java:212)"

**Comment by yschimke** [comment]
@elirehema This dependency is not required.  Android is logging an INFO message that is not critical.

> `implementation 'org.conscrypt:conscrypt-android:2.2.1'`

**Comment by elirehema** [comment]
@yschimke I used it and resolved my problem
