### ISSUE TITLE
:android-test:connectedCheck fails to run with duplicate class files

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5902]
```
Caused by: com.android.tools.r8.utils.AbortException: Error: Program type already present: okhttp3.CallEvent$CallFailed
        at com.android.tools.r8.utils.Reporter.failIfPendingErrors(Reporter.java:101)
        at com.android.tools.r8.utils.Reporter.fatalError(Reporter.java:72)
        at com.android.tools.r8.utils.ExceptionUtils.withCompilationHandler(ExceptionUtils.java:66)
        ... 11 more
```

Seemingly because Intellij and gradle output to different paths

```
find . -name \*CallFailed\*
./okhttp-testing-support/build/classes/java/main/okhttp3/CallEvent$CallFailed.class
./okhttp-testing-support/build/classes/kotlin/main/okhttp3/CallEvent$CallFailed.class
```

**Comment by yschimke** [comment]
Example project, command to build

$ ANDROID_SDK_ROOT=XXXX/sdk ./gradlew :android-test:connectedCheck

**Comment by yschimke** [comment]
The main intersting this about this model is that it has both java and kotlin under the same directory tree

```
$ find okhttp-testing-support/src/main/java
okhttp-testing-support/src/main/java
okhttp-testing-support/src/main/java/okhttp3
okhttp-testing-support/src/main/java/okhttp3/FakeProxySelector.java
okhttp-testing-support/src/main/java/okhttp3/ForwardingRequestBody.java
okhttp-testing-support/src/main/java/okhttp3/FakeSSLSession.java
okhttp-testing-support/src/main/java/okhttp3/OkHttpClientTestRule.kt
okhttp-testing-support/src/main/java/okhttp3/ClientRuleEventListener.kt
okhttp-testing-support/src/main/java/okhttp3/internal
okhttp-testing-support/src/main/java/okhttp3/internal/io
okhttp-testing-support/src/main/java/okhttp3/internal/io/InMemoryFileSystem.java
okhttp-testing-support/src/main/java/okhttp3/internal/duplex
okhttp-testing-support/src/main/java/okhttp3/internal/duplex/AsyncRequestBody.java
okhttp-testing-support/src/main/java/okhttp3/UppercaseRequestInterceptor.java
okhttp-testing-support/src/main/java/okhttp3/ForwardingResponseBody.java
okhttp-testing-support/src/main/java/okhttp3/RecordingEventListener.kt
okhttp-testing-support/src/main/java/okhttp3/UppercaseResponseInterceptor.java
okhttp-testing-support/src/main/java/okhttp3/testing
okhttp-testing-support/src/main/java/okhttp3/testing/PlatformVersion.kt
okhttp-testing-support/src/main/java/okhttp3/testing/Flaky.kt
okhttp-testing-support/src/main/java/okhttp3/testing/PlatformRule.kt
okhttp-testing-support/src/main/java/okhttp3/OkHttpDebugLogging.kt
okhttp-testing-support/src/main/java/okhttp3/RecordingCookieJar.java
okhttp-testing-support/src/main/java/okhttp3/CallEvent.kt
okhttp-testing-support/src/main/java/okhttp3/TestUtil.java
okhttp-testing-support/src/main/java/okhttp3/RecordingHostnameVerifier.java
okhttp-testing-support/src/main/java/okhttp3/FakeDns.java
```

**Comment by yschimke** [comment]
Output from

```
$ ./gradlew test --warning-mode all
...
Copying or archiving duplicate paths with the default duplicates strategy has been deprecated. This is scheduled to be removed in Gradle 7.0. Duplicate path: "okhttp3/CallEvent$CallEnd.class". Explicitly set the duplicates strategy to 'DuplicatesStrategy.INCLUDE' if you want to allow duplicate paths. Consult the upgrading guide for further information: https://docs.gradle.org/6.3/userguide/upgrading_version_5.html#implicit_duplicate_strategy_for_copy_or_archive_tasks_has_been_deprecated
```

**Comment by yschimke** [comment]
moving src/main/java to src/main/kotlin appears to fix this in my testing.

**Comment by swankjesse** [comment]
Nice. We should just move everything?

**Comment by yschimke** [comment]
Testing the build if we want to pull the trigger on this https://github.com/square/okhttp/pull/5938/files

**Comment by yschimke** [comment]
@swankjesse Still an issue for tests

```
 find . -name 'CallKotlinTest.*'
./okhttp/build/classes/java/test/okhttp3/CallKotlinTest.class
./okhttp/build/classes/kotlin/test/okhttp3/CallKotlinTest.class
./okhttp/src/test/java/okhttp3/CallKotlinTest.kt
```

It manifests in two ways, either conflicts in gradle builds, or stale results when running tests since two classes can be out of sync.
