### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException Util.checkOffsetAndCount(Util.java:30)

### ISSUE THREAD

**Issue by pnkshir** [square/okhttp#5923]
We are using OkHttpp version com.squareup.okhttp3:okhttp "3.14.2" and getting following crash for some users. We could not reproduce, but as traced from crashlytics we get this crash

Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: size=0 offset=0 byteCount=2048
at com.android.okhttp.okio.Util.checkOffsetAndCount(Util.java:30)
at com.android.okhttp.okio.Buffer.write(Buffer.java:1178)
at com.android.okhttp.okio.Buffer.read(Buffer.java:1221)
at com.android.okhttp.okio.RealBufferedSource.read(RealBufferedSource.java:55)
at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.read(Http1xStream.java:393)
at com.android.okhttp.internal.Util.skipAll(Util.java:159)
at com.android.okhttp.internal.Util.discard(Util.java:141)
at com.android.okhttp.internal.http.Http1xStream$FixedLengthSource.close(Http1xStream.java:410)
at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:396)
at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:384)
at com.google.android.gms.internal.firebase_messaging.zzk.zza(zzk.java:4)
at com.google.firebase.messaging.zzm.close(zzm.java:37)
at com.google.firebase.messaging.zzd.zza(zzd.java:51)
at com.google.firebase.messaging.FirebaseMessagingService.zzc(FirebaseMessagingService.java:69)
at com.google.firebase.messaging.zze.run(zze.java:2)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at com.google.android.gms.common.util.concurrent.zza.run(zza.java:6)
at java.lang.Thread.run(Thread.java:764)

**Comment by JakeWharton** [comment]
This exception comes from the Android framework's version of OkHttp, not the version you have bundled into your application. You can report framework bugs to http://b.android.com/new.
