### ISSUE TITLE
WebSocketHttpTest.serverMaxWindowBitsTooHigh() is flaky

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#5935]
```
okhttp3.internal.ws.WebSocketHttpTest > serverMaxWindowBitsTooHigh FAILED
    java.lang.AssertionError: expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at okhttp3.OkHttpClientTestRule.ensureAllConnectionsReleased(OkHttpClientTestRule.kt:93)
        at okhttp3.OkHttpClientTestRule$apply$1.evaluate(OkHttpClientTestRule.kt:127)
        at okhttp3.testing.PlatformRule$apply$1.evaluate(PlatformRule.kt:69)
        at okhttp3.TestLogHandler$1.evaluate(TestLogHandler.java:50)
```
https://app.circleci.com/pipelines/github/square/okhttp/2891/workflows/a8324886-5feb-4570-ba79-8997947cd50f/jobs/11790

**Comment by yschimke** [comment]
Damn, that is one flaky test!

**Comment by yschimke** [comment]
No longer as flaky? https://circleci.com/build-insights/gh/square/okhttp/master
