### ISSUE TITLE
Flaky windows test

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5948]
https://app.circleci.com/pipelines/github/square/okhttp/2946/workflows/dafc20ae-fd8a-4f0b-a185-eb8a13723158/jobs/12108

```
okhttp3.CallTest > interceptorGetsHttp2 FAILED
    java.lang.NullPointerException
        at java.base/java.io.FileDescriptor$1.get(FileDescriptor.java:76)
        at java.base/java.net.PlainSocketImpl.checkAndReturnNativeFD(PlainSocketImpl.java:309)
        at java.base/java.net.PlainSocketImpl.socketShutdown(PlainSocketImpl.java:204)
        at java.base/java.net.AbstractPlainSocketImpl.shutdownOutput(AbstractPlainSocketImpl.java:619)
        at java.base/java.net.Socket.shutdownOutput(Socket.java:1556)
        at java.base/sun.security.ssl.BaseSSLSocketImpl.shutdownOutput(BaseSSLSocketImpl.java:234)
        at java.base/sun.security.ssl.SSLSocketImpl.duplexCloseOutput(SSLSocketImpl.java:561)
        at java.base/sun.security.ssl.SSLSocketImpl.close(SSLSocketImpl.java:479)
        at okhttp3.internal.Util.closeQuietly(Util.kt:500)
        at okhttp3.internal.connection.RealConnectionPool.evictAll(RealConnectionPool.kt:127)
        at okhttp3.ConnectionPool.evictAll(ConnectionPool.kt:57)
        at okhttp3.OkHttpClientTestRule.ensureAllConnectionsReleased(OkHttpClientTestRule.kt:92)
        at okhttp3.OkHttpClientTestRule$apply$1.evaluate(OkHttpClientTestRule.kt:127)
        at okhttp3.internal.io.InMemoryFileSystem$apply$1.evaluate(InMemoryFileSystem.kt:41)
        at okhttp3.testing.PlatformRule$apply$1.evaluate(PlatformRule.kt:69)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
        at okhttp3.TestLogHandler$1.evaluate(TestLogHandler.java:50)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:288)
        at org.junit.internal.runners.statements.FailOnTimeout$CallableStatement.call(FailOnTimeout.java:282)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.lang.Thread.run(Thread.java:835)
```

**Comment by yschimke** [comment]
Think this was platform/version specific.  Reopen if seen again.  In recent JDK11 it's guarded with a null check.
