### ISSUE TITLE
ContextException

### ISSUE THREAD

**Issue by Mrtol** [square/okhttp#5964]
net.dv8tion.jda.api.exceptions.ErrorResponseException: -1: okhttp3.internal.http2.StreamResetException
	at net.dv8tion.jda.api.exceptions.ErrorResponseException.create(ErrorResponseException.java:158)
	at net.dv8tion.jda.api.requests.Request.onFailure(Request.java:104)
	at net.dv8tion.jda.internal.requests.RestActionImpl.handleResponse(RestActionImpl.java:238)
	at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:199)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:259)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:144)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:127)
	at net.dv8tion.jda.internal.requests.ratelimit.BotRateLimiter$Bucket.run(BotRateLimiter.java:416)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:830)
Caused by: okhttp3.internal.http2.StreamResetException: stream was reset: REFUSED_STREAM
	at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:148)
	at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:74)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197)
	at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148)
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:204)
	... 9 more
Caused by: net.dv8tion.jda.api.exceptions.ContextException
	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:52)
	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:64)
	at net.dv8tion.jda.internal.requests.RestActionImpl.queue(RestActionImpl.java:167)
	at net.dv8tion.jda.api.requests.RestAction.queue(RestAction.java:320)
	at me.mrtol.marpel.BüyükSistemler.Loglar.entry(Loglar.java:114)
	at me.mrtol.marpel.BüyükSistemler.Loglar.lambda$onVoiceChannelUpdateName$15(Loglar.java:781)
	... 3 more

Loglar:114
![image](https://user-images.githubusercontent.com/41306224/79730124-09bbed80-82f9-11ea-82f9-d485d76cdfc2.png)

Loglar:781
![image](https://user-images.githubusercontent.com/41306224/79730097-032d7600-82f9-11ea-92b7-c8a8b51a5f2f.png)

**Comment by yschimke** [comment]
The inner most two exceptions are from a library we don't have access to, and a routine error indicating the server denied your request.  Suggest opening a question on stackoverflow for usage help.  This is not reproducible for us.

**Comment by MinnDevelopment** [comment]
Only the innermost exception is from a different library and it is not the cause of the issue. The ContextException is added after okhttp threw to add the stack context for an async callback.

**Comment by yschimke** [comment]
If you post a link to stackoverflow with example code, we can continue the discussion there.
