### ISSUE TITLE
Add CI Tests with JDK 8 252

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#5976]
```-------------------------------------------------------------------------------
Test set: okhttp3.tls.HandshakeCertificatesTest
-------------------------------------------------------------------------------
Tests run: 3, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.55 s <<< FAILURE! - in okhttp3.tls.HandshakeCertificatesTest
clientAndServer(okhttp3.tls.HandshakeCertificatesTest)  Time elapsed: 0.409 s  <<< ERROR!
java.util.concurrent.ExecutionException: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at okhttp3.tls.HandshakeCertificatesTest.clientAndServer(HandshakeCertificatesTest.java:93)
Caused by: javax.net.ssl.SSLHandshakeException: Remote host closed connection during handshake
        at okhttp3.tls.HandshakeCertificatesTest.lambda$doServerHandshake$0(HandshakeCertificatesTest.java:159)
Caused by: java.io.EOFException: SSL peer shut down incorrectly
        at okhttp3.tls.HandshakeCertificatesTest.lambda$doServerHandshake$0(HandshakeCertificatesTest.java:159)
```

**Comment by yschimke** [comment]
Won't fix for now.  We haven't settled on Circle CI and it isn't trivial given we build with JDK 11
