### ISSUE TITLE
OkHttp 3.x failed to get ALPN selected protocol when used with Java HotSpot 1.8.0_251

### ISSUE THREAD

**Issue by geoffrey-thomas** [square/okhttp#6000]
After JDK upgrade to Java HotSpot 1.8.0_251, okhttp thinks that the platform to be used is Jdk9Platform, and it fails at Jdk9Platform.getSelectedProtocol(Jdk9Platform.java:68). Stack trace is provided below.

This is an issue identical to https://github.com/square/okhttp/issues/5970, except that Java HotSpot 1.8.0_251 is used here.

Are there any plans to provide a fix for this in okhttp 3.14.x? If so, when can it be expected?

Thanks

> 
Caused by: **java.lang.AssertionError: failed to get ALPN selected protocol**
        at okhttp3.internal.platform.**Jdk9Platform.getSelectedProtocol(Jdk9Platform.java:68)**
        at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:347)
        at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:284)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:169)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocation.java:135)
        at okhttp3.internal.connection.StreamAllocation.newStream(StreamAllocation.java:114)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:42)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:125)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:264)
        at okhttp3.RealCall.execute(RealCall.java:93)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.GeneratedMethodAccessor337.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at okhttp3.internal.platform.Jdk9Platform.getSelectedProtocol(Jdk9Platform.java:58)
        ... 78 more
Caused by: java.lang.UnsupportedOperationException
        at javax.net.ssl.SSLSocket.getApplicationProtocol(SSLSocket.java:691)
        ... 82 more

**Comment by yschimke** [comment]
It's probably a small number of days for a maintenance release of 3.12.x and 3.14.x.

FWIW - this problem you see indicates another problem for you.  alpn-boot won't work with these versions, so you'll fallback to HTTP/1.1.  And in the case of #5970 the fix needed was to a custom Socket implementation in the Zulu JVM.  So it's worth understanding that also.

**Comment by yschimke** [comment]
https://square.github.io/okhttp/changelog_3x/

**Comment by geoffrey-thomas** [comment]
Thanks for the heads up. Fallback to HTTP/1.1 should be fine for now.
