### ISSUE TITLE
Seeing random InterruptedIOException with OkHttp 4.5.0

### ISSUE THREAD

**Issue by arpitmalhotra** [square/okhttp#6018]
I am getting these following interrupted exeptions randomly from okhttp on a post calls using http2. I even have my read/write and call timeouts set to 0 meaning no timeouts as per the documentation. We are not cancelling any future. 

Also added this on 
https://stackoverflow.com/questions/61583744/getting-java-io-interruptedioexception-with-okhttp-4-5-0-randomly

This is my httpclient below

```
        this.client = new OkHttpClient.Builder()
            .protocols(Collections.singletonList(Protocol.H2_PRIOR_KNOWLEDGE)
            .connectionSpecs(Collections.singletonList(ConnectionSpec.CLEARTEXT))
            .connectionPool(new ConnectionPool(20, 30, TimeUnit.SECONDS))
            .readTimeout(0, TimeUnit.MILLISECONDS)
            .writeTimeout(0, TimeUnit.MILLISECONDS)
            .callTimeout(0, TimeUnit.MILLISECONDS)
            .build();
```
Can anyone advise why i am getting these following exceptions and how to possibly fix these

```
java.io.`InterruptedIOException`: null
at okhttp3.internal.http2.Http2Stream.waitForIo$okhttp(Http2Stream.kt:662) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:140) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:96) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148) ~[okhttp-4.5.0.jar:?]
at 
```
and

```
java.io.InterruptedIOException: interrupted
at okio.Timeout.throwIfReached(Timeout.kt:98) ~[okio-2.5.0.jar:?]
at okio.OutputStreamSink.write(JvmOkio.kt:50) ~[okio-2.5.0.jar:?]
at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:103) ~[okio-2.5.0.jar:?]
at okio.RealBufferedSink.flush(RealBufferedSink.kt:247) ~[okio-2.5.0.jar:?]
at okhttp3.internal.http2.Http2Writer.flush(Http2Writer.kt:120) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http2.Http2Connection.flush(Http2Connection.kt:408) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http2.Http2Stream$FramingSink.close(Http2Stream.kt:626) ~[okhttp-4.5.0.jar:?]
at okio.ForwardingSink.close(ForwardingSink.kt:37) ~[okio-2.5.0.jar:?]
at okhttp3.internal.connection.Exchange$RequestBodySink.close(Exchange.kt:242) ~[okhttp-4.5.0.jar:?]
at okio.RealBufferedSink.close(RealBufferedSink.kt:268) ~[okio-2.5.0.jar:?]
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:60) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:100) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:197) ~[okhttp-4.5.0.jar:?]
at okhttp3.internal.connection.RealCall.execute(RealCall.kt:148) ~[okhttp-4.5.0.jar:?]
at c
```

**Comment by yschimke** [comment]
Stackoverflow is the right place to ask a question like this.  Please reopen this with a reproducible test case, as is we can't investigate this.
