### ISSUE TITLE
Flaky test report

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6033]
From last 100 failed builds, filtered to master branch 

```
1	okhttp3.DuplexTest.duplexWithAuthChallenge
1	okhttp3.EventListenerTest.authenticatingTunnelProxyConnect
1	okhttp3.EventListenerTest.failedDribbledCallEventSequence
1	okhttp3.EventListenerTest.requestBodyFailHttp2OverHttps
1	okhttp3.EventListenerTest.secureConnectWithTunnel
1	okhttp3.EventListenerTest.successfulSecureConnect
1	okhttp3.EventListenerTest.timeToFirstByteHttp2OverHttps
1	okhttp3.WholeOperationTimeoutTest.timeoutReadingResponse
1	okhttp3.internal.concurrent.TaskRunnerTest.cancelWhileExecutingDoesNotStopUncancelableTask
10	okhttp3.internal.http.CancelTest.cancelAndFollowup[(CANCEL, H2)]
4	okhttp3.internal.http.CancelTest.cancelAndFollowup[(CANCEL, HTTP)]
3	okhttp3.internal.http.CancelTest.cancelAndFollowup[(CANCEL, HTTPS)]
2	okhttp3.internal.http2.Http2ConnectionTest.readTimesOut
1	okhttp3.internal.http2.HttpOverHttp2Test.connectionNotReusedAfterShutdown[h2]
1	okhttp3.internal.http2.HttpOverHttp2Test.connectionWindowUpdateAfterCanceling[h2_prior_knowledge]
1	okhttp3.internal.http2.HttpOverHttp2Test.connectionWindowUpdateOnClose[h2_prior_knowledge]
3	okhttp3.internal.http2.HttpOverHttp2Test.responseHeadersAfterGoaway[h2_prior_knowledge]
2	okhttp3.internal.tls.CertificatePinnerChainValidationTest.pinRootNotPresentInChain
1	okhttp3.internal.ws.RealWebSocketTest.pingOnInterval
1	okhttp3.internal.ws.RealWebSocketTest.unacknowledgedPingFailsConnection
2	okhttp3.internal.ws.RealWebSocketTest.unexpectedPongsDoNotInterfereWithFailureDetection
2	okhttp3.internal.ws.WebSocketHttpTest.clientMaxWindowBitsIncluded
3	okhttp3.internal.ws.WebSocketHttpTest.closeReasonMaximumLength
1	okhttp3.internal.ws.WebSocketHttpTest.closeReasonTooLong
2	okhttp3.internal.ws.WebSocketHttpTest.compressedMessages
3	okhttp3.internal.ws.WebSocketHttpTest.unexpectedExtensionParameter
2	okhttp3.internal.ws.WebSocketHttpTest.webSocketsDontTriggerEventListener
9	okhttp3.logging.LoggingEventListenerTest.connectFail
```

**Comment by yschimke** [comment]
```
org.junit.ComparisonFailure: expected:<...tionAcquired",
    "[Canceled",
    "ResponseFai]led",
    "Connectio...> but was:<...tionAcquired",
    "[ResponseFailed",
    "Cance]led",
    "Connectio...>
	at jdk.internal.reflect.GeneratedConstructorAccessor44.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:500)
	at okhttp3.internal.http.CancelTest.cancelAndFollowup(CancelTest.kt:238)
org.junit.ComparisonFailure: expected:<...tionAcquired",
    "[Canceled",
    "ResponseFai]led",
    "Connectio...> but was:<...tionAcquired",
    "[ResponseFailed",
    "Cance]led",
    "Connectio...>
org.junit.ComparisonFailure: expected:<...tionAcquired",
    "[Canceled",
    "ResponseFai]led",
    "Connectio...> but was:<...tionAcquired",
    "[ResponseFailed",
    "Cance]led",
    "Connectio...>
org.junit.ComparisonFailure: expected:<...tionAcquired",
    "[Canceled",
    "ResponseFai]led",
    "Connectio...> but was:<...tionAcquired",
    "[ResponseFailed",
    "Cance]led",
    "Connectio...>
org.junit.ComparisonFailure: expected:<...tionAcquired",
    "[Canceled",
    "ResponseFai]led",
    "Connectio...> but was:<...tionAcquired",
    "[ResponseFailed",
    "Cance]led",
    "Connectio...>
org.junit.ComparisonFailure: expected:<...tionAcquired",
    "[Canceled",
    "]ResponseFailed",
   ...> but was:<...tionAcquired",
    "[]ResponseFailed",
   ...>
org.junit.ComparisonFailure: expected:<...ionAcquired",
    "[Canceled",
    "ResponseFai]led",
    "Connecti...> but was:<...ionAcquired",
    "[ResponseFailed",
    "Cance]led",
    "Connecti...>
org.junit.ComparisonFailure: expected:<...ionAcquired",
    "[Canceled",
    "]ResponseFailed",
  ...> but was:<...ionAcquired",
    "[]ResponseFailed",
  ...>
org.junit.ComparisonFailure: expected:<...ionAcquired",
    "[Canceled",
    "]ResponseFailed",
  ...> but was:<...ionAcquired",
    "[]ResponseFailed",
  ...>
org.junit.ComparisonFailure: expected:<...tionAcquired",
    "[Canceled",
    "ResponseFai]led",
    "Connectio...> but was:<...tionAcquired",
    "[ResponseFailed",
    "Cance]led",
    "Connectio...>
org.junit.ComparisonFailure: expected:<...ionAcquired",
    "[Canceled",
    "]ResponseFailed",
  ...> but was:<...ionAcquired",
    "[]ResponseFailed",
  ...>
org.junit.ComparisonFailure: expected:<...ionAcquired",
    "[Canceled",
    "]ResponseFailed",
  ...> but was:<...ionAcquired",
    "[]ResponseFailed",
  ...>
org.junit.ComparisonFailure: expected:<...ionAcquired",
    "[Canceled",
    "]ResponseFailed",
  ...> but was:<...ionAcquired",
    "[]ResponseFailed",
  ...>
org.junit.ComparisonFailure: expected:<...tionAcquired",
    "[Canceled",
    "]ResponseFailed",
   ...> but was:<...tionAcquired",
    "[]ResponseFailed",
   ...>
org.junit.ComparisonFailure: expected:<...ionAcquired",
    "[Canceled",
    "ResponseFailed",
    "ConnectionReleas]ed"]> but was:<...ionAcquired",
    "[ResponseFailed",
    "ConnectionReleased",
    "Cancel]ed"]>
org.junit.ComparisonFailure: expected:<...ionAcquired",
    "[Canceled",
    "]ResponseFailed",
  ...> but was:<...ionAcquired",
    "[]ResponseFailed",
  ...>
org.junit.ComparisonFailure: expected:<...ionAcquired",
    "[Canceled",
    "]ResponseFailed",
  ...> but was:<...ionAcquired",
    "[]ResponseFailed",
  ...>
```

**Comment by yschimke** [comment]
```
java.lang.AssertionError: 
Expecting:
 "[2 ms] connectFailed: null javax.net.ssl.SSLHandshakeException: Handshake failed"
to match pattern:
 "\[\d+ ms] connectFailed: null javax\.net\.ssl\.(?:SSLProtocolException|SSLHandshakeException): (?:Unexpected handshake message: client_hello|Handshake message sequence violation, 1|Read error).*"
	at okhttp3.logging.HttpLoggingInterceptorTest$LogRecorder.assertLogMatch(HttpLoggingInterceptorTest.java:944)
	at okhttp3.logging.LoggingEventListenerTest$LogRecorder.assertLogMatch(LoggingEventListenerTest.java:249)
	at okhttp3.logging.LoggingEventListenerTest.connectFail(LoggingEventListenerTest.java:236)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
```

**Comment by yschimke** [comment]
Remaining 

```
14	okhttp3.internal.ws.WebSocketHttpTest
8	okhttp3.logging.LoggingEventListenerTest
6	okhttp3.internal.http2.HttpOverHttp2Test
3	okhttp3.CallTest
2	okhttp3.internal.http2.Http2ConnectionTest
2	okhttp3.internal.tls.CertificatePinnerChainValidationTest
2	okhttp3.internal.ws.RealWebSocketTest
1	okhttp3.DuplexTest
1	okhttp3.internal.concurrent.TaskRunnerTest
```

**Comment by yschimke** [comment]
Nothing stands out for the WebSocketHttpTest other than they are flaky


https://circleci.com/gh/square/okhttp/13434 Workflows(job_name=testjdk14, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13427 Workflows(job_name=testjdk11, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13421 Workflows(job_name=testjdk12windows, workflow_name=nightly)
https://circleci.com/gh/square/okhttp/13406 Workflows(job_name=testjdk11, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13356 Workflows(job_name=testjdk11, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13350 Workflows(job_name=testjdk8, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13342 Workflows(job_name=testjdk8, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13335 Workflows(job_name=testjdk8, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13283 Workflows(job_name=testjdk8alpn, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13243 Workflows(job_name=testjdk11, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13138 Workflows(job_name=testjdk13, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13108 Workflows(job_name=testjdk14, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13102 Workflows(job_name=testjdk14, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13096 Workflows(job_name=testjdk13, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13095 Workflows(job_name=testjdk8, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13094 Workflows(job_name=testjdk14, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13093 Workflows(job_name=testjdk11, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13091 Workflows(job_name=testjdk13, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13090 Workflows(job_name=testjdk8, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13089 Workflows(job_name=testjdk14, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13087 Workflows(job_name=testjdk11, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13065 Workflows(job_name=testjdk13, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13051 Workflows(job_name=testjdk8alpn, workflow_name=nightly)
https://circleci.com/gh/square/okhttp/13009 Workflows(job_name=testjdk11, workflow_name=commit)
https://circleci.com/gh/square/okhttp/13007 Workflows(job_name=testjdk8, workflow_name=commit)
https://circleci.com/gh/square/okhttp/12999 Workflows(job_name=testjdk8alpn, workflow_name=nightly)
https://circleci.com/gh/square/okhttp/12947 Workflows(job_name=testjdk8alpn, workflow_name=commit)
https://circleci.com/gh/square/okhttp/12905 Workflows(job_name=testjdk8, workflow_name=nightly)

**Comment by yschimke** [comment]
I think we are hiding the root cause though

```
okhttp3.internal.ws.WebSocketHttpTest > serverMaxWindowBitsTooHigh FAILED
    java.lang.AssertionError: expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:89)
        at org.junit.Assert.failNotEquals(Assert.java:835)
        at org.junit.Assert.assertEquals(Assert.java:120)
        at org.junit.Assert.assertEquals(Assert.java:146)
        at okhttp3.OkHttpClientTestRule.ensureAllConnectionsReleased(OkHttpClientTestRule.kt:134)
        at okhttp3.OkHttpClientTestRule$apply$1.evaluate(OkHttpClientTestRule.kt:178)
        at okhttp3.testing.PlatformRule$apply$1.evaluate(PlatformRule.kt:69)
        at okhttp3.TestLogHandler$1.evaluate(TestLogHandler.java:50)
        at org.junit.rules.ExternalResource$1.evaluate(ExternalResource.java:54)
```

**Comment by yschimke** [comment]
Flaky test report shows something unhealthy on that box?

https://13521-5152285-gh.circle-artifacts.com/0/%7E/reports/okhttp/build/reports/tests/test/classes/okhttp3.InterceptorTest.html

```
Events (11)
[0 ms] callStart: Request{method=GET, url=http://localhost:57231/}
[9089 ms] proxySelectStart: http://localhost:57231/
[11811 ms] proxySelectEnd: [DIRECT]
[11811 ms] dnsStart: localhost
[16064 ms] dnsEnd: [localhost/127.0.0.1]
[16588 ms] connectStart: localhost/127.0.0.1:57231 DIRECT
[17835 ms] connectEnd: http/1.1
[19057 ms] connectionAcquired: Connection{localhost:57231, proxy=DIRECT hostAddress=localhost/127.0.0.1:57231 cipherSuite=none protocol=http/1.1}
[22164 ms] connectionReleased
[22165 ms] callEnd
[22849 ms] canceled
```

vs normal

```
Events (16)
[0 ms] callStart: Request{method=GET, url=http://localhost:62676/}
[8 ms] proxySelectStart: http://localhost:62676/
[8 ms] proxySelectEnd: [DIRECT]
[8 ms] dnsStart: localhost
[8 ms] dnsEnd: [localhost/127.0.0.1]
[12 ms] connectStart: localhost/127.0.0.1:62676 DIRECT
[21 ms] connectEnd: http/1.1
[22 ms] connectionAcquired: Connection{localhost:62676, proxy=DIRECT hostAddress=localhost/127.0.0.1:62676 cipherSuite=none protocol=http/1.1}
[25 ms] requestHeadersStart
[26 ms] requestHeadersEnd
[36 ms] responseHeadersStart
[37 ms] responseHeadersEnd: Response{protocol=http/1.1, code=200, message=OK, url=http://localhost:62676/}
[39 ms] responseBodyStart
[39 ms] responseBodyEnd: byteCount=0
[40 ms] connectionReleased
[40 ms] callEnd
```

**Comment by yschimke** [comment]
Last 100 failed builds

```

1	okhttp3.CallTest.canceledAfterResponseIsDeliveredBreaksStreamButSignalsOnce_HTTPS
1	okhttp3.CallTest.canceledBeforeResponseReadSignalsOnFailure_HTTPS
1	okhttp3.CallTest.http205WithBodyDisallowed
1	okhttp3.CallTest.leakedResponseBodyLogsStackTrace
1	okhttp3.CallTest.tlsTimeoutsNotRetried
3	okhttp3.DuplexTest.duplexWithAuthChallenge
1	okhttp3.EventListenerTest.successfulCallEventSequenceWithListener
1	okhttp3.internal.cache.DiskLruCacheTest.aggressiveClearingHandlesEdit[FileSystem.SYSTEM]
1	okhttp3.internal.cache.DiskLruCacheTest.aggressiveClearingHandlesRead[FileSystem.SYSTEM]
1	okhttp3.internal.concurrent.TaskRunnerTest.singleQueueIsSerial
2	okhttp3.internal.http.CancelTest.cancelAndFollowup[(CANCEL, H2)]
1	okhttp3.internal.http.CancelTest.cancelAndFollowup[(CANCEL, HTTP)]
1	okhttp3.internal.http.CancelTest.cancelAndFollowup[(CANCEL, HTTPS)]
1	okhttp3.internal.http2.HttpOverHttp2Test.concurrentRequestWithEmptyFlowControlWindow[h2_prior_knowledge]
1	okhttp3.internal.http2.HttpOverHttp2Test.connectionWindowUpdateOnClose[h2_prior_knowledge]
1	okhttp3.internal.http2.HttpOverHttp2Test.emptyDataFrameSentWithEmptyBody[h2_prior_knowledge]
1	okhttp3.internal.http2.HttpOverHttp2Test.gzippedResponseBody[h2_prior_knowledge]
2	okhttp3.internal.http2.HttpOverHttp2Test.pingsTransmitted[h2_prior_knowledge]
1	okhttp3.internal.http2.HttpOverHttp2Test.recoverFromMultipleCancelReusesConnection[h2_prior_knowledge]
1	okhttp3.internal.http2.HttpOverHttp2Test.recoverFromOneCancelRequiresNewConnection[h2_prior_knowledge]
1	okhttp3.internal.http2.HttpOverHttp2Test.responseHeadersAfterGoaway[h2_prior_knowledge]
1	okhttp3.internal.http2.HttpOverHttp2Test.shutdownAfterLateCoalescing[h2_prior_knowledge]
1	okhttp3.internal.ws.WebSocketHttpTest.callTimeoutDoesNotApplyOnceConnected
1	okhttp3.internal.ws.WebSocketHttpTest.clientDoesNotPingServerByDefault
1	okhttp3.internal.ws.WebSocketHttpTest.throwingOnOpenFailsImmediately
1	okhttp3.internal.ws.WebSocketHttpTest.unacknowledgedPingFailsConnection
1	okhttp3.internal.ws.WebSocketHttpTest.unplannedCloseHandledByCloseWithoutFailure
2	okhttp3.internal.ws.WebSocketHttpTest.wssScheme
12	okhttp3.tls.HeldCertificateTest.decodeMalformed
```
