### ISSUE TITLE
Expected URL scheme 'http' or 'https' but was 'asset'

### ISSUE THREAD

**Issue by spacens** [square/okhttp#6046]
I have ejected an expo project using ExpoKit and it is using okhttp as a dependency.

The project runs successfully without issues in development environment. But when I build a signed apk, I got the following error.

```
E/GlideExecutor: Request threw uncaught throwable
    java.lang.IllegalArgumentException: Expected URL scheme 'http' or 'https' but was 'asset'
        at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:10)
        at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1)
        at okhttp3.Request$Builder.url(Request.kt:6)
        at com.bumptech.glide.integration.okhttp3.a.a(OkHttpStreamFetcher.java:1)
        at com.bumptech.glide.load.b.L.a(SourceGenerator.java:12)
        at com.bumptech.glide.load.b.l.q(DecodeJob.java:4)
        at com.bumptech.glide.load.b.l.r(DecodeJob.java:4)
        at com.bumptech.glide.load.b.l.run(DecodeJob.java:7)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
        at com.bumptech.glide.load.b.c.a.run(GlideExecutor.java:8)
```
I just ejected from expo project and I never used a url that starts with "asset".

It was using okhttp 3.12 so I tried to upgrade to 4.6.0 but only got the same error. Here is the code from my build.gradle.

```
implementation "com.android.support:exifinterface:${safeExtGet("supportLibVersion", "28.0.0")}"
implementation 'com.squareup.okio:okio:1.9.0'
implementation 'com.facebook.soloader:soloader:0.6.0'

// expo-file-system
implementation 'com.squareup.okhttp3:okhttp:4.6.0'
implementation 'com.squareup.okhttp3:okhttp-urlconnection:4.6.0'
```

I have already spent 2 days to debug this issue but nothing helped me. Could you let me know if this is an issue with the library? Or can it be an issue with ExpoKit?

**Comment by JakeWharton** [comment]
Don't know what ExpoKit is but yes it's their bug. OkHttp doesn't handle asset URLs and they would need to route to AssetManager theirselves.
