### ISSUE TITLE
Http1ExchangeCodec NPE while IOException occured during create https proxy tunnel

### ISSUE THREAD

**Issue by LiboDing** [square/okhttp#6048]
OKHttpClient verison: 3.14.8

stack trace as below:
```
java.lang.NullPointerException at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.java:391)
java.lang.NullPointerException: null
        at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.java:391)
        at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.java:427)
        at okhttp3.internal.Util.skipAll(Util.java:204)
        at okhttp3.internal.http1.Http1ExchangeCodec.skipConnectBody(Http1ExchangeCodec.java:308)
        at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.java:403)
        at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:236)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:177)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
        at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
        at okhttp3.RealCall.execute(RealCall.java:81)
```

Occured at create tunnel for proxy https connection, the RealConnection is always null:
```
# RealConnection.java
395 Http1ExchangeCodec tunnelCodec = new Http1ExchangeCodec(null, null, source, sink);
        ... 
403 tunnelCodec.skipConnectBody(response);
```
Http1ExchangeCodec#realConnection is always null in this scenario, so NPE!
```
# Http1ExchangeCodec.java
391    realConnection.noNewExchanges();
```

**Comment by yschimke** [comment]
Fixed here incidentally (I think) on 4.x https://github.com/square/okhttp/pull/5775/files#diff-38746ad5fee2e9a6dd1bf5b4179d7850

Looks reasonably safe to make non-nullable here also.

**Comment by yschimke** [comment]
@LiboDing can you provide more context on what scenario you see this?  JDK or Android versions etc. What sort of operations, frequency.

3.14.x is deprecated, and generally only gets security patches.

**Comment by LiboDing** [comment]
Java 11.0.5
OkHttpClient 3.14.8

The code is very simple: build with proxy, and execute https request.
NPE not occur every time, only occur at https tunnel connection establised but Socket read timeout.
```
public static void main(String[] args) throws IOException {
        String host = "62.33.207.201";
        int port = 3128;
        OkHttpClient okHttpClient = new OkHttpClient.Builder()
            .proxy(new Proxy(Proxy.Type.HTTP, new InetSocketAddress(host, port)))
            .build();
        String url = "https://apps.apple.com/cn/app/%E6%90%BA%E7%A8%8B%E9%87%91%E8%9E%8D-%E5%88%86%E6%9C%9F%E8%B4%B7%E6%AC%BE%E5%80%9F%E9%92%B1/id1388731823?ign-mpt=uo%3D4";
        Response res = okHttpClient.newCall(new Request.Builder().get().url(url).build()).execute();
        System.out.println(res);
    }
```

stack trace is simple as well:
```
Exception in thread "main" java.lang.NullPointerException
	at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.java:391)
	at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.java:427)
	at okhttp3.internal.Util.skipAll(Util.java:204)
	at okhttp3.internal.http1.Http1ExchangeCodec.skipConnectBody(Http1ExchangeCodec.java:308)
	at okhttp3.internal.connection.RealConnection.createTunnel(RealConnection.java:403)
	at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.java:236)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:177)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
	at okhttp3.RealCall.execute(RealCall.java:81)
```
As 3.x has been deprecated, I consider migrate to 4.x

**Comment by yschimke** [comment]
Thanks, reopen if you encounter it on 4.x.  Thanks.
