### ISSUE TITLE
Caused by java.lang.VerifyError: Verifier rejected class com.android.org.conscrypt.ConscryptFileDescriptorSocket

### ISSUE THREAD

**Issue by pnkshir** [square/okhttp#6053]
Hello, we are coming across following crash in crashlytics , for realme 5pro Android OS 10: 

Libraries used : 
com.squareup.okhttp3:okhttp:3.14.2
com.squareup.okhttp3:logging-interceptor:3.14.2
com.squareup.okhttp3:mockwebserver:3.14.2

We could not reproduce it, but able to see it in crashlytcis. Please find the logs below: 
Could you please help on this.

Caused by java.lang.VerifyError: Verifier rejected class com.android.org.conscrypt.ConscryptFileDescriptorSocket: com.android.org.conscrypt.ConscryptSession com.android.org.conscrypt.ConscryptFileDescriptorSocket.provideSession(): [0xFFFFFFFF] exception handler starts at bad address (2)
 void com.android.org.conscrypt.ConscryptFileDescriptorSocket.waitForHandshake() failed to verify: void com.android.org.conscrypt.ConscryptFileDescriptorSocket.waitForHandshake(): [0x3A] unexpected non-exception class Reference: com.android.org.conscrypt.AbstractSessionContext$2 (declaration of 'com.android.org.conscrypt.ConscryptFileDescriptorSocket' appears in /apex/com.android.conscrypt/javalib/conscrypt.jar)
       at com.android.org.conscrypt.Platform.createFileDescriptorSocket(Platform.java:356)
       at com.android.org.conscrypt.OpenSSLSocketFactoryImpl.createSocket(OpenSSLSocketFactoryImpl.java:155)
       at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:325)
       at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:300)
       at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:185)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
       at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
       at com.discovery.sonicclient.SonicClient$SonicRequestInterceptor.intercept(SonicClient.java:1015)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
       at okhttp3.RealCall.execute(RealCall.java:81)
       at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(FirebasePerfOkHttpClient.java:5)
       at retrofit2.OkHttpCall.execute(OkHttpCall.java:188)
       at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:45)
       at io.reactivex.Observable.subscribe(Observable.java:12267)
       at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:34)
       at io.reactivex.Observable.subscribe(Observable.java:12267)
       at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
       at io.reactivex.Single.subscribe(Single.java:3603)
       at io.reactivex.internal.operators.single.SingleResumeNext.subscribeActual(SingleResumeNext.java:39)
       at io.reactivex.Single.subscribe(Single.java:3603)
       at io.reactivex.internal.operators.single.SingleSubscribeOn$SubscribeOnObserver.run(SingleSubscribeOn.java:89)
       at io.reactivex.Scheduler$DisposeTask.run(Scheduler.java:578)
       at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:66)
       at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:57)
       at java.util.concurrent.FutureTask.run(FutureTask.java:266)
       at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:919)

**Comment by yschimke** [comment]
This bug is from within core Android (AOSP), not for OkHttp.
