### ISSUE TITLE
Crash in Android10Platform static initializer

### ISSUE THREAD

**Issue by inat-tv** [square/okhttp#6061]
Hello
I tested with Firebase and gives the following errors.

**Robo test, Nexus 4, Virtual, API Level 19**

```
Significant exception
java.lang.ExceptionInInitializerError
     FATAL EXCEPTION: main
Process: com.renklab.inatpro, PID: 5688
java.lang.ExceptionInInitializerError
	at okhttp3.internal.platform.Android10Platform.<clinit>(Android10Platform.kt:71)
	at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:206)
	at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:168)
	at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:169)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:237)
	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:1069)
	at com.squareup.picasso.OkHttp3Downloader.<init>(OkHttp3Downloader.java:71)
	at com.squareup.picasso.OkHttp3Downloader.<init>(OkHttp3Downloader.java:50)
	at com.squareup.picasso.OkHttp3Downloader.<init>(OkHttp3Downloader.java:40)
	at com.squareup.picasso.Picasso$Builder.build(Picasso.java:848)
	at com.squareup.picasso.Picasso.get(Picasso.java:683)
	at com.renklab.adapter.CategoryAdapter.onBindViewHolder(CategoryAdapter.java:54)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
```

**Robo test, A9 2018, API Level 26**

```
Significant exception
	at okhttp3.Request$Builder.addHeader(Unknown Source:8)
     FATAL EXCEPTION: Thread-8
Process: com.renklab.inatpro, PID: 12167
java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter value
	at okhttp3.Request$Builder.addHeader(Unknown Source:8)
	at com.renklab.fragment.huOkHttpFragment.lambda$onCreateView$6$huOkHttpFragment(huOkHttpFragment.java:209)
	at com.renklab.fragment.-$$Lambda$huOkHttpFragment$syJXiYHVUhA1OyzbvILO4kUVmZI.onClick(Unknown Source:2)
	at android.view.View.performClick(View.java:6909)
	at android.view.View$PerformClick.run(View.java:26199)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at androidx.test.espresso.base.Interrogator.a(Interrogator.java:31)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:132)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:126)
	at androidx.test.espresso.base.UiControllerImpl.a(UiControllerImpl.java:42)
	at androidx.test.espresso.action.MotionEvents.a(MotionEvents.java:75)
	at androidx.test.espresso.action.Tap.b(Tap.java:16)
	at androidx.test.espresso.action.Tap$1.a(Tap.java:2)
	at androidx.test.espresso.action.GeneralClickAction.perform(GeneralClickAction.java:11)
	at androidx.test.espresso.ViewInteraction$SingleExecutionViewAction.perform(ViewInteraction.java:8)
	at androidx.test.espresso.ViewInteraction.a(ViewInteraction.java:33)
	at androidx.test.espresso.ViewInteraction$1.call(ViewInteraction.java:2)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at android.os.Handler.handleCallback(Handler.java:789)
	at android.os.Handler.dispatchMessage(Handler.java:98)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6942)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
```

**Comment by JakeWharton** [comment]
What version of OkHttp?

**Comment by inat-tv** [comment]
> What version of OkHttp?

Okhttp 4.6.0

**Comment by swankjesse** [comment]
For the first error, you need to either downgrade to OkHttp 3.12.x or change your minimum API level to 21. OkHttp has required Android 5.x or better since 3.13.

For the second error, you're passing null to a function that forbids null.

Please don't put two unrelated stacktraces in the same bug going forward, it makes triage more difficult on our end.

**Comment by inat-tv** [comment]
> For the first error, you need to either downgrade to OkHttp 3.12.x or change your minimum API level to 21. OkHttp has required Android 5.x or better since 3.13.
> 
> For the second error, you're passing null to a function that forbids null.
> 
> Please don't put two unrelated stacktraces in the same bug going forward, it makes triage more difficult on our end.

**I tried versions 4.12.0 and 4.12.12 but there is still an error. It gives the following error.**

```
Significant exception
java.lang.ExceptionInInitializerError
     FATAL EXCEPTION: Thread-304
Process: com.renklab.inatpro, PID: 7185
java.lang.ExceptionInInitializerError
	at okhttp3.internal.platform.Android10Platform.<clinit>(Android10Platform.kt:71)
	at okhttp3.internal.platform.Platform$Companion.findPlatform(Platform.kt:206)
	at okhttp3.internal.platform.Platform$Companion.access$findPlatform(Platform.kt:168)
	at okhttp3.internal.platform.Platform.<clinit>(Platform.kt:169)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:237)
	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:1069)
	at com.squareup.picasso.OkHttp3Downloader.<init>(OkHttp3Downloader.java:71)
	at com.squareup.picasso.OkHttp3Downloader.<init>(OkHttp3Downloader.java:50)
	at com.squareup.picasso.OkHttp3Downloader.<init>(OkHttp3Downloader.java:40)
	at com.squareup.picasso.Picasso$Builder.build(Picasso.java:848)
	at com.squareup.picasso.Picasso.get(Picasso.java:683)
	at com.renklab.adapter.CategoryAdapter.onBindViewHolder(CategoryAdapter.java:54)
	at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
	at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
	at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
	at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
	at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
	at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
	at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
	at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
	at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
	at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
	at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
	at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
	at android.view.View.layout(View.java:14817)
	at android.view.ViewGroup.layout(ViewGroup.java:4631)
	at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
	at android.widget.LinearLayout.layoutVertical(LinearLayout.java
Error reporting crash
java.lang.SecurityException: Calling from not trusted UID!
	at android.os.Parcel.readException(Parcel.java:1465)
	at android.os.Parcel.readException(Parcel.java:1419)
	at android.app.ActivityManagerProxy.handleApplicationCrash(ActivityManagerNative.java:3704)
	at com.android.internal.os.RuntimeInit$UncaughtHandler.uncaughtException(RuntimeInit.java:84)
	at androidx.appcompat.app.AppCompatDelegateImpl$1.uncaughtException(AppCompatDelegateImpl.java:177)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:693)
	at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:690)
```

**Comment by inat-tv** [comment]
> For the first error, you need to either downgrade to OkHttp 3.12.x or change your minimum API level to 21. OkHttp has required Android 5.x or better since 3.13.
> 
> For the second error, you're passing null to a function that forbids null.
> 
> Please don't put two unrelated stacktraces in the same bug going forward, it makes triage more difficult on our end.

Picasso Error?

**Comment by inat-tv** [comment]
> For the first error, you need to either downgrade to OkHttp 3.12.x or change your minimum API level to 21. OkHttp has required Android 5.x or better since 3.13.
> 
> For the second error, you're passing null to a function that forbids null.
> 
> Please don't put two unrelated stacktraces in the same bug going forward, it makes triage more difficult on our end.

Latest Log (Picasso)

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.renklab.inatpro, PID: 4777
    java.lang.ExceptionInInitializerError
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015)
        at com.squareup.picasso.OkHttp3Downloader.<init>(OkHttp3Downloader.java:71)
        at com.squareup.picasso.OkHttp3Downloader.<init>(OkHttp3Downloader.java:50)
        at com.squareup.picasso.OkHttp3Downloader.<init>(OkHttp3Downloader.java:40)
        at com.squareup.picasso.Picasso$Builder.build(Picasso.java:848)
        at com.squareup.picasso.Picasso.get(Picasso.java:683)
        at com.renklab.adapter.CategoryAdapter.onBindViewHolder(CategoryAdapter.java:54)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    	at a
