### ISSUE TITLE
InsecureAndroidTrustManager checkServerTrusted fails when using addInsecureHost

### ISSUE THREAD

**Issue by marcorighini** [square/okhttp#6062]
Android, trying to use `okhttp 4.7.0` `addInsecureHost`
```
// clientBuilder: OkHttpClient.Builder
// added some interceptors
...
val clientCertificates = HandshakeCertificates.Builder()
                    .addPlatformTrustedCertificates()
                    .addInsecureHost(proxyHost)
                    .build()
clientBuilder.proxy(Proxy(Proxy.Type.HTTP, InetSocketAddress.createUnresolved(proxyHost, proxyPort)))
clientBuilder.sslSocketFactory(clientCertificates.sslSocketFactory(), clientCertificates.trustManager)
clientBuilder.hostnameVerifier(HostnameVerifier { _, _ -> true })
...
```
but it fails with
```
     Caused by: java.security.cert.CertificateException: java.lang.RuntimeException: java.lang.IllegalArgumentException: Expected receiver of type android.security.net.config.RootTrustManager, but got okhttp3.tls.internal.InsecureAndroidTrustManager
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(:com.google.android.gms@16089023@16.0.89 (040800-239467275):9)
        at com.google.android.gms.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
        at com.google.android.gms.org.conscrypt.NativeSsl.doHandshake(:com.google.android.gms@16089023@16.0.89 (040800-239467275):7)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(:com.google.android.gms@16089023@16.0.89 (040800-239467275):14)
        	... 58 more
     Caused by: java.lang.RuntimeException: java.lang.IllegalArgumentException: Expected receiver of type android.security.net.config.RootTrustManager, but got okhttp3.tls.internal.InsecureAndroidTrustManager
        at com.google.android.gms.org.conscrypt.Platform.checkTrusted(:com.google.android.gms@16089023@16.0.89 (040800-239467275):3)
        at com.google.android.gms.org.conscrypt.Platform.checkServerTrusted(:com.google.android.gms@16089023@16.0.89 (040800-239467275):3)
        at com.google.android.gms.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(:com.google.android.gms@16089023@16.0.89 (040800-239467275):12)
        	... 61 more
     Caused by: java.lang.IllegalArgumentException: Expected receiver of type android.security.net.config.RootTrustManager, but got okhttp3.tls.internal.InsecureAndroidTrustManager
        at java.lang.reflect.Method.invoke(Native Method)
        at okhttp3.tls.internal.InsecureAndroidTrustManager.checkServerTrusted(InsecureAndroidTrustManager.kt:48)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.google.android.gms.org.conscrypt.Platform.checkTrusted(:com.google.android.gms@16089023@16.0.89 (040800-239467275):2)
        	... 63 more
```

target sdk 29
min sdk 23
error on 26 (emulator)

**Comment by yschimke** [comment]
It looks like you are using the Play Provider.  Thanks for raising. I'll take a look this evening if no-one beats me to it.

**Comment by mattinger** [comment]
I am having the same exact issue.  It seems it the code above works only when you actually get a match against the insecure hosts list.  If that doesn't have the host you are talking to, the above error occurs.

**Comment by mattinger** [comment]
It seems like this line in InsecureAndroidTrustManager:

      return method.invoke(this, chain, authType, host) as List<Certificate>


should be passing delegate and not this as the first argument.

**Comment by swankjesse** [comment]
Thanks for the report. Our bad!
