### ISSUE TITLE
Picasso Android 4.4.1 Error?

### ISSUE THREAD

**Issue by inat-tv** [square/okhttp#6070]
My OkHttp3 Version

**testImplementation("com.squareup.okhttp3:mockwebserver:3.12.0")
implementation("com.squareup.okhttp3:okhttp:3.12.0")**

Picasso Version

**implementation 'com.squareup.picasso:picasso:2.71828'**

Error Log

```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.renklab.inatpro, PID: 5273
    java.lang.ExceptionInInitializerError
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015)
        at com.squareup.picasso.OkHttp3Downloader.<init>(OkHttp3Downloader.java:71)
        at com.squareup.picasso.OkHttp3Downloader.<init>(OkHttp3Downloader.java:50)
        at com.squareup.picasso.OkHttp3Downloader.<init>(OkHttp3Downloader.java:40)
        at com.squareup.picasso.Picasso$Builder.build(Picasso.java:848)
        at com.squareup.picasso.Picasso.get(Picasso.java:683)
        at com.renklab.adapter.CategoryAdapter.onBindViewHolder(CategoryAdapter.java:54)
        at androidx.recyclerview.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:7065)
        at androidx.recyclerview.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:7107)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:6012)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:6279)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6118)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:6114)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2303)
        at androidx.recyclerview.widget.GridLayoutManager.layoutChunk(GridLayoutManager.java:561)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1587)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:665)
        at androidx.recyclerview.widget.GridLayoutManager.onLayoutChildren(GridLayoutManager.java:170)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:4134)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3851)
        at androidx.recyclerview.widget.RecyclerView.onLayout(RecyclerView.java:4404)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.RelativeLayout.onLayout(RelativeLayout.java:1055)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at androidx.drawerlayout.widget.DrawerLayout.onLayout(DrawerLayout.java:1231)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:388)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1671)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1525)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1434)
        at android.view.View.layout(View.java:14817)
        at android.view.ViewGroup.layout(ViewGroup.java:4631)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:453)
    	at a
```

My picasso code

 **Picasso.get().load(singleItem.getCategoryImage()).placeholder(R.drawable.place_holder_channel).into(holder.image);**

**Comment by JakeWharton** [comment]
The cause is missing because the exception trace was truncated. You can add an error listener to Picasso to get the exception instance and then log the cause.

**Comment by inat-tv** [comment]
> cause

```
    @Override
    public void onBindViewHolder(@NonNull final RecyclerView.ViewHolder viewHolder, final int position) {
        if (viewHolder.getItemViewType() == VIEW_TYPE_ITEM) {
            final ItemRowHolder holder = (ItemRowHolder) viewHolder;
            final ItemCategory singleItem = dataList.get(position);
            holder.text.setText(singleItem.getCategoryName());
            Picasso.get().load(singleItem.getCategoryImage()).placeholder(R.drawable.place_holder_channel).into(holder.image);
            holder.cardView.setOnClickListener(v -> PopUpAds.showInterstitialAds(mContext, holder.getAdapterPosition(), clickListener));
        }
    }
```

**Comment by yschimke** [comment]
3.12.0 is not the latest version on 3.12.x, can you provide a reproduction using the latest version and reopen the issue.  Without this we can't investigate, and if we find a fix we won't patch the older version anyway.

**Comment by inat-tv** [comment]
> 3.12.0 is not the latest version on 3.12.x, can you provide a reproduction using the latest version and reopen the issue. Without this we can't investigate, and if we find a fix we won't patch the older version anyway.
> 
> Also line numbers don't match 3.12.0 https://github.com/square/okhttp/blob/parent-3.12.0/okhttp/src/main/java/okhttp3/OkHttpClient.java#L263

isn't the latest version 3.12.12? This appears in versions. I also tried this. Are not you reading?

**Comment by yschimke** [comment]
> Are not you reading?

Did I offend you?

I don't see the reference to 3.12.12 in your bug report.

**Comment by inat-tv** [comment]
> > Are not you reading?
> 
> Did I offend you?
> 
> I don't see the reference to 3.12.12 in your bug report.

Sorry. I said it in the previous notification. I tried, but again I encounter this error.
