### ISSUE TITLE
Okhttp 3.12.12 Android 4.4.2 FATAL EXCEPTION

### ISSUE THREAD

**Issue by inat-tv** [square/okhttp#6078]
**Hello there. We have resolved other issues. I am using Okhttp 3.12.12 version. It gives the following error in Android 4.4.2 version. I am making 2 requests. I pull out the data from the first request and put it in the second request as a title. But it doesn't work. No problem on Android 5.**

First request response 
String ↓
String HUHU;

Request response ↓
HUHU = Objects.requireNonNull(matcher1.group(1));

Second request header ↓
.addHeader("watched-sig", HUHU)

**This error only happens on android 4.**
 
```
05-21 11:38:52.582 1889-1889/com.renklab.inatpro E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.renklab.inatpro, PID: 1889
    java.lang.NullPointerException: value for name watched-sig == null
        at okhttp3.Headers.checkValue(Headers.java:268)
        at okhttp3.Headers$Builder.add(Headers.java:312)
        at okhttp3.Request$Builder.addHeader(Request.java:196)
        at com.renklab.fragment.huOkHttpFragment.lambda$onCreateView$6$huOkHttpFragment(huOkHttpFragment.java:212)
        at com.renklab.fragment.-$$Lambda$huOkHttpFragment$syJXiYHVUhA1OyzbvILO4kUVmZI.onClick(lambda)
        at android.view.View.performClick(View.java:4438)
        at android.view.View$PerformClick.run(View.java:18422)
        at android.os.Handler.handleCallback(Handler.java:733)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5019)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
```

**Comment by swankjesse** [comment]
Really looks like you're putting null into a header. Can you make an executable test case to demonstrate the problem?

**Comment by inat-tv** [comment]
> Really looks like you're putting null into a header. Can you make an executable test case to demonstrate the problem?

No, I did not put a null value in the header. It is obvious that it is correct even in log records. There is no problem on Android 5 and above, but there is a problem on Android 4.

**Comment by yschimke** [comment]
Maybe run with a debugger and emulator running 4.4.2.  It's hard without a clean reproduction for us to do anything that you can't do.

**Comment by inat-tv** [comment]
> Maybe run with a debugger and emulator running 4.4.2. It's hard without a clean reproduction for us to do anything that you can't do.
> 
> Or ask on stackoverflow, maybe someone else has seen similar issues.
> 
> We try to keep the open issues in this github issue tracker to things with reproductions of known bugs. Sorry for being a bit dismissive of the bug you are seeing.

It works when you get a get request. but it doesn't work when I make a post request. Do you think it has anything to do with SSL? Or is it the code I wrote? But it just didn't work on android 4.
