### ISSUE TITLE
HTTP/2 negotiation problem, no downgrade - Expected a SETTINGS frame but was 7

### ISSUE THREAD

**Issue by acarlsen** [square/okhttp#6082]
Hi, I have an issue connecting to a web server, that fails in the HTTP/2 protocol negotiation stage (I assume). The problem is intermittent, probably because of the issue with the QNAP web server implementation of HTTP/2. 

If I force OkHttp to use only Protocol.HTTP_1_1 in client builder everything works fine.
I would assume OkHttp to downgrade connection to HTTP 1.1 and retry upon encountering this error. Or maybe at least throw an error than can tell the client it may be a good idea to downgrade connection.

Edit: on OkHttp 4.7.0 and many different Android OS versions.

```
OkHttp: --> PROPFIND https://qnap-webdav-server/
OkHttp: Content-Type: text/xml; charset=utf-8
OkHttp: Content-Length: 277
OkHttp: User-Agent: OkHttp
OkHttp: Translate: f
OkHttp: Pragma: no-cache
OkHttp: Cache-Control: no-cache
OkHttp: Depth: 1
OkHttp: --> END PROPFIND
OkHttp: <-- HTTP FAILED: java.io.IOException: Expected a SETTINGS frame but was 7
2020-05-23 18:31:07.120 30674-30816/dk.tacit.android.foldersync.developer E/foldersync: AccountViewModel$onAuthenticateAccount: Error in testing connection for WebDAV
    java.io.IOException: Expected a SETTINGS frame but was 7
        at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:110)
        at okhttp3.internal.http2.Http2Reader.readConnectionPreface(Http2Reader.kt:72)
        at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:617)
        at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
        at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
        at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
        at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
        at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
    java.io.IOException: Expected a SETTINGS frame but was 7
        at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:110)
        at okhttp3.internal.http2.Http2Reader.readConnectionPreface(Http2Reader.kt:72)
        at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:617)
        at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
        at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
        at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
        at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
        at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

**Comment by yschimke** [comment]
No. I'm not sure any browsers do either. If a webserver is broken and can't respond, users may see errors. 

See if there are any updates to your QNAP device.

We blacklist things like different routes if ISPs can't manage a working IPv6 stack. But no plans for HTTP/2. It's easier to control for client and server. No third party network involved.

**Comment by acarlsen** [comment]
I think its fine that there are errors and client has to handle downgrade to HTTP 1.1 if desired, but it could then perhaps be nice to know at which stage an error such as this happened. The message could perhaps contain a hint that this happens during protocol negotiation, so client can attempt handle it in an nice way, so it won't try to downgrade on unrelated IOException errors.

**Comment by yschimke** [comment]
If it works in other clients like curl then it supports the case of improving handling here. But if it fails generally with clients it's probably worth raising with QNAP.

**Comment by acarlsen** [comment]
Its a user of my app who has the issue with his QNAP NAS - he has made a ticket with QNAP after I told him about the issue. He claims other WebDAV clients had no issues, but they could of course also default to only allow HTTP 1.1 or downgrade on error. Forcing HTTP 1.1 works perfectly, as mentioned, it would just be nice to get a hint that could be a solution.

Also important to note that it fail 50-60% of the time, but not always, so other client may have retries on this part of the negotiation?

**Comment by yschimke** [comment]
Since we likely can't reproduce without a QNAP device, it might be best to wait for response from their support.  But failing that something like a packet capture from Wireshark would also help. Otherwise it's really tough just from an exception trace.

I really honestly believe the optimal solution is getting clients and servers to fix their respective bugs, not workaround them. If it is the server here.  Otherwise you end up raising similar bugs on various client libraries.

**Comment by yschimke** [comment]
We should probably fix up this error message, 7 is go away.

```
  const val TYPE_GOAWAY = 0x7
```

**Comment by yschimke** [comment]
Assuming that there isn't something peculiar here like plaintext HTTP/2 (H2_PRIOR_KNOWLEDGE), then it's likely that we are using ALPN to start a connection, and before we can establish a working HTTP/2 connection (send preface, then receive settings), we are getting a goaway from the server.

This definitely seems like something for the QNAP server to resolve.  Either it supports HTTP/2 or it doesn't and it has indicated via ALPN that it does. But any further information would help investigate.  Maybe it's some bespoke feature like IP restrictions, or client auth checks?

**Comment by yschimke** [comment]
Going to close here as we can't reproduce.  Please reopen if you ahve a way to reproduce, and if you have a link to the QNAP report, please add it here.
