### ISSUE TITLE
java.lang.IllegalStateException: closed

### ISSUE THREAD

**Issue by H4kt** [square/okhttp#6106]
StackTrace:
```
    java.lang.IllegalStateException: closed
        at okio.RealBufferedSource.request(RealBufferedSource.java:66)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:253)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:250)
        at okhttp3.RealCall$AsyncCall.execute(RealCall.java:201)
        at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:919)
```

Latest request I see in logs is:
```
2020-06-01 18:36:51.649 22455-22557/com.faberlicchat D/OkHttp: <-- 500 Internal Server Error https://srvchat.faberlic.com/FLChat/events (30135ms)
2020-06-01 18:36:51.650 22455-22557/com.faberlicchat D/OkHttp: Server: nginx
2020-06-01 18:36:51.650 22455-22557/com.faberlicchat D/OkHttp: Date: Mon, 01 Jun 2020 15:36:16 GMT
2020-06-01 18:36:51.650 22455-22557/com.faberlicchat D/OkHttp: Content-Type: application/json; charset=utf-8
2020-06-01 18:36:51.650 22455-22557/com.faberlicchat D/OkHttp: Content-Length: 4644
2020-06-01 18:36:51.650 22455-22557/com.faberlicchat D/OkHttp: Connection: keep-alive
2020-06-01 18:36:51.650 22455-22557/com.faberlicchat D/OkHttp: Cache-Control: private
2020-06-01 18:36:51.651 22455-22557/com.faberlicchat D/OkHttp: X-AspNet-Version: 4.0.30319
2020-06-01 18:36:51.651 22455-22557/com.faberlicchat D/OkHttp: X-Powered-By: ASP.NET
```

The cause might be that server responded with no body while OkHttp attempted to read it

**Comment by yschimke** [comment]
This is something you should raise with the server team.

**Comment by yschimke** [comment]
We should fix the bug throwing IllegalStateException and make sure it comes back as an IOException.

**Comment by yschimke** [comment]
In order to investigate, please provide the versions of OkHttp you are using.

**Comment by swankjesse** [comment]
I don’t think this is an OkHttp bug. If you close a stream and then attempt to read it, that’s an IllegalStateException. My expectation here is some other interceptor is closing the response body.

**Comment by yschimke** [comment]
I couldn't repro with this branch https://github.com/square/okhttp/pull/6108 on 4.x.  Report is against some version of 3.x

```
java.net.ProtocolException: unexpected end of stream
	at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.kt:371)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
	at okio.RealBufferedSource.request(RealBufferedSource.kt:207)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:245)
```
