### ISSUE TITLE
ArrayIndexOutOfBoundsException in topPrivateDomain()

### ISSUE THREAD

**Issue by shellderp** [square/okhttp#6109]
hello friends!

on com.squareup.okhttp3:okhttp:4.7.2

it looks like a valid HttpUrl is created from a URL like `http://a./` but calling `topPrivateDomain()` throws a `ArrayIndexOutOfBoundsException`

I'm not sure if the url should fail to parse or topPrivateDomain should just return null.

repro:

```kotlin
import okhttp3.HttpUrl.Companion.toHttpUrl
import org.junit.jupiter.api.Test

class HttpBug {
  @Test fun test() {
    "http://a./".toHttpUrl().topPrivateDomain()
  }
}
```

```
java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0
	at okhttp3.internal.publicsuffix.PublicSuffixDatabase$Companion.binarySearch(PublicSuffixDatabase.kt:278)
	at okhttp3.internal.publicsuffix.PublicSuffixDatabase$Companion.access$binarySearch(PublicSuffixDatabase.kt:227)
	at okhttp3.internal.publicsuffix.PublicSuffixDatabase.findMatchingRule(PublicSuffixDatabase.kt:109)
	at okhttp3.internal.publicsuffix.PublicSuffixDatabase.getEffectiveTldPlusOne(PublicSuffixDatabase.kt:71)
	at okhttp3.HttpUrl.topPrivateDomain(HttpUrl.kt:773)
```

**Comment by swankjesse** [comment]
Can fix!

**Comment by yschimke** [comment]
https://github.com/square/okhttp/pull/6111
