### ISSUE TITLE
I got java.io.EOFException sometime

### ISSUE THREAD

**Issue by shllove** [square/okhttp#6113]
Hi, I got java.io.EOFException sometime, about six for one hour,  my okhttp lib version is 3.11.0,
pls kindly reply to me. Thks

java.io.EOFException
at okio.RealBufferedSource.require(RealBufferedSource.kt:55)
at okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.kt:299)
at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.readChunkSize(Http1ExchangeCodec.kt:450)
at okhttp3.internal.http1.Http1ExchangeCodec$ChunkedSource.read(Http1ExchangeCodec.kt:429)
at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:279)
at okio.Buffer.writeAll(Buffer.kt:1104)
at okio.RealBufferedSource.readString(RealBufferedSource.kt:194)
at okhttp3.ResponseBody.string(ResponseBody.kt:187)
at com.mongoproxy.client.OkHttp.postForm(OkHttp.java:83)

**Comment by yschimke** [comment]
Please raise on stackoverflow, with a working reproduction.  This isn't an actionable bug report for us, it could be just a slosed socket.

**Comment by saud-otaibi** [comment]
Hello @shllove - Did you ask this on stackoverflow or were you able to solve it? I am facing this issue currently and it would be really helpful to know how you solved it in case you did.

**Comment by mohammadpourzaker** [comment]
I gave the reward to the reward and solved this by giving you the security
codes and for you, but what would I reward my reward?

در تاریخ یکشنبه ۱۲ سپتامبر ۲۰۲۱،‏ ۱۵:۲۳ Saud Alotaibi <
***@***.***> نوشت:

**Comment by mohammadpourzaker** [comment]
You are a fool to understand that you are worth nothing.
