### ISSUE TITLE
Android - okhttp3.internal.io.FileSystem$Companion$SYSTEM$1.rename (FileSystem.java:89) crash

### ISSUE THREAD

**Issue by SomeKoder** [square/okhttp#6123]
These crashes keep happening:
`failed to rename /data/user/0/com.package/cache/62ac51d56050cb47dea413039d3e3b67.0.tmp to /data/user/0/com.package/cache/62ac51d56050cb47dea413039d3e3b67.0`

They happen randomly and not all the time, I'm unable to reproduce which makes it all the more confusing. The crashes are all similar to this one, but will sometimes be "delete" or "read"

They're happening too often to ignore. Is there a way to mitigate or fix this this? As far as I can tell, it happens on most devices. I apologize for the lack of information. We're using version 4.5.0.

**Comment by swankjesse** [comment]
Full stack trace? I suspect the filesystem is full. OkHttp us supposed to just stop caching when that happens.

**Comment by swankjesse** [comment]
Also please try the latest release; we've had cache fixes since 4.5.0.

**Comment by SomeKoder** [comment]
I'm sorry for the long reply, here is the stack trace: 
Fatal Exception: java.io.IOException: failed to rename /data/user/0/com.crosschasm.evchargerlocator/cache/feef9348d5877ee07813624fb12f97d6.1.tmp to /data/user/0/com.crosschasm.evchargerlocator/cache/feef9348d5877ee07813624fb12f97d6.1
       at okhttp3.internal.io.FileSystem$Companion$SYSTEM$1.rename(FileSystem.java:89)
       at okhttp3.internal.cache.DiskLruCache.completeEdit$okhttp(DiskLruCache.java:524)
       at okhttp3.internal.cache.DiskLruCache$Editor.commit(DiskLruCache.java:865)
       at okhttp3.Cache$RealCacheRequest$1.close(Cache.java:406)
       at okio.RealBufferedSink.close(RealBufferedSink.java:268)
       at okhttp3.internal.cache.CacheInterceptor$cacheWritingResponse$cacheWritingSource$1.read(CacheInterceptor.java:170)
       at okio.RealBufferedSource.read(RealBufferedSource.java:188)
       at okio.RealBufferedSource.exhausted(RealBufferedSource.java:198)
       at okio.GzipSource.read(GzipSource.java:88)
       at okio.RealBufferedSource.read(RealBufferedSource.java:188)
       at okio.ForwardingSource.read(ForwardingSource.java:29)
       at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:288)
       at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.java:158)
       at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:288)
       at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:351)
       at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:180)
       at java.io.InputStreamReader.read(InputStreamReader.java:184)
       at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.java:211)
       at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1295)
       at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1333)
       at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:538)
       at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
       at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:40)
       at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
       at com.package.NullOnEmptyConverterFactory$responseBodyConverter$1.convert(NullOnEmptyConverterFactory.java:16)
       at com.package.NullOnEmptyConverterFactory$responseBodyConverter$1.convert(NullOnEmptyConverterFactory.java:8)
       at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
       at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:504)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)

Although, I will definitely try the lastest version, thank you!

**Comment by yschimke** [comment]
There are various reasons why this could be normal e.g. The phone or your app is clearing the cache, your disk is full.

Can you collect this information and re-open.

As is this isn't actionable, if you can confirm the cache is full and contents are not being deleted we will reopen and look more.

**Comment by dinhhieuac** [comment]
Hi
I have the same problem and it's quite common
Info Device
[https://prnt.sc/u7di0b](https://prnt.sc/u7di0b
)
Fatal Exception: java.io.IOException: failed to rename /data/user/0/com.myapp.and_tv/cache/04ffd598d3450c64ffffab7d2e054719.1.tmp to /data/user/0/com.myapp.and_tv/cache/04ffd598d3450c64ffffab7d2e054719.1
       at okhttp3.internal.io.FileSystem$Companion$SYSTEM$1.rename(FileSystem.kt:89)
       at okhttp3.internal.cache.DiskLruCache.completeEdit$okhttp(DiskLruCache.kt:532)
       at okhttp3.internal.cache.DiskLruCache$Editor.commit(DiskLruCache.kt:901)
       at okhttp3.Cache$RealCacheRequest$1.close(Cache.kt:406)
       at okio.RealBufferedSink.close(RealBufferedSink.kt:268)
       at okhttp3.internal.cache.CacheInterceptor$cacheWritingResponse$cacheWritingSource$1.read(CacheInterceptor.kt:190)
       at okio.RealBufferedSource.read(RealBufferedSource.kt:188)
       at okio.ForwardingSource.read(ForwardingSource.kt:29)
       at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:314)
       at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.kt:158)
       at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:288)
       at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:351)
       at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:180)
       at java.io.InputStreamReader.read(InputStreamReader.java:184)
       at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.kt:211)
       at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1295)
       at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1333)
       at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:538)
       at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
       at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:41)
       at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
       at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
       at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:153)
       at com.google.firebase.perf.network.zzh.onResponse(com.google.firebase:firebase-perf@@19.0.8:22)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
       at java.lang.Thread.run(Thread.java:764)
Thanks
HieuHD

**Comment by oproulx** [comment]
We are still seeing the same error in version **_4.9.0_**

okhttp3.internal.io.FileSystem$Companion$SystemFileSystem.rename (FileSystem.java:90)
okhttp3.internal.cache.DiskLruCache.completeEdit$okhttp (DiskLruCache.java:532)
okhttp3.internal.cache.DiskLruCache$Editor.commit (DiskLruCache.java:901)
okhttp3.Cache$RealCacheRequest$1.close (Cache.java:406)
okio.internal.RealBufferedSinkKt.commonClose (RealBufferedSinkKt.java:203)
okio.RealBufferedSink.close (RealBufferedSink.java:286)
okhttp3.internal.cache.CacheInterceptor$cacheWritingResponse$cacheWritingSource$1.read (CacheInterceptor.java:190)
okio.internal.RealBufferedSourceKt.commonRead (RealBufferedSourceKt.java:39)
okio.RealBufferedSource.read (RealBufferedSource.java:189)
okio.internal.RealBufferedSourceKt.commonExhausted (RealBufferedSourceKt.java:49)
okio.RealBufferedSource.exhausted (RealBufferedSource.java:197)
okio.GzipSource.read (GzipSource.java:88)
okio.internal.RealBufferedSourceKt.commonRead (RealBufferedSourceKt.java:39)
okio.RealBufferedSource.read (RealBufferedSource.java:189)
okio.ForwardingSource.read (ForwardingSource.java:29)
retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read (OkHttpCall.java:288)
okio.RealBufferedSource$inputStream$1.read (RealBufferedSource.java:158)
sun.nio.cs.StreamDecoder.readBytes (StreamDecoder.java:291)
java.io.InputStreamReader.read (InputStreamReader.java:184)
okhttp3.ResponseBody$BomAwareReader.read (ResponseBody.java:211)
com.google.gson.stream.JsonReader.fillBuffer (JsonReader.java:1295)
com.google.gson.stream.JsonReader.peek (JsonReader.java:425)
retrofit2.converter.gson.GsonResponseBodyConverter.convert (GsonResponseBodyConverter.java:40)
retrofit2.converter.gson.GsonResponseBodyConverter.convert (GsonResponseBodyConverter.java:27)
com.mogiletech.android.core.data.network.NullOnEmptyConverterFactory$responseBodyConverter$1.convert (NullOnEmptyConverterFactory.java:16)
com.mogiletech.android.core.data.network.NullOnEmptyConverterFactory$responseBodyConverter$1.convert (NullOnEmptyConverterFactory.java:8)
retrofit2.OkHttpCall.parseResponse (OkHttpCall.java:225)
retrofit2.OkHttpCall$1.onResponse (OkHttpCall.java:121)
okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.java:519)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1167)
java.lang.Thread.run (Thread.java:919)

Any help is greatly appreciated!

Thanks,

**Comment by oproulx** [comment]
Hello,

We are still seeing this crash on version 4.9.0.

```
Fatal Exception: java.io.IOException: failed to rename /data/user/0/OURAPP/cache/57ad8dd5e5e0a9c6b5f4b00d66f8e3c6.0.tmp to /data/user/0/OURAPP/cache/57ad8dd5e5e0a9c6b5f4b00d66f8e3c6.0
       at okhttp3.internal.io.FileSystem$Companion$SystemFileSystem.rename(FileSystem.java:90)
       at okhttp3.internal.cache.DiskLruCache.completeEdit$okhttp(DiskLruCache.java:532)
       at okhttp3.internal.cache.DiskLruCache$Editor.commit(DiskLruCache.java:901)
       at okhttp3.Cache$RealCacheRequest$1.close(Cache.java:406)
       at okio.internal.RealBufferedSinkKt.commonClose(RealBufferedSinkKt.java:203)
       at okio.RealBufferedSink.close(RealBufferedSink.java:286)
       at okhttp3.internal.cache.CacheInterceptor$cacheWritingResponse$cacheWritingSource$1.read(CacheInterceptor.java:190)
       at okio.internal.RealBufferedSourceKt.commonRead(RealBufferedSourceKt.java:39)
       at okio.RealBufferedSource.read(RealBufferedSource.java:189)
       at okio.internal.RealBufferedSourceKt.commonExhausted(RealBufferedSourceKt.java:49)
       at okio.RealBufferedSource.exhausted(RealBufferedSource.java:197)
       at okio.GzipSource.read(GzipSource.java:88)
       at okio.internal.RealBufferedSourceKt.commonRead(RealBufferedSourceKt.java:39)
       at okio.RealBufferedSource.read(RealBufferedSource.java:189)
       at okio.ForwardingSource.read(ForwardingSource.java:29)
       at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:288)
       at okio.RealBufferedSource$inputStream$1.read(RealBufferedSource.java:158)
       at sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:288)
       at sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:351)
       at sun.nio.cs.StreamDecoder.read(StreamDecoder.java:180)
       at java.io.InputStreamReader.read(InputStreamReader.java:184)
       at okhttp3.ResponseBody$BomAwareReader.read(ResponseBody.java:211)
       at com.google.gson.stream.JsonReader.fillBuffer(JsonReader.java:1295)
       at com.google.gson.stream.JsonReader.nextNonWhitespace(JsonReader.java:1333)
       at com.google.gson.stream.JsonReader.doPeek(JsonReader.java:538)
       at com.google.gson.stream.JsonReader.peek(JsonReader.java:425)
       at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:40)
       at retrofit2.converter.gson.GsonResponseBodyConverter.convert(GsonResponseBodyConverter.java:27)
       at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:225)
       at retrofit2.OkHttpCall$1.onResponse(OkHttpCall.java:121)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

Any help is greatly appreciated!

Olivier

**Comment by yschimke** [comment]
Any chance you have two Cache instances sharing the same directory?

**Comment by oproulx** [comment]
> Any chance you have two Cache instances sharing the same directory?

Here is how we configure the client:

![image (1)](https://user-images.githubusercontent.com/5933387/101938483-65e9bf80-3bb1-11eb-8070-8a0cb5538c67.png)

We call `RetrofitClient.init(context: this)` in our .app class, so the cache is configured based on the .app context.

**Comment by yschimke** [comment]
If you have two serviceApi then you likely have two Cache instances sharing the same directory, this is probably the cause.

**Comment by oproulx** [comment]
> If you have two serviceApi then you likely have two Cache instances sharing the same directory, this is probably the cause.
> 
> See https://square.github.io/okhttp/4.x/okhttp/okhttp3/-ok-http-client/#okhttpclients-should-be-shared

Thanks for the suggestion!  We will ensure that only 1 client is created and post back if that resolves the crashes.
