### ISSUE TITLE
OkHttp-1.5 can't run on Android 2.2

### ISSUE THREAD

**Issue by takke** [square/okhttp#618]
Android 2.2 is unsupported?
OkHttp-1.5 can't run on my android 2.2 device.

Stack trace:

```
Caused by: java.lang.NoSuchMethodError: java.lang.String.getBytes
    at com.squareup.okhttp.internal.okio.ByteString.encodeUtf8(ByteString.java:61)
    at com.squareup.okhttp.Protocol.<init>(Protocol.java:48)
    at com.squareup.okhttp.Protocol.<clinit>(Protocol.java:33)
    ...
```

https://github.com/square/okhttp/blob/master/okio/src/main/java/okio/ByteString.java#L61

unfortunately, String.getBytes(Charset) is "API Level9 (Android2.3)".

**Comment by raul1991** [comment]
```java
Caused by: java.lang.NoClassDefFoundError: java.util.ArrayDeque
            at com.squareup.okhttp.Dispatcher.<init>(Dispatcher.java:44)
            at com.squareup.okhttp.OkHttpClient.<init>(OkHttpClient.java:196)
```
I am facing this problem in Api level 8, 2.2.1

**Comment by JakeWharton** [comment]
Version 2.x only supports API 9 and up

**Comment by raul1991** [comment]
Ill then upgrade my minSdkVersion to 9 then. Thanks.
