### ISSUE TITLE
UnknownHostException bug in API-30

### ISSUE THREAD

**Issue by AhmerAfzal1** [square/okhttp#6189]
There is bug in API 30, Host address is correct and okhttp works fine in API29 with particular [link](https://graph.facebook.com/100025917301113/picture?width=512&height=512)

Please take a look

`java.net.UnknownHostException: Unable to resolve host "graph.facebook.com": No address associated with hostname
    at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:156)
    at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
    at java.net.InetAddress.getAllByName(InetAddress.java:1152)
    at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
    at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
    at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
    at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
    at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
    at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
    at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
    at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
    at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
    at com.ahmer.whatsapp.activity.AhmerActivity$DownloadMyImage.doInBackground(AhmerActivity.java:313)
    at com.ahmer.whatsapp.activity.AhmerActivity$DownloadMyImage.doInBackground(AhmerActivity.java:293)
    at com.ahmer.afzal.utils.CoroutineAsyncTask$execute$1.invokeSuspend(CoroutineAsyncTask.kt:31)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:241)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:740)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
    at libcore.io.Linux.android_getaddrinfo(Native Method)
    at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
    at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:202)
    at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:73)
    at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	... 28 more`

**Comment by yschimke** [comment]
On it's own this is a generic network error. It's not a bug in OkHttp and not something we can fix on our own. You should ask about usage questions like this on stackoverflow.

But most likely it's Android not letting your app use the network while backgrounded, or based on some restrictions e.g. low power mode.

Please raise a question on stackoverflow.
