### ISSUE TITLE
Failed resolution of: Lokhttp3/internal/concurrent/TaskRunner$RealBackend;

### ISSUE THREAD

**Issue by CyrusCeasar** [square/okhttp#6195]
I got following error when i executed my AndroidJunit4 test.  **androidTestImplementation rootProject.ext.test["mockwebserver"]** has been added to my build.gradle. Additionally,  **mockwebserver =com.squareup.okhttp3:mockwebserver:4.7.2**.
  I want to know if MockwebServer could run in AndroidJunit4 Testing?
```

java.lang.NoClassDefFoundError: Failed resolution of: Lokhttp3/internal/concurrent/TaskRunner$RealBackend;
at okhttp3.mockwebserver.MockWebServer.<init>(MockWebServer.kt:101)
at com.zhixin.wedeep.homepage.Util.<clinit>(Util.kt:31)
at com.zhixin.wedeep.homepage.MockHomePageDataModule.provideHomePageDatabase(MockHomePageDataModule.kt:68)
at com.zhixin.wedeep.homepage.MockHomePageDataModule_ProvideHomePageDatabaseFactory.provideHomePageDatabase(MockHomePageDataModule_ProvideHomePageDatabaseFactory.java:34)
at com.zhixin.wedeep.homepage.viewmodel.DaggerTestHomePageViewModel_HiltComponents_ApplicationC.getCompositionDao(DaggerTestHomePageViewModel_HiltComponents_ApplicationC.java:96)
at com.zhixin.wedeep.homepage.viewmodel.DaggerTestHomePageViewModel_HiltComponents_ApplicationC.injectTestHomePageViewModel(DaggerTestHomePageViewModel_HiltComponents_ApplicationC.java:154)
at com.zhixin.wedeep.homepage.viewmodel.DaggerTestHomePageViewModel_HiltComponents_ApplicationC.injectTest(DaggerTestHomePageViewModel_HiltComponents_ApplicationC.java:139)
at com.zhixin.wedeep.homepage.viewmodel.DaggerTestHomePageViewModel_HiltComponents_ApplicationC.injectTest(DaggerTestHomePageViewModel_HiltComponents_ApplicationC.java:69)
at com.zhixin.wedeep.homepage.viewmodel.TestHomePageViewModel_ComponentDataHolder.injectInternal(TestHomePageViewModel_ComponentDataHolder.java:25)
at com.zhixin.wedeep.homepage.viewmodel.TestHomePageViewModel_ComponentDataHolder.lambda$get$0(TestHomePageViewModel_ComponentDataHolder.java:18)
at com.zhixin.wedeep.homepage.viewmodel.-$$Lambda$TestHomePageViewModel_ComponentDataHolder$YqbecUEzlSH6v5hjApI4XJcfBSE.injectTest(Unknow



```

**Comment by yschimke** [comment]
Yes, but your dependencies are mixing versions.  This is for bug reports, consider using stackoverflow or asking a colleague to help you with the dependency issue.
