### ISSUE TITLE
"java.lang.NoSuchFieldError: Companion" while using toHttpUrlOrNull 

### ISSUE THREAD

**Issue by ltpquang** [square/okhttp#6199]
Hi folks I'm stuck with this exception 

```
Caused by: java.lang.NoSuchFieldError: Companion
        at okhttp3.internal.Util.<clinit>(Util.kt:72)
        at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1239)
        at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1633)
        at okhttp3.HttpUrl$Companion.parse(HttpUrl.kt:1642)
        at vn.zalopay.client.cucumber.plugin.XrayReporter.<init>(XrayReporter.kt:21)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at io.cucumber.core.plugin.PluginFactory.newInstance(PluginFactory.java:114)
        ... 41 more
```

While calling

```
val httpUrl = "http://google.com".toHttpUrlOrNull()
```

![image](https://user-images.githubusercontent.com/4617357/88454558-baa6cb00-ce9a-11ea-897c-0ede746f869a.png)

Any idea to resolve this thing?

OkHttp version: 4.8.0
Kotlin version: 1.3.72

**Comment by ltpquang** [comment]
My bad, I have a transitive dependency on okio v1.14.0, in which method `decodeHex` is not available, causing my app crash.
