### ISSUE TITLE
Robolectric tests fail when updating okHttp to 4.7 or later.

### ISSUE THREAD

**Issue by psa-anddev** [square/okhttp#6205]
I updated okHttp to 4.8. After that, I realized that all the Robolectric tests in that project were failing because okHttp cannot find the "BCJSSE" provider which is, I believe, Bouncy Castle. 

Here, you have an example of a stacktrace.
```
org.koin.core.error.InstanceCreationException: Could not create instance for [type:Single,class:'com.novastonemedia.novastone.views.attachments.sendpicture.SendPictureViewModel']
	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:61)
	at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40)
	at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:75)
	at org.koin.core.Koin.resolve(Koin.kt:107)
	at org.koin.core.Koin.get(Koin.kt:96)
	at com.novastonemedia.novastone.integration.attachments.SendPictureTest.should send a picture(SendPictureTest.kt:169)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27)
	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
	at org.robolectric.RobolectricTestRunner$HelperTestRunner$1.evaluate(RobolectricTestRunner.java:546)
	at org.robolectric.internal.SandboxTestRunner$2.lambda$evaluate$0(SandboxTestRunner.java:252)
	at org.robolectric.internal.bytecode.Sandbox.lambda$runOnMainThread$0(Sandbox.java:89)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [type:Factory,class:'com.novastonemedia.novastone.features.attachments.sendattachment.SendAttachmentInput']
	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:61)
	at org.koin.core.instance.FactoryDefinitionInstance.get(FactoryDefinitionInstance.kt:37)
	at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:75)
	at org.koin.core.Koin.resolve(Koin.kt:107)
	at org.koin.core.Koin.get(Koin.kt:96)
	at com.novastonemedia.novastone.di.AttachmentsDeliveryModuleKt$attachmentsDeliveryModule$1$1.invoke(AttachmentsDeliveryModule.kt:16)
	at com.novastonemedia.novastone.di.AttachmentsDeliveryModuleKt$attachmentsDeliveryModule$1$1.invoke(AttachmentsDeliveryModule.kt)
	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
	... 23 more
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [type:Single,class:'com.novastonemedia.novastone.gateways.MessagesGateway']
	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:61)
	at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40)
	at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:75)
	at org.koin.core.Koin.resolve(Koin.kt:107)
	at org.koin.core.Koin.get(Koin.kt:96)
	at com.novastonemedia.novastone.di.AttachmentsModuleKt$attachmentsModule$1$1.invoke(AttachmentsModule.kt:26)
	at com.novastonemedia.novastone.di.AttachmentsModuleKt$attachmentsModule$1$1.invoke(AttachmentsModule.kt)
	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
	... 30 more
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [type:Factory,class:'com.novastonemedia.novastone.network.webservices.AttachmentService']
	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:61)
	at org.koin.core.instance.FactoryDefinitionInstance.get(FactoryDefinitionInstance.kt:37)
	at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:75)
	at org.koin.core.Koin.resolve(Koin.kt:107)
	at org.koin.core.Koin.get(Koin.kt:96)
	at com.novastonemedia.novastone.di.GatewaysModuleKt$gatewaysModule$1$5.invoke(GatewaysModule.kt:386)
	at com.novastonemedia.novastone.di.GatewaysModuleKt$gatewaysModule$1$5.invoke(GatewaysModule.kt)
	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
	... 37 more
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [type:Single,class:'com.novastonemedia.novastone.helpers.RetrofitWrapper']
	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:61)
	at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40)
	at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:75)
	at org.koin.core.Koin.resolve(Koin.kt:107)
	at org.koin.core.Koin.get(Koin.kt:96)
	at com.novastonemedia.novastone.di.NetworkModuleKt$networkModule$1$15.invoke(NetworkModule.kt:190)
	at com.novastonemedia.novastone.di.NetworkModuleKt$networkModule$1$15.invoke(NetworkModule.kt)
	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
	... 44 more
Caused by: org.koin.core.error.InstanceCreationException: Could not create instance for [type:Single,class:'okhttp3.OkHttpClient']
	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:61)
	at org.koin.core.instance.SingleDefinitionInstance.get(SingleDefinitionInstance.kt:40)
	at org.koin.core.definition.BeanDefinition.resolveInstance(BeanDefinition.kt:75)
	at org.koin.core.Koin.resolve(Koin.kt:107)
	at org.koin.core.Koin.get(Koin.kt:96)
	at com.novastonemedia.novastone.di.NetworkModuleKt$networkModule$1$14.invoke(NetworkModule.kt:208)
	at com.novastonemedia.novastone.di.NetworkModuleKt$networkModule$1$14.invoke(NetworkModule.kt)
	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
	... 51 more
Caused by: java.security.NoSuchProviderException: no such provider: BCJSSE
	at sun.security.jca.GetInstance.getService(GetInstance.java:83)
	at sun.security.jca.GetInstance.getInstance(GetInstance.java:206)
	at javax.net.ssl.TrustManagerFactory.getInstance(TrustManagerFactory.java:183)
	at okhttp3.internal.platform.BouncyCastlePlatform.platformTrustManager(BouncyCastlePlatform.kt:41)
	at okhttp3.OkHttpClient.<init>(OkHttpClient.kt:237)
	at okhttp3.OkHttpClient$Builder.build(OkHttpClient.kt:1069)
	at com.novastonemedia.novastone.di.NetworkModuleKt$networkModule$1$8.invoke(NetworkModule.kt:88)
	at com.novastonemedia.novastone.di.NetworkModuleKt$networkModule$1$8.invoke(NetworkModule.kt)
	at org.koin.core.instance.DefinitionInstance.create(DefinitionInstance.kt:54)
	... 58 more
```
**Actual result:** Tests fail due to the lack of the Bouncy Castle Provider
**Expected result:** Test shouldn't fail due to the lack of Bouncy Castle provider.

**Comment by yschimke** [comment]
We use the registration of security providers to tell us which Platform instance to use.  This code has changed recently because of incompatible changes in both Android and Android Studio.

Looking into Robolectric code, they are registering only one of the two necessary providers we need.

https://github.com/robolectric/robolectric/blob/96ff4116ea83e93339d295e98175a8e49e2aadbc/robolectric/src/main/java/org/robolectric/android/internal/AndroidTestEnvironment.java#L143-L145

```
    if (Security.getProvider(BouncyCastleProvider.PROVIDER_NAME) == null) {
      Security.insertProviderAt(new BouncyCastleProvider(), 1);
    }
```

You should be able to workaround this by registering both yourself.

```
        Security.insertProviderAt(BouncyCastleProvider(), 1)
        Security.insertProviderAt(BouncyCastleJsseProvider(), 2)
```

**Comment by yschimke** [comment]
I'm not particularly comfortable doing much more here automatically because every change has potential to break because of

1) Existing project workarounds people employ
2) Changes of behaviour over Android versions
3) Changes of behaviour because of IDE or build systems

**Comment by psa-anddev** [comment]
Adding the providers was enough to fix the Robolectric tests. I actually didn't know there were two providers for Bouncy Castle so I got to learn something. Thank you for the help.
