### ISSUE TITLE
3.14.x versions have unstable handling of NetworkOnMainThreadException

### ISSUE THREAD

**Issue by byencho** [square/okhttp#6216]
Starting with version 3.14.0, if a `NetworkOnMainThreadException` happens it is possible for a subsequent request to receive the response from the previous (supposedly failed) request.

Consider this code snippet using OkHttp 3.14.0 and Okio 1.15.0

```kotlin
        val xkcdClient = OkHttpClient.Builder()
            .addNetworkInterceptor(
                HttpLoggingInterceptor { println(it) }.apply {
                    level = HttpLoggingInterceptor.Level.BODY
                }
            )
            .build()

        val strip1Request = Request.Builder()
            .url("https://xkcd.com/1/info.0.json")
            .build()

        val strip2Request = Request.Builder()
            .url("https://xkcd.com/2/info.0.json")
            .build()

        val strip3Request = Request.Builder()
            .url("https://xkcd.com/3/info.0.json")
            .build()

        val noopCallback = object : Callback {
            override fun onFailure(call: Call, e: IOException) = Unit

            override fun onResponse(call: Call, response: Response) = Unit
        }

        // This first request ensures the host is correctly recognized for connection recycling
        // later
        xkcdClient
            .newCall(strip1Request)
            .enqueue(noopCallback)

        // This second request will trigger a NetworkOnMainThreadException. The try / catch mimics
        // the behavior when using OkHttp + Retrofit + RxJava2.
        val handler = Handler()
        handler.postDelayed(
            {
                try {
                    xkcdClient
                        .newCall(strip2Request)
                        .execute()
                } catch (e: NetworkOnMainThreadException) {
                    e.printStackTrace()
                }
            },
            1000
        )

        // This final request will receive the response from the request above.
        handler.postDelayed(
            {
                xkcdClient
                    .newCall(strip3Request)
                    .enqueue(noopCallback)
            },
            2000
        )
```

This makes a first request in order for the host to be recognized for connection recycling later. The second request is the problematic one that fails. The try / catch mimics what would happen when making the actual request via Retrofit + RxJava (which is how we discovered the issue). The final request is where the problem revealed : the network response returned is actually the response for the second request.

The complete set of logs produced here are 

```
2020-08-07 13:19:04.889 28123-28340 I: --> GET https://xkcd.com/1/info.0.json http/1.1
2020-08-07 13:19:04.889 28123-28340 I: Host: xkcd.com
2020-08-07 13:19:04.889 28123-28340 I: Connection: Keep-Alive
2020-08-07 13:19:04.889 28123-28340 I: Accept-Encoding: gzip
2020-08-07 13:19:04.889 28123-28340 I: User-Agent: okhttp/3.14.0
2020-08-07 13:19:04.889 28123-28340 I: --> END GET
2020-08-07 13:19:04.936 28123-28340 I: <-- 200 OK https://xkcd.com/1/info.0.json (46ms)
2020-08-07 13:19:04.936 28123-28340 I: Connection: keep-alive
2020-08-07 13:19:04.936 28123-28340 I: Content-Length: 290
2020-08-07 13:19:04.936 28123-28340 I: Server: nginx
2020-08-07 13:19:04.936 28123-28340 I: Content-Type: application/json
2020-08-07 13:19:04.936 28123-28340 I: Last-Modified: Fri, 07 Aug 2020 04:00:03 GMT
2020-08-07 13:19:04.936 28123-28340 I: ETag: W/"5f2cd1c3-1ac"
2020-08-07 13:19:04.936 28123-28340 I: Expires: Fri, 07 Aug 2020 17:45:30 GMT
2020-08-07 13:19:04.936 28123-28340 I: Cache-Control: max-age=300
2020-08-07 13:19:04.936 28123-28340 I: Content-Encoding: gzip
2020-08-07 13:19:04.936 28123-28340 I: Accept-Ranges: bytes
2020-08-07 13:19:04.936 28123-28340 I: Date: Fri, 07 Aug 2020 18:19:07 GMT
2020-08-07 13:19:04.936 28123-28340 I: Via: 1.1 varnish
2020-08-07 13:19:04.936 28123-28340 I: Age: 231
2020-08-07 13:19:04.936 28123-28340 I: X-Served-By: cache-mdw17342-MDW
2020-08-07 13:19:04.936 28123-28340 I: X-Cache: HIT
2020-08-07 13:19:04.936 28123-28340 I: X-Cache-Hits: 1
2020-08-07 13:19:04.936 28123-28340 I: X-Timer: S1596824347.113793,VS0,VE0
2020-08-07 13:19:04.936 28123-28340 I: Vary: Accept-Encoding
2020-08-07 13:19:04.937 28123-28340 I: {"month": "1", "num": 1, "link": "", "year": "2006", "news": "", "safe_title": "Barrel - Part 1", "transcript": "[[A boy sits in a barrel which is floating in an ocean.]]\nBoy: I wonder where I'll float next?\n[[The barrel drifts into the distance. Nothing else can be seen.]]\n{{Alt: Don't we all.}}", "alt": "Don't we all.", "img": "https://imgs.xkcd.com/comics/barrel_cropped_(1).jpg", "title": "Barrel - Part 1", "day": "1"}
2020-08-07 13:19:04.937 28123-28340 I: <-- END HTTP (428-byte, 290-gzipped-byte body)
2020-08-07 13:19:05.216 28123-28123 W: Accessing hidden field Landroid/view/View;->mAccessibilityDelegate:Landroid/view/View$AccessibilityDelegate; (greylist, reflection, allowed)
2020-08-07 13:19:05.755 28123-28123 I: --> GET https://xkcd.com/2/info.0.json http/1.1
2020-08-07 13:19:05.755 28123-28123 I: Host: xkcd.com
2020-08-07 13:19:05.755 28123-28123 I: Connection: Keep-Alive
2020-08-07 13:19:05.755 28123-28123 I: Accept-Encoding: gzip
2020-08-07 13:19:05.755 28123-28123 I: User-Agent: okhttp/3.14.0
2020-08-07 13:19:05.755 28123-28123 I: --> END GET
2020-08-07 13:19:05.756 28123-28123 I: <-- HTTP FAILED: android.os.NetworkOnMainThreadException
2020-08-07 13:19:05.756 28123-28123 W: android.os.NetworkOnMainThreadException
2020-08-07 13:19:05.756 28123-28123 W:     at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
2020-08-07 13:19:05.756 28123-28123 W:     at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:424)
2020-08-07 13:19:05.756 28123-28123 W:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(ConscryptFileDescriptorSocket.java:608)
2020-08-07 13:19:05.756 28123-28123 W:     at okio.Okio$1.write(Okio.java:79)
2020-08-07 13:19:05.756 28123-28123 W:     at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
2020-08-07 13:19:05.756 28123-28123 W:     at okio.RealBufferedSink.flush(RealBufferedSink.java:224)
2020-08-07 13:19:05.756 28123-28123 W:     at okhttp3.internal.http1.Http1ExchangeCodec.finishRequest(Http1ExchangeCodec.java:190)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.internal.connection.Exchange.finishRequest(Exchange.java:101)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:86)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.java:223)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:221)
2020-08-07 13:19:05.757 28123-28123 W:     at okhttp3.RealCall.execute(RealCall.java:81)
2020-08-07 13:19:05.757 28123-28123 W:     at com.smartthings.smarthome.device.list.fragment.DeviceFragment$onCreate$1.run(DeviceFragment.kt:109)
2020-08-07 13:19:05.757 28123-28123 W:     at android.os.Handler.handleCallback(Handler.java:883)
2020-08-07 13:19:05.757 28123-28123 W:     at android.os.Handler.dispatchMessage(Handler.java:100)
2020-08-07 13:19:05.757 28123-28123 W:     at android.os.Looper.loop(Looper.java:214)
2020-08-07 13:19:05.757 28123-28123 W:     at android.app.ActivityThread.main(ActivityThread.java:7356)
2020-08-07 13:19:05.757 28123-28123 W:     at java.lang.reflect.Method.invoke(Native Method)
2020-08-07 13:19:05.757 28123-28123 W:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
2020-08-07 13:19:05.757 28123-28123 W:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
2020-08-07 13:19:06.759 28123-28340 I: --> GET https://xkcd.com/3/info.0.json http/1.1
2020-08-07 13:19:06.759 28123-28340 I: Host: xkcd.com
2020-08-07 13:19:06.759 28123-28340 I: Connection: Keep-Alive
2020-08-07 13:19:06.759 28123-28340 I: Accept-Encoding: gzip
2020-08-07 13:19:06.759 28123-28340 I: User-Agent: okhttp/3.14.0
2020-08-07 13:19:06.759 28123-28340 I: --> END GET
2020-08-07 13:19:06.934 28123-28340 I: <-- 200 OK https://xkcd.com/3/info.0.json (174ms)
2020-08-07 13:19:06.934 28123-28340 I: Connection: keep-alive
2020-08-07 13:19:06.934 28123-28340 I: Content-Length: 283
2020-08-07 13:19:06.934 28123-28340 I: Server: nginx
2020-08-07 13:19:06.934 28123-28340 I: Content-Type: application/json
2020-08-07 13:19:06.934 28123-28340 I: Last-Modified: Fri, 07 Aug 2020 04:00:03 GMT
2020-08-07 13:19:06.934 28123-28340 I: ETag: W/"5f2cd1c3-1fb"
2020-08-07 13:19:06.934 28123-28340 I: Expires: Fri, 07 Aug 2020 17:50:34 GMT
2020-08-07 13:19:06.934 28123-28340 I: Cache-Control: max-age=300
2020-08-07 13:19:06.934 28123-28340 I: Content-Encoding: gzip
2020-08-07 13:19:06.934 28123-28340 I: Accept-Ranges: bytes
2020-08-07 13:19:06.934 28123-28340 I: Date: Fri, 07 Aug 2020 18:19:08 GMT
2020-08-07 13:19:06.934 28123-28340 I: Via: 1.1 varnish
2020-08-07 13:19:06.934 28123-28340 I: Age: 233
2020-08-07 13:19:06.934 28123-28340 I: X-Served-By: cache-mdw17342-MDW
2020-08-07 13:19:06.934 28123-28340 I: X-Cache: HIT
2020-08-07 13:19:06.934 28123-28340 I: X-Cache-Hits: 1
2020-08-07 13:19:06.934 28123-28340 I: X-Timer: S1596824349.989360,VS0,VE0
2020-08-07 13:19:06.934 28123-28340 I: Vary: Accept-Encoding
2020-08-07 13:19:06.935 28123-28340 I: {"month": "1", "num": 2, "link": "", "year": "2006", "news": "", "safe_title": "Petit Trees (sketch)", "transcript": "[[Two trees are growing on opposite sides of a sphere.]]\n{{Alt-title: 'Petit' being a reference to Le Petit Prince, which I only thought about halfway through the sketch}}", "alt": "'Petit' being a reference to Le Petit Prince, which I only thought about halfway through the sketch", "img": "https://imgs.xkcd.com/comics/tree_cropped_(1).jpg", "title": "Petit Trees (sketch)", "day": "1"}
2020-08-07 13:19:06.935 28123-28340 I: <-- END HTTP (507-byte, 283-gzipped-byte body)
```

Note how the request for the 3rd strip produces the data for the 2nd (which is most directly seen by looking at the `num` property). This is one basic example but we've seen this behavior in the wild with our own APIs. This also isn't simply a problem with the logging; the response printed by the logger is definitely the one that gets delivered to the `Response`.

This issue is not present in versions prior to `3.14.0` or in `4.x.x`.

The stacktraces for the `NetworkOnMainThreadException` before and after `3.14.0` hint at part of the problem. On `3.13.1` it is clear OkHttp is catching the error, marking the stream with a failure, and rethrowing:

```
     Caused by: android.os.NetworkOnMainThreadException
        at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
        at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:424)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.shutdownAndFreeSslNative(ConscryptFileDescriptorSocket.java:1021)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.close(ConscryptFileDescriptorSocket.java:1016)
        at okhttp3.internal.Util.closeQuietly(Util.java:154)
        at okhttp3.internal.connection.StreamAllocation.streamFailed(StreamAllocation.java:468)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:143)
        ...
```

After `3.14.0` the crash happens in `Okio` and is not caught and rethrown:

```
        android.os.NetworkOnMainThreadException
          at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
          at com.android.org.conscrypt.Platform.blockGuardOnNetwork(Platform.java:424)
          at com.android.org.conscrypt.ConscryptFileDescriptorSocket$SSLOutputStream.write(ConscryptFileDescriptorSocket.java:608)
          at okio.Okio$1.write(Okio.java:79)
          at okio.AsyncTimeout$1.write(AsyncTimeout.java:180)
          at okio.RealBufferedSink.flush(RealBufferedSink.java:224)
          at okhttp3.internal.http1.Http1ExchangeCodec.finishRequest(Http1ExchangeCodec.java:190)
          ...
```

This seems to leave the connection in an invalid state where it is still open and ready to read the response but it will also be recycled for the next request because it was not marked with a failure.

**Comment by swankjesse** [comment]
We are not fixing any bugs on 3.14.x. Please use the latest release.

**Comment by byencho** [comment]
Yeah I figured as much. I just wanted to get this documented, thanks!
