### ISSUE TITLE
java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics in Spring boot project

### ISSUE THREAD

**Issue by mash-reza** [square/okhttp#6231]
Hi. I'm using Spring boot 2.3.3 and java 9.
I'm using Retrofit 2 as my network requesting library. it works perfect but I want to log my request's body so I can see if request body POJO class is converting correctly to josn using Gson Convertor.
I try to add HttpLoggingInterceptor to OkhttpClient before building retrofit object. at runtime I get this error while creating API with retrofit.
```
java.lang.NoClassDefFoundError: kotlin/jvm/internal/Intrinsics
	at okhttp3.logging.HttpLoggingInterceptor.<init>(HttpLoggingInterceptor.kt) ~[logging-interceptor-4.8.1.jar:na]
	at okhttp3.logging.HttpLoggingInterceptor.<init>(HttpLoggingInterceptor.kt:40) ~[logging-interceptor-4.8.1.jar:na]
	at okhttp3.logging.HttpLoggingInterceptor.<init>(HttpLoggingInterceptor.kt) ~[logging-interceptor-4.8.1.jar:na]
	at com.wetherApi.test.network.NetworkService.getInstance(NetworkService.java:26) ~[classes/:na]
	at com.wetherApi.test.service.TokenService.refreshToken(TokenService.java:26) ~[classes/:na]
	at com.wetherApi.test.component.UpdateTokenScheduledTask.run(UpdateTokenScheduledTask.java:22) ~[classes/:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:564) ~[na:na]
	at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.2.8.RELEASE.jar:5.2.8.RELEASE]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:514) [na:na]
	at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) [na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:300) [na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) [na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) [na:na]
	at java.base/java.lang.Thread.run(Thread.java:844) [na:na]
Caused by: java.lang.ClassNotFoundException: kotlin.jvm.internal.Intrinsics
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496) ~[na:na]
	... 18 common frames omitted
```

**Comment by mash-reza** [comment]
I found it. it was because logging interceptor version was not the same with okhttp version of retrofit.
i updated the okhttp dependencies to latest version and it worked.
