### ISSUE TITLE
java.lang.IllegalStateException: Unbalanced enter/exit

### ISSUE THREAD

**Issue by suiyuan2009** [square/okhttp#6318]
Our usage, which is in a rabbitmq consumer.
We use `com.squareup.okhttp3:okhttp:3.9.1` and `openjdk version "1.8.0_242"`.
```
OkHttpClient okHttpClient = new OkHttpClient.Builder().build(); // which is a bean.

public Response someFunction(...) {
...
okHttpClient.newCall(request).execute();
...
}
```
We got this exception for more than 1 hour, but it doesn't happen right now. It's hard to reproduce.
```
java.lang.IllegalStateException: Unbalanced enter/exit
    at okio.AsyncTimeout.enter(AsyncTimeout.java:73)
    at okio.AsyncTimeout$2.read(AsyncTimeout.java:235)
    at okio.RealBufferedSource.exhausted(RealBufferedSource.java:61)
    at okhttp3.internal.connection.RealConnection.isHealthy(RealConnection.java:591)
    at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:120)
    at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88)
    at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
    at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
    at okhttp3.RealCall.execute(RealCall.java:81)
```

**Comment by suiyuan2009** [comment]
There should not be multiple `enter` in https://android.googlesource.com/platform/external/okhttp/+/a2cab72/okio/okio/src/main/java/okio/AsyncTimeout.java#206, unless multiple threads invoked `AsyncTimeout.enter`? Since there is an `enter`, there will be an `exit`.

**Comment by yschimke** [comment]
See guidance on https://github.com/square/okhttp/issues/4110, usually this is interaction with a single call across multiple threads.  But as is we can't do anything, if you think it's a bug, please provide a reproduction and reopen.

Closing as we aren't looking into this.
