### ISSUE TITLE
android-test failures with additional tests

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6419]

**Comment by yschimke** [comment]
DnsOverHttpsTest.usesCache

```
java.net.UnknownHostException: google.com
at okhttp3.dnsoverhttps.DnsOverHttps.throwBestFailure(DnsOverHttps.kt:176)
at okhttp3.dnsoverhttps.DnsOverHttps.lookupHttps(DnsOverHttps.kt:97)
at okhttp3.dnsoverhttps.DnsOverHttps.lookup(DnsOverHttps.kt:77)
at okhttp3.dnsoverhttps.DnsOverHttpsTest.usesCache(DnsOverHttpsTest.java:186)
at java.lang.reflect.Method.invoke(Native Method)
at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:688)
at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
at okhttp3.testing.PlatformRule.interceptTestMethod(PlatformRule.kt:75)
at org.junit.jupiter.engine.descriptor.-$$Lambda$VcVqu5ThYof3tLANzzaX3dcRMaY.apply(Unknown Source:0)
at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
at org.junit.jupiter.engine.execution.-$$Lambda$ExecutableInvoker$ReflectiveInterceptorCall$_2CnqIbadH7Fu1IFUZnKsEXz2bw.apply(Unknown Source:2)
at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
at org.junit.jupiter.engine.execution.-$$Lambda$ExecutableInvoker$261CBY1xI2VzNyAER1enkFZVl78.apply(Unknown Source:6)
at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
at org.junit.jupiter.engine.descriptor.-$$Lambda$VcVqu5ThYof3tLANzzaX3dcRMaY.apply(Unknown Source:0)
at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
at org.junit.jupiter.engine.execution.-$$Lambda$ExecutableInvoker$ReflectiveInterceptorCall$_2CnqIbadH7Fu1IFUZnKsEXz2bw.apply(Unknown Source:2)
at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
at org.junit.jupiter.engine.execution.-$$Lambda$ExecutableInvoker$261CBY1xI2VzNyAER1enkFZVl78.apply(Unknown Source:6)
at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$6$TestMethodTestDescriptor(TestMethodTestDescriptor.java:210)
at org.junit.jupiter.engine.descriptor.-$$Lambda$TestMethodTestDescriptor$eOXpdJL9axLS-As6h-8JcXoSDRw.execute(Unknown Source:6)
at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:206)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:131)
at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:65)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5$NodeTestTask(NodeTestTask.java:139)
at org.junit.platform.engine.support.hierarchical.-$$Lambda$NodeTestTask$iUXWHF1xaiNcYR5G5GdsQs0EZvw.execute(Unknown Source:2)
at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7$NodeTestTask(NodeTestTask.java:129)
at org.junit.platform.engine.support.hierarchical.-$$Lambda$NodeTestTask$EGvQnBKlf_egWc2nEHQLBdQ73ww.invoke(Unknown Source:2)
at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8$NodeTestTask(NodeTestTask.java:127)
at org.junit.platform.engine.support.hierarchical.-$$Lambda$NodeTestTask$xk_8gX_hho6ccqggbguYtLpCiYY.execute(Unknown Source:2)
at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
at org.junit.platform.engine.support.hierarchical.-$$Lambda$YtR87xxv7Lsk5lq-Q1zNp0wlLKE.accept(Unknown Source:2)
at java.util.ArrayList.forEach(ArrayList.java:1262)
at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5$NodeTestTask(NodeTestTask.java:143)
at org.junit.platform.engine.support.hierarchical.-$$Lambda$NodeTestTask$iUXWHF1xaiNcYR5G5GdsQs0EZvw.execute(Unknown Source:2)
at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7$NodeTestTask(NodeTestTask.java:129)
at org.junit.platform.engine.support.hierarchical.-$$Lambda$NodeTestTask$EGvQnBKlf_egWc2nEHQLBdQ73ww.invoke(Unknown Source:2)
at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8$NodeTestTask(NodeTestTask.java:127)
at org.junit.platform.engine.support.hierarchical.-$$Lambda$NodeTestTask$xk_8gX_hho6ccqggbguYtLpCiYY.execute(Unknown Source:2)
at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
at org.junit.platform.engine.support.hierarchical.-$$Lambda$YtR87xxv7Lsk5lq-Q1zNp0wlLKE.accept(Unknown Source:2)
at java.util.ArrayList.forEach(ArrayList.java:1262)
at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:38)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5$NodeTestTask(NodeTestTask.java:143)
at org.junit.platform.engine.support.hierarchical.-$$Lambda$NodeTestTask$iUXWHF1xaiNcYR5G5GdsQs0EZvw.execute(Unknown Source:2)
at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7$NodeTestTask(NodeTestTask.java:129)
at org.junit.platform.engine.support.hierarchical.-$$Lambda$NodeTestTask$EGvQnBKlf_egWc2nEHQLBdQ73ww.invoke(Unknown Source:2)
at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8$NodeTestTask(NodeTestTask.java:127)
at org.junit.platform.engine.support.hierarchical.-$$Lambda$NodeTestTask$xk_8gX_hho6ccqggbguYtLpCiYY.execute(Unknown Source:2)
at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:126)
at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:84)
at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:32)
at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:51)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:108)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0$EngineExecutionOrchestrator(EngineExecutionOrchestrator.java:54)
at org.junit.platform.launcher.core.-$$Lambda$EngineExecutionOrchestrator$CdfJJpbUlE7i83wtqJ017emB9-o.accept(Unknown Source:8)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:96)
at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:84)
at de.mannodermaus.junit5.AndroidJUnit5.run(AndroidJUnit5.java:111)
at org.junit.runners.Suite.runChild(Suite.java:128)
at org.junit.runners.Suite.runChild(Suite.java:27)
at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
at androidx.test.internal.runner.TestExecutor.execute(TestExecutor.java:56)
at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:395)
at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2205)
Caused by: java.net.SocketTimeoutException: timeout
at okio.SocketAsyncTimeout.newTimeoutException(JvmOkio.kt:144)
at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162)
at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:335)
at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:180)
at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
at java.lang.Thread.run(Thread.java:923)
Caused by: java.net.SocketException: Socket closed
at java.net.SocketInputStream.read(SocketInputStream.java:209)
at java.net.SocketInputStream.read(SocketInputStream.java:144)
at okio.InputStreamSource.read(JvmOkio.kt:91)
at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
... 20 more
```

**Comment by yschimke** [comment]
```
okhttp3.CallHandshakeTest > effectiveOrderInRestrictedJdk11[Pixel 4 - 11] FAILED 
        java.lang.NumberFormatException: For input string: "0.9"
        at java.lang.Integer.parseInt(Integer.java:615)

okhttp3.CallHandshakeTest > testDefaultHandshakeCipherSuiteOrderingTls12Restricted[Pixel 4 - 11] FAILED 
        java.lang.AssertionError:
        Expecting:

okhttp3.CallHandshakeTest > testDefaultHandshakeCipherSuiteOrderingTls12Modern[Pixel 4 - 11] FAILED 
        java.lang.AssertionError:
        Expecting:

okhttp3.CallHandshakeTest > testHandshakeCipherSuiteOrderingWhenReversed[Pixel 4 - 11] FAILED 
        java.lang.AssertionError:
        Expecting:

okhttp3.CallHandshakeTest > testDefaultHandshakeCipherSuiteOrderingTls13Modern[Pixel 4 - 11] FAILED 
        java.lang.NumberFormatException: For input string: "0.9"
        at java.lang.Integer.parseInt(Integer.java:615)

okhttp3.CallTest > leakedResponseBodyLogsStackTrace[Pixel 4 - 11] FAILED 
        java.lang.AssertionError: Timed out waiting for log message.
        at okhttp3.TestLogHandler.take(TestLogHandler.java:93)

okhttp3.CallTest > anonCipherSuiteUnsupported[Pixel 4 - 11] FAILED 
        java.lang.IllegalArgumentException: cipherSuite TLS_DH_anon_WITH_AES_128_GCM_SHA256 is not supported.
        at com.android.org.conscrypt.NativeCrypto.checkEnabledCipherSuites(NativeCrypto.java:1139)

okhttp3.CallTest > asyncLeakedResponseBodyLogsStackTrace[Pixel 4 - 11] FAILED 
        java.lang.AssertionError: Timed out waiting for log message.
        at okhttp3.TestLogHandler.take(TestLogHandler.java:93)

okhttp3.CallTest > recoverFromTlsHandshakeFailure_tlsFallbackScsvEnabled[Pixel 4 - 11] FAILED 
        java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:675)

okhttp3.CallTest > httpsWithIpAddress[Pixel 4 - 11] FAILED 
        java.lang.NullPointerException: Attempt to invoke virtual method 'int okhttp3.Response.code()' on a null object reference
        at okhttp3.RecordedResponse.assertCode(RecordedResponse.java:61)

okhttp3.CallTest > failingCallsDoNotInterfereWithConnection[Pixel 4 - 11] FAILED 
        org.opentest4j.AssertionFailedError:
        Expecting:

okhttp3.ConnectionSpecTest > tls_defaultCiphers_withFallbackIndicator[Pixel 4 - 11] FAILED 
        java.lang.IllegalArgumentException: cipherSuite SSL_RSA_WITH_RC4_128_MD5 is not supported.
        at com.google.android.gms.org.conscrypt.NativeCrypto.checkEnabledCipherSuites(:com.google.android.gms@204612046@20.46.12 (150400-341564925):6)

okhttp3.ConnectionSpecTest > tls_defaultCiphers_noFallbackIndicator[Pixel 4 - 11] FAILED 
        java.lang.IllegalArgumentException: cipherSuite SSL_RSA_WITH_RC4_128_MD5 is not supported.
        at com.google.android.gms.org.conscrypt.NativeCrypto.checkEnabledCipherSuites(:com.google.android.gms@204612046@20.46.12 (150400-341564925):6)

okhttp3.ConnectionSpecTest > tls_missingRequiredCipher[Pixel 4 - 11] FAILED 
        java.lang.IllegalArgumentException: cipherSuite SSL_RSA_WITH_RC4_128_SHA is not supported.
        at com.google.android.gms.org.conscrypt.NativeCrypto.checkEnabledCipherSuites(:com.google.android.gms@204612046@20.46.12 (150400-341564925):6)

okhttp3.ConnectionSpecTest > tls_explicitCiphers[Pixel 4 - 11] FAILED 
        java.lang.IllegalArgumentException: cipherSuite SSL_RSA_WITH_RC4_128_MD5 is not supported.
        at com.google.android.gms.org.conscrypt.NativeCrypto.checkEnabledCipherSuites(:com.google.android.gms@204612046@20.46.12 (150400-341564925):6)

okhttp3.ConnectionSpecTest > allEnabledTlsVersions[Pixel 4 - 11] FAILED 
        java.lang.AssertionError:
        Expecting:

okhttp3.ConnectionSpecTest > allEnabledCipherSuites[Pixel 4 - 11] FAILED 
        java.lang.IllegalArgumentException: cipherSuite SSL_RSA_WITH_RC4_128_SHA is not supported.
        at com.google.android.gms.org.conscrypt.NativeCrypto.checkEnabledCipherSuites(:com.google.android.gms@204612046@20.46.12 (150400-341564925):6)

okhttp3.ConnectionSpecTest > tls_missingTlsVersion[Pixel 4 - 11] FAILED 
        java.lang.IllegalArgumentException: cipherSuite SSL_RSA_WITH_RC4_128_MD5 is not supported.
        at com.google.android.gms.org.conscrypt.NativeCrypto.checkEnabledCipherSuites(:com.google.android.gms@204612046@20.46.12 (150400-341564925):6)

okhttp3.HttpUrlTest > fromJavaNetUrlUnsupportedScheme[Use get = true][Pixel 4 - 11] FAILED 
        java.net.MalformedURLException: unknown protocol: mailto
        at java.net.URL.<init>(URL.java:608)

okhttp3.HttpUrlTest > fromJavaNetUrlUnsupportedScheme[Use get = false][Pixel 4 - 11] FAILED 
        java.net.MalformedURLException: unknown protocol: mailto
        at java.net.URL.<init>(URL.java:608)

okhttp3.MediaTypeTest > testCharsetNameIsDoubleQuotedAndSingleQuoted[Use get = true][Pixel 4 - 11] FAILED 
        org.opentest4j.AssertionFailedError:
        Expecting:

okhttp3.MediaTypeTest > testCharsetNameIsDoubleQuotedAndSingleQuoted[Use get = false][Pixel 4 - 11] FAILED 
        org.opentest4j.AssertionFailedError:
        Expecting:

okhttp3.WebPlatformUrlTest > initializationError[Pixel 4 - 11] FAILED 
        java.lang.NullPointerException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkNotNullParameter, parameter $this$source
        at okio.Okio__JvmOkioKt.source(Unknown Source:2)

okhttp3.dnsoverhttps.DnsOverHttpsTest > usesCache[Pixel 4 - 11] FAILED 
        java.net.UnknownHostException: google.com
        at okhttp3.dnsoverhttps.DnsOverHttps.throwBestFailure(DnsOverHttps.kt:176)

okhttp3.internal.concurrent.TaskRunnerTest > differentQueuesAreParallel[Pixel 4 - 11] FAILED 
        java.lang.AssertionError:
        Expecting:

okhttp3.internal.concurrent.TaskRunnerTest > shutdownFailsToCancelsScheduledTasks[Pixel 4 - 11] FAILED 
        java.lang.AssertionError:
        Expecting:

okhttp3.internal.concurrent.TaskRunnerTest > executeDelayed[Pixel 4 - 11] FAILED 
        java.lang.AssertionError:
        Expecting:

okhttp3.internal.concurrent.TaskRunnerTest > interruptingCoordinatorAttemptsToCancelsAndFails[Pixel 4 - 11] FAILED 
        java.lang.AssertionError:
        Expecting:

okhttp3.internal.connection.RouteSelectorTest > routeToString[Pixel 4 - 11] FAILED 
        java.lang.NumberFormatException: For input string: "0.9"
        at java.lang.Integer.parseInt(Integer.java:615)

okhttp3.internal.tls.ClientAuthTest > invalidClientAuthFails[Pixel 4 - 11] FAILED 
        java.lang.AssertionError:
        Expecting:

okhttp3.internal.tls.ClientAuthTest > missingClientAuthFailsForNeeds[Pixel 4 - 11] FAILED 
        java.lang.AssertionError:
        Expecting:

okhttp3.internal.tls.HostnameVerifierTest > verifyNonAsciiSubjectAlt[Pixel 4 - 11] FAILED 
        java.lang.AssertionError:
        Expecting:

okhttp3.internal.tls.HostnameVerifierTest > testWilcardNonAsciiSubjectAlt[Pixel 4 - 11] FAILED 
        java.lang.AssertionError:
        Expecting:

okhttp3.internal.tls.HostnameVerifierTest > specialKInExternalCert[Pixel 4 - 11] FAILED 
        java.lang.AssertionError:
        Expecting:
```

**Comment by yschimke** [comment]
Draft PR for testing https://github.com/square/okhttp/pull/6424

**Comment by yschimke** [comment]
Will reopen after a clean run again, think just some failures in CallTest remain.
