### ISSUE TITLE
http2 SocketTimeoutException: timeout

### ISSUE THREAD

**Issue by wangduanqing5945** [square/okhttp#6485]
i got this issue on Android 11, After 5 minutes back in the background, back in the foreground.
The problem lasts for 3 to 5 minutes and then returns to normal

http1.1 is fine，it occurs when I upgrade to Http2.0

okhttp: com.squareup.okhttp3:okhttp:4.2.0

stack:

`
2020-12-21 18:17:14.815 6669-6669/com.meteor.vchat E/WowoLog: java.net.SocketTimeoutException: timeout
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.kt:662)
        at okhttp3.internal.http2.Http2Stream$StreamTimeout.exitAndThrowIfTimedOut(Http2Stream.kt:671)
        at okhttp3.internal.http2.Http2Stream.takeHeaders(Http2Stream.kt:142)
        at okhttp3.internal.http2.Http2ExchangeCodec.readResponseHeaders(Http2ExchangeCodec.kt:99)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:105)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at me.jessyan.progressmanager.ProgressManager$1.intercept(ProgressManager.java:97)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:37)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:215)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.meteor.vchat.base.api.WRetrofitClient$handleBuilder$$inlined$-addInterceptor$2.intercept(Interceptor.kt:81)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at com.meteor.vchat.base.api.WRetrofitClient$handleBuilder$$inlined$-addInterceptor$1.intercept(Interceptor.kt:99)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
        at okhttp3.RealCall$AsyncCall.run(RealCall.kt:136)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
`

**Comment by yschimke** [comment]
As a start, could you provide output from an event listener like https://square.github.io/okhttp/4.x/okhttp-logging-interceptor/okhttp3.logging/-logging-event-listener/

https://square.github.io/okhttp/events/

I don't expect it to solve the issue but will let us confirm whether it's reusing a previously acquired connection that is blocked, or if there is some other cause.

**Comment by wangduanqing5945** [comment]
@yschimke 

`2020-12-25 16:02:22.520 21296-28450/com.meteor.vchat I/okhttp.OkHttpClient: [0 ms] callStart: Request{method=POST, url=https://api.imkaka.com/v1/user/feed/list, tags={class retrofit2.Invocation=com.meteor.vchat.base.api.ProfileService.getFeedList() [0, 20]}}
2020-12-25 16:02:22.532 21296-32444/com.meteor.vchat I/okhttp.OkHttpClient: [11 ms] cacheMiss
2020-12-25 16:02:22.532 21296-32444/com.meteor.vchat I/okhttp.OkHttpClient: [12 ms] connectionAcquired: Connection{api.imkaka.com:443, proxy=DIRECT hostAddress=api.imkaka.com/39.107.209.71:443 cipherSuite=TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256 protocol=h2}
2020-12-25 16:02:22.532 21296-32444/com.meteor.vchat I/okhttp.OkHttpClient: [12 ms] requestHeadersStart
2020-12-25 16:02:22.534 21296-32444/com.meteor.vchat I/okhttp.OkHttpClient: [14 ms] requestHeadersEnd
2020-12-25 16:02:22.535 21296-32444/com.meteor.vchat I/okhttp.OkHttpClient: [15 ms] requestBodyStart
2020-12-25 16:02:22.536 21296-32444/com.meteor.vchat I/okhttp.OkHttpClient: [16 ms] requestBodyEnd: byteCount=16
2020-12-25 16:02:32.537 21296-32444/com.meteor.vchat I/okhttp.OkHttpClient: [10017 ms] responseFailed: java.net.SocketTimeoutException: timeout
2020-12-25 16:02:32.541 21296-32444/com.meteor.vchat I/okhttp.OkHttpClient: [10020 ms] connectionReleased
2020-12-25 16:02:32.541 21296-32444/com.meteor.vchat I/okhttp.OkHttpClient: [10021 ms] callFailed: java.net.SocketTimeoutException: timeout
`

**Comment by wangduanqing5945** [comment]
i upgrade OKHTTP version to 4.9.0, but issue still exist

**Comment by yschimke** [comment]
It's unlikely we can help you, it doesn't look like a reproducible bug we can fix.  For OkHttp this looks like the server is taking 10 seconds to respond and you are correctly getting a timeout.  The actual cause might be the server, or it might be a stuck/stale socket on the device, but OkHttp seems to be correctly sending the request without a write timeout failure or similar.

Closing here, you should trace the request on the server, try with an alternate development server/proxy or similar.  But likely there is not much we can help you with.

**Comment by EnzymeFan** [comment]
> i upgrade OKHTTP version to 4.9.0, but issue still exist

Any progress for share ? I met the similar issue @wangduanqing5945 

`
Caused by: com.yqg.ec.common.exception.EcException: Error when sending request, request: Request{method=POST, url=https://fcm.googleapis.com/v1/projects/easycash-prod/messages:send, tag=null}
	at com.yqg.ec.common.exception.EcException.error(EcException.java:25)
	at com.yqg.ec.common.exception.EcException.error(EcException.java:19)
	at com.yqg.core.util.httpservice.EcHttpClient.send(EcHttpClient.java:84)
	at com.yqg.core.util.httpservice.EcHttpClient.syncCallOrThrow(EcHttpClient.java:58)
	at com.yqg.core.service.firebase.FirebaseService.sendRequest(FirebaseService.java:189)
	at com.yqg.core.service.firebase.FirebaseService.pushToSingle(FirebaseService.java:114)
	... 23 common frames omitted
Caused by: java.net.SocketTimeoutException: timeout
	at okhttp3.internal.http2.Http2Stream$StreamTimeout.newTimeoutException(Http2Stream.java:593)
`

It always occurred at the peek hour of daily API callings, and never failback after it heppened everytime

**Comment by himanshubb** [comment]
@yschimke for me, I am okay if its throwing the `SocketTimeoutException`, but need help in finding the place where I can catch this exception and handle it gracefully..
because my retrofit is unable to catch this exception. which is causing my app to get crashed and bad user experience.

**Comment by ranjithd14** [comment]
Why this issue closed, without solving the issue?

**Comment by yschimke** [comment]
It's not clear there is anything for OkHttp to fix here. Looks like a server issue. If it's an OkHttp issue please provide a way to reproduce the issue.

**Comment by 1126174422** [comment]
> It's not clear there is anything for OkHttp to fix here. Looks like a server issue. If it's an OkHttp issue please provide a way to reproduce the issue.

i can reproduce the issue.

okhttp: com.squareup.okhttp3:okhttp:4.2.0

First, we need to break a request, for example, using Charles pairs to specify a breakpoint for a request. Then, while keeping request A in the breakpoint state, do not operate, and continue to initiate other requests b,c and so on. You will find that before request A is let go or terminated, the other requests can't be issued normally, which eventually leads to timeout. On the contrary, switching to http1.1 does not have this problem.

I believe that in the process of real users' use, there is a certain probability that one request will get stuck for some reasons, but this should not affect other requests. This seems to be caused by connection reuse.
