### ISSUE TITLE
🙉okhttp3 version:3.10.0 proguard 混淆打包的时候报错

### ISSUE THREAD

**Issue by liupeng1991** [square/okhttp#6493]
![image](https://user-images.githubusercontent.com/20416276/103275592-75fdfd80-49ff-11eb-87b3-a09ed93c2ca6.png)

**Comment by liupeng1991** [comment]
java.lang.AssertionError: No System TLS
        at okhttp3.internal.Util.assertionError(SourceFile:465)
        at okhttp3.OkHttpClient.systemDefaultSslSocketFactory(SourceFile:304)
        at okhttp3.OkHttpClient.<init>(SourceFile:255)
        at okhttp3.OkHttpClient.<init>(SourceFile:228)
        at com.liupeng.base.d.d.<init>(SourceFile:48)
        at com.liupeng.base.d.d.a(SourceFile:70)
        at com.liupeng.base.d.d.a(SourceFile:62)
        at com.app.MyApplication.onCreate(SourceFile:84)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1155)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5949)
        at android.app.ActivityThread.access$1200(ActivityThread.java:200)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:201)
        at android.app.ActivityThread.main(ActivityThread.java:6810)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)

**Comment by liupeng1991** [comment]
-dontwarn okhttp3.internal.platform.ConscryptPlatform
-dontwarn org.conscrypt.ConscryptHostnameVerifier
-dontwarn okhttp3.**
-dontwarn okio.**
-dontwarn javax.annotation.**
# A resource is loaded with a relative path so the package of this class must be preserved.
-keepnames class okhttp3.internal.publicsuffix.PublicSuffixDatabase

**Comment by yschimke** [comment]
There should be a chained exception which indicates the actual problem.  https://github.com/square/okhttp/blob/okhttp_3.10.x/okhttp/src/main/java/okhttp3/OkHttpClient.java#L294

But generally this represents a problem with the security providers and you should continue the discussion in Stackoverflow, please post a link the the question here.

See similar problems here https://github.com/square/okhttp/issues/3768
https://stackoverflow.com/questions/63937317/no-system-tls-on-android-after-using-bouncy-castle

Please reopen with a reproducible bug report, otherwise continue with stackoverflow.

**Comment by storytellerF** [comment]
add bouncycastle proguard rule

https://github.com/open-keychain/open-keychain/blob/master/OpenKeychain/proguard-rules-bouncycastle.pro

**Comment by liupeng1991** [comment]
您好，邮件已收到，待查阅后回复您。
