### ISSUE TITLE
new OkHttpClient.Builder().build() crash on android 4.4

### ISSUE THREAD

**Issue by andreu-sergienko** [square/okhttp#6505]
dependencies:
implementation 'com.squareup.okhttp3:logging-interceptor:3.12.12'
implementation 'com.squareup.okhttp3:okhttp:3.12.12'

android-version:4.4

log:
01-08 00:18:15.474 3092-3092/? E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.ksudev.mirtv, PID: 3092
    java.lang.ExceptionInInitializerError
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263)
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229)
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015)
        at com.ksudev.mirtv.g.h.<init>(RetrofitApi.java:76)
        at com.ksudev.mirtv.g.h.a(RetrofitApi.java:112)
        at com.ksudev.mirtv.c.b.a(AddChannelModel.java:25)
        at com.ksudev.mirtv.f.k.a(SplashPresenter.java:32)
        at com.ksudev.mirtv.SplashActivity.onCreate(SplashActivity.java:21)
        at android.app.Activity.performCreate(Activity.java:5231)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245)
        at android.app.ActivityThread.access$800(ActivityThread.java:135)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:136)
        at android.app.ActivityThread.main(ActivityThread.java:5017)
        at java.lang.reflect.Method.invokeNative(Native Method)
        at java.lang.reflect.Method.invoke(Method.java:515)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
        at dalvik.system.NativeStart.main(Native Method)
     Caused by: java.lang.IllegalStateException: Expected Android API level 21+ but was 19
        at okhttp3.internal.platform.AndroidPlatform.buildIfSupported(AndroidPlatform.java:243)
        at okhttp3.internal.platform.Platform.findAndroidPlatform(Platform.java:247)
        at okhttp3.internal.platform.Platform.findPlatform(Platform.java:203)
        at okhttp3.internal.platform.Platform.<clinit>(Platform.java:79)
        at okhttp3.OkHttpClient.newSslSocketFactory(OkHttpClient.java:263) 
        at okhttp3.OkHttpClient.<init>(OkHttpClient.java:229) 
        at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java:1015) 
        at com.ksudev.mirtv.g.h.<init>(RetrofitApi.java:76) 
        at com.ksudev.mirtv.g.h.a(RetrofitApi.java:112) 
        at com.ksudev.mirtv.c.b.a(AddChannelModel.java:25) 
        at com.ksudev.mirtv.f.k.a(SplashPresenter.java:32) 
        at com.ksudev.mirtv.SplashActivity.onCreate(SplashActivity.java:21) 
        at android.app.Activity.performCreate(Activity.java:5231) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1087) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2159) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2245) 
        at android.app.ActivityThread.access$800(ActivityThread.java:135) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1196) 
        at android.os.Handler.dispatchMessage(Handler.java:102) 
        at android.os.Looper.loop(Looper.java:136) 
        at android.app.ActivityThread.main(ActivityThread.java:5017) 
        at java.lang.reflect.Method.invokeNative(Native Method) 
        at java.lang.reflect.Method.invoke(Method.java:515) 
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595) 
        at dalvik.system.NativeStart.main(Native Method)

**Comment by yschimke** [comment]
Check your resolved dependencies. Likely something is bumping you up to 4.x

**Comment by congnt148** [comment]
Android 4.4 (works for me)

```
implementation ("com.squareup.okhttp3:okhttp:3.12.12"){
   force = true //API 19 support
}
```

**Comment by andreu-sergienko** [comment]
@congnt148  Thank you! Its works!
