### ISSUE TITLE
java.lang.IllegalStateException invalid dictionary: prefix not unique

### ISSUE THREAD

**Issue by CharlesTai** [square/okhttp#6517]
sdk version:
    implementation 'com.squareup.retrofit2:retrofit:2.4.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.4.0'
    implementation 'com.squareup.retrofit2:adapter-rxjava2:2.4.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:3.12.12'
Android version:
    Android 11
Device:
    OPPO,vivo,pixel...
I'm facing a issue that crash in Android 11.
this is the crash log:

Fatal Exception: java.lang.ExceptionInInitializerError
       at okhttp3.internal.http2.Hpack$Writer.writeByteString(Hpack.java:552)
       at okhttp3.internal.http2.Hpack$Writer.writeHeaders(Hpack.java:520)
       at okhttp3.internal.http2.Http2Writer.headers(Http2Writer.java:299)
       at okhttp3.internal.http2.Http2Writer.synStream(Http2Writer.java:126)
       at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:259)
       at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:231)
       at okhttp3.internal.http2.Http2Codec.writeRequestHeaders(Http2Codec.java:117)
       at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:50)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
       at okhttp3.RealCall.execute(RealCall.java:92)
       at com.google.firebase.crashlytics.internal.network.HttpRequest.execute(HttpRequest.java:129)
       at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:86)
       at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:200)
       at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:193)
       at com.google.android.gms.tasks.zzo.run(zzo.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:64)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
       at java.lang.Thread.run(Thread.java:923)

Caused by java.lang.IllegalStateException: invalid dictionary: prefix not unique
       at okhttp3.internal.http2.Huffman.addCode(Huffman.java:180)
       at okhttp3.internal.http2.Huffman.buildTree(Huffman.java:168)
       at okhttp3.internal.http2.Huffman.<init>(Huffman.java:88)
       at okhttp3.internal.http2.Huffman.<clinit>(Huffman.java:79)
       at okhttp3.internal.http2.Hpack$Writer.writeByteString(Hpack.java:552)
       at okhttp3.internal.http2.Hpack$Writer.writeHeaders(Hpack.java:520)
       at okhttp3.internal.http2.Http2Writer.headers(Http2Writer.java:299)
       at okhttp3.internal.http2.Http2Writer.synStream(Http2Writer.java:126)
       at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:259)
       at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.java:231)
       at okhttp3.internal.http2.Http2Codec.writeRequestHeaders(Http2Codec.java:117)
       at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:50)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
       at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:254)
       at okhttp3.RealCall.execute(RealCall.java:92)
       at com.google.firebase.crashlytics.internal.network.HttpRequest.execute(HttpRequest.java:129)
       at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:86)
       at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:200)
       at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:193)
       at com.google.android.gms.tasks.zzo.run(zzo.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:64)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
       at java.lang.Thread.run(Thread.java:923)

and firebase sdk version if you need:
    // Import the Firebase BoM
    implementation platform('com.google.firebase:firebase-bom:26.1.0')
    // When using the BoM, you don't specify versions in Firebase library dependencies
    implementation 'com.google.firebase:firebase-analytics'     // firebase analytics
    implementation 'com.google.firebase:firebase-messaging'     // firebase 推送
    implementation 'com.google.firebase:firebase-crashlytics'   // firebase crashlytics
    implementation 'com.google.firebase:firebase-perf'          // firebase performance

![image](https://user-images.githubusercontent.com/13956257/104979336-fdf38800-5a3e-11eb-99f7-282d42fe7905.png)

please help me clean this issue. thanks

**Comment by swankjesse** [comment]
This looks like a runtime bug in vivo devices on Android 11. Could you please report to the device manufacturer?

Alternately, could you provide an executable test case?

**Comment by CharlesTai** [comment]
> This looks like a runtime bug in vivo devices on Android 11. Could you please report to the device manufacturer?
> 
> Alternately, could you provide an executable test case?

I can't recurrent this bug, so I can't provide an executable test case. and i found this bug in vivo, oppo and google pixel devides, maybe is not the devices bug?

**Comment by swankjesse** [comment]
Vivo and Oppo are the same company. Google is different – can you paste info on the Google crash? It might tell us something.

**Comment by CharlesTai** [comment]
> Vivo and Oppo are the same company. Google is different – can you paste info on the Google crash? It might tell us something.

OK thanks , i will report this bug to vivo and Google.

**Comment by yschimke** [comment]
Also https://stackoverflow.com/questions/65784940/java-lang-illegalstateexception-invalid-dictionary-prefix-not-unique

**Comment by AIRongbin1990** [comment]
> > Vivo and Oppo are the same company. Google is different – can you paste info on the Google crash? It might tell us something.
> 
> OK thanks , i will report this bug to vivo and Google.

Hi, Same issue for our App. Is your problem solved?
