### ISSUE TITLE
Deadlock with SocketChannelImpl on JDK11

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6558]
Out of https://github.com/square/okhttp/pull/6554

We end up with reader threads blocked in SocketChannelRead with a lock

```
"OkHttp localhost@4208" daemon prio=5 tid=0x32 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	 blocks OkHttp https://localhost:61953/...@3648
	  at sun.nio.ch.FileDispatcherImpl.read0(FileDispatcherImpl.java:-1)
	  at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	  at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	  at sun.nio.ch.IOUtil.read(IOUtil.java:245)
	  at sun.nio.ch.IOUtil.read(IOUtil.java:223)
	  at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:355)
	  at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:203)
	  - locked <0x1097> (a java.lang.Object)
	  at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	  - locked <0x1098> (a sun.nio.ch.SocketAdaptor$SocketInputStream)
	  at sun.security.ssl.SSLSocketInputRecord.read(SSLSocketInputRecord.java:478)
	  at sun.security.ssl.SSLSocketInputRecord.readHeader(SSLSocketInputRecord.java:472)
	  at sun.security.ssl.SSLSocketInputRecord.bytesInCompletePacket(SSLSocketInputRecord.java:70)
	  at sun.security.ssl.SSLSocketImpl.readApplicationRecord(SSLSocketImpl.java:1354)
	  at sun.security.ssl.SSLSocketImpl$AppInputStream.read(SSLSocketImpl.java:963)
	  at okio.InputStreamSource.read(JvmOkio.kt:93)
	  at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
	  at okio.RealBufferedSource.request(RealBufferedSource.kt:60)
	  at okio.RealBufferedSource.require(RealBufferedSource.kt:53)
	  at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:89)
	  at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:618)
	  at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
	  at okhttp3.internal.concurrent.TaskQueue$execute$1.runOnce(TaskQueue.kt:98)
	  at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
	  at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
	  at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	  at java.lang.Thread.run(Thread.java:834)
```

and writers blocked at 

```
"OkHttp https://localhost:61953/...@3648" prio=5 tid=0x2e nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for OkHttp localhost@4208 to release lock on <0x1097> (a java.lang.Object)
	  at java.nio.channels.Channels.writeFully(Channels.java:92)
	  at java.nio.channels.Channels$1.write(Channels.java:172)
	  - locked <0x1094> (a java.nio.channels.Channels$1)
	  at sun.security.ssl.SSLSocketOutputRecord.deliver(SSLSocketOutputRecord.java:319)
	  - locked <0x1095> (a sun.security.ssl.SSLSocketOutputRecord)
	  at sun.security.ssl.SSLSocketImpl$AppOutputStream.write(SSLSocketImpl.java:1202)
	  at okio.OutputStreamSink.write(JvmOkio.kt:56)
	  at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)
	  at okio.RealBufferedSink.flush(RealBufferedSink.kt:183)
	  at okhttp3.internal.http2.Http2Writer.flush(Http2Writer.kt:120)
	  - locked <0x1096> (a okhttp3.internal.http2.Http2Writer)
	  at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.kt:268)
	  at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.kt:225)
	  at okhttp3.internal.http2.Http2ExchangeCodec.writeRequestHeaders(Http2ExchangeCodec.kt:76)
	  at okhttp3.internal.connection.Exchange.writeRequestHeaders(Exchange.kt:63)
	  at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:41)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	  at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	  at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	  at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	  at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	  at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	  at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	  at java.lang.Thread.run(Thread.java:834)
```

worse when we timeout they cleanup works gets blocked in a closeQuietly call

```
"Test worker@1603" prio=5 tid=0xf nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for OkHttp localhost@4209 to release lock on <0x1139> (a java.lang.Object)
	  at java.nio.channels.Channels.writeFully(Channels.java:92)
	  at java.nio.channels.Channels$1.write(Channels.java:172)
	  - locked <0x1137> (a java.nio.channels.Channels$1)
	  at sun.security.ssl.SSLSocketOutputRecord.encodeAlert(SSLSocketOutputRecord.java:81)
	  - locked <0x1138> (a sun.security.ssl.SSLSocketOutputRecord)
	  at sun.security.ssl.TransportContext.warning(TransportContext.java:247)
	  at sun.security.ssl.SSLSocketImpl.closeNotify(SSLSocketImpl.java:645)
	  at sun.security.ssl.SSLSocketImpl.duplexCloseOutput(SSLSocketImpl.java:631)
	  at sun.security.ssl.SSLSocketImpl.close(SSLSocketImpl.java:566)
	  at okhttp3.internal.Util.closeQuietly(Util.kt:507)
	  at okhttp3.internal.connection.RealConnectionPool.evictAll(RealConnectionPool.kt:132)
	  at okhttp3.ConnectionPool.evictAll(ConnectionPool.kt:57)
	  at okhttp3.OkHttpClientTestRule.ensureAllConnectionsReleased(OkHttpClientTestRule.kt:148)
	  at okhttp3.OkHttpClientTestRule.afterEach(OkHttpClientTestRule.kt:212)
```

**Comment by yschimke** [comment]
Example with Conscrypt

```
"OkHttp https://local.host:57397/...@3873" prio=5 tid=0x26 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 blocks OkHttp local.host applyAndAckSettings@3733
	 waiting for OkHttp local.host@3894 to release lock on <0xf56> (a java.lang.Object)
	  at java.nio.channels.Channels.writeFully(Channels.java:92)
	  at java.nio.channels.Channels$1.write(Channels.java:172)
	  - locked <0xf54> (a java.nio.channels.Channels$1)
	  at org.conscrypt.ConscryptEngineSocket$SSLOutputStream.writeToSocket(ConscryptEngineSocket.java:699)
	  at org.conscrypt.ConscryptEngineSocket$SSLOutputStream.writeInternal(ConscryptEngineSocket.java:673)
	  at org.conscrypt.ConscryptEngineSocket$SSLOutputStream.write(ConscryptEngineSocket.java:636)
	  - locked <0xf55> (a java.lang.Object)
	  at okio.OutputStreamSink.write(JvmOkio.kt:56)
	  at okio.AsyncTimeout$sink$1.write(AsyncTimeout.kt:99)
	  at okio.RealBufferedSink.flush(RealBufferedSink.kt:183)
	  at okhttp3.internal.http2.Http2Writer.flush(Http2Writer.kt:120)
	  - locked <0xf53> (a okhttp3.internal.http2.Http2Writer)
	  at okhttp3.internal.http2.Http2Connection.newStream(Http2Connection.kt:268)
```

```
"OkHttp local.host@3894" daemon prio=5 tid=0x29 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
	 blocks OkHttp https://local.host:57397/...@3873
	  at sun.nio.ch.FileDispatcherImpl.read0(FileDispatcherImpl.java:-1)
	  at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	  at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:276)
	  at sun.nio.ch.IOUtil.read(IOUtil.java:245)
	  at sun.nio.ch.IOUtil.read(IOUtil.java:223)
	  at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:355)
	  at sun.nio.ch.SocketAdaptor$SocketInputStream.read(SocketAdaptor.java:203)
	  - locked <0xf56> (a java.lang.Object)
	  at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
	  - locked <0xf58> (a sun.nio.ch.SocketAdaptor$SocketInputStream)
	  at org.conscrypt.ConscryptEngineSocket$SSLInputStream.readFromSocket(ConscryptEngineSocket.java:920)
	  at org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:884)
	  at org.conscrypt.ConscryptEngineSocket$SSLInputStream.readUntilDataAvailable(ConscryptEngineSocket.java:799)
	  at org.conscrypt.ConscryptEngineSocket$SSLInputStream.read(ConscryptEngineSocket.java:772)
	  - locked <0xf59> (a java.lang.Object)
	  at okio.InputStreamSource.read(JvmOkio.kt:93)
	  at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:125)
	  at okio.RealBufferedSource.request(RealBufferedSource.kt:60)
	  at okio.RealBufferedSource.require(RealBufferedSource.kt:53)
	  at okhttp3.internal.http2.Http2Reader.nextFrame(Http2Reader.kt:89)
	  at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:618)
	  at okhttp3.internal.http2.Http2Connection$ReaderRunnable.invoke(Http2Connection.kt:609)
```

```
"OkHttp local.host applyAndAckSettings@3733" daemon prio=5 tid=0x18 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 waiting for OkHttp https://local.host:57397/...@3873 to release lock on <0xf53> (a okhttp3.internal.http2.Http2Writer)
	  at okhttp3.internal.http2.Http2Connection$ReaderRunnable.applyAndAckSettings(Http2Connection.kt:737)
	  at okhttp3.internal.http2.Http2Connection$ReaderRunnable$settings$$inlined$execute$1.runOnce(Http2Connection.kt:716)
	  at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
	  at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
	  at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
	  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	  at java.lang.Thread.run(Thread.java:834)
```

**Comment by swankjesse** [comment]
That stacktrace shows a very bad bug in ChannelInputStream on Java 11: the lock on `0xf56` is way too coarse.

We’re doing a blocking read with thread @3894. Such reads are allowed to take a long time to complete; it is waiting for the peer to send data. While it reads ChannelInputStream is locking `0xf56`:

```
"OkHttp local.host@3894" daemon prio=5 tid=0x29 nid=NA runnable
  java.lang.Thread.State: RUNNABLE
         ...
	  - locked <0xf56> (a java.lang.Object)
	  at sun.nio.ch.ChannelInputStream.read(ChannelInputStream.java:103)
```

But thread @3873 can’t write until that blocking read returns?! 

```
OkHttp https://local.host:57397/...@3873" prio=5 tid=0x26 nid=NA waiting for monitor entry
  java.lang.Thread.State: BLOCKED
	 blocks OkHttp local.host applyAndAckSettings@3733
	 waiting for OkHttp local.host@3894 to release lock on <0xf56> (a java.lang.Object)
	  at java.nio.channels.Channels.writeFully(Channels.java:92)
```

This is a pretty severe bug in `ChannelInputStream`, and it suggests bad things about the way concurrency is tested for that class.

**Comment by swankjesse** [comment]
https://stackoverflow.com/a/175025/40013

**Comment by swankjesse** [comment]
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=4509080

**Comment by yschimke** [comment]
New bug got closed which seems fine https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8261798
