### ISSUE TITLE
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException length=2048; regionStart=2048; regionLength=2048 

### ISSUE THREAD

**Issue by whoislxy** [square/okhttp#6564]
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: length=2048; regionStart=2048; regionLength=2048
       at libcore.util.ArrayUtils.throwsIfOutOfBounds(ArrayUtils.java:40)
       at libcore.io.IoBridge.write(IoBridge.java:533)
       at java.io.FileOutputStream.write(FileOutputStream.java:392)
       at com.android.okhttp.okio.Okio$1.write(Okio.java:78)
       at com.android.okhttp.okio.ForwardingSink.write(ForwardingSink.java:37)
       at com.android.okhttp.internal.FaultHidingSink.write(FaultHidingSink.java:23)
       at com.android.okhttp.okio.ForwardingSink.write(ForwardingSink.java:37)
       at com.android.okhttp.okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.java:177)
       at com.android.okhttp.internal.http.HttpEngine$2.read(HttpEngine.java:810)
       at com.android.okhttp.internal.Util.skipAll(Util.java:165)
       at com.android.okhttp.internal.Util.discard(Util.java:147)
       at com.android.okhttp.internal.http.HttpEngine$2.close(HttpEngine.java:820)
       at com.android.okhttp.okio.RealBufferedSource.close(RealBufferedSource.java:397)
       at com.android.okhttp.okio.RealBufferedSource$1.close(RealBufferedSource.java:385)
       at com.google.android.gms.internal.firebase_messaging.zzh.zza(zzh.java:2)
       at com.google.firebase.messaging.ImageDownload.close(ImageDownload.java:1)
       at com.google.firebase.messaging.DisplayNotification.waitForAndApplyImageDownload(DisplayNotification.java:5)
       at com.google.firebase.messaging.DisplayNotification.handleNotification(DisplayNotification.java:5)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(FirebaseMessagingService.java:8)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(FirebaseMessagingService.java:8)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(FirebaseMessagingService.java:3)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(FirebaseMessagingService.java:3)
       at com.google.android.gms.tasks.TaskCompletionSource.setResult(TaskCompletionSource.java:8)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(EnhancedIntentService.java:1)
       at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(EnhancedIntentService.java:6)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:6)
       at java.lang.Thread.run(Thread.java:919)
       
       okhttp version：5.0.0-alpha.2

**Comment by yschimke** [comment]
This is a bug in Android (AOSP) fork of OkHttp

Com.android.okhttp

**Comment by whoislxy** [comment]
How can I fix it？

**Comment by whoislxy** [comment]
Fatal Exception: java.lang.ArrayIndexOutOfBoundsException
       at com.android.okio.Util.checkOffsetAndCount(Util.java:29)
       at com.android.okio.Okio.copy(Okio.java:39)
       at com.android.okhttp.internal.http.HttpConnection$AbstractSource.cacheWrite(HttpConnection.java:378)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:449)
       at com.android.okhttp.internal.Util.skipAll(Util.java:227)
       at com.android.okhttp.internal.http.HttpConnection.discard(HttpConnection.java:212)
       at com.android.okhttp.internal.http.HttpConnection$FixedLengthSource.close(HttpConnection.java:464)
       at com.android.okio.RealBufferedSource.close(RealBufferedSource.java:198)
       at com.android.okio.RealBufferedSource$1.close(RealBufferedSource.java:181)
       at com.google.android.gms.internal.firebase_messaging.zzh.zza(zzh.java:2)
       at com.google.firebase.messaging.ImageDownload.close(ImageDownload.java:1)
       at com.google.firebase.messaging.DisplayNotification.waitForAndApplyImageDownload(DisplayNotification.java:5)
       at com.google.firebase.messaging.DisplayNotification.handleNotification(DisplayNotification.java:5)
       at com.google.firebase.messaging.FirebaseMessagingService.dispatchMessage(FirebaseMessagingService.java:8)
       at com.google.firebase.messaging.FirebaseMessagingService.passMessageIntentToSdk(FirebaseMessagingService.java:8)
       at com.google.firebase.messaging.FirebaseMessagingService.handleMessageIntent(FirebaseMessagingService.java:3)
       at com.google.firebase.messaging.FirebaseMessagingService.handleIntent(FirebaseMessagingService.java:3)
       at com.google.firebase.messaging.EnhancedIntentService.lambda$processIntent$0$EnhancedIntentService(EnhancedIntentService.java:1)
       at com.google.firebase.messaging.EnhancedIntentService$$Lambda$0.run(EnhancedIntentService.java)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at com.google.android.gms.common.util.concurrent.zza.run(zza.java:2)
       at java.lang.Thread.run(Thread.java:818)

**Comment by yschimke** [comment]
Raise a bug with Android AOSP or the library using it.
