### ISSUE TITLE
Socket Closed Exception while downloading files in a multithread environment

### ISSUE THREAD

**Issue by pradeepkumrawat** [square/okhttp#6628]
Hi, I am facing below exception while downloading multiple files in different threads. Using OkHttp 4.4.0 version for this.

java.net.SocketTimeoutException: timeout
	at okio.SocketAsyncTimeout.newTimeoutException(Okio.kt:149)
	at okio.AsyncTimeout.access$newTimeoutException(AsyncTimeout.kt:162)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:340)
	at okio.RealBufferedSource.read(RealBufferedSource.kt:188)
	at okhttp3.internal.http1.Http1ExchangeCodec$AbstractSource.read(Http1ExchangeCodec.kt:349)
	at okhttp3.internal.http1.Http1ExchangeCodec$FixedLengthSource.read(Http1ExchangeCodec.kt:386)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:276)
	at okio.RealBufferedSource.read(RealBufferedSource.kt:188)
	at com.thalesifec.framework.connectivityservice.plugin.servers.contentserviceplugin.DownloadManager.doDownload(DownloadManager.java:237)
	at com.thalesifec.framework.connectivityservice.plugin.servers.contentserviceplugin.DownloadManager.processDownload(DownloadManager.java:174)
	at com.thalesifec.framework.connectivityservice.plugin.servers.contentserviceplugin.DownloadManager.downloadFile(DownloadManager.java:96)
	at com.thalesifec.framework.connectivityservice.plugin.servers.ContentService.getFile(ContentService.java:404)
	at com.thalesifec.framework.connectivityservice.plugin.servers.ContentService.lambda$startFetchingContents$1(ContentService.java:607)
	at com.thalesifec.framework.connectivityservice.plugin.servers.ContentService$$Lambda$212/9208225.run(Unknown Source)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:183)
	at java.net.SocketInputStream.read(SocketInputStream.java:121)
	at okio.InputStreamSource.read(Okio.kt:93)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:129)
	... 16 common frames omitted

Can anyone please help me on this?

**Comment by yschimke** [comment]
Can you move this discussion to stackoverflow, we try to keep the issue tracker for reproducible bug reports.  Also consider updating to a recent release.
