### ISSUE TITLE
Most secondary builds have 1-2 legit failures

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6648]
See https://github.com/square/okhttp/actions

https://github.com/square/okhttp/actions/runs/781182353

Open JSSE

```
CallHandshakeTest > testDefaultHandshakeCipherSuiteOrderingTls13Modern() FAILED
    org.opentest4j.AssertionFailedError: JDK with version 8 expected to fail with exception that ANYTHING
```

Bouncycastle

```
CallHandshakeTest > testHandshakeCipherSuiteOrderingWhenReversed() FAILED
    org.bouncycastle.tls.TlsFatalAlertReceived: handshake_failure(40)
```

Conscrypt

```
CertificatePinnerChainValidationTest > signersMustHaveCaBitSet() FAILED
    org.opentest4j.AssertionFailedError: expected connection failure but got Response{protocol=h2, code=200, message=, url=https://localhost:44305/}
```

Windows

```
DiskLruCacheTest > [2] (NioSystemFileSystem, true) FAILED
    java.io.IOException: Failed to delete temp directory C:\Users\RUNNER~1\AppData\Local\Temp\junit6432741218474853413. The following paths could not be deleted (see suppressed exceptions for details): , journal
 ````

Graal

```
   ├─ WebPlatformUrlTest ✔
   │  └─ httpUrl(WebPlatformUrlTestData) ✘ Failed to find a no-argument constructor for ArgumentsProvider [okhttp3.WebPlatformUrlTest$TestDataParamProvider]. Please ensure that a no-argument constructor exists and that the class is either a top-level class or a static nested class
```

Android (29)

```
okhttp3.dnsoverhttps.DnsOverHttpsTest > usesCache[test(AVD) - 10] FAILED 
	java.net.UnknownHostException: google.com
	at okhttp3.dnsoverhttps.DnsOverHttps.throwBestFailure(DnsOverHttps.kt:170)
```

ALPN

```
SessionReuseTest > testSessionReuse(String) > okhttp3.SessionReuseTest.testSessionReuse(String)[1] FAILED
    javax.net.ssl.SSLHandshakeException: No new session is allowed and no existing session can be resumed
```

**Comment by yschimke** [comment]
Linked issue https://github.com/square/okhttp/issues/6506

**Comment by yschimke** [comment]
Conscrypt relates to this PR https://github.com/square/okhttp/pull/6586

**Comment by yschimke** [comment]
Also seen 

```

ClientAuthTest > missingClientAuthFailsForNeeds() FAILED
    java.io.IOException: exhausted all routes
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:132)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at okhttp3.internal.tls.ClientAuthTest.missingClientAuthFailsForNeeds(ClientAuthTest.java:210)
```

**Comment by yschimke** [comment]
```
HttpOverHttp2Test > responseHeadersAfterGoaway(Protocol, MockWebServer) > okhttp3.internal.http2.HttpOverHttp2Test.responseHeadersAfterGoaway(Protocol, MockWebServer)[2] FAILED
    org.opentest4j.AssertionFailedError: 
    Expecting:
     <null>
    to be equal to:
     <"ABC">
    but was not.
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at okhttp3.internal.http2.HttpOverHttp2Test.responseHeadersAfterGoaway(HttpOverHttp2Test.java:1814)
```

**Comment by swankjesse** [comment]
Thanks for cataloging this.

**Comment by yschimke** [comment]
@swankjesse the Conscrypt report https://github.com/google/conscrypt/issues/1018

**Comment by swankjesse** [comment]
@yschimke for Conscrypt I think their implementation is correct and OkHttp needs to add a CA check here:
https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/internal/tls/BasicCertificateChainCleaner.kt#L99

We're doing our own path building, and I didn't include code to reject this case.

**Comment by yschimke** [comment]
Closing in favour of individual issues.  We have skipped ones we understand and haven't prioritised.  So nothing to do here at the moment.
