### ISSUE TITLE
java.lang.IllegalStateException: Logger.getLogger(TaskRunner::class.java.name) must not be null

### ISSUE THREAD

**Issue by rajnisingla** [square/okhttp#6673]
05-07 01:12:57.834  7624  7624 E AndroidRuntime: java.lang.ExceptionInInitializerError
05-07 01:12:57.834  7624  7624 E AndroidRuntime:        at okhttp3.ConnectionPool.<init>(ConnectionPool.java:40)
05-07 01:12:57.834  7624  7624 E AndroidRuntime:        at okhttp3.ConnectionPool.<init>(ConnectionPool.java:47)
05-07 01:12:57.834  7624  7624 E AndroidRuntime:        at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.java:471)

05-07 01:12:57.834  7624  7624 E AndroidRuntime: Caused by: java.lang.IllegalStateException: Logger.getLogger(TaskRunner::class.java.name) must not be null
05-07 01:12:57.834  7624  7624 E AndroidRuntime:        at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.java:311)

We get this stacktrace while we launch our android application. Could anyone please help with this?
Okhttp version : 4.8.0
Will be happy to provide any other information that is required.

**Comment by swankjesse** [comment]
Looks like an issue with your device. Can you create a test case to reproduce this?!

**Comment by rajnisingla** [comment]
I believe with usual android configuration it works fine.
I tested using multiple devices across multiple android version. The issue exists. If it helps, we are working with a chromium fork project which is java based. Earlier with chromium 87 version, it was working fine. When we moved to chromium 89, we started getting this crash. So may be it has something to do with build tools versions used or R8/proguard. Chromium uses full R8 mode.

**Comment by rajnisingla** [comment]
I confirmed just now. With debug build it is working fine. The issue is with release build only so it has something to do with R8 obfuscation and optimization.

**Comment by rajnisingla** [comment]
No, i figured out the issue just now. It was due to a recent change in one of chromium proguard files.

-assumenosideeffects class java.util.logging.Logger {
    void finest(...);
    void finer(...);
    void fine(...);
    void info(...);
    void warning(...);
    void severe(...);
    void throwing(...);
    void log(...);
    void logp(...);
    static java.util.logging.Logger getLogger(...) return null;
    boolean isLoggable(...) return false;
}

see here getLogger api is returning null always. This was causing the issue. Once i removed this rule, it worked. So there was no issue with okhttp. So I can close this issue now.
