### ISSUE TITLE
java.lang.VerifyError

### ISSUE THREAD

**Issue by NewHuLe** [square/okhttp#6680]
android version: Android 9
okhttp version: 4.9.0
gradle version: 4.1.2
Fatal Exception: java.lang.VerifyError: Rejecting class kotlin.ranges.RangesKt that attempts to sub-type erroneous class kotlin.ranges.RangesKt___RangesKt (declaration of 'kotlin.ranges.RangesKt' appears in base.apk!classes4.dex)
       at okhttp3.Headers$Companion.of(Headers.java:373)
       at okhttp3.internal.Util.<clinit>(Util.java:63)
       at okhttp3.internal.Util.immutableListOf(Util.java:473)
       at okhttp3.OkHttpClient.<clinit>(OkHttpClient.java:1073)
       at com.google.firebase.crashlytics.internal.network.HttpRequest.<clinit>(HttpRequest.java:43)
       at com.google.firebase.crashlytics.internal.network.HttpRequestFactory.buildHttpRequest(HttpRequestFactory.java:43)
       at com.google.firebase.crashlytics.internal.common.AbstractSpiCall.getHttpRequest(AbstractSpiCall.java:113)
       at com.google.firebase.crashlytics.internal.settings.network.DefaultSettingsSpiCall.invoke(DefaultSettingsSpiCall.java:80)
       at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:200)
       at com.google.firebase.crashlytics.internal.settings.SettingsController$1.then(SettingsController.java:193)
       at com.google.android.gms.tasks.zzp.run(zzp.java:2)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at com.google.firebase.crashlytics.internal.common.ExecutorUtils$1$1.onRun(ExecutorUtils.java:60)
       at com.google.firebase.crashlytics.internal.common.BackgroundPriorityRunnable.run(BackgroundPriorityRunnable.java:27)
       at java.lang.Thread.run(Thread.java:764)

**Comment by yschimke** [comment]
We will need a repro for this, can't make any progress with this report as is.  Possible build related?  Sorry.
