### ISSUE TITLE
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 10547040 free bytes and 10MB until OOM, max allowed footprint 536870912, growth limit 536870912; failed due to fragmentation (largest possible contiguous allocation 0 bytes)

### ISSUE THREAD

**Issue by wj576038874** [square/okhttp#6687]
java.lang.OutOfMemoryError: Failed to allocate a 16 byte allocation with 10547040 free bytes and 10MB until OOM, max allowed footprint 536870912, growth limit 536870912; failed due to fragmentation (largest possible contiguous allocation 0 bytes)
	at libcore.io.IoBridge.closeAndSignalBlockedThreads(IoBridge.java:242)
	at java.io.FileInputStream.close(FileInputStream.java:418)
	at okio.Okio$2.close(Okio.java:1)
	at okhttp3.internal.Util.closeQuietly(Util.java:1)
	at okhttp3.RequestBody$3.writeTo(RequestBody.java:3)
	at okhttp3.MultipartBody.writeOrCountBytes(MultipartBody.java:24)
	at okhttp3.MultipartBody.writeTo(MultipartBody.java:1)
	at com.upyun.library.common.ProgressRequestBody.writeTo(ProgressRequestBody.java:3)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:20)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:7)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:22)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:22)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:9)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:10)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:1)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:13)
	at okhttp3.RealCall.execute(RealCall.java:9)
	at com.upyun.library.common.UploadClient.fromUpLoad2(UploadClient.java:14)
	at com.upyun.library.common.FormUploader2.run(FormUploader2.java:20)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:764)

**Comment by JakeWharton** [comment]
Your heap is fragmented seemingly beyond repair. Per the exception message, your heap is at the maximum size and can support 0 new bytes being allocated. This means whoever calls `new` next will get this OOM. In this case it was OkHttp, but it could have been any library or even your own code. There is nothing OkHttp can do here.

**Comment by yschimke** [comment]
There is a "He who smelt it dealt it" soft rule. If you see it multiple times here, it's more likely it's related to the way you use OkHttp. So check you are properly closing OkHttp calls, reusing a client, and avoiding an unbounded number of concurrent execute calls.  But not a bug for us.

**Comment by cathychi** [comment]
Could I ask what it means to properly close OkHttp calls? Does that just mean closing every connection we open? Would cancel() be enough or do we need to call close(1000, null)?

**Comment by swankjesse** [comment]
@cathychi yes, you need to **close** every Response and WebSocket you create. Note that `cancel()` is not `close()` and does not free resources.
