### ISSUE TITLE
AssertionError: Method getAlpnSelectedProtocol not supported for object SSL socket over Socket on Android 11

### ISSUE THREAD

**Issue by mikezliu** [square/okhttp#6701]
I'm getting the crash below on some Android devices (i.e. Android 11, MI 9 SE)

OkHttp version: 4.9.1 (this seems to use io.grpc:grpc-okhttp:1.28.0)
targetSdkVersion 30

This issue seems to be fixed on grpc 1.32.2: https://github.com/grpc/grpc-java/issues/7519

Is it safe to use grpc v1.32.2 with OkHttp 4.9.1?

Fatal Exception: java.lang.AssertionError: Method getAlpnSelectedProtocol not supported for object SSL socket over Socket[address=firestore.googleapis.com/172.217.167.74,port=443,localPort=47098]
       at io.grpc.okhttp.internal.OptionalMethod.invoke(OptionalMethod.java:114)
       at io.grpc.okhttp.internal.OptionalMethod.invokeWithoutCheckedException(OptionalMethod.java:135)
       at io.grpc.okhttp.OkHttpProtocolNegotiator$AndroidNegotiator.getSelectedProtocol(OkHttpProtocolNegotiator.java:183)
       at io.grpc.okhttp.OkHttpProtocolNegotiator$AndroidNegotiator.negotiate(OkHttpProtocolNegotiator.java:145)
       at io.grpc.okhttp.OkHttpTlsUpgrader.upgrade(OkHttpTlsUpgrader.java:63)
       at io.grpc.okhttp.OkHttpClientTransport$4.run(OkHttpClientTransport.java:571)
       at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:123)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)

**Comment by yschimke** [comment]
That is a fork of the code, so nothing specifically to do here for square/okhttp.
