### ISSUE TITLE
OkHttp Graal builds fail with Kotlin 1.5.10

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6715]
https://github.com/square/okhttp/runs/2816094342?check_suite_focus=true

```
[ConsoleLauncher:1931]   (features):   2,117.94 ms,  2.82 GB
Error: Unsupported features in 5 methods
[ConsoleLauncher:1931]     analysis:  97,213.36 ms,  2.82 GB
Detailed message:
Error: unbalanced monitors: mismatch at monitorexit, 106|LoadField#this$0 != 162|LoadField#this$0
Call path from entry point to okhttp3.internal.http2.Http2Connection$pushHeadersLater$$inlined$execute$default$1.runOnce(): 
	at okhttp3.internal.http2.Http2Connection$pushHeadersLater$$inlined$execute$default$1.runOnce(TaskQueue.kt:98)
	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
	at java.lang.Thread.run(Thread.java:829)
	at com.oracle.svm.core.thread.JavaThreads.threadStartRoutine(JavaThreads.java:553)
	at com.oracle.svm.core.posix.thread.PosixJavaThreads.pthreadStartRoutine(PosixJavaThreads.java:192)
	at com.oracle.svm.core.code.IsolateEnterStub.PosixJavaThreads_pthreadStartRoutine_e1f4a8c0039f8337338252cd8734f63a79b5e3df(generated:0)
Original exception that caused the problem: org.graalvm.compiler.code.SourceStackTraceBailoutException$1: unbalanced monitors: mismatch at monitorexit, 106|LoadField#this$0 != 162|LoadField#this$0
	at okhttp3.internal.http2.Http2Connection$pushHeadersLater$$inlined$execute$default$1.runOnce(TaskQueue.kt:225)
Caused by: org.graalvm.compiler.core.common.PermanentBailoutException: unbalanced monitors: mismatch at monitorexit, 106|LoadField#this$0 != 162|LoadField#this$0
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.bailout(BytecodeParser.java:3974)
	at jdk.internal.vm.compiler/org.graalvm.compiler.java.BytecodeParser.genMonitorExit(BytecodeParser.java:2842)
```

**Comment by yschimke** [comment]
Reported here oracle/graal#3466
