### ISSUE TITLE
StringIndexOutOfBoundsException at okhttp3.JavaNetCookieJar.decodeHeaderAsJavaNetCookies(JavaNetCookieJar.kt:98)

### ISSUE THREAD

**Issue by ValleZ** [square/okhttp#6721]
I see exceptions in cookie parser. Most likely the cookies are invalid but it's better to handle it w/o throwing errors:

Invalid cookie for https://www1.shoppersdrugmart.ca/en/health-and-pharmacy: Shoppers Drug Mart_Language=en-ca; expires=Tue, 20 Jul 2021 18:57:18 GMT; path=/; secure
java.lang.StringIndexOutOfBoundsException: begin 1, end 0, length 1
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at okhttp3.JavaNetCookieJar.decodeHeaderAsJavaNetCookies(JavaNetCookieJar.kt:98)
        at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.kt:59)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:74)

SEVERE: Invalid cookie for https://www.bankofbaroda.in/contact-us.htm: ClassBank Of Baroda CMSs=; path=/; secure; httponly
java.lang.StringIndexOutOfBoundsException: begin 1, end 0, length 1
        at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
        at java.base/java.lang.String.substring(String.java:1874)
        at okhttp3.JavaNetCookieJar.decodeHeaderAsJavaNetCookies(JavaNetCookieJar.kt:98)

Okhttp gradle dependencies:
    implementation("com.squareup.okhttp3:okhttp:4.9.1")
    implementation("com.squareup.okhttp3:okhttp-dnsoverhttps:5.0.0-alpha.2")
    implementation("com.squareup.okhttp3:okhttp-urlconnection:4.9.1")

**Comment by swankjesse** [comment]
Can fix.

**Comment by yschimke** [comment]
@swankjesse you happy with passing through ", I think we pass through a bunch of hot messes, so this is no different.  But we could drop, and if so should we drop other bad examples?
