### ISSUE TITLE
 Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V

### ISSUE THREAD

**Issue by sanju1989** [square/okhttp#6722]
I am getting this strict mode policy violation.

**Comment by yschimke** [comment]
Can you provide a stacktrace. Are you calling execute on the Android main thread?

**Comment by sanju1989** [comment]
StrictMode policy violation: android.os.strictmode.NonSdkApiUsedViolation: Lcom/android/org/conscrypt/ConscryptEngineSocket;->setHostname(Ljava/lang/String;)V
	at android.os.StrictMode.lambda$static$1(StrictMode.java:416)
	at android.os.-$$Lambda$StrictMode$lu9ekkHJ2HMz0jd3F8K8MnhenxQ.accept(Unknown Source:2)
	at java.lang.Class.getDeclaredMethodInternal(Native Method)
	at java.lang.Class.getPublicMethodRecursive(Class.java:2079)
	at java.lang.Class.getMethod(Class.java:2066)
	at java.lang.Class.getMethod(Class.java:1693)
	at m.k0.k.e.a(:1)
	at m.k0.k.e.c(:1)
	at m.k0.k.a.f(Unknown Source:21)
	at m.k0.f.c.f(:19)
	at m.k0.f.c.c(:12)
	at m.k0.f.g.d(:45)
	at m.k0.f.g.e(Unknown Source:0)
	at m.k0.f.a.a(:11)
	at m.k0.g.f.b(:2)
	at m.k0.e.b.a(:107)
	at m.k0.g.f.b(:2)
	at m.k0.g.a.a(:27)
	at m.k0.g.f.b(:2)
	at m.k0.g.h.a(:7)
	at m.k0.g.f.b(:2)
	at m.k0.g.f.a(Unknown Source:6)
	at m.z.b(:12)
	at m.z$b.a(Unknown Source:9)
	at m.k0.b.run(Unknown Source:17)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)


I got this problem in Android Pre-launch report.

**Comment by yschimke** [comment]
This shouldn't be happening with OkHttp 3.12.13 or 4.9.1.  Which version are you using?

**Comment by sanju1989** [comment]
Yes thanks... i was using the old OkHttp version. Now i have changed this with 4.9.1.    Really thanks:)
