### ISSUE TITLE
java.lang.NullPointerException okio.Buffer.write

### ISSUE THREAD

**Issue by IvanShafran** [square/okhttp#6723]
Hello!

Sorry, I can't reproduce this bug, but I may provide some clues to start with.

So let's start with the usage. I'm using WebSocket from okhttp3:4.9.1 like this:

```Java
OkHttpClient myHttp = new OkHttpClient();
Request request = new Request.Builder().url(endpoint).build();
socket = myHttp.newWebSocket(request, new WebSocketListener() {
    @Override public void onOpen(WebSocket webSocket, Response response) {
        ...
    }
    ...
});
```

The socket field is guarded by the lock and set to null on close/failure. But it may pass send calls during socket opening. So as mentioned in docs, it is totally fine. Also, if the socket fails, we create a new one.

So recently, I got this rare exception that I can't reproduce:
```
Fatal Exception: java.lang.NullPointerException
       at okio.Buffer.write(Buffer.kt:1815)
       at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
       at okio.DeflaterSink.deflate(DeflaterSink.kt:97)
       at okio.DeflaterSink.write(DeflaterSink.kt:64)
       at okhttp3.internal.ws.MessageDeflater.deflate(MessageDeflater.kt:45)
       at okhttp3.internal.ws.WebSocketWriter.writeMessageFrame(WebSocketWriter.kt:155)
       at okhttp3.internal.ws.RealWebSocket.writeOneFrame$okhttp(RealWebSocket.kt:527)
       at okhttp3.internal.ws.RealWebSocket$WriterTask.runOnce(RealWebSocket.kt:620)
       at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
       at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
       at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

I checked other threads in the Crashlytics report, and the OkHttp thread bounded to my socket has this:
```
Thread name: OkHttp "my endpoint name"

OkHttp "my endpoint address"...
       at java.util.zip.Deflater.deflateBytes(Deflater.java)
       at java.util.zip.Deflater.deflate(Deflater.java:462)
       at java.util.zip.Deflater.deflate(Deflater.java:384)
       at okio.DeflaterSink.deflate(DeflaterSink.kt:91)
       at okio.DeflaterSink.finishDeflate$okio(DeflaterSink.kt:117)
       at okio.DeflaterSink.close(DeflaterSink.kt:128)
       at okhttp3.internal.ws.MessageDeflater.close(MessageDeflater.kt:62)
       at okhttp3.internal.ws.WebSocketWriter.close(WebSocketWriter.kt:199)
       at okhttp3.internal.Util.closeQuietly(Util.kt:488)
       at okhttp3.internal.ws.RealWebSocket.failWebSocket(RealWebSocket.kt:596)
       at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:197)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

Another useful thread:
```
Thread name: OkHttp "my endpoint address" writer

OkHttp "my endpoint address" writer
       at java.util.zip.Deflater.needsInput(Deflater.java:339)
       at okio.DeflaterSink.deflate(DeflaterSink.kt:98)
       at okio.DeflaterSink.write(DeflaterSink.kt:64)
       at okhttp3.internal.ws.MessageDeflater.deflate(MessageDeflater.kt:45)
       at okhttp3.internal.ws.WebSocketWriter.writeMessageFrame(WebSocketWriter.kt:155)
       at okhttp3.internal.ws.RealWebSocket.writeOneFrame$okhttp(RealWebSocket.kt:527)
       at okhttp3.internal.ws.RealWebSocket$WriterTask.runOnce(RealWebSocket.kt:620)
       at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
       at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
       at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

The suspicious part is `failWebSocket` in the second trace. But it has paired writer thread. I'm a bit baffled by this. Probably stack trace is from the previous instance of WebSocket, and fail happened during the shutdown. I can't say. Another version is  NPE was caused by concurrency issues during failWebSocket. I see that most part of the RealWebSocket is covered with `synchronized`. Therefore it is a weak theory.

I'd appreciate any help! Thank you!

**Comment by swankjesse** [comment]
Tricky bug report. One possible cause is a corrupt Okio Buffer caused by thread-unsafe access somewhere. That could cause that first NullPointerException

**Comment by yschimke** [comment]
@swankjesse I've raised https://github.com/square/okhttp/issues/6725 to think about how we can provide some assistance for devs tracking down these issues. But it's not related to this specific issue.

**Comment by swankjesse** [comment]
No clear action to take here. I like @yschimke ’s recommendation to add better detection.
