### ISSUE TITLE
Unable to build native image for cli application (missing Android dependencies)

### ISSUE THREAD

**Issue by ragunathjawahar** [square/okhttp#6825]
**Compile time exception**
```
Error: Unsupported features in 4 methods
Detailed message:
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: android.os.Build$VERSION. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing okhttp3.internal.platform.AndroidPlatform.getSdkInt(AndroidPlatform.java:432)
Call path from entry point to okhttp3.internal.platform.AndroidPlatform.getSdkInt(): 
        no path found from entry point to target method

Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: android.os.Build$VERSION. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing retrofit2.Platform$Android.<init>(Platform.java:114)
Call path from entry point to retrofit2.Platform$Android.<init>(): 
        no path found from entry point to target method

Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: android.os.Handler. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing retrofit2.Platform$Android$MainThreadExecutor.<init>(Platform.java:134)
Call path from entry point to retrofit2.Platform$Android$MainThreadExecutor.<init>(): 
        at retrofit2.Platform$Android$MainThreadExecutor.<init>(Platform.java:133)
        at retrofit2.Platform$Android.defaultCallbackExecutor(Platform.java:119)
        at retrofit2.Retrofit$Builder.build(Retrofit.java:633)
        at [REDACTED](ApiClient.kt:17)
        at [REDACTED](SomeCommand.kt:79)
        at [REDACTED].SomeCommand.run(SomeCommand.kt:43)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeHooks(RuntimeSupport.java:125)
        at com.oracle.svm.core.jdk.RuntimeSupport.executeStartupHooks(RuntimeSupport.java:75)
        at com.oracle.svm.core.JavaMainWrapper.runCore(JavaMainWrapper.java:137)
        at com.oracle.svm.core.JavaMainWrapper.run(JavaMainWrapper.java:182)
        at com.oracle.svm.core.code.IsolateEnterStub.JavaMainWrapper_run_5087f5482cc9a6abc971913ece43acb471d2631b(generated:0)
Error: com.oracle.graal.pointsto.constraints.UnresolvedElementException: Discovered unresolved type during parsing: android.os.Handler. To diagnose the issue you can use the --allow-incomplete-classpath option. The missing type is then reported at run time when it is accessed the first time.
Trace: 
        at parsing retrofit2.Platform$Android$MainThreadExecutor.execute(Platform.java:138)
Call path from entry point to retrofit2.Platform$Android$MainThreadExecutor.execute(Runnable): 
        at retrofit2.Platform$Android$MainThreadExecutor.execute(Platform.java:138)
        at java.lang.ProcessHandleImpl.completion(ProcessHandleImpl.java:135)
        at java.lang.ProcessImpl.initStreams(ProcessImpl.java:389)
        at java.lang.ProcessImpl.lambda$new$0(ProcessImpl.java:352)
        at java.lang.ProcessImpl$$Lambda$245/0x00000007c0d0bc40.run(Unknown Source)
        at com.oracle.svm.core.jdk.Target_java_security_AccessController.doPrivileged(SecuritySubstitutions.java:118)
        at java.util.ServiceLoader.loadProvider(ServiceLoader.java:859)
        at java.util.ServiceLoader$LayerLookupIterator.hasNext(ServiceLoader.java:952)
        at java.util.AbstractSet.hashCode(AbstractSet.java:121)
        at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:936)
        at java.util.Properties.getProperty(Properties.java:1128)
        at com.oracle.svm.core.jdk.SystemPropertiesSupport.getProperty(SystemPropertiesSupport.java:170)
        at com.oracle.svm.core.jdk.Target_java_lang_System.getProperty(JavaLangSubstitutions.java:291)
        at com.oracle.svm.jni.JNIJavaCallWrappers.jniInvoke_VA_LIST:Ljava_lang_System_2_0002egetProperty_00028Ljava_lang_String_2_00029Ljava_lang_String_2(generated:0)

Error: Use -H:+ReportExceptionStackTraces to print stacktrace of underlying exception
Error: Image build request failed with exit status 1
com.oracle.svm.driver.NativeImage$NativeImageError: Image build request failed with exit status 1
        at com.oracle.svm.driver.NativeImage.showError(NativeImage.java:1772)
        at com.oracle.svm.driver.NativeImage.build(NativeImage.java:1519)
        at com.oracle.svm.driver.NativeImage.performBuild(NativeImage.java:1480)
        at com.oracle.svm.driver.NativeImage.main(NativeImage.java:1467)
        at com.oracle.svm.driver.NativeImage$JDK9Plus.main(NativeImage.java:1959)
```
All the errors point to the Android platform.

I managed to build an image using the `--allow-incomplete-classpath` flag and the image fails during runtime with the following exception.

**Runtime exception**
```
Exception in thread "main" java.lang.ExceptionInInitializerError
        at com.oracle.svm.core.classinitialization.ClassInitializationInfo.initialize(ClassInitializationInfo.java:315)
        at okhttp3.HttpUrl$Builder.parse(HttpUrl.java:1313)
        at okhttp3.HttpUrl.get(HttpUrl.java:917)
        at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:506)
```

**Comment by yschimke** [comment]
This is fixed in OkHttp 5 when it's released.  Until then you can follow this approach

https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/internal/graal/svm.kt

```
@TargetClass(AndroidPlatform::class)
@Delete
class TargetAndroidPlatform {
}

...

@TargetClass(Platform.Companion::class)
class TargetPlatform {
  @Substitute
  fun findPlatform(): Platform {
    return Jdk9Platform.buildIfSupported()!!
  }
}
```

You will need this dependency also org.graalvm.nativeimage:svm:21.2.0

**Comment by yschimke** [comment]
Reopen if you have further issues, and if you hit some blocker we can look at a patch release.  It does work, I've blocked numerous CLI apps with nativeImage, for example https://github.com/cashapp/certifikit/blob/master/certifikit-cli/build.gradle
