### ISSUE TITLE
Platform.java okhttp3.internal.platform.Platform.platformTrustManager

### ISSUE THREAD

**Issue by tuandao2511** [square/okhttp#6867]
Hello!

Sorry, I can't reproduce this bug, I’ve got issue on  Firebase Crashlytic. The issue had appeared on android 5, device SHAPE. 

I have use some libs:

- com.squareup.okhttp3:okhttp:4.3.0
- com.squareup.okhttp3:logging-interceptor:4.3.0

So let's start with the usage:
```
fun provideOkhttpClient(application: Application, cache: Cache): OkHttpClient {
    val httpLoggingInterceptor = HttpLoggingInterceptor()
    httpLoggingInterceptor.level = HttpLoggingInterceptor.Level.BODY
    return OkHttpClient.Builder()
        .cache(cache)
        .callTimeout(1, TimeUnit.MINUTES)
        .connectTimeout(1, TimeUnit.MINUTES)
        .addInterceptor(httpLoggingInterceptor)
        .addInterceptor(
            ChuckInterceptor(application)
                .showNotification(true)
        )
        .build()
}
```
I got this rare exception that I can't reproduce:

Caused by java.lang.NoSuchMethodException
[]
Caused by java.lang.NoSuchMethodException: []
at java.lang.Class.getConstructor(Class.java:531)
at java.lang.Class.getDeclaredConstructor(Class.java:510)
at java.lang.Class.newInstance(Class.java:1561)
at java.security.Provider$Service.newInstanceNoParameter(Provider.java:1123)
at java.security.Provider$Service.newInstance(Provider.java:1092)
at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:141)
at javax.net.ssl.TrustManagerFactory.getInstance(TrustManagerFactory.java:76)
at okhttp3.internal.platform.Platform.platformTrustManager(Platform.java)
at okhttp3.OkHttpClient.(OkHttpClient.java)
at okhttp3.OkHttpClient$Builder.build(OkHttpClient.java)

….
Caused by java.lang.InstantiationException
class com.android.org.conscrypt.TrustManagerFactoryImpl has no zero argument constructor
Caused by java.lang.NoSuchMethodException: []
at java.lang.Class.getConstructor(Class.java:531)
at java.lang.Class.getDeclaredConstructor(Class.java:510)
at java.lang.Class.newInstance(Class.java:1561)
at java.security.Provider$Service.newInstanceNoParameter(Provider.java:1123)
at java.security.Provider$Service.newInstance(Provider.java:1092)
at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:141)
at javax.net.ssl.TrustManagerFactory.getInstance(TrustManagerFactory.java:76)
at okhttp3.internal.platform.Platform.platformTrustManager(Platform.java)
….
Caused by java.security.NoSuchAlgorithmException
TrustManagerFactory PKIX implementation not found
Caused by java.security.NoSuchAlgorithmException: TrustManagerFactory PKIX implementation not found
at java.security.Provider$Service.newInstanceNoParameter(Provider.java:1125)
at java.security.Provider$Service.newInstance(Provider.java:1092)
at org.apache.harmony.security.fortress.Engine.getInstance(Engine.java:141)
at javax.net.ssl.TrustManagerFactory.getInstance(TrustManagerFactory.java:76)
at okhttp3.internal.platform.Platform.platformTrustManager(Platform.java)
…
Fatal Exception: java.lang.RuntimeException
Unable to create application xxxx : java.security.NoSuchAlgorithmException: TrustManagerFactory PKIX implementation not found
Fatal Exception: java.lang.RuntimeException: Unable to create application xxxx: java.security.NoSuchAlgorithmException: TrustManagerFactory PKIX implementation not found
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4738)
at android.app.ActivityThread.access$1700(ActivityThread.java:161)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1432)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5438)
at java.lang.reflect.Method.invoke(Method.java)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:917)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:712)

The app is always interrupted okhttp3.internal.platform.Platform.platformTrustManager. Currently, the issue have appeared in other devices (only see android 5, SHAPE device).
I'd appreciate any help! Thank you!

**Comment by yschimke** [comment]
This is an Android bug (com.android.org.conscrypt.TrustManagerFactoryImpl), not okhttp.  Sorry, we can't provide any insight into why it's happening.
