### ISSUE TITLE
Runtime exception running a Kotlin script (*.kts)

### ISSUE THREAD

**Issue by loxal** [square/okhttp#6872]
```
java.lang.NoClassDefFoundError: okio/Buffer
	at okhttp3.ResponseBody$Companion.create(ResponseBody.kt:248)
	at okhttp3.ResponseBody$Companion.create$default(ResponseBody.kt:247)
	at okhttp3.internal.Util.<clinit>(Util.kt:69)
	at okhttp3.internal.concurrent.TaskRunner.<clinit>(TaskRunner.kt:313)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:41)
	at okhttp3.ConnectionPool.<init>(ConnectionPool.kt:47)
	at okhttp3.OkHttpClient$Builder.<init>(OkHttpClient.kt:481)
	at Request_main$load$1.invokeSuspend(request.main.kts:165)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoop.common.kt:277)
	at kotlinx.coroutines.BlockingCoroutine.joinBlocking(Builders.kt:87)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(Builders.kt:61)
	at kotlinx.coroutines.BuildersKt.runBlocking(Unknown Source)
	at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(Builders.kt:40)
	at kotlinx.coroutines.BuildersKt.runBlocking$default(Unknown Source)
	at Request_main.load(request.main.kts:163)
	at Request_main.<init>(request.main.kts:162)
Caused by: java.lang.ClassNotFoundException: okio.Buffer
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:440)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
```

...is thrown by a *.kts script running Liberica JDK 8 that...

`@file:DependsOn("/home/alex/my/project/okhttp/okhttp/build/libs/okhttp-5.0.0-SNAPSHOT.jar")`

...references a locally build JAR using Liberica JDK 8 that imports...

```
import okhttp3.OkHttpClient
import okhttp3.Request
```

Everything works fine when using `@file:DependsOn("com.squareup.okhttp3:okhttp:5.0.0-alpha.2")` instead.

**Comment by yschimke** [comment]
The jar won't have the dependencies pulled in transitively.  While the second uses maven repo artifacts that can get transitive dependencies from a pom file.

**Comment by loxal** [comment]
@yschimke Adding `@file:DependsOn("com.squareup.okio:okio:2.10.0")` resolved this issue for me.
