### ISSUE TITLE
IllegalStateException when reading data from a connection closed by another thread

### ISSUE THREAD

**Issue by robUx4** [square/okhttp#689]
The log shows my REST reader getting an IllegalStateException when trying to read from an HTTP connection that has been closed (not by me). I think it should throw an IOException instead. This is with the okhttp 2.0 master branch.

``````
java.lang.IllegalStateException: closed
       at okio.RealBufferedSink.flush(SourceFile:152)
       at com.squareup.okhttp.internal.http.HttpEngine.readResponse(SourceFile:570)
       at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.execute(SourceFile:384)
       at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.getResponse(SourceFile:331)
       at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.getHeaderFields(SourceFile:178)
       at com.squareup.okhttp.internal.http.DelegatingHttpsURLConnection.getHeaderFields(SourceFile:178)
       at com.squareup.okhttp.internal.http.HttpsURLConnectionImpl.getHeaderFields(SourceFile:1)
       at com.levelup.touiteur.DBCookieMaster.setCookieResponse(SourceFile:460)
       at com.levelup.http.AbstractHttpRequest.setResponse(SourceFile:159)
       at com.levelup.http.twitter.HttpTwitterPost.setResponse(SourceFile:66)
       at com.levelup.http.HttpClient.getQueryResponse(SourceFile:165)
       at com.levelup.http.HttpClient.getInputStream(SourceFile:187)
       at com.levelup.http.HttpClient.parseRequest(SourceFile:274)
       at com.levelup.http.HttpClient.getStringResponse(SourceFile:312)
       at com.levelup.http.twitter.TwitterOAuth.getRequestTokener(SourceFile:165)
       at com.levelup.http.twitter.TwitterOAuth.queryJSONObject(SourceFile:72)
       at com.levelup.http.twitter.TwitterOAuth.queryJSONObjectOnly(SourceFile:68)
       at com.plume.twitter.TwitterClient.queryJSONObjectOnly(SourceFile:641)
       at com.plume.twitter.TwitterClient$ProfileUpdateBuilder.updateProfile(SourceFile:1070)
       at com.levelup.touiteur.ProfileTwitter$2$1.execute(SourceFile:554)
       at com.levelup.touiteur.ActivityTouiteur$BusyWorkingThread.run(SourceFile:595)```
``````

**Comment by Elshad** [comment]
Hello,
OkHttp 2.2.0

When i use 
```
System.out.println(response.body().string());
String ceyson = response.body().string();
```
there is exception like this 
```
W/System.err﹕ java.lang.IllegalStateException: closed
W/System.err﹕ at com.squareup.okhttp.internal.http.HttpConnection$FixedLengthSource.read(HttpConnection.java:405)
W/System.err﹕ at okio.Buffer.writeAll(Buffer.java:705)
W/System.err﹕ at okio.RealBufferedSource.readByteArray(RealBufferedSource.java:92)
W/System.err﹕ at com.squareup.okhttp.ResponseBody.bytes(ResponseBody.java:57)
W/System.err﹕ at com.squareup.okhttp.ResponseBody.string(ResponseBody.java:83)
```
But when i use only `String ceyson = response.body().string();` it is ok

**Comment by antonj** [comment]
Same here for `com.squareup.okhttp:okhttp:2.2.0`, reading the body twice with `bytes()` throws this exception.

**Comment by swankjesse** [comment]
We aren't going to cache the bytes. That could waste a serious amount of memory. If you need to read the response body multiple times, you need to do your own buffering.

**Comment by antonj** [comment]
That's what I did. It might be good to add to documentation though that you cannot read the body twice. Took me some time to figure out.

**Comment by swankjesse** [comment]
@antonj which documentation did you read before you ran into the problem?

**Comment by antonj** [comment]
@swankjesse I looked for documentation in `ResponseBody` and the `string()` and `bytes()` methods. My use case for reading twice was that I was passing around a `Response` instance through some RxJava flatMap functions to do some extra checks for a specific API.

Thanks for a great lib btw.

**Comment by ryandt** [comment]
@antonj @swankjesse Could you explain the buffering you are suggesting to read ```response.body().string()```? I'm essentially looking to read it for logging purposes in an ```Interceptor``` before passing the ```Response``` object on for GSON to map the JSON to my models.

**Comment by mkrcpp** [comment]
```
 //return String or null
    public static void doGetRequest(String url, final File destFile, final GSResponseListener responseListener) {
        getInstance().getOkHttpClient().newCall(new Request.Builder().url(url).get().build()).enqueue(new Callback() {
            @Override
            public void onFailure(Request request, IOException e) {
                if (responseListener != null)
                    responseListener.process(null);
            }

            @Override
            public void onResponse(final Response response) throws IOException {
                if (response != null && response.isSuccessful()) {
                    String content = response.body().string();
                    if (destFile != null)
                        writeTextToFile(content, destFile);
                    if (responseListener != null)
                        responseListener.process(content);
                } else if (responseListener != null)
                    responseListener.process(null);
            }
        });
    }

    //return String or null
    public static void doGetRequest(String url, final GSResponseListener responseListener) {
        doGetRequest(url, null, responseListener);
    }

    public static final String ENCODING_UTF8 = "UTF-8";

    public static boolean writeTextToFile(String content, File file) {
        return writeTextToFile(content, null, file);
    }

    public static boolean writeTextToFile(String content, Throwable throwable, File file) {
        boolean isAppendSuccess = false;
        try {
            OutputStreamWriter outputStreamWriter = new OutputStreamWriter(new FileOutputStream(file, false), ENCODING_UTF8);
            PrintWriter printWriter = new PrintWriter(outputStreamWriter, true);
            printWriter.print(content);
            if (throwable != null)
                throwable.printStackTrace(printWriter);
            printWriter.flush();
            printWriter.close();
            isAppendSuccess = true;
        } catch (Exception e) {
            e.printStackTrace();
        }
        return isAppendSuccess;
    }
```

**Comment by tony1213** [comment]
I have an issue on this.Cannot read the body twice.

**Comment by JacobCooley** [comment]
I'm getting this error from Crashlytics on Android and I have no idea how to solve it.  Not much information.  I think the only dependency I am using that uses okhttp is picasso
