### ISSUE TITLE
OCSP response does not include a response for a certificate supplied in the OCSP request🙉

### ISSUE THREAD

**Issue by yahooyee** [square/okhttp#6930]
Caused by: java.security.cert.CertificateException: Chain validation failed
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:721)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:551)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:572)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:640)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:507)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:426)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:354)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:89)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:224)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.verifyCertificateChain(ConscryptFileDescriptorSocket.java:407)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at com.android.org.conscrypt.NativeSsl.doHandshake(NativeSsl.java:387)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:226)
2021-11-25 18:50:42.091 5841-5841/? W/System.err: 	... 50 more
2021-11-25 18:50:42.091 5841-5841/? W/System.err: Caused by: java.security.cert.CertPathValidatorException: OCSP response does not include a response for a certificate supplied in the OCSP request
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at java.security.cert.CertPathValidator.validate(CertPathValidator.java:301)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:717)
2021-11-25 18:50:42.091 5841-5841/? W/System.err: 	... 63 more
2021-11-25 18:50:42.091 5841-5841/? W/System.err: Caused by: java.security.cert.CertPathValidatorException: OCSP response does not include a response for a certificate supplied in the OCSP request
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:416)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:709)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:363)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:337)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
2021-11-25 18:50:42.091 5841-5841/? W/System.err: 	... 68 more
2021-11-25 18:50:42.091 5841-5841/? W/System.err: 	Suppressed: java.security.cert.CertPathValidatorException: Could not determine revocation status
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at sun.security.provider.certpath.RevocationChecker.buildToNewKey(RevocationChecker.java:1092)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at sun.security.provider.certpath.RevocationChecker.verifyWithSeparateSigningKey(RevocationChecker.java:910)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:577)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at sun.security.provider.certpath.RevocationChecker.checkCRLs(RevocationChecker.java:465)
2021-11-25 18:50:42.091 5841-5841/? W/System.err:     at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:394)
2021-11-25 18:50:42.091 5841-5841/? W/System.err: 		... 70 more

**Comment by yschimke** [comment]
com.android.org.conscrypt is an AOSP project, not something we can help with here.
