### ISSUE TITLE
EventListener responseBodyEnd not called on interceptor changed responses

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#6992]
```
  @Test public void requestBodySuccessWithDecompression() throws IOException {
    client = client.newBuilder().addInterceptor(chain ->
      chain.proceed(chain.request()).newBuilder().body(ResponseBody.create("UNCOMPRESSED", null)).build()).build();

    server.enqueue(new MockResponse()
      .setResponseCode(200)
      .setBody("COMPRESSED"));

    Call call = client.newCall(new Request.Builder()
      .url(server.url("/"))
      .build());
    Response response = call.execute();
    ResponseBody body = response.body();
    assertThat(body.string()).isEqualTo("COMPRESSED");

    ResponseBodyEnd responseBodyEnd = listener.removeUpToEvent(ResponseBodyEnd.class);
    MatcherAssert.assertThat("response body bytes", responseBodyEnd.getBytesRead(), equalTo((long) "UNCOMPRESSED".length()));
  }
```

```

full event sequence: [CallStart(timestampNs=2514641748646, call=okhttp3.internal.connection.RealCall@25243bc1), ProxySelectStart(timestampNs=2514700063900, call=okhttp3.internal.connection.RealCall@25243bc1, url=http://localhost:55852/), ProxySelectEnd(timestampNs=2514700947638, call=okhttp3.internal.connection.RealCall@25243bc1, url=http://localhost:55852/, proxies=[DIRECT]), DnsStart(timestampNs=2514701299959, call=okhttp3.internal.connection.RealCall@25243bc1, domainName=localhost), DnsEnd(timestampNs=2514701711478, call=okhttp3.internal.connection.RealCall@25243bc1, domainName=localhost, inetAddressList=[localhost/127.0.0.1]), ConnectStart(timestampNs=2514711734997, call=okhttp3.internal.connection.RealCall@25243bc1, inetSocketAddress=localhost/127.0.0.1:55852, proxy=DIRECT), ConnectEnd(timestampNs=2514721726227, call=okhttp3.internal.connection.RealCall@25243bc1, inetSocketAddress=localhost/127.0.0.1:55852, proxy=DIRECT, protocol=http/1.1), ConnectionAcquired(timestampNs=2514723554366, call=okhttp3.internal.connection.RealCall@25243bc1, connection=Connection{localhost:55852, proxy=DIRECT hostAddress=localhost/127.0.0.1:55852 cipherSuite=none protocol=http/1.1}), RequestHeadersStart(timestampNs=2514726513044, call=okhttp3.internal.connection.RealCall@25243bc1), RequestHeadersEnd(timestampNs=2514727400790, call=okhttp3.internal.connection.RealCall@25243bc1, headerLength=105), ResponseHeadersStart(timestampNs=2514735397953, call=okhttp3.internal.connection.RealCall@25243bc1), ResponseHeadersEnd(timestampNs=2514736050334, call=okhttp3.internal.connection.RealCall@25243bc1, headerLength=20)]
java.lang.AssertionError: full event sequence: [CallStart(timestampNs=2514641748646, call=okhttp3.internal.connection.RealCall@25243bc1), ProxySelectStart(timestampNs=2514700063900, call=okhttp3.internal.connection.RealCall@25243bc1, url=http://localhost:55852/), ProxySelectEnd(timestampNs=2514700947638, call=okhttp3.internal.connection.RealCall@25243bc1, url=http://localhost:55852/, proxies=[DIRECT]), DnsStart(timestampNs=2514701299959, call=okhttp3.internal.connection.RealCall@25243bc1, domainName=localhost), DnsEnd(timestampNs=2514701711478, call=okhttp3.internal.connection.RealCall@25243bc1, domainName=localhost, inetAddressList=[localhost/127.0.0.1]), ConnectStart(timestampNs=2514711734997, call=okhttp3.internal.connection.RealCall@25243bc1, inetSocketAddress=localhost/127.0.0.1:55852, proxy=DIRECT), ConnectEnd(timestampNs=2514721726227, call=okhttp3.internal.connection.RealCall@25243bc1, inetSocketAddress=localhost/127.0.0.1:55852, proxy=DIRECT, protocol=http/1.1), ConnectionAcquired(timestampNs=2514723554366, call=okhttp3.internal.connection.RealCall@25243bc1, connection=Connection{localhost:55852, proxy=DIRECT hostAddress=localhost/127.0.0.1:55852 cipherSuite=none protocol=http/1.1}), RequestHeadersStart(timestampNs=2514726513044, call=okhttp3.internal.connection.RealCall@25243bc1), RequestHeadersEnd(timestampNs=2514727400790, call=okhttp3.internal.connection.RealCall@25243bc1, headerLength=105), ResponseHeadersStart(timestampNs=2514735397953, call=okhttp3.internal.connection.RealCall@25243bc1), ResponseHeadersEnd(timestampNs=2514736050334, call=okhttp3.internal.connection.RealCall@25243bc1, headerLength=20)]
	at okhttp3.RecordingEventListener.removeUpToEvent(RecordingEventListener.kt:85)
	at okhttp3.EventListenerTest.requestBodySuccessWithDecompression(EventListenerTest.java:1596)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
```

**Comment by yschimke** [comment]
It's only a bug if the actual response is ignored.
