### ISSUE TITLE
Caused by: java.lang.NoSuchMethodError: okhttp3.ResponseBody.source()Lokio/BufferedSource;

### ISSUE THREAD

**Issue by houguanglin** [square/okhttp#7011]
i used  okhttp to connection influxdb, get an error:

Caused by: java.lang.NoSuchMethodError: okhttp3.ResponseBody.source()Lokio/BufferedSource;
	at retrofit2.OkHttpCall$ExceptionCatchingResponseBody.<init>(OkHttpCall.java:285) ~[retrofit-2.6.2.jar:?]
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:223) ~[retrofit-2.6.2.jar:?]
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:188) ~[retrofit-2.6.2.jar:?]
	at org.influxdb.impl.InfluxDBImpl.execute(InfluxDBImpl.java:829) ~[influxdb-java-2.21.jar:?]
	at org.influxdb.impl.InfluxDBImpl.executeQuery(InfluxDBImpl.java:824) ~[influxdb-java-2.21.jar:?]
	at org.influxdb.impl.InfluxDBImpl.query(InfluxDBImpl.java:559) ~[influxdb-java-2.21.jar:?]

the version is:
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.9.1</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>logging-interceptor</artifactId>
            <version>4.9.1</version>
        </dependency>
        <dependency>
          <groupId>com.squareup.okio</groupId>
          <artifactId>okio</artifactId>
          <version>2.8.0</version>
          <scope>compile</scope>
        </dependency>

**Comment by houguanglin** [comment]
问题解决了，发现是有一个jar包中包含了okhttp的全部代码，但是并不是以jar包的方式引入的，而是直接拷贝，排除那个包之后就好了

**Comment by houguanglin** [comment]
ok
