### ISSUE TITLE
exception in android 12

### ISSUE THREAD

**Issue by arsalanNasiri** [square/okhttp#7034]
For me, when using the method (chain.proceed (request)), there is a problem which is the following error.

My error happens in Android 12

I use retrofit

`class CustomInterceptor implements Interceptor {
    @NonNull
    @Override
    public Response intercept(Chain chain) throws IOException {
        Request request = chain.request ();
        return chain.proceed (request);
    }
}`

`Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.`

**Comment by yschimke** [comment]
Neither Retrofit or OkHttp are relevant for the error with Intent Mutability. I suggest you search and ask on Stackoverflow.

**Comment by imTefa** [comment]
@arsalanNasiri  Did you managed to fix this issue?

**Comment by fkocak2505** [comment]
I had some issue on Android 12. Please fix that issue..

**Comment by Bacass** [comment]
I have some issue on Android 12. Please fix that issue..

**Comment by todoFixIt** [comment]
Sorry for the delay, in case it is useful information I'm using  implementation 'com.google.android.gms:play-services-location:20.0.0' apart from OkHttp is the only dependency I wasn't able to update yet because it slows the whole app when I do it.

The errors in the order I got them:

**NotificationsManager** 
```
java.lang.IllegalArgumentException: com.anon.anon: Targeting S+ (version 31 and above) requires that one of 
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the 
PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
```

**EventThread** 
```
Task threw exception
java.lang.IllegalStateException: Unable to extract the trust manager on Android10Platform, sslSocketFactory is 
class com.google.android.gms.org.conscrypt.OpenSSLSocketFactoryImpl
	at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:751)
	at io.socket.engineio.client.transports.WebSocket.doOpen(WebSocket.java:50)
	at io.socket.engineio.client.Transport$1.run(Transport.java:82)
	at io.socket.thread.EventThread.exec(EventThread.java:55)
	at io.socket.engineio.client.Transport.open(Transport.java:77)
	at io.socket.engineio.client.Socket.probe(Socket.java:472)
	at io.socket.engineio.client.Socket.onOpen(Socket.java:485)
	at io.socket.engineio.client.Socket.onHandshake(Socket.java:526)
	at io.socket.engineio.client.Socket.onPacket(Socket.java:499)
	at io.socket.engineio.client.Socket.access$1000(Socket.java:31)
	at io.socket.engineio.client.Socket$5.call(Socket.java:313)
	at io.socket.emitter.Emitter.emit(Emitter.java:117)
	at io.socket.engineio.client.Transport.onPacket(Transport.java:134)
	at io.socket.engineio.client.transports.Polling.access$700(Polling.java:17)
	at io.socket.engineio.client.transports.Polling$2.call(Polling.java:124)
	at io.socket.engineio.parser.Parser.decodePayload(Parser.java:251)
	at io.socket.engineio.client.transports.Polling._onData(Polling.java:134)
	at io.socket.engineio.client.transports.Polling.onData(Polling.java:106)
	at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:111)
	at io.socket.thread.EventThread$2.run(EventThread.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

**AndroidRuntime**	
```
FATAL EXCEPTION: EventThread
Process: com.anon.anon, PID: 31286
java.lang.IllegalStateException: Unable to extract the trust manager on Android10Platform, sslSocketFactory is 
class com.google.android.gms.org.conscrypt.OpenSSLSocketFactoryImpl
	at okhttp3.OkHttpClient$Builder.sslSocketFactory(OkHttpClient.kt:751)
	at io.socket.engineio.client.transports.WebSocket.doOpen(WebSocket.java:50)
	at io.socket.engineio.client.Transport$1.run(Transport.java:82)
	at io.socket.thread.EventThread.exec(EventThread.java:55)
	at io.socket.engineio.client.Transport.open(Transport.java:77)
	at io.socket.engineio.client.Socket.probe(Socket.java:472)
	at io.socket.engineio.client.Socket.onOpen(Socket.java:485)
	at io.socket.engineio.client.Socket.onHandshake(Socket.java:526)
	at io.socket.engineio.client.Socket.onPacket(Socket.java:499)
	at io.socket.engineio.client.Socket.access$1000(Socket.java:31)
	at io.socket.engineio.client.Socket$5.call(Socket.java:313)
	at io.socket.emitter.Emitter.emit(Emitter.java:117)
	at io.socket.engineio.client.Transport.onPacket(Transport.java:134)
	at io.socket.engineio.client.transports.Polling.access$700(Polling.java:17)
	at io.socket.engineio.client.transports.Polling$2.call(Polling.java:124)
	at io.socket.engineio.parser.Parser.decodePayload(Parser.java:251)
	at io.socket.engineio.client.transports.Polling._onData(Polling.java:134)
	at io.socket.engineio.client.transports.Polling.onData(Polling.java:106)
	at io.socket.engineio.client.transports.PollingXHR$5$1.run(PollingXHR.java:111)
	at io.socket.thread.EventThread$2.run(EventThread.java:80)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

**Comment by yschimke** [comment]
This suggests you aren't passing in the trustManager. The sslSocketFactory shouldn't fail like that if you do.

Are you using the latest version of that library

This seems correct

https://github.com/socketio/socket.io-client-java/blob/main/src/site/markdown/usage.md

**Comment by todoFixIt** [comment]
I was already using the trustManager that was not the issue, **updating io.socket:socket.io-client from 0.x to 1.x solved the issue**. I didn't update that dependency from the begining because the server is on 1.x and the compatibility chart shows that only works with clients in 0.x, but it seems working now...

Thank you for your time.
