### ISSUE TITLE
IllegalArgumentException: port out of range:662184962

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#7153]
Not sure what we could be doing to trigger this...

```
Fatal Exception: java.lang.IllegalArgumentException: port out of range:662184962
       at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:144)
       at java.net.InetSocketAddress.createUnresolved(InetSocketAddress.java:269)
       at sun.net.spi.DefaultProxySelector$1.run(DefaultProxySelector.java:315)
       at sun.net.spi.DefaultProxySelector$1.run(DefaultProxySelector.java:219)
       at java.security.AccessController.doPrivileged(AccessController.java:43)
       at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:218)
       at okhttp3.internal.connection.RouteSelector.resetNextProxy$selectProxies(RouteSelector.kt:109)
       at okhttp3.internal.connection.RouteSelector.resetNextProxy(RouteSelector.kt:116)
       at okhttp3.internal.connection.RouteSelector.<init>(RouteSelector.kt:56)
       at okhttp3.internal.connection.RealRoutePlanner.planConnect(RealRoutePlanner.kt:131)
       at okhttp3.internal.connection.RealRoutePlanner.plan(RealRoutePlanner.kt:63)
       at okhttp3.internal.connection.SequentialExchangeFinder.find(SequentialExchangeFinder.kt:37)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:267)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:96)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:75)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
```

**Comment by swankjesse** [comment]
Same as https://github.com/square/okhttp/issues/6877

**Comment by swankjesse** [comment]
Same as https://github.com/square/okhttp/issues/5681

**Comment by swankjesse** [comment]
No action to take on this. It’s a misconfiguration and it’s best reported with a fatal crash like this. The alternative is we could ignore the proxy selector, but that hides bugs.

**Comment by vikas0** [comment]
hey @swankjesse 
so what we do, I also have the same issue.
````
Fatal Exception: java.lang.IllegalArgumentException: port out of range:123456
       at java.net.InetSocketAddress.checkPort(InetSocketAddress.java:144)
       at java.net.InetSocketAddress.createUnresolved(InetSocketAddress.java:269)
       at sun.net.spi.DefaultProxySelector$1.run(DefaultProxySelector.java:315)
       at sun.net.spi.DefaultProxySelector$1.run(DefaultProxySelector.java:219)
       at java.security.AccessController.doPrivileged(AccessController.java:43)
       at sun.net.spi.DefaultProxySelector.select(DefaultProxySelector.java:218)
       at com.android.okhttp.internal.http.RouteSelector.resetNextProxy(RouteSelector.java:123)
       at com.android.okhttp.internal.http.RouteSelector.<init>(RouteSelector.java:63)
       at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:172)
       at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
       at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
       at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
       at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
       at com.android.okhttp.internal.huc.HttpURLConnectionImpl.getOutputStream(HttpURLConnectionImpl.java:262)
       at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.getOutputStream(DelegatingHttpsURLConnection.java:219)
       at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:30)
       at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.writeRequestBodyToOutputStream(FirebaseInstallationServiceClient.java:234)
       at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.writeGenerateAuthTokenRequestBodyToOutputStream(FirebaseInstallationServiceClient.java:275)
       at com.google.firebase.installations.remote.FirebaseInstallationServiceClient.generateAuthToken(FirebaseInstallationServiceClient.java:410)
       at com.google.firebase.installations.FirebaseInstallations.fetchAuthTokenFromServer(FirebaseInstallations.java:563)
       at com.google.firebase.installations.FirebaseInstallations.doNetworkCallIfNecessary(FirebaseInstallations.java:387)
       at com.google.firebase.installations.FirebaseInstallations.lambda$doRegistrationOrRefresh$2(FirebaseInstallations.java:374)
       at com.google.firebase.installations.-$$Lambda$FirebaseInstallations$SC1awUtshakVcZWKWh8TCfIkd4g.run(-.java:4)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)`
```

How do we handle this?

Happening on app startup as per crashlytics.

**Comment by yschimke** [comment]
com.android.okhttp.internal.http is not this project, it's part of AOSP.

**Comment by vikas0** [comment]
@yschimke under which project can i put this issue for tracking.  
com.google.firebase.installations.remote.FirebaseInstallationServiceClient is there in the stacktrace.

**Comment by yschimke** [comment]
Maybe https://firebase.google.com/support/troubleshooter/report/bugs
