### ISSUE TITLE
java.io.IOException: java.util.zip.DataFormatException: invalid distance too far back

### ISSUE THREAD

**Issue by steve-chancetop** [square/okhttp#7178]
Hello, guys. I found an issue when I integrated Java project with kotlin project. This issue occurred when a java client calling a kotlin api (javalin). This issue confused me a lot. Would you guys give some explain of this.
Error trace as
```
Caused by: java.io.IOException: java.util.zip.DataFormatException: invalid distance too far back
	at okio.InflaterSource.readOrInflate(InflaterSource.kt:99)
	at okio.InflaterSource.read(InflaterSource.kt:49)
	at okio.GzipSource.read(GzipSource.kt:69)
	at okio.Buffer.writeAll(Buffer.kt:1642)
	at okio.RealBufferedSource.readByteArray(RealBufferedSource.kt:236)
	at okhttp3.ResponseBody.bytes(ResponseBody.kt:124)
```

**Comment by steve-chancetop** [comment]
Thank you for your updates. This is not easy to reproduce. But I'd prefer to provide it, if there is any more detail to reproduce it.

**Comment by yschimke** [comment]
Thanks, please reopen with more detail.
