### ISSUE TITLE
域名下划线问题

### ISSUE THREAD

**Issue by coderxiaotu** [square/okhttp#7182]
测试域名为：https://test_test.test.com
java.lang.IllegalArgumentException: Invalid input to toASCII: 
  at java.net.IDN.toASCII(IDN.java:115)
        at javax.net.ssl.SNIHostName.<init>(SNIHostName.java:99)
        at com.android.org.conscrypt.Platform.getSSLParameters(Platform.java:153)
        at com.android.org.conscrypt.ConscryptFileDescriptorSocket.getSSLParameters(ConscryptFileDescriptorSocket.java:1117)
        at com.android.okhttp.internal.Platform.configureTlsExtensions(Platform.java:121)
        at com.android.okhttp.internal.io.RealConnection.connectTls(RealConnection.java:191)
        at com.android.okhttp.internal.io.RealConnection.connectSocket(RealConnection.java:153)
        at com.android.okhttp.internal.io.RealConnection.connect(RealConnection.java:116)
        at com.android.okhttp.internal.http.StreamAllocation.findConnection(StreamAllocation.java:186)
        at com.android.okhttp.internal.http.StreamAllocation.findHealthyConnection(StreamAllocation.java:128)
        at com.android.okhttp.internal.http.StreamAllocation.newStream(StreamAllocation.java:97)
        at com.android.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:289)
        at com.android.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:232)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:465)
        at com.android.okhttp.internal.huc.HttpURLConnectionImpl.connect(HttpURLConnectionImpl.java:131)
        at com.android.okhttp.internal.huc.DelegatingHttpsURLConnection.connect(DelegatingHttpsURLConnection.java:90)
        at com.android.okhttp.internal.huc.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:30)
       .......

**Comment by yschimke** [comment]
This has been fixed https://github.com/square/okhttp/issues/5840

Please update to OkHttp 4.9.3.
