### ISSUE TITLE
IllegalStateException "Check failed" with Fast Fallback on 5.0.0-alpha.6 on Android

### ISSUE THREAD

**Issue by talklittle** [square/okhttp#7186]
OkHttp 5.0.0-alpha.6

Fast fallback enabled.

Unfortunately I don't know how to reproduce the issue. Got a few crash logs, Android 11 and 12, and not specific to any device manufacturer.

Two slightly different stack traces. One mentions `RealRoutePlanner.planReusePooledConnection` and the other does not.

```
Fatal Exception: java.lang.IllegalStateException: Check failed.
       at okhttp3.internal.connection.RealCall.acquireConnectionNoEvents(RealCall.java:89)
       at okhttp3.internal.connection.RealConnectionPool.callAcquirePooledConnection(RealConnectionPool.java:52)
       at okhttp3.internal.connection.RealRoutePlanner.planReusePooledConnection$okhttp(RealRoutePlanner.java:32)
       at okhttp3.internal.connection.ConnectPlan.handleSuccess(ConnectPlan.java:21)
       at okhttp3.internal.connection.FastFallbackExchangeFinder.find(FastFallbackExchangeFinder.java:138)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.java:29)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:11)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:166)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:194)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:166)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:167)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:166)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:34)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:166)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:113)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)
```

```
Fatal Exception: java.lang.IllegalStateException: Check failed.
       at okhttp3.internal.connection.RealCall.acquireConnectionNoEvents(RealCall.java:89)
       at okhttp3.internal.connection.ConnectPlan.handleSuccess(ConnectPlan.java:53)
       at okhttp3.internal.connection.FastFallbackExchangeFinder.find(FastFallbackExchangeFinder.java:138)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.java:29)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:11)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:166)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:194)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:166)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:167)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:166)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:34)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:166)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.java:113)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.java:33)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:923)
```

**Comment by swankjesse** [comment]
Can fix!

**Comment by yschimke** [comment]
@talklittle just want to say thanks for the report, and both stacktraces.  Really helpful to flush out any issues before 5.0.

**Comment by swankjesse** [comment]
I’m gonna assume your crash reporting tool or obfuscator mangled the line numbers and put `.java` file extensions where `.kt` is expected. But the stacktrace otherwise holds up. I rewrote it here.

```
Fatal Exception: java.lang.IllegalStateException: Check failed.
       at okhttp3.internal.connection.RealCall.acquireConnectionNoEvents(RealCall.kt:284)
       at okhttp3.internal.connection.RealConnectionPool.callAcquirePooledConnection(RealConnectionPool.kt:96)
       at okhttp3.internal.connection.RealRoutePlanner.planReusePooledConnection$okhttp(RealRoutePlanner.kt:162)
       at okhttp3.internal.connection.ConnectPlan.handleSuccess(ConnectPlan.kt:473)
       at okhttp3.internal.connection.FastFallbackExchangeFinder.find(FastFallbackExchangeFinder.kt:91)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:267)
```

Looks like a straight up logic bug where I’m doing a bad job replacing a fresh connection with a pooled one.

**Comment by swankjesse** [comment]
Looks like a straight up logic bug where I’m doing a bad job replacing a fresh connection with a pooled one.

**Comment by talklittle** [comment]
> just want to say thanks for the report, and both stacktraces. Really helpful to flush out any issues before 5.0.

Thank you guys for continuing to maintain this vital library, and in particular working on Happy Eyeballs which is going to improve Android and Java applications' stability greatly at an ecosystem level. Very awesome.
