### ISSUE TITLE
NullPointerException when write in concurrency

### ISSUE THREAD

**Issue by wisdomtl** [square/okhttp#7212]
I am writing string into file by BufferedSink in concurrency. It crashs. the code looks like the following:

```kotlin
 val sink = File("xxx").sink(true).buffer()
mainScope.launch(Dispatchers.IO) {
            repeat(10000) {
                sink.writeUtf8(str4) // str4 is a long string
            }
}

mainScope.launch(Dispatchers.IO) {
            repeat(10000) {
                sink.writeUtf8(str1) // str1 is a short string
            }
}

mainScope.launch(Dispatchers.IO) {
            repeat(10000) {
                sink.writeUtf8(str2) // str2 is a long string
            }
}

mainScope.launch(Dispatchers.IO) {
            repeat(10000) {
                sink.writeUtf8(str3) // str3 is a short string
            }
}
```

sometimes the error call stack looks like this:

    java.lang.ArrayIndexOutOfBoundsException: length=8192; regionStart=14618; regionLength=-6426
        at libcore.util.ArrayUtils.throwsIfOutOfBounds(ArrayUtils.java:40)
        at libcore.io.IoBridge.write(IoBridge.java:533)
        at java.io.FileOutputStream.write(FileOutputStream.java:392)
        at okio.OutputStreamSink.write(JvmOkio.kt:57)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
        at okio.RealBufferedSink.writeUtf8(RealBufferedSink.kt:162)

while sometime it looks like this:

    java.lang.NullPointerException
        at okio.OutputStreamSink.write(JvmOkio.kt:55)
        at okio.RealBufferedSink.emitCompleteSegments(RealBufferedSink.kt:255)
        at okio.RealBufferedSink.writeUtf8(RealBufferedSink.kt:162)

**Comment by swankjesse** [comment]
Buffer and BufferedSink are not safe for concurrent use. If you want to use it from multiple dispatchers, you need a coordination mechanism like a lock.
