### ISSUE TITLE
SocektTimeoutException when using specific local address

### ISSUE THREAD

**Issue by Roofi27** [square/okhttp#7216]
I have problem with using OkHttp client with overriten SocketFactory. I' ve implemented my custom SocketFactory in the same way it is implemented [here](https://github.com/yschimke/okurl/blob/e484fa1548b7e34b95972826f40dce0b5fe32f35/src/main/kotlin/com/baulsupp/oksocial/network/InterfaceSocketFactory.kt)

Some of the requests works, but most of the times when I try to execute http request I get error:

```
java.net.SocketTimeoutException: connect timed out
        at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
        at java.base/java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:242)
        at java.base/java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:224)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:120)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
```
        
Does anyone knows where the problem is?

**Comment by yschimke** [comment]
What interface are you binding to? Can that network access the IP?

Is this on JVM or Android?

**Comment by yschimke** [comment]
Can you post this on stackoverflow and post a link there, let's continue the discussion there instead of in an issue tracker.

**Comment by Roofi27** [comment]
https://stackoverflow.com/questions/71748458/okhttp3-socekttimeoutexception-when-using-specific-local-address
