### ISSUE TITLE
 java.security.NoSuchProviderException: no such provider: BC

### ISSUE THREAD

**Issue by 08carmelo** [square/okhttp#7234]
A small number of crashes occur in online apps, they only occur in some models of Android 7, such as LG accounted for 98%

crash log:

Fatal Exception: java.lang.AssertionError: java.security.NoSuchProviderException: no such provider: BC
       at com.android.org.conscrypt.NativeCrypto.X509_NAME_hash(NativeCrypto.java:399)
       at com.android.org.conscrypt.NativeCrypto.X509_NAME_hash_old(NativeCrypto.java:380)
       at android.security.net.config.DirectoryCertificateSource.getHash(DirectoryCertificateSource.java:187)
       at android.security.net.config.DirectoryCertificateSource.findCert(DirectoryCertificateSource.java:166)
       at android.security.net.config.DirectoryCertificateSource.findBySubjectAndPublicKey(DirectoryCertificateSource.java:91)
       at android.security.net.config.SystemCertificateSource.findBySubjectAndPublicKey(SystemCertificateSource.java)
       at android.security.net.config.CertificatesEntryRef.findBySubjectAndPublicKey(CertificatesEntryRef.java:47)
       at android.security.net.config.NetworkSecurityConfig.findTrustAnchorBySubjectAndPublicKey(NetworkSecurityConfig.java:123)
       at android.security.net.config.TrustedCertificateStoreAdapter.getTrustAnchor(TrustedCertificateStoreAdapter.java:51)
       at com.android.org.conscrypt.TrustManagerImpl.findTrustAnchorBySubjectAndPublicKey(TrustManagerImpl.java:795)
       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:393)
       at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:375)
       at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:304)
       at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
       at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:88)
       at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:178)
       at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:599)
       at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(NativeCrypto.java)
       at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:360)
       at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.kt:379)
       at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.kt:337)
       at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:209)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.infra.apm.lcp.NetWorkMonitorInterceptor.intercept(OkHttpHook.kt:38)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.infra.apm.lcp.NetWorkMonitorInterceptor.intercept(OkHttpHook.kt:38)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
       at com.google.firebase.perf.network.FirebasePerfOkHttpClient.execute(FirebasePerfOkHttpClient.java:44)
       at com.x.library.httputils.get.HttpGetUtils.getData(HttpGetUtils.java:192)
       at com.x.library.httputils.get.thread.GetDataThread.get(GetDataThread.java:63)
       at com.x.library.httputils.get.thread.GetDataThread.running(GetDataThread.java:37)
       at com.x.library.httputils.BaseHttpClientThread.run(BaseHttpClientThread.java:43)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
       at java.lang.Thread.run(Thread.java:761)

**Comment by yschimke** [comment]
Conscrypt is part of the android platform, you can file a bug with AOSP, or potentially the https://github.com/google/conscrypt project.  But this is not something we can help with.

`com.android.org.conscrypt.NativeCrypto.X509_NAME_hash`
