### ISSUE TITLE
WebSocket close

### ISSUE THREAD

**Issue by Alanqiu** [square/okhttp#7259]
The call to close appears, always printing the following information

W/MessageQueue: Handler (com.loc.e$a) {9171c7e} sending message to a Handler on a dead thread
    java.lang.IllegalStateException: Handler (com.loc.e$a) {9171c7e} sending message to a Handler on a dead thread
        at android.os.MessageQueue.enqueueMessage(MessageQueue.java:574)
        at android.os.Handler.enqueueMessage(Handler.java:778)
        at android.os.Handler.sendMessageAtTime(Handler.java:727)
        at android.os.Handler.sendMessageDelayed(Handler.java:697)
        at android.os.Handler.sendMessage(Handler.java:635)
        at android.os.Handler$MessengerImpl.send(Handler.java:919)
        at android.os.Messenger.send(Messenger.java:59)
        at com.loc.d.a(Unknown Source:47)
        at com.loc.d.m(Unknown Source:86)
        at com.loc.d.h(Unknown Source:0)
        at com.loc.d$a.handleMessage(Unknown Source:214)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:233)
        at android.os.Looper.loop(Looper.java:344)
        at android.os.HandlerThread.run(HandlerThread.java:67)
        at com.loc.d$b.run(Unknown Source:0)

**Comment by JakeWharton** [comment]
There is no OkHttp in the offending stacktrace. What makes you assume this is related to OkHttp?

**Comment by Alanqiu** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by Alanqiu** [comment]
Thanks for the answer. I tried to shield my Handler, and it will already appear when there is no Handler used. It will not occur without calling close.
![image](https://user-images.githubusercontent.com/5857925/165433278-6ad26b50-57aa-4bbe-bbeb-0f4af4b4e27d.png)
![image](https://user-images.githubusercontent.com/5857925/165433440-249432a1-6d8f-4897-b9de-162abbaad569.png)

**Comment by yschimke** [comment]
What ever behaviour is changing its very likely in you app code. Please reopen with a clear stack trace showing okhttp is the cause or a bug repro.
