### ISSUE TITLE
Fatal Exception: java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by owant** [square/okhttp#7284]
Fatal Exception: java.lang.NoSuchMethodError: No static method delimiterOffset(Ljava/lang/String;IILjava/lang/String;)I in class Lokhttp3/internal/Util; or its super classes (declaration of 'okhttp3.internal.Util' appears in /data/app/~~qPK1Ju7Qg_I4pJQYfShFYw==/com.gosund.smart-YGpnO1TejUYnIJRXokCrxQ==/base.apk!classes26.dex)
       at okhttp3.JavaNetCookieJar.decodeHeaderAsJavaNetCookies(JavaNetCookieJar.java:91)
       at okhttp3.JavaNetCookieJar.loadForRequest(JavaNetCookieJar.java:74)
       at com.facebook.react.modules.network.ReactCookieJarContainer.loadForRequest(ReactCookieJarContainer.java:40)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:74)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)

          

"com.squareup.okhttp3:okhttp-bom:4.9.3",
"com.squareup.okhttp3:okhttp",
"com.squareup.okhttp3:logging-interceptor",
"com.squareup.okhttp3:okhttp-urlconnection",

**Comment by yschimke** [comment]
Which dependency is JavaNetCookieJar coming from, it shows in stacktrace as java instead of kotlin.

**Comment by yschimke** [comment]
See https://stackoverflow.com/a/63368774/1542667 

api("com.squareup.okhttp3:okhttp-urlconnection:4.9.3")
