### ISSUE TITLE
okhttp thread blocked and the task queue keeps increasing

### ISSUE THREAD

**Issue by zouhuajian** [square/okhttp#7287]
I use okhttp to send post request to prometheus.

all okhttp threads are blocked and the task queue keeps increasing, it may cause `java.lang.OutOfMemoryError: GC overhead limit exceeded`

``` java
"OkHttp http://xxx:18480/..." Id=139 BLOCKED on okhttp3.internal.concurrent.TaskRunner@1df40aa1 owned by "OkHttp ConnectionPool" Id=2967
	at okhttp3.internal.concurrent.TaskQueue.schedule(TaskQueue.kt:62)
	-  blocked on okhttp3.internal.concurrent.TaskRunner@1df40aa1
	at okhttp3.internal.concurrent.TaskQueue.schedule$default(TaskQueue.kt:61)
	at okhttp3.internal.connection.RealConnectionPool.connectionBecameIdle(RealConnectionPool.kt:114)
	at okhttp3.internal.connection.RealCall.releaseConnectionNoEvents$okhttp(RealCall.kt:386)
	at okhttp3.internal.connection.RealCall.callDone(RealCall.kt:350)
	-  locked okhttp3.internal.connection.RealConnection@1d1808f1
	at okhttp3.internal.connection.RealCall.noMoreExchanges$okhttp(RealCall.kt:325)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:212)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	...
	Number of locked synchronizers = 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@35d01c63

"OkHttp ConnectionPool" Id=2967 BLOCKED on okhttp3.internal.connection.RealConnection@1d1808f1 owned by "OkHttp http://xxx:18480/..." Id=139
	at okhttp3.internal.connection.RealConnectionPool.cleanup(RealConnectionPool.kt:153)
	-  blocked on okhttp3.internal.connection.RealConnection@1d1808f1
	at okhttp3.internal.connection.RealConnectionPool$cleanupTask$1.runOnce(RealConnectionPool.kt:44)
	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
	Number of locked synchronizers = 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@26ae2037
```
![jprofiler](https://user-images.githubusercontent.com/24971576/170260760-2a9affba-0dd3-4377-9bde-bb4bc7795a0f.png)

**Client Configuration**
``` java
public static OkHttpClient getClient(boolean enableRetry) {
    ConnectionPool connectionPool = new ConnectionPool(8, 5, TimeUnit.MINUTES);
    Dispatcher dispatcher = new Dispatcher(new ThreadPoolExecutor(8, 8,
            1, TimeUnit.MINUTES,
            new LinkedBlockingQueue<>(16),
            new ThreadFactoryBuilder().setNameFormat("okhttp-dispatcher-%d").setDaemon(true).build(),
            new ThreadPoolExecutor.CallerRunsPolicy()));
    dispatcher.setMaxRequestsPerHost(8);
    dispatcher.setMaxRequests(8);
    OkHttpClient.Builder builder = new OkHttpClient().newBuilder()
            .retryOnConnectionFailure(false)
            .callTimeout(Duration.ofSeconds(10))
            .readTimeout(Duration.ofSeconds(3))
            .writeTimeout(Duration.ofSeconds(3))
            .dispatcher(dispatcher)
            .connectionPool(connectionPool);
    if (enableRetry) {
        builder.addInterceptor(OkHttpRetryInterceptor.create(3));
    }
    return builder.build();
}
```

**Comment by zouhuajian** [comment]
> I suspect it's a result of the ThreadPoolExecutor policy you set. Does it happen with the default?
Yes, this problem also occurs with the default thread pool, I thought it was a problem with the default thread pool.

**Comment by yschimke** [comment]
What does OkHttpRetryInterceptor look like?

**Comment by zouhuajian** [comment]
> What does OkHttpRetryInterceptor look like?

I didn't remove OkHttpRetryInterceptor to test, i'll do it today, the problem of thread blocked does not come up very often, it takes some time

**OkHttpRetryInterceptor**
``` java
public static class OkHttpRetryInterceptor implements Interceptor {
    private static final long RETRY_INTERVAL_MILLIS = 200;
    public int maxRetryTimes;

    private OkHttpRetryInterceptor(int maxRetryTimes) {
        this.maxRetryTimes = maxRetryTimes;
    }

    public static OkHttpRetryInterceptor create(int maxRetryTimes) {
        return new OkHttpRetryInterceptor(maxRetryTimes);
    }

    @Override
    public Response intercept(Chain chain) throws IOException {
        Request request = chain.request();
        Response response = chain.proceed(request);
        int retryCount = 1;
        while (!response.isSuccessful() && retryCount <= maxRetryTimes) {
            long wait = RETRY_INTERVAL_MILLIS * retryCount;
            LOGGER.warn("okhttp retry: retry count = {}, wait = {}ms, response = {}", retryCount, wait, response);
            response.close();
            try {
                TimeUnit.MILLISECONDS.sleep(wait);
            } catch (InterruptedException ignored1) {
            }
            retryCount++;
            response = chain.proceed(request);
        }
        return response;
    }
}
```

**now client configuration**
``` java
public static OkHttpClient getClientDefault() {
    Duration duration = Duration.ofSeconds(3);
    return new OkHttpClient().newBuilder()
            .callTimeout(Duration.ofSeconds(10))
            .readTimeout(duration)
            .writeTimeout(duration)
            .build();
}
```

**Comment by zouhuajian** [comment]
> > What does OkHttpRetryInterceptor look like?
> 
> there is no OkHttpRetryInterceptor log, so I didn't remove OkHttpRetryInterceptor to test, i'll do it today, the problem of thread blocked does not come up very often, it takes some time
> 
> okhttp version: 4.9.3
> 
> **OkHttpRetryInterceptor**
> 
> ```java
> public static class OkHttpRetryInterceptor implements Interceptor {
>     private static final long RETRY_INTERVAL_MILLIS = 200;
>     public int maxRetryTimes;
> 
>     private OkHttpRetryInterceptor(int maxRetryTimes) {
>         this.maxRetryTimes = maxRetryTimes;
>     }
> 
>     public static OkHttpRetryInterceptor create(int maxRetryTimes) {
>         return new OkHttpRetryInterceptor(maxRetryTimes);
>     }
> 
>     @Override
>     public Response intercept(Chain chain) throws IOException {
>         Request request = chain.request();
>         Response response = chain.proceed(request);
>         int retryCount = 1;
>         while (!response.isSuccessful() && retryCount <= maxRetryTimes) {
>             long wait = RETRY_INTERVAL_MILLIS * retryCount;
>             LOGGER.warn("okhttp retry: retry count = {}, wait = {}ms, response = {}", retryCount, wait, response);
>             response.close();
>             try {
>                 TimeUnit.MILLISECONDS.sleep(wait);
>             } catch (InterruptedException ignored1) {
>             }
>             retryCount++;
>             response = chain.proceed(request);
>         }
>         return response;
>     }
> }
> ```
> 
> **now client configuration**
> 
> ```java
> public static OkHttpClient getClientDefault() {
>     Duration duration = Duration.ofSeconds(3);
>     return new OkHttpClient().newBuilder()
>             .callTimeout(Duration.ofSeconds(10))
>             .readTimeout(duration)
>             .writeTimeout(duration)
>             .build();
> }
> ```

When using the default client configuration, the program failed to reproduce the blocking problem today, but the following problems occurred, and I don't think it is normal.

``` java

"OkHttp http://xxx:18480/..." Id=6000 BLOCKED on okhttp3.internal.connection.RealConnection@24e09a4d owned by "OkHttp http://xxx:18480/..." Id=6141
	at okhttp3.internal.connection.RealConnectionPool.callAcquirePooledConnection(RealConnectionPool.kt:84)
	-  blocked on okhttp3.internal.connection.RealConnection@24e09a4d
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:180)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	...
	Number of locked synchronizers = 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@23c6c225


"OkHttp http://xxx:18480/..." Id=6141 RUNNABLE
	at okhttp3.internal.concurrent.TaskQueue.schedule(TaskQueue.kt:62)
	at okhttp3.internal.concurrent.TaskQueue.schedule$default(TaskQueue.kt:61)
	at okhttp3.internal.connection.RealConnectionPool.connectionBecameIdle(RealConnectionPool.kt:114)
	at okhttp3.internal.connection.RealCall.releaseConnectionNoEvents$okhttp(RealCall.kt:386)
	at okhttp3.internal.connection.RealCall.callDone(RealCall.kt:350)
	-  locked okhttp3.internal.connection.RealConnection@24e09a4d
	at okhttp3.internal.connection.RealCall.noMoreExchanges$okhttp(RealCall.kt:325)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:212)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	...
	Number of locked synchronizers = 1
	- java.util.concurrent.ThreadPoolExecutor$Worker@42677cb3
```

By the way, a colleague I know from another company has a similar problem, but I don't know how he uses it

``` java
"OkHttp ConnectionPool":
  waiting to lock monitor 0x00007f9b9ca0fa48 (object 0x0000000651ac92e8, a org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$ParentFirstClassLoader),
  which is held by "PreState (60/80)#0"
"PreState (60/80)#0":
  waiting to lock monitor 0x00007f9b98e16ff8 (object 0x0000000653805400, a okhttp3.internal.connection.RealConnection),
  which is held by "OkHttp ConnectionPool"

Java stack information for the threads listed above:
===================================================
"OkHttp ConnectionPool":
	at okhttp3.internal.connection.RealConnectionPool.pruneAndGetAllocationCount(RealConnectionPool.kt:220)
	at okhttp3.internal.connection.RealConnectionPool.cleanup(RealConnectionPool.kt:155)
	- locked <0x0000000653805400> (a okhttp3.internal.connection.RealConnection)
	at okhttp3.internal.connection.RealConnectionPool$cleanupTask$1.runOnce(RealConnectionPool.kt:44)
	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:116)
	at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:65)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
"PreState (60/80)#0":
	at okhttp3.internal.connection.RealConnection.incrementSuccessCount$okhttp(RealConnection.kt:163)
	- waiting to lock <0x0000000653805400> (a okhttp3.internal.connection.RealConnection)
	at okhttp3.internal.connection.RealCall.messageDone$okhttp(RealCall.kt:305)
	at okhttp3.internal.connection.Exchange.bodyComplete(Exchange.kt:193)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.complete(Exchange.kt:324)
	at okhttp3.internal.connection.Exchange$ResponseBodySource.read(Exchange.kt:295)
	at okio.RealBufferedSource.read(RealBufferedSource.kt:189)
	at okio.ForwardingSource.read(ForwardingSource.kt:29)
	at retrofit2.OkHttpCall$ExceptionCatchingResponseBody$1.read(OkHttpCall.java:314)
	at okio.RealBufferedSource.select(RealBufferedSource.kt:229)
	at okhttp3.internal.Util.readBomAsCharset(Util.kt:259)
	at okhttp3.ResponseBody.string(ResponseBody.kt:187)
	at com.tencent.monitor.common.client.converter.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:34)
	at com.tencent.monitor.common.client.converter.JacksonResponseBodyConverter.convert(JacksonResponseBodyConverter.java:24)
	at retrofit2.OkHttpCall.parseResponse(OkHttpCall.java:243)
	at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
	...
	at java.lang.Thread.run(Thread.java:748)

Found 1 deadlock.
```

**Comment by yschimke** [comment]
Thanks for the stacktrace, the deadlock looks worrying and suggests a real problem.

I can't reproduce, any chance you can try to reproduce based on this gist with a public test server like httpbin?

https://gist.github.com/yschimke/02c3964023e6df860d6719dd8de707bf

**Comment by yschimke** [comment]
It doesn't seem like an OkHttp only problem.  This worries me and suggests we may not be able to reproduce without your exact environment.

```
  waiting to lock monitor 0x00007f9b9ca0fa48 (object 0x0000000651ac92e8, a org.apache.flink.runtime.execution.librarycache.FlinkUserCodeClassLoaders$ParentFirstClassLoader),
```

Your stacktrace is truncated so we can't see why the other thread is holding that lock.  Are you doing any work in a static initializer for example?

**Comment by yschimke** [comment]
Even in the first stack trace I can't understand how the locks would get in that stack.  runTask explicitly checks we don't hold that lock at that point.

```
  private fun runTask(task: Task) {
    this.assertThreadDoesntHoldLock()
```

I think we need a repro outside of flink to continue investigation.

**Comment by zouhuajian** [comment]
> Even in the first stack trace I can't understand how the locks would get in that stack. runTask explicitly checks we don't hold that lock at that point.
> 
> ```
>   private fun runTask(task: Task) {
>     this.assertThreadDoesntHoldLock()
> ```
> 
> I think we need a repro outside of flink to continue investigation.

I'm trying to reproduce outside of flink, this phenomenon is really not easy to reproduce.

**Comment by yschimke** [comment]
Can you post more of the stacktrace, particularly for the FlinkUserCodeClassLoaders thread?

**Comment by zouhuajian** [comment]
> > Can you post more of the stacktrace, particularly for the FlinkUserCodeClassLoaders thread?
> 
> Sorry for the late reply, I have put the flink taskmanager thread dump on the gist. I still haven't reproduced the problem outsite of flink.
> 
> [flink-taskmanager-threaddump](https://gist.github.com/zouhuajian/ae1db5063ac7d6f60ec3273ea0b99048)

The problem of deadlock may be the cause of jdk.

"UNKNOWN_owner_addr"
https://bugs.java.com/bugdatabase/view_bug.do?bug_id=JDK-8215355

**Comment by yschimke** [comment]
Nice catch, thanks.
