### ISSUE TITLE
🙉java.lang.NoClassDefFoundError: Could not initialize class okhttp3.internal.Util

### ISSUE THREAD

**Issue by ioGarfield** [square/okhttp#7309]
`java.lang.NoClassDefFoundError:` Could not initialize class okhttp3.internal.Util
	at okhttp3.OkHttpClient.<clinit>(OkHttpClient.kt:1073)
	at com.ymm.ai.platform.sdk.util.HttpUtil.<clinit>(HttpUtil.java:34)
	at com.ymm.ai.platform.sdk.AiAccessFacade.searchWithCondition(AiAccessFacade.java:161)
	at com.ymm.ai.platform.sdk.AiAccessFacade.searchWithCondition(AiAccessFacade.java:92)

pom.xml:
```
<dependency>
            <groupId>com.squareup.okhttp3</groupId>
            <artifactId>okhttp</artifactId>
            <version>4.9.3</version>
            <exclusions>
                <exclusion>
                    <artifactId>kotlin-stdlib</artifactId>
                    <groupId>org.jetbrains.kotlin</groupId>
                </exclusion>
            </exclusions>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib</artifactId>
            <version>1.4.0</version>
        </dependency>
        <dependency>
            <groupId>org.jetbrains.kotlin</groupId>
            <artifactId>kotlin-stdlib-common</artifactId>
            <version>1.4.0</version>
        </dependency>
        <dependency>
            <groupId>com.squareup.okio</groupId>
            <artifactId>okio</artifactId>
            <version>2.8.0</version>
            <exclusions>
                <exclusion>
                    <artifactId>kotlin-stdlib</artifactId>
                    <groupId>org.jetbrains.kotlin</groupId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by yschimke** [comment]
Please ask on a site like stackoverflow.  We can't provide 1:1 support for general build issues via the issue tracker.

**Comment by JavierSegoviaCordoba** [comment]
@ioGarfield did you solve this? I am getting it too.
