### ISSUE TITLE
java.net.BindException: Address already in use: no further information 

### ISSUE THREAD

**Issue by beranos** [square/okhttp#7372]
Hello, i'm having this problem in a multi threaded application, the error doesn't seem to appear instantly but after i would guess 10k-15k requests, is there anything i can do to solve this error? for more info i'm also running proxies with authentication (they are rotating) and the error i'm having it seems like this guy was having the same problem: https://github.com/square/okhttp/issues/5313

what code should i change to solve this error? i will try it because i really need to solve this

Full stracktrace: 

> java.net.BindException: Address already in use: no further information
        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:594)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:116)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:266)
        at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:232)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:174)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:238)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:111)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:79)
        at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.kt:163)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:35)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
        at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:194)
        at okhttp3.RealCall.execute(RealCall.kt:67)
        at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
        at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by yschimke** [comment]
This is a better question for stackoverflow.

But if you follow https://square.github.io/okhttp/features/events/ you should be able to see if it's reusing connections or creating new ones each time.  Also check the connection pool when it's failing.

Sorry we can't help 1:1 with issues like this.

**Comment by beranos** [comment]
Hello i did that and got this, can you look into the logs? will really appreciate it, here they are:

> REQUEST 1
0.000 proxySelectStart
0.000 proxySelectEnd
0.000 callStart
0.664 responseHeadersStart
0.664 responseHeadersEnd
0.000 connectStart
0.000 proxySelectStart
0.000 proxySelectEnd
0.664 responseBodyStart
0.001 connectStart
0.174 secureConnectStart
0.998 responseHeadersStart
0.998 responseHeadersEnd
2.422 responseHeadersStart
2.422 responseHeadersEnd
0.953 secureConnectEnd
2.422 responseBodyStart
0.006 connectFailed
0.998 responseBodyStart
0.999 responseBodyEnd
0.006 callFailed
0.999java.net.BindException: Address already in use: no further information requestHeadersStart

        at java.base/sun.nio.ch.Net.pollConnect(Native Method)
        at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:594)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
        at java.base/java.net.Socket.connect(Socket.java:633)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)0.999
        at okhttp3.internal.connection.ConnectPlan.connectSocket(ConnectPlan.kt:254)requestHeadersEnd

        at okhttp3.internal.connection.ConnectPlan.connectTcp(ConnectPlan.kt:128)1.360
        at okhttp3.internal.connection.FastFallbackExchangeFinder$launchTcpConnect$1.runOnce(FastFallbackExchangeFinder.kt:138)responseHeadersStart

        at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:117)1.361
        at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)responseHeadersEnd

        at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:66)0.005
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)connectFailed

        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)0.954
        at java.base/java.lang.Thread.run(Thread.java:833)connectEnd

0.005 callFailed
1.361java.net.BindException: Address already in use: no further information
 responseBodyStart      at java.base/sun.nio.ch.Net.pollConnect(Native Method)

1.361   at java.base/sun.nio.ch.Net.pollConnectNow(Net.java:672)
responseBodyEnd
        at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546)
REQUEST 1       at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:594)

0.955   at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
connectionAcquired
        at java.base/java.net.Socket.connect(Socket.java:633)0.955
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)requestHeadersStart

        at okhttp3.internal.connection.ConnectPlan.connectSocket(ConnectPlan.kt:254)1.361
        at okhttp3.internal.connection.ConnectPlan.connectTcp(ConnectPlan.kt:128)requestHeadersStart

0.955   at okhttp3.internal.connection.FastFallbackExchangeFinder$launchTcpConnect$1.runOnce(FastFallbackExchangeFinder.kt:138)
requestHeadersEnd       at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:117)

0.000   at okhttp3.internal.concurrent.TaskRunner.access$runTask(TaskRunner.kt:42)
callStart       at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:66)

2.743   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
responseBodyEnd at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)

1.362   at java.base/java.lang.Thread.run(Thread.java:833)
requestHeadersEnd
2.743 connectionReleased
2.744 callEnd
0.184 secureConnectStart
0.001 proxySelectStart
0.001 proxySelectEnd

**Comment by yschimke** [comment]
Sorry, someone else may. But I'm away from keyboard, and travelling with my family. I suggest stackoverflow.
