### ISSUE TITLE
java.lang.IllegalStateException: Unbalanced enter/exit

### ISSUE THREAD

**Issue by adamparslew** [square/okhttp#7381]
Apologies if this has already been addressed.  I have encountered the following problem:

- I attempt to create a websocket to a given URL but encountering a 503 during handshaking (rather than 101) resulting in a callback to `onFailure()`.
- Within the callback I attempt to create a new websocket to the same URL, which gives rise to a second call to `onFailure()`:
```
java.io.IOException: canceled due to java.lang.IllegalStateException: Unbalanced enter/exit
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:530)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
	Suppressed: java.lang.IllegalStateException: Unbalanced enter/exit
		at okio.AsyncTimeout$Companion.scheduleTimeout(AsyncTimeout.kt:225)
		at okio.AsyncTimeout$Companion.access$scheduleTimeout(AsyncTimeout.kt:201)
		at okio.AsyncTimeout.enter(AsyncTimeout.kt:54)
		at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:331)
		at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
		at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
		at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
		at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
		at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
		at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
		at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
		at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
		at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
		... 3 more
```
- The second reconnect attempt then gives rise to the following uncaught exception:
```
java.lang.IllegalStateException: Unbalanced enter/exit
	at okio.AsyncTimeout.enter(AsyncTimeout.kt:49)
	at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:329)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
	at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
	at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
	at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

```
- This occurs when I attempt to create the websocket either on the callback thread (directly within `onFailure()`) or from a separate thread.  Note that I am using a shared static `OkHttpClient `instance, as this was the recommended approach.
- The problem does not occur following a successful attempt to the site, only upon start-up if a 503 is immediately encountered.
- I have encountered this under both Java 8 and 17 with okhttp 4.9.3 and 4.10.0.
- The workaround I have found is to schedule the socket creation with a slight delay (>30ms), which avoids this problem.

### Sample Code
I was able to reproduce the problem by providing a non-websocket URL that then returns a status code other than 101:
```
package websocket;

import okhttp3.OkHttpClient;
import okhttp3.Request;
import okhttp3.Response;
import okhttp3.WebSocket;
import okhttp3.WebSocketListener;
import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;

public class OkHttpFailureTest {
    private static final Logger logger = Logger.getLogger(OkHttpFailureTest.class.getName());
    private static final OkHttpClient client = new OkHttpClient.Builder()
            .pingInterval(5L, TimeUnit.SECONDS)
            .build();

    private static class ReconnectingClient extends WebSocketListener {
        private final Request request;

        public ReconnectingClient(String url) {
            this.request = new Request.Builder().url(url).build();
        }

        public void connect() {//
            client.newWebSocket(request, this);
        }

        @Override
        public void onFailure(@NotNull WebSocket webSocket, @NotNull Throwable t, @Nullable Response response) {
            logger.log(Level.SEVERE, String.format("onFailure(%s,%s)", t.getMessage(), response), t);
            connect();
        }
    }

    public static void main(String[] args) {
        Thread.setDefaultUncaughtExceptionHandler((t, e) -> {
            logger.log(Level.SEVERE, "Caught " + t, e);
            System.exit(1);
        });

        // Intentionally use a URL that will return a status code other than 101:
        ReconnectingClient client = new ReconnectingClient("http://news.bbc.co.uk");
        client.connect();
    }
}
```
Any help would be greatly appreciated.  Obviously I have the workaround but it would be good to understand if this is a genuine bug, whether I am mis-using the API, or whether the site in question is not following the correct protocol by returning something other than 101 during the initial handshake.

Thanks,
Adam.

**Comment by adamparslew** [comment]
Great; thanks for confirming.  It's worth mentioning that, oddly this only seemed to catch us out when the process first starts (and the host we're attempting to connect to returns 503): Once a successful connection had been made, subsequent socket drop + recovery attempts resulting in 503 do not appear to trigger the same problem.  I am not 100% on this though.

**Comment by yschimke** [comment]
I can't reproduce this, including with the test. Any chance you can put up a draft PR with a test showing failures in CI?

I've even tried using an Interceptor to change the error to a 503, since the site you used no longer fails in that way.

**Comment by crysxd** [comment]
Also happening on my end with the exact stack trace and using websockets (wrapped with KTOR though). Basicallly when the websocket breaks down I immediately connect it again, causing the issue.

**Comment by vanniktech** [comment]
I also just ran into this. @yschimke I've got a public repo for you: https://github.com/vanniktech/playground/pull/96 which fails:

```
➜  kotlin git:(okhttp-7381/unbalanced) gw run
Configuration cache is an incubating feature.
Reusing configuration cache.

> Task :kotlin:run
java.io.IOException: canceled due to java.lang.IllegalStateException: Unbalanced enter/exit
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:530)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
        Suppressed: java.lang.IllegalStateException: Unbalanced enter/exit
                at okio.AsyncTimeout$Companion.scheduleTimeout(AsyncTimeout.kt:231)
                at okio.AsyncTimeout$Companion.access$scheduleTimeout(AsyncTimeout.kt:204)
                at okio.AsyncTimeout.enter(AsyncTimeout.kt:57)
                at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:333)
                at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
                at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
                at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
                at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
                at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
                at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
                at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
                at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
                ... 3 more
Exception in thread "OkHttp Dispatcher" java.lang.IllegalStateException: Unbalanced enter/exit
        at okio.AsyncTimeout$Companion.scheduleTimeout(AsyncTimeout.kt:231)
        at okio.AsyncTimeout$Companion.access$scheduleTimeout(AsyncTimeout.kt:204)
        at okio.AsyncTimeout.enter(AsyncTimeout.kt:57)
        at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:333)
        at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:427)
        at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:320)
        at okhttp3.internal.http1.HeadersReader.readLine(HeadersReader.kt:29)
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:178)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:106)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:79)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1589)
```

**Comment by eury-fsl** [comment]
> vanniktech/playground#96

Any clue why is this hapenning? I'm getting the same issue.

**Comment by vanniktech** [comment]
Nope. I'm also using the workaround stated above. Basically waiting a few milliseconds.

**Comment by yschimke** [comment]
I'll take a look at the repro on the weekend. Thanks for providing it. Apologies, but have been battling a different issue with media3 at the moment.

**Comment by yschimke** [comment]
Found the cause. @swankjesse can probably spot if the reordering is wrong, otherwise I'll try to land with a test this weekend.

**Comment by hdjddhvxf** [comment]
annotations
.annotation system Ldalvik/annotation/MemberClasses;
    value = {
        Lsg/c$a;
    }
.end annotation


# static fields
.field public static final h:J

.field public static final i:J

.field public static j:Lsg/c;


# instance fields
.field public e:Z

.field public f:Lsg/c;

.field public g:J


# direct methods
.method public static constructor <clinit>()V
    .registers 3

    sget-object v0, Ljava/util/concurrent/TimeUnit;->SECONDS:Ljava/util/concurrent/TimeUnit;

    const-wide/16 v1, 0x3c

    invoke-virtual {v0, v1, v2}, Ljava/util/concurrent/TimeUnit;->toMillis(J)J

    move-result-wide v0

    sput-wide v0, Lsg/c;->h:J

    sget-object v2, Ljava/util/concurrent/TimeUnit;->MILLISECONDS:Ljava/util/concurrent/TimeUnit;

    invoke-virtual {v2, v0, v1}, Ljava/util/concurrent/TimeUnit;->toNanos(J)J

    move-result-wide v0

    sput-wide v0, Lsg/c;->i:J

    return-void
.end method

.method public constructor <init>()V
    .registers 1

    invoke-direct {p0}, Lsg/b0;-><init>()V

    return-void
.end method

.method public static h()Lsg/c;
    .registers 9

    .line 1
    const-class v0, Lsg/c;

    .line 3
    sget-object v1, Lsg/c;->j:Lsg/c;

    .line 5
    iget-object v1, v1, Lsg/c;->f:Lsg/c;

    .line 7
    const/4 v2, 0x0

    .line 8
    invoke-static {}, Ljava/lang/System;->nanoTime()J

    .line 11
    move-result-wide v3

    .line 12
    if-nez v1, :cond_26

    .line 14
    sget-wide v5, Lsg/c;->h:J

    .line 16
    invoke-virtual {v0, v5, v6}, Ljava/lang/Object;->wait(J)V

    .line 19
    sget-object v0, Lsg/c;->j:Lsg/c;

    .line 21
    iget-object v0, v0, Lsg/c;->f:Lsg/c;

    .line 23
    if-nez v0, :cond_25

    .line 25
    invoke-static {}, Ljava/lang/System;->nanoTime()J

    .line 28
    move-result-wide v0

    .line 29
    sub-long/2addr v0, v3

    .line 30
    sget-wide v3, Lsg/c;->i:J

    .line 32
    cmp-long v5, v0, v3

    .line 34
    if-ltz v5, :cond_25

    .line 36
    sget-object v2, Lsg/c;->j:Lsg/c;

    .line 38
    :cond_25
    return-object v2

    .line 39
    :cond_26
    iget-wide v5, v1, Lsg/c;->g:J

    .line 41
    sub-long/2addr v5, v3

    .line 42
    const-wide/16 v3, 0x0

    .line 44
    cmp-long v7, v5, v3

    .line 46
    if-lez v7, :cond_3c

    .line 48
    const-wide/32 v3, 0xf4240

    .line 51
    div-long v7, v5, v3

    .line 53
    mul-long v3, v3, v7

    .line 55
    sub-long/2addr v5, v3

    .line 56
    long-to-int v1, v5

    .line 57
    invoke-virtual {v0, v7, v8, v1}, Ljava/lang/Object;->wait(JI)V

    .line 60
    return-object v2

    .line 61
    :cond_3c
    sget-object v0, Lsg/c;->j:Lsg/c;

    .line 63
    iget-object v3, v1, Lsg/c;->f:Lsg/c;

    .line 65
    iput-object v3, v0, Lsg/c;->f:Lsg/c;

    .line 67
    iput-object v2, v1, Lsg/c;->f:Lsg/c;

    .line 69
    return-object v1
.end method


# virtual methods
.method public final i()V
    .registers 11

    .line 1
    iget-boolean v0, p0, Lsg/c;->e:Z

    .line 3
    if-nez v0, :cond_73

    .line 5
    iget-wide v0, p0, Lsg/b0;->c:J

    .line 7
    iget-boolean v2, p0, Lsg/b0;->a:Z

    .line 9
    const-wide/16 v3, 0x0

    .line 11
    cmp-long v5, v0, v3

    .line 13
    if-nez v5, :cond_11

    .line 15
    if-nez v2, :cond_11

    .line 17
    return-void

    .line 18
    :cond_11
    const/4 v3, 0x1

    .line 19
    iput-boolean v3, p0, Lsg/c;->e:Z

    .line 21
    const-class v3, Lsg/c;

    .line 23
    monitor-enter v3

    .line 24
    :try_start_17
    sget-object v4, Lsg/c;->j:Lsg/c;

    .line 26
    if-nez v4, :cond_2a

    .line 28
    new-instance v4, Lsg/c;

    .line 30
    invoke-direct {v4}, Lsg/c;-><init>()V

    .line 33
    sput-object v4, Lsg/c;->j:Lsg/c;

    .line 35
    new-instance v4, Lsg/c$a;

    .line 37
    invoke-direct {v4}, Lsg/c$a;-><init>()V

    .line 40
    invoke-virtual {v4}, Ljava/lang/Thread;->start()V

    .line 43
    :cond_2a
    invoke-static {}, Ljava/lang/System;->nanoTime()J

    .line 46
    move-result-wide v6

    .line 47
    if-eqz v5, :cond_3c

    .line 49
    if-eqz v2, :cond_3c

    .line 51
    invoke-virtual {p0}, Lsg/b0;->c()J

    .line 54
    move-result-wide v4

    .line 55
    sub-long/2addr v4, v6

    .line 56
    invoke-static {v0, v1, v4, v5}, Ljava/lang/Math;->min(JJ)J

    .line 59
    move-result-wide v0

    .line 60
    goto :goto_3e

    .line 61
    :cond_3c
    if-eqz v5, :cond_42

    .line 63
    :goto_3e
    add-long/2addr v0, v6

    .line 64
    iput-wide v0, p0, Lsg/c;->g:J

    .line 66
    goto :goto_4a

    .line 67
    :cond_42
    if-eqz v2, :cond_6a

    .line 69
    invoke-virtual {p0}, Lsg/b0;->c()J

    .line 72
    move-result-wide v0

    .line 73
    iput-wide v0, p0, Lsg/c;->g:J

    .line 75
    :goto_4a
    iget-wide v0, p0, Lsg/c;->g:J

    .line 77
    sub-long/2addr v0, v6

    .line 78
    sget-object v2, Lsg/c;->j:Lsg/c;

    .line 80
    :goto_4f
    iget-object v4, v2, Lsg/c;->f:Lsg/c;

    .line 82
    if-eqz v4, :cond_5d

    .line 84
    iget-wide v8, v4, Lsg/c;->g:J

    .line 86
    sub-long/2addr v8, v6

    .line 87
    cmp-long v5, v0, v8

    .line 89
    if-gez v5, :cond_5b

    .line 91
    goto :goto_5d

    .line 92
    :cond_5b
    move-object v2, v4

    .line 93
    goto :goto_4f

    .line 94
    :cond_5d
    :goto_5d
    iput-object v4, p0, Lsg/c;->f:Lsg/c;

    .line 96
    iput-object p0, v2, Lsg/c;->f:Lsg/c;

    .line 98
    sget-object v0, Lsg/c;->j:Lsg/c;

    .line 100
    if-ne v2, v0, :cond_68

    .line 102
    invoke-virtual {v3}, Ljava/lang/Object;->notify()V
    :try_end_68
    .catchall {:try_start_17 .. :try_end_68} :catchall_70

    .line 105
    :cond_68
    monitor-exit v3

    .line 106
    return-void

    .line 107
    :cond_6a
    :try_start_6a
    new-instance v0, Ljava/lang/AssertionError;

    .line 109
    invoke-direct {v0}, Ljava/lang/AssertionError;-><init>()V

    .line 112
    throw v0
    :try_end_70
    .catchall {:try_start_6a .. :try_end_70} :catchall_70

    .line 113
    :catchall_70
    move-exception v0

    .line 114
    monitor-exit v3

    .line 115
    throw v0

    .line 116
    :cond_73
    new-instance v0, Ljava/lang/IllegalStateException;

    .line 118
    const-string v1, "Unbalanced enter/exit"

    .line 120
    invoke-direct {v0, v1}, Ljava/lang/IllegalStateException;-><init>(Ljava/lang/String;)V

    .line 123
    throw v0
.end method

.method public final j(Ljava/io/IOException;)Ljava/io/IOException;
    .registers 3

    invoke-virtual {p0}, Lsg/c;->l()Z

    move-result v0

    if-nez v0, :cond_7

    return-object p1

    :cond_7
    invoke-virtual {p0, p1}, Lsg/c;->m(Ljava/io/IOException;)Ljava/io/IOException;

    move-result-object p1

    return-object p1
.end method

.method public final k(Z)V
    .registers 3

    invoke-virtual {p0}, Lsg/c;->l()Z

    move-result v0

    if-eqz v0, :cond_f

    if-nez p1, :cond_9

    goto :goto_f

    :cond_9
    const/4 p1, 0x0

    invoke-virtual {p0, p1}, Lsg/c;->m(Ljava/io/IOException;)Ljava/io/IOException;

    move-result-object p1

    throw p1

    :cond_f
    :goto_f
    return-void
.end method

.method public final l()Z
    .registers 5

    iget-boolean v0, p0, Lsg/c;->e:Z

    const/4 v1, 0x0

    if-nez v0, :cond_6

    return v1

    :cond_6
    iput-boolean v1, p0, Lsg/c;->e:Z

    const-class v0, Lsg/c;

    monitor-enter v0

    :try_start_b
    sget-object v2, Lsg/c;->j:Lsg/c;

    :goto_d
    if-eqz v2, :cond_1d

    iget-object v3, v2, Lsg/c;->f:Lsg/c;

    if-ne v3, p0, :cond_1b

    iget-object v3, p0, Lsg/c;->f:Lsg/c;

    iput-object v3, v2, Lsg/c;->f:Lsg/c;

    const/4 v2, 0x0

    iput-object v2, p0, Lsg/c;->f:Lsg/c;
    :try_end_1a
    .catchall {:try_start_b .. :try_end_1a} :catchall_20

    goto :goto_1e

    :cond_1b
    move-object v2, v3

    goto :goto_d

    :cond_1d
    const/4 v1, 0x1

    :goto_1e
    monitor-exit v0

    return v1

    :catchall_20
    move-exception v1

    monitor-exit v0

    throw v1
.end method

.method public m(Ljava/io/IOException;)Ljava/io/IOException;
    .registers 4

    new-instance v0, Ljava/io/InterruptedIOException;

    const-string v1, "timeout"

    invoke-direct {v0, v1}, Ljava/io/InterruptedIOException;-><init>(Ljava/lang/String;)V

    if-eqz p1, :cond_c

    invoke-virtual {v0, p1}, Ljava/lang/Throwable;->initCause(Ljava/lang/Throwable;)Ljava/lang/Throwable;

    :cond_c
    return-object v0
.end method

.method public n()V
    .registers 1

    return-void
.end method
