### ISSUE TITLE
java.net.SocketException: Connection reset

### ISSUE THREAD

**Issue by germanSuplex23** [square/okhttp#7519]
Im running okHttp on Jboss wildfly 13 (domain) centOs7 with the following jar okhttp-4.2.2. I am calling a REST post call to my client side but im encountering a connection reset each time the call exceeds 5 minutes. I have adjusted the timeout to 900 seconds but it is still failing. 

OkHttpClient.Builder builder = new OkHttpClient.Builder();
						   	 builder.connectTimeout(900, TimeUnit.SECONDS); 
						   	 builder.readTimeout(900, TimeUnit.SECONDS); 
						   	 builder.writeTimeout(900, TimeUnit.SECONDS);
						   	 builder.callTimeout(900, TimeUnit.SECONDS);
	    httpClient = builder.build();

2022-11-09 09:30:37,411 ERROR [stderr] (default task-11819) java.net.SocketException: Connection reset
2022-11-09 09:30:37,411 ERROR [stderr] (default task-11819)     at java.net.SocketInputStream.read(SocketInputStream.java:210)
2022-11-09 09:30:37,412 ERROR [stderr] (default task-11819)     at java.net.SocketInputStream.read(SocketInputStream.java:141)
2022-11-09 09:30:37,412 ERROR [stderr] (default task-11819)     at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
2022-11-09 09:30:37,412 ERROR [stderr] (default task-11819)     at sun.security.ssl.InputRecord.read(InputRecord.java:503)
2022-11-09 09:30:37,413 ERROR [stderr] (default task-11819)     at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:975)
2022-11-09 09:30:37,413 ERROR [stderr] (default task-11819)     at sun.security.ssl.SSLSocketImpl.readDataRecord(SSLSocketImpl.java:933)
2022-11-09 09:30:37,414 ERROR [stderr] (default task-11819)     at sun.security.ssl.AppInputStream.read(AppInputStream.java:105)
2022-11-09 09:30:37,414 ERROR [stderr] (default task-11819)     at okio.InputStreamSource.read(Okio.kt:102)
2022-11-09 09:30:37,415 ERROR [stderr] (default task-11819)     at okio.AsyncTimeout$source$1.read(AsyncTimeout.kt:159)
2022-11-09 09:30:37,415 ERROR [stderr] (default task-11819)     at okio.RealBufferedSource.indexOf(RealBufferedSource.kt:349)
2022-11-09 09:30:37,416 ERROR [stderr] (default task-11819)     at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.kt:222)
2022-11-09 09:30:37,416 ERROR [stderr] (default task-11819)     at okhttp3.internal.http1.Http1ExchangeCodec.readHeaderLine(Http1ExchangeCodec.kt:210)
2022-11-09 09:30:37,416 ERROR [stderr] (default task-11819)     at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:181)
2022-11-09 09:30:37,417 ERROR [stderr] (default task-11819)     at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:105)
2022-11-09 09:30:37,417 ERROR [stderr] (default task-11819)     at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:82)
2022-11-09 09:30:37,417 ERROR [stderr] (default task-11819)     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
2022-11-09 09:30:37,418 ERROR [stderr] (default task-11819)     at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:37)
2022-11-09 09:30:37,418 ERROR [stderr] (default task-11819)     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
2022-11-09 09:30:37,418 ERROR [stderr] (default task-11819)     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
2022-11-09 09:30:37,419 ERROR [stderr] (default task-11819)     at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:82)
2022-11-09 09:30:37,419 ERROR [stderr] (default task-11819)     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
2022-11-09 09:30:37,419 ERROR [stderr] (default task-11819)     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
2022-11-09 09:30:37,420 ERROR [stderr] (default task-11819)     at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
2022-11-09 09:30:37,420 ERROR [stderr] (default task-11819)     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
2022-11-09 09:30:37,420 ERROR [stderr] (default task-11819)     at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:71)
2022-11-09 09:30:37,421 ERROR [stderr] (default task-11819)     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:112)
2022-11-09 09:30:37,421 ERROR [stderr] (default task-11819)     at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:87)
2022-11-09 09:30:37,421 ERROR [stderr] (default task-11819)     at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.kt:184)
2022-11-09 09:30:37,422 ERROR [stderr] (default task-11819)     at okhttp3.RealCall.execute(RealCall.kt:66)
2022-11-09 09:30:37,422 ERROR [stderr] (default task-11819)     at biz.autoscan.ils.dcm.services.DcmInputDocumentDataServices.postApplication(DcmInputDocumentDataServices.java:4707)
2022-11-09 09:30:37,422 ERROR [stderr] (default task-11819)     at biz.autoscan.ils.dcm.services.DcmInputDocumentDataServices.callRestServiceSubmit(DcmInputDocumentDataServices.java:4581)
2022-11-09 09:30:37,423 ERROR [stderr] (default task-11819)     at biz.autoscan.ils.dcm.services.DcmInputDocumentDataServices.submitInsuranceApplication(DcmInputDocumentDataServices.java:4293)
2022-11-09 09:30:37,423 ERROR [stderr] (default task-11819)     at biz.autoscan.ils.dcm.InsAppSubmissionWindow.btnSubmit_action(InsAppSubmissionWindow.java:576)
2022-11-09 09:30:37,423 ERROR [stderr] (default task-11819)     at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
2022-11-09 09:30:37,424 ERROR [stderr] (default task-11819)     at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
2022-11-09 09:30:37,424 ERROR [stderr] (default task-11819)     at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2022-11-09 09:30:37,424 ERROR [stderr] (default task-11819)     at java.lang.reflect.Method.invoke(Method.java:498)
2022-11-09 09:30:37,425 ERROR [stderr] (default task-11819)     at com.sun.el.util.ReflectionUtil.invokeMethod(ReflectionUtil.java:181)
2022-11-09 09:30:37,425 ERROR [stderr] (default task-11819)     at com.sun.el.parser.AstValue.invoke(AstValue.java:289)
2022-11-09 09:30:37,425 ERROR [stderr] (default task-11819)     at com.sun.el.MethodExpressionImpl.invoke(MethodExpressionImpl.java:304)
2022-11-09 09:30:37,426 ERROR [stderr] (default task-11819)     at com.sun.faces.application.MethodBindingMethodExpressionAdapter.invoke(MethodBindingMethodExpressionAdapter.java:88)
2022-11-09 09:30:37,426 ERROR [stderr] (default task-11819)     at com.sun.faces.application.ActionListenerImpl.processAction(ActionListenerImpl.java:102)
2022-11-09 09:30:37,427 ERROR [stderr] (default task-11819)     at com.sun.rave.web.ui.appbase.faces.ActionListenerImpl.processAction(ActionListenerImpl.java:91)
2022-11-09 09:30:37,427 ERROR [stderr] (default task-11819)     at javax.faces.component.UICommand.broadcast(UICommand.java:387)
2022-11-09 09:30:37,428 ERROR [stderr] (default task-11819)     at javax.faces.component.UIViewRoot.broadcastEvents(UIViewRoot.java:475)
2022-11-09 09:30:37,428 ERROR [stderr] (default task-11819)     at javax.faces.component.UIViewRoot.processApplication(UIViewRoot.java:756)
2022-11-09 09:30:37,428 ERROR [stderr] (default task-11819)     at com.sun.faces.lifecycle.InvokeApplicationPhase.execute(InvokeApplicationPhase.java:82)
2022-11-09 09:30:37,429 ERROR [stderr] (default task-11819)     at com.sun.faces.lifecycle.Phase.doPhase(Phase.java:100)
2022-11-09 09:30:37,429 ERROR [stderr] (default task-11819)     at com.sun.faces.lifecycle.LifecycleImpl.execute(LifecycleImpl.java:118)
2022-11-09 09:30:37,430 ERROR [stderr] (default task-11819)     at javax.faces.webapp.FacesServlet.service(FacesServlet.java:265)
2022-11-09 09:30:37,430 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:74)
2022-11-09 09:30:37,431 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
2022-11-09 09:30:37,431 ERROR [stderr] (default task-11819)     at com.sun.rave.web.ui.util.UploadFilter.doFilter(UploadFilter.java:225)
2022-11-09 09:30:37,432 ERROR [stderr] (default task-11819)     at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
2022-11-09 09:30:37,432 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
2022-11-09 09:30:37,432 ERROR [stderr] (default task-11819)     at biz.autoscan.ils.security.SecurityFilter.doFilter(SecurityFilter.java:104)
2022-11-09 09:30:37,433 ERROR [stderr] (default task-11819)     at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
2022-11-09 09:30:37,433 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
2022-11-09 09:30:37,433 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
2022-11-09 09:30:37,434 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
2022-11-09 09:30:37,434 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.ServletChain$1.handleRequest(ServletChain.java:68)
2022-11-09 09:30:37,434 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
2022-11-09 09:30:37,435 ERROR [stderr] (default task-11819)     at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
2022-11-09 09:30:37,435 ERROR [stderr] (default task-11819)     at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2022-11-09 09:30:37,435 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:132)
2022-11-09 09:30:37,436 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
2022-11-09 09:30:37,436 ERROR [stderr] (default task-11819)     at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2022-11-09 09:30:37,436 ERROR [stderr] (default task-11819)     at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
2022-11-09 09:30:37,437 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
2022-11-09 09:30:37,437 ERROR [stderr] (default task-11819)     at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
2022-11-09 09:30:37,437 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
2022-11-09 09:30:37,438 ERROR [stderr] (default task-11819)     at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
2022-11-09 09:30:37,438 ERROR [stderr] (default task-11819)     at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
2022-11-09 09:30:37,438 ERROR [stderr] (default task-11819)     at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2022-11-09 09:30:37,439 ERROR [stderr] (default task-11819)     at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
2022-11-09 09:30:37,439 ERROR [stderr] (default task-11819)     at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2022-11-09 09:30:37,439 ERROR [stderr] (default task-11819)     at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
2022-11-09 09:30:37,440 ERROR [stderr] (default task-11819)     at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
2022-11-09 09:30:37,440 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.SessionRestoringHandler.handleRequest(SessionRestoringHandler.java:119)
2022-11-09 09:30:37,440 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
2022-11-09 09:30:37,441 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
2022-11-09 09:30:37,441 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
2022-11-09 09:30:37,442 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
2022-11-09 09:30:37,442 ERROR [stderr] (default task-11819)     at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
2022-11-09 09:30:37,443 ERROR [stderr] (default task-11819)     at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
2022-11-09 09:30:37,443 ERROR [stderr] (default task-11819)     at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
2022-11-09 09:30:37,443 ERROR [stderr] (default task-11819)     at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
2022-11-09 09:30:37,444 ERROR [stderr] (default task-11819)     at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
2022-11-09 09:30:37,444 ERROR [stderr] (default task-11819)     at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
2022-11-09 09:30:37,444 ERROR [stderr] (default task-11819)     at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1514)
2022-11-09 09:30:37,445 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
2022-11-09 09:30:37,445 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
2022-11-09 09:30:37,445 ERROR [stderr] (default task-11819)     at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
2022-11-09 09:30:37,446 ERROR [stderr] (default task-11819)     at io.undertow.server.Connectors.executeRootHandler(Connectors.java:360)
2022-11-09 09:30:37,446 ERROR [stderr] (default task-11819)     at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:830)
2022-11-09 09:30:37,446 ERROR [stderr] (default task-11819)     at org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
2022-11-09 09:30:37,447 ERROR [stderr] (default task-11819)     at org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1985)
2022-11-09 09:30:37,447 ERROR [stderr] (default task-11819)     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1487)
2022-11-09 09:30:37,448 ERROR [stderr] (default task-11819)     at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1378)
2022-11-09 09:30:37,448 ERROR [stderr] (default task-11819)     at java.lang.Thread.run(Thread.java:748)

**Comment by yschimke** [comment]
Please ask these types of questions on stackoverflow. OR if you are sure it's a bug, please make a reproduction in a test or against a test server.

We can't provide 1:1 support.
