### ISSUE TITLE
OkHttp 4.10.0: Explicit termination method 'close' not called

### ISSUE THREAD

**Issue by vanniktech** [square/okhttp#7532]
I am using OkHttp 4.10.0 and I've just gotten this strict mode warning:

```
StrictMode  D  StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resour
              ce leaks.
           D      at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1986)
           D      at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:336)
           D      at java.io.FileOutputStream.finalize(FileOutputStream.java:495)
           D      at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:319)
           D      at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:306)
           D      at java.lang.Daemons$Daemon.run(Daemons.java:140)
           D      at java.lang.Thread.run(Thread.java:1012)
           D  Caused by: java.lang.Throwable: Explicit termination method 'close' not called
           D      at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:288)
           D      at dalvik.system.CloseGuard.open(CloseGuard.java:257)
           D      at java.io.FileOutputStream.<init>(FileOutputStream.java:253)
           D      at okio.Okio__JvmOkioKt.appendingSink(JvmOkio.kt:178)
           D      at okio.Okio.appendingSink(Unknown Source:1)
           D      at okhttp3.internal.io.FileSystem$Companion$SystemFileSystem.appendingSink(FileSystem.kt:66)
           D      at okhttp3.internal.cache.DiskLruCache.newJournalWriter(DiskLruCache.kt:302)
           D      at okhttp3.internal.cache.DiskLruCache.readJournal(DiskLruCache.kt:295)
           D      at okhttp3.internal.cache.DiskLruCache.initialize(DiskLruCache.kt:236)
           D      at okhttp3.internal.cache.DiskLruCache.get(DiskLruCache.kt:426)
           D      at okhttp3.Cache.get$okhttp(Cache.kt:172)
           D      at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:47)
           D      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
           D      at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
           D      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
           D      at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
           D      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
           D      at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
           D      at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
           D      at com.vanniktech.feature.rssreader.backend.DefaultRssFetcher$fetch$6$1.invokeSuspend(DefaultRssFetcher.kt:151)
           D      at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
           D      at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
           D      at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
           D      at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
           D      at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
           D      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
           D      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
           D      at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

I can see that `newJournalWriter()` is called here: https://github.com/square/okhttp/blob/e46a200fceaa5fbd9c9278eebe9c978399bd329c/okhttp/src/main/kotlin/okhttp3/internal/cache/DiskLruCache.kt#L295 and it's closed here: https://github.com/square/okhttp/blob/e46a200fceaa5fbd9c9278eebe9c978399bd329c/okhttp/src/main/kotlin/okhttp3/internal/cache/DiskLruCache.kt#L679

I'm not familiar with the code but can it be that when newJournalWriter() there is already a `journalWriter` set which would need to be closed?!

My calling site (DefaultRssFetcher:151) looks like this:

```kotlin
withContext(Dispatchers.IO) { 
  okHttpClient.newCall(makeRequest(url).execute() }.use { response ->
    ...
  }
}
```

So I do close the response that I get from OkHttp.

**Comment by yschimke** [comment]
`initialize` is called the first time the Cache is used.

Are you calling cache.close, when you close your client, or release it?

https://github.com/square/okhttp/blob/okhttp_4.10.x/okhttp/src/main/kotlin/okhttp3/OkHttpClient.kt#L111-L115

**Comment by vanniktech** [comment]
I don't call cache.close(), neither to I close / release my client. I'm in an Android Application here.

**Comment by yschimke** [comment]
Do you have a singleton client instance.

I'll try to reproduce based on your original hypothesis. Can put protective close in place.

**Comment by vanniktech** [comment]
Yup. In my custom Android Application class I have a `private val okHttpClient by lazy(NONE) { ... }`

**Comment by yschimke** [comment]
@vanniktech there are some existing tests that were not enabled because of this problem. I've tried improving some, not sure it's worth backporting yet, until all issues are fixed.

Hopefully the scope of this problem for you is limited, if it's the same cases it's likely just recovering from cache corruption and not an ongoing leak of the running program.

**Comment by vanniktech** [comment]
A big downside is that I can't really enable the missing close() detection of StrictMode in my entire application by forcing a crash. So I might leak some other resources else where.

Is this already fixed in OkHttp 5? I can use an alpha version if that has a fix for this.

**Comment by yschimke** [comment]
Probably in the next alpha?

**Comment by vanniktech** [comment]
Nice. I can even verify this before you folks build a new alpha version by trying out the snapshot.

**Comment by yschimke** [comment]
Please try now, I'm not 100% certain it's solved, but at least if we can reproduce it now, there is a clean tested based with the existing bugs fixed.

https://github.com/square/okhttp#releases

**Comment by vanniktech** [comment]
Unfortunately not fixed:

```
             StrictMode  D  StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for infor
                            mation on avoiding resource leaks.
                         D      at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1986)
                         D      at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:336)
                         D      at java.io.FileOutputStream.finalize(FileOutputStream.java:495)
                         D      at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:319)
                         D      at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:306)
                         D      at java.lang.Daemons$Daemon.run(Daemons.java:140)
                         D      at java.lang.Thread.run(Thread.java:1012)
                         D  Caused by: java.lang.Throwable: Explicit termination method 'close' not called
                         D      at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:288)
                         D      at dalvik.system.CloseGuard.open(CloseGuard.java:257)
                         D      at java.io.FileOutputStream.<init>(FileOutputStream.java:253)
                         D      at okio.Okio__JvmOkioKt.sink(JvmOkio.kt:174)
                         D      at okio.Okio.sink(Unknown Source:1)
                         D      at okio.JvmSystemFileSystem.appendingSink(JvmSystemFileSystem.kt:105)
                         D      at okio.ForwardingFileSystem.appendingSink(ForwardingFileSystem.kt:212)
                         D      at okio.FileSystem.appendingSink(FileSystem.kt:89)
                         D      at okhttp3.internal.cache.DiskLruCache.newJournalWriter(DiskLruCache.kt:311)
                         D      at okhttp3.internal.cache.DiskLruCache.readJournal(DiskLruCache.kt:304)
                         D      at okhttp3.internal.cache.DiskLruCache.initialize(DiskLruCache.kt:245)
                         D      at okhttp3.internal.cache.DiskLruCache.get(DiskLruCache.kt:437)
                         D      at okhttp3.Cache.get$okhttp(Cache.kt:177)
                         D      at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:48)
                         D      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                         D      at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
                         D      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                         D      at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
                         D      at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
                         D      at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:202)
                         D      at okhttp3.internal.connection.RealCall.execute(RealCall.kt:155)
```

**Comment by vanniktech** [comment]
Maybe this https://github.com/square/okhttp/blob/master/okhttp/src/jvmMain/kotlin/okhttp3/internal/cache/DiskLruCache.kt#L397 also needs to use closeQuietly?

**Comment by yschimke** [comment]
When does it surface? While the app is running? 

any chance it's an unlikely init race? `private val okHttpClient by lazy(NONE)` seems unsafe.

**Comment by vanniktech** [comment]
> any chance it's an unlikely init race? `private val okHttpClient by lazy(NONE)` seems unsafe.

Yeah that's actually the problem. Wow. Even with 4.10.0. Kudos to you for finding a non related close issue!
