### ISSUE TITLE
javax.net.ssl.SSLException: Unable to create application data

### ISSUE THREAD

**Issue by TestPlanB** [square/okhttp#7538]
java.lang.RuntimeException: javax.net.ssl.SSLException: Unable to create application data
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.newSsl(ConscryptFileDescriptorSocket.java:161)
	at com.android.org.conscrypt.ConscryptFileDescriptorSocket.<init>(ConscryptFileDescriptorSocket.java:152)
	at com.android.org.conscrypt.OpenSSLSocketFactoryImpl.createSocket(OpenSSLSocketFactoryImpl.java:149)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:369)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:337)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:209)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:226)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:74)

okhttp version is 4.2.2

**Comment by yschimke** [comment]
From https://github.com/google/conscrypt/issues/891 looks like an out of memory error.  We can't help with this.  But I would suggest confirming you are not creating lots of OkHttpClient instances.
