### ISSUE TITLE
Tests flake on GitHub actions because hostnames are fetched from DNS

### ISSUE THREAD

**Issue by swankjesse** [square/okhttp#7603]
I [ran tests](https://github.com/square/okhttp/actions/runs/3813128891/jobs/6486697956) on Windows. That failed for a surprising reason:

```
MockWebServerTest > requestUrlReconstructed() FAILED
    org.opentest4j.AssertionFailedError: 
    expected: "MiningMadness.com"
     but was: "miningmadness.com"
        at java.base@11.0.17/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base@11.0.17/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base@11.0.17/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at app//okhttp3.mockwebserver.MockWebServerTest.requestUrlReconstructed(MockWebServerTest.java:471)
```

Perhaps my GitHub actions worker’s IP address has a DNS record, maybe some madness related to mining? We’re doing `InetAddress.getCanonicalHostName()` and that might do a DNS lookup. (Yuck.)

**Comment by yschimke** [comment]
Github has a hosts file with thousands of additional hosts blackholed to local host.

**Comment by yschimke** [comment]
https://github.com/square/okhttp/issues/6813
