### ISSUE TITLE
`ClassNotFoundException` not found with mix of `okhttp-jvm:5.0.0-alpha.10` and `okhttp-tls::4.10.0` 

### ISSUE THREAD

**Issue by yogurtearl** [square/okhttp#7663]
with `com.squareup.okhttp3:okhttp-jvm:5.0.0-alpha.10` and `com.squareup.okhttp3:okhttp-tls:4.10.0` included in the same JVM app, we got this stack trace: 

```text
Caused by: java.lang.ClassNotFoundException: okhttp3.internal.Util
        at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
        at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        at okhttp3.tls.HandshakeCertificates$Builder.build(HandshakeCertificates.kt:174) ~[okhttp-tls-4.10.0.jar:?]
```

The fix is, of course, to just use matching version of the `com.squareup.okhttp3` dependencies (and use `okhttp-bom` to help align dependencies)

Mostly just filing this issue so that future people that hit this can find it via search and fix the conflicting dependency versions.

**Comment by yogurtearl** [comment]
Closing as there is not action needed here.
