### ISSUE TITLE
Unknown host exception Android

### ISSUE THREAD

**Issue by mane91** [square/okhttp#7677]
I am getting below exception. mostly this issue is on **Android 13** devices.

**Caused by java.net.UnknownHostException: Unable to resolve host <HOST_NAME>: No address associated with hostname**
       at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:124)
       at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
       at java.net.InetAddress.getAllByName(InetAddress.java:1152)
       at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
       at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
       at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
       at java.lang.Thread.run(Thread.java:1012)

**Comment by yschimke** [comment]
This is expected on mobile depending on network conditions.

Please use a site like stackoverflow for support.

**Comment by varuntribe** [comment]
This has started happening randomly on our Android app and now is a frequent issue, while iOS app is working as expected. We have checked our servers, no downtime or host issues were encountered. Also, worked with our users and none of them had any internet issues when this happened. It's only happening for Android 13 and above, no prior version is impacted. I think it's worth looking in to this issue. I will be dedicated some time tomorrow to investigate it further and will share my findings here.

**Comment by yschimke** [comment]
Please provide a way for us to reproduce. It's possible this is some doze mode on a particular device stopping network traffic

**Comment by santosaprima** [comment]
Hi @varuntribe did you manage to investigate it?

**Comment by varuntribe** [comment]
Hey @santosaprima , we had to add more reporting on this issue, as it's near impossible to reproduce in test env. We are releasing updated builds with additional reporting today so hopefully we will have some more insight into the issue in next week or so. 
I think Yskimke might be on to something with the doze mode. We are also thinking around the same line. It could be our background worker thread that is failing, that's why we have added failed endpoints as part of the new reporting system.

**Comment by yschimke** [comment]
Discussion on the other bug, but flagging here for different audience.  This comes from a 2 second negative result cache in Android.

https://cs.android.com/android/platform/superproject/main/+/main:libcore/ojluni/src/main/java/java/net/Inet6AddressImpl.java;l=117

So the question is why was network connectivity missing within the last two seconds even if working now.

**Comment by varuntribe** [comment]
Did anyone manage to find a workaround for this?

**Comment by decisionnguyen** [comment]
Same issue on Android 13 :(

**Comment by TopIvanAbramov** [comment]
same issue periodically raise

**Comment by yschimke** [comment]
Android fix for this https://cs.android.com/android/_/android/platform/frameworks/base/+/0fa9120b8f72916951b2d070afd6c3dfd3c13f77. I'm not sure if this goes into mainline modules, but I'm assuming not.

**Comment by saikrupa** [comment]
is this issue addressed in the latest version?

**Comment by yschimke** [comment]
@saikrupa you should check with Android, or your device maker.

**Comment by mehmet6parmak** [comment]
Hi @yschimke do you see any side-effects of using an interceptor like below? 

```
class AndroidNegativeDnsCacheResolutionInterceptor(private val maxRetries: Int = 10, private val retryDelayMillis: Long = 250L) :
        Interceptor {
        override fun intercept(chain: Interceptor.Chain): Response {
            var attempt = 0
            while (true) {
                try {
                    return chain.proceed(chain.request())
                } catch (e: UnknownHostException) {
                    attempt++
                    if (attempt > maxRetries) {
                        throw e // Rethrow the exception after exceeding retries
                    }
                    Thread.sleep(retryDelayMillis) // Add a delay before retrying
                }
            }
        }
    }
```

**Comment by yschimke** [comment]
intercept is already a blocking call, so not really. I can't comment on whether it's the right thing to do for your case.  But having a delay in an ApplicationInterceptor should be ok.

**Comment by Chimildic** [comment]
Can someone tell in detail what to do to fix the issue? I receive `Unable to resolve host` when app try send request after launch by `AlarmManager` and enqueued `Worker`. Usually at night, when the phone has not been used for a long time.

**Comment by cVecchioTheOld** [comment]
@mehmet6parmak 
Did the interceptor help to solve the issue?
I'm facing the issue and I'm looking for a workaround

> Hi [@yschimke](https://github.com/yschimke) do you see any side-effects of using an interceptor like below? By the way, I am able to reproduce the case mostly when the app was launched from a PN on lock screen. The http call is initiated very early inside android app's onCreate method.
> 
> ```
> class AndroidNegativeDnsCacheResolutionInterceptor(private val maxRetries: Int = 10, private val retryDelayMillis: Long = 250L) :
>         Interceptor {
>         override fun intercept(chain: Interceptor.Chain): Response {
>             var attempt = 0
>             while (true) {
>                 try {
>                     return chain.proceed(chain.request())
>                 } catch (e: UnknownHostException) {
>                     attempt++
>                     if (attempt > maxRetries) {
>                         throw e // Rethrow the exception after exceeding retries
>                     }
>                     Thread.sleep(retryDelayMillis) // Add a delay before retrying
>                 }
>             }
>         }
>     }
> ```

**Comment by datngotan-aavn** [comment]
> Can someone tell in detail what to do to fix the issue? I receive `Unable to resolve host` when app try send request after launch by `AlarmManager` and enqueued `Worker`. Usually at night, when the phone has not been used for a long time.

i face the same issue when using worker. Do you have any solution?
