### ISSUE TITLE
Okhttp crash in android 12 javax.net.ssl.SSLException

### ISSUE THREAD

**Issue by TestPlanB** [square/okhttp#7762]
device: PEHM00. 
android os :12

java.lang.RuntimeException: javax.net.ssl.SSLException: Unable to create application data
	at com.android.org.conscrypt.ConscryptEngine.newSsl(ConscryptEngine.java:208)
	at com.android.org.conscrypt.ConscryptEngine.<init>(ConscryptEngine.java:199)
	at com.android.org.conscrypt.ConscryptEngineSocket.newEngine(ConscryptEngineSocket.java:117)
	at com.android.org.conscrypt.ConscryptEngineSocket.<init>(ConscryptEngineSocket.java:104)
	at com.android.org.conscrypt.Java8EngineSocket.<init>(Java8EngineSocket.java:62)
	at com.android.org.conscrypt.Platform.createEngineSocket(Platform.java:329)
	at com.android.org.conscrypt.OpenSSLSocketFactoryImpl.createSocket(OpenSSLSocketFactoryImpl.java:163)
	at okhttp3.internal.connection.RealConnection.connectTls(RealConnection.java:341)
	at okhttp3.internal.connection.RealConnection.establishProtocol(RealConnection.java:310)
	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:178)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:236)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:109)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:77)
	at okhttp3.internal.connection.Transmitter.newExchange$okhttp(Transmitter.java:162)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:35)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:87)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:82)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:87)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:84)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:112)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:71)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:87)
	at com.delivery.wp.argus.android.hook.okhttp.RecordBodyInterceptor.intercept(RecordBodyInterceptor.java:50)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:112)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:87)
	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:184)
	at okhttp3.RealCall$AsyncCall.run(RealCall.java:136)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)

**Comment by yschimke** [comment]
This is a crash in the AOSP conscrypt code, not okhttp
