### ISSUE TITLE
Getting NoHttpResponseException on every second run 

### ISSUE THREAD

**Issue by FeanorsCurse** [square/okhttp#7793]
I am getting a NoHttpResponseException on every second run, it seems to be very similar to this issue:
https://github.com/mock-server/mockserver/issues/509

I cannot really provide a sample failing test, as I don't know the combination in which this occurs and cannot paste our existing code base.

Caused by: org.apache.http.NoHttpResponseException: localhost:3003 failed to respond
	at app//org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:141)
	at app//org.apache.http.impl.conn.DefaultHttpResponseParser.parseHead(DefaultHttpResponseParser.java:56)
	at app//org.apache.http.impl.io.AbstractMessageParser.parse(AbstractMessageParser.java:259)
	at app//org.apache.http.impl.DefaultBHttpClientConnection.receiveResponseHeader(DefaultBHttpClientConnection.java:163)
	at app//org.apache.http.impl.conn.CPoolProxy.receiveResponseHeader(CPoolProxy.java:157)
	at app//org.apache.http.protocol.HttpRequestExecutor.doReceiveResponse(HttpRequestExecutor.java:273)
	at app//org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:125)

**Comment by yschimke** [comment]
This doesn't appear to be OkHttp

Isn't this for https://hc.apache.org/

**Comment by FeanorsCurse** [comment]
No this is OkHttp. I just linked to the other issues because it seems very similar.

**Comment by yschimke** [comment]
Please provide a stacktrace or test reproducing it. Not actionable as is.

**Comment by FeanorsCurse** [comment]
Will try, thank you.
