### ISSUE TITLE
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/okhttp/HttpUrl$Builder

### ISSUE THREAD

**Issue by nAkhmedov** [square/okhttp#7906]
When I launch an app via Charles proxy - app crashes

2023-06-22 17:09:43.226 16292-16546 AndroidRuntime          com.myapp.android                  E  FATAL EXCEPTION: grpc-okhttp-0
                                                                                                    Process: com.myapp.android, PID: 16292
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Lcom/squareup/okhttp/HttpUrl$Builder;
                                                                                                    	at io.grpc.okhttp.OkHttpClientTransport.createHttpProxyRequest(OkHttpClientTransport.java:713)
                                                                                                    	at io.grpc.okhttp.OkHttpClientTransport.createHttpProxySocket(OkHttpClientTransport.java:665)
                                                                                                    	at io.grpc.okhttp.OkHttpClientTransport.access$1100(OkHttpClientTransport.java:110)
                                                                                                    	at io.grpc.okhttp.OkHttpClientTransport$4.run(OkHttpClientTransport.java:561)
                                                                                                    	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "com.squareup.okhttp.HttpUrl$Builder" on path: DexPathList[[zip file "/data/app/~~FNpnMbAPF2q9STsnadDkQA==/com.myapp.android-QQjs-6VDXCrK9_PlBUZZsg==/base.apk"],nativeLibraryDirectories=[/data/app/~~FNpnMbAPF2q9STsnadDkQA==/com.myapp.android-QQjs-6VDXCrK9_PlBUZZsg==/lib/arm64, /data/app/~~FNpnMbAPF2q9STsnadDkQA==/com.myapp.android-QQjs-6VDXCrK9_PlBUZZsg==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at io.grpc.okhttp.OkHttpClientTransport.createHttpProxyRequest(OkHttpClientTransport.java:713) 
                                                                                                    	at io.grpc.okhttp.OkHttpClientTransport.createHttpProxySocket(OkHttpClientTransport.java:665) 
                                                                                                    	at io.grpc.okhttp.OkHttpClientTransport.access$1100(OkHttpClientTransport.java:110) 
                                                                                                    	at io.grpc.okhttp.OkHttpClientTransport$4.run(OkHttpClientTransport.java:561) 
                                                                                                    	at io.grpc.internal.SerializingExecutor.run(SerializingExecutor.java:133) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)

**Comment by yschimke** [comment]
This isn't for the OkHttp project

io.grpc.okhttp.OkHttpClientTransport is the grpc project.
Charles proxy is another project.

If it works without Charles, then you should raise it with them.

**Comment by JakeWharton** [comment]
Also `com.squareup.okhttp` is OkHttp 2.x which is ancient and unsupported.
