### ISSUE TITLE
Test failure with JDK 20

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#7919]
```
HttpUrlTest[jvm] > hostnameUri[jvm] FAILED
    java.lang.RuntimeException: java.net.MalformedURLException: Illegal character found in host: '"'
        at okhttp3.HttpUrl.url(HttpUrl.kt:101)
        at okhttp3.UrlComponentEncodingTesterJvmPlatform.testToUrl(UrlComponentEncodingTesterJvm.kt:130)
        at okhttp3.UrlComponentEncodingTesterJvmPlatform.test(UrlComponentEncodingTesterJvm.kt:118)
        at okhttp3.UrlComponentEncodingTester.test(UrlComponentEncodingTester.kt:102)
        at okhttp3.HttpUrlTest.hostnameUri(HttpUrlTest.kt:573)

        Caused by:
        java.net.MalformedURLException: Illegal character found in host: '"'
            at java.base/java.net.URL.<init>(URL.java:798)
            at java.base/java.net.URL.<init>(URL.java:646)
            at java.base/java.net.URL.<init>(URL.java:582)
            at okhttp3.HttpUrl.url(HttpUrl.kt:99)
            ... 4 more

            Caused by:
            java.lang.IllegalArgumentException: Illegal character found in host: '"'
                at java.base/java.net.URLStreamHandler.setURL(URLStreamHandler.java:522)
                at java.base/java.net.URLStreamHandler.parseURL(URLStreamHandler.java:325)
                at java.base/java.net.URL.<init>(URL.java:793)
                ... 7 more
```

**Comment by yschimke** [comment]
Presumably

_[➜](https://www.oracle.com/java/technologies/javase/20-relnote-issues.html#JDK-8293590) URL Constructors Called with Malformed Input May Throw MalformedURLException for Cases where It Was Not Thrown Previously ([JDK-8293590](https://bugs.openjdk.org/browse/JDK-8293590))

The parsing of input provided to the java.net.URL constructors has changed in this release to be more strict. If the URL constructors are called with malformed input, then MalformedURLException may be thrown for cases where it wasn’t thrown previously.

In previous releases, some of the parsing and validation performed by the JDK built-in URLStreamHander implementations was delayed until URL::openConnection or URLConnection::connect was called. Some of these parsing and validation actions are now performed early, within URL constructors. An exception caused by a malformed URL that would have been delayed until the connection was opened or connected might now cause a MalformedURLException to be thrown at URL construction time.

This change only affects URL instances that delegate to JDK built-in stream handler implementations. Applications relying on custom, third party URLStreamHandler implementations should remain unaffected.

A new JDK specific system property -Djdk.net.url.delayParsing or -Djdk.net.url.delayParsing=true can be specified on the command line to revert to the previous behavior. By default, the property is not set, and the new behavior is in place.

This new property is provided for backward compatibility and may be removed in a future release._

**Comment by devashishTaneja** [comment]
@yschimke I am a first-time contributor to this repo, can I take up this issue?

**Comment by yschimke** [comment]
@devashishTaneja Thanks for the offer. However, we are quite conservative about welcoming new contributors. @swankjesse and myself, don't tend to have enough time to support the ramp up of new contributors.

**Comment by yschimke** [comment]
@swankjesse Should HttpUrl be tolerant of `http://a"z/`

Or should we change to test to expect `"http://a"z/".toHttpUrl().toUrl()` to fail? Changing UrlComponentEncodingTesterJvmPlatform?

**Comment by swankjesse** [comment]
From [HttpUrlTest](https://github.com/square/okhttp/blob/master/okhttp/src/commonTest/kotlin/okhttp3/HttpUrlTest.kt#L536),

    // HttpUrl is quite lenient with what characters it accepts. In particular, characters like '{'
    // and '"' are permitted but unlikely to occur in real-world URLs. Unfortunately we can't just
    // lock it down due to URL templating: "http://{env}.{dc}.example.com".

I don’t think it’s helpful to lock this down further. The quote characters are ultimately going to fail to resolve stuff in DNS.

**Comment by swankjesse** [comment]
We’ve got [another relevant test](https://github.com/square/okhttp/blob/master/okhttp/src/jvmTest/java/okhttp3/HttpUrlJvmTest.kt#L30-L36):

```kotlin
  /** This one's ugly: the HttpUrl's host is non-empty, but the URI's host is null. */
  @Test
  fun hostContainsOnlyStrippedCharacters() {
    val url = "http://>/".toHttpUrl()
    assertThat(url.host).isEqualTo(">")
    assertThat(url.toUri().host).isNull()
  }
```

I think we do likewise for URL.
