### ISSUE TITLE
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10000012c

### ISSUE THREAD

**Issue by JasonZhao0608** [square/okhttp#7928]
implementation 'com.squareup.retrofit2:retrofit:2.9.0'
implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
implementation 'com.squareup.okhttp3:logging-interceptor:4.7.2'
implementation 'com.squareup.okhttp3:okhttp:4.9.1'
implementation 'com.squareup.okhttp3:okhttp-urlconnection:4.9.1'
implementation 'com.squareup.okio:okio:2.10.0'

1.#00 pc 000000000003b6f0 /apex/com.android.conscrypt/lib64/libssl.so (SSL_SESSION_get_time+4)
2.#01 pc 00000000000336b0 /apex/com.android.conscrypt/lib64/libjavacrypto.so (_ZL25NativeCrypto_SSL_get_timeP7_JNIEnvP7_jclasslP8_jobject+124)
3.#02 pc 0000000000140350 /apex/com.android.runtime/lib64/libart.so (art_quick_generic_jni_trampoline+144)
4.#03 pc 00000000001375b8 /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_static_stub+568)
5.#04 pc 0000000000169f20 /apex/com.android.runtime/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+276)
6.#05 pc 0000000000305470 /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreter34ArtInterpreterToCompiledCodeBridgeEPNS_6ThreadEPNS_9ArtMethodEPNS_11ShadowFrameEtPNS_6JValueE+384)
7.#06 pc 0000000000300750 /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreter6DoCallILb0ELb0EEEbPNS_9ArtMethodEPNS_6ThreadERNS_11ShadowFrameEPKNS_11InstructionEtPNS_6JValueE+912)
8.#07 pc 000000000059d990 /apex/com.android.runtime/lib64/libart.so (MterpInvokeStatic+368)
9.#08 pc 0000000000131994 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_static+20)
10.#09 pc 000000000059b0f4 /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1432)
11.#10 pc 0000000000131814 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20)
12.#11 pc 000000000059b0f4 /apex/com.android.runtime/lib64/libart.so (MterpInvokeVirtual+1432)
13.#12 pc 0000000000131814 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_virtual+20)
14.#13 pc 000000000059c8e8 /apex/com.android.runtime/lib64/libart.so (MterpInvokeInterface+1740)
15.#14 pc 0000000000131a14 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_interface+20)
16.#15 pc 000000000059d484 /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1168)
17.#16 pc 0000000000131914 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
18.#17 pc 000000000059d484 /apex/com.android.runtime/lib64/libart.so (MterpInvokeDirect+1168)
19.#18 pc 0000000000131914 /apex/com.android.runtime/lib64/libart.so (mterp_op_invoke_direct+20)
20.#19 pc 00000000002d60bc /apex/com.android.runtime/lib64/libart.so (_ZN3art11interpreterL7ExecuteEPNS_6ThreadERKNS_20CodeItemDataAccessorERNS_11ShadowFrameENS_6JValueEbb.llvm.11254168580287671421+240)
21.#20 pc 000000000058c560 /apex/com.android.runtime/lib64/libart.so (artQuickToInterpreterBridge+1012)
22.#21 pc 0000000000140468 /apex/com.android.runtime/lib64/libart.so (art_quick_to_interpreter_bridge+88)
23.#22 pc 000000000001e324 /system/framework/arm64/boot-okhttp.oat (com.android.okhttp.internal.Util.closeQuietly+52)
24.#23 pc 0000000000011894 /system/framework/arm64/boot-okhttp.oat (com.android.okhttp.ConnectionPool.cleanup+628)
25.#24 pc 0000000000010fbc /system/framework/arm64/boot-okhttp.oat (com.android.okhttp.ConnectionPool$1.run+108)
26.#25 pc 00000000002f9fe8 /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor.runWorker+984)
27.#26 pc 00000000002f7650 /system/framework/arm64/boot.oat (java.util.concurrent.ThreadPoolExecutor$Worker.run+64)
28.#27 pc 00000000001a50b8 /system/framework/arm64/boot.oat (java.lang.Thread.run+72)
29.#28 pc 0000000000137334 /apex/com.android.runtime/lib64/libart.so (art_quick_invoke_stub+548)
30.#29 pc 0000000000169f00 /apex/com.android.runtime/lib64/libart.so (_ZN3art9ArtMethod6InvokeEPNS_6ThreadEPjjPNS_6JValueEPKc+244)
31.#30 pc 00000000004ac900 /apex/com.android.runtime/lib64/libart.so (_ZN3art12_GLOBAL__N_118InvokeWithArgArrayERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_9ArtMethodEPNS0_8ArgArrayEPNS_6JValueEPKc+104)
32.#31 pc 00000000004ad994 /apex/com.android.runtime/lib64/libart.so (_ZN3art35InvokeVirtualOrInterfaceWithJValuesERKNS_33ScopedObjectAccessAlreadyRunnableEP8_jobjectP10_jmethodIDPK6jvalue+416)
33.#32 pc 00000000004ed8b4 /apex/com.android.runtime/lib64/libart.so (_ZN3art6Thread14CreateCallbackEPv+1176)
34.#33 pc 00000000000cd8a0 /apex/com.android.runtime/lib64/bionic/libc.so (_ZL15__pthread_startPv+36)
35.#34 pc 00000000000702b0 /apex/com.android.runtime/lib64/bionic/libc.so (__start_thread+64)
36.at com.android.org.conscrypt.NativeCrypto.SSL_get_time(Native method)
37.at com.android.org.conscrypt.NativeSsl.getTime(NativeSsl.java:101)
38.at com.android.org.conscrypt.ActiveSession.isValid(ActiveSession.java:148)
39.at com.android.org.conscrypt.ActiveSession.getSessionContext(ActiveSession.java:67)
40.at com.android.org.conscrypt.SessionSnapshot.<init>(SessionSnapshot.java:46)
41.at com.android.org.conscrypt.ConscryptFileDescriptorSocket.transitionTo(ConscryptFileDescriptorSocket.java:1168)
42.at com.android.org.conscrypt.ConscryptFileDescriptorSocket.close(ConscryptFileDescriptorSocket.java:970)
43.at com.android.okhttp.internal.Util.closeQuietly(Util.java:91)
44.at com.android.okhttp.ConnectionPool.cleanup(ConnectionPool.java:288)
45.at com.android.okhttp.ConnectionPool$1.run(ConnectionPool.java:99)
46.at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
47.at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
48.at java.lang.Thread.run(Thread.java:919)

**Comment by yschimke** [comment]
You should raise this with Conscrypt.

**Comment by ArchanaPrabhu** [comment]
Looks related to this issue :
https://github.com/google/conscrypt/issues/1131
