### ISSUE TITLE
FATAL EXCEPTION crashes Android app

### ISSUE THREAD

**Issue by TelephoneTan** [square/okhttp#7941]
I am using okhttp `com.squareup.okhttp3:okhttp:4.10.0` in Android 13.0 to make an async http call, the app crashed.

I fully understand this is due to missing the INTERNET permission, but I don't understand why the app crashed. According to #1049 and #1103, it seems that the fatal exception should only be logged instead of crash the app.

Is this behavior by design or a bug?

From the debugging results, the `onFailure` callback got invoked as expected, but after that the app crashed immediately:

![image](https://github.com/square/okhttp/assets/49133394/2f8cfcbd-2acd-487e-b55b-2fe51ed4a130)

logs:

```
FATAL EXCEPTION: OkHttp Dispatcher
Process: com.guetcob.coursetable, PID: 25015
java.lang.SecurityException: Permission denied (missing INTERNET permission?)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:150)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
	at java.net.InetAddress.getAllByName(InetAddress.java:1152)
	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49)
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164)
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129)
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71)
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: android.system.GaiException: android_getaddrinfo failed: EAI_NODATA (No address associated with hostname)
	at libcore.io.Linux.android_getaddrinfo(Native Method)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222)
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133)
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135)
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103) 
	at java.net.InetAddress.getAllByName(InetAddress.java:1152) 
	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49) 
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164) 
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129) 
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71) 
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205) 
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) 
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) 
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) 
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) 
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) 
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) 
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) 
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) 
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
	at java.lang.Thread.run(Thread.java:1012) 
Caused by: android.system.ErrnoException: android_getaddrinfo failed: EPERM (Operation not permitted)
	at libcore.io.Linux.android_getaddrinfo(Native Method) 
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133) 
	at libcore.io.BlockGuardOs.android_getaddrinfo(BlockGuardOs.java:222) 
	at libcore.io.ForwardingOs.android_getaddrinfo(ForwardingOs.java:133) 
	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:135) 
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103) 
	at java.net.InetAddress.getAllByName(InetAddress.java:1152) 
	at okhttp3.Dns$Companion$DnsSystem.lookup(Dns.kt:49) 
	at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:164) 
	at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:129) 
	at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:71) 
	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205) 
	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106) 
	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74) 
	at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255) 
	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32) 
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95) 
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83) 
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76) 
	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109) 
	at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201) 
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517) 
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137) 
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637) 
	at java.lang.Thread.run(Thread.java:1012)
```
🙏🙏

**Comment by TelephoneTan** [comment]
the fatal exception is thrown from here:
https://github.com/square/okhttp/blob/b35852fa39fb4b1df71a13fa5807f56a8022e51a/okhttp/src/jvmMain/kotlin/okhttp3/Dns.kt#L47-L55
https://github.com/square/okhttp/blob/b35852fa39fb4b1df71a13fa5807f56a8022e51a/okhttp/src/jvmMain/kotlin/okhttp3/Dns.kt#L49

**Comment by yschimke** [comment]
We generally don't want to hide serious runtime exceptions and wrap to IOException. In this case you should add the internet permission.

If it's important for your particular casez you can wrap all of the integration points like DNS and SocketFactory to convert thesez but current behaviour is by design.
