### ISSUE TITLE
Connection fails with a timeout when using HTTP proxy specified via system proxy settings

### ISSUE THREAD

**Issue by r-smirnov** [square/okhttp#7958]
Every application that uses OkHttp fails when `java.net.useSystemProxies` system property is set:
```
Exception in thread "main" java.net.SocketTimeoutException: Connect timed out
        at java.base/java.net.SocksSocketImpl.readSocksReply(SocksSocketImpl.java:139)
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:455)
        at java.base/java.net.Socket.connect(Socket.java:609)
        at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
        at okhttp3.internal.connection.RealConnection.connectTunnel(RealConnection.kt:261)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:201)
        at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
        at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
        at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
        at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
        at okhttp.bug.App.main(App.java:15)
        Suppressed: java.net.SocketTimeoutException: Connect timed out
                ... 22 more
```
This is due to the java.net.Socket that is created with java.net.SocksSocketImpl, rather than java.net.HttpConnectSocketImpl. Removing the check for Proxy.Type.HTTP in [RealConnection](https://github.com/square/okhttp/blob/68a106d3269b0ad02136a1bfa81c07a6c006fffe/okhttp/src/main/kotlin/okhttp3/internal/connection/RealConnection.kt#L287) results in the socket with correct implementation type and fixes the issue.

**Comment by yschimke** [comment]
Presumably this is only failing if you have a SOCKS5 proxy configured?

What is this returning for you?

```
  val target = ProxySelector.getDefault().select(("https://google.com".toHttpUrl().toUri()))
  println(target)
```

Have you made the following change?

```
    val rawSocket = when (route.proxy.type()) {
      Proxy.Type.DIRECT -> route.address.socketFactory.createSocket()!! // removed , Proxy.Type.HTTP
      else -> Socket(route.proxy)
    }
```

**Comment by lukasz-jarocki-sonarsource** [comment]
Hi,

I have HTTP (not SOCKS5) proxy running on machine and I set it as system proxy on my windows. Anytime I set in Java VM `java.net.useSystemProxies` the OkHttp request fails with the same exact stacktrace as linked in the OP post.
