### ISSUE TITLE
java.lang.NoSuchFieldError: Companion

### ISSUE THREAD

**Issue by firingsloth** [square/okhttp#7977]
ERROR:
java.lang.NoSuchFieldError: Companion
	at okhttp3.internal.Util.<clinit>(Util.kt:70)
	at okhttp3.Dispatcher.promoteAndExecute(Dispatcher.kt:243)
	at okhttp3.Dispatcher.setMaxRequests(Dispatcher.kt:52)

 I have checked mvn dependency tree.Do you know other reason that could cause it?
mvn dependency:tree
[INFO] +- com.squareup.okhttp3:okhttp:jar:4.11.0:compile
[INFO] |  +- com.squareup.okio:okio:jar:3.2.0:compile
[INFO] |  |  \- com.squareup.okio:okio-jvm:jar:3.2.0:compile
[INFO] |  +- org.jetbrains.kotlin:kotlin-stdlib:jar:1.6.20:compile
[INFO] |  |  +- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.6.20:compile
[INFO] |  |  \- org.jetbrains:annotations:jar:13.0:compile
[INFO] |  \- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.6.20:compile
[INFO] |     \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.6.20:compile

**Comment by lizhen789** [comment]
跟你一模一样

**Comment by anguslee-wse** [comment]
Include [okio](https://central.sonatype.com/artifact/com.squareup.okio/okio) in your dependency.
