### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException: okhttp3.Cache$Entry.readCertificateList

### ISSUE THREAD

**Issue by Anigif** [square/okhttp#7978]
We have a few Android TV users (don't now it's related to Android TV) that gets a crash in a custom interceptor we have. Its not that many users but they are however getting this crash _a lot_. 

This is an example of the stacktrace after we call `proceed()`, so I'm sure if we can do anything in our end (other than catching the exception): 
```
Fatal Exception: java.lang.NullPointerException:
       at okhttp3.Cache$Entry.readCertificateList(Cache.kt:612)
       at okhttp3.Cache$Entry.<init>(Cache.kt:534)
       at okhttp3.Cache.get$okhttp(Cache.kt:178)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:47)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       ...
```

**Comment by yschimke** [comment]
Similar to https://github.com/square/okhttp/issues/6260

**Comment by yschimke** [comment]
I can't see how it can happen, but even a corrupted cache file, causing base64 decode should fail, should be a IOException.  

Will fix and backport to 4.x

**Comment by Anigif** [comment]
Android TVs often work in mysterious ways! But sounds awesome you'll make a fix.

I forgot to mention at first, but in our project is using Retrofit 2.9.0 and have a reference to OkHttp 4.11.0 as well - not sure if that makes a difference.
