### ISSUE TITLE
Strict mode UntaggedSocketViolation on Android

### ISSUE THREAD

**Issue by simon-st** [square/okhttp#8064]
Hi. I am getting an `UntaggedSocketViolation` on every OkHttp call on Android with StrictMode enabled

Enable strict mode in Application file.
```
StrictMode.setThreadPolicy(
    ThreadPolicy.Builder()
        .detectAll()
        .penaltyLog()
        .build()
)
StrictMode.setVmPolicy(
    VmPolicy.Builder()
        .detectAll()
        .penaltyLog()
        .build()
)
```

Example ViewModel to provoke the warning:
```
class TestViewModel: ViewModel() {

    private val client = OkHttpClient()

    fun onButtonClick() {
        viewModelScope.launch(Dispatchers.IO) {
            Log.e("Test", "onButtonClick()")

            // This would fix the warning, but is impractical in a real project
            TrafficStats.setThreadStatsTag(123)

            val request = Request.Builder()
                .url("https://google.com")
                .build()

            val response = client.newCall(request).execute()
            val responseString = response.body?.string()
            Log.e("Test", "onButtonClick() ... $responseString")
        }
    }
}
```

Warning output:
```
tagSocket(104) with statsTag=0xffffffff, statsUid=-1
StrictMode policy violation: android.os.strictmode.UntaggedSocketViolation: Untagged socket detected; use TrafficStats.setTrafficStatsTag() to track all network usage
    at android.os.StrictMode.onUntaggedSocket(StrictMode.java:2250)
    at android.os.StrictMode.noteUntaggedSocket(StrictMode.java:2699)
    at android.net.TrafficStats$SocketTagger.tag(TrafficStats.java:255)
    at libcore.io.BlockGuardOs.tagSocket(BlockGuardOs.java:55)
    at libcore.io.BlockGuardOs.socket(BlockGuardOs.java:404)
    at libcore.io.ForwardingOs.socket(ForwardingOs.java:821)
    at libcore.io.IoBridge.socket(IoBridge.java:840)
    at java.net.PlainSocketImpl.socketCreate(PlainSocketImpl.java:128)
    at java.net.AbstractPlainSocketImpl.create(AbstractPlainSocketImpl.java:128)
    at java.net.Socket.createImpl(Socket.java:514)
    at java.net.Socket.getImpl(Socket.java:577)
    at java.net.Socket.setSoTimeout(Socket.java:1203)
    at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:293)
    at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
    at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
    at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
    at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
    at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
    at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
    at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
    at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
    at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
    at com.mytestapplication.TestViewModel$onButtonClick$1.invokeSuspend(MainActivity.kt:85)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
    at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
    at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
    at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)
```

I know I could remvove the warning with `TrafficStats.setThreadStatsTag()` but that is impractical in a real project as the actual network call happens in a pure JVM module without access to `TrafficStats`. I feel like there should be a way through OkHttp to set the stats tag, or one should be set automatically.

**Comment by simon-st** [comment]
never mind, reading through #3537 provides some workarounds. Not ideal, but it should work.
