### ISSUE TITLE
Interceptor's request.body().writeTo(buffer); causes "java.net.ProtocolException: unexpected end of stream" with MultipartBody Post

### ISSUE THREAD

**Issue by i-infra** [square/okhttp#8138]
I'm POSTing a MultipartBody using OkHttpClient - wire protocol is Http2.

With

```
        HttpLoggingInterceptor httpLoggingInterceptor = new HttpLoggingInterceptor();

        httpLoggingInterceptor.setLevel(HttpLoggingInterceptor.Level.BODY);
```

Every attempt to POST the MultipartBody fails with variations of `java.net.ProtocolException: unexpected end of stream`

As per the following traceback:

```Caused by: java.net.ProtocolException: unexpected end of stream
        at okhttp3.internal.connection.Exchange$RequestBodySink.close(Exchange.kt:244)
        at okio.RealBufferedSink.close(RealBufferedSink.kt:287)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:63)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:221)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at org.asamk.signal.manager.config.ServiceConfig.lambda$getServiceEnvironmentConfig$0(ServiceConfig.java:46)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall.execute(RealCall.kt:154)
````

A workaround I have implemented and tested is to have an interceptor write the body to a buffer and then create a new Request with the MultipartBody represented instead as raw bytes. This is logged fine and completes fine, suggesting that somewhere inside MultipartBody is a hidden (unlabeled?) oneshot or oneshot-like abstraction.

An implementation of this workaround can be found at https://github.com/firedexofficial/signal-cli/blob/bad99253bc52bd16ae9065ed9f82bf62a952a2d9/lib/src/main/java/org/asamk/signal/manager/config/FixHttpLoggingInterceptor.java

Adding this interceptor before HttpLoggingInterceptor enables the request to complete successfully. 

This resembles https://github.com/square/okhttp/issues/2738 in terms of issue/traceback and I see folks in the comments using HttpLoggingInterceptor.  See also: https://github.com/square/okhttp/issues/7779 and https://github.com/wordpress-mobile/WordPress-Android/issues/5690 and https://github.com/square/okhttp/issues/2738#issuecomment-515960916. 

This appears to be at least a footgun with HttpLoggingInterceptor (incompatible with MultipartBody POSTs) and possibly a subtle implementation issue with OkHttp. None of the other workarounds (connection: close / retry on failure) worked, but setting "HttpLoggingInterceptor.Level.HEADERS" instead of BODY did the job, cluing me into where the issue existed.

**Comment by i-infra** [comment]
version: com.squareup.okhttp3:okhttp:4.11.0

**Comment by yschimke** [comment]
I think it's because one of the Parts of the MultipartBody is oneshot.  So I've put up a PR to check for this, which will stop logging.

Can you confirm that some part of the form is one shot in your case?

**Comment by yschimke** [comment]
Hopefully this should be fixed in next 5.0 release.  I'll discuss with @swankjesse whether to backport to 4.x. 

But if you are using that workaround, it might be simpler to ensure you are not using OneShot parts. Or if you are not, then we can reopen.

**Comment by jimmy-jos** [comment]
@yschimke @i-infra 
I am facing this issue intermittently. When i use HttpLoggingInterceptor, its not happening or is very difficult to reproduce. 

I am not really sure what is OneShot part. 

Can you please let me know what is the workaround?

is it to do this:
```

Request request = chain.request();
        Buffer buffer = new Buffer();
        Request newRequest;
        if ( request.body() != null ) {
            request.body().writeTo(buffer);
            newRequest = new Request(request.url(), request.method(), request.headers(), RequestBody.create(buffer.readByteArray(), request.body().contentType()), request.getTags$okhttp());
        }
        else {
            newRequest = new Request(request.url(), request.method(), request.headers(), RequestBody.create(buffer.readByteArray()), request.getTags$okhttp());
        }
        return chain.proceed(newRequest);
```

**Comment by reda-alaoui** [comment]
@yschimke can the fix be backported to 4.x? I am using retrofit 2 and I don't think retrofit 2 or 3 is compatible with okhttp 5.

**Comment by reda-alaoui** [comment]
> [@yschimke](https://github.com/yschimke) can the fix be backported to 4.x? I am using retrofit 2 and I don't think retrofit 2 or 3 is compatible with okhttp 5.

Forget it, looks like upgrading to latest retrofit and okhttp was easy peasy :)
