### ISSUE TITLE
Crash on android.system.ErrnoException

### ISSUE THREAD

**Issue by alishari** [square/okhttp#8153]
I ran into a Crashlytics error:

```
Caused by android.system.ErrnoException
isConnected failed: ECONNABORTED (Software caused connection abort)
libcore.io.IoBridge.isConnected (IoBridge.java:334)
libcore.io.IoBridge.connectErrno (IoBridge.java:237)
libcore.io.IoBridge.connect (IoBridge.java:179)
java.net.PlainSocketImpl.socketConnect (PlainSocketImpl.java:142)
java.net.AbstractPlainSocketImpl.doConnect (AbstractPlainSocketImpl.java:390)
java.net.AbstractPlainSocketImpl.connectToAddress (AbstractPlainSocketImpl.java:230)
java.net.AbstractPlainSocketImpl.connect (AbstractPlainSocketImpl.java:212)
java.net.SocksSocketImpl.connect (SocksSocketImpl.java:436)
java.net.Socket.connect (Socket.java:646)
okhttp3.internal.platform.Platform.connectSocket (Platform.kt:128)
okhttp3.internal.connection.RealConnection.connectSocket (RealConnection.kt:295)
okhttp3.internal.connection.RealConnection.connect (RealConnection.kt:207)
okhttp3.internal.connection.ExchangeFinder.findConnection (ExchangeFinder.kt:226)
okhttp3.internal.connection.ExchangeFinder.findHealthyConnection (ExchangeFinder.kt:106)
okhttp3.internal.connection.ExchangeFinder.find (ExchangeFinder.kt:74)
okhttp3.internal.connection.RealCall.initExchange$okhttp (RealCall.kt:255)
okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.kt:32)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.kt:95)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.kt:83)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.kt:76)
okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt:109)
okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp (RealCall.kt:201)
okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt:517)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1137)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:637)
java.lang.Thread.run (Thread.java:1012)
```

It looks like we might need to include ErrnoException in this part of the code:
https://github.com/square/okhttp/blob/e285d4e68b235b790cfade185532c0777e927803/okhttp/src/main/kotlin/okhttp3/internal/platform/Platform.kt#L138

```
  @Throws(IOException::class)
  open fun connectSocket(socket: Socket, address: InetSocketAddress, connectTimeout: Int) {
    socket.connect(address, connectTimeout)
  }
```

I cannot reproduce the issue so not sure how can I help you but seems others raised this issue before but didn't get enough attention.

**Comment by yschimke** [comment]
In other cases it's wrapped in an IOException or SecurityException, both of which are handled appropriately.  Given the "caused by", I suspect it's the same here. Can you print the full stacktrace?

```
Caused by android.system.ErrnoException
isConnected failed: ECONNABORTED (Software caused connection abort)
libcore.io.IoBridge.isConnected (IoBridge.java:334)
```

**Comment by alishari** [comment]
Yeah, So it is the app responsibility to handle it but not clear where this issue raised in the codebase. I would love to help to improve how OkHttp report this issue if we can improve the report from OkHttp to make it more clear. Any idea how to improve it?
```
Fatal Exception: java.net.ConnectException: Failed to connect to [URL]
       at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:297)
       at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)

Caused by java.net.ConnectException: failed to connect to [URL] (port 443) from X (port 34844) after 10000ms: isConnected failed: ECONNABORTED (Software caused connection abort)
       at libcore.io.IoBridge.isConnected(IoBridge.java:347)
       at libcore.io.IoBridge.connectErrno(IoBridge.java:237)
       at libcore.io.IoBridge.connect(IoBridge.java:179)
       at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
       at java.net.Socket.connect(Socket.java:646)
       at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
       at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
       at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)

Caused by android.system.ErrnoException: isConnected failed: ECONNABORTED (Software caused connection abort)
       at libcore.io.IoBridge.isConnected(IoBridge.java:334)
       at libcore.io.IoBridge.connectErrno(IoBridge.java:237)
       at libcore.io.IoBridge.connect(IoBridge.java:179)
       at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
       at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
       at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
       at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
       at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
       at java.net.Socket.connect(Socket.java:646)
       at okhttp3.internal.platform.Platform.connectSocket(Platform.kt:128)
       at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.kt:295)
       at okhttp3.internal.connection.RealConnection.connect(RealConnection.kt:207)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:226)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012)
```

**Comment by yschimke** [comment]
There isn't really any one place.

`Call.execute()` could fail.
`Call.enqueue()` could pass this to your callback.
Reading from the Response could fail.

You should be handling network errors, which this is, in your network code. Or use something like ktor or retrofit, that will wrap OkHttp and do more of this handling for you.

**Comment by yschimke** [comment]
If you are still stuck, post a repro to stackoverflow. But no action here.
