### ISSUE TITLE
StrictMode error: Missing close() on Sink used in FileSystem.isCivilized()

### ISSUE THREAD

**Issue by Wrywulf** [square/okhttp#8186]
I have enabled StrictMode in my Android app and I fairly frequently run across this stack trace:

```
StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
         at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1994)
         at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:336)
         at java.io.FileOutputStream.finalize(FileOutputStream.java:500)
         at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:339)
         at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:324)
         at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:300)
         at java.lang.Daemons$Daemon.run(Daemons.java:145)
         at java.lang.Thread.run(Thread.java:1012)
        Caused by: java.lang.Throwable: Explicit termination method 'close' not called
         at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:288)
         at dalvik.system.CloseGuard.open(CloseGuard.java:257)
         at java.io.FileOutputStream.<init>(FileOutputStream.java:253)
         at okio.Okio__JvmOkioKt.sink(JvmOkio.kt:174)
         at okio.Okio.sink(Unknown Source:1)
         at okio.Okio__JvmOkioKt.sink$default(JvmOkio.kt:174)
         at okio.Okio.sink$default(Unknown Source:1)
         at okio.JvmSystemFileSystem.sink(JvmSystemFileSystem.kt:101)
         at okio.ForwardingFileSystem.sink(ForwardingFileSystem.kt:206)
         at okhttp3.internal.cache.DiskLruCache$fileSystem$1.sink(DiskLruCache.kt:108)
         at okio.FileSystem.sink(FileSystem.kt:75)
         at okhttp3.internal._UtilCommonKt.isCivilized(-UtilCommon.kt:305)
         at okhttp3.internal.cache.DiskLruCache.initialize(DiskLruCache.kt:240)
         at okhttp3.internal.cache.DiskLruCache.get(DiskLruCache.kt:437)
         at okhttp3.Cache.get$okhttp(Cache.kt:176)
         at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:48)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
         at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
         at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
         at com.unwire.mobility.app.cache.okhttp.UseCacheWhenOfflineInterceptor.intercept(UseCacheWhenOfflineInterceptor.kt:23)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
         at com.unwire.ssg.retrofit2.SsgHttpErrorInterceptor.intercept(SsgHttpErrorInterceptor.kt:51)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
         at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:233)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
         at com.unwire.mobility.app.data.api.AcceptLanguageHeaderInterceptor.intercept(AcceptLanguageHeaderInterceptor.kt:37)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
         at com.unwire.mobility.app.data.api.ApiMetaDataInterceptor.intercept(ApiMetaDataInterceptor.kt:12)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
         at com.unwire.ssg.signer.okhttp.OkHttpSigner.intercept(OkHttpSigner.java:92)
         at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
         at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
         at okhttp3.internal.connection.RealCall.execute(RealCall.kt:158)
         at retrofit2.OkHttpCall.execute(OkHttpCall.java:204)
         at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:46)
         at io.reactivex.Observable.subscribe(Observable.java:12284)
         at retrofit2.adapter.rxjava2.ResultObservable.subscribeActual(ResultObservable.java:35)
         at io.reactivex.Observable.subscribe(Observable.java:12284)
         at io.reactivex.internal.operators.observable.ObservableSingleSingle.subscribeActual(ObservableSingleSingle.java:35)
         at io.reactivex.Single.subscribe(Single.java:3666)
```

I don't immediately see what could be done differently in my own code, as the error seems to be related to a resource used inside `DiskLruCache`'s initialize():

```
fun initialize() {
...
    civilizedFileSystem = fileSystem.isCivilized(journalFileBackup)
...
}

internal fun FileSystem.isCivilized(file: Path): Boolean {
  sink(file).use {
    try {
      delete(file)
      return true
    } catch (_: IOException) {
    }
  }
  delete(file)
  return false
}
```

Despite the `.use {}` it seems that the `Sink` opened by `isCivilized` is not guaranteed to be closed in all cases. Which is weird

Does this make sense?

**Comment by yschimke** [comment]
It sounds like this bug - https://github.com/square/okio/pull/1188/files

**Comment by Wrywulf** [comment]
Thanks for following up.

That bugfix definitely looks like it could match what I'm seeing.

But afaict I'm currently already using okio 3.3.0 (verified with gradle dependencyInsight for the gradle :app module). And I'm using OkHttp 5.0.0-alpha.11.

**Comment by yschimke** [comment]
Alpha 11 was using 3.2.0, and this code is inlined.

https://github.com/square/okhttp/blob/parent-5.0.0-alpha.11/gradle/libs.versions.toml

Can you upgrade to 5.0.0-alpha.11 and check if still happening?

**Comment by Wrywulf** [comment]
Thanks! I upgraded to alpha.12 and I no longer see that strict mode error 👍 

However, I still see this one (was also there before, but I have not yet reported as an issue to this github):

```
StrictMode policy violation: android.os.strictmode.LeakedClosableViolation: A resource was acquired at attached stack trace but never released. See java.io.Closeable for information on avoiding resource leaks.
       at android.os.StrictMode$AndroidCloseGuardReporter.report(StrictMode.java:1994)
       at dalvik.system.CloseGuard.warnIfOpen(CloseGuard.java:336)
       at java.io.FileInputStream.finalize(FileInputStream.java:508)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:339)
       at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:324)
       at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:300)
       at java.lang.Daemons$Daemon.run(Daemons.java:145)
       at java.lang.Thread.run(Thread.java:1012)
      Caused by: java.lang.Throwable: Explicit termination method 'close' not called
       at dalvik.system.CloseGuard.openWithCallSite(CloseGuard.java:288)
       at dalvik.system.CloseGuard.open(CloseGuard.java:257)
       at java.io.FileInputStream.<init>(FileInputStream.java:176)
       at okio.Okio__JvmOkioKt.source(JvmOkio.kt:181)
       at okio.Okio.source(Unknown Source:1)
       at okio.JvmSystemFileSystem.source(JvmSystemFileSystem.kt:96)
       at okio.ForwardingFileSystem.source(ForwardingFileSystem.kt:200)
       at okhttp3.internal.cache.DiskLruCache$Entry.newSource(DiskLruCache.kt:1044)
       at okhttp3.internal.cache.DiskLruCache$Entry.snapshot$okhttp(DiskLruCache.kt:1025)
       at okhttp3.internal.cache.DiskLruCache.get(DiskLruCache.kt:445)
       at okhttp3.Cache.get$okhttp(Cache.kt:190)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:48)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:84)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:65)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.unwire.mobility.app.cache.okhttp.CacheHitLoggingInterceptor.intercept(CacheHitLoggingInterceptor.kt:19)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.logging.HttpLoggingInterceptor.intercept(HttpLoggingInterceptor.kt:234)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.unwire.mobility.app.data.api.ApiMetaDataInterceptor.intercept(ApiMetaDataInterceptor.kt:12)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.unwire.mobility.app.cache.DiskOkHttpMediaCache$FilterNonMediaResponsesInterceptor.intercept(DiskOkHttpMediaCache.kt:118)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.unwire.mobility.app.cache.okhttp.UseCacheWhenOfflineInterceptor.intercept(UseCacheWhenOfflineInterceptor.kt:23)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:205)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:543)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
       at java.lang.Thread.run(Thread.java:1012) 
```

In your opinion, should I raise this as another bug?

Again, I don't immediately see what the problem is in my own code, but in this case I'm not as sure as before.

It seems the cacheCandidate body is not being closed properly:

```
class CacheInterceptor(internal val cache: Cache?) : Interceptor {

  @Throws(IOException::class)
  override fun intercept(chain: Interceptor.Chain): Response {
    val call = chain.call()
    val cacheCandidate = cache?.get(chain.request())
...
}

```

**Comment by yschimke** [comment]
This generally represents your app not closing the response.  I'd check that.  Perhaps add a Call listener and increment a counter on each CallStart vs CallEnd+CallFailed.

But without a repro, we can't do much more.

**Comment by yschimke** [comment]
Happy to reopen with a repro showing happening with all responses closed.
