### ISSUE TITLE
EOF exception while trying to close the websocket

### ISSUE THREAD

**Issue by not9cb** [square/okhttp#8262]
Hello,

I was trying to connect to a websocket using the api (tested on version 4.12.0 and 5.0.0-alpha.12, also using a proxy), but for some reason when I try to close the socket after I get a certain message from the socket an exception is thrown and the socket is not closed (onClosed nor onClosing method is being called).

This is the error:

`java.io.EOFException
	at okio.RealBufferedSource.require(RealBufferedSource.kt:202)
	at okio.RealBufferedSource.readByte(RealBufferedSource.kt:212)
	at okhttp3.internal.ws.WebSocketReader.readHeader(WebSocketReader.kt:119)
	at okhttp3.internal.ws.WebSocketReader.processNextFrame(WebSocketReader.kt:102)
	at okhttp3.internal.ws.RealWebSocket.loopReader(RealWebSocket.kt:293)
	at okhttp3.internal.ws.RealWebSocket$connect$1.onResponse(RealWebSocket.kt:195)
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
`

This is how I tried to close it (any combination of codes and messages didn't work):
`webSocket.close(1010, "Disconnected");`

**Comment by JakeWharton** [comment]
Sounds like the server is closing the socket without acknowledging the close in violation of the protocol. An EOF is what I'd expect here, as the reader is waiting for the close acknowledgement (and any other frames which precede it) but it got a socket closure instead.

**Comment by not9cb** [comment]
So if I understood correctly, the server closes the socket, but doesn't inform me (the client) of the closure and then the EOF exception is thrown. Would it be possible to catch that exception and call the onClosed method anyways since the websocket was _technically_ closed? I've used another API before and it seemed to work fine, but it didn't support proxies so I switched to this one.

**Comment by yschimke** [comment]
I don't think we want to silently swallow such as error. But it's still an IOException, you can recover from this as appropriate.

**Comment by not9cb** [comment]
Understandable, I've handled the exception inside the onFailure method and called the onClosed method manually, it seems to work fine. Also, just to make sure, can I just get rid of the websocket object once I'm done with it or do I need to do anything else since there was an exception thrown?

**Comment by swankjesse** [comment]
You don’t need to do anything after `onFailure()`. Resources are cleaned up.
