### ISSUE TITLE
Potential failure on CallServerInterceptor if writeRequestHeader fails

### ISSUE THREAD

**Issue by gdrehmer** [square/okhttp#8283]
Unfortunately this bug is hard to replicate and to create a failing test. 
But I hope it still gets attention.

We've noticed that there is a big number of crashes in our customer base after upgrading from OkHttp 4.9.3 to version 4.12.0, as per stacktrace below.

We've also noticed a change in 4.11 could be related to that:

> Read the response even if writing the request fails (https://github.com/square/okhttp/pull/6295) (https://github.com/square/okhttp/pull/7453)

https://github.com/square/okhttp/commit/e46a200fceaa5fbd9c9278eebe9c978399bd329c

It seems that a change has been introduced in `CallServerInterceptor` which moved the `exchange.write*` operations into a `try/catch` block (I suppose by design, to fix the issue as referenced in the commit).

However, the effect of that could be that the following block, the [`exchange.readResponseHeaders`](https://github.com/square/okhttp/commit/e46a200fceaa5fbd9c9278eebe9c978399bd329c#diff-a7e9adfc4dd5b5461614c783b04cbccd4f0c7ee8693db5c361622cd149904e55R93) might be executed with `state` set to `0` (IDLE, not initalised), if the previous [`exchange.writeRequestHeaders(request)`](https://github.com/square/okhttp/commit/e46a200fceaa5fbd9c9278eebe9c978399bd329c#diff-a7e9adfc4dd5b5461614c783b04cbccd4f0c7ee8693db5c361622cd149904e55R41) operation failed for any reason  **apart from `ConnectionShutdownException`**. The `readResponseHeaders` has a guard statement which would throw an exception if `state == 0`.

I couldn't find a way which could cause the `exchange.writeRequestHeaders` call to raise an exception, but we are observing many cases (it is our top crash, affecting thousands of customers in a couple of days after rollout).

It is important to note that we also updated from Okio 3.0.0 to 3.7.0 in the same release.

## Stacktrace:
```
Exception java.lang.IllegalStateException: state: 0
  at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders (Http1ExchangeCodec.kt)
  at okhttp3.internal.connection.Exchange.readResponseHeaders (Exchange.kt)
  at okhttp3.internal.http.CallServerInterceptor.intercept (CallServerInterceptor.kt)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt)
  at okhttp3.internal.connection.ConnectInterceptor.intercept (ConnectInterceptor.kt)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt)
  at okhttp3.internal.cache.CacheInterceptor.intercept (CacheInterceptor.kt)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt)
  at okhttp3.internal.http.BridgeInterceptor.intercept (BridgeInterceptor.kt)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt)
  at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept (RetryAndFollowUpInterceptor.kt)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt)
  at my.company.SomeInterceptor 
  (...)
  at okhttp3.internal.http.RealInterceptorChain.proceed (RealInterceptorChain.kt)
  at okhttp3.internal.connection.RealCall.getREsponseWithInterceptorChain$okhttp (RealCall.kt)
  at okhttp3.internal.connection.RealCall$AsyncCall.run (RealCall.kt)
  at java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1145)
  at java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:644)
  at java.lang.Thread.run (Thread.java:1012)

```

**Comment by yschimke** [comment]
Probably a dupe of https://github.com/square/okhttp/issues/6853

**Comment by savvasenok** [comment]
Any updates on this topic? I also receive this error with almost the same stacktrace:
```
java.lang.IllegalStateException: state: 0
        at okhttp3.internal.http1.Http1ExchangeCodec.readResponseHeaders(Http1ExchangeCodec.kt:173)
        at okhttp3.internal.connection.Exchange.readResponseHeaders(Exchange.kt:110)
        at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.kt:93)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:34)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at io.sentry.okhttp.SentryOkHttpInterceptor.intercept(SentryOkHttpInterceptor.kt:110)
        at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
        at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
        at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
        at java.lang.Thread.run(Thread.java:1012)
```

**Comment by tolia-ogurt** [comment]
The same for me. I also receive this error. How I can fix this?

**Comment by jdicami** [comment]
Any solution, we are experiencing this as well.

**Comment by okaminu** [comment]
I debugged the issue locally and found that the okhttp 4.12 version handles http connections in such a way that when http request is sent and IOException is received which is caused by "broken pipe" or "connection reset by peer", the exception is not rethrown until failed request's response header's are retrieved, but access to these headers fail, because the request failed, thus rightfully throwing exception "IllegalStateException: state: 0" that is not related to original cause. There is an internal interceptor called RetryAndFollowUpInterceptor that handles failed requests by recovering or retrying, but it's invoked only if IOException is thrown. Since IOException is not thrown, the request is not retried nor recovered.
I made a fix that catches IllegalStateException and rethrows original IOException so RetryAndFollowUpInterceptor could catch it and retry/recover, the issue did not reproduce afterwards.
Commit https://github.com/okaminu/okhttp/commit/9624f1c2ec322434e98d60a0039b5cad4a71e343
Build that includes the fix https://github.com/okaminu/okhttp/releases/tag/parent-4.12.1

I tried to make a PR with the fix so it could be merged, but the 4.12.0 version that has the bug is a git tag, closest branch with the version is 4.10.0 that doesn't have the bug.

**Comment by yschimke** [comment]
We haven't been trying to catch the `IllegalStateException` so far, rather avoid it happening. Are you able to repro that specific condition?

My worry with catching the ISE, is that we don't know what state we are in.  Since we haven't fixed this so far, we may have to apply this bandaid and remove it once we have fixed the ISE root cause.

**Comment by okaminu** [comment]
> We haven't been trying to catch the `IllegalStateException` so far, rather avoid it happening. Are you able to repro that specific condition?
> 
> My worry with catching the ISE, is that we don't know what state we are in. Since we haven't fixed this so far, we may have to apply this bandaid and remove it once we have fixed the ISE root cause.
I was able to reproduce this condition by: 
1. Starting web servers A and B
2. Make the server A do a http GET request to the server B, which completes successfully
3. Restart the server B
4. Repeat the step 2, which will fail with the ISE

After the second step, server A keeps the connection open to server B, which is reset by server B after restart, thus throwing an IOException, which is caught by okhttp client and kept for rethrow until headers are read, but reading the headers fail due to state being 0. 
From what I noticed is that It seems this only affects when GET requests are made, because when request has a body, even during connection reset by peer, the state is not 0 which succeeds at passing the state check, but when request doesn't have a body, it fails on state check. I assume this is due to `okhttp3.internal.http1.Http1ExchangeCodec.writeRequest` changing the state from `STATE_IDLE` to `STATE_OPEN_REQUEST_BODY` at the end of the function, because during connection reset by peer, if the request was not GET, it succeeds at changing the  state, but when request is GET, it fails at changing the state, thus throwing ISE at later state check for state still being `STATE_IDLE`.

**Comment by yschimke** [comment]
Thanks, I'll try to make a repro in the code.  Really appreciate your pointers.

**Comment by yschimke** [comment]
Another possibly related one

https://github.com/square/okhttp/issues/8712

**Comment by yschimke** [comment]
Attempt at a fix, with a simple repro test.  https://github.com/square/okhttp/pull/8759

**Comment by SufiyanHS** [comment]
@yschimke Thank you for the fix and repro.  Do you have any rough date of when this might go live in beta?

**Comment by SufiyanHS** [comment]
@yschimke Need a small clarification from you.

I have forked Okhttp, created a branch `myOkhttp/parent-5.0.0-alpha.8` from the tag [parent-5.0.0-alpha.8](https://github.com/square/okhttp/releases/tag/parent-5.0.0-alpha.8), and then merged my changes on top of it.  This branch is currently used in my app. 

Now this particular `IllegalStateException` is the Top most crash among my users. To resolve them, I want to use your fix made in https://github.com/square/okhttp/pull/8759.   The problem is we don't have enough time to first sync our Fork with latest alpha, and then use your fix.   I was wondering if I can directly, cherrypick(or manually copy-paste) your fix without first syncing with upstream, will it cause any side-effects?

Would really appreciate  your response.

**Comment by yschimke** [comment]
I believe so. I think just this file should be enough?

https://github.com/square/okhttp/pull/8759/files#diff-2ecabb6c8b8c32f9ce552820acb8e76e2cb906aa5450bbb6b7411321117519dd

**Comment by yschimke** [comment]
5.0 released

**Comment by subgrand** [comment]
May I ask if this crash was introduced in version 4.12?
