### ISSUE TITLE
Review tests failing on windows

### ISSUE THREAD

**Issue by yschimke** [square/okhttp#8342]
https://github.com/square/okhttp/actions/runs/8580241807/job/23516850984?pr=8209

```
Execution failed for task ':okcurl:test'.
> Unexpected errors were encountered while processing test results that may result in some results being incorrect or incomplete.
   > Could not write '/127.0.0.1:55498'.
```

**Comment by yschimke** [comment]
also

```
DuplexTest > duplexWithAuthChallenge() FAILED
    java.util.concurrent.ExecutionException: okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
        at java.base/java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.base/java.util.concurrent.FutureTask.get(FutureTask.java:205)
        at mockwebserver3.internal.duplex.MockStreamHandler.awaitSuccess(MockStreamHandler.kt:118)
        at okhttp3.DuplexTest.duplexWithAuthChallenge(DuplexTest.kt:463)

        Caused by:
        okhttp3.internal.http2.StreamResetException: stream was reset: CANCEL
            at app//okhttp3.internal.http2.Http2Stream.checkOutNotClosed$okhttp(Http2Stream.kt:704)
            at app//okhttp3.internal.http2.Http2Stream$FramingSink.flush(Http2Stream.kt:633)
            at app//okio.RealBufferedSink.flush(RealBufferedSink.kt:270)
```
