### ISSUE TITLE
Cannot instantiate MockWebServer on alpha 14​: java.lang.NoClassDefFoundError: okhttp3/internal/_UtilJvmKt

### ISSUE THREAD

**Issue by edysli** [square/okhttp#8374]
Upgrading from 5.0.0-alpha.12 to 5.0.0-alpha.14 makes our tests fail with java.lang.NoClassDefFoundError: okhttp3/internal/_UtilJvmKt.

Example test to reproduce
```java
import mockwebserver3.MockWebServer;
import org.junit.jupiter.api.Test;

class MockWebServerTest {
    @Test
    void create() {
        new MockWebServer();
    }
}
```
fails with:
```
java.lang.NoClassDefFoundError: okhttp3/internal/_UtilJvmKt
	at mockwebserver3.MockWebServer.<init>(MockWebServer.kt:105)
	at MockWebServerTest.create(MockWebServerTest.java:9)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ClassNotFoundException: okhttp3.internal._UtilJvmKt
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 5 more
```

I've also noticed that the transitive dependencies differ between 5.0.0-alpha.12 and 5.0.0-alpha.14. Maybe the cause lies there...
```
+- com.squareup.okhttp3:mockwebserver3-junit5:jar:5.0.0-alpha.12:test
|  +- com.squareup.okhttp3:mockwebserver3:jar:5.0.0-alpha.12:test
|  |  \- com.squareup.okhttp3:okhttp-jvm:jar:5.0.0-alpha.12:test
|  |     \- com.squareup.okio:okio-jvm:jar:3.7.0:test
|  \- org.jetbrains.kotlin:kotlin-stdlib:jar:1.9.23:test
|     \- org.jetbrains:annotations:jar:13.0:test
```
```
+- com.squareup.okhttp3:mockwebserver3-junit5:jar:5.0.0-alpha.14:test
|  +- com.squareup.okhttp3:mockwebserver3:jar:5.0.0-alpha.14:test
|  |  \- com.squareup.okhttp3:okhttp:jar:4.12.0:test
|  |     +- com.squareup.okio:okio:jar:3.6.0:test
|  |     |  \- com.squareup.okio:okio-jvm:jar:3.6.0:test
|  |     |     \- org.jetbrains.kotlin:kotlin-stdlib-common:jar:1.9.23:test
|  |     \- org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar:1.9.23:test
|  |        \- org.jetbrains.kotlin:kotlin-stdlib-jdk7:jar:1.9.23:test
|  \- org.jetbrains.kotlin:kotlin-stdlib:jar:1.9.23:test
|     \- org.jetbrains:annotations:jar:13.0:test
```

**Comment by yschimke** [comment]
OkHttp 4.12 looks broken. Are you saying alpha.14 is pulling that in?

**Comment by yschimke** [comment]
https://repo1.maven.org/maven2/com/squareup/okhttp3/mockwebserver3/5.0.0-alpha.14/mockwebserver3-5.0.0-alpha.14.pom

Looks fine, so make sure you aren't pinning to 4.12.0

**Comment by edysli** [comment]
Indeed, you are correct: I have Spring Boot pinning OkHttp to 4.12.0 on my project. Sorry for the noise! :worried: 
Running `mvn dependency:tree` with `-Dverbose=true` would have revealed this.
