### ISSUE TITLE
TaskRunner's concurrent performance exhibits a significant decline in case of poor networks conditions

### ISSUE THREAD

**Issue by bringyou** [square/okhttp#8388]
Our server needs to call some external API, and the stablity of API providers is quite poor and not reliable.
And we found that during instances of network fluctuation, okHttp's internal `TaskRunner` will cause so many threads keep waiting for condition,  **finally resulting in all threads that have attempted HTTP calls becoming suspended**. We can check the jstack pic below
<img width="1375" alt="image" src="https://github.com/square/okhttp/assets/25130803/79790731-555d-4eb2-b411-606194d9a330">
After debugging we found that all `OkHttpClient` uses `TaskRunner.INSTANCE` [by the default](https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/OkHttpClient.kt#L266).
And nearly every method in `TaskRunner` [acquire a instance level lock](https://github.com/square/okhttp/blob/master/okhttp/src/main/kotlin/okhttp3/internal/concurrent/TaskRunner.kt).
**In another word,  all instances of `OkHttpClient` configured as default will competing for the same lock instance** in some scenarios, especially when external's network is poor and not reliable.
Is there any plan to improve the concurrent performance of `TaskRunner`? e.g.  use atomic values rather than ReentrantLock

**Comment by bringyou** [comment]
How to reproduce: calling a external API which can only serve limited tcp and takes a long time to create each tcp

**Comment by yschimke** [comment]
Can you show a stack trace or the thread that holds the lock?

**Comment by yschimke** [comment]
Are you sure those stacktraces aren't just the threads waiting for work to do?

Can you point to other profiling showing the slowdown?

As far as locks vs synchronised. I looked at this recently https://github.com/square/okhttp/issues/8366

It seems most detailed investigations show for contended work using Locks is the more performant option. So before switching to synchronized, do you have some links or benchmarks showing the benefit of synchronized?

**Comment by swankjesse** [comment]
This particular lock is not expected to be held for more than a few cycles – every acquire reads & writes a few lock-guarded fields and then releases the lock.

But under highly-concurrent use, the fact that we’re using locking at all is likely to cause some contention.

Can you tell me how many concurrent calls are you making?

If it’s not very many (say, 10 or fewer) and you’re seeing this problem, then it’s likely we’ve got a bug in our implementation. We’re holding the lock longer than we’re expecting to.

If you’re doing lots of concurrent calls and this lock is a bottleneck, then I think we should invest in find getting a lock-free alternative to TaskRunner; either by writing one or by using something else in the JDK.

**Comment by bringyou** [comment]
@yschimke  Hi ,this is the full stacktrace , we can see that threads were blocked at `TaskRunner.runTask` and waiting for lock.
[jstatck-2.txt](https://github.com/square/okhttp/files/15137561/jstatck-2.txt)
(running on okhttpclient alpha-14)
> 	at java.util.concurrent.locks.ReentrantLock$Sync.lock(java.base@21/ReentrantLock.java:153)
> 	at java.util.concurrent.locks.ReentrantLock.lock(java.base@21/ReentrantLock.java:322)
> 	at okhttp3.internal.concurrent.TaskRunner.runTask(TaskRunner.kt:126)

**Comment by bringyou** [comment]
> Can you tell me how many concurrent calls are you making?
> 
> If it’s not very many (say, 10 or fewer) and you’re seeing this problem, then it’s likely we’ve got a bug in our implementation. We’re holding the lock longer than we’re expecting to.
Hi, @swankjesse it's about 4 concurrent calls. But as mentioned before, the network of external server is not stable and reliable, sometimes the server will take a long time to ack TCP.

**Comment by yschimke** [comment]
Thanks for the stacktrace, it's really helpful. Apologies for not taking this so seriously initially, it does look like a legit issue.

The move from synchronized to ReentrantLock, does lose us the Thread dump info of who holds the lock.  I can't see any thread in your trace that would have the lock, and is blocked.

I can however trivially reproduce what you see, not by slowdown, but by taking a lock and just not releasing it. but it sounds like that is not what you see.

I'll try to reproduce this with some additional tracing and socket delays. The atomic option would be to give you a slightly tweaked build with some tracing to capture the thread that has the lock at these times.

**Comment by yschimke** [comment]
I'm not seeing something concrete.  In the creative testing I'm doing, the two things holding locks and taking a non trivial amount of time are

TaskRunner.awaitTaskToRun 
Http2Connection.applyAndAckSettings

I'll see if I can work out where it's going.

**Comment by yschimke** [comment]
RealBackend.execute seems to be occasionally taking 1-3 ms on my laptop. But I'm really not confident here, or what I'm seeing.

**Comment by swankjesse** [comment]
I think we might just be missing a `signal()` call on our monitor? This thread is waiting on the condition and it shouldn’t be.

```
"OkHttp TaskRunner" #1545 [255] daemon prio=5 os_prio=0 cpu=0.13ms elapsed=1117.04s tid=0x00007f8320012f40 nid=255 waiting on condition  [0x00007f82f09c8000]
   java.lang.Thread.State: WAITING (parking)
	at jdk.internal.misc.Unsafe.park(java.base@21/Native Method)
	- parking to wait for  <0x00000000f14c1118> (a java.util.concurrent.locks.ReentrantLock$NonfairSync)
	at java.util.concurrent.locks.LockSupport.park(java.base@21/LockSupport.java:221)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquire(java.base@21/AbstractQueuedSynchronizer.java:754)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.awaitNanos(java.base@21/AbstractQueuedSynchronizer.java:1761)
	at okhttp3.internal.concurrent.TaskRunner$RealBackend.coordinatorWait(TaskRunner.kt:320)
	at okhttp3.internal.concurrent.TaskRunner.awaitTaskToRun(TaskRunner.kt:229)
	at okhttp3.internal.concurrent.TaskRunner$runnable$1.run(TaskRunner.kt:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(java.base@21/ThreadPoolExecutor.java:1144)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(java.base@21/ThreadPoolExecutor.java:642)
	at java.lang.Thread.runWith(java.base@21/Thread.java:1596)
	at java.lang.Thread.run(java.base@21/Thread.java:1583)

   Locked ownable synchronizers:
	- <0x00000000f33ff110> (a java.util.concurrent.ThreadPoolExecutor$Worker)
```

**Comment by yschimke** [comment]
@swankjesse I think you know this code a lot better than I do.  I'll leave it to you. let me know if I can help.

**Comment by bringyou** [comment]
> I think we might just be missing a signal() call on our monitor? This thread is waiting on the condition and it shouldn’t be.

Maybe the `TaskRunner.coordinatorWaiting` should be annotated as `@Volatile` ?

**Comment by swankjesse** [comment]
My hypothesis is that when TaskRunner is busy, it potentially launches unnecessary threads here:

https://github.com/square/okhttp/blob/aede7c57f3e03fa1c8338268675ccc711eeeeefa/okhttp/src/main/kotlin/okhttp3/internal/concurrent/TaskRunner.kt#L208-L211

```kotlin
          // Also start another thread if there's more work or scheduling to do.
          if (multipleReadyTasks || !coordinatorWaiting && readyQueues.isNotEmpty()) {
            backend.execute(this@TaskRunner, runnable)
          }
```

These threads exit quickly, but they contend with the lock in the process. And that exacerbates the problem.

Fixing this code to start only the threads it needs should be a straightforward fix.

**Comment by Bennett-Lynch** [comment]
I encountered what appears to be the same issue and wanted to share some extra data/anecdotes. The contention around `okhttp3.internal.concurrent.TaskRunner` and `okhttp3.internal.connection.RealConnection` caused my server worker threads (all using OkHttp synchronously) to back up.

In below profile comparisons, A is healthy and B is unhealthy:

<img width="1328" alt="image" src="https://github.com/square/okhttp/assets/11811448/4bab1ab4-bbe8-432c-be3f-495826496e27">

---

<img width="1330" alt="image" src="https://github.com/square/okhttp/assets/11811448/7a23e9f1-ae8a-4530-80c1-0fd024dc5a4c">

---

<img width="1331" alt="image" src="https://github.com/square/okhttp/assets/11811448/16d90cdf-06d7-42d1-aa2e-49e4f48b1558">

---

<img width="1329" alt="image" src="https://github.com/square/okhttp/assets/11811448/1af33a71-9a85-4f98-a9cc-efeced26b704">

---

And below is a single host profile timeline:

<img width="1046" alt="image" src="https://github.com/square/okhttp/assets/11811448/5ee6db8d-10a4-4e84-84a5-9aaec6f4df7b">

---

<img width="1040" alt="image" src="https://github.com/square/okhttp/assets/11811448/139640b2-acd5-422c-b095-dc9f55407f93">

Some non-OkHttp elements are hidden for the sake of privacy but OkHttp was a significant outlier by both locking and thread creation.

@swankjesse Does this corroborate your theory? How much confidence do we have that https://github.com/square/okhttp/pull/8391 might have fixed it?

**Comment by Bennett-Lynch** [comment]
Is it possible to remove the lock usage in favor of a single `AtomicInteger` which tracks outstanding threads requested? `startAnotherThread` logic could then use CAS semantics to decrement if positive and only start a thread if the value was modified.

**Comment by swankjesse** [comment]
@Bennett-Lynch doing this with lock-free is a good idea, but I’d prefer to do that holistically. Right now we use locks throughout this thing and it’s easy to reason about this way. Mixing and matching concurrency primitives is more difficult to do well!

**Comment by bringyou** [comment]
Just share a code snippet that I am currently using to reduce the competing:
```kotlin
@file:Suppress("INVISIBLE_MEMBER", "INVISIBLE_REFERENCE")

fun dispatcherPoweredByVirtualThread() = Dispatcher(
    Executors.newThreadPerTaskExecutor(Thread.ofVirtual().name("OkHttp Dispatcher(Virtual Thread)", 0).factory())
)
fun virtualThreadClient(dispatcherCustomizer: Dispatcher.() -> Unit = {}): OkHttpClient.Builder {
    val ret = OkHttpClient.Builder()
    ret.dispatcher(dispatcherPoweredByVirtualThread().apply(dispatcherCustomizer))
    ret.taskRunner = TaskRunner(RealBackend(Thread.ofVirtual().name("OkHttp TaskRunner(Virtual Thread)", 0).factory()))
    return ret
}
```
With the power of virtual threads(since JDK21), we can easily change OkHttpClient's backend thread to virutal threads, and we can create much more instances without additional cost. And, more instances bring more `Lock` items, this reduces competing

**Comment by Bennett-Lynch** [comment]
@bringyou Nice, good option to have in our back pocket. :)

@swankjesse Understood on the need for a holistic approach. Few questions if you can spare the time:

1. If synchronous requests use the "bring your own thread" model, why are we creating extra threads? What type of tasks are being run on these threads? Is there any added value in not running them on the caller's thread?

2. Do you have an idea for what scenarios may originally contribute to delayed task execution (thus triggering the cascading failure case of more threads, causing more contention/delays)? @bringyou suggested delayed TCP connection establishment could contribute. Does that sound correct, and are there any other potential contributors?

3. Is it fair to suggest that the cascading failure mode could be triggered by either slower task execution or higher incoming rate/concurrency? 

4. How much confidence do we have that https://github.com/square/okhttp/pull/8391 might have resolved the issue? Is there any type of load testing we can run to help validate?

**Comment by swankjesse** [comment]
1. For Happy Eyeballs, we started attempting multiple connections concurrently, on different threads.
2. We also use background threads for HTTP2 PING responses, WINDOW_UPDATE responses, and similar.
3. I’m optimistic? If you’d like to try out a SNAPSHOT build and see if it addresses you problem, that’d be awesome.

**Comment by Bennett-Lynch** [comment]
Thanks, @swankjesse.

Do the different threads hold the lock during the entire connection attempt, or just until the thread starts processing?

**Comment by amihusb** [comment]
Hi! Thanks a lot for a fix. We have like 20k crashes a month, affecting 13.5k users in android app. We are using 4* version of okhttp, it is possible to have fix in 4.12.1 release or snapshot build? We will try out and provide a feedback

**Comment by yschimke** [comment]
I believe fixed with https://github.com/square/okhttp/pull/8391
