### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException: Unable to load publicsuffixes.gz resource from the classpath.

### ISSUE THREAD

**Issue by hpdx** [square/okhttp#8449]
We use okhttp version 4.12.0 ,  Android 14

Fatal Exception: java.lang.IllegalStateException: Unable to load publicsuffixes.gz resource from the classpath.
       at okhttp3.internal.publicsuffix.PublicSuffixDatabase.findMatchingRule(PublicSuffixDatabase.kt:110)
       at okhttp3.internal.publicsuffix.PublicSuffixDatabase.getEffectiveTldPlusOne(PublicSuffixDatabase.kt:72)
       at com.vshots.common.network.dnsoverhttps.DnsOverHttps$Companion.isPrivateHost$common_release(DnsOverHttps.kt:322)
       at com.vshots.common.network.dnsoverhttps.DnsOverHttps.lookup(DnsOverHttps.kt:60)
       at com.vshots.common.network.dnsoverhttps.CTDns.getInetAddressList(CTDns.kt:73)
       at com.vshots.common.network.dnsoverhttps.CTDns.lookup(CTDns.kt:37)
       at okhttp3.internal.connection.RouteSelector.resetNextInetSocketAddress(RouteSelector.kt:169)
       at okhttp3.internal.connection.RouteSelector.nextProxy(RouteSelector.kt:131)
       at okhttp3.internal.connection.RouteSelector.next(RouteSelector.kt:73)
       at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.kt:205)
       at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.kt:106)
       at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.kt:74)
       at okhttp3.internal.connection.RealCall.initExchange$okhttp(RealCall.kt:255)
       at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.kt:32)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.kt:95)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.kt:83)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.kt:76)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.chengtong.im.sdk.core.IMWebSocket$httpClient$2.invoke$lambda$2$lambda$1(IMWebSocket.kt:92)
       at com.chengtong.im.sdk.core.IMWebSocket$httpClient$2.$r8$lambda$PCoulHUsjM2OiO53Phkkl1drjfY()
       at com.chengtong.im.sdk.core.IMWebSocket$httpClient$2$$ExternalSyntheticLambda1.intercept(D8$$SyntheticClass)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at com.chengtong.im.sdk.core.IMWebSocket$httpClient$2.invoke$lambda$2$lambda$0(IMWebSocket.kt:87)
       at com.chengtong.im.sdk.core.IMWebSocket$httpClient$2.$r8$lambda$8Gwjjo0Y3H5BcTCeEcEaNKajC0s()
       at com.chengtong.im.sdk.core.IMWebSocket$httpClient$2$$ExternalSyntheticLambda0.intercept(D8$$SyntheticClass)
       at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.kt:109)
       at okhttp3.internal.connection.RealCall.getResponseWithInterceptorChain$okhttp(RealCall.kt:201)
       at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:517)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:920)

**Comment by yuvalgnessin-qz** [comment]
We ran into this as well, I opened a new issue here: https://github.com/square/okhttp/issues/8534
