### ISSUE TITLE
Exchange.writeRequestHeaders  java.lang.NullPinterException:null

### ISSUE THREAD

**Issue by thp521** [square/okhttp#8491]
Version: okhttp:3.14.9
Phenomenon: All requests to access third-party services suddenly throw NPE. Most services return to normal after a few seconds, but only one third-party service returns to normal after half an hour. This situation occurred twice, once in April and lasted for two hours. Once in July and lasted for half an hour.
Exception stack information:
java.lang.NullPinterException:null
at okio.Segment.push(Segment.java:111)
at okio.Buffer.writableSegment(Buffer.java:1307)
at okio.Buffer.writeUtf8(Buffer.java:980)
at okio.Buffer.writeUtf8(Buffer.java:961)
at okio.RealBufferedSink.writeUtf8(RealBufferSink.java:53)
at okhhtp3.internal.http1.HttpExchangeCodec.writeRequest(Http1ExchangeCodec.java:196)
at okhhtp3.internal.http1.HttpExchangeCodec.writeRequestHeaders(Http1ExchangeCodec.java:141)
at okhhtp3.internal.connection.Exchange.writeRequestHeaders(Exchange.java:72)
at okhhtp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:43)
at okhhtp3.internal.http.RealInterceptorChain.procceed(RealInterceptorChain.java:142)
at okhhtp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:43)
at okhhtp3.internal.http.RealInterceptorChain.procceed(RealInterceptorChain.java:142)
at okhhtp3.internal.http.RealInterceptorChain.procceed(RealInterceptorChain.java:117)
at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142)
at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117)
at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229)
at okhttp3.RealCall.execute(RealCall.java:81)

Please help me solve this problem, thank you

**Comment by yschimke** [comment]
Version 3 is not actively maintained or supported
