### ISSUE TITLE
okhttp sse not support server response content-type:application/x-ndjson

### ISSUE THREAD

**Issue by MABIY** [square/okhttp#8510]
okhttp version: 4.9.3
okhttp sse version: 4.9.3
```java
java.lang.IllegalStateException: Invalid content-type: application/x-ndjson
	at okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.kt:60) ~[okhttp-sse-4.9.3.jar:na]
	at okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.kt:46) ~[okhttp-sse-4.9.3.jar:na]
	at okhttp3.internal.connection.RealCall$AsyncCall.run(RealCall.kt:519) ~[okhttp-4.9.3.jar:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
```
![image](https://github.com/user-attachments/assets/178668e0-997a-4fe7-9dc2-ebc08fd4e6de)

**Comment by MABIY** [comment]
this should a feature request, l'm add a feature request.

**Comment by JakeWharton** [comment]
Note that you can work around this today with a network interceptor that rewrites the content type to the standard SSE media type.

**Comment by JakeWharton** [comment]
I just looked up what ndjson is. It is NOT a compatible SSE format which uses double-newline delimited chunks and `data: `-prefixed lines.

You will have to write your own parser for this, although our SSE one will server as a good example to learn from.

**Comment by MABIY** [comment]
> I just looked up what ndjson is. It is NOT a compatible SSE format which uses double-newline delimited chunks and `data: `-prefixed lines.
> 
> You will have to write your own parser for this, although our SSE one will server as a good example to learn from.

Thank you for taking the time to think about it.

ndjson is some differnt of you think,you can look https://github.com/ndjson/ndjson-spec?tab=readme-ov-file
