### ISSUE TITLE
NoClassDefFoundError _UtilJvmKt

### ISSUE THREAD

**Issue by svenhaag** [square/okhttp#8552]
v5.0.0-alpha.13 and 5.0.0-alpha.14. 5.0.0-alpha.12 works fine.

Calling this in a Junit5 Extension:
```
public class MockWebServerExtension implements TestInstancePostProcessor, AfterEachCallback {
@Override
    public void postProcessTestInstance(Object testInstance, ExtensionContext context) throws Exception {
        MockWebServer mockWebServer = new MockWebServer();
        // ...
    }
}
```

I get this error:
```
java.lang.NoClassDefFoundError: okhttp3/internal/_UtilJvmKt
	at mockwebserver3.MockWebServer.<init>(MockWebServer.kt:105)
	at okhttp3.mockwebserver.MockWebServer.<init>(MockWebServer.kt:34)
	at com.example.MockWebServerExtension.postProcessTestInstance(MockWebServerExtension.java:36)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.forEachRemaining(StreamSpliterators.java:310)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:735)
	at java.base/java.util.stream.Streams$ConcatSpliterator.forEachRemaining(Streams.java:734)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.Optional.orElseGet(Optional.java:364)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
Caused by: java.lang.ClassNotFoundException: okhttp3.internal._UtilJvmKt
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:525)
	... 15 more
```

The test class being:
```
@EnableAutoWeld
@ExtendWith(MockWebServerExtension.class)
@AddExtensions(ResteasyCdiExtension.class)
@ActivateScopes(SessionScoped.class)
class TestClass {}
```

**Comment by yschimke** [comment]
Likely you are mixing different versions of okhttp, can you check all versions are lined up.

**Comment by svenhaag** [comment]
![Image](https://github.com/user-attachments/assets/8db7f64b-b8dd-4392-8a09-3c8880a8736a)

**Comment by yschimke** [comment]
Use mockwebserver 5.0.x with okhttp 4.12 wont work.
