### ISSUE TITLE
incorrect treatment of multiple informational HTTP responses

### ISSUE THREAD

**Issue by reschke** [square/okhttp#8568]
NOTE: this is not the same as <https://github.com/square/okhttp/issues/7440>.

From <https://github.com/greenbytes/java-http-1xx-tests>:

~~~
mvn clean install -Dtest=OkHttpClientTests
~~~

Responses that contain *multiple* 1xx messages are treated incorrectly:

~~~
[ERROR] testOkHttpClient104_100(org.greenbytes.http.test1xx.OkHttpClientTests)  Time elapsed: 0.459 s  <<< ERROR!
java.lang.IllegalStateException: state: 3
        at org.greenbytes.http.test1xx.OkHttpClientTests.testOkHttpClient(OkHttpClientTests.java:20)
        at org.greenbytes.http.test1xx.OkHttpClientTests.testOkHttpClient104_100(OkHttpClientTests.java:63)

[ERROR] testOkHttpClient104_2(org.greenbytes.http.test1xx.OkHttpClientTests)  Time elapsed: 0.006 s  <<< ERROR!
java.lang.IllegalStateException: state: 3
        at org.greenbytes.http.test1xx.OkHttpClientTests.testOkHttpClient(OkHttpClientTests.java:20)
        at org.greenbytes.http.test1xx.OkHttpClientTests.testOkHttpClient104_2(OkHttpClientTests.java:58)
~~~

**Comment by yschimke** [comment]
Thanks for the great repro.

**Comment by reschke** [comment]
It's my pleasure :-)

**Comment by yschimke** [comment]
I put together a test and minimal fix. It feels too easy, so I'd love a review.
