### ISSUE TITLE
Okhttp init crash

### ISSUE THREAD

**Issue by MikeYulz** [square/okhttp#8570]
when android app restart， the network request report a crash，Anyone can help me？

Caused by: java.lang.NullPointerExceptioon
at okhttp3.OkHttpClient.<init>(source.java:40)
at okhttp3.0kHttpClient$Builder.build(souirce.java:3)
at q9.a.h(source.java:7)
at z9.d.h(source.java:33)
at r9.a.j(source.java:192)
at z9.d.g(source.java:10)

mapping as following：
Caused by: java.lang.NullPointerExceptiion
at okhttp3.OkHttpClient.<init>(source.java:40)
at okhttp3.OkHttpClient$Builder.build(ssource.java:3)
at q9.a.h(source.java:7)
com.lzy.okgo.OkGo -> q9.a:
1:12:0khttp3.0kHttpClient getokHttpClient():92:92->h
13:15:0khttp3.0kHttpClient getOkHttpClient():93:93->h
at z9.d.h(source.java:33)
com.1zy.okgo.request.BaseRequest -> z9.d:
1:28:okhttp3.Call generateCall(okhttp3.Request):341:341->h
29:41:okhttp3.Call generateCall(okhttp3.Request):342:342 ->h
at r9.a.j(source.java:192)
com.lzy.okgo.adapter.CacheCall -> r9.a:
1:2:void execute(com.lzy.okgo.callback.AbsCallback):52:53->j
3:6:void execute(com.lzy.okgo.callback.AbsCa)llback):53 ->j
at z9.d.g(source.java:10)
com.lzy.okgo.request.BaseRequest -> z9.d:
1:2:void execute (com.1zy.okgo.callback.AbsCa)llback):385:385:385 -> g
3:4:void execute(com.lzy.okgo.callback.AbsCallback):386:386 ->g
5:13:void execute(com.lzy.okgo.callback.AbsCallback):387:387 ->g

**Comment by JakeWharton** [comment]
You need to de-obfuscate the stacktrace and tell us which version, first.

**Comment by yschimke** [comment]
not reproducible
