### ISSUE TITLE
NPE in internal.idn.IdnaMappingTable.findRangesOffset

### ISSUE THREAD

**Issue by ber4444** [square/okhttp#8574]
```
       Fatal Exception: java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
       at okhttp3.internal.idn.IdnaMappingTable.findRangesOffset(IdnaMappingTable.java:242)
       at okhttp3.internal.idn.IdnaMappingTable.map(IdnaMappingTable.java:130)
       at okhttp3.internal._HostnamesCommonKt.idnToAscii(-HostnamesCommon.kt:322)
       at okhttp3.internal._HostnamesCommonKt.toCanonicalHost(-HostnamesCommon.kt:307)
       at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.java:1448)
       at okhttp3.HttpUrl$Companion.get(HttpUrl.java:1744)
       at okhttp3.HttpUrl$Companion.parse(HttpUrl.java:1754)
       at okhttp3.HttpUrl.parse(HttpUrl.java:34)
       at zipkin2.reporter.okhttp3.InternalOkHttpSender.newEndpoint(InternalOkHttpSender.java:61)
       at zipkin2.reporter.okhttp3.InternalOkHttpSender.newEndpoint(InternalOkHttpSender.java:36)
```
seeing the above in some Samsung devices in Crashlytics

we are using '5.0.0-alpha.14'... by the way, would love to see a new alpha, it's been 7 months already

**Comment by ber4444** [comment]
https://github.com/square/okhttp/blob/02d69bf883c47905d0ad3fd9d2ad75b8ede75bb9/okhttp/src/main/kotlin/okhttp3/internal/idn/IdnaMappingTable.kt#L242
tries to read an index from a `String` that obviously doesn't exist, easy fix would be to add a sanity test before getting the index

getting a NPE instead of an `IndexOutOfBoundsException` might be an OEM issue

**Comment by yschimke** [comment]
I don't think that's the right fix. It's hiding a bug in the logic, the VM/compiler, or the build corrupting the file. We can make this code tolerant of corruption, but it's hiding the root problem.

```
    val rangesPosition = sections.read14BitInt(sectionsIndex + 2)

    val rangesLimit =
      when {
        sectionsIndex + 4 < sections.length -> sections.read14BitInt(sectionsIndex + 6)
        else -> ranges.length / 4
      }
```

For that to be out of range, it must be one of

1. Getting a bad position or limit from sections
2. Some corruption of the data, either on disk or afterwards
3. a logic (okhttp), compilation (agp) or runtime (oem) bug

Regarding why it's reading a char instead of a codepoint, the encoding is explained at the top of the file. But by this point we are really only looking the compare the last 7 bits of the target.

**Comment by yschimke** [comment]
I misread the error. It's even stranger than this.

`ranges` is created here

```
internal val IDNA_MAPPING_TABLE: IdnaMappingTable = IdnaMappingTable(
      sections =
          "\u0000\u0000
      ranges =
          "\u0000x--AP
      mappings =
          "\u0020̈\u0020
    )
```

So there isn't something we can fix. This is set and immutable from creation, before any methods are called.

**Comment by yschimke** [comment]
Can you provide more details about the Samsung devices seeing this error? Are they a particular version? A lot of distinct users? Are they jailbroken?

**Comment by swankjesse** [comment]
I wonder if packing data into a string is upsetting the runtime somehow.

**Comment by ber4444** [comment]
It's occasionally happening on Samsung devices only, Android 14. 
Examples: 
Galaxy S24 Ultra
Galaxy A15 5G

**Comment by yschimke** [comment]
Anything else common like region?

**Comment by Toubap** [comment]
Hello
Recently happening to me as well.

<img width="540" alt="Image" src="https://github.com/user-attachments/assets/b991b930-c2c9-42c1-a180-a6e18d8dcae4" />

It started when I added a widget to the app. Could be related to the receiver ACTION_APPWIDGET_UPDATE that starts the app at device boot. Well I face other issues related to that, as it triggers some code without Application.onCreate being launched

**Comment by yschimke** [comment]
If 9% of the errors are from Transsion, I'm more suspect that there is something fishy with those devices.

**Comment by piyushgoyal123** [comment]
Do we have any fix for this? Happening to me as well.

**Comment by yogurtearl** [comment]
Using kotlin `2.1.21` and R8 `8.10.21` and compile SDK 35

I saw in production on Android 15 using okhttp `5.0.0-alpha.16` and so far **_only on Pixel devices_**. 

```kotlin
object MyConstants {
         MY_URL = "https://myurl.example.com" 
}
```

and then we have a call to `MyConstants.MY_URL.toHttpUrl()` 

The code is minified using a recent version of R8 (`8.10.21`) and works fine 99.99% of the time. 

This is a very rare crash... but also surprising in that it is parsing a constant. 

Stack trace is a bit different: 

```
          Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
       at okhttp3.internal.idn.IdnaMappingTable.findRangesOffset(IdnaMappingTable.java:242)
       at okhttp3.internal.idn.IdnaMappingTable.map(IdnaMappingTable.java:130)
       at okhttp3.internal._HostnamesCommonKt.idnToAscii(-HostnamesCommon.kt:322)
       at okhttp3.internal._HostnamesCommonKt.toCanonicalHost(-HostnamesCommon.kt:307)
       at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.kt:1448)
       at okhttp3.HttpUrl$Companion.get(HttpUrl.kt:1744)
```


As mentioned above, somehow `ranges` is null on this line, but ranges is set to a constant in the constructor? 

`val b0 = ranges[entryIndex].code`


It happens right on app startup in the first `activity.onCreate`

**Comment by yogurtearl** [comment]
Perhaps https://github.com/romainguy/kotlin-explorer could shed light on this?

**Comment by michael-winkler** [comment]
We also received a crash log.

```
Fatal Exception: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.mugler.SitemanTicketSystem/com.mugler.sitemanTicketSystem.MainActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4164)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)

Caused by java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
       at okhttp3.internal.idn.IdnaMappingTable.findRangesOffset(IdnaMappingTable.java:242)
       at okhttp3.internal.idn.IdnaMappingTable.map(IdnaMappingTable.java:130)
       at okhttp3.internal._HostnamesCommonKt.idnToAscii(-HostnamesCommon.kt:321)
       at okhttp3.internal._HostnamesCommonKt.toCanonicalHost(-HostnamesCommon.kt:306)
       at okhttp3.HttpUrl$Builder.parse$okhttp(HttpUrl.java:1442)
       at okhttp3.HttpUrl$Companion.get(HttpUrl.java:1734)
       at okhttp3.HttpUrl.get(HttpUrl.java:39)
       at retrofit2.Retrofit$Builder.baseUrl(Retrofit.java:554)
       at com.mugler.sitemanTicketSystem.api.Retrofit.retrofitBuilder(Retrofit.kt:48)
       at com.mugler.sitemanTicketSystem.api.Retrofit.init(Retrofit.kt:31)
       at com.mugler.sitemanTicketSystem.api.Retrofit.init$default(Retrofit.kt:24)
       at com.mugler.sitemanTicketSystem.api.ApiServices.getLoginSimulationApi(ApiServices.kt:65)
       at com.mugler.sitemanTicketSystem.utils.ValidationUtil$Companion.sitemanLoginValide(ValidationUtil.java:26)
       at com.mugler.sitemanTicketSystem.MainActivity.validate(MainActivity.kt:729)
       at com.mugler.sitemanTicketSystem.MainActivity.preInitialize(MainActivity.kt:309)
       at com.mugler.sitemanTicketSystem.MainActivity.onCreate(MainActivity.kt:197)
       at android.app.Activity.performCreate(Activity.java:8975)
       at android.app.Activity.performCreate(Activity.java:8944)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1456)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:4146)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4322)
       at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:103)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:139)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:96)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2685)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loopOnce(Looper.java:230)
       at android.os.Looper.loop(Looper.java:319)
       at android.app.ActivityThread.main(ActivityThread.java:8919)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:578)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

Samsung Galaxy A54 5G Android 14

And our implementations:

```
implementation("com.squareup.retrofit2:retrofit:3.0.0")
implementation("com.squareup.retrofit2:converter-gson:3.0.0")
implementation("com.squareup.retrofit2:converter-scalars:3.0.0")
implementation("com.squareup.okhttp3:okhttp:5.1.0")
```

**Comment by gmazzo** [comment]
Same here:
<img width="568" height="345" alt="Image" src="https://github.com/user-attachments/assets/26b74910-fc66-43d7-a003-45f2f6dad5fc" />


It's very strange, since it does not to be fully related to R8. We forced the logic to reach that piece of code in R8 minified code, and it was not failing. But we still have some error reports in production 🤔

**Comment by SimonMarquis** [comment]
Same here since we upgraded to V5.
Though it appears to only happen on Xiaomi devices, in background mode, during the app process initialisation (the stra traces all show Dagger graph initialisation)

<img width="1119" height="468" alt="Image" src="https://github.com/user-attachments/assets/2fc8f45f-080f-46bc-91b8-8cf085e14fc8" />

**Comment by yschimke** [comment]
Probably worth filing a bug with the manufacturer then

**Comment by michael-winkler** [comment]
As mentioned in [this GitHub comment](https://github.com/square/okhttp/issues/8574#issuecomment-2480516950):

```kotlin
internal val IDNA_MAPPING_TABLE: IdnaMappingTable = IdnaMappingTable(
    sections = "\u0000\u0000",
    ranges = "\u0000x--AP",
    mappings = "\u0020̈\u0020"
)
```

Is it possible that R8 or ProGuard is removing this field?. Adding a simple `@Keep` annotation might help:

```kotlin
@Keep
internal val IDNA_MAPPING_TABLE: IdnaMappingTable = IdnaMappingTable(
    sections = "\u0000\u0000",
    ranges = "\u0000x--AP",
    mappings = "\u0020̈\u0020"
)
```

@yschimke

**Comment by yschimke** [comment]
@michael-winkler I mean if it fixes it, sure. But doesn't it need to be non-null to get this far?

```
aused by java.lang.NullPointerException: Attempt to invoke virtual method 'char java.lang.String.charAt(int)' on a null object reference
       at okhttp3.internal.idn.IdnaMappingTable.findRangesOffset(IdnaMappingTable.java:242)
       at okhttp3.internal.idn.IdnaMappingTable.map(IdnaMappingTable.java:130)
```

**Comment by michael-winkler** [comment]
The error indicates that `ranges` 

````
val b0 = ranges[entryIndex].code
````

was null at that point in time.
This raises the question of how that’s possible, since ranges is defined as a non-null val of type String in the constructor.

````
internal class IdnaMappingTable internal constructor(
  val sections: String,
  val ranges: String,
  val mappings: String,
)
````

Could this actually be an R8 or ProGuard issue?
Technically, ranges and the other fields are correctly defined, but at runtime they appear to be missing — for whatever reason.
This suggests that they might have been stripped or optimized away, despite being used implicitly.

**Comment by yschimke** [comment]
Could you check the release APK and see what is in there?

**Comment by gmazzo** [comment]
> Could you check the release APK and see what is in there?

<img width="646" height="246" alt="Image" src="https://github.com/user-attachments/assets/73819bcb-948b-4d3b-b26a-380848c46ca2" />

###### `IdnaMappingTable.kt`
```
.class public final Lokhttp3/internal/idn/IdnaMappingTable;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation runtime Lkotlin/Metadata;
    d1 = {
        "\u0000\n\n\u0002\u0018\u0002\n\u0002\u0010\u0000\n\u0000\u0008\u0000\u0018\u00002\u00020\u0001\u00a8\u0006\u0002"
    }
    d2 = {
        "Lokhttp3/internal/idn/IdnaMappingTable;",
        "",
        "okhttp"
    }
    k = 0x1
    mv = {
        0x2,
        0x2,
        0x0
    }
    xi = 0x30
.end annotation

```

###### `IdnaMappingTableInstanceKt`
```
.class public final Lokhttp3/internal/idn/IdnaMappingTableInstanceKt;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation runtime Lkotlin/Metadata;
    d1 = {
        "\u0000\u0002\n\u0000\u00a8\u0006\u0000"
    }
    d2 = {
        "okhttp"
    }
    k = 0x2
    mv = {
        0x2,
        0x2,
        0x0
    }
    xi = 0x30
.end annotation


# static fields
.field public static final a:Lokhttp3/internal/idn/IdnaMappingTable;


# direct methods
.method static constructor <clinit>()V
    .registers 1

    .line 1
    new-instance v0, Lokhttp3/internal/idn/IdnaMappingTable;

    .line 2
    .line 3
    invoke-direct {v0}, Ljava/lang/Object;-><init>()V

    .line 4
    .line 5
    .line 6
    sput-object v0, Lokhttp3/internal/idn/IdnaMappingTableInstanceKt;->a:Lokhttp3/internal/idn/IdnaMappingTable;

    .line 7
    .line 8
    return-void
.end method
```

###### `IdnaMappingTableKt`
```
.class public final Lokhttp3/internal/idn/IdnaMappingTableKt;
.super Ljava/lang/Object;
.source "SourceFile"


# annotations
.annotation runtime Lkotlin/Metadata;
    d1 = {
        "\u0000\u0002\n\u0000\u00a8\u0006\u0000"
    }
    d2 = {
        "okhttp"
    }
    k = 0x2
    mv = {
        0x2,
        0x2,
        0x0
    }
    xi = 0x30
.end annotation


# direct methods
.method public static final a(ILjava/lang/String;)I
    .registers 3

    .line 1
    const-string v0, "<this>"

    .line 2
    .line 3
    invoke-static {p1, v0}, Lkotlin/jvm/internal/l;->f(Ljava/lang/Object;Ljava/lang/String;)V

    .line 4
    .line 5
    .line 6
    invoke-virtual {p1, p0}, Ljava/lang/String;->charAt(I)C

    .line 7
    .line 8
    .line 9
    move-result v0

    .line 10
    add-int/lit8 p0, p0, 0x1

    .line 11
    .line 12
    invoke-virtual {p1, p0}, Ljava/lang/String;->charAt(I)C

    .line 13
    .line 14
    .line 15
    move-result p0

    .line 16
    shl-int/lit8 p1, v0, 0x7

    .line 17
    .line 18
    add-int/2addr p1, p0

    .line 19
    return p1
.end method

```

I'm not a bytecode expect, but it seems all fields of `IdnaMappingTable` have been removed?

**Comment by michael-winkler** [comment]
@gmazzo Where have you found that?

<img width="285" height="142" alt="Image" src="https://github.com/user-attachments/assets/ebdeb2c8-27ea-48db-be16-9c278d8c8696" />

That's all I see from the classes.dex

**Edit:**
After I added my mapping I can see more.

```
.class public abstract Lokhttp3/internal/idn/IdnaMappingTableInstanceKt;
.super Ljava/lang/Object;
.source "SourceFile"


# static fields
.field public static final IDNA_MAPPING_TABLE:Lcom/google/android/material/shape/EdgeTreatment;


# direct methods
.method static constructor <clinit>()V
    .registers 2

    new-instance v0, Lcom/google/android/material/shape/EdgeTreatment;

    const/16 v1, 0x1d

    invoke-direct {v0, v1}, Lcom/google/android/material/shape/EdgeTreatment;->R3.EdgeTreatment.<init>(I)V

    sput-object v0, Lokhttp3/internal/idn/IdnaMappingTableInstanceKt;->IDNA_MAPPING_TABLE:Lcom/google/android/material/shape/EdgeTreatment;

    return-void
.end method

.method public static final a(ILjava/lang/String;)I
    .registers 3

    invoke-virtual {p1, p0}, Ljava/lang/String;->charAt(I)C

    move-result v0

    add-int/lit8 p0, p0, 0x1

    invoke-virtual {p1, p0}, Ljava/lang/String;->charAt(I)C

    move-result p0

    shl-int/lit8 p1, v0, 0x7

    add-int/2addr p1, p0

    return p1
.end method

```

**Comment by gmazzo** [comment]
> [@gmazzo](https://github.com/gmazzo) Where have you found that?

It's from Android Studio, by inspecting our production minified release bundle. Looking at the specific `classesX.dex`

<img width="523" height="501" alt="Image" src="https://github.com/user-attachments/assets/26c80485-9525-448f-a255-c307defbd034" />

**Comment by michael-winkler** [comment]
Okay. I did not found it in our release apk but inside our debug apk.
I wonder why I can not found it inside the release apk.

Only difference for our build are R8/pro guard is enabled for release only.

**Comment by yschimke** [comment]
My observation, is that release builds do a lot of mangling, but it's keeping what it needs.

See https://github.com/square/okhttp/pull/8994

I suspect OkHttp is somehow triggering an issue with some different build setup you have. But I don't think the fix is in OkHttp, unless we can make a clean reproduction. I don't want to just sprinkle Keep rules unless we understand why it's being stripped. 

I'd suggest specifying the keep rules in your own build for now.

**Comment by yschimke** [comment]
Probably an unpopular call, but I'm going to close this as I think the PR demonstrates this is working.

I'm very happy to continue discussing, but I don't think it's a bug for OkHttp to fix. I'll re-open in a second, with a repro.

**Comment by rolgalan** [comment]
Hi @yschimke,

Thanks for providing this test in #8994, with that I've been able to reproduce the issue. The problem actually happens when the `proguard-android-optimize.txt` file from AGP is added instead of the `proguard-android.txt` currently used in the test app. The usage of the optimized set of rules is [recommended](https://developer.android.com/topic/performance/app-optimization/enable-app-optimization) by Android to improve the application performance.

`setProguardFiles(listOf(getDefaultProguardFile("proguard-android-optimize.txt"), "proguard-rules.pro"))`

To be honest, the test is not failing 🤷 but you can see the `IdnaMappingTableInstanceKt` actually being stripped out from the final apk. You can validate this by opening the .dex from the apk as explained in above comments. See the screenshots:

| normal | optimized |
| ------------- |-------------|
| ![normal][ref-normal-1] | ![opt][ref-opt-1] |

[ref-normal-1]: https://github.com/user-attachments/assets/e38825ad-b612-4069-bce2-117d50801d0d
[ref-opt-1]: https://github.com/user-attachments/assets/b652730e-103d-4d2b-9bce-e87d99be494b


Also, if you add the `whyareyoukeeping` rule:
```
-whyareyoukeeping class okhttp3.internal.idn.IdnaMappingTableInstanceKt {
  *;
}
```

The output with the `proguard-android-optimize.txt` is that nothing is found to keep it:

```
Nothing is keeping okhttp3.internal.idn.IdnaMappingTable okhttp3.internal.idn.IdnaMappingTableInstanceKt.getIDNA_MAPPING_TABLE()
```

Output with the  `proguard-android.txt`:
```
okhttp3.internal.idn.IdnaMappingTable okhttp3.internal.idn.IdnaMappingTableInstanceKt.getIDNA_MAPPING_TABLE()
|- is invoked from:
|  java.lang.String okhttp3.internal._HostnamesCommonKt.idnToAscii(java.lang.String)
|- is invoked from:
|  java.lang.String okhttp3.internal._HostnamesCommonKt.toCanonicalHost(java.lang.String)
|- is invoked from:
|  okhttp3.HttpUrl$Builder okhttp3.HttpUrl$Builder.parse$okhttp_release(okhttp3.HttpUrl,java.lang.String)
|- is invoked from:
|  okhttp3.HttpUrl okhttp3.HttpUrl$Companion.get(java.lang.String)
|- is invoked from:
|  void okhttp.android.testapp.MainActivity.onCreate(android.os.Bundle)
|- is defined in library method overridden by:
|  okhttp.android.testapp.MainActivity
|- is referenced in keep rule:
|  ./android-test-app/build/intermediates/aapt_proguard_file/release/processReleaseResources/aapt_rules.txt:5:1
```

With the above information, would you reconsider opening this issue again and potentially adding a keep rule for the IdnaMappingTableInstance in your [consumerProguardFile](https://github.com/yschimke/okhttp/blob/5b2a1e139e9721455990a1b3d1462be47d27c599/okhttp/okhttp3.pro) so the host apps don't need to add custom proguard rules to use this library?

**Comment by JakeWharton** [comment]
I think you should file a bug against R8 because it is doing something incorrect with our code. Keep rules are needed for things accessed reflectively–not for normal references like this.

You can embed a keep rule in your application to work around the problem in the mean time, and then remove it once R8 is fixed (and released). It's unclear when we would be able to remove such a keep rule if we were to add it. After all, we don't know the AGP/R8 versions of our consumers.

**Comment by yschimke** [comment]
I'll update the test we already have to include those rules.  Thanks for finding that.

**Comment by yschimke** [comment]
Test functionality is broken with release builds with the optimised config. So that won't work without a lot of special casing. Including `okhttp3.**`

The first failure is androidx.tracing.Trace from the Android test runner (maybe this https://issuetracker.google.com/issues/269319902?)

**Comment by yschimke** [comment]
Running the test activity does work. That's with IdnaMappingTableInstanceKt stripped.

If I add the following to the activity, it keeps those types automatically.

```
    println("https://☃.net/robots.txt".toHttpUrl().host)
```

So at least with AGP 8.12.0 and 8.13.0-alpha1 it seems to correctly keep IdnaMappingTable when needed, and strip when not. so I don't even have a repro to raise for your issue.

**Comment by rolgalan** [comment]
> I think you should file a bug against R8 because it is doing something incorrect with our code. Keep rules are needed for things accessed reflectively–not for normal references like this.

Fair @JakeWharton, [reported to R8 in the Google Issue tracker](https://issuetracker.google.com/issues/436756681). Please anyone arriving here with the same issue upvote/comment 🙏 .

While I agree with you that this is a R8 general problem, we are not using any particular customization but relying on the official recommended ones by Android. This would be the case for most of your Android users, so it could be worth sharing this proactively with your userbase (for example in the changelog for 5.0.0, recommending to add the specific keep rule there) to prevent any issues upfront. I am pretty sure this has not get bigger impact yet because there is probably still a majority of people not updated to 5.0 yet.

**Comment by yschimke** [comment]
Yep, agreed.

My concern is we can't reproduce cleanly. So what's the advice? 

`-keep okhttp3.** { *; }`

And it seems rare for now. Not widespread.

**Comment by yogurtearl** [comment]
Maybe this? 

```kotlin
-keep class okhttp3.internal.idn.IdnaMappingTableKt { *; }
-keep class okhttp3.internal.idn.IdnaMappingTableInstanceKt { *; }
-keep class okhttp3.internal.idn.IdnaMappingTable { *; }
```

**Comment by yschimke** [comment]
The linked R8 bug shows that only stops it being optimised and inlined. It isn't causing the problem.

So we haven't reproduced that this is what is going on. Or that config fixes it in the wild.

Even if we can't root cause it, we should add this if we can see production failures are 0 in an updated version. Does anyone have metrics to show that?

Currently the opposite 

> It's very strange, since it does not to be fully related to R8. We forced the logic to reach that piece of code in R8 minified code, and it was not failing. But we still have some error reports in production 🤔

**Comment by rolgalan** [comment]
> The linked R8 bug shows that only stops it being optimised and inlined. It isn't causing the problem.
> 
> So we haven't reproduced that this is what is going on. Or that config fixes it in the wild.
> 


Indeed, the R8 team already looked into this and they found out that the missing strings are actually moved to somewhere else, but are present in the apk. Therefore our clue on R8 stripping out these strings was misleading 🙏. At this point there is no evidence proving that R8 is the actual reason.

We are back to the starting point... Might this be something related to the devices then? We have 77% Xiaomi, 16% Samsung, but also Oppo, Motorola and others. None rooted. With Android 15 to 12. So no clear pattern 🤷. Getting similar reports on Crashlytics/PlayStore. 

> Even if we can't root cause it, we should add this if we can see production failures are 0 in an updated version. Does anyone have metrics to show that?

We are already in the process to launch a new release with a keep rule for the _IdnaMappingTableInstanceKt_, but at this point I do not expect this to mitigate the issue (unless there is other optimization messing it up somehow, but quite unlikely at this point). In any case I will come back next week to report if it actually changes anything. Otherwise we will rollback to okhttp 4.x as the impact is quite high for our customer base (>0.1% crashed users).

**Comment by yschimke** [comment]
I do wonder whether it's regional. Perhaps certain domains causing the failure?

**Comment by rolgalan** [comment]
I confirm that this issue was completely resolved for us by adding the following proguard rules:

```
keep class okhttp3.internal.idn.IdnaMappingTable { *; }
keep class okhttp3.internal.idn.IdnaMappingTableInstanceKt{ *; }
```

We had hundreds of weekly crashes in production due to this and we don't have them anymore for the last couple of weeks since this was released.

It looks to me that R8 might be introducing some other optimization that leads to this crash. It does not happen every time, so it might be some race condition or something in very specific execution paths. Unfortunately we cannot provide any reproducible example as we've not been to reproduce this crash locally. But it's definitively solved by adding the rules, so there should be something related to how R8 changes the code. 

https://issuetracker.google.com/issues/436756681

**Comment by swankjesse** [comment]
@rolgalan wow, that’s quite helpful to know.

**Comment by yschimke** [comment]
We should add this into our proguard, or use Keep annotations.

**Comment by JakeWharton** [comment]
I don't really think we should do anything. The open issue can serve as documentation until R8 either locates their optimization bug or determines the problem with the VM and puts in a workaround.

**Comment by yschimke** [comment]
OK, well the R8 issue is open again. So maybe that's the path forward.

I'm ok with workaround R8 bugs even it reduces pain. But we can see if that ticket comes to a resolution first. or we get more reports.

**Comment by melihakalan** [comment]
Even though Google does not seem to be caring this bug, everyone using okhttp with r8 enabled having this issue even if they are not aware. The problem is that you don't always (or never) get a stack trace with a NPE or anything related to okhttp. I'm glad that I've found issue this by chance while looking for a mysterious SIGSEGV issue which brought me here. In my case, a SIGSEGV fault was originating from an Ad Network SDK using okhttp. Since you can get nearly zero clue from obfuscated vital stack traces, everyone seem to be counting that as a random native crash...

**Comment by emartynov** [comment]
We also got it. So adding R8 configuration lines is not fixing it?
