### ISSUE TITLE
okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR

### ISSUE THREAD

**Issue by EpariNigam** [square/okhttp#8620]
I don't know, what lead to this. But, it is crashing the app with below stack trace.

 okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
	at com.microsoft.clarity.sq1.k.h(SourceFile:201)
	at com.microsoft.clarity.pq1.c.d(SourceFile:3)
	at com.microsoft.clarity.qq1.b.intercept(SourceFile:317)
	at com.microsoft.clarity.qq1.g.a(SourceFile:122)
	at com.microsoft.clarity.pq1.a.intercept(SourceFile:118)
	at com.microsoft.clarity.qq1.g.a(SourceFile:122)
	at com.microsoft.clarity.nq1.a.intercept(SourceFile:163)
	at com.microsoft.clarity.qq1.g.a(SourceFile:122)
	at com.microsoft.clarity.qq1.a.intercept(SourceFile:225)
	at com.microsoft.clarity.qq1.g.a(SourceFile:122)
	at com.microsoft.clarity.qq1.i.intercept(SourceFile:156)
	at com.microsoft.clarity.qq1.g.a(SourceFile:122)
	at com.microsoft.clarity.zf.a.intercept(SourceFile:76)
	at com.microsoft.clarity.qq1.g.a(SourceFile:122)
	at com.microsoft.clarity.zf.c.intercept(SourceFile:10)
	at com.microsoft.clarity.qq1.g.a(SourceFile:122)
	at okhttp3.logging.HttpLoggingInterceptor.intercept(SourceFile:479)
	at com.microsoft.clarity.qq1.g.a(SourceFile:122)
	at com.microsoft.clarity.pq1.e.e(SourceFile:100)
	at com.microsoft.clarity.pq1.e$a.run(SourceFile:48)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
		... 23 more
	Suppressed: okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
		... 23 more
	Suppressed: okhttp3.internal.http2.StreamResetException: stream was reset: INTERNAL_ERROR
		... 23 more
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [n1{Cancelling}@dfbef97, Dispatchers.Main.immediate]

**Comment by EpariNigam** [comment]
The place where we are doing RPC calls, we have added try catch blocks to catch exception. But, this seems didn't caught, any help would be appreciated.

**Comment by EpariNigam** [comment]
Using latest version 4.12.0 in the project.

**Comment by yschimke** [comment]
You should raise this with the server maintainers.

https://datatracker.ietf.org/doc/html/rfc9113#INTERNAL_ERROR

> INTERNAL_ERROR (0x02): The endpoint encountered an unexpected internal error.

**Comment by EpariNigam** [comment]
@yschimke My question was around, how to handle this crash from client side?

**Comment by EpariNigam** [comment]
It is happening in httplogging interceptor.

Can you tell me how to handle this?

**Comment by yschimke** [comment]
httplogging interceptor is part of the call chain, so this is expected. 

See https://square.github.io/okhttp/features/interceptors/

If you need more help, consider a site like stackoverflow.  We can't provide 1:1 support for users.
