### ISSUE TITLE
SocketTimeoutException with OkHttp 1.6

### ISSUE THREAD

**Issue by fwang** [square/okhttp#903]
Hi, I've been getting SocketTimeoutException intermittently. I don't think this is an internet connection issue because:
- the error can also be observed when making api calls to local test environment
- making the same api call through the Android browser (while getting SocketTimeoutException in the app) always works and returns within 100ms 

Setup:

```
retrofit 1.5.1 + okhttp 1.6.0

the client is created through retrofit's code:

OkHttpClient client = new OkHttpClient();
client.setConnectTimeout(Defaults.CONNECT_TIMEOUT_MILLIS, TimeUnit.MILLISECONDS);
client.setReadTimeout(Defaults.READ_TIMEOUT_MILLIS, TimeUnit.MILLISECONDS);
```

Error:

```
retrofit.RetrofitError:
java.net.SocketTimeoutException: failed to connect to api.xx.com/50.18.xx.xx (port 80) after 15000ms
```

This is my third day debugging the issue. Any insights would be greatly appreciated!

**Comment by xhwSkhizein** [comment]
```
java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:495)
	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
	at com.squareup.okhttp.internal.okio.Okio$2.read(Okio.java:113)
	at com.squareup.okhttp.internal.okio.RealBufferedSource.readUtf8Line(RealBufferedSource.java:89)
	at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:149)
	at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:99)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:595)
	at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.execute(HttpURLConnectionImpl.java:381)
	at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.getResponse(HttpURLConnectionImpl.java:328)
	at com.squareup.okhttp.internal.http.HttpURLConnectionImpl.getResponseCode(HttpURLConnectionImpl.java:493)
	at retrofit.client.UrlConnectionClient.readResponse(UrlConnectionClient.java:73)
	at retrofit.client.UrlConnectionClient.execute(UrlConnectionClient.java:38)
	at retrofit.RestAdapter$RestHandler.invokeRequest(RestAdapter.java:321)
```
I got this when i want to get data from server,but i can post data to server. And as I know, only  Android 4.2.2; Coolpad;  Android 4.2.2; Hasee; can repo it.  @laurentiuonac and @Zhelyazko, have you solved it now ?

**Comment by Zhelyazko** [comment]
It was a server-side issue in my case - tcp_timestamp had to be disabled on the server and everything started working fine.

**Comment by laurentiuonac** [comment]
@xhwSkhizein Same here, disabled tcp_timestamp and everything worked fine.

**Comment by duanhongyi** [comment]
@xhwSkhizein disabled tcp_timestamp but the exception still；Android urlconnection does not have this problem。

java.net.SocketTimeoutException
	at java.net.PlainSocketImpl.read(PlainSocketImpl.java:495)
	at java.net.PlainSocketImpl.access$000(PlainSocketImpl.java:46)
	at java.net.PlainSocketImpl$PlainSocketInputStream.read(PlainSocketImpl.java:240)
	at okio.Okio$2.read(Okio.java:137)
	at okio.AsyncTimeout$2.read(AsyncTimeout.java:211)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:300)
	at okio.RealBufferedSource.indexOf(RealBufferedSource.java:289)
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:196)
	at com.squareup.okhttp.internal.http.HttpConnection.readResponse(HttpConnection.java:190)
	at com.squareup.okhttp.internal.http.HttpTransport.readResponseHeaders(HttpTransport.java:80)
	at com.squareup.okhttp.internal.http.HttpEngine.readNetworkResponse(HttpEngine.java:830)
	at com.squareup.okhttp.internal.http.HttpEngine.access$200(HttpEngine.java:95)
	at com.squareup.okhttp.internal.http.HttpEngine$NetworkInterceptorChain.proceed(HttpEngine.java:823)
	at com.squareup.okhttp.internal.http.HttpEngine.readResponse(HttpEngine.java:684)
	at com.squareup.okhttp.Call.getResponse(Call.java:272)
	at com.squareup.okhttp.Call$ApplicationInterceptorChain.proceed(Call.java:228)
	at com.squareup.okhttp.Call.getResponseWithInterceptorChain(Call.java:199)
	at com.squareup.okhttp.Call.execute(Call.java:79)
	at com.uu.usertesttool.connection.NetToJavaRequest.requestServer(NetToJavaRequest.java:27)
	at com.uu.usertesttool.connection.ConnectionTest.doOwnTest(ConnectionTest.java:23)
	at com.uu.usertesttool.MainTest.doTest(MainTest.java:52)
	at com.uu.usertesttool.MainActivity$2$1.run(MainActivity.java:85)
	at java.lang.Thread.run(Thread.java:838)

**Comment by lzyzsd** [comment]
I have the same problem with @duanhongyi , UrlConnection does not throw Timeout exception while okhttp does.

**Comment by duanhongyi** [comment]
@lzyzsd  disable jit

see this:
https://github.com/square/okhttp/issues/1518

**Comment by gkarpiak** [comment]
Had the same issue and in short fixed it by rebooting my instance/server, see here http://stackoverflow.com/a/33409139/1317086

However, it's still very strange that the issue happened and actually experienced by some developers and mostly on Android devices.

By the way, OkHttp, as far as I know, is now used by stock Android out of the box (the only difference is version which is used)
